tailscale/tailscale

go.mod
go.sum

go.mod: update wireguard-go

---

util/set/set.go
util/set/set_test.go

util/set: make Clone a method

---

cmd/k8s-operator/proxy.go

Use Rewrite instead of Director as per the Go docs for the ReverseProxy.
Fixes tailscale/corp#15526

cmd/k8s-operator: use rewrite instead of director in ReverseProxy

---

ipn/ipnlocal/local.go

ipn/ipnlocal: fix small typo

---

hostinfo/hostinfo.go

hostinfo: fix a couple of logic simplification lints

---

cmd/tailscaled/tailscaled_windows.go

In corp PR #14970 I updated the installer to set a security mitigation that always forces system32 to the front of the Windows dynamic linker's search path.
Unfortunately there are other products out there that, partying like it's 1995, drop their own, older version of wintun.dll into system32. Since we look there first, we end up loading that old version.
We can fix this by preloading wintun using a fully-qualified path. When wintun-go then loads wintun, the dynamic linker will hand it the module that was previously loaded by us.
Fixes #10023, #10025, #10052

cmd/tailscaled: pre-load wintun.dll using a fully-qualified path

---

ipn/localapi/localapi.go
ipn/localapi/localapi_test.go

Clients optionally request private key filtering. If they don't, we should require Write access for the user.
Updates https://github.com/tailscale/corp/issues/15506

ipn/localapi: require Write access on /watch-ipn-bus with private keys

---

ipn/ipnlocal/local.go

ipn/ipnlocal: include web client port in setTCPPortsIntercepted

---

clientupdate/clientupdate.go
clientupdate/clientupdate_test.go

In case there's a wild symlink in one of the target paths, we don't want to accidentally delete too much. Limit `cleanupOldDownloads` to deleting individual files only.
Updates https://github.com/tailscale/tailscale/issues/10082

clientupdate: do not recursively delete dirs in cleanupOldDownloads

---

go.mod
go.sum

There will certainly be more changes, probably even later today, but I'd like to go ahead and pull in what we've got.

go.mod: update web-client-prebuilt

---

cmd/tailscale/cli/web.go

After running `tailscale web`, only disable the user pref if it was not already previously set.

cmd/tailscale: respect existing web client pref

---

derp/derphttp/derphttp_test.go
derp/derphttp/mesh_client.go

3d7fb6c21d dropped the explicit called to (*Client).connect when its (*Client).WatchConnectionChanges got removed+refactored.
This puts it back, but in RunWatchConnectionLoop, before the call to the (*Client).ServerPublicKey accessor, which is documented to return the zero value (which is what broke us) on an unconnected connection.
Plus some tests.
Fixes tailscale/corp#15604

derp/derphttp: fix derptrack fix

---

util/syspolicy/policy_keys.go

syspolicy: add Allow LAN Access visibility key

---

util/winutil/winutil_windows.go

To safely request and drop privileges, runtime.Lock/UnlockOSThread and
windows.Impersonate/RevertToSelf should be called. Add these calls to
winutil.EnableCurrentThreadPrivilege so that callers don't need to worry
about it.
Updates https://github.com/tailscale/corp/issues/15488

util/winutil: simplify dropping privileges after use 

---

client/web/assets.go
client/web/src/components/app.tsx
client/web/src/components/views/management-client-view.tsx
client/web/src/icons/arrow-right.svg
client/web/src/icons/chevron-down.svg
client/web/src/index.css

Hooks up more of the home page UI.

client/web: build out client home page

---

client/web/package.json
client/web/src/components/app.tsx
client/web/yarn.lock

Using wouter, a lightweight React routing library.

client/web: add route management for ui pages

---

cmd/tailscale/cli/web.go

If the status request to check for the preview node cap fails, continue with starting up the legacy client.

cli/web: don't block startup on status req

---

client/web/src/components/app.tsx
client/web/src/components/views/device-details-view.tsx
client/web/src/components/views/management-client-view.tsx
client/web/src/index.css
client/web/src/ui/profile-pic.tsx

Initial addition of device details view on the frontend. A little more backend piping work to come to fill all of the detail fields, for now using placeholders.

client/web: add device details view

---

client/web/src/components/app.tsx

client/web: pipe newSession through to readonly view

---

client/web/src/components/app.tsx
client/web/src/components/exit-node-selector.tsx
client/web/src/components/views/management-client-view.tsx
client/web/src/hooks/node-data.ts
client/web/src/icons/check.svg
client/web/src/icons/chevron-down.svg
client/web/src/icons/search.svg
client/web/src/index.css

client/web: add initial framework for exit node selector

---

client/web/src/components/app.tsx

Only loading data once auth request has completed.

client/web: move useNodeData out of App component

---

go.mod
go.sum

go.mod: updates web-client-prebuilt

---

ipn/ipnserver/server.go
ipn/localapi/localapi.go
ipn/localapi/localapi_test.go

For an operator user, require them to be able to `sudo tailscale` to use
`tailscale serve`. This is similar to the Windows elevated token check.
Updates https://github.com/tailscale/corp/issues/15405
Updates https://github.com/tailscale/corp/issues/15405

ipn/localapi: require root or sudo+operator access for SetServeConfig

---

clientupdate/clientupdate.go

Check for root early, before we fetch the pkgs index. This avoids several seconds delay for the command to tell you to sudo.

clientupdate: check whether running as root early

---

ipn/ipnlocal/local.go

As part of tailnet-lock netmap processing, the LocalBackend mutex is unlocked so we can potentially make a network call. Its possible (during shutdown or while the control client is being reset) for b.cc to become nil before the lock is picked up again.
Fixes: #9554

ipn/ipnlocal: fix nil control client panic while updating TKA head

---

client/web/src/components/acl-tag.tsx
client/web/src/components/views/device-details-view.tsx
client/web/src/hooks/node-data.ts
client/web/src/index.css
client/web/src/ui/badge.tsx
client/web/web.go

Fills /details page with real values, passed back from the /data endpoint.

client/web: populate device details view

---

clientupdate/clientupdate.go
ipn/ipnlocal/c2n.go

The c2n part was broken because we were not looking up the tailscale binary for that GOOS. The rest of the update was failing at the `pkg upgrade` confirmation prompt. We also need to manually restart tailscaled after update.

clientupdate,ipn/ipnlocal: fix c2n update on freebsd

---

appc/appconnector.go
appc/appconnector_test.go

The app connector matches a configuration of "*.example.com" to mean any sub-domain of example.com.
Updates #15437

appc: add support for matching wildcard domains

---

ssh/tailssh/incubator.go
ssh/tailssh/tailssh.go

ssh/tailssh: add envknobs to force override forwarding + sftp

---

ipn/policy/policy.go

ipn/policy: mark AppConnector service as interesting

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

Some conditional paths may otherwise skip the hostinfo update, so kick it off asynchronously as other code paths do.
Updates tailscale/corp#15437

ipn/ipnlocal: ensure that hostinfo is updated on app connector preference changes

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go

@bradfitz I assume this would be the preferred approach?

tailcfg,ipn/ipnlocal: add hostinfo field to replace service entry

---

posture/serialnumber_notmacos.go

posture: ignore not found serial errors

---

ipn/ipnlocal/c2n.go

ipn/ipnlocal: clean up c2n handling's big switch, add a mux table

---

ipn/ipnlocal/local.go

ipn/ipnlocal: respect ExitNodeAllowLANAccess on iOS

---

.github/workflows/update-webclient-prebuilt.yml

.github: add action for updating web-client-prebuilt module

---

client/web/assets.go

In production, the asset handler is receiving requests for pages like /details, which results in a 404. Instead, if we know the requested file does not exist, serve the main index page and let wouter route it appropriately on the frontend.
Updates tailscale/corp/#14335

client/web: server /index.html on 404 requests

---

client/web/src/components/app.tsx

Move Header component inside Router so that links are relative to the router base URL.

client/web: fix back button on devices with URL prefix

---

wgengine/magicsock/endpoint.go

This is gated behind the silent disco control knob, which is still in its infancy. Prior to this change disco pong reception was the only event that could move trustBestAddrUntil forward, so even though we weren't heartbeating, we would kick off discovery pings every trustUDPAddrDuration and mirror to DERP.

wgengine/magicsock: move trustBestAddrUntil forward on non-disco rx

---

client/web/src/components/login-toggle.tsx

When the viewing user is accessing a webclient not over Tailscale, they must connect over Tailscale before being able to log into the full management client, which is served over TS. This change adds a check that the user is able to access the node's tailscale IP. If not able to, the signin button is disabled. We'll also be adding Copy here to help explain to the user that they must connect to Tailscale before proceeding.
Updates #10261

client/web: when readonly, add check for TS connection

---

ipn/ipnlocal/serve.go

Updates https://github.com/tailscale/corp/issues/15485

ipn/ipnlocal: strip mount point from file serve

---

tsnet/example/web-client/web-client.go
tsnet/tsnet.go

tsnet: add option to run integrated web client

---

client/web/src/components/login-toggle.tsx

client/web: fix margins on login popover

---

health/health.go
wgengine/magicsock/derp.go

Updates #3363
Updates tailscale/corp#396

health: don't report a warning in DERP homeless mode

---

client/web/auth.go
client/web/web.go
client/web/web_test.go
ipn/ipnlocal/web_client.go
ipn/localapi/localapi.go

This change removes the existing debug-web-client localapi endpoint and replaces it with functions passed directly to the web.ServerOpts when constructing a web.ManageServerMode client.
The debug-web-client endpoint previously handled making noise requests to the control server via the /machine/webclient/ endpoints. The noise requests must be made from tailscaled, which has the noise connection open. But, now that the full client is served from tailscaled, we no longer need to proxy this request over the localapi.

{client/web},{ipn/ipnlocal}: replace localapi debug-web-client endpoint

---

util/syspolicy/caching_handler.go
util/syspolicy/caching_handler_test.go
util/syspolicy/handler_windows.go
util/syspolicy/syspolicy_test.go

Add a cache for syspolicy reads

Add syspolicy cache

---

control/controlclient/map.go
control/controlclient/map_test.go
tailcfg/tailcfg.go
types/netmap/nodemut.go

control/controlclient: support incremental packet filter updates [capver 81]

---

cmd/tailscale/cli/set.go

cmd/tailscale/cli: correct app connector help text in set

---

cmd/tailscale/cli/debug.go

It's possible to do this with a combination of watch-ipn and jq, but looking at the netmap while debugging is quite common, so it's nice to have a one-shot command to get it.

cmd/tailscale/cli: add debug function to print the netmap

---

cmd/containerboot/main.go
cmd/containerboot/main_test.go

containerboot: Add TS_ACCEPT_ROUTES

---

util/httpm/httpm_test.go

Updates #9635
Change-Id: I9089200f9327605036c88fc12834acece0c11694

util/httpm: don't run test if .git doesn't exist

---

ipn/ipnlocal/local.go
types/appctype/appconnector.go

appc,ipn/local: support wildcard when matching app-connectors

---

tsnet/tsnet.go
tsnet/tsnet_test.go

Application code can call the tsnet s.CapturePcap(filename) method to write all packets, sent and received, to a pcap file. The cleartext packets are written, outside the Wireguard tunnel. This is expected to be useful for debugging.
Updates https://github.com/tailscale/tailscale/issues/9707

tsnet: add CapturePcap method for debugging

---

tka/state.go

tka: clarify field comment

---

wgengine/netstack/netstack.go

wgengine/netstack: disable RACK on Windows

---

clientupdate/clientupdate.go
clientupdate/clientupdate_test.go
clientupdate/testdata/tailscale-1.52.0.plg
clientupdate/testdata/tailscale-1.54.0.plg
clientupdate/testdata/tailscale-nover-path-mentioned.plg
clientupdate/testdata/tailscale-nover.plg
cmd/tailscale/cli/update.go
ipn/ipnlocal/c2n.go

Use the [`plugin`
CLI](https://forums.unraid.net/topic/72240-solved-is-there-a-way-to-installuninstall-plugins-from-script/#comment-676870) to fetch and apply the update.
cc @dkaser 
Updates https://github.com/tailscale/tailscale/issues/10184

clientupdate: implement update for Unraid

---

ipn/ipnlocal/local.go

Updates: https://github.com/tailscale/corp/issues/16041

ipn/ipnlocal: update hostinfo when app connector state is toggled

---

client/web/web.go

Fixes a TODO in web.authorizeRequest.
`getSession` calls `WhoIs` already. Call `getSession` earlier in `authorizeRequest` so we can avoid the duplicate `WhoIs` check on the same request.
Updates #10261

client/web: remove duplicate WhoIs call

---

client/web/src/hooks/node-data.ts

Was setting this for testing, snuck into the merged version.
Updates #10261

client/web: remove ControlAdminURL override

---

client/web/src/components/app.tsx
client/web/src/components/exit-node-selector.tsx
client/web/src/components/login-toggle.tsx
client/web/src/components/views/device-details-view.tsx
client/web/src/components/views/home-view.tsx
client/web/src/components/views/ssh-view.tsx
client/web/src/components/views/subnet-router-view.tsx
client/web/src/index.css
client/web/src/ui/button.tsx
client/web/styles.json
client/web/tailwind.config.js

client/web: adjust colors and some UI margins

---

client/web/src/components/views/subnet-router-view.tsx

client/web: add cancel button to subnet router input section

---

util/syspolicy/handler_windows.go
util/syspolicy/policy_keys.go

util/syspolicy: add policy client metrics

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

This adds support for enforcing exit node LAN access, DNS and subnet routes.
Adding new preference policies was getting repetitive, so this turns some of the boilerplate into a table.
Updates tailscale/corp#15585
Updates ENG-2240
Change-Id: Iabd3c42b0ae120b3145fac066c5caa7fc4d67824

ipn/ipnlocal: add additional syspolicy enforcement

---

client/web/src/components/address-copy-card.tsx
client/web/src/components/app.tsx
client/web/src/components/exit-node-selector.tsx
client/web/src/components/login-toggle.tsx
client/web/src/components/views/home-view.tsx
client/web/src/components/views/ssh-view.tsx
client/web/src/components/views/subnet-router-view.tsx
client/web/src/hooks/exit-nodes.ts
client/web/src/ui/card.tsx
client/web/src/ui/empty-state.tsx
client/web/src/ui/search-input.tsx

Style changes made in live pairing session.
Updates #10261

client/web: style tweaks

---

.golangci.yml
Makefile
cmd/tailscale/cli/cli_test.go
posture/serialnumber_macos_test.go

Change-Id: Ice78fc907bad24c1de749a1595e212ef2db4b8bb

ci: run 'go vet' in golangci-lint; fix errors in tests

---

client/web/src/components/app.tsx
client/web/src/components/update-available.tsx
client/web/src/components/views/device-details-view.tsx
client/web/src/components/views/home-view.tsx
client/web/src/components/views/ssh-view.tsx
client/web/src/components/views/subnet-router-view.tsx
client/web/src/index.css

Updates:
* Card component used throughout instead of custom card class
* SSH toggle changed to non-editable text/status icon in readonly
* Red error text on subnet route input when route post failed
Updates #10261

client/web: small UI cleanups

---

cmd/containerboot/main.go

`tailscaled` and `tailscale` expect the socket to be at `/var/run/tailscale/tailscaled.sock`, however containerboot would set up the socket at `/tmp/tailscaled.sock`. This leads to a poor UX when users try to use any `tailscale` command as they have to prefix everything with `--socket /tmp/tailscaled.sock`.
To improve the UX, this adds a symlink to
`/var/run/tailscale/tailscaled.sock` to point to `/tmp/tailscaled.sock`.
This approach has two benefits, 1 users are able to continue to use existing scripts without this being a breaking change. 2. users are able to use the `tailscale` CLI without having to add the `--socket` flag.
Fixes tailscale/corp#15902
Fixes #6849
Fixes #10027

cmd/containerboot: symlink TS_SOCKET to socket expected by CLI

---

client/web/web.go

In Login mode, must first run system auth. But once authorized, should be able to reach rest of auth logic to check whether the user can manage the node. This results in showing/hiding the sign in button in the frontend login toggle.
Updates #10261

client/web: fix serveAPIAuth in Login mode

---

client/web/package.json
client/web/src/components/app.tsx
client/web/src/components/views/device-details-view.tsx
client/web/src/components/views/subnet-router-view.tsx
client/web/src/ui/dialog.tsx
client/web/src/ui/popover.tsx
client/web/src/ui/portal-container-context.tsx
client/web/src/utils/util.ts
client/web/yarn.lock

Add confirmation dialogs for disconnecting and stopping advertisement of a subnet route.
Updates #10261

client/web: add confirmation dialogs

---

client/web/web.go
client/web/web_test.go

Add metric logging for the case where a user is viewing a local or remote node.

client/web: add metric logging when viewing local / remote node

---

cmd/k8s-operator/proxy.go

Add the new format but keep respecting the old one.
Updates #4217

cmd/k8s-operator: drop https:// in capName

---

client/web/src/components/login-toggle.tsx
client/web/src/hooks/auth.ts

client/web: fix ts connection check

---

client/web/assets.go

client/web: only add cache header for assets

---

ipn/ipnlocal/local.go

Fixes #10595
Change-Id: I4e96e9c43b8dedb5f88b03368c01b0e46723e15b

ipn/ipnlocal: fix usage of slices.Compact

---

wgengine/magicsock/derp.go

The switch in Conn.runDerpReader() on the derp.ReceivedMessage type contained cases other than derp.ReceivedPacket that fell through to writing to c.derpRecvCh, which should only be reached for derp.ReceivedPacket. This can result in the last/previous derp.ReceivedPacket to be re-handled, effectively creating a duplicate packet. If the last derp.ReceivedPacket happens to be a disco.CallMeMaybe it may result in a disco ping scan towards the originating peer on the endpoints contained.
The change in this commit moves the channel write on c.derpRecvCh and subsequent select awaiting the result into the derp.ReceivedMessage case, preventing it from being reached from any other case. Explicit continue statements are also added to non-derp.ReceivedPacket cases where they were missing, in order …

wgengine/magicsock: fix handling of derp.PeerGoneMessage

---

client/web/web.go

Throughout the web UI, we present the tailscale addresses for the self node. In the case of the node being shared out with a user from another tailnet, the peer viewer may actually know the node by a different IP than the node knows itself as (Tailscale IPs can be configured as desired on a tailnet level). This change includes two fixes:
1. Present the self node's addresses in the frontend as the addresses the viewing node knows it as (i.e. the addresses the viewing node uses to access the web client).
2. We currently redirect the viewer to the Tailscale IPv4 address if viewing it by MagicDNS name, or any other name that maps to the Tailscale node. When doing this redirect, which is primarily added for DNS rebinding protection, we now check the address the peer knows this node as, and …

client/web: use Tailscale IP known by peer node

---

disco/disco.go

disco: correct noun for nacl box type in disco docs

---

ipn/prefs.go

Using reflect.MethodByName disables some linked deadcode optimizations and makes our binaries much bigger.
Difference before/after this commit:
```
-rwxr-xr-x  1 awly awly  30M Dec 19 15:28 tailscaled.after*
-rwxr-xr-x  1 awly awly  43M Dec 19 15:27 tailscaled.before*
```
Fixes #10627

ipn: remove use of reflect.MethodByName

---

api.md

api.md: add docs for setting an IP address

---

ipn/ipnlocal/local.go

Change-Id: I1fdad454198d7ea4a898dbff3062818b0db35167

ipn/ipnlocal: fix data race with capForcedNetfilter field

---

wgengine/magicsock/endpoint.go

wgengine/magicsock: fix typos in docs

---

util/winutil/restartmgr_windows.go

util/winutil: add some missing docs to restartmgr errors

---

net/dns/resolver/forwarder.go

To make it easier to correlate the starting/ending log messages.
Change-Id: I2802d53ad98e19bc8914bc58f8c04d4443227b26

net/dns/resolver: add ID to verbose logs in forwarder

---

tstest/integration/integration_test.go

tstest/integration: add tests for auto-update defaulting behavior

---

client/web/src/components/login-toggle.tsx

The manage client always listens on http (non-secure) port 5252.  If the login client is loaded over https, then the connectivity check to `/ok` will fail with a mixed-content error. Mixed-content enforcement is a browser setting that we have no control over, so there's no way around this.
In this case of the login client being loaded over https, we skip the connectivity check entirely.  We will always render the sign-in button, though we don't know for sure if the user has connectivity, so we provide some additional help text in case they have trouble signing in.
Updates hassio-addons/addon-tailscale#314
Existing UI when we can determine connectivity:
New UI when the login client is loaded over https and we can't do the connectivity check:

client/web: skip connectivity check on https

---

cmd/k8s-operator/sts.go
cmd/k8s-operator/sts_test.go

Fix two minor bits post- #10825

cmd/k8s-operator: minor fix in name gen

---

derp/derp_server.go

derp: remove unused per-client struct field

---

derp/derp_client.go
derp/derp_server.go

derp: optimize another per client field alignment

---

net/netmon/netmon.go

net/netmon: when a new network is added, trigger netmon update

---

tstime/rate/value.go
tstime/rate/value_test.go

Implement support for marshaling and unmarshaling a Value.
Updates tailscale/corp#8427

tstime/rate: implement Value.{Marshal,Unmarshal}JSON

---

util/slicesx/slicesx.go
util/slicesx/slicesx_test.go

For use in corp, where we appear to have re-implemented this in a few places with varying signatures.
Change-Id: Id863a87e674f3caa87945519be8e09650e9c1d76

util/slicesx: add Filter function

---

cmd/k8s-operator/deploy/chart/templates/deployment.yaml
cmd/k8s-operator/deploy/chart/values.yaml
cmd/k8s-operator/deploy/manifests/operator.yaml
docs/windows/policy/tailscale.admx

Adds missing env var option; also allow arbitrary env var for greater flexibility

feat(operator/chart): expose operator tag env var, allow arbitrary env var

---

util/nocasemaps/nocase.go
util/nocasemaps/nocase_test.go

Added append functionality to nocasemaps for multiple values at a time, where the key will be lowered and the value will be added to the map.

oss/util: Add Append function to Nocasemaps

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/peermtu.go
wgengine/magicsock/peermtu_stubs.go

magicsock: mute noisy expected peer mtu related error

---

ipn/ipnlocal/serve_test.go

ipn/ipnlocal: fix failing test

---

words/scales.txt

words: i like the direction this list is taking

---

cmd/hello/hello.go

cmd/hello: avoid deprecated APIs

---

appc/appconnector.go
appc/appconnector_test.go
ipn/ipnlocal/peerapi_test.go

If any domain along a CNAME chain matches any of the routed domains, add routes for the discovered domains.
Fixes tailscale/corp#16928

appc,ipn/ipnlocal: add app connector routes if any part of a CNAME chain is routed

---

util/deephash/deephash.go

util/deephash: document pathological deephash behavior

---

cmd/hello/hello.tmpl.html

Fixes https://github.com/tailscale/corp/issues/17104

cmd/hello: link to the Hello KB article

---

ipn/localapi/localapi.go

Use Http.StatusOk instead of 200

ipn/localapi: more http status cleanup

---

tsweb/tsweb.go
tsweb/tsweb_test.go

I'll need to use both `NormalizedPath()` and a custom bucket handler in control (for things like `/api/v2/tailnet/<tailnetSID>`), but this is a good starting point i think.
Updates: corp#17075

tsweb: implementing bucketed statistics for started/finished counts

---

tsweb/tsweb.go
tsweb/tsweb_test.go

tsweb: replace domains/emails in paths when bucketing stats

---

appc/appconnector.go

Advertise DNS discovered addresses as a single preference update rather than one at a time.
Sort the list of observed addresses and use binary search to consult the list.
Updates tailscale/corp#16636

appc: optimize dns response observation for large route tables

---

tsweb/tsweb.go
tsweb/tsweb_test.go

tsweb: normalize common StableID's in bucketed stats, export as LabelMap

---

tsweb/tsweb.go
tsweb/tsweb_test.go

Last one I hope XD
Updates: corp#17075

tsweb: normalize passkey identities in bucketed stats

---

util/deephash/deephash_test.go

util/deephash: cleanup TODO in TestHash

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go
control/controlclient/controlclient_test.go
control/controlclient/map.go
control/controlknobs/controlknobs_test.go
ipn/prefs_test.go
ssh/tailssh/tailssh_test.go
tailcfg/tailcfg_test.go
types/dnstype/dnstype_test.go
types/netmap/nodemut.go
types/netmap/nodemut_test.go
types/persist/persist_test.go
util/ctxkey/key.go
util/deephash/deephash.go
util/deephash/deephash_test.go
util/deephash/types.go
wgengine/router/router_test.go
wgengine/wgint/wgint.go

all: use reflect.TypeFor now available in Go 1.22

---

taildrop/resume.go
tka/aum.go
types/key/util.go
types/logid/id.go

all: use new AppendEncode methods available in Go 1.22

---

.github/workflows/test.yml

Change-Id: I10dca601c79411b412180a46b3f82136e40544b0

.github: fuzzing is now unbroken

---

cmd/tailscaled/tailscaled_windows.go
ipn/ipnlocal/local.go

Starts TailFS for Windows too, initializes shares on startup.

tailfs: fix startup issues on windows

---

cmd/tailscaled/tailscaled.go

As part of #10631, we stopped using function pointers for subcommands, preventing us from registering platform-specific installSystemDaemon and uninstallSystemDaemon subcommands.
Fixes #11099

tailscaled: revert to using pointers for subcommands

---

util/cloudenv/cloudenv.go
util/cloudenv/cloudenv_test.go

Updates #4984
Change-Id: Ib229eb40af36a80e6b0fd1dd0cabb07f0d50a7d1

util/cloudenv: add support for DigitalOcean

---

ipn/ipnlocal/local.go
ipn/ipnlocal/state_test.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go
types/persist/persist_clone.go
types/persist/persist_view.go

Removing as per go/group-all-the-things.
Updates tailscale/corp#17445

tailcfg: remove UserProfile.Groups

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/share.go

cmd/tailscale: hide share subcommand

---

tsweb/debug.go

This reverts commit 30c9189ed307df6f2c1567aa7945bde77bb54c52.

Revert "tsweb: update ServeMux matching to 1.22.0 syntax (#11090)"

---

net/dns/manager_freebsd.go
net/dns/manager_linux.go
net/dns/openresolv.go

Updates #11129
Change-Id: Ic594868ba3bc31f6d3b0721ecba4090749a81f7f

net/dns: log more info when openresolv commands fail

---

wgengine/router/router_linux.go

wgengine/router: fix ip rule restoration

---

cmd/tailscale/cli/web.go

cmd/tailscale: make web client URL clickable

---

derp/derp_server.go

derp: plumb context to Server.verifyClient

---

net/tshttpproxy/tshttpproxy.go

Updates #11196
Change-Id: Id6334c10f52f4cfbda9f03dc8096ab7a6c54a088

net/tshttpproxy: log when we're using a proxy

---

cmd/tsconnect/wasm/wasm_js.go
control/controlclient/map.go
ipn/ipnlocal/local.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/serve.go
ipn/ipnlocal/web_client.go
net/tsaddr/tsaddr.go
net/tsdial/dnsmap.go
tsnet/tsnet.go
types/views/views.go
types/views/views_test.go
wgengine/magicsock/debughttp.go
wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock.go
wgengine/netstack/netstack.go
wgengine/pendopen.go
wgengine/userspace.go
wgengine/wgcfg/nmcfg/nmcfg.go

Updates #11058
Updates golang/go#65685

all: remove LenIter, use Go 1.22 range-over-int instead

---

wgengine/netstack/netstack.go

- add a clientmetric with a counter of TCP forwarder drops due to the max attempts;
- make max attempts configurable via an envknob to allow debugging without recompiling the client;
- fix varz metric types, as they are all counters.
Updates #8210

wgengine/netstack: expose TCP forwarder drops via clientmetrics

---

ipn/ipnstate/ipnstate.go
types/key/node.go
wgengine/pendopen.go
wgengine/userspace.go
wgengine/wgint/wgint.go
wgengine/wgint/wgint_test.go

A few misc and cleanup changes in prep for #7617

misc cleanup changes while reading code

---

tailfs/tailfsimpl/tailfs_test.go

Ues a noop authenticator to avoid potential races in gowebdav's built-in authenticator.
Fixes #11259

tailfs: fix race condition in tailfs_test

---

tailcfg/derpmap.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

tailcfg: add latitude, longitude for node location

---

util/cache/none.go
util/cache/single.go

Change-Id: Ib3a33a7609530ef8c9f3f58fc607a61e8655c4b5

util/cache: fix missing interface methods

---

tsweb/tsweb.go
tsweb/tsweb_test.go

tsweb: allow empty redirect URL in CleanRedirectURL

---

tailcfg/tailcfg.go

tailcfg: add suggest exit node related node attribute

---

util/cmpver/version.go
util/cmpver/version_test.go

util/cmpver: add Less/LessEq helper funcs

---

ipn/store.go

ipn: add comments about thread-safety to StateStore

---

ipn/ipnlocal/local.go
ipn/ipnlocal/tailfs.go

This eliminates unnecessary map.Clone() calls and also eliminates repetitive notifications about the same set of shares.

ipn/ipnlocal: reduce allocations in TailFS share notifications

---

tsweb/request_id.go

In case we want to change the format to something opaque later.
Updates tailscale/corp#2549
Change-Id: Ie2eac8b885b694be607e9d5101d24b650026d89c

tsweb: add String method to tsweb.RequestID

---

tailcfg/tailcfg.go

bump version for adding NodeAttrSuggestExitNode

tailcfg: bump CapabilityVersion

---

util/linuxfw/iptables_runner.go

util/linuxfw: correct logical error in NAT table check

---

util/linuxfw/iptables_runner.go

There are container environments such as GitHub codespaces that have partial IPv6 support - routing support is enabled at the kernel level, but lacking IPv6 filter support in the iptables module.
In the specific example of the codespaces environment, this also has pre-existing legacy iptables rules in the IPv4 tables, as such the nascent firewall mode detection will always pick iptables.
We would previously fault trying to install rules to the filter table, this catches that condition earlier, and disables IPv6 support under these conditions.
Updates #5621
Updates #11344
Updates #11354

util/linuxfw: fix support for containers without IPv6 iptables filters

---

wgengine/netstack/netstack.go
wgengine/netstack/netstack_test.go

This fixes a bug that was introduced in #11258 where the handling of the per-client limit didn't properly account for the fact that the gVisor TCP forwarder will return 'true' to indicate that it's handled a duplicate SYN packet, but not launch the handler goroutine.
In such a case, we neither decremented our per-client limit in the wrapper function, nor did we do so in the handler function, leading to our per-client limit table slowly filling up without bound.
Fix this by doing the same duplicate-tracking logic that the TCP forwarder does so we can detect such cases and appropriately decrement our in-flight counter.
Updates tailscale/corp#12184
Change-Id: Ib6011a71d382a10d68c0802593f34b8153d06892

wgengine/netstack: fix bug with duplicate SYN packets in client limit

---

cmd/derpprobe/derpprobe.go
prober/derp.go
prober/derp_test.go
prober/prober.go

Also, export cumulative counters for probes, not just last-state gauges.
Three separate commits for easier review.

prober: add an optional DERP mesh probe that sends arbitrary large payloads

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
ipn/ipnlocal/state_test.go

If the client uses the default Tailscale control URL, validate that all PopBrowserURLs are under tailscale.com or *.tailscale.com. This reduces the risk of a compromised control plane opening phishing pages for example.
The client trusts control for many other things, but this is one easy way to reduce that trust a bit.
Fixes #11393

ipn/ipnlocal: validate domain of PopBrowserURL on default control URL

---

syncs/syncs.go
syncs/syncs_test.go

To mimic sync.Map.Swap, sync/atomic.Value.Swap, etc.
Change-Id: If7627da1bce8b552873b21d7e5ebb98904e9a650

syncs: add Swap method

---

tool/gocross/autoflags.go
tool/gocross/autoflags_test.go

tool/gocross: add android autoflags

---

cmd/k8s-operator/connector_test.go
cmd/k8s-operator/ingress_test.go
cmd/k8s-operator/operator_test.go
cmd/k8s-operator/proxyclass_test.go
cmd/k8s-operator/sts.go
cmd/k8s-operator/testutils_test.go
ipn/conf.go

Cherry-pick of https://github.com/tailscale/tailscale/pull/11453

cmd/k8s-operator,ipn/conf.go: fix --accept-routes for proxies (cherry-pick)

---

control/controlclient/direct.go
control/controlclient/noise.go
control/controlclient/noise_test.go
tailcfg/tailcfg.go

control/controlclient: send load balancing hint HTTP request header

---

ipn/ipnlocal/tailfs.go

This allows the UI to distinguish between 'no shares' versus 'not being notified about shares'.
Updates ENG-2843

ipnlocal: ensure TailFS share notifications are non-nil

---

control/controlclient/map.go

control/controlclient: free memory on iOS before full netmap work

---

ipn/ipnlocal/local.go
net/portmapper/portmapper.go
tailcfg/tailcfg.go
wgengine/magicsock/derp.go
wgengine/magicsock/magicsock.go

tailcfg, ipn/ipnlocal, wgengine/magicsock: add only-tcp-443 node attr

---

metrics/multilabelmap.go
metrics/multilabelmap_test.go
tsweb/varz/varz.go
tsweb/varz/varz_test.go

metrics, tsweb/varz: add multi-label map metrics

---

cmd/tailscale/cli/update.go

cmd/tailscale/cli: remove Beta tag from tailscale update

---

go.mod
go.sum

To pick up https://github.com/gaissmai/bart/pull/17.
Updates #deps

go.mod: bump github.com/gaissmai/bart

---

control/controlclient/direct.go

The initial control client request can get stuck in the event that a connection is established but then lost part way through, without any ICMP or RST. Ensure that the control client will be restarted by timing out that initial request as well.
Fixes #11542

control/controlclient: move client watchdog to cover initial request

---

tsweb/tsweb.go

tsweb: make BucketedStats not track 400s, 404s, etc

---

safeweb/http.go
safeweb/http_test.go

Allow the use of inline styles with safeweb via an opt-in configuration item. This will append `style-src "self" "unsafe-inline"` to the default CSP. When present the `style-src` directive will take preference over the fallback `default-src "self"` directive.
Updates tailscale/corp#8027

safeweb: add opt-in inline style CSP toggle

---

logtail/logtail.go

Corp details:
https://github.com/tailscale/corp/issues/18177#issuecomment-2026598715
https://github.com/tailscale/corp/pull/18775#issuecomment-2027505036
Updates tailscale/corp#18177

logtail: prevent js/wasm clients from picking TLS client cert

---

safeweb/http.go
safeweb/http_test.go

When both muxes match, and one of them is a wildcard "/" pattern (which is common in browser muxes), choose the more specific pattern. If both are non-wildcard matches, there is a pattern overlap, so return an error.

safeweb: detect mux handler conflicts

---

net/dns/direct.go
net/dns/direct_test.go

it will leak many inotify if not cancel the ctx.

net/dns: close ctx when close dns directManager

---

cmd/tsconnect/wasm/wasm_js.go
logtail/logtail.go

logtail: delete unused code from old way to configure zstd

---

util/linuxfw/nftables_runner.go

For proxies created by the Kubernetes operator we [clamp traffic sent out via `tailscale0` interface](https://github.com/tailscale/tailscale/blob/v1.63.0-pre/cmd/containerboot/main.go#L858).
However, it looks like the [nftables implementation](https://github.com/tailscale/tailscale/blob/v1.63.0-pre/util/linuxfw/nftables_runner.go#L241-L318) of the rule was never executed because a rule before it, jumps to another chain where a rule with accept verdict matches, which means that no other rules in that chain are processed:
```
table ip filter {
chain FORWARD {
type filter hook forward priority filter; policy accept;
counter packets 100 bytes 6178 jump ts-forward // <- move on to ts-forward
oifname "tailscale0*" tcp flags syn tcp option maxseg size set rt mtu // <- the clamping rule
}
chain …
```

util/linuxfw: fix MSS clamping in nftables mode

---

cmd/derper/derper.go
cmd/derpprobe/derpprobe.go

cmd/{derper,derpprobe}: add --version flag

---

control/controlclient/direct.go
tstest/integration/integration_test.go
tstest/integration/testcontrol/testcontrol.go

Updates #11585
Updates https://github.com/tailscale/corp/issues/18882

control/controlclient: delete old naclbox code, require ts2021 Noise

---

clientupdate/systemd_linux.go
net/dns/direct_test.go
net/dns/resolvconffile/resolvconffile_test.go

clientupdate, net/dns: fix some "tailsacle" typos

---

cmd/tailscale/cli/configure-synology-cert.go
cmd/tailscale/cli/configure-synology-cert_test.go
cmd/tailscale/cli/configure.go

cmd/tailscale/cli: Add CLI command to update certs on Synology devices.

---

cmd/tailscale/cli/exitnode.go

The output was changing randomly per run, due to range over a map.
Then some misc style tweaks I noticed while debugging.
Fixes #11629

cmd/tailscale/cli: make exit-node list not random

---

tsweb/tsweb.go

We would have incomplete stats and missing logs in cases of panics.
Updates tailscale/corp#18687

tsweb: handle panics in retHandler

---

ipn/ipnlocal/local.go

A number of methods in LocalBackend (with suffixed "LockedOnEntry")
require b.mu be held but unlock it on the way out. That's asymmetric
and atypical and error prone.
This adds a helper method to LocalBackend that locks the mutex and
returns a sync.OnceFunc that unlocks the mutex. Then we pass around
that unlocker func down the chain to make it explicit (and somewhat
type check the passing of ownership) but also let the caller defer
unlock it, in the case of errors/panics that happen before the callee
gets around to calling the unlock.
This revealed a latent bug in LocalBackend.DeleteProfile which double
unlocked the mutex.
Updates #11649

ipn/ipnlocal: add some "lockedOnEntry" helpers + guardrails, fix bug

---

ipn/ipnlocal/local.go

This names the func() that Once-unlocked LocalBackend.mu. It does so
both for docs and because it can then have a method: Unlock, for the
few points that need to explicitly unlock early (the cause of all this
mess). This makes those ugly points easy to find, and also can then
make them stricter, panicking if the mutex is already unlocked. So a
normal call to the func just once-releases the mutex, returning false
if it's already done, but the Unlock method is the strict one.
Then this uses it more, so most the b.mu.Unlock calls remaining are
simple cases and usually defers.
Updates #11649

ipn/ipnlocal: name the unlockOnce type, plumb more, add Unlock method

---

net/dns/publicdns/publicdns.go
net/dns/publicdns/publicdns_test.go
net/dns/resolver/forwarder_test.go

Updates #7946
[@bradfitz fixed up version of #8417]

net/dns/{publicdns,resolver}: add start of Control D support

---

cmd/tailscale/cli/configure-kube.go

Relevant documentation:
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable

cli/configure: respect $KUBECONFIG

---

docs/windows/policy/en-US/tailscale.adml
docs/windows/policy/tailscale.admx

Updates ENG-2776
Updates the .admx and .adml files to include the new ManagedByOrganizationName, ManagedByCaption and ManagedByURL system policies, added in Tailscale v1.62 for Windows.

docs/policy: update ADMX and ADML files with new Windows 1.62 syspolicies

---

net/dns/manager_windows_test.go
net/dns/nrpt_windows.go

We were being too aggressive when deciding whether to write our NRPT rules to the local registry key or the group policy registry key.
After once again reviewing the document which calls itself a spec (see issue), it is clear that the presence of the DnsPolicyConfig subkey is the important part, not the presence of values set in the DNSClient subkey. Furthermore, a footnote indicates that the presence of DnsPolicyConfig in the GPO key will always override its counterpart in the local key. The implication of this is important: we may unconditionally write our NRPT rules to the local key. We copy our rules to the policy key only when it contains NRPT rules belonging to somebody other than us.
Fixes https://github.com/tailscale/corp/issues/19071

net/dns: unconditionally write NRPT rules to local settings

---

tailcfg/tailcfg.go

tailcfg: add exit destination for network flow logs node attribute

---

ipn/ipnlocal/local.go

Updates tailscale/corp#18984
Updates tailscale/corp#18202

ipnlocal: enable allow LAN for android

---

.github/workflows/test.yml
cmd/tailscaled/tailscaled.go
go.mod
go.sum
net/tstun/tstun_stub.go
net/tstun/tun.go
posture/serialnumber_stub.go

At least in userspace-networking mode.
Fixes #11361

cmd/tailscaled, net/tstun: build for aix/ppc64

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
tstest/integration/integration_test.go

[3 commits, various cleanups]
Updates #11649

ipn/ipnlocal: [3 commits, various cleanups]

---

util/syspolicy/handler.go

util/syspolicy: clean up doc grammar and consistency

---

paths/paths_unix.go

paths: set default state path on AIX

---

wgengine/router/router_linux.go

Trying to run iptables/nftables on Synology pauses for minutes with
lots of errors and ultimately does nothing as it's not used and we
lack permissions.
Updates #11737

wgengine/router: don't attempt route cleanup on Synology

---

net/dns/resolver/forwarder.go

This ensures that we close the underlying connection(s) when a major link change happens. If we don't do this, on mobile platforms switching between WiFi and cellular can result in leftover connections in the http.Client's connection pool which are bound to the "wrong" interface.
Updates #10821
Updates https://github.com/tailscale/corp/issues/19124
Change-Id: Ibd51ce2efcaf4bd68e14f6fdeded61d4e99f9a01

net/dns/resolver: use SystemDial in DoH forwarder

---

docs/windows/policy/en-US/tailscale.adml
docs/windows/policy/tailscale.admx

Change-Id: Ib53b639690b77d1b7d857304dca2119f197227ce

docs/windows/policy: add missing key expiration warning interval

---

cmd/tailscale/cli/drive.go

cmd/tailscale: clarify Taildrive grants in help text

---

tailcfg/tailcfg.go

tailcfg: rename exit node destination network flow log node attribute

---

net/tsdial/tsdial.go

If this happens, it results in us pessimistically closing more connections than might be necessary, but is more correct since we won't "miss" a change to the default route interface and keep trying to send data over a nonexistent interface, or one that can't reach the internet.
Updates tailscale/corp#19124
Change-Id: Ia0b8b04cb8cdcb0da0155fd08751c9dccba62c1a

net/tsdial: assume all connections are affected if no default route is present

---

control/controlclient/direct.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

tailcfg: remove some unused fields from RegisterResponseAuth

---

ipn/ipnlocal/profiles.go
ipn/ipnlocal/profiles_test.go

Prior to
https://github.com/tailscale/tailscale/pull/11814/commits/1613b18f8280c2bce786980532d012c9f0454fa2#diff-314ba0d799f70c8998940903efb541e511f352b39a9eeeae8d475c921d66c2ac, nodes could set AutoUpdate.Apply=true on unsupported platforms via `EditPrefs`. Specifically, this affects tailnets where default auto-updates are on.
Fix up those invalid prefs on profile reload, as a migration.
Updates #11544

ipn/ipnlocal: reset auto-updates if unsupported on profile load

---

cmd/k8s-operator/deploy/crds/tailscale.com_proxyclasses.yaml
cmd/k8s-operator/deploy/manifests/operator.yaml
cmd/k8s-operator/sts.go
cmd/k8s-operator/sts_test.go
k8s-operator/api.md
k8s-operator/apis/v1alpha1/types_proxyclass.go
k8s-operator/apis/v1alpha1/zz_generated.deepcopy.go
scripts/kube-deepcopy.sh

cmd/k8s-operator,k8s-operator: optionally configure Pod affinity rules for proxies

---

release/dist/qnap/files/scripts/build-qpkg.sh

Updates tailscale/tailscale-qpkg#135

release/dist/qnap: omit .qpkg.codesigning files

---

tailcfg/tailcfg.go

tailcfg: add auto exit node attribute

---

safeweb/http.go
safeweb/http_test.go

safeweb: handle mux pattern collisions more generally

---

control/controlclient/auto.go
control/controlclient/direct.go
ipn/ipnlocal/local.go

control/controlclient: plumb health.Tracker

---

health/health.go
wgengine/magicsock/derp.go
wgengine/magicsock/magicsock.go

health, wgengine/magicsock: remove last of health package globals

---

cmd/containerboot/main.go

See #11893 for context- this fixes a race condition in iptables mode where containerboot was running wait syscall against all its subprocesses and causing iptables commands ran with `go.Run` crash the container.
Containerboot now waits on `tailscaled` process only - there is no other process running in the container post-start that we should be attempting to clean up.
Updates tailscale/tailscale#11893

cmd/containerboot: wait on tailscaled process only

---

api.md

api.md: fix missing links after move of device posture

---

tailcfg/tailcfg.go

tailcfg: add suggest exit node UI node attribute

---

types/views/views.go

types/views: use slices.Contains{,Func}

---

ipn/ipnlocal/local.go

Also, reset it in a few more places (e.g. logout, new blank profiles, etc.) to avoid a few more cases where a pre-existing dialPlan can cause a new Headscale server take 10+ seconds to connect.
Updates #11938
Follow-up to #11933
Change-Id: I3095173a5a3d9720507afe4452548491e9e45a3e

ipn/ipnlocal: reset the dialPlan only when the URL is unchanged

---

util/slicesx/slicesx.go
util/slicesx/slicesx_test.go

We had this in a different repo, but moving it here, as this a more
fitting package.

util/slicesx: add AppendMatching

---

drive/driveimpl/drive_test.go
drive/driveimpl/remote_impl.go

drive: don't allow DELETE on read-only shares

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/ffcomplete/internal/complete.go
cmd/tailscale/cli/ffcomplete/internal/complete_test.go
cmd/tailscale/cli/ssh.go

Updates https://github.com/tailscale/tailscale/issues/3793

cmd/tailscale/cli: fix --socket adherence in tab-completion results, omit empty

---

.gitignore
Makefile
ssh/tailssh/incubator.go
ssh/tailssh/tailssh_integration_test.go
ssh/tailssh/testcontainers/Dockerfile

ssh/tailssh: add integration test

---

.github/workflows/installer.yml
scripts/installer.sh

scripts/installer.sh: remove unnecessary escaping in grep

---

health/health.go
ipn/ipnlocal/local.go
ipn/ipnlocal/profiles.go

In prep for making health warnings rich objects with metadata rather
than a bunch of strings, start moving it all into the same place.
We'll still ultimately need the stringified form for the CLI and
LocalAPI for compatibility but we'll next convert all these warnings
into Warnables that have severity levels and such, and legacy
stringification will just be something each Warnable thing can do.
Updates #4136

health, ipn/ipnlocal: move more health warning code into health.Tracker

---

net/dns/resolver/forwarder.go

To aid in debugging exactly what's going wrong, instead of the not-particularly-useful "dns udp query: context deadline exceeded" error that we currently get.
Updates #3786
Updates #10768
Updates #11620
(etc.)
Change-Id: I76334bf0681a8a2c72c90700f636c4174931432c

net/dns/resolver: add better error wrapping

---

cmd/derper/bootstrap_dns_test.go
cmd/derper/derper.go
derp/derphttp/derphttp_client.go
derp/derphttp/derphttp_server.go
derp/derphttp/derphttp_test.go
net/netcheck/netcheck.go
ssh/tailssh/tailssh_test.go
tstest/nettest/nettest.go
wgengine/userspace.go

[6 commits, all vaguely related in making tests pass in airplane mode]

Various airplane wifi fixes

---

drive/driveimpl/compositedav/propfind.go
drive/driveimpl/compositedav/stat_cache.go
drive/driveimpl/drive_test.go
drive/driveimpl/local_impl.go
ipn/ipnlocal/drive.go
ipn/ipnlocal/local.go

Updates #11967
There are two separate fixes in two commits.

drive: actually cache results on statcache

---

tsweb/tsweb.go

The inflight request tracker only starts recording a new bucket after the first non-error request. Unfortunately, it's written in such a way that ONLY successful requests are ever marked as being finished. Once a bucket has had at least one successful request and begun to be tracked, all subsequent error cases are never marked finished and always appear as in-flight.
This change ensures that if a request is recorded has having been started, we also mark it as finished at the end.
Updates tailscale/corp#19767

tsweb: ensure in-flight requests are always marked as finished

---

tsweb/tsweb.go

tsweb: remove redundant bumpStartIfNeeded func

---

util/syspolicy/policy_keys.go
util/syspolicy/syspolicy_test.go

util/syspolicy: add auto exit node related keys

---

cmd/sniproxy/sniproxy_test.go
ipn/ipnlocal/local.go
net/netcheck/netcheck.go
net/netcheck/netcheck_test.go
net/stun/stuntest/stuntest.go
tailcfg/derpmap.go
tstest/integration/integration_test.go

all: make more tests pass/skip in airplane mode

---

ipn/ipnlocal/local.go
net/portmapper/portmapper.go
tstest/integration/integration_test.go

ipn/ipnlocal, tstest/integration: add panic to catch flaky test in the act

---

control/controlclient/auto.go

I found this too hard to read before.
This is pulled out of #12033 as it's unrelated cleanup in retrospect.
Updates #12028

control/controlclient: early return and outdent some code

---

ipn/ipnlocal/local.go

Instead of calling it from Start everytime, call it from NewLocalBackend once.
Updates #11649

ipn/ipnlocal: call SetNetInfoCallback from NewLocalBackend

---

cmd/tailscaled/tailscaled.go
ipn/ipnserver/server.go

There was a small window in ipnserver after we assigned a LocalBackend
to the ipnserver's atomic but before we Start'ed it where our
initalization Start could conflict with API calls from the LocalAPI.
Simplify that a bit and lay out the rules in the docs.
Updates #12028

ipn/ipnserver: close a small race in ipnserver, ~simplify code

---

ipn/ipnlocal/local.go

ipn/ipnlocal: fix read of keyExpired outside mutex

---

ipn/ipnlocal/local.go

ipn/ipnlocal: fix another read of keyExpired outside mutex

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
wgengine/magicsock/magicsock.go

ipnlocal, magicsock: add more description to storing last suggested exit node related functions

---

words/scales.txt

Some tails, some scales.
This is my first commit in this package so please let me know if I'm doing something wrong!

words: scaly fruit salad? go fly a kite

---

net/tstun/wrap.go

In a configuration where the local node (ip1) has a different IP (ip2) that it uses to communicate with a peer (ip3) we would do UDP flow tracking on the `ip2->ip3` tuple. When we receive the response from the peer `ip3->ip2` we would dnat it back to `ip3->ip1` which would then not match the flow track state and the packet would get dropped.
To fix this, we should do flow tracking on the `ip1->ip3` tuple instead of `ip2->ip3` which requires doing SNAT after the running filterPacketOutboundToWireGuard.
Updates tailscale/corp#19971, tailscale/corp#8020
(cherry picked from commit 1f51bb68915eec6ba7e44a4fb184ff68b069d9d2)

net/tstun: do SNAT after filterPacketOutboundToWireGuard

---

version/version.go

To be used to in a different repo.

version: add Info func to expose EmbeddedInfo

---

api.md

api.md: document user invite apis

---

api.md

api.md: document device invite apis

---

cmd/containerboot/main.go

See tailscale/tailscale#12156 for context - if a proxy with a tailnet IPv4 address is being created for a backend Service with a ClusterIP that is an IPv6 address, this will likely not work and users will need to configure their proxies to only have IPv6 addresses.
Updates tailscale/tailscale#12156

cmd/containerboot: warn when an ingress proxy with an IPv4 tailnet address is being created for an IPv6 backend(s)

---

cmd/stunc/stunc.go

cmd/stunc: support ipv6 address targets

---

cmd/k8s-operator/svc.go

cmd/k8s-operator: fix typo

---

logtail/backoff/backoff.go

logtail/backoff: update Backoff.BackOff docs

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

ipn/ipnlocal: allowed suggested exit nodes policy

---

ipn/ipnlocal/c2n.go

The `--wait` flag for `systemd-run` was added in systemd 232. While it is quite old, it doesn't hurt to special-case them and skip the `--wait` flag. The consequence is that we lose the update command output in logs, but at least auto-updates will work.
Fixes #12136

ipn/ipnlocal: support c2n updates with old systemd versions

---

cmd/tailscale/cli/up.go

See #12307 for context.
In `1.66.3` we added a new `--stateful-filtering` flag, [explicitly set to `true`](https://github.com/tailscale/tailscale/pull/12025/commits/fcdbecab8ae79d2037039da4b3bbcf2f2d739ef2#diff-c54bd9769f7b92d4fd2054fa4acc55f8e37e2a4d03a4fc07662abb20aff3ccaeR125)
In `1.66.4` we [flipped it to false](https://github.com/tailscale/tailscale/pull/12197/commits/43b463a964cf66556534dc062b7404ad4f766210#diff-c54bd9769f7b92d4fd2054fa4acc55f8e37e2a4d03a4fc07662abb20aff3ccaeR124).
`tailscale/tailscale` container image by default configures tailscale using `tailscale up` command, which requires a once set flag to be explicitly set on subsequent restarts. It looks like a flag that was defaulted to `true` appeared as set and a subsequent upgrade to a version that defaulted the flag to …

cmd/tailscale/cli: allow 'tailscale up' to succeed if a previously set --stateful-filtering flag is unset

---

clientupdate/clientupdate.go

Alpine APK repos are versioned, and contain different package sets. Older APK releases and repos don't have the latest tailscale package. When we report "no update available", check whether pkgs.tailscale.com has a newer tarball release. If it does, it's possible that the system is on an older Alpine release. Print additional messages to suggest the user to upgrade their OS.
Fixes #11309

clientupdate: mention when Alpine system upgrade is needed

---

appc/appconnector.go
appc/appconnector_test.go

So that we have some debugging info if users have trouble with storing the routeInfo.
Updates #11008

appc: log how often routeInfo is stored

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

In order to test the sticky last suggestion code, a test was written for
LocalBackend.SuggestExitNode but it contains a random number generator
which makes writing comprehensive tests very difficult. This doesn't
change how the last suggestion works, but it adds some infrastructure to
make that easier in a later PR.
This adds func parameters for the two randomized parts: breaking ties
between DERP regions and breaking ties between nodes. This way tests can
validate the entire list of tied options, rather than expecting a
particular outcome given a particular random seed.
As a result of this, the global random number generator can be used
rather than seeding a local one each time.
In order to see the tied nodes for the location based (i.e. Mullvad)
case, pickWeighted needed to return a …

ipn/ipnlocal: improve testability of random node selection

---

cmd/natc/natc.go

Now that tsnet supports it, use it.
Updates tailscale/corp#20503

cmd/natc: use ListenPacket

---

cmd/stunstamp/stunstamp.go

Evaluation of remote write errors was using errors.Is() where it should have been using errors.As().
Updates tailscale/corp#20344

cmd/stunstamp: fix remote write retry

---

cmd/natc/natc.go

cmd/natc: add --wg-port flag

---

net/netcheck/netcheck.go
net/netcheck/netcheck_test.go

net/netcheck: flesh out some logging in error paths

---

cmd/stunstamp/api.go
cmd/stunstamp/stunstamp.go
cmd/stunstamp/stunstamp_linux.go

cmd/stunstamp: support probing multiple ports

---

appc/appconnector.go
appc/appconnector_test.go

So that we can debug customer problems more easily.
Updates #11008

appc: log how many routes are being written

---

drive/driveimpl/remote_impl.go
logpolicy/logpolicy.go
safesocket/basic_test.go
safesocket/pipe_windows.go
safesocket/safesocket.go
safesocket/safesocket_js.go
safesocket/safesocket_plan9.go
safesocket/unixsocket.go
tstest/integration/integration_test.go

This adds a variant for Connect that takes in a context.Context which allows passing through cancellation etc by the caller.
Updates tailscale/corp#18266

safesocket: add ConnectContext

---

cmd/k8s-operator/svc.go

Fix the error formatting bug on this issue:
Fixes #12411

tsnet: fix error formatting bug

---

net/dnscache/dnscache.go

As an alternative to #11935 using #12003.
Updates #11935
Change-Id: I05f643fe812ceeaec5f266e78e3e529cab3a1ac3

net/dnscache: use parent context to perform lookup

---

net/dns/resolver/forwarder.go

Fixes tailscale/corp#20677
On macOS (and possibly iOS) sleep/wake, we're encountering a condition where reconfigure the network a little bit too quickly - before apple has set nameservers for our interface. This results in a persistent condition where we have no upstream resolver and fail all forwarded DNS queries.
No upstream nameservers is a legitimate configuration, and we have no  (good) way of determining when Apple is ready - but if we need to forward a query, and we have no nameservers, then something has gone badly wrong and the network is very broken.
A simple fix here is to simply inject a netMon event, which will go through the configuration dance again when we hit the SERVFAIL condition.
Tested by artificially/randomly returning [] for the list of nameservers in the bespoke …

net/dns: re-query system resolvers on no-upstream resolver failure on apple platforms

---

cmd/derper/README.md

Co-authored-by: James Tucker
Co-authored-by: Maisem Ali
Co-authored-by: Andrew Dunham

cmd/derper: add a README

---

wgengine/netstack/netstack.go

Cherry-pick of https://github.com/tailscale/tailscale/pull/12454
Co-authored-by: Andrew Dunham <andrew@du.nham.ca>
Signed-off-by: Irbe Krumina <irbe@tailscale.com>
(cherry picked from commit 88f2d234a4da1abdb31d720beae88c832a624cef)

wgengine/netstack: fix 4via6 subnet routes

---

wgengine/netstack/netstack.go
wgengine/netstack/netstack_test.go

This refactors the logic for determining whether a packet should be sent to the host or not into a function, and then adds tests for it.
Updates #11304
Updates #12448
Change-Id: Ief9afa98eaffae00e21ceb7db073c61b170355e5

wgengine/netstack: add test for #12448

---

client/tailscale/localclient.go
client/tailscale/localclient_test.go
derp/derp_server.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go
ipn/localapi/localapi_test.go

ipn/localapi,client/tailscale,cmd/derper: add WhoIs lookup by nodekey, use in derper

---

cmd/stunc/stunc.go

cmd/stunc: support user-specified port

---

health/health.go

health: fix data race in new warnable code

---

wgengine/filter/filter_test.go

wgengine/filter: add more benchmarks, make names more explicit

---

wgengine/filter/filter_test.go

To show performance during heavy flows on established connections.
BenchmarkFilterMatch/tcp-not-syn-v4-8           52125848                21.46 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           52388781                21.43 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           52916954                21.32 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           52590730                21.43 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           53015923                21.32 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-no-logs-8   122795029                9.783 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-no-logs-8   100000000               10.09 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-no-logs-8   120090948                9.747 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-no-logs-8   122350448 …

wgengine/filter: add TCP non-SYN benchmarks

---

net/ipset/ipset.go

So profiles show more useful names than just func1, func2, func3, etc.
There will still be func1 on them all, but the symbol before will say
what the lookup type is.
Updates #12486

net/ipset: return all closures from named wrappers

---

wgengine/filter/filter_test.go

To show the effects of the flow LRU accounting on e.g. QUIC traffic.
For an open TCP connection:
BenchmarkFilterMatch/tcp-not-syn-v4-8           66602070                16.74 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           67718179                16.60 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           68403351                16.84 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           66076416                16.87 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           67159012                16.67 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           65009526                16.58 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           66588055                16.62 ns/op
BenchmarkFilterMatch/tcp-not-syn-v4-8           63037071                16.58 ns/op …

wgengine/filter: add UDP flow benchmark

---

client/tailscale/devices.go

client/tailscale: add NodeID to device

---

types/logid/id.go
types/logid/id_test.go

The Add method derives a new ID by adding a signed integer to the ID, treating it as an unsigned 256-bit big-endian integer.
We also add Less and Compare methods to PrivateID to provide feature parity with existing methods on PublicID.
Updates tailscale/corp#11038

types/logid: add Add method

---

derp/derp_server.go

Only implemented for the local tailscaled variant for now.

derp: add a verifyClients check to the consistency check

---

hostinfo/hostinfo_windows.go

We need to expand our enviornment information to include info about the Windows store. Thinking about future plans, it would be nice to include both the packaging mechanism and the distribution mechanism.
In this PR we change packageTypeWindows to check a new registry value named MSIEnv, and concatenate that value to "msi/" when present.
Updates [#2790](https://github.com/tailscale/corp/issues/2790)

hostinfo: update Windows hostinfo to include MSIDist registry value

---

cmd/tailscale/cli/netcheck.go

Updates tailscale/corp#20969
Right now, when netcheck starts, it asks tailscaled for a copy of the DERPMap. If it doesn't have one, it makes a HTTPS request to controlplane.tailscale.com to fetch one.
This will always fail if you're on a network with a captive portal actively blocking HTTPS traffic. The code appears to hang entirely because the http.Client doesn't have a Timeout set. It just sits there waiting until the request succeeds or fails.
This adds a timeout of 10 seconds, and logs more details about the status of the HTTPS request.

cli/netcheck: fail with output if we time out fetching a derpmap

---

net/flowtrack/flowtrack.go
net/flowtrack/flowtrack_test.go

I meant to do this in the earlier change and had a git fail.
To atone, add a test too while I'm here.
Updates #12486
Updates #12507

net/flowtrack: fix, test String method

---

derp/derp_server.go

derp: don't verify mesh peers when --verify-clients is set

---

control/controlclient/direct.go
control/controlhttp/client.go

control/controlclient: add more Screen Time blocking detection

---

ipn/ipnlocal/local.go
net/tstun/wrap_test.go
tailcfg/tailcfg.go
wgengine/filter/filter.go
wgengine/filter/filter_test.go
wgengine/filter/filtertype/filtertype.go
wgengine/filter/filtertype/filtertype_clone.go
wgengine/filter/match.go
wgengine/filter/tailcfg.go

See #12542 for background.
Updates #12542

wgengine/filter: support FilterRules matching on srcIP node caps [capver 100]

---

cmd/stunstamp/stunstamp.go

Timeouts could already be identified as NaN values on stunstamp_derp_stun_rtt_ns, but we can't use NaN effectively with promql to visualize them. So, this commit adds a timeouts metric that we can use with rate/delta/etc promql functions.
Updates tailscale/corp#20689

cmd/stunstamp: add explicit metric to track timeout events

---

derp/derp.go
derp/derp_client.go
derp/derp_server.go
derp/derp_test.go

derp: add PeerPresentFlags bitmask to Watch messages

---

cmd/derper/derper.go

cmd/derper: add debug endpoint to adjust mutex profiling rate

---

derp/derp_server.go

sendMeshUpdates tries to write as much as possible without blocking,
being careful to check the bufio.Writer.Available size before writes.
Except that regressed in 6c791f7d60fa which made those messages larger, which
meants we were doing network I/O with the Server mutex held.
Updates tailscale/corp#13945

derp: account for increased size of peerPresent messages in mesh updates

---

derp/derp_server.go

I couldn't convince myself the old way was safe and couldn't lose
writes.
And it seemed too complicated.
Updates tailscale/corp#21104

derp: redo, simplify how mesh update writes are queued/written

---

util/linuxfw/nftables_runner.go

Verify that IPv6 if available if nftable runner for an IPv6 address gets requested.
Updates tailscale/tailscale#12215

util/linuxfw: check if nftable is not nil before using it

---

net/dns/resolver/forwarder.go

Change-Id: I0e815a69ee44ca0ff7c0ea0ca3c6904bbf67ed1f

net/dns/resolver: fix test failure

---

tsweb/tsweb.go
tsweb/tsweb_test.go

To complement the existing `onCompletion` callback, which is called after request handler.
Updates tailscale/corp#17075

tsweb: accept a function to call before request handling

---

wgengine/magicsock/derp.go
wgengine/magicsock/magicsock.go

Updates tailscale/corp#18095
Change-Id: I423adca2de0730092394bb5fd5796cd35557d352

wgengine/magicsock: add more DERP home clientmetrics

---

cmd/derper/README.md

A few other minor language updates.

cmd/derper: add some DERP diagnostics pointers

---

cmd/derper/derper.go

cmd/derper: link to various derper docs in more places

---

cmd/derper/README.md
derp/derp_server.go

cmd/derper: clarify that derper and tailscaled need to be in sync

---

tsnet/tsnet.go

tsnet: do not log an error on shutdown

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

Fixes #12644
Change-Id: I3589b01a9c671937192caaedbb1312fd906ca712

ipn/ipnlocal: fix nil pointer dereference and add related test

---

derp/xdp/xdp_linux.go

BPF links require that the owning FD remains open, this FD is embedded into the RawLink returned by the attach function and must live for the duration of the server.
Updates ENG-4274

derp/xdp: retain the link so that the fd is not closed

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

ipn/ipnlocal: handle auto value for ExitNodeID syspolicy v2

---

cmd/stunstamp/stunstamp.go

cmd/stunstamp: fix handling of invalid DERP map resp

---

version/mkversion/mkversion.go

version/mkversion: allow env config of oss git cache dir

---

.github/workflows/installer.yml
scripts/installer.sh

scripts: don't refresh the pacman repository on Arch

---

wgengine/magicsock/derp.go
wgengine/magicsock/magicsock.go

And fix up a bogus comment and flesh out some other comments.

wgengine/magicsock: use derp-region-as-magic-AddrPort hack in fewer places

---

ipn/ipnlocal/c2n.go

We added a workaround for --wait, but didn't confirm the other flags, which were added in systemd 235 and 236. Check systemd version for deciding when to set all 3 flags.
Fixes #12136

ipn/ipnlocal: gate systemd-run flags on systemd version

---

cmd/natc/natc.go
go.mod
go.sum
net/ipset/ipset.go
net/tsdial/tsdial.go
net/tstun/wrap.go

go.mod: bump bart

---

prober/derp.go

prober: propagate DERPMap request creation errors

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

ipn/ipnlocal: check for offline auto exit node in SetControlClientStatus

---

net/tstun/wrap.go

net/tstun: fix docstring for Wrapper.SetWGConfig

---

logtail/logtail.go

logtail: close idle HTTP connections on shutdown

---

cmd/cloner/cloner.go
cmd/viewer/viewer.go

cmd/cloner, cmd/viewer: add _test prefix for files generated with the test build tag

---

tsweb/tsweb.go
tsweb/tsweb_test.go

Updates #12784
tsweb.StdHandler re-throws panics that it catches, but their stack trace does not point into the handler where the original panic occurred. This PR adds the stack trace containing the handler line into the error message that we log.
It does not however solve the other two issues mentioned in #12784 - that retHandler breaks the panic-chain and gives a useless stack trace for http.Server to log, or that the "Internal server error" message that we generate never makes it back to the client because the http.Server closed the connection when it saw the panic.

tsweb: add stack trace to panic error msg

---

tsweb/tsweb_test.go

tsweb: fix TestStdHandler_panic flake

---

ipn/ipnlocal/local.go

Change-Id: I31dec154aa3b5edba01f10eec37640f631729cb2

ipn/ipnlocal: wait for DERP before auto exit node migration

---

build_docker.sh
hostinfo/hostinfo_linux.go
hostinfo/packagetype_container.go

hostinfo: set Hostinfo.PackageType for mkctr container builds

---

derp/derphttp/derphttp_client.go

... and then do approximately nothing with that information, other than a big TODO. This is mostly me relearning this code and leaving breadcrumbs for others in the future.
Updates #12724

derp/derphttp: determine whether a region connect was to non-ideal node

---

tsweb/tsweb.go
tsweb/tsweb_test.go

Fixes #12784
When a panic hits http.Server then it closes the connection before the response is sent to the client. Even if you explicitly flush the response in the handler. So here we change tsweb's handlers to swallow panics when it can be confident that the stack trace has been logged.

tsweb: swallow panics

---

wgengine/router/ifconfig_windows.go

Windows requires routes to have a nexthop. Routes created using the interface's local IP address or an unspecified IP address ("0.0.0.0" or "::") as the nexthop are considered on-link routes. Notably, Windows treats on-link subnet routes differently, reserving the last IP in the range as the broadcast IP and therefore prohibiting TCP connections to it, resulting in WSA error 10049: "The requested address is not valid in its context". This does not happen with single-host routes, such as routes to Tailscale IP addresses, but becomes a problem with advertised subnets when all IPs in the range should be reachable.
Before Windows 8, only routes created with an unspecified IP address were considered on-link, so our previous approach of using the interface's own IP as the nexthop likely worked …

wgengine/router: use quad-100 as the nexthop on Windows

---

ipn/ipnlocal/local.go

Change-Id: I6d396780b058ff0fbea0e9e53100f04ef3b76339

ipn/ipnlocal: add comment explaining auto exit node migration

---

tsweb/tsweb.go
tsweb/tsweb_test.go

tsweb: log cancelled requests as 499

---

types/opt/value.go

types/opt: add (Value[T]).GetOr(def T) T method

---

tsweb/tsweb.go
tsweb/tsweb_test.go

Updates #12141
Fixes tailscale/corp#21858
* Any time a request.Context has been cancelled when we're processing an error, we'll log it as a 499. We try to keep the original error around if it contains a context.Cancelled or http.ErrAbortHandler. If not, we wrap it with a context.Context too.
* Any time we log a 499 but already sent a different response code to a client (before the request context errored), we include the original response code in the error message, e.g. "context cancelled (original code 200)" could indicate that we sent a 200 OK but the client disconnected when we were transmitting the response body. It's not guaranteed that the client received the 200 OK because it gets buffered.
* I've exported the tsweb.WriteHTTPError function for us to make use of instead of …

tsweb: log all cancellations as 499s

---

wgengine/netstack/netstack.go

wgengine/netstack: simplify netaddrIPFromNetstackIP

---

cmd/tailscale/cli/netcheck.go

Updates #12954
Change-Id: Ic14f037b48a79b1263b140c6699579b466d89310

cmd/tailscale/cli: release portmap after netcheck

---

words/scales.txt

words: add some associated with scales

---

health/health.go

health: don't show login error details with context cancelations

---

net/captivedetection/captivedetection.go

Updates tailscale/tailscale#1634
This PR optimizes captive portal detection on Android and iOS by excluding cellular data interfaces (`pdp*` and `rmnet*`). As cellular networks do not present captive portals, frequent network switches between Wi-Fi and cellular would otherwise trigger captive detection unnecessarily, causing battery drain.

net/captivedetection: exclude cellular data interfaces

---

wgengine/magicsock/cloudinfo.go
wgengine/magicsock/cloudinfo_nocloud.go
wgengine/magicsock/cloudinfo_test.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

Updates #12774
Change-Id: I1661b6a2da7966ab667b075894837afd96f4742f

wgengine/magicsock: use cloud metadata to get public IPs

---

util/winutil/gp/policylock_windows.go

util/winutil/gp: fix a busy loop bug

---

tsweb/tsweb_test.go

tsweb: mark TestStdHandler_ConnectionClosedDuringBody flaky

---

tstest/integration/integration_test.go

tstest/integration: mark TestNATPing flaky

---

net/socks5/socks5.go
net/socks5/socks5_test.go

net/socks5: support UDP

---

cmd/derper/derper.go
cmd/derper/derper_test.go
derp/derphttp/derphttp_server.go

cmd/derper: move 204 handler from package main to derphttp

---

prober/prober.go
prober/status.go
prober/status.html

prober: make status page more clear

---

tsweb/tsweb_test.go

tsweb: fix TestStdHandler_ConnectionClosedDuringBody flake

---

tstest/natlab/vnet/conf.go
tstest/natlab/vnet/pcap.go
tstest/natlab/vnet/vnet.go

tstest/natlab/vnet: capture network wan/lan interfaces

---

client/tailscale/localclient.go

Similar to UseSocketOnly, but pulled out separately in case
people are doing unknown weird things.
Updates #13038

client/tailscale: add LocalClient.OmitAuth for tests

---

cmd/tta/fw_linux.go
cmd/tta/tta.go
cmd/vnet/run-krazy.sh
logpolicy/logpolicy.go
net/tlsdial/tlsdial.go
tstest/integration/nat/nat_test.go
tstest/natlab/vnet/conf.go
tstest/natlab/vnet/vnet.go
wgengine/magicsock/magicsock_linux.go

In particular, tests showing that #3824 works. But that test doesn't actually work yet; it only gets a DERP connection. (why?)
Updates #13038

cmd/tta, vnet: add host firewall, env var support, more tests

---

tstest/integration/nat/nat_test.go

tstest/integration/nat: annotate test 'want' values, fail on mismatch

---

gokrazy/tsapp/config.json
tstest/integration/nat/nat_test.go
tstest/natlab/vnet/conf.go

tstest/natlab/vnet: [4 commits]

---

cmd/containerboot/main.go

Add functionality to optionally serve an HTTP health check endpoint (off by default) for containerized tailscale.
Users can enable health check endpoint by setting TS_HEALTHCHECK_ADDR_PORT env var to `[<addr>]:<port>`.
Containerboot will then serve an unauthenticatd HTTP health check at `/healthz` at that address.
The health check returns 200 OK if the node has at least one tailnet IP address, else returns 503.
I have tested that this works as a backend target HTTP health check for AWS NLB.
Also have tested it as a [readiness probe for Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes):
```
...
containers:
- name: tailscale
env:
- name: POD_IP
valueFrom:
fieldRef:
apiVersion: v1
fieldPath: status.podIP …
```

cmd/containerboot: optionally serve health check endpoint

---

util/codegen/codegen.go
util/codegen/codegen_test.go

fix: codegen error when using anonymous struct #13076

util/codegen: codegen not using qualified name when using anonymous struct

---

health/health.go
wgengine/magicsock/magicsock.go

wgengine/magicsock: log when a ReceiveFunc fails

---

safeweb/http.go
safeweb/http_test.go

Updates https://github.com/tailscale/corp/issues/14881

safeweb: add Server.Close method

---

Makefile
ssh/tailssh/incubator.go
ssh/tailssh/tailssh_integration_test.go
ssh/tailssh/testcontainers/Dockerfile
tailcfg/tailcfg.go

Fixes https://github.com/tailscale/tailscale/issues/12849
This [follow-on PR](https://github.com/tailscale/tailscale/pull/13048) allows selectively enabling V2 behavior for specific machines using a node attribute.

ssh/tailssh: fix SSH on busybox systems

---

ssh/tailssh/incubator.go
ssh/tailssh/privs_test.go
ssh/tailssh/tailssh_integration_test.go
ssh/tailssh/testcontainers/Dockerfile

…e can chdir to it
Fixes #13120

ssh/tailssh: only chdir incubator process to user's homedir when necessary and possible

---

cmd/tailscale/cli/debug.go

To avoid dig vs nslookup vs $X availability issues between
OSes/distros. And to be in Go, to match the resolver we use.
Updates #13038

cmd/tailscale/cli: add debug command to do DNS lookups portably

---

ipn/ipnlocal/local.go
types/views/views.go
types/views/views_test.go

types/views: add Slice.All iterator

---

cmd/tta/tta.go
cmd/vnet/vnet-main.go
gokrazy/natlabapp/builddir/tailscale.com/go.sum
tstest/natlab/vnet/conf.go
tstest/natlab/vnet/vnet.go

Multiple natlab commits, pulled out of the meta IPv6 PR to make it smaller.
Updates #13038

natlab: [multiple commits]

---

tstest/natlab/vnet/vnet.go

And sprinkle some more docs around.
Updates #13038

tstest/natlab: respect NATTable interface's invalid-means-drop everywhere

---

cmd/vnet/vnet-main.go

cmd/vnet: omit log spam when backend status hasn't changed

---

tstest/integration/integration_test.go

tstest/integration: exercise TCP DNS queries against quad-100

---

tstest/integration/integration_test.go

tstest/integration: change log.Fatal() to t.Fatal()

---

tstest/natlab/vnet/pcap.go

So that we can view the pcap as we debug interactively.
Updates #13038

tstest/natlab/vnet: flush and sync pcap file after every packet

---

cmd/tta/tta.go
cmd/vnet/run-krazy.sh
cmd/vnet/vnet-main.go
tstest/integration/nat/nat_test.go
tstest/natlab/vnet/conf.go
tstest/natlab/vnet/vip.go
tstest/natlab/vnet/vnet.go

tstest/natlab/vnet: add start of IPv6 support

---

ipn/ipnlocal/local.go

On a major link change the LAN routes may change, so on linkChange where ChangeDelta.Major, we need to call authReconfig to ensure that new routes are observed and applied.
Updates tailscale/corp#22574

ipn/ipnlocal: update routes on link change with ExitNodeAllowLANAccess

---

types/opt/bool.go
types/opt/bool_test.go

types/opt: add BoolFlag for setting Bool value as a flag

---

cmd/tta/tta.go
logpolicy/logpolicy.go
tstest/integration/nat/nat_test.go
tstest/natlab/vnet/conf.go
tstest/natlab/vnet/vnet.go

tstest/natlab/vnet: fix IPv6 [multiple commits]

---

tstest/natlab/vnet/conf.go
tstest/natlab/vnet/vnet.go
tstest/natlab/vnet/vnet_test.go

And refactor some of vnet.go for testability.
The only behavioral change (with a new test) is that ethernet
broadcasts no longer get sent back to the sender.
Updates #13038

tstest/natlab/vnet: start adding tests

---

tstest/natlab/vnet/vnet.go
tstest/natlab/vnet/vnet_test.go

To test how virtual machines connect to the natlab vnet code.
Updates #13038

tstest/natlab/vnet: add qemu + Virtualization.framework protocol tests

---

tstest/integration/integration_test.go
wgengine/netstack/netstack.go

When the TS_DEBUG_NETSTACK_LOOPBACK_PORT environment variable is set,
netstack will loop back (dnat to addressFamilyLoopback:loopbackPort)
TCP & UDP flows originally destined to localServicesIP:loopbackPort.
localServicesIP is quad-100 or the IPv6 equivalent.
Updates tailscale/corp#22713

wgengine/netstack: implement netstack loopback

---

flake.lock
flake.nix

Updates https://github.com/tailscale/tailscale/issues/12912

nix: update nix and use go 1.23

---

tstest/integration/integration_test.go

tstest/integration: add UDP netstack loopback integration test

---

net/tstun/wrap.go

net/tstun: clarify GROFilterFunc *gro.GRO usage

---

drive/driveimpl/remote_impl.go

This allows Taildrive to work on systems like Busybox that don't have sudo.
Fixes #12282

drive/driveimpl: use su instead of sudo

---

tstest/natlab/vnet/conf.go
tstest/natlab/vnet/vnet.go
tstest/natlab/vnet/vnet_test.go

tstest/natlab/vnet: add syslog tests

---

tstest/natlab/vnet/vnet.go
tstest/natlab/vnet/vnet_test.go

No need to make callers specify the redundant IP version or
TTL/HopLimit or EthernetType in the common case. The mkPacket helper
can set those when unset.
And use the mkIPLayer in another place, simplifying some code.
Updates #13038

tstest/natlab/vnet: move some boilerplate to mkPacket helper

---

ipn/ipnlocal/network-lock.go

ipn/ipnlocal: fix a nil pointer dereference when serving /localapi/v0/tka/status

---

wgengine/magicsock/magicsock.go

Fixes #13332
Updates tailscale/corp#20732

wgengine/magicsock: fix panic regression from cryptokey routing change

---

tstest/integration/nat/nat_test.go
tstest/natlab/vnet/conf.go
tstest/natlab/vnet/vnet.go

This reproduces the bug report from
https://github.com/tailscale/tailscale/issues/13346
It does not yet fix it.
Updates #13346

tstest/natlab: add dual stack with blackholed IPv4 test

---

net/dns/manager_darwin.go

Updates tailscale/tailscale#177
It appears that the OSS distribution of `tailscaled` is currently unable to get the current system base DNS configuration, as GetBaseConfig() in manager_darwin.go is unimplemented. This PR adds a basic implementation that reads the current values in `/etc/resolv.conf`, to at least unblock DNS resolution via Quad100 if `--accept-dns` is enabled.

net/dns: support GetBaseConfig on Darwin OSS tailscaled

---

cmd/tailscale/cli/dns-status.go

And a grammatical nit.
Updates #12912

cmd/tailscale/cli: use new Go 1.23 slices.Sorted

---

control/controlclient/map.go
envknob/envknob.go
net/netcheck/netcheck_test.go
wgengine/magicsock/derp.go

all: use new Go 1.23 slices.Sorted more

---

health/health.go

health: fix magicsockReceiveFuncWarnable health clearing

---

cmd/stunstamp/stunstamp.go
cmd/stunstamp/stunstamp_linux.go

cmd/stunstamp: cleanup timeout and interval constants

---

cmd/natc/natc.go

cmd/natc: fix nil pointer

---

ipn/ipnlocal/local.go
proxymap/proxymap.go
wgengine/netstack/netstack.go

ipnlocal,proxymap,wgengine/netstack: add optional WhoIs/proxymap debug

---

.github/workflows/test.yml

.github: enable fuzz testing again (go1.23)

---

derp/derp_server.go
derp/derp_test.go

73280595a8880bdca for #2751 added a "clientSet" interface to
distinguish the two cases of a client being singly connected (the
common case) vs tolerating multiple connections from the client at
once. At the time (three years ago) it was kinda an experiment
and we didn't know whether it'd stop the reconnect floods we saw
from certain clients. It did.
So this promotes it to a be first-class thing a bit, removing the
interface. The old tests from 73280595a were invaluable in ensuring
correctness while writing this change (they failed a bunch).
But the real motivation for this change is that it'll permit a future
optimization to add flow tracking for stats & performance where we
don't contend on Server.mu for each packet sent via DERP. Instead,
each client can track its active flows and hold …

derp: unify server's clientSet interface into concrete type

---

derp/derp_server.go
ssh/tailssh/tailssh.go
util/linuxfw/helpers.go
util/slicesx/slicesx.go
util/slicesx/slicesx_test.go

And update a few callers as examples of motivation. (there are a
couple others, but these are the ones where it's prettier)

util/slicesx: add FirstEqual and LastEqual

---

tstest/integration/nat/nat_test.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_default.go
wgengine/magicsock/magicsock_linux.go

Updates #13140
Change-Id: Ica85b2ac8ac7eab4ec5413b212f004aecc453279

wgengine/magicsock: disable raw disco by default; add envknob to enable

---

derp/derp_server.go

In prep for upcoming flow tracking & mutex contention optimization
changes, this change refactors (subjectively simplifying) how the DERP
Server accounts for which peers have written to which other peers, to
be able to send PeerGoneReasonDisconnected messages to writes to
uncache their DRPO (DERP Return Path Optimization) routes.
Notably, this removes the Server.sentTo field which was guarded by
Server.mu and checked on all packet sends. Instead, the accounting is
moved to each sclient's sendLoop goroutine and now only needs to
acquire Server.mu for newly seen senders, the first time a peer sends
a packet to that sclient.
This change reduces the number of reasons to acquire Server.mu
per-packet from two to one. Removing the last one is the subject of an
upcoming change.
Updates #3560 …

derp: refactor DERP server's peer-gone watch mechanism

---

wgengine/magicsock/magicsock.go

Updates #13484
Updates tailscale/corp#17879

wgengine/magicsock: add side-effect-free function for netcheck UDP sends

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: fix sendUDPStd docs

---

ipn/ipnlocal/drive.go
ipn/ipnlocal/local.go
types/views/views.go
types/views/views_test.go

And convert a all relevant usages.
Updates #12912

types/views: add SliceView.All iterator

---

derp/derp_client.go
derp/derphttp/mesh_client.go

derp: document the RunWatchConnectionLoop callback gotchas

---

health/health.go
health/warnings.go

health: clean up updateBuiltinWarnablesLocked a bit, fix DERP warnings

---

cmd/k8s-operator/deploy/chart/values.yaml
cmd/k8s-operator/deploy/crds/tailscale.com_connectors.yaml
cmd/k8s-operator/deploy/crds/tailscale.com_proxyclasses.yaml
cmd/k8s-operator/deploy/manifests/operator.yaml
k8s-operator/api.md
k8s-operator/apis/v1alpha1/types_connector.go
k8s-operator/apis/v1alpha1/types_proxyclass.go

cmd/k8s-operator, k8s-operator: fix outdated kb links

---

wgengine/userspace.go

wgengine: make opts.Metrics mandatory

---

ipn/ipnlocal/local.go
tsnet/tsnet_test.go
tstest/integration/testcontrol/testcontrol.go

ipn/ipnlocal: add advertised and primary route metrics

---

cmd/k8s-operator/operator_test.go
cmd/k8s-operator/sts.go
cmd/k8s-operator/testutils_test.go

This PR updates the Kubernetes operator reconciler to remove the auth key from proxies's tailscaled configs, once the proxies have been assumed to have logged in.
The operator creates a non-reusable auth key for each of the cluster proxies that it creates and puts in the tailscaled configfile mounted to the proxies.
The proxies are always tagged, and their state is persisted in a Kubernetes Secret, so their node keys are expected to never be regenerated, so that they don't need to re-auth.
Some tailnet configurations however have seen issues where the auth keys being left in the tailscaled configfile cause the proxies to end up in unauthorized state after a restart at a later point in time, see #13451
Currently, we have not found a way to reproduce this issue, however this commit removes …

cmd/k8s-operator: remove auth key once proxy has logged in

---

logpolicy/logpolicy.go

logpolicy: don't create a filch buffer if logging is disabled

---

ssh/tailssh/accept_env.go
ssh/tailssh/accept_env_test.go
ssh/tailssh/incubator.go
ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_integration_test.go
ssh/tailssh/tailssh_test.go

Add logic to set environment variables that match the SSH rule's `acceptEnv` settings in the SSH session's environment.
Updates https://github.com/tailscale/corp/issues/22775

ssh: Add logic to set accepted environment variables in SSH session

---

control/controlhttp/client.go
health/health.go

control/controlhttp: fix connectivity on Alaska Air wifi

---

net/portmapper/upnp.go
net/portmapper/upnp_test.go

We were previously not checking that the external IP that we got back from a UPnP portmap was a valid endpoint; add minimal validation that this endpoint is something that is routeable by another host.
Updates tailscale/corp#23538
Change-Id: Id9649e7683394aced326d5348f4caa24d0efd532

net/portmapper: don't return unspecified/local external IPs

---

docs/windows/policy/en-US/tailscale.adml
docs/windows/policy/tailscale.admx

docs/windows/policy: add ADMX policy setting to configure the AuthKey

---

control/controlclient/direct.go

control/controlclient: bound ReportHealthChange context lifetime to Direct client's

---

tstest/test-wishlist.md

Of tests we wish we could easily add. One day.
Updates #13038

tstest: add the start of a testing wishlist

---

ipn/ipnlocal/local.go

We were selectively uploading it, but we were still gathering it,
which can be a waste of CPU.
Also remove a bunch of complexity that I don't think matters anymore.
And add an envknob to force service collection off on a single node,
even if the tailnet policy permits it.
Fixes #13463

ipn/ipnlocal: don't run portlist code unless service collection is on

---

tailcfg/tailcfg.go

Updates tailscale/corp#23574.
Question to reviewer: does this require a bump of CapabilityVersion?

tailcfg: add func to check for known valid ServiceProtos

---

wgengine/netstack/netstack.go
wgengine/netstack/netstack_userping.go
wgengine/netstack/netstack_userping_test.go

Hacky temporary workaround until we do #13654 correctly.
Updates #13654

wgengine/netstack: check userspace ping success on Windows

---

ssh/tailssh/incubator.go

ssh/tailssh: pass window size pixels in IoctlSetWinsize events

---

safeweb/http.go
safeweb/http_test.go

Add the ability to specify Strict-Transport-Security options in response to BrowserMux HTTP requests in safeweb.
Updates https://github.com/tailscale/corp/issues/23375

safeweb: add StrictTransportSecurityOptions config

---

hostinfo/hostinfo.go

hostinfo: update SetPackage doc with new Android values

---

wgengine/pendopen.go

Like we do for the ones on iOS.
As a bonus, this removes a caller of tsaddr.IsTailscaleIP which we
want to revamp/remove soonish.
Updates #13687

wgengine: stop conntrack log spam about Canonical net probes

---

assert_ts_toolchain_match.go
version-embed.go
version_tailscale_test.go

tailscaleroot: panic if tailscale_go build tag but Go toolchain mismatch

---

derp/derp_server.go

derp: add server metric for batch write sizes

---

net/netcheck/netcheck.go

Updates #13728
Change-Id: I1e8319d6b2da013ae48f15113b30c9333e69cc0b

net/netcheck: don't panic if a region has no Nodes

---

net/sockstats/sockstats_tsgo.go

net/sockstats: quiet some log spam in release builds

---

kube/egressservices/egressservices.go
kube/egressservices/egressservices_test.go

Instead of converting our PortMap struct to a string during marshalling for use as a key, convert the whole collection of PortMaps to a list of PortMap objects, which improves the readability of the JSON config while still keeping the data structure we need in the code.
The updated tests nicely illustrate the difference in the config format, and I tested the whole end to end flow with this update. If testing, remember to deploy both the proxy image and the operator image.
Updates #13406, #13531

kube/egressservices: improve egress ports config readability

---

util/syspolicy/setting/snapshot.go

util/syspolicy/setting: update Snapshot to use Go 1.23 iterators

---

syncs/syncs.go
syncs/syncs_test.go
taildrop/taildrop.go
tstest/natlab/vnet/vnet.go
wgengine/netstack/netstack.go

syncs: delete Map.Range, update callers to iterators

---

ipn/conffile/conffile.go
ipn/conffile/conffile_hujson.go
tstest/iosdeps/iosdeps_test.go

ipn/conffile: don't depend on hujson on iOS/Android

---

ssh/tailssh/incubator.go

This allows passing through any environment variables that we set ourselves, for example DBUS_SESSION_BUS_ADDRESS.
Updates #11175

ssh/tailssh: calculate passthrough environment at latest possible stage

---

tstest/resource.go

tstest: avoid Fatal in ResourceCheck to show panic

---

tsnet/tsnet_test.go
util/clientmetric/clientmetric.go
util/clientmetric/clientmetric_test.go
wgengine/magicsock/derp.go
wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

This PR adds metrics in quite performance sensitive part of the code, please help me figure if this is approach is reasonable.

wgengine: instrument with usermetrics

---

cmd/tailscale/cli/advertise.go
cmd/tailscale/cli/cli.go
cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/set.go
cmd/tailscale/cli/up.go
ipn/ipn_clone.go
ipn/ipn_view.go
ipn/prefs.go
ipn/prefs_test.go
tailcfg/tailcfg.go

cmd/tailscale,ipn,tailcfg: add `tailscale advertise` subcommand behind envknob

---

scripts/installer.sh

This fixes the installation on newer Fedora versions that use dnf5 as the 'dnf' binary.
Updates #13828
Change-Id: I39513243c81640fab244a32b7dbb3f32071e9fce

scripts/installer.sh: support DNF5

---

derp/derp_server.go

derp: give trusted mesh peers longer write timeouts

---

net/tstun/tap_linux.go
net/tstun/wrap.go

Few changes:
- Instead of using a hardcoded IP, get it from the netmap.
- Use 100.100.100.100 as the gateway IP
- Use the /10 CGNAT range instead of a random /24
Updates #2589

net/tstun: use /10 as subnet for TAP mode; read IP from netmap

---

health/health.go

health: fix spurious warning about DERP home region '0'

---

cmd/k8s-operator/operator_test.go
cmd/k8s-operator/svc.go

Addresses https://github.com/tailscale/tailscale/issues/13671

cmd/k8s-operator: validate tailnet-ip annotation IP addr

---

wgengine/magicsock/endpoint.go

wgengine/magicsock: fix stats packet counter on derp egress

---

wgengine/magicsock/derp.go

This adds additional logging on DERP home changes to allow better troubleshooting.
Updates tailscale/corp#18095

wgengine/magicsock: log home DERP changes with latency

---

util/syspolicy/source/env_policy_store.go
util/syspolicy/source/env_policy_store_test.go

... all prefixed with TS_DEBUGSYSPOLICY_*.
Updates #13193
Updates #12687
Updates #13855

util/syspolicy/source: put EnvPolicyStore env keys in their own namespace

---

util/syspolicy/policy_keys.go

Updates https://github.com/tailscale/corp/issues/23789

util/syspolicy: add policy key for onboarding flow visibility

---

net/netcheck/netcheck.go
net/netcheck/netcheck_test.go

Cherry-pick into release branch.
---
In an environment with unstable latency, such as upstream bufferbloat, there are cases where a full netcheck could drop the prior preferred DERP (likely home DERP) from future netcheck probe plans. This will then likely result in a home DERP having a missing sample on the next incremental netcheck, ultimately resulting in a home DERP move.
This change does not fix our overall response to highly unstable latency, but it is an incremental improvement to prevent single spurious samples during a full netcheck from alone triggering a flapping condition, as now the prior changes to include historical latency will still provide the desired resistance, and the home DERP should not move unless latency is consistently worse over a 5 minute period.
Note that …

net/netcheck: ensure prior preferred DERP is always in netchecks

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

We were only updating the ProfileManager and not going down the EditPrefs path which meant the prefs weren't applied till either the process restarted or some other pref changed.
This makes it so that we reconfigure everything correctly when ReloadConfig is called.
Updates #13032

ipn/ipnlocal: reload prefs correctly on ReloadConfig

---

net/socks5/socks5.go
net/socks5/socks5_test.go

(fork of CL #13535 because I didn't have permission to rebase it to kick-off CI)

net/socks5: optimize UDP relay

---

cmd/tsconnect/common.go

Thanks to @davidbuzz for raising the issue in #13973.
Fixes #8272
Fixes #13973

cmd/tsconnect: block after starting esbuild dev server

---

tsnet/tsnet.go

Pulled of otherwise unrelated PR #13884.

tsnet: add accessor to get tsd.System

---

tsweb/varz/varz.go

Updates tailscale/corp#23546 (noticed when doing this)

tsweb/varz: optimize some allocs, add helper func for others

---

safeweb/http.go

Updates #14047
Change-Id: I2d20454c715b11ad9c6aad1d81445e05a170c3a2

safeweb: add a Shutdown method to the Server type

---

cmd/tsconnect/wasm/wasm_js.go
ipn/ipnlocal/drive.go
ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/serve.go
ipn/ipnlocal/web_client.go
net/ipset/ipset.go
net/tsaddr/tsaddr.go
net/tsdial/dnsmap.go
tsnet/tsnet.go
types/netmap/netmap.go
util/set/slice.go
wgengine/magicsock/debughttp.go
wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock.go
wgengine/netstack/netstack.go
wgengine/pendopen.go
wgengine/userspace.go
wgengine/wgcfg/nmcfg/nmcfg.go

This gets close to all of the remaining ones.
Updates #12912

all: use iterators over slice views more

---

words/scales.txt

https://portsmouthbrewery.com/shilling-scale/
Any scale that includes "wee heavy" is a scale worth including.
Updates #words

words: add a scale

---

words/scales.txt

We were missing some relatively obvious ones :sweat_smile: 
Updates tailscale/corp#14698

words: scale up our word count

---

words/scales.txt

https://en.wikipedia.org/wiki/Scoville_scale
Updates #words

words: Add scoville to scales.txt

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/cli_test.go

cmd/tailscale/cli: add "help" alias for --help

---

ipn/ipnlocal/c2n.go
ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go

ipn,tailcfg: add VIPService struct and c2n to fetch them from client

---

net/captivedetection/captivedetection.go
net/captivedetection/captivedetection_test.go

We see tons of logs of the form:
2024/11/15 19:57:29 netcheck: [v2] 76 available captive portal detection endpoints: [Endpoint{URL="http://192.73.240.161/generate_204", StatusCode=204, ExpectedContent="", SupportsTailscaleChallenge=true, Provider=DERPMapOther} Endpoint{URL="http://192.73.240.121/generate_204", StatusCode=204, ExpectedContent="", SupportsTailscaleChallenge=true, Provider=DERPMapOther} Endpoint{URL="http://192.73.240.132/generate_204", StatusCode=204, ExpectedContent="",
11:58SupportsTailscaleChallenge=true, Provider=DERPMapOther} Endpoint{URL="http://209.177.158.246/generate_204", StatusCode=204, ExpectedContent="", SupportsTailscaleChallenge=true, Provider=DERPMapOther} Endpoint{URL="http://209.177.158.15/generate_204", StatusCode=204, ExpectedContent="", …

net/captivedetection: replace 10k log lines with ... less

---

go.mod
go.sum

go.mod: bump tailscale/wireguard-go

---

version/version.go
version/version_checkformat.go
version/version_internal_test.go

version: validate Long format on Android builds

---

version/version_checkformat.go
version/version_internal_test.go

version: fix earlier test/wording mistakes

---

cmd/k8s-operator/deploy/chart/templates/ingressclass.yaml
cmd/k8s-operator/deploy/chart/values.yaml

Add a variable to the k8s operator values which defaults to true, and use that to decide whether to install the IngressClass.
Links to #14152
Fixes tailscale/tailscale#14152

Make the deployment of an IngressClass optional with a default to true

---

ipn/ipnlocal/local.go

In this PR, we update `LocalBackend` to rebuild the set of allowed suggested exit nodes whenever the `AllowedSuggestedExitNodes` syspolicy setting changes. Additionally, we request a new suggested exit node when this occurs, enabling its use if the `ExitNodeID` syspolicy setting is set to `auto:any`.
Updates #12687

ipn/ipnlocal: rebuild allowed suggested exit nodes when syspolicy changes

---

net/netmon/netmon_darwin.go

Updates #14201
Updates golang/go#70528

net/netmon: catch ParseRIB panic to gather buffer data

---

ipn/localapi/localapi.go

ipn/localapi: count localapi requests to metric endpoints

---

net/netcheck/netcheck.go
net/netcheck/netcheck_test.go

net/netcheck: clean up ICMP probe AddrPort lookup

---

health/health_test.go

health: fix TestHealthMetric to pass on release branch

---

derp/derp_server.go
derp/derp_test.go

Use envknob to configure the per client send queue depth for the derp server.
Fixes tailscale/corp#24978

derp/server: add env var for configuring queue depth

---

prober/derp.go

1ed9bd76d682299376f404521cf1958a7f9bea7a meant to make tunAddress be optional.
Updates tailscale/corp#24635

prober: fix WithBandwidthProbing behavior with optional tunAddress

---

cmd/derper/bootstrap_dns_test.go
docs/windows/policy/en-US/tailscale.adml
ipn/ipnserver/proxyconnect.go
logpolicy/logpolicy.go
logpolicy/logpolicy_test.go
logtail/api.md
logtail/example/logadopt/logadopt.go
logtail/example/logreprocess/demo.sh
logtail/example/logreprocess/logreprocess.go
logtail/logtail.go
net/tlsdial/tlsdial.go
tsnet/tsnet.go
tstest/natlab/vnet/vip.go
tstest/natlab/vnet/vnet.go

Switch logging service from log.tailscale.io to log.tailscale.com

---

syncs/syncs.go
syncs/syncs_test.go

MutexValue is simply a value guarded by a mutex.
For any type that is not pointer-sized,
MutexValue will perform much better than AtomicValue since it will not incur an allocation boxing the value into an interface value (which is how Go's atomic.Value is implemented under-the-hood.

syncs: add MutexValue

---

cmd/systray/systray.go

cmd/systray: add account switcher

---

cmd/systray/systray.go

Bring UI closer to macOS and windows:
- split login and tailnet name over separate lines
- render profile picture (with very simple caching)
- use checkbox to indicate active profile. I've not found any desktops that can't render checkboxes, so I'd like to explore other options if needed.
before and after:
Updates #1708

cmd/systray: improve profile menu

---

cmd/systray/systray.go

The new menu delay added to fix libdbusmenu systrays causes problems with KDE. Given the state of wildly varying systray implementations, I suspect we may need more desktop-specific hacks, so I'm setting this up to accommodate that.
Updates #1708
Updates #14431

cmd/systray: remove new menu delay on KDE

---

cmd/systray/systray.go

This commit builds the exit node menu including the recommended exit node, if available, as well as tailnet and mullvad exit nodes.
This does not yet update the menu based on changes in exit node outside of the systray app, which will come later.  This also does not include the ability to run as an exit node.
Updates #1708

cmd/systray: add exit nodes menu

---

cmd/systray/systray.go

cmd/systray: add visual workarounds for gnome, mac, and windows

---

util/stringsx/stringsx.go
util/stringsx/stringsx_test.go

Noted as useful during review of #14448.
Updates #14457

util/stringsx: add package for extra string functions, like CompareFold

---

cmd/systray/systray.go

- rebuild menu when prefs change outside of systray, such as setting an exit node
- refactor onClick handler code
- compare lowercase country name, the same as macOS and Windows (now sorts Ukraine before USA)
- fix "connected / disconnected" menu items on stopped status
- prevent nil pointer on "This Device" menu item
Updates #1708

cmd/systray: rebuild menu on pref change, assorted other fixes

---

scripts/installer.sh

Fixes #13955
Tested working in VM

scripts/installer.sh: allow CachyOS for Arch packages

---

cmd/systray/systray.go

Move a number of global state vars into the Menu struct, keeping things better encapsulated. The systray package still relies on its own global state, so only a single Menu instance can run at a time.
Move a lot of the initialization logic out of onReady, in particular fetching the latest tailscale state. Instead, populate the state before calling systray.Run, which fixes a timing issue in GNOME (#14477).
This change also creates a separate bgContext for actions not tied menu item clicks. Because we have to rebuild the entire menu regularly, we cancel that context as needed, which can cancel subsequent updateState calls.
Also exit cleanly on SIGINT and SIGTERM.
Updates #1708
Fixes #14477

cmd/systray: update state management and initialization

---

control/controlclient/direct.go
control/controlclient/noise.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go
tailcfg/tailcfg.go

Updates tailscale/corp#24690
Updates #4077

all: add means to set device posture attributes from node

---

control/controlclient/map.go
envknob/logknob/logknob.go
envknob/logknob/logknob_test.go
ipn/ipnlocal/local.go
ipn/ipnlocal/serve.go
tailcfg/tailcfg.go
types/netmap/netmap.go

And misc cleanup along the way.
Updates #12912

all: use iterators in more places instead of Range funcs

---

README.md
client/tailscale/localclient.go
version-embed.go
wgengine/filter/filter_test.go
wgengine/netstack/gro/gro.go

I was taking a look at the Tailscale repository for the first time and was getting familiar with the `Makefile` contained within. These issues popped up  and were some quick and easy fixes. This was also a good excuse to become familiar with the contribution process as well.

Fix various linting, vet & static check issues

---

ipn/backend.go

Updates #1909 (noticed while working on that)

ipn: declare NotifyWatchOpt consts without using iota

---

tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go
tstest/integration/testcontrol/testcontrol.go

tailcfg: remove unused User fields

---

ipn/ipnlocal/local.go
util/goroutines/goroutines.go
util/goroutines/tracker.go

Updates #14520
Updates #14517 (in that I pulled this out of there)

ipn/ipnlocal, util/goroutines: track goroutines for tests, shutdown

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

In the process, because I needed it for testing, make all
LocalBackend-managed goroutines be accounted for. And then in tests,
verify they're no longer running during LocalBackend.Shutdown.

ipn/ipnlocal: move where auto exit node selection happens

---

cmd/derper/mesh.go

Include the mesh log prefix in all mesh connection setup.
Updates tailscale/corp#25653

cmd/derper: improve logging on derp mesh connect

---

control/controlclient/noise.go
control/controlclient/noise_test.go

Fixes tailscale/tailscale#14563
When creating a `NoiseClient`, ensure that if any private IP address is provided, with both an `http` scheme and an explicit port number, we do not ever attempt to use HTTPS. We were only handling the case of `127.0.0.1` and `localhost`, but `192.168.x.y` is a private IP as well. This uses the `netip` package to check and adds some logging in case we ever need to troubleshoot this.

controlclient: do not set HTTPS port for any private coordination server IP

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
ipn/serve.go

This commit updates the VIPService c2n endpoint on client to response with actual VIPServie configuration stored in the serve config.
Fixes #https://github.com/tailscale/corp/issues/24510

ipn/ipnlocal: connect serve config to c2n endpoint

---

ipn/ipnlocal/local.go

ipn/ipnlocal: add client metric gauge for number of IPNBus connections

---

types/views/views.go
types/views/views_test.go

Extracted from some code written in the other repo.
Updates tailscale/corp#25479
Change-Id: I6df062fdffa1705524caa44ac3b6f2788cf64595

types/views: add SliceEqualAnyOrderFunc

---

cmd/derpprobe/derpprobe.go
prober/derp.go
prober/derp_test.go

prober: support filtering regions by region ID in addition to code

---

control/controlclient/direct.go

control/controlclient: remove misleading TS_DEBUG_NETMAP, make it TS_DEBUG_MAP=2 (or more)

---

client/tailscale/localclient.go

client/tailscale: fix typo in comment

---

net/netmon/state.go

We have observed some clients with extremely large lists of IPv6 endpoints, in some cases from subnets where the machine also has the zero address for a whole /48 with then arbitrary addresses additionally assigned within that /48. It is in general unnecessary for reachability to report all of these addresses, typically only one will be necessary for reachability. We report two, to cover some other common cases such as some styles of IPv6 private address rotations.

net/netmon: trim IPv6 endpoints in already routable subnets

---

ipn/ipnserver/server_test.go

I made a last-minute change in #14626 to split a single loop that created `1_000` concurrent connections into an inner and outer loop that create `100` concurrent connections `10` times. This introduced a race because the last user's connection may still be active (from the server's perspective) when a new outer iteration begins. Since every new client gets a unique `ClientID`, but we reuse usernames and `UIDs`, the server may let a user in (as the `UID` matches, which is fine), but the test might then fail due to a `ClientID` mismatch:
```
server_test.go:232: CurrentUser(Initial): got &{S-1-5-21-1-0-0-1001 User-4 <nil> Client-2 false false}; want &{S-1-5-21-1-0-0-1001 User-4 <nil> Client-114 false false}
```
In this PR, we update `(*testIPNServer).blockWhileInUse` to check whether the …

ipn/ipnserver: fix TestConcurrentOSUserSwitchingOnWindows

---

prober/derp.go

prober: remove per-packet DERP pub key copying overheads

---

prober/derp.go

prober: remove DERP pub key copying overheads in qd and non-tun measures

---

net/tstun/wrap.go

Since 5297bd2cff8ed03679, tstun.Wrapper has required its Start
method to be called for it to function. Failure to do so just
results in weird hangs and I've wasted too much time multiple
times now debugging. Hopefully this prevents more lost time.
Updates tailscale/corp#24454

net/tstun: add logging to aid developers missing Start calls

---

tsnet/tsnet.go
tsnet/tsnet_test.go

I saw this panic while writing a new test for #14715:
panic: send on closed channel
goroutine 826 [running]:
tailscale.com/tsnet.(*listener).handle(0x1400031a500, {0x1035fbb00, 0x14000b82300})
/Users/bradfitz/src/tailscale.com/tsnet/tsnet.go:1317 +0xac
tailscale.com/wgengine/netstack.(*Impl).acceptTCP(0x14000204700, 0x14000882100)
/Users/bradfitz/src/tailscale.com/wgengine/netstack/netstack.go:1320 +0x6dc
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket in goroutine 807
/Users/bradfitz/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240722211153-64c016c92987/pkg/tcpip/transport/tcp/forwarder.go:98 +0x32c
FAIL    tailscale.com/tsnet     0.927s
Updates #14715

tsnet: fix panic on race between listener.Close and incoming packet

---

tsnet/tsnet.go
tsnet/tsnet_test.go

tsnet: block in Server.Dial until backend is Running

---

cmd/tailscale/cli/advertise.go
cmd/tailscale/cli/cli.go

Both @agottardo and I tripped over this today.

cmd/tailscale/cli: clean up how optional commands get registered

---

tsweb/debug.go

tsweb: add missing debug pprof endpoints

---

cmd/tailscale/cli/cli.go
util/slicesx/slicesx.go
util/slicesx/slicesx_test.go
util/syspolicy/internal/metrics/metrics.go

util/slicesx: add AppendNonzero

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

Unrevert https://github.com/tailscale/tailscale/pull/14710 and fix the deadlock in the follow-up commit.

ipn/ipnlocal: re-advertise appc routes on startup, take 2

---

control/controlclient/map.go

This was a slow memory leak on busy tailnets with lots of tagged
ephemeral nodes.
Updates tailscale/corp#26058

control/controlclient: delete unreferenced mapSession UserProfiles

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/configure_apple.go
cmd/tailscale/cli/debug.go
cmd/tailscale/cli/dns.go
cmd/tailscale/cli/exitnode.go
cmd/tailscale/cli/metrics.go
cmd/tailscale/cli/network-lock.go
cmd/tailscale/cli/switch.go
cmd/tailscale/cli/syspolicy.go

3dabea0fc2c added some docs with inconsistent usage docs.
This fixes them, and adds a test.
It also adds some other tests and fixes other verb tense
inconsistencies.
Updates tailscale/corp#25278

cmd/tailscale: fix, test some recent doc inconsistencies

---

tailcfg/tailcfg.go
util/dnsname/dnsname.go

Change-Id: I163b3f762b9d45c2155afe1c0a36860606833a22

tailcfg: adjust ServiceName.Validate to use vizerror

---

control/controlclient/auto.go
control/controlclient/controlclient_test.go
control/controlknobs/controlknobs.go
tailcfg/tailcfg.go

Updates #1909
Updates #12542
Updates tailscale/corp#26058

control/controlclient: skip SetControlClientStatus when queue has newer results later

---

cmd/natc/natc.go

cmd/natc: expose netstack metrics in client metrics in natc

---

tstest/deptest/deptest.go

This protects against rearranging packages and not catching that a BadDeps
package got moved. That would then effectively remove a test.
Updates #12614

tstest/deptest: verify that tailscale.com BadDeps actually exist

---

health/health.go
health/health_test.go
health/state.go

health: relax no-derp-home warnable to not fire if not in map poll

---

tsnet/tsnet.go
tsnet/tsnet_test.go

tsnet: return from Accept when the listener gets closed

---

client/web/web.go
go.mod
go.sum
safeweb/http.go

For https://github.com/gorilla/csrf/commit/9dd6af1f6d30fc79fb0d972394deebdabad6b5eb
Updates tailscale/corp#25340

go.mod: bump gorilla/csrf for security fix

---

control/controlclient/auto.go

control/controlclient: flesh out a recently added comment

---

prober/prober.go
prober/prober_test.go

Some probes might need to run for longer than their scheduling interval, so this change relaxes the 1-at-a-time restriction, allowing us to configure probe concurrency and timeout separately. The default values remain the same (concurrency of 1; timeout of 80% of interval).
Updates tailscale/corp#25479

prober: support multiple probes running concurrently

---

cmd/tailscale/cli/funnel.go

cli/funnel: fix comment typo

---

types/views/views.go
types/views/views_test.go

SliceEqualAnyOrderFunc had an optimization missing from SliceEqualAnyOrder.
Now they share the same code and both have the optimization.
Updates #14593

types/views: make SliceEqualAnyOrder also do short slice optimization

---

ipn/ipnauth/access.go
ipn/ipnauth/actor.go
util/syspolicy/policy_keys.go

ipn/ipnauth,util/syspolicy: improve comments

---

wgengine/wgcfg/nmcfg/nmcfg.go

wgengine/wgcfg/nmcfg: coalesce, limit some debug logs

---

ipn/ipnlocal/local.go

Without adding this, the packet filter rejects traffic to VIP service addresses before checking the filters sent in the netmap.
Fixes tailscale/corp#26241
Change-Id: Idd54448048e9b786cf4873fd33b3b21e03d3ad4c

ipn/ipnlocal: add VIP service IPs to localnets

---

derp/derp_server.go

derp: tcp-write-timeout=0 should disable write deadline

---

logpolicy/logpolicy.go
logtail/logtail.go

logpolicy: expose MaxBufferSize and MaxUploadSize options

---

scripts/installer.sh

scripts/installer.sh: add BigLinux as a Manjaro derivative

---

wgengine/netstack/link_endpoint.go

Originally identified by Coder and documented in their blog post, this implementation differs slightly as our link endpoint was introduced for a different purpose, but the behavior is the same: apply backpressure rather than dropping packets. This reduces the negative impact of large packet count bursts substantially. An alternative would be to swell the size of the channel buffer substantially, however that's largely just moving where buffering occurs and may lead to reduced signalling back to lower layer or upstream congestion controls.
Updates #9707
Updates #10408
Updates tailscale/corp#24483
Updates tailscale/corp#25169

wgengine/netstack: block link writes when full rather than drop

---

ssh/tailssh/tailssh.go

Some clients don't support 'none' authentication and insist on supplying
a public key. This change allows them to do so. It ignores the public key
and uses Tailscale to authenticate.
Updates #14922
I tested this by trying to tunnel [pgadmin](https://www.pgadmin.org/) via a bastion host without and with the fix. Without the fix, it fails to even create the SSH tunnel.
With the fix, it gets further.

ssh/tailssh: add back a fake public key handler to support buggy clients

---

types/bools/bools.go
types/bools/bools_test.go

Add Int which converts a bool into an integer.
Updates tailscale/corp#22024

types/bool: add Int

---

tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go

And add omitempty to the ProfilePicURL too while here. Plenty
of users (and tagged devices) don't have profile pics.
Updates #14988

tailcfg: remove ancient UserProfiles.Roles field

---

cmd/k8s-operator/ingress-for-pg.go
cmd/k8s-operator/ingress-for-pg_test.go

Allows to optionally configure a _not redirected_ HTTP endpoint for ProxyGroup Ingresses.
This is for edge cases such as where web app is exposed and it would be preferable to access it via HTTPS, but there is a concern of hitting rate limits + a mix of usages (scripts + human users), so having an HTTP endpoint that on which the workload can be accessed makes sense. The assumption is that HTTPS here is just for browser UX as the connection between the client and the proxy is anyway over Wireguard.
The HTTP endpoint can be configured via `tailscale.com/http-endpoint: "enabled"` annotation, i.e
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
annotations:
tailscale.com/http-endpoint: enabled
tailscale.com/proxy-group: ingress-proxies
name: foo
spec:
ingressClassName: tailscale …
```

cmd/k8s-operator: allow to optionally configure an HTTP endpoint for the ProxyGroup Ingress

---

net/netcheck/netcheck.go

net/netcheck: remove unnecessary custom map clone function

---

ipn/ipnlocal/local.go

We already reset the always-on override flag when switching profiles and in a few other cases. In this PR, we update `(*LocalBackend).Start()` to reset it as well. This is necessary to support scenarios where `Start()` is called explicitly, such as when the GUI starts or when `tailscale up` is used with additional flags and passes prefs via `ipn.Options` in a call to `Start()` rather than via `EditPrefs()`.
Additionally, we update it to apply policy settings to the current prefs, which is necessary for properly overriding prefs specified in `ipn.Options`.
Updates #14823

ipn/ipnlocal: reset always-on override and apply policy settings on start

---

cmd/testwrapper/flakytest/flakytest.go
cmd/testwrapper/flakytest/flakytest_test.go

I'd like to enable extra logging in CI for tests marked as flaky
Updates tailscale/corp#26637

cmd/testwrapper/flakytest: add Marked to check if in flakytest

---

client/web/web.go
client/web/web_test.go

Fix the order of the CSRF handlers (HTTP plaintext context setting, _then_ enforcement) in the construction of the web UI server. This resolves false-positive "invalid Origin" 403 exceptions when attempting to update settings in the web UI.
Updates #14822
Updates #14872

client/web: fix CSRF handler order in web UI

---

cmd/containerboot/serve.go
cmd/containerboot/tailscaled.go

Updates tailscale/tailscale#15081

cmd/containerboot: fix nil pointer exception

---

go.mod
go.sum

Updates tailscale/tailscale#15159

go.{mod,sum}: bump mkctr

---

ipn/ipnlocal/local.go

Previously, it initialized when the backend was created. This caused two problems:
1. It would not properly switch when changing profiles.
2. If the backend was created before the profile had been selected, Taildrive's shares were uninitialized.
Updates #14825

ipn/ipnlocal: initialize Taildrive shares when starting backend

---

cmd/testwrapper/testwrapper.go

Capture output associated with a package and display it if the package fails. This will for example capture runs where a panic is thrown outside a test, such as when things are logged after a test completes.
Updates tailscale/corp#26861

cmd/testwrapper: Display package-level output

---

cmd/derper/derper.go

cmd/derper: add --home flag to control home page behavior

---

net/captivedetection/endpoints.go
net/netcheck/netcheck.go
net/netcheck/netcheck_test.go
tailcfg/derpmap.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

tailcfg: add DERPRegion.NoMeasureNoHome, deprecate+document Avoid [cap 115]

---

cmd/natc/natc.go

natc itself can't immediately fix the problem, but it can more correctly error that return bad addresses.
Updates tailscale/corp#26968

cmd/natc: error and log when IP range is exhausted

---

ssh/tailssh/incubator.go

And don't return a comma-separated string. That's kinda weird
signatur-wise, and not always needed anyway. The caller can do it
easily enough.

ssh/tailssh: fix typo in forwardedEnviron method, add docs

---

cmd/testwrapper/testwrapper.go

While we retry tests which are marked flaky, we have flaky tests which are not marked. An indicator of which is that GitHub actions are retried manually and they subsequently pass. In an effort to spot this, we'll later parse out which tests prevented an automatic retry when a manual retry resolved it.
Updates tailscale/corp#26637

cmd/testwrapper: print failed tests preventing retry

---

net/packet/geneve.go
net/packet/geneve_test.go

net/packet: implement Geneve header serialization

---

.github/workflows/govulncheck.yml

.github/workflows/govulncheck.yml: send messages to another channel

---

ipn/ipnlocal/local_test.go

This only tests `LocalBackend` in isolation, by using a mock client (Direct+Auto). We'll want a test that covers Direct + Auto as well as they assemble a NetworkMap from incremental NetMaps to pass to LocalBackend, so this isn't testing the full client. I figure it's probably still a useful test as it does exercise `srcIPHasCapForFilter`, which is currently untested.

ipn/ipnlocal: add test for CapMap packet filters

---

cmd/proxy-to-grafana/proxy-to-grafana.go

This adds support for using ACL Grants to configure a role for the auto-provisioned user.
Fixes tailscale/corp#14567

 cmd/proxy-to-grafana: support setting Grafana role via grants

---

cmd/k8s-operator/ingress-for-pg.go
cmd/k8s-operator/ingress-for-pg_test.go

When the Ingress is updated to a new hostname, the controller does not currently clean up the old VIPService from control. Fix this up to parse the ownership comment correctly and write a test to enforce the improved behaviour
Change-Id: I792ae7684807d254bf2d3cc7aa54aa04a582d1f5

cmd/k8s-operator: ensure old VIPServices are cleaned up

---

net/dns/manager.go

updates tailscale/corp#27145
We require a means to trigger a recompilation of the DNS configuration to pick up new nameservers for platforms where we blend the interface nameservers from the OS into our DNS config.
Notably, on Darwin,the only API we have at our disposal will, in rare instances, return a transient error when querying the interface nameservers on a link change if they have not been set when we get the AF_ROUTE messages for the link update.   Darwin clients are unique with respect to the need to blend in the interface nameservers due to limitations in their split DNS support.
There's a corresponding change in corp for Darwin clients, to track the interface namservers during NEPathMonitor events, and call this when the nameservers change.
This will also fix the slightly more …

net/dns: expose a function for recompiling the DNS configuration

---

cmd/tailscale/cli/debug.go

This adds a portable way to do a raw LocalAPI request without worrying
about the Unix-vs-macOS-vs-Windows ways of hitting the LocalAPI server.
(It was already possible but tedious with 'tailscale debug local-creds')
Updates tailscale/corp#24690

cmd/tailscale: add CLI debug command to do raw LocalAPI requests

---

cmd/tailscaled/tailscaled.go
cmd/tailscaled/tailscaled_windows.go
cmd/tsconnect/wasm/wasm_js.go
ipn/ipnlocal/local_test.go
ipn/ipnlocal/loglines_test.go
ipn/ipnlocal/serve_test.go
ipn/ipnlocal/state_test.go
ipn/ipnserver/server_test.go
ipn/localapi/localapi_test.go
ssh/tailssh/tailssh_test.go
tsd/tsd.go
tsnet/tsnet.go
wgengine/bench/wg.go
wgengine/netstack/netstack_test.go
wgengine/userspace_ext_test.go

Replace NewSystemWithEventBus with plain NewSystem, and update all usage.
See https://github.com/tailscale/tailscale/pull/15355#discussion_r2003910766
Updates #15160
Change-Id: I64d337f09576b41d9ad78eba301a74b9a9d6ebf4

all: update the tsd.System constructor name

---

tsnet/tsnet_test.go

tsnet: use test logger for testcontrol and node logs

---

net/netmon/interfaces_test.go
net/netmon/netmon.go
net/netmon/state.go

Baby step towards #15408.
Updates #15408

net/netmon: unexport GetState

---

cmd/natc/natc_test.go

These tests aren't perfect, nor is this complete coverage, but this is a set of coverage that is at least stable.
Updates #15367

cmd/natc: add some initial unit test coverage

---

tstest/integration/testcontrol/testcontrol.go

Only send a stored raw map message in reply to a streaming map response. Otherwise a non-streaming map response might pick it up first, and potentially drop it. This guarantees that a map response sent via AddRawMapResponse will be picked up by the main map response loop in the client.
Fixes #15362

tstest/integration/testcontrol: fix AddRawMapResponse race condition

---

wgengine/magicsock/magicsock.go

When an event bus is plumbed in, use it to subscribe and react to port mapping
updates instead of using the client's callback mechanism. For now, the callback
remains available as a fallback when an event bus is not provided.
Updates #15160
Change-Id: I026adca44bf6187692ee87ae8ec02641c12f7774

wgengine/magicsock: subscribe to portmapper updates

---

cmd/natc/natc.go
cmd/natc/natc_test.go

This is a very dumb fix as it has an unbounded worst case runtime. IP allocation needs to be done in a more sane way in a follow-up.
Updates #15367

cmd/natc: add test and fix for ip exhaustion

---

cmd/tailscaled/tailscaled.go

Not all platforms have hardlinks, or not easily.
This lets a "tailscale" wrapper script set an environment variable
before calling tailscaled.
Updates #2233

cmd/tailscaled: make embedded CLI run earlier, support triggering via env

---

cmd/k8s-operator/deploy/crds/tailscale.com_proxygroups.yaml
cmd/k8s-operator/deploy/manifests/operator.yaml
cmd/k8s-operator/ingress-for-pg.go
cmd/k8s-operator/operator.go
k8s-operator/api.md
k8s-operator/apis/v1alpha1/types_proxygroup.go

Re-enable HA Ingress again that was disabled for 1.82 release.
This reverts commit fea74a60d529bcccbc8ded74644256bb6f6c7727.

cmd/k8s-operator,k8s-operator: enable HA Ingress again.

---

cmd/vnet/vnet-main.go
tstest/natlab/vnet/conf.go
tstest/natlab/vnet/vnet.go

For hooking up websocket VM clients to natlab.
Updates #13038

cmd/vnet: add wsproxy mode

---

tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

Not currently used in the OSS tree, a View for tailcfg.VIPService will make implementing some server side changes easier.
Updates tailscale/corp#26272
Change-Id: If1ed0bea4eff8c4425d3845b433a1c562d99eb9e

tailcfg: add VIPServiceView

---

ipn/ipnlocal/peerapi.go

ipn/ipnlocal: fix taildrive logf formatting verb

---

tailcfg/tailcfg.go

tailcfg: add relay client and server NodeAttr's

---

tailcfg/tailcfg.go

tailcfg: add UDP relay PeerCapability's

---

go.mod
go.sum
tempfork/acme/acme.go
tempfork/acme/acme_test.go
tempfork/acme/rfc8555.go
tempfork/acme/rfc8555_test.go
tempfork/acme/types.go

Pull in https://github.com/tailscale/golang-x-crypto/pull/16
Updates #15542

tempfork/acme: update to latest version

---

drive/driveimpl/dirfs/dirfs.go
drive/driveimpl/fileserver.go
drive/remote_permissions.go

Fix some minor typos in comments

drive: fix minor typos in comments

---

words/scales.txt
words/tails.txt

words: C what I did there?

---

cmd/natc/natc.go
cmd/natc/natc_test.go

Ensure that the upstream is always queried, so that if upstream is going to NXDOMAIN natc will also return NXDOMAIN rather than returning address allocations.
At this time both IPv4 and IPv6 are still returned if upstream has a result, regardless of upstream support - this is ~ok as we're proxying.
Rewrite the tests to be once again slightly closer to integration tests, but they're still very rough and in need of a refactor.
Further refactors are probably needed implementation side too, as this removed rather than added units.
Updates #15367

cmd/natc: fix handling of upstream and downstream nxdomain

---

ipn/prefs.go

ipn: use slices.Equal in another spot

---

ipn/ipnlocal/cert.go

When we have an old cert that is being rotated, include it in the order. If we're in the ARI-recommended rotation window, LE should exclude us from rate limits. If we're not within that window, the order still succeeds, so there's no risk in including the old cert.
Fixes #15542

ipn/ipnlocal: include previous cert in new ACME orders

---

.github/CONTRIBUTING.md

Per suggestion from @sfllaw at https://github.com/tailscale/tailscale/pull/15576#issuecomment-2787386082
Updates #engdocs

.github: add CONTRIBUTING.md

---

cmd/natc/natc.go

As IPv4 and IPv6 end up with different MSS and different congestion control strategies, proxying between them can really amplify TCP meltdown style conditions in many real world network conditions, such as with higher latency, some loss, etc.
Attempt to match up the protocols, otherwise pick a destination address arbitrarily. Also shuffle the target address to spread load across upstream load balancers.
Updates #15367

cmd/natc: attempt to match IP version between upstream and downstream

---

clientupdate/clientupdate_windows.go

In this PR, we update the Windows client updater to:
- Run `msiexec` with logging enabled and preserve the log file in `%ProgramData%\Tailscale\Logs`. The logging helps us troubleshoot issues where something goes wrong, such as the GUI not restarting properly during the update.
- Preserve the updater's own log file in the same location;
- Properly handle `ERROR_SUCCESS_REBOOT_REQUIRED`, `ERROR_SUCCESS_REBOOT_INITIATED`, and `ERROR_INSTALL_ALREADY_RUNNING` exit codes. The first two values indicate that installation completed successfully and no further retries are needed. The last one means the Windows Installer service is busy. Retrying immediately is likely to fail and may be risky; it could uninstall the current version without successfully installing the new one, potentially leaving …

clientupdate: fix MSI exit code handling, preserve MSI and updater logs on Windows

---

ipn/ipnlocal/local.go

Updates tailscale/tailscale#14393

ipnlocal: log when client reports new peerAPI ports

---

ipn/ipnstate/ipnstate.go
wgengine/magicsock/magicsock.go

ipn/ipnstate: add home DERP to tailscale status JSON

---

cmd/natc/ippool/ippool.go
cmd/natc/ippool/ippool_test.go
cmd/natc/natc.go
cmd/natc/natc_test.go

Because we derive v6 addresses from v4 addresses we only need to store the v4 address, not both.
Updates #14667

cmd/natc: only store v4 addresses

---

wgengine/netstack/netstack.go

Updates google/gvisor#11632
Updates tailscale/corp#27717

wgengine/netstack: revert cubic cc to reno cc

---

tstest/integration/integration_test.go

Query for the const quad-100 reverse DNS name, for which a forward record will also be served. This test was previously dependent on search domain behavior, and now it is not.
Updates #15607

tstest/integration: simplify TestDNSOverTCPIntervalResolver

---

ipn/auditlog/extension.go

ipn/auditlog: fix featureName doc typo

---

ipn/ipnlocal/extension_host.go

We added this helper in 1e2e319e7d26. Remove this copy.

ipn/ipnlocal: remove another copy of slicesx.MapValues

---

cmd/tsidp/tsidp.go
cmd/tsidp/tsidp_test.go

Replace all instances of interface{} with any to resolve the golangci-lint errors that appeared in the previous tsidp PR.

cmd/tsidp: fix interface{} linter warnings

---

ipn/auditlog/extension.go
ipn/desktop/extension.go
ipn/ipnext/ipnext.go
ipn/ipnlocal/extension_host.go
ipn/ipnlocal/extension_host_test.go

Updates #12614
Co-authored-by: Nick Khyl <nickk@tailscale.com>

ipn/ipnext: remove support for unregistering extension

---

feature/relayserver/relayserver.go
feature/taildrop/ext.go
ipn/auditlog/extension.go
ipn/desktop/extension.go
ipn/ipnext/ipnext.go
ipn/ipnlocal/extension_host.go
ipn/ipnlocal/extension_host_test.go
ipn/ipnlocal/local.go

Updates #12614
Co-authored-by: Nick Khyl <nickk@tailscale.com>

ipn/{ipnext,ipnlocal}: add a SafeBackend interface

---

disco/disco.go
disco/disco_test.go

This message type is currently unused and considered experimental.

disco: implement CallMeMaybeVia serialization

---

ipn/ipnlocal/dnsconfig_test.go
ipn/ipnlocal/drive.go
ipn/ipnlocal/local.go
ipn/ipnlocal/local_node_context.go
ipn/ipnlocal/local_test.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/peerapi.go
ipn/ipnlocal/peerapi_test.go
ipn/ipnlocal/serve.go
ipn/ipnlocal/serve_test.go
ipn/ipnlocal/taildrop.go
ipn/ipnlocal/taildrop_test.go
ipn/ipnlocal/web_client.go

ipn/ipnlocal: add localNodeContext with netmap-related fields and methods

---

types/logger/logger.go

Spotted after Brad showed me this utility in #15806.

types/logger: release ArgWriter destination after use

---

wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock.go

wgengine/magicsock: support Geneve-encap'd Disco transmission

---

control/controlclient/map_test.go
health/health.go
health/health_test.go

control/controlclient,health: add tests for control health tracking

---

tsnet/tsnet.go

And also validate opts for unknown types, before other side effects.
Fixes #15833

tsnet: add FunnelTLSConfig FunnelOption type

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

wgengine/magicsock: start to make disco reception Geneve aware

---

wgengine/magicsock/magicsock.go

Conn.sendDiscoMessage() now verifies if the destination disco key is associated with any known peer(s) in a thread-safe manner.
Updates #15844

wgengine/magicsock: fix discoInfo leak

---

ipn/ipnlocal/local.go

This fixes the Taildrop deadlock from 8b72dd787320.
Fixes #15824

ipn/ipnlocal: fix Taildrop deadlock

---

cmd/tailscale/cli/set.go

cmd/tailscale/cli: unhide `--posture-checking` flag to `set`

---

wgengine/magicsock/magicsock.go

Conn.handleDiscoMessage() now makes a distinction between relay handshake disco messages and peer disco messages.

wgengine/magicsock: implement more relay handshake disco handling

---

logtail/logtail.go
logtail/logtail_test.go

logtail: remove unneeded IP redaction code

---

ipn/ipnlocal/local.go
ipn/ipnlocal/node_backend.go

As just discussed on Slack with @nickkhyl.
Updates #12614

ipn/ipnlocal: rename localNodeContext to nodeBackend

---

tstest/integration/integration.go

This is a hack, but should suffice and be fast enough.
I really want to figure out what's keeping that writable fd open.
Fixes #15868

tstest/integration: work around ETXTBUSY flake

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/set.go
cmd/tailscale/cli/up.go
cmd/tailscale/cli/up_test.go
ipn/prefs.go

For consistency with other flags, per Slack chat.
Updates #5902

cmd/tailscale/cli: rename "--posture-checking" to "--report-posture"

---

feature/relayserver/relayserver.go

feature/relayserver: consider relay:server node attribute for enablement

---

client/local/local.go

Add [godoc links](https://go.dev/doc/comment#doclinks) to package [`tailscale.com/client/local`](https://pkg.go.dev/tailscale.com/client/local).

client/local: add godoc links

---

ssh/tailssh/incubator.go

Commit 4b525fdda defers changing the working directory until the incubator process drops its privileges.
However, it didn't account for the case where there is no incubator process, because no tailscaled was found on the PATH. In that case, it only intended to run `tailscaled be-child` in the root directory but accidentally ran everything there.
Fixes: #15350

ssh/tailssh: chdir to user's homedir when directly running a command

---

ssh/tailssh/tailssh_test.go

In `tailssh.go:1284`, `(*sshSession).startNewRecording` starts a fire-and-forget goroutine that can outlive the test that triggered its creation. Among other things, it uses `ss.logf`, and may call it after the test has already returned. Since we typically use `(*testing.T).Logf` as the logger, this results in a data race and causes flaky tests.
Ideally, we should fix the root cause and/or use a `goroutines.Tracker` to wait for the goroutine to complete. But with the release approaching, it might be too risky to make such changes now.
As a workaround, we update the tests to use `tstest.WhileTestRunningLogger`, which logs to `t.Logf` while the test is running and disables logging once the test finishes, avoiding the race.
While there, we also fix `TestSSHAuthFlow` not to use `log.Printf`. …

ssh/tailssh: fix data race during execution of test

---

prober/tls.go
prober/tls_test.go

OCSP has been removed from the LE certs. Use CRL verification instead.
If a cert provides a CRL, check its revocation status, if no CRL is provided and otherwise is valid, pass the check.
Fixes #15912

prober: update cert check for prober

---

docs/windows/policy/en-US/tailscale.adml
docs/windows/policy/tailscale.admx

docs/windows/policy: add OnboardingFlow policy to ADMX file

---

docs/commit-messages.md

Adapted from [http://go/cleanup](https://docs.google.com/document/d/1b3v1xs-q-HQhOzExgDdhIiUTSiVyazW28WrZ2oDdmFc/edit?tab=t.0).
Fixes: #15932

docs/commit-messages.md: explain #cleanup commits

---

ipn/localapi/localapi.go

ipn/ipnlocal: attach Tailnet Lock status to bugreports

---

feature/taildrop/integration_test.go

Updates #15970
Updates #15812
Updates tailscale/corp#28449

feature/taildrop: add integration test variant with profiles that exist

---

wgengine/magicsock/endpoint.go

wgengine/magicsock: add missing logf arg

---

cmd/k8s-operator/svc-for-pg.go

cmd/k8s-operator: warn if HA Service is applied, but VIPService feature flag is not enabled

---

cmd/k8s-operator/ingress-for-pg_test.go
cmd/k8s-operator/svc-for-pg.go
cmd/k8s-operator/svc-for-pg_test.go

Also changes wording tests for L7 HA Reconciler
Updates #15895

cmd/k8s-operator: rename VIPService -> Tailscale Service in L3 HA Service Reconciler

---

wgengine/magicsock/endpoint.go

wgengine/magicsock: fix pong handling 'EndpointChange' reporting

---

wgengine/magicsock/endpoint.go

heartbeatInterval is currently 3s.

wgengine/magicsock: fix outdated heartbeat comment

---

cmd/tsidp/tsidp.go
cmd/tsidp/ui-edit.html
cmd/tsidp/ui-header.html
cmd/tsidp/ui-list.html
cmd/tsidp/ui-style.css
cmd/tsidp/ui.go

Add comprehensive web interface at Ui for managing OIDC clients, similar to tsrecorder's design. Features include list view, create/edit forms with validation, client secret management, delete functionality with confirmation dialogs, responsive design, and restricted tailnet access only.
Fixes #16067
UI Demo
https://github.com/user-attachments/assets/de1f24e6-6bdf-4421-afe2-acfd544eba87

cmd/tsidp: add web UI for managing OIDC clients

---

cmd/containerboot/main_test.go
cmd/containerboot/settings.go
cmd/containerboot/settings_test.go

This is cherry pick of https://github.com/tailscale/tailscale/pull/16129
cc @ChaosInTheCRD @tomhjp 
Updates tailscale/tailscale#16108
(cherry picked from commit 5b670eb3a5f1749a655692d97a2e7086c78d1580)

cmd/containerboot: allow setting --accept-dns via TS_EXTRA_ARGS again

---

control/controlclient/map.go
control/controlclient/map_test.go
health/state.go
ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
tailcfg/tailcfg.go
types/netmap/nodemut.go

Updates https://github.com/tailscale/corp/issues/27759

controlclient,health,ipnlocal,tailcfg: add DisplayMessage support

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

ipn/ipnlocal: fix deadlock when filtering DisplayMessage URLs

---

cmd/natc/ippool/consensusippool.go
cmd/natc/ippool/consensusippool_test.go
cmd/natc/ippool/consensusippoolserialize.go
cmd/natc/ippool/ippool.go
cmd/natc/ippool/ippool_test.go
cmd/natc/natc.go
cmd/natc/natc_test.go

Enable nat connector to be run on a cluster of machines for high
availability.
Updates https://github.com/tailscale/tailscale/issues/14667

cmd/natc: add optional consensus backend

---

net/packet/packet.go

net/packet: fix Parsed docs

---

control/controlclient/map.go
control/controlclient/map_test.go
health/health_test.go
health/state.go
ipn/ipnlocal/local_test.go

health: prefix Warnables received from the control plane

---

cmd/k8s-operator/ingress-for-pg.go
cmd/k8s-operator/ingress-for-pg_test.go

This is a cherry pick of https://github.com/tailscale/tailscale/pull/16199
Updates https://github.com/tailscale/corp/issues/24795
(cherry picked from 4456f77af71367e52565a76dd58a796fa108e3f8)

cmd/k8s-operator: explicitly set tcp on VIPService port configuration for Ingress with ProxyGroup

---

wgengine/magicsock/relaymanager.go

It might complete, interrupting it reduces the chances of establishing a relay path.

wgengine/magicsock: don't cancel in-progress relayManager work

---

cmd/natc/ippool/consensusippool.go
cmd/natc/natc.go

Which can make operating the service more convenient. It makes sense to put the cluster state with this if specified, so rearrange the logic to handle that.
Updates #14667

cmd/natc: allow specifying the tsnet state dir

---

tsweb/varz/varz.go

tsweb/varz: add binary name to version metric

---

prober/derp.go

Record dropped packets as soon as they time out, rather than after tx record queues spill over, this will more accurately capture small amounts of packet loss in a timely fashion.
Updates tailscale/corp#24522

prober: record DERP dropped packets as they occur

---

cmd/tailscale/cli/network-lock.go
tka/builder_test.go
tka/tka.go

tka: reject removal of the last signing key

---

ipn/ipnlocal/peerapi.go

ipn/ipnlocal: add some verbose logging to taildrive peerapi handler

---

ipn/ipnlocal/c2n.go
ipn/ipnserver/actor.go

Hi, this is my first PR here. Please let me know if there is something missing.

ipn: add missing entries for OpenBSD

---

.github/workflows/test.yml
cmd/testwrapper/testwrapper.go

It's one of the slower ones, so split it up into chunks.
Updates tailscale/corp#28679

.github/workflows: shard the Windows builder

---

.github/workflows/test.yml

.github/workflows: try running Windows jobs on bigger VMs

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go
wgengine/magicsock/relaymanager.go
wgengine/magicsock/relaymanager_test.go

wgengine/magicsock: generate relay server set from tailnet policy

---

wgengine/magicsock/relaymanager.go

wgengine/magicsock: set rxDiscoMsgCh field in relayHandshakeWork

---

wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/relaymanager.go
wgengine/magicsock/relaymanager_test.go

wgengine/magicsock: set conn field in relayHandshakeDiscoMsgEvent

---

wgengine/magicsock/debugknobs.go
wgengine/magicsock/debugknobs_stubs.go
wgengine/magicsock/magicsock.go

wgengine/magicsock: add envknob to toggle UDP relay feature

---

disco/disco.go
disco/disco_test.go
net/udprelay/server.go
net/udprelay/server_test.go
wgengine/magicsock/relaymanager.go

disco,net/udprelay,wgengine/magicsock: support relay re-binding

---

util/eventbus/bus.go

util/eventbus: fix docstrings

---

ipn/ipnlocal/drive.go
ipn/ipnlocal/local.go

This allows logging the following Taildrive behavior from the client's perspective when --verbose=1:
- Initialization of Taildrive remotes for every peer
- Peer availability checks
- All HTTP requests to peers (not just GET and PUT)
Updates tailscale/corp#29702

ipn/ipnlocal: add verbose Taildrive logging on client side

---

feature/relayserver/relayserver.go
net/udprelay/server.go
net/udprelay/server_test.go

feature/relayserver,net/udprelay: add IPv6 support

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

Now that `(*LocalBackend).suggestExitNodeLocked` is never called with a non-current netmap (the `netMap` parameter is always `nil`, indicating that the current netmap should be used), we can remove the unused parameter.
Additionally, instead of `suggestExitNodeLocked` passing the most recent full netmap to `suggestExitNode`, we now pass the current `nodeBackend` so it can access peers with delta updates applied.
Finally, with that fixed, we no longer need to skip `TestUpdateNetmapDeltaAutoExitNode`. So we update it as well.
Fixes #16455

ipn/ipnlocal: plumb nodeBackend into suggestExitNode to support delta updates, such as online status changes

---

ipn/ipnlocal/extension_host_test.go

ipn/ipnlocal: fix missing defer in testExtension.Shutdown

---

net/udprelay/server.go
net/udprelay/server_test.go

We can't relay a packet received over the IPv4 socket back out the same socket if destined to an IPv6 address, and vice versa.
Updates tailscale/corp#30206

net/udprelay: fix relaying between mixed address family sockets

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

wgengine/magicsock: support self as candidate peer relay

---

cmd/tailscale/cli/status.go
ipn/ipnstate/ipnstate.go
wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock.go

cmd/tailscale/cli,ipn/ipnstate,wgengine/magicsock: label peer-relay

---

ipn/localapi/localapi.go

Errors were mashalled without the correct newlines. Also, they could
generally be mashalled with more data, so an intermediate was introduced
to make them slightly nicer to look at.
Updates #15160

ipn/localapi: do not break client on event marshalling errors

---

cmd/tailscaled/tailscaled.go
logpolicy/logpolicy.go
net/dns/manager_linux.go
net/tstun/tun.go
net/tstun/tun_linux.go
paths/paths.go
paths/paths_unix.go
util/linuxfw/detector.go
util/linuxfw/iptables_runner.go
version/distro/distro.go

all: detect JetKVM and specialize a handful of things for it

---

feature/relayserver/relayserver.go
wgengine/magicsock/magicsock.go

feature/relayserver,wgengine/magicsock: remove WIP gating of peer relay

---

go.mod
go.sum

go.mod: bump wg-go to fix keepalive detection

---

net/udprelay/server.go

net/udprelay: fix peer relay server deadlock

---

wgengine/magicsock/endpoint.go
wgengine/magicsock/endpoint_test.go

A trusted peer relay path is always better than an untrusted direct or peer relay path.
Updates tailscale/corp#30412

wgengine/magicsock: prioritize trusted peer relay paths over untrusted

---

health/health_test.go
tailcfg/tailcfg.go
tailcfg/tailcfg_test.go

tailcfg: send health update if DisplayMessage URL changes

---

tailcfg/tailcfg.go
wgengine/magicsock/debugknobs.go
wgengine/magicsock/debugknobs_stubs.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

feature/relayserver,tailcfg,wgengine/magicsock: set peer relay CapVer

---

wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock.go

wgengine/magicsock: add peer relay metrics

---

feature/relayserver/relayserver.go
feature/relayserver/relayserver_test.go

consumeEventbusTopics now owns server and related eventbus machinery.
Updates tailscale/corp#30651

feature/relayserver: fix consumeEventbusTopics deadlock

---

cmd/k8s-operator/dnsrecords.go
cmd/k8s-operator/dnsrecords_test.go

This update introduces support for DNS records associated with ProxyGroup egress services, ensuring that the ClusterIP Service IP is used instead of Pod IPs.
Fixes #15945
Image built at `ghcr.io/rajsinghtech/k8s-operator:v0.0.7`
Resulting `records.json` (Pods are `10.1.0.0/16` and services `10.0.0.0/16`)
``` json
{"version":"v1alpha1","ip4":{"flux-webhook-robbinsdale.keiretsu.ts.net":["10.1.1.4"[],"goldpinger-ottawa.keiretsu.ts.net":["10.1.1.142"[],"goldpinger-robbinsdale.keiretsu.ts.net":["10.1.3.41"[],"hello-world-ottawa-tailscale-examples.keiretsu.ts.net":["10.0.221.62"[],"hello-world-robbinsdale-tailscale-examples.keiretsu.ts.net":["10.0.143.155"[],"hello-world-shared-tailscale-examples.keiretsu.ts.net":["10.0.205.106"[],"hubble.keiretsu.ts.net":["10.1.1.143"[],"idp.keiretsu.ts.net":[" …
```

cmd/k8s-operator: Enhance DNS record handling for ProxyGroup egress 

---

control/controlclient/map_test.go
health/health_test.go
health/state.go
ipn/ipnlocal/local_test.go

health: add an ETag to UnhealthyState for change detection

---

k8s-operator/sessionrecording/ws/conn_test.go

This occasionally panics waiting on a nil ctx, but was missed in the previous PR because it's quite a rare flake as it needs to progress to a specific point in the parser. Also makes the failure output a bit easier to action.
Updates #16678
Change-Id: Ifd36dfc915b153aede36b8ee39eff83750031f95

k8s-operator: fix test flake

---

tailcfg/tailcfg.go
wgengine/magicsock/magicsock.go

wgengine/magicsock: fix magicsock deadlock around Conn.NoteRecvActivity

---

drive/driveimpl/remote_impl.go

Some systems have `sudo`, some have `su`. This tries both, increasing the chance that we can run the file server as an unprivileged user.
Updates #14629

drive/driveimpl: use sudo or su to run file server

---

Makefile

Makefile: sort make commands and fix printing newlines

---

scripts/installer.sh

this should fix the issue on https://github.com/tailscale/tailscale/issues/16740

Update installer.sh add FreeBSD ver 15

---

client/systray/startup-creator.go
client/systray/tailscale-systray.service
cmd/tailscale/cli/systray.go

client/systray: add startup script generator for systemd

---

CODE_OF_CONDUCT.md

CODE_OF_CONDUCT.md: update Code of Conduct

---

cmd/tailscale/cli/configure.go
cmd/tailscale/cli/configure_linux-all.go
cmd/tailscale/cli/configure_linux.go
cmd/tailscale/cli/systray.go

cmd/tailscale/cli: move systray configuration to tailscale configure

---

cmd/tailscale/cli/cli.go

This prints all command and flag docs as JSON. To be used for validating and/or generating the contents of https://tailscale.com/kb/1080/cli.
Updates https://github.com/tailscale/tailscale-www/issues/4722

cmd/tailscale: add --json-docs flag

---

net/tshttpproxy/tshttpproxy.go

net/tshttpproxy: use errors.New for error creation

---

tsconsensus/tsconsensus.go

We have been unintentionally ignoring errors from calling bootstrap. bootstrap sometimes calls raft.BootstrapCluster which sometimes returns a safe to ignore error, handle that case appropriately.
Updates #14667

tsconsensus: check for bootstrap error

---

net/udprelay/server.go

net/udprelay: set ICMP err immunity sock opt

---

ipn/localapi/debugderp.go

ipn/localapi: make tailscale debug derp STUNOnly-aware

---

wgengine/magicsock/endpoint.go

wgengine/magicsock: trigger peer relay path discovery on CallMeMaybe RX

---

wgengine/magicsock/endpoint.go

wgengine/magicsock: make endpoint.discoPing peer relay aware

---

CODE_OF_CONDUCT.md

Remove duplicate entry not present on approved wording

CODE_OF_CONDUCT.md: fix duplicate entry

---

build_dist.sh
client/local/local.go
client/local/syspolicy.go
cmd/tailscale/cli/cli.go
cmd/tailscale/cli/syspolicy.go
cmd/tailscaled/deps_test.go
ipn/localapi/localapi.go
ipn/localapi/syspolicy_api.go

util/syspolicy: finish adding ts_omit_syspolicy build tags, tests

---

cmd/containerboot/kube.go

This commit modifies containerboot's state reset process to handle the state secret not existing. During other parts of the boot process we gracefully handle the state secret not being created yet, but missed that check within `resetContainerbootState`
Fixes https://github.com/tailscale/tailscale/issues/16804

cmd/containerboot: do not reset state on non-existant secret

---

ipn/ipnlocal/state_test.go

ipn/ipnlocal: add state change test for key expiry

---

cmd/tailscale/cli/set.go

cmd/tailscale/cli: add new line for set --webclient

---

cmd/tailscale/cli/set.go
cmd/tailscale/cli/up.go

cmd/tailscale/cli: fix the spelling of "routes"

---

ipn/ipnlocal/local.go
ipn/ipnlocal/node_backend.go
ipn/prefs.go
types/netmap/netmap.go

Updates https://github.com/tailscale/corp/issues/30456

ipn/ipnlocal, types: plumb display name to network profile

---

cmd/tailscale/cli/switch.go
ipn/prefs.go

Updates cli to use tailnet display name
Updates tailscale/corp#32108

cmd/tailscale: use tailnet display name on cli

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: fix debug disco printing of alloc resp disco keys

---

wgengine/magicsock/debugknobs.go
wgengine/magicsock/debugknobs_stubs.go
wgengine/magicsock/endpoint.go

wgengine/magicsock: add TS_DEBUG_NEVER_DIRECT_UDP debug knob

---

cmd/omitsize/omitsize.go

When you say --features=foo,bar, that was supposed to mean
to only show features "foo" and "bar" in the table.
But it was also being used as the set of all features that are
omittable, which was wrong, leading to misleading numbers
when --features was non-empty.
Updates #12614

cmd/omitsize: fix the --features flag

---

wgengine/magicsock/magicsock_test.go

This test ostensibly checks whether we record an error metric if a packet is dropped because the network is down, but the network connectivity is irrelevant -- the send error is actually because the arguments to Send() are invalid:
RebindingUDPConn.WriteWireGuardBatchTo:
[unexpected] offset (0) != Geneve header length (8)
This patch changes the test so we try to send a valid packet, and we verify this by sending it once before taking the network down.  The new error is:
magicsock: network down
which is what we're trying to test.
We then test sending an invalid payload as a separate test case.
---
I discovered this while looking at #17122 (tests that require Internet connectivity, and looking for tests which explicitly try to simulate a network outage), which …

wgengine/magicsock: send a valid payload in TestNetworkDownSendErrors

---

feature/relayserver/relayserver.go
tstest/integration/integration.go
tstest/integration/integration_test.go
tstest/integration/testcontrol/testcontrol.go

tstest/integration{/testcontrol}: add peer relay integration test

---

util/eventbus/bus_test.go
util/eventbus/client.go

Subscribers already have a Done channel that the caller can use to detect when
the subscriber has been closed. Typically this happens when the governing
Client closes, which in turn is typically because the Bus closed.
But clients and subscribers can stop at other times too, and a caller has no
good way to tell the difference between "this subscriber closed but the rest
are OK" and "the client closed and all these subscribers are finished".
We've worked around this in practice by knowing the closure of one subscriber
implies the fate of the rest, but we can do better: Add a Done method to the
Client that allows us to tell when that has been closed explicitly, after all
the publisers and subscribers associated with that client have been closed.
This allows the caller to be sure that, by …

util/eventbus: add a Done channel to the Client

---

cmd/tailscaled/deps_test.go
ipn/ipnlocal/local.go
ipn/ipnlocal/ssh.go
ipn/ipnlocal/ssh_stub.go

And add a test.
Updates #12614

ipn/ipnlocal: fix a case where ts_omit_ssh was still linking in x/crypto/ssh

---

words/scales.txt
words/tails.txt

👋 The community was asked for more words, so I've grabbed my additions from the document that was setup (https://docs.google.com/document/d/1aZZndVgaxxC2ZeX0x0b2q7WpbnY7Wx1nyZseUVtWEog/edit?tab=t.0) checked for dupes and threw them in.
Enjoy 😄

words: add to tails.txt and scales.txt

---

ipn/ipnlocal/expiry.go

This commit does not change the order or meaning of any eventbus activity, it
only updates the way the plumbing is set up.
Updates #15160
Change-Id: I0a175e67e867459daaedba0731bf68bd331e5ebc

ipn/ipnlocal: use eventbus.Monitor in expiryManager

---

control/controlclient/direct.go

control/controlclient: fix tka godoc

---

wgengine/router/router_linux.go

This commit does not change the order or meaning of any eventbus activity, it
only updates the way the plumbing is set up.
Updates #15160
Change-Id: I61b863f9c05459d530a4c34063a8bad9046c0e27

wgengine/router: use eventbus.Monitor in linuxRouter

---

client/systray/systray.go

client/systray: use new tailnet display name is profile title

---

types/key/hardware_attestation.go

Sitestep cmd/viewer incompatibility hiccups with
HardwareAttestationPublic type due to its ecdsa.PublicKey inner member
by serializing the key to a byte slice instead.
Updates tailscale/corp#31269

types/key: Change HardwareAttestationPublic inner representation

---

feature/tpm/attestation.go
feature/tpm/attestation_test.go
feature/tpm/tpm.go

feature/tpm: implement key.HardwareAttestationKey

---

tstest/integration/integration_test.go

Based on Nick's feedback here: https://github.com/tailscale/tailscale/pull/17275#discussion_r2380651410
Updates #17108

tstest/integration: skip this test rather than commenting it out

---

cmd/tailscale/cli/status.go

Makes the output look like this
``` console
user@host:~$ tailscale status --header
IP            Hostname            Owner           OS     Status
--            --------            -----           --     ------
100.68.90.36  tailscale-operator  tagged-devices  linux  offline, last seen 2d ago
```
Fixes #17238

cmd/tailscale/cli: use tabwriter for output

---

README.md

README: update the version of Go in the README

---

ipn/ipnlocal/serve.go
ipn/ipnlocal/serve_test.go

(Kinda related: #17351)
Updates #17305

ipn/ipnlocal: proxy h2c grpc using net/http.Transport instead of x/net/http2

---

feature/tpm/tpm.go

feature/tpm: don't log to stderr in tests

---

wgengine/router/osrouter/router_linux.go

As found by @cmol in #17423.
Updates #17423

wgengine/router/osrouter: fix data race in magicsock port update callback

---

net/wsconn/wsconn.go

The package comment information has expired, clean it up.

Update wsconn package comment

---

client/local/local.go
cmd/tailscale/cli/up.go
control/controlclient/direct.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go
ipn/prefs.go

all: use buildfeatures consts in a few more places

---

wgengine/magicsock/relaymanager_test.go

wgengine/magicsock: add more handleNewServerEndpointRunLoop tests

---

cmd/tailscaled/tailscaled.go

cmd/tailscaled: guard some flag work with buildfeatures checks

---

client/local/local.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go

Saves ~94 KB from the min build.
Updates #12614

ipn/localapi: dead code eliminate unreachable/useless LocalAPI handlers when disabled

---

cmd/tailscaled/tailscaled.go

Since #17376, containerboot crashes on startup in k8s because state encryption is enabled by default without first checking that it's compatible with the selected state store. Make sure we only default state encryption to enabled if it's not going to immediately clash with other bits of tailscaled config.
Updates tailscale/corp#32909
Change-Id: I76c586772750d6da188cc97b647c6e0c1a8734f0

cmd/tailscaled: default state encryption off for incompatible args

---

ipn/ipnlocal/expiry.go
wgengine/magicsock/magicsock.go
wgengine/router/osrouter/router_linux.go
wgengine/userspace.go

There are four separate commits here.
There are a few more cases to do after this, but they are more complex, so I'll
send those separately.

Use eventbus.SubscribeFunc where applicable

---

wgengine/magicsock/endpoint.go

This commit also shuffles the hasPeerRelayServers atomic load to happen sooner, reducing the cost for clients with no peer relay servers.
Updates tailscale/corp#33099

wgengine/magicsock: start peer relay path discovery sooner
