.gitignore

.gitignore: ignore compiled binaries in the cmd folders

---

Dockerfile

This isn't perfect, but a good start.

Introduce a simple Dockerfile

---

control/controlclient/auto_test.go
control/controlclient/direct_test.go
ipn/e2e_test.go

controlclient, ipn: update tests for key pointer change

---

SECURITY.md

Adding this file adds UI hints to Github about vulnerability reports, and also gives me a place to point an issue template at for easier discovery.

Add a SECURITY.md for vulnerability reports.

---

wgengine/router_default.go

wgengine: add required NewFakeRouter parameter

---

wgengine/faketun.go
wgengine/router_fake.go
wgengine/router_linux.go
wgengine/rusage.go
wgengine/rusage_nowindows.go
wgengine/userspace.go
wgengine/watchdog.go
wgengine/wgengine.go

Still a WIP. For discussion with @crawshaw first.

wgengine: flesh out some docs

---

cmd/tsshd/tsshd.go
go.mod
go.sum
wgengine/ifconfig_windows.go
wgengine/router_windows.go
wgengine/rtnlmon/mon.go

wgengine: fix windows build for winipcfg-go

---

.github/workflows/linux.yml
test.sh

First pass at #37 without support for cross-compilation of tests
Signed-off-by: evalexpr <wilkinsphysics@gmail.com>

Try build/test different geese in CI

---

logpolicy/logpolicy.go

And minor cleanups.
Let me know if my docs are accurate.

logpolicy: add some docs

---

wgengine/router_bsd.go
wgengine/router_default.go

wgengine: build for freebsd

---

control/controlclient/auto.go
control/controlclient/direct.go
wgengine/magicsock/magicsock.go

control/controlclient, wgengine/magicsock: misc cleanups

---

control/controlclient/auto.go
control/controlclient/controlclient_test.go
ipn/backend.go
ipn/local.go
types/empty/message.go

types/empty: add Message, stop using mysterious *struct{}

---

Dockerfile

Dockerfile: optimize incremental build a bit, copy all binaries to output

---

tailcfg/tailcfg.go
tailcfg/tailcfg_test.go

tailcfg: don't panic on node equal check

---

cmd/tailscale/tailscale.go
cmd/tailscaled/tailscaled.go
ipn/backend.go
ipn/fake.go
ipn/handle.go
ipn/ipnserver/server.go
ipn/local.go
ipn/message.go
ipn/message_test.go
ipn/prefs.go
ipn/prefs_test.go

ipn: temporary support for loading legacy relaynode configs.

---

derp/derp.go
derp/derp_client.go
derp/derp_server.go

Addresses one of crawshaw's TODOs.

derp: change the protocol framing to always include a length

---

wgengine/magicsock/magicsock.go

Updates #92 (not a complete fix; could be better/faster?)

wgengine/magicsock: reset favorite address on handshakes

---

wgengine/magicsock/magicsock.go

First commit removes some old cruft.
Second commit makes sure `UpdateDst` doesn't treat a DERP magic IP as a roaming address, because that won't go anywhere.
Neither seems to fix my 15-second timeout window bug, but I found them along the way.

magicsock: cleanup unused code and keep DERP out of the roaming IP slot

---

wgengine/magicsock/magicsock.go

The x/time/rate dependency adds 24kb to tailscaled binary size.

magicsock: rate limit send error log messages

---

go.mod
go.sum
wgengine/router_linux.go

wgengine: don't create duplicate iptables rules on Linux, clean up

---

cmd/derper/derper.go
derp/derp_server.go
metrics/metrics.go
tsweb/tsweb.go

tsweb, derp: add expvar http.Handler for Prometheus's format

---

derp/derphttp/derphttp_client.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go
wgengine/userspace.go

Hopefully more coming later today. Current TODO list:

magicsock: some tests

---

wgengine/magicsock/magicsock.go

magicsock: lookup AddrSet by key from DERP

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: don't discard UDP packet on UDP+DERP race

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

wgengine/magicsock: plumb logf throughout, and expose in Options.

---

derp/derp_server.go

Updates #162
Updates #163 (maybe)

derp: add varz for home moves

---

net/interfaces/interfaces.go
wgengine/magicsock/magicsock.go
wgengine/monitor/monitor.go

So we can at least re-STUN on boring updates.

Move linkstate boring change filtering to magicsock

---

wgengine/magicsock/magicsock.go

magicsock: remove TODO

---

derp/derp_server.go

derp: add clients_replaced counter

---

netcheck/netcheck.go

(Otherwise any DERP server down is a failure.)

netcheck: ignore IPv4 STUN failures if we saw at least one reply

---

cmd/derper/derper.go
derp/derp_client.go
derp/derp_server.go
derp/derp_test.go
derp/derphttp/derphttp_server.go
net/nettest/conn.go
net/nettest/pipe.go
net/nettest/pipe_test.go

Hopefully this fixes the staircase connection problem we've been seeing.

Test and workaround (mostly test) a derp tx/rx interaction between independent clients

---

wgengine/magicsock/magicsock.go
wgengine/userspace.go
wgengine/wgengine.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/184)

wgengine: don't Reconfig on boring link changes

---

wgengine/magicsock/magicsock.go

Before, endpoint updates were constantly being interrupted and resumed
on Linux due to tons of LinkChange messages from over-zealous Linux
netlink messages (from router_linux.go)
Now that endpoint updates are fast and bounded in time anyway, just
let them run to completion, but note that another needs to be
scheduled after.
Now logs went from pages of noise to just:
```
root@taildoc:~# grep -i -E 'stun|endpoint update' log
2020/03/13 08:51:29 magicsock.Conn: starting endpoint update (initial)
2020/03/13 08:51:30 magicsock.Conn.ReSTUN: endpoint update active, need another later ("link-change-minor")
2020/03/13 08:51:31 magicsock.Conn: starting endpoint update (link-change-minor)
2020/03/13 08:51:31 magicsock.Conn.ReSTUN: endpoint update active, need another later ("link-change-minor") …
```

wgengine/magicsock: don't interrupt endpoint updates, merge all mutexes into one

---

cmd/relaynode/relaynode.go
cmd/tailscale/tailscale.go
control/controlclient/auto_test.go
go.mod
go.sum
ipn/prefs.go
ipn/prefs_test.go
tailcfg/tailcfg_test.go
wgengine/magicsock/magicsock_test.go

For https://github.com/tailscale/wireguard-go/pull/12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/187)

all: update to wireguard-go API changes

---

tsweb/log.go

This is a prelude to having logging helpers in tsweb.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/189)

tsweb: pull in tlog data structures from corp repo.

---

portlist/netstat.go
portlist/netstat_test.go
portlist/portlist_darwin.go
portlist/portlist_linux.go
portlist/portlist_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/190)

portlist: ignore ports bound to localhost

---

.github/workflows/license.yml
atomicfile/atomicfile.go
net/nettest/pipe_test.go
scripts/check_license_headers.sh
tsweb/log.go
tsweb/tsweb.go
version/ver.go.in
wgengine/magicsock/magicsock.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/191)

WIP: Danderson/new ci

---

tsweb/log.go
tsweb/tsweb.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/192)

tsweb: adjust names and docs of the "handler with errors" functions.

---

wgengine/magicsock/magicsock.go

More steps towards IPv6 transport.
We now send it to tailcontrol, which ignores it.
But it doesn't actually actually support IPv6 yet (outside of STUN).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/196)

wgengine/magicsock: listen on udp6, use it for STUN, report endpoint

---

control/controlclient/direct.go
tailcfg/tailcfg.go
wgengine/magicsock/magicsock.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/198)

tailcfg, controlclient, magicsock: request IPv6 endpoints, but ignore them

---

derp/derp_server.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/203)

derp: export metric for server's initial MemStats.Sys reading

---

derp/derp_server.go

Makes it less complicated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/208)

derp: remove the mutex around and closing of send channel

---

derp/derp.go
derp/derp_client.go
derp/derp_server.go
derp/derp_test.go
wgengine/magicsock/magicsock.go

Updates #150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/209)

derp: send new "peer gone" frames when previous sender disconnects

---

control/controlclient/netmap.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/211)

control/controlclient: add TODO to delete the UAPI method

---

wgengine/magicsock/magicsock.go

Updates #207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/216)

wgengine/magicsock: if UDP blocked, pick DERP where most peers are

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

Revision to earlier 6284454ae5995
Don't be sticky if we have no peers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/220)

wgengine/magicsock: revise derp fallback logic

---

wgengine/magicsock/magicsock.go

28 is cutting it close, and we think jitter will help some spikes
we're seeing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/222)

wgengine/magicsock: re-stun every [20,27] sec, not 28

---

logpolicy/logpolicy.go

It'll do it anyway.
Makes journalctl -fu cleaner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/223)

logpolicy: don't log timestamp when running under systemd

---

cmd/tailscaled/tailscaled.go
ipn/ipnserver/server.go
ipn/ipnstate/ipnstate.go
ipn/local.go
types/key/key.go
wgengine/magicsock/magicsock.go
wgengine/userspace.go
wgengine/watchdog.go
wgengine/wgengine.go

Very early draft. Not very pretty or complete (no network maps) or
cross-referenced yet (engine peer stats need to be merged with
magicsock state and with network map info).
But it's something.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/224)

cmd/tailscaled, wgengine, ipn: add /debug/ipn handler with world state

---

cmd/tailscale/netcheck.go
cmd/tailscale/status.go
cmd/tailscale/tailscale.go
go.mod
go.sum
ipn/backend.go
ipn/fake_test.go
ipn/handle.go
ipn/ipnserver/server.go
ipn/ipnstate/ipnstate.go
ipn/local.go
ipn/message.go
net/interfaces/interfaces.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/232)

cmd/tailscale: add status subcommand

---

safesocket/unixsocket.go

(For cmd/tailscale CLI support on macOS)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/237)

safesocket: connect to the macOS network extension on darwin (as last resort)

---

ipn/local.go
ipn/policy/policy.go

Counterproposal to #239 (featuring docs & stuff)
And all 8xxx ports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/240)

ipn: filter portlist to a short list of "interesting" ports

---

logpolicy/logpolicy.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/250)

logpolicy: log on dials, add knob to force HTTP/1 for log uploads

---

tsweb/tsweb.go
tsweb/tsweb_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/251)

tsweb: don't flush, treat no-op Handler as 200, like Go

---

logtail/logtail.go
logtail/logtail_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/252)

logtail: reduce allocations encoding text

---

logtail/logtail.go

We'll be fixing the server so this won't trigger in practice,
but it demos the connection reuse problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/249)

logtail: read to EOF on chunked response

---

cmd/mkpkg/main.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/269)

cmd/mkpkg: fix missing default value for --depends

---

ipn/local.go
wgengine/userspace.go
wgengine/wgengine.go

Updates #282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/283)

wgengine: quiet some engine reconfig logging, make more consistent

---

wgengine/userspace.go

Fixes #273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/284)

wgengine: diagnose why CreateTUN might've failed for users

---

net/interfaces/interfaces.go
net/interfaces/interfaces_test.go
wgengine/userspace.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/278)

net/interfaces: add IsExpensive and up state to State

---

wgengine/magicsock/magicsock.go

/cc @bgentry
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/280)

wgengine/magicsock: reset AddrSet states on Rebind

---

wgengine/magicsock/magicsock.go

Fixes #276
/cc @bgentry
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/277)

wgengine/magicsock: close derp connections on rebind

---

.github/workflows/cross-darwin.yml
.github/workflows/cross-freebsd.yml
.github/workflows/cross-openbsd.yml
.github/workflows/cross-windows.yml
.github/workflows/license.yml
.github/workflows/linux.yml
.github/workflows/staticcheck.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/308)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171910389245016) by [Unito](https://www.unito.io/learn-more)

github: use Go 1.14 in CI.

---

control/controlclient/direct.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/310)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1172287743992775) by [Unito](https://www.unito.io/learn-more)

control/controlclient: fix deadlock in timeout+keepalive race

---

.github/workflows/staticcheck.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/323)

Disable staticcheck for tempfork packages.

---

wgengine/magicsock/magicsock.go

I know you love sync.Conds :). Pondering another code structure that lets us avoid it, but this is the minimum necessary fix to get correct ordering of shutdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/332)

wgengine/magicsock: wait for endpoint updater goroutine when closing.

---

control/controlclient/auto_test.go
ipn/e2e_test.go
ipn/message_test.go
tstest/clock.go
tstest/doc.go
tstest/log.go
tstest/resource.go
tsweb/tsweb_test.go

Every time I import "testy", I think I really ought to rename it. Finally remembered to do so between other changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/335)

tstest: rename from testy.

---

logpolicy/logpolicy.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/344)

logpolicy: report the correct error

---

cmd/tailscale/netcheck.go

cmd/netcheck: better DERP latency checking output

---

ipn/ipnstate/ipnstate.go

You can visualize the results here: https://codepen.io/sylr/full/ZEbXNdB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/347)

ipn/ipnstate: improve HTML output

---

Dockerfile
wgengine/router/router_linux.go
wgengine/userspace.go

Part of #368.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/369)

Fix handling of busybox's broken `ip` implementation.

---

go.mod
go.sum
netcheck/netcheck.go

Updates #207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/360)

netcheck: DERP latency over HTTPS when UDP failed

---

types/logger/logger.go

Updates #365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/366)

types/logger: simplify mutex locking in rate-limited logger

---

wgengine/router/router_linux.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/374)

wgengine/router: allow loopback traffic from our own IP(s).

---

ipn/local.go

Addresses issue #363, this is a pretty trivial solution.
Signed-off-by: Wendi Yu <wendi.yu@yahoo.ca>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/377)

ipn: reduce logspam from node with no peers

---

derp/derphttp/derphttp_client.go
go.mod

Updates #227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/380)

derp/derphttp: use SOCKS/etc proxies for derphttp dials

---

tailcfg/derpmap.go
tailcfg/tailcfg.go

Updates #387
Updates #388
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/386)

tailcfg: add DERP map structures

---

cmd/tailscale/tailscale.go
ipn/local.go
ipn/prefs.go
ipn/prefs_test.go
wgengine/router/router.go
wgengine/router/router_linux.go
wgengine/router/router_linux_test.go

Also adds a fairly terrible unit test that stubs out OS command calls, but verifies that we can transition from any state to any state without dropping the ball.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/384)

wgengine/router: support various states of disabled netfilter mangling.

---

cmd/tailscaled/tailscaled.go
go.sum
ipn/ipnserver/server_test.go
ipn/local.go
tailcfg/tailcfg.go
types/logger/logger.go
types/logger/logger_test.go
wgengine/userspace.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/381)

wgengine: log node IDs when peers are added/removed

---

control/controlclient/direct.go
log/logheap/logheap.go
log/logheap/logheap_test.go
tailcfg/tailcfg.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/268)

tailcfg: add MapResponse.Debug mechanism to trigger logging heap pprof

---

wgengine/tstun/tun.go

This is an alternative to #404 which also addresses @bradfitz's comment on needlessly exported errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/406)

tstun: tolerate zero reads

---

cmd/tailscale/tailscale.go
ipn/local.go
wgengine/router/router_linux.go
wgengine/router/router_linux_test.go
wgengine/router/runner.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/418)

A bunch of fixes to router_linux.

---

wgengine/userspace.go

We canceled the pingers in Close, but didn't wait around for their
goroutines to be cleaned up. This caused the ipn/e2e_test to catch
pingers in its resource leak check.
This commit introduces an object, but also simplifies the semantics
around the pinger's cancel functions. They no longer need to be called
while holding the mutex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/425)

wgengine: ensure pingers are gone before returning from Close

---

version/.gitignore
version/clean.do
version/describe.txt.do
version/long.txt.do
version/mkversion.sh
version/mkversion_test.go
version/short.txt.do
version/version.xcconfig.do

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/428)

version: support major.minor.patch tags without breaking Apple builds.

---

logpolicy/logpolicy.go

Fixes #247.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/253)

logpolicy: don't dump logging config in /

---

tsweb/jsonhandler.go
tsweb/jsonhandler_test.go

Updates #395
Signed-off-by: Zijie Lu <zijie@tailscale.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/437)

tsweb: JSONHandler using reflect

---

cmd/derper/derper.go
cmd/derper/mesh.go
derp/derp.go
derp/derp_client.go
derp/derp_server.go
derp/derp_test.go
derp/derphttp/derphttp_client.go

Updates #388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/440)

cmd/derper: support forwarding packets amongst set of peer DERP servers

---

version/cmp.go
version/cmp_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/458)

version: add an AtLeast helper to compare versions.

---

net/stun/stun.go

- Reuse IP length constants from net package.
- Remove beu16 to make endianness functions consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/463)

net/stun: Remove unreachable code

---

ipn/local.go

@bradfitz: this should get rid of the flake you mentioned. Curious that it didn't come up before; doesn't seem like that code was recently changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/480)

ipn: fix race in enterState

---

wgengine/magicsock/magicsock_test.go

Not quite what I was after, but I ran into this while tracking down #487. With small probability, the inner `t.Logf` can get used before the switch back to the outer one but after `t.Run` exits, which causes a confusing race that shows up as being inside `testing`.
The easiest way to avoid this seems to be this: switch to outer logger right before `t.Run` exits, changing the locking around so that all "in-flight" logging completes before this happens.
Unfortunately, with this done, `go test -race -count=1000` consistently passes for me in `magicsock`, so #487 remains a mystery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/494)

magicsock: eliminate logging race in test

---

version/xversion.go

Updates tailscale/tailscale#486
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/497)

version: add support for setting version with the -X Go linker flag

---

cmd/tailscale/tailscale.go

Use sysctl to check IP forwarding state for better OS compatiblity.
Signed-off-by: Brian Chu <cynix@cynix.org>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/459)

cmd/tailscale: Allow advertising subnet routes on *BSD.

---

control/controlclient/direct.go
control/controlclient/netmap.go
control/controlclient/netmap_test.go
ipn/local.go
tailcfg/tailcfg.go
types/opt/bool.go
types/opt/bool_test.go
wgengine/magicsock/magicsock.go
wgengine/tstun/tun.go
wgengine/tstun/tun_test.go
wgengine/userspace.go
wgengine/watchdog.go
wgengine/wgengine.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/511)

disable regular STUNs on inactivity

---

tstest/natlab/natlab.go
tstest/natlab/natlab_test.go

Adds a test with multiple networks, one of which is v4-only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/518)

tstest/natlab: correctly handle dual-stacked PacketConns.

---

tstest/natlab/natlab.go
tstest/natlab/natlab_test.go

No tests yet, opening PR early for API feedback. Thoughts?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/519)

Add HandlePacket and Inject, so machines can optionally mangle packets

---

.github/workflows/linux32.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/531)

github: also run 32-bit tests on Linux

---

tstest/natlab/natlab.go
tstest/natlab/natlab_test.go

Requires a bunch of refactoring so that Networks only ever
refer to Interfaces that have been attached to them, and
Interfaces know about both their Network and Machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/544)

tstest/natlab: provide inbound interface to HandlePacket.

---

wgengine/magicsock/magicsock.go

This appears to be the reason behind linux race tests failing due to leaked goroutines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/553)

wgengine/magicsock: wait for derphttp client goroutine to exit

---

tstest/natlab/nat.go
tstest/natlab/natlab.go
tstest/natlab/natlab_test.go

This lets us implement the most common kinds of NAT in the wild.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/551)

tstest/natlab: add a configurable SNAT44 translator.

---

atomicfile/atomicfile.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/558)

atomicfile: use ioutil.TempFile, sync

---

ipn/ipnserver/server.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/561)

ipn/ipnserver: support simultaneous connections

---

wgengine/magicsock/magicsock.go

https://github.com/tailscale/tailscale/commit/891898525c12630b0f896cb9142ff5274e07afc2 had a continue that meant the didCopy synchronization never ran.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/563)

wgengine/magicsock: update comment, fix earlier commit

---

.github/workflows/staticcheck.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/564)

github/workflows: add go vet ./... step

---

tailcfg/tailcfg.go
tailcfg/tailcfg_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/572)

tailcfg: add Hostinfo.OSVersion, DeviceModel

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/version.go

Fixes #448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/573)

cmd/tailscale: add "version" subcommand

---

wgengine/router/dns_resolvconf.go

Resolves #583.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/590)

wgengine/router: support legacy resolvconf

---

cmd/tailscaled/tailscaled.go

Currently, cleanup does not wait for logs to flush (unfortunately, I discovered this while looking at logs...). This is because it simply `return`s and log flushing was placed at the end of `main`. This fixes that, and removes some `Fatalf`s which will not wait for logs to flush either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/592)

cmd/tailscaled: always flush logs properly

---

wgengine/magicsock/magicsock_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/600)

wgengine/magicsock: refactor twoDevicePing

---

logtail/logtail.go
logtail/logtail_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/602)

logtail: return correct write size from logger.Write

---

derp/derp_server.go
ipn/ipnstate/ipnstate.go
net/netcheck/netcheck.go
tstest/natlab/natlab.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/601)

Add tests for active path discovery

---

wgengine/filter/filter.go
wgengine/filter/filter_test.go
wgengine/packet/ip.go

Fixes #402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/613)

wgengine/filter: don't spam logs about normal IPv6 LAN traffic

---

wgengine/userspace.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/616)

wgengine: disable wireguard config trimming for now except iOS w/ many peers

---

wgengine/router/dns_direct.go

This appears to be the reason behind systemd-resolved occasionally holding onto an old config after `/etc/resolv.conf` is changed.
Resolves #588.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/619)

router: reload systemd-resolved after changing /etc/resolv.conf

---

wgengine/router/router_userspace_bsd.go

The sandbox violations were due to `ifconfig down` being unintentionally included in `Close` for both darwin and freebsd. This fixes that. `downDNS` is a no-op on darwin, so it's fine to run it on both platforms. At the same time, `ifconfig down` is not actually the right thing to do on `freebsd`, as the command elaborates. Note that `cleanup` never runs in the darwin sandbox, as it is only called from `cmd/tailscaled`.
This is all a bit annoying to reason about; #615 refactors things into a better shape, but this is a minimal fix.
Resolves #597.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/617)

router: stop iOS subprocess sandbox violations

---

version/mkversion.sh
version/mkversion_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/633)

version: adjust to a pure semver version number, per bradfitz's proposal.

---

net/interfaces/interfaces_darwin.go
net/interfaces/interfaces_darwin_cgo.go
net/interfaces/interfaces_darwin_cgo_test.go
net/interfaces/interfaces_darwin_nocgo.go
net/interfaces/route.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/636)

net/interfaces: use syscalls to find private gateway IP address

---

logpolicy/logpolicy.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/642)

logpolicy: upload early logpolicy output, log where we decide to write logs

---

wgengine/tsdns/map.go
wgengine/tsdns/map_test.go
wgengine/tsdns/tsdns.go
wgengine/tsdns/tsdns_test.go
wgengine/userspace.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/640)

tsdns: implement reverse DNS lookups, canonicalize names everywhere.

---

control/controlclient/direct.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/649)

control/controlclient: reset timeout timer on non-keepalive map updates

---

wgengine/router/ifconfig_windows.go

Fixes tailscale/corp#542
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/653)

wgengine/router: set MTU on Windows to min(configured,possible)

---

cmd/derper/derper.go
derp/derp_server.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/652)

derp: add server version to /debug, expvars

---

control/controlclient/auto.go
ipn/ipnserver/server.go
logtail/backoff/backoff.go
logtail/logtail.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/660)

backoff: update to Go style, document a bit

---

control/controlclient/auto.go
ipn/local.go

Updates #604
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/628)

control/controlclient: use less battery when stopped, stop map requests

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/up.go
go.mod
go.sum

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/665)

cmd/tailscale/cli: validate advertised routes' IP address-vs-network bits

---

derp/derp_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/655)

add basic benchmark

---

net/interfaces/interfaces_linux.go
net/interfaces/interfaces_linux_test.go
net/netns/netns_linux.go
net/netns/netns_linux_test.go

@eliasnaur, can you try this?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/668)

net/netns, net/interfaces: move defaultRouteInterface, add Android fallback

---

derp/derp_server.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/677)

derp: remove two key.Public allocations

---

derp/derp_server.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/678)

derp: add a debug option to verbosely log drops to a destination.

---

net/interfaces/interfaces.go
wgengine/monitor/monitor_unsupported.go
wgengine/monitor/monitor_windows.go

Updates tailscale/corp#553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/679)

wgengine/monitor: add Windows linkchange monitor

---

tsweb/jsonhandler.go
tsweb/jsonhandler_test.go

This PR introduce a new `JSONHandler` without using reflect to solve the problems mentioned in #656 and #657.
Instead, `JSONHandler` takes a `JSONHandlerFunc`. It only take `*http.Request` as argument to avoid any misuse of `http.ResponseWriter`. The function's results must be (status int, data interface{}, err error).
```go
type JSONHandlerFunc func(r *http.Request) (status int, data interface{}, err error)
```
To unmarshal the request body, use the following code:
```go
body := new(DataType)
if err := json.NewDecoder(r.Body).Decode(body); err != nil {
return http.StatusBadRequest, nil, err
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/684)

tsweb: rewrite JSONHandler without using reflect

---

.github/workflows/cross-darwin.yml
.github/workflows/cross-freebsd.yml
.github/workflows/cross-openbsd.yml
.github/workflows/cross-windows.yml
.github/workflows/license.yml
.github/workflows/linux.yml
.github/workflows/linux32.yml
.github/workflows/staticcheck.yml
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/692)

Switch to Go 1.15.

---

wgengine/router/dns/manager_windows.go

It seems that global (as opposed to per-interface) state is required to accomplish this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/672)

router/dns: set all domains on Windows

---

wgengine/magicsock/magicsock.go
wgengine/userspace.go

Second attempt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/715)

magicsock: call RequestStatus when DERP connects

---

cmd/tailscale/cli/status.go
ipn/ipnstate/ipnstate.go
wgengine/magicsock/magicsock.go

Adds derp and endpoints information to `ipnstate.Status`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/703)

cmd/tailscale: add derp and endpoints status

---

cmd/cloner/cloner.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/738)

cmd/cloner: fix found type detection

---

cmd/cloner/cloner.go
tailcfg/tailcfg_clone.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/739)

cloner clone func

---

tstest/resource.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/743)

tstest: don't log on success

---

syncs/locked.go
syncs/locked_test.go
syncs/syncs.go
wgengine/router/dns/manager.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/744)

syncs: add AssertLocked

---

syncs/watchdog.go
syncs/watchdog_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/749)

syncs: add Watch, for monitoring mutex contention

---

wgengine/router/ifconfig_windows.go

Fixes #412
Updates #524
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/754)

wgengine/router: tolerate disabled IPv6 on Windows

---

control/controlclient/netmap.go

Fixes tailscale/corp#500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/763)

control/controlclient: don't accept /32 routes without --accept-routes

---

cmd/microproxy/microproxy.go

This makes it easier to run microproxy locally during development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/765)

cmd/microproxy: add -insecure flag

---

net/netns/netns_windows.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/776)

net/netns: document Windows socket binding a bit more

---

wgengine/tsdns/tsdns.go
wgengine/tsdns/tsdns_test.go

Noticed while debugging something else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/782)

wgengine/tsdns: handle bonjour service prefixes in rdns names

---

wgengine/tsdns/forwarder.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/790)

wgengine/tsdns: use netns to obtain a socket

---

wgengine/router/router_linux.go
wgengine/router/router_linux_test.go
wgengine/router/runner.go

Part of #19.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/773)

wgengine/router: set up basic IPv6 routing/firewalling.

---

control/controlclient/direct.go
control/controlclient/netmap.go
ipn/ipnstate/ipnstate.go
ipn/local.go
tailcfg/tailcfg.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/796)

all: slim down Netmap types

---

tstest/resource.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/800)

tstest: skip resource check when test has failed

---

ipn/ipnserver/server_test.go
logtail/filch/filch_test.go
tempfork/osexec/lp_unix_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/804)

all: use testing.T.TempDir

---

ipn/local.go
net/interfaces/interfaces.go
wgengine/userspace.go
wgengine/wgengine.go

Not configurable yet.
Updates tailscale/corp#653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/806)

ipn, wgengine: disable subnet routes if network has PAC configuration

---

tailcfg/tailcfg.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/811)

tailcfg: restore Role field to MapResponse

---

control/controlclient/direct.go
net/tsaddr/tsaddr.go
tailcfg/tailcfg.go
wgengine/router/router_linux.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/821)

Misc v6 setup work in OSS prior to teaching the control server about v6.

---

control/controlclient/direct.go
ipn/local.go
tailcfg/tailcfg.go

Updates tailscale/corp#634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/836)

tailcfg: bump, document MapRequest.Version value

---

ipn/local.go

Fixes tailscale/corp#732
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/842)

ipn: send machine key to clients so they can downgrade to 1.0.x if needed

---

.github/workflows/windows.yml

.github/workflows: add tests on Windows

---

ipn/ipnserver/server.go

If we can't find the mapping from SID ("user ID") -> username, don't
treat that as a fatal. Apparently that happens in the wild for Reasons.
Ignore it for now. It's just a nice-to-have for error messages in the
rare multi-user case.
Updates #869
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/871)

ipn/ipnserver: work around os/user.LookupId failure on Windows

---

wgengine/router/router_windows.go

Updating the Windows firewall is usually reasonably fast, but
sometimes blocks for, 20 seconds, 4 minutes, etc. Not sure why.
Until we understand that's happening, configure it in the background
without blocking the normal control flow.
Updates #785
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/867)

wgengine/router: make Windows firewall configuration async

---

tsweb/tsweb.go
tsweb/tsweb_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/874)

tsweb: add status code counter expvar support

---

.github/workflows/windows.yml

Fixes #872
Signed-off-by: Alex Brainman <alex.brainman@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/886)

.github/workflows: use cache to speed up Windows tests

---

version/mkversion.sh
version/mkversion_test.go

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/888)

version: use -g as the "other" suffix, so that `git show` works.

---

control/controlclient/direct.go
ipn/local.go
ipn/prefs.go
ipn/prefs_test.go

Two logging fix commits to ease debugging.

ipn: two logging fixes

---

control/controlclient/direct.go

control/controlclient: diagnose zero bytes from control

---

net/packet/packet.go

I figured out how to get rid of the unnecessary panic branches. :)

net/packet: minor optimizations to decoding

---

wgengine/userspace.go

First remove the device (to clear its wireguard session key), and then
add it back.
Fixes #929

wgengine: reconfigure wireguard peer in two steps when its disco key changes

---

wgengine/monitor/monitor_windows.go

I used the Windows APIs wrong previously, but it had worked just
enough.
Updates #921

wgengine/monitor: fix memory corruption in Windows implementation

---

logtail/logtail.go

Add content length hints to headers.
The server can use these hints to more efficiently select buffers.
Stop attempting to compress tiny requests.
The bandwidth savings are negligible (and sometimes negative!),
and it makes extra work for the server.

logtail: help the server be more efficient

---

tsweb/tsweb.go

tsweb: add an endpoint to manually trigger a GC.

---

control/controlclient/auto.go

control/controlclient: don't spin when starting up when node key is expired

---

wgengine/tsdns/tsdns.go
wgengine/tsdns/tsdns_test.go

wgengine/tsdns: fix error response marshaling, improve bad query logs

---

wgengine/router/router_linux.go

wgengine/router: disable IPv6 on Linux if ip rule -6 fails

---

wgengine/monitor/monitor_windows.go

eccc167 introduced winMin.closeHandle. The commit opens the handle,
but it never closes it.
Windows handles are not boundless, and should be closed.
Updates #921
Signed-off-by: Alex Brainman <alex.brainman@gmail.com>

wgengine/monitor: close winMin.closeHandle

---

control/controlclient/auto.go
control/controlclient/direct.go

Previously, any change to endpoints or hostinfo (or hostinfo's
netinfo) would result in the long-running map request HTTP stream
being torn down and restarted, losing all compression context along
with it.
This change makes us instead send a lite map request (OmitPeers: true,
Stream: false) that doesn't subscribe to anything, and then the
coordination server knows to not close other streams for that node
when it recives a lite request.
Fixes tailscale/corp#797

control/controlclient: use lite map request handler to avoid aborting streams

---

cmd/cloner/cloner.go
cmd/derper/derper.go
ipn/prefs.go
logtail/filch/filch.go
safesocket/unixsocket.go

all: adjust Unix permissions for those without umasks

---

logtail/logtail_test.go

This reverts commit e4f53e9b6f1a4d3d6f00091ddef617989b1ea3e4.
At least two of these tests are flakey, reverting until they can be
made more robust.

Revert "Add logtail tests (#1114)"

---

types/logger/logger.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go
wgengine/userspace.go

This is a series of commits; it may be easier to review them one at a time.

fix test flakes in wgengine/magicsock

---

wgengine/magicsock/magicsock_test.go

Test is flakey, remove it and figure out what to do differently later.

magicsock: remove TestConnClosing.

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

wgengine/magicsock: simplify ReceiveIPv4+DERP path

---

wgengine/magicsock/magicsock.go

To save CPU and wakeups, don't run the DERP cleanup timer regularly
unless there are 2+ DERP connections.

wgengine/magicsock: don't run the DERP cleanup timer so often

---

disco/disco.go
disco/disco_test.go
wgengine/magicsock/magicsock.go

disco: support parsing/encoding endpoints in call-me-maybe frames

---

disco/disco.go
wgengine/magicsock/magicsock.go

wgengine/magicsock: send, use endpoints in CallMeMaybe messages

---

Dockerfile
build_docker.sh

Partially Address #504 - (Dockerfile doesn't embed correct version) per https://github.com/tailscale/tailscale/issues/504#issuecomment-763733107
Signed-off-by: Steve Coffman <steve@khanacademy.org>

Add docker build script to inject version information

---

safesocket/unixsocket.go

Continuation of earlier two umask changes,
5611f290eb118eddc256560eaaa69f509347b4de and
d6e9fb1df0fd67d08065c2277e7c4f4a82b7930f.
This change mostly affects us, running tailscaled as root by hand (wit
a umask of 0077), not under systemd. End users running tailscaled
under systemd won't have a umask.

safesocket: on Linux, make /var/run/tailscale be 0755

---

ipn/ipnserver/server.go

ipn/ipnserver: on Windows in unattended mode, wait for Engine forever

---

wgengine/userspace.go

Also don't log.Fatalf in a function returning an error.
Fixes #1204

wgengine: fix crash reading long UAPI lines from legacy peers

---

cmd/tsshd/tsshd.go
net/interfaces/interfaces.go
net/interfaces/interfaces_test.go
tsweb/tsweb.go

net/interfaces: remove IsTailscaleIP, make callers use tsaddr.

---

net/interfaces/interfaces.go

net/interfaces: don't send over zt* interfaces

---

control/controlclient/direct.go
control/controlclient/netmap.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
util/dnsname/dnsname.go
util/dnsname/dnsname_test.go

tailcfg: update display name fields and methods

---

go.mod
go.sum
wgengine/magicsock/legacy.go
wgengine/magicsock/magicsock.go

wgenginer/magicsock: remove Addrs methods

---

tsweb/tsweb.go

tsweb: add num_goroutines expvar

---

wgengine/wglog/wglog.go

wgengine/wglog: don't log failure to send data packets

---

wgengine/router/router_linux.go

Previously we disabled v6 support if the disable_policy knob was
missing in /proc, but some kernels support policy routing without
exposing the toggle. So instead, treat disable_policy absence as a
"maybe", and make the direct `ip -6 rule` probing a bit more
elaborate to compensate.
Fixes #1241.

wgengine/router: probe better for v6 policy routing support.

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: filter disco packets and packets when stopped from wireguard

---

logpolicy/logpolicy.go

Signed-Off-By: Christine Dodrill <xe@tailscale.com>

logpolicy: use TS_LOG_TARGET

---

wgengine/magicsock/magicsock_test.go

We removed the "fast retry" code from our wireguard-go fork.
As a result, pings can take longer to transit when retries are required. 
Allow that.

wgengine/magicsock: allow more time for pings to transit

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

wgengine/magicsock: fix DERP reader hang regression during concurrent reads

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: reconnect to DERP home after network comes back up

---

wgengine/router/router_windows.go

wgengine/router: add another Windows firewall rule to allow incoming UDP

---

wgengine/tstun/tun.go

wgengine/tstun: reply to MagicDNS pings

---

cmd/hello/hello.go
cmd/hello/hello.tmpl.html

This PR adds styling to our hello.ipn.dev server to provide a nicer welcome to new users. All styles and embedded directly in the webpage, so there are no dependencies we need to load externally.
Styles follow the pattern of our Tailwind-based admin panel so it's easy to make edits in the future.
There's a spiffy little intro animation that only runs on the first load of the page, and falls back gracefully without any JS.
/cc @bradfitz

cmd/hello: style welcome message

---

cmd/hello/hello.tmpl.html

Fixes a bug where long machine names would push content out of the box. Gets me every time…

cmd/hello: truncate long strings

---

wgengine/magicsock/magicsock_test.go

When a handshake race occurs, a queued data packet can get lost.
TestTwoDevicePing expected that the very first data packet would arrive.
This caused occasional flakes.
Change TestTwoDevicePing to repeatedly re-send packets
and succeed when one of them makes it through.
This is acceptable (vs making WireGuard not drop the packets)
because this only affects communication with extremely old clients.
And those extremely old clients will eventually connect,
because the kernel will retry sends on timeout.

wgengine/magicsock: retry and re-send packets in TestTwoDevicePing

---

cmd/tailscaled/debug.go
cmd/tailscaled/install_darwin.go
cmd/tailscaled/tailscaled.go

Tangentially related to #987, #177, #594, #925, #505

cmd/tailscaled: fix up install-system-daemon on darwin, add uninstall too

---

wgengine/router/router_linux.go
wgengine/router/router_linux_test.go

This makes cidrDiff do as much as possible before failing, and makes a
delete of an already-deleted rule be a no-op. We should never do this
ourselves, but other things on the system can, and this should help us
recover a bit.
Also adds the start of root-requiring tests.
TODO: hook into wgengine/monitor and notice when routes are changed
behind our back, and invalidate our routes map and re-read from
kernel (via the ip command) at least on the next reconfig call.
Updates tailscale/corp#1338

wgengine/router: make Linux delRoute idempotent, cidrDiff fail late as possible

---

cmd/tailscale/cli/status.go
ipn/ipnstate/ipnstate.go
tailcfg/tailcfg.go
util/dnsname/dnsname.go
util/dnsname/dnsname_test.go

Fixes https://github.com/tailscale/corp/issues/1266

tailcfg: sanitize hostname in node display name generation

---

wgengine/userspace.go

wgengine: consistently close things when NewUserspaceEngineAdvanced errors

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

wgengine/magicsock: fix discoEndpoint caching bug when a node key changes

---

wgengine/netstack/netstack.go

wgengine/netstack: add Magic DNS + DNS resolution to SOCKS5 dialing

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
net/interfaces/interfaces.go

ipn/ipnlocal: transform default routes into "all but LAN" routes.

---

wgengine/netstack/netstack.go

wgengine/netstack: forward incoming connections to localhost

---

wgengine/netstack/netstack.go

wgengine/netstack: use system dialer to contact servers on localhost

---

wgengine/router/ifconfig_windows.go

This is necessary because either protocol can be disabled globally by a
Windows registry policy, at which point trying to touch that address
family results in "Element not found" errors. This change skips programming
address families that Windows tell us are unavailable.
Fixes #1396.

wgengine/router: make windows gracefully handle disabled IPv4 or IPv6.

---

portlist/clean.go
portlist/clean_test.go
portlist/netstat.go
portlist/portlist_linux.go

portlist: report a better process name for .Net on linux.

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

And if we have over 10,000 CGNAT routes, just route the entire
CGNAT range. (for the hello test server)
Fixes #1450

ipn/ipnlocal: make IPv6 OS routes be a single /48 for our ULA space

---

control/controlclient/direct.go
tailcfg/tailcfg.go

So the control server can test whether a client's actually present.
Most clients are over HTTP/2, so these pings (to the same host) are
super cheap.
This mimics the earlier goroutine dump mechanism.

tailcfg, control/controlclient: add MapResponse.PingRequestURL

---

wgengine/netstack/netstack.go

wgengine/netstack: add support for incoming UDP connections

---

wgengine/netstack/netstack.go

wgengine/netstack: stop UDP forwarding when one side dies

---

wgengine/router/router_openbsd.go

Similar to FreeBSD in https://github.com/tailscale/tailscale/issues/1307,
add IPv6 addresses with a prefix length of 48.
Fixes https://github.com/tailscale/tailscale/issues/1372

wgengine: add OpenBSD IPv6 support.

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

There was a logical race where Conn.Rebind could acquire the
RebindingUDPConn mutex, close the connection, fail to rebind, release
the mutex, and then because the mutex was no longer held, ReceiveIPv4
wouldn't retry reads that failed with net.ErrClosed, letting that
error back to wireguard-go, which would then stop running that receive
IP goroutine.
Instead, keep the RebindingUDPConn mutex held for the entirety of the
replacement in all cases.
Updates tailscale/corp#1289

wgengine/magicsock: fix Conn.Rebind race that let ErrClosed errors be read

---

control/controlclient/direct.go

IP forwarding is not required when advertising a machine's local IPs
over Tailscale.

control/controlclient: report broken IP forwarding more precisely.

---

wgengine/tsdns/forwarder.go
wgengine/tsdns/tsdns.go
wgengine/userspace.go

wgengine{,tsdns}: rebind MagicDNS forwarders on link change

---

net/netcheck/netcheck.go
net/netcheck/netcheck_test.go

net/netcheck: add a few more STUN retries for prior DERP home

---

control/controlclient/direct.go
health/health.go
wgengine/router/ifconfig_windows.go

wgengine/router: report to control when setPrivateNetwork fails

---

control/controlclient/auto.go
health/health.go
ipn/ipnlocal/local.go

health, ipn/ipnlocal: track, log overall health

---

wgengine/monitor/monitor_darwin.go

Should help iOS battery life on NEProvider.wake/skip events
with useless route updates that shouldn't cause re-STUNs.

wgengine/monitor: skip more route messages on darwin

---

net/portmapper/portmapper.go

net/portmapper: silently handle PCP NOT_AUTHORIZED responses.

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

wgengine/magicsock: don't update control if only endpoint order changes

---

cmd/tailscale/cli/ping.go
ipn/backend.go
ipn/fake_test.go
ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go
ipn/message.go
net/packet/packet.go
net/packet/tsmp.go
wgengine/filter/filter.go
wgengine/tstun/tun.go
wgengine/userspace.go
wgengine/watchdog.go
wgengine/wgengine.go

net/packet, wgengine/{filter,tstun}: add TSMP ping

---

ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go
ipn/ipnstate/ipnstate.go
wgengine/magicsock/magicsock.go

Also some necessary refactoring of the ipn/ipnstate too.

ipn/ipnlocal: start of peerapi between nodes

---

syncs/watchdog_test.go

The Windows CI machine experiences significant random execution delays.
For example, in this code from watchdog.go:
```go
done := make(chan bool)
go func() {
start := time.Now()
mu.Lock()
```
There was a 500ms delay from initializing done to locking mu.
This test checks that we receive a sufficient number of events quickly enough.
In the face of random 500ms delays, unsurprisingly, the test fails.
There's not much principled we can do about it.
We could build a system of retries or attempt to detect these random delays,
but that game isn't worth the candle.
Skip the test.

syncs: disable TestWatchMultipleValues on Windows CI builds

---

wgengine/monitor/monitor.go

... to force rebinds of TCP connections
Fixes #1555
Updates tailscale/felicity#4

wgengine/monitor: on wall time jump, synthesize network change event

---

ipn/backend.go
ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go

ipn{,/ipnlocal}: set new Notify.FilesWaiting when server has file(s)

---

wgengine/magicsock/magicsock_test.go

It can end up executing an a new goroutine,
at which point instead of immediately stopping test execution, it hangs.
Since this is unexpected anyway, panic instead.
As a bonus, it makes call sites nicer and removes a kludge comment.

wgengine/magicsock: don't call t.Fatal in magicStack.IP

---

cmd/tailscale/cli/web.go
cmd/tailscale/cli/web.html

This is a draft of a some UI improvements for the web frontend introduced in #1605. It's pretty basic at the moment, showing device and user information, and any urgent actions that need to be taken.

cmd/tailscale: add initial web UI

---

net/interfaces/interfaces_linux.go

io.EOF gets morphed into a "no default routes found" error
if we hit https://github.com/google/gvisor/issues/5732
Check for the correct err.

interfaces: check correct error /proc/net/route

---

client/tailscale/tailscale.go
cmd/tailscale/cli/bugreport.go
cmd/tailscale/cli/cli.go
ipn/ipnserver/server.go
ipn/localapi/localapi.go

Adding a subcommand which prints and logs a log marker. This should help diagnose any issues that users face.
Fixes #1466

cmd/tailscale, ipn/localapi: add "tailscale bugreport" subcommand

---

cmd/tailscaled/install_darwin.go

cmd/tailscaled: remove tailscaled binary on uninstall-system-daemon

---

tailcfg/tailcfg_test.go
wgengine/magicsock/magicsock_test.go

The code is not obviously better or worse, but this makes the little warning
triangle in my editor go away, and the distraction removal is worth it.

all: gofmt -s

---

internal/deepprint/deepprint_test.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go
wgengine/wgcfg/config.go
wgengine/wgcfg/nmcfg/nmcfg.go
wgengine/wgcfg/parser.go
wgengine/wgcfg/writer.go

This PR fixes the test failures at head in the corp repo.
See the commit messages for explanation.

all: remove listen_port and simplify magicsock

---

ipn/localapi/localapi.go

ipn/localapi: 404 on bad endpoints

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
ipn/localapi/localapi.go

I'm out tomorrow but I knew people were waiting for this, but unfortunately it doesn't work.
The peerapi4/peerapi6 are still getting filtered by control somewhere.
But once control is fixed this should work. (but it has extra XXX debug logging in it that somebody should remove but merging)
To debug control, run tailscaled with `TS_DEBUG_MAP=1` and look for any peers having `peerapi4` and/or `peerapi6` services.
To use/debug this localapi for file targets, use e.g.
```
$ sudo curl --unix-socket /var/run/tailscale/tailscaled.sock http://foo/localapi/v0/file-targets
[]
```

ipn/localapi: add API for getting file targets

---

net/nettest/conn.go
net/nettest/conn_test.go
net/nettest/listener.go
net/nettest/listener_test.go
net/nettest/pipe.go
net/nettest/pipe_test.go

net/nettest: make nettest.NewConn pass x/net/nettest.TestConn

---

cmd/tailscaled/tailscaled.go
cmd/tailscaled/tailscaled_windows.go
ipn/ipnlocal/local.go
wgengine/netstack/netstack.go
wgengine/netstack/subnet_router_wrapper.go
wgengine/userspace.go
wgengine/userspace_ext_test.go
wgengine/userspace_test.go

cmd/tailscaled, wgengine{,/netstack}: add netstack hybrid mode, add to Windows

---

control/controlclient/sign_supported.go

When searching for the matching client identity, the returned
certificate chain was accidentally set to that of the last identity
returned by the certificate store instead of the one corresponding to
the selected identity.
Also, add some extra error checking for invalid certificate chains, just
in case.

control/controlclient: return correct certificate

---

cmd/tailscaled/tailscaled.go
ipn/backend.go
ipn/ipnlocal/local.go
ipn/ipnserver/server.go
paths/paths.go

ipn, paths, cmd/tailscaled: remove LegacyConfigPath, relaynode migration

---

ipn/ipnlocal/local.go
net/tstun/wrap.go
net/tstun/wrap_test.go

net/tstun: accept peerapi connections through the filter

---

ipn/backend.go
ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go

for @crawshaw to review.
FYI @soniaappasamy and @rosszurowski, also welcome any feedback

ipn/ipnlocal: provide IPN bus updates as files arrive

---

control/controlclient/direct.go

Closes #1686
Signed-off-by: Simon Kirillov svkirillov3@gmail.com

Create tls client config with server hostname instead of serverURL.Host

---

api.md

Signed-off-by: Daniel Chung <daniel@tailscale.com>

api.md: clarify response behaviour for ACL POST endpoint

---

net/dns/nm.go

Leaving as a PR to myself for tomorrow, as I can't brain enough to check this for goodness right now.

net/dns: support split and unsplit DNS in NetworkManager.

---

derp/derp_test.go

derp: handle net.ErrClosed in TestSendFreeze

---

cmd/tailscale/cli/up.go
ipn/ipnlocal/local.go
ipn/prefs.go
ipn/prefs_clone.go
ipn/prefs_test.go
wgengine/router/router.go
wgengine/router/router_linux.go
wgengine/router/router_linux_test.go

ipn/ipnlocal,wgengine/router,cmd/tailscale: add flag to enable local network access when using exit nodes.

---

net/stun/stun_fuzzer.go

This PR fixes the stun fuzzer.

stun fuzzer: Small fix

---

wgengine/router/router_userspace_bsd.go

wgengine/router: add the Tailscale ULA route on darwin

---

control/controlclient/direct.go
control/controlclient/direct_test.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
version/version.go

And fix PeerSeenChange bug where it was ignored unless there were
other peer changes.
Updates tailscale/corp#1574

tailcfg, control/controlclient: (mapver 16) add Node.Online, MapResponse.OnlineChange

---

net/tsaddr/tsaddr.go

net/tsaddr: add new IP range for ephemeral nodes in Tailscale ULA

---

cmd/tailscaled/tailscaled.go

cmd/tailscaled: let SOCKS5 dial non-Tailscale addrs in userspace mode

---

control/controlclient/map.go
control/controlclient/map_test.go
tailcfg/tailcfg.go

tailcfg, control/controlclient: allow empty MapResponse.Domain (mapver17)

---

cmd/tailscale/cli/up.go
ipn/ipnlocal/local.go
ipn/ipnserver/server.go
ipn/prefs.go
ipn/prefs_clone.go
ipn/prefs_test.go

From discussion with @danderson.
Fixes #1684 (in a different way)

ipn, cmd/tailscale/cli: add pref to configure sudo-free operator user

---

net/tsaddr/tsaddr.go

net/tsaddr: expand ephemeral nodes range to /64

---

ipn/ipnlocal/local.go

ipn/ipnlocal: restrict local lan access to linux machines.

---

.github/workflows/linux-race.yml
.github/workflows/windows-race.yml

.github/workflows: add --race tests on Linux and Windows

---

cmd/tailscaled/tailscaled_windows.go
ipn/ipnserver/server.go

With this change, the ipnserver's safesocket.Listen (the localhost
tcp.Listen) happens right away, before any synchronous
TUN/DNS/Engine/etc setup work, which might be slow, especially on
early boot on Windows.
Because the safesocket.Listen starts up early, that means localhost
TCP dials (the safesocket.Connect from the GUI) complete successfully
and thus the GUI avoids the MessageBox error. (I verified that
pacifies it, even without a Listener.Accept; I'd feared that Windows
localhost was maybe special and avoided the normal listener backlog).
Once the GUI can then connect immediately without errors, the various
timeouts then matter less, because the backend is no longer trying to
race against the GUI's timeout. So keep retrying on errors for a
minute, or 10 minutes if the system just …

cmd/tailscaled: don't block ipnserver startup behind engine init on Windows

---

wgengine/wgcfg/nmcfg/nmcfg.go

These were getting rate-limited for nodes with many peers.
Buffer the output and emit a single line, which is nicer anyway.

wgengine/wgcfg/nmcfg: consolidate "skipped unselected" log lines

---

wgengine/netstack/netstack.go

wgengine/netstack: log ForwarderRequest in readable form, only in debug mode

---

control/controlclient/auto.go
ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

ipn/ipnlocal: on fresh lazy-connecting install, start in state NeedsLogin

---

ipn/ipnlocal/local.go

It was getting cleared on notify.
Document that authURL is cleared on notify and add a new field that
isn't, using the new field for the JSON status.

ipn/ipnlocal: fix tailscale status --json AuthURL field

---

cmd/tailscale/cli/up.go

cmd/tailscale: don't print out old authURL on up --force-reauth

---

health/health.go
wgengine/magicsock/magicsock.go

Review skeptically; I'm not entirely sure I'm holding package health correctly.

health: track whether magicsock receive functions are running

---

ipn/ipnlocal/peerapi.go
ipn/ipnlocal/peerapi_test.go

oh, Windows.
Updates tailscale/corp#1626

ipn/ipnlocal: put a retry loop around Windows file deletes

---

ipn/ipnlocal/peerapi.go
ipn/ipnlocal/peerapi_test.go

ipn/ipnlocal: add peerapi goroutine fetch

---

net/dns/resolver/forwarder.go

net/dns/resolver: remove unnecessary/racy WaitGroup.

---

ipn/ipnlocal/local.go

Updates tailscale/corp#1621
/cc @apenwarr

ipn/ipnlocal: close peer API listeners on transition away from Running

---

ipn/backend.go
ipn/ipnlocal/local.go

Updates tailscale/corp#1621
/cc @apenwarr @soniaappasamy @maisem

ipn/ipnlocal: add a LocalBackend.Start fast path if already running

---

ipn/ipnlocal/peerapi.go
ipn/ipnlocal/peerapi_test.go

If DeleteFile fails on Windows due to another process (anti-virus,
probably) having our file open, instead leave a marker file that the
file is logically deleted, and remove it from API calls and clean it
up lazily later.
Fixes tailscale/corp#1626

ipn/ipnlocal: use delete marker files to work around Windows delete problems

---

health/health.go
wgengine/magicsock/magicsock.go

Tomorrow will no doubt bring yet another reworking.
Two commits here: First deletes the previous implementation, second adds a new one.

health: fix receive func health checks for today

---

wgengine/userspace.go

wgengine: periodically poll engine status for logging side effect

---

health/health.go
wgengine/magicsock/magicsock.go

Please review commits individually.

wgengine/magicsock: follow-up bind cleanups

---

tstest/integration/integration_test.go

Only minimal tailscale + tailscaled for now.
And a super minimal in-memory logcatcher.
No control ... yet.

testing: add start of an integration test

---

tstest/integration/integration_test.go
tstest/integration/testcontrol/testcontrol.go

tstest/integration/testcontrol: add start of test control server

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go

This fixes #1833 in two ways:
* stop setting NoSNAT on non-Linux. It only matters on Linux and the flag
is hidden on non-Linux, but the code was still setting it. Because of
that, the new pref-reverting safety checks were failing when it was
changing.
* Ignore the two Linux-only prefs changing on non-Linux.
Fixes #1833

cmd/tailscale: make pref-revert checks ignore OS-irrelevant prefs

---

cmd/tailscale/cli/web.go
cmd/tailscale/cli/web.html
paths/paths.go

With this the web UI login button works on DSM 6.

synology web UI

---

ipn/ipnlocal/peerapi.go

ipn/ipnlocal: redact more errors

---

net/tsaddr/tsaddr.go
net/tsaddr/tsaddr_test.go
wgengine/userspace.go

I want to use this from netstack but it's not exported.

net/tsaddr: add NewContainsIPFunc (move from wgengine)

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go

cmd/tailscale: fix tailscale up --advertise-exit-node validation

---

net/tstun/wrap.go
net/tstun/wrap_test.go

Whenever we dropped a packet due to ACLs, wireguard-go was logging:
Failed to write packet to TUN device: packet dropped by filter
Instead, just lie to wireguard-go and pretend everything is okay.
Fixes #1229

net/tstun: fix TUN log spam when ACLs drop a packet

---

wgengine/userspace.go

It is unused, and has been since early Feb 2021 (Tailscale 1.6).
We can't get delete the DeviceOptions entirely yet;
first #1831 and #1839 need to go in, along with some wireguard-go changes.
Deleting this chunk of code now will make the later commits more clearly correct.

wgengine/userspace: delete HandshakeDone

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go

The --advertise-routes and --advertise-exit-node flags both mutating
one pref is the gift that keeps on giving.
I need to rewrite the this up warning code to first map prefs back to
flag values and then just compare flags instead of comparing prefs,
but this is the minimal fix for now.
This also includes work on the tests, to make them easier to write
(and more accurate), by letting you write the flag args directly and
have that parse into the upArgs/MaskedPrefs directly, the same as the
code, rather than them being possibly out of sync being written by
hand.
Fixes https://twitter.com/EXPbits/status/1390418145047887877

cmd/tailscale: fix another up warning with exit nodes

---

scripts/installer.sh

Bit of a draft state still. We inventoried OSes and transcribed our current install instructions, but I have to switch gears to debugging right now, so throwing this into a PR for initial thoughts.

scripts: add an install script.

---

cmd/tailscale/cli/web.go

cmd/tailscale: web login fixes for Synology/QNAP

---

tstest/integration/vms/vms_test.go

tstest/integration/vms: small cleanups

---

tstest/integration/vms/vms_test.go

Previously we spewed a lot of output to stdout and stderr, even when
`-v` wasn't set. This is sub-optimal for various reasons. This patch
makes a writer out of testing.TB so that output can be shunted to
test logs.
Updates #1988

tstest/integration/vms: t.Log for VM output

---

tstest/integration/vms/vms_test.go

This lets us see the names of distros in our tests.
Updates #1988

tstest/integration/vms: maintain distro info

---

tstest/integration/vms/vms_test.go

Instead of testing all the VMs at once when they are all ready, this
patch changes the testing logic so that the vms are tested as soon as
they register with testcontrol. Also limit the amount of VM ram used at
once with the `-ram-limit` flag. That uses a semaphore to guard resource
use.
Updates #1988

tstest/integration/vms: test vms as they are ready

---

tstest/integration/vms/vms_test.go

Previously this built the binaries for every distro. This is a bit
overkill given we are using static binaries. This patch makes us only
build once.
There was also a weird issue with how processes were being managed.
Previously we just killed qemu with Process.Kill(), however that was
leaving behind zombies. This has been mended to not only kill qemu but
also waitpid() the process so it doesn't become a zombie.
Updates #1988

tstest/integration/vms: only build binaries once

---

tstest/integration/vms/vms_test.go

I've run into a couple issues where the tests time out while a VM image
is being downloaded, making the cache poisoned for the next run. This
moves the hash checking into its own function and calls it much sooner
in the testing chain. If the hash check fails, the OS is redownloaded.

tstest/integration/vms: aggressively re-verify shasums

---

tstest/integration/integration_test.go
tstest/integration/testcontrol/testcontrol.go

Adding new enum for update channel, added map for PingRequests
Signed-off-by: Simeng He <simeng@tailscale.com>

Adding AddPingRequest, and sending a new enum to Keepaliveloop

---

net/dns/resolver/forwarder.go

net/dns/resolver: don't spam logs on EHOSTUNREACH.

---

cmd/mkpkg/main.go
packages/deb/deb.go
packages/deb/deb_test.go

packages/deb: new package to extract metadata from .debs.

---

tstest/integration/vms/vms_test.go

tstest/integration/vms: bump images for upstream changes

---

.github/workflows/xe-experimental-vm-test.yml
tstest/integration/vms/runner.nix

This runner is in my homelab while we muse about a better, more
permanent home for these tests.
Updates #1988

.github/workflows: add integration test with a custom runner

---

wgengine/router/router_openbsd.go

The route creation for the `tun` device was augmented in #1469 but
didn't account for adding IPv4 vs. IPv6 routes. There are 2 primary
changes as a result:
* Ensure that either `-inet` or `-inet6` was used in the
[`route(8)`](https://man.openbsd.org/route) command
* Use either the `localAddr4` or `localAddr6` for the gateway argument
depending which destination network is being added
The basis for the approach is based on the implementation from
`router_userspace_bsd.go`, including the `inet()` helper function.
Fixes #2048
References #1469
Signed-off-by: Fletcher Nichol <fnichol@nichol.ca>

wgenine/router: fix OpenBSD route creation

---

derp/derp_server.go

It would be useful to know the time that packets spend inside of a queue before they are sent
off, as that can be indicative of the load the server is handling (and there was also an
existing TODO). This adds a simple exponential moving average metric to track the average packet
queue duration.
req `danderson` for review because he was cited in the original TODO.
Signed-off-by: julianknodt <julianknodt@gmail.com>

derp: add pkt queue latency timer

---

ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go

tailcfg: add DNSConfig.SetDNSDomains

---

net/dns/manager_linux.go

It appears that Proxmox/LXC can install a resolv.conf that mentions
systemd-resolved by name in its header comment, but actually has nothing
at all to do with systemd-resolved. On such setups, we incorrectly choose
to configure resolved even though it has no control over the "true" DNS
configuration.
Work around this by only using resolved if resolv.conf mentions resolved
in its header comment, _and_ has a single resolver pointing to 127.0.0.53.
Strictly speaking, this can break a valid configuration of resolved, where
resolv.conf is symlinked to a resolved-managed file that just lists upstream
DNS servers directly. However, as far as I know, this configuration never
occurs in the wild, and that "upstreams directly" resolv.conf is meant
for consumption by the likes of dnsmasq and other …

net/dns: work around mysterious LXC resolv.conf.

---

tstest/integration/vms/vms_test.go

Previously we used t.Logf indirectly via package log. This worked, but
it was not ideal for our needs. It could cause the streams of output to
get crossed. This change uses a logger.FuncWriter every place log.Output
was previously used, which will more correctly write log information to
the right test output stream.

tstest/integration/vms: log to t.Logf directly

---

ipn/ipnlocal/local.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go

Updates #1748
Updates #1235
Updates #2055

tailcfg: add DNSConfig.ExtraRecords

---

cmd/derper/derper.go
cmd/microproxy/microproxy.go
tsweb/debug.go
tsweb/debug_test.go
tsweb/tsweb.go

tsweb: replace NewMux with a more flexible DebugHandler.

---

tailcfg/tailcfg.go

tailcfg: add Debug.RandomizeClientPort

---

ipn/ipnlocal/peerapi_macios_ext.go
net/dns/manager.go
net/dns/manager_test.go
net/dns/resolver/forwarder.go
net/dns/resolver/macios_ext.go
net/dns/resolver/tsdns.go
net/dns/resolver/tsdns_test.go
net/netns/netns_macios.go
tstest/resource.go
wgengine/userspace.go

Fixes #2224
Fixes tailscale/corp#2045

net/dns{,/resolver}: refactor DNS forwarder, send out of right link on macOS/iOS

---

net/dns/resolver/forwarder.go
net/dns/resolver/tsdns_server_test.go
net/dns/resolver/tsdns_test.go

This change (subject to some limitations) looks for the EDNS OPT record
in queries and responses, clamping the size field to fit within our DNS
receive buffer. If the size field is smaller than the DNS receive buffer
then it is left unchanged.
I think we will eventually need to transition to fully processing the
DNS queries to handle all situations, but this should cover the most
common case.
Mostly fixes #2066

net/dns/resolver: clamp EDNS size

---

net/dns/direct.go
net/dns/resolved.go

net/dns: remove ref to managerImpl

---

wgengine/filter/filter.go

This uses a debug envvar to optionally disable filter logging rate
limits by setting the environment variable
TS_DEBUG_FILTER_RATE_LIMIT_LOGS to "all", and if it matches,
the code will effectively disable the limits on the log rate by
setting the limit to 1 millisecond. This should make sure that all
filter logs will be captured.

wgengine/filter: add a debug flag for filter logs

---

net/dns/resolver/neterr_other.go

This has been bothering me for a while, but everytime I run format from the root directory
it also formats this file. I didn't want to add it to my other PRs but it's annoying to have to
revert it every time.
I don't really think this needs much review if at all, so merge it whenever

net/dns/resolver: fmt item

---

.github/workflows/xe-experimental-vm-test.yml

This is an experiment to see how often this test would fail if we run it
on every commit. This depends on #2145 to fix a flaky part of the test.

integration vm tests: run on every commit to main

---

control/controlclient/direct.go
ipn/prefs.go
ipn/prefs_test.go
net/dnsfallback/dnsfallback.go
net/interfaces/interfaces.go

ipn, etc: use controlplane.tailscale.com

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go

cmd/tailscale/cli: accept login server synonym

---

api.md

The implementation of the preview function has changed since the
API was documented, update the document to match.

api.md: update preview example

---

net/tstun/wrap.go

Every TUN Read went through several multi-case selects.
We know from past experience with wireguard-go that these are slow
and cause scheduler churn.
This PR removes multi-case selects from hot code.
There are three commits; the first contains the substantive change.
The other two are simplifications.

net/tstun: remove multi-case selects from hot code

---

util/deephash/deephash.go
util/deephash/deephash_test.go

```
Hash-6              69.4µs ± 6%    68.4µs ± 4%     ~     (p=0.286 n=9+9)
HashMapAcyclic-6     115µs ± 5%     115µs ± 4%     ~     (p=1.000 n=10+10)
name              old alloc/op   new alloc/op   delta
Hash-6              2.29kB ± 0%    1.88kB ± 0%  -18.13%  (p=0.000 n=10+10)
HashMapAcyclic-6    2.53kB ± 0%    2.53kB ± 0%     ~     (all equal)
name              old allocs/op  new allocs/op  delta
Hash-6                58.0 ± 0%      54.0 ± 0%   -6.90%  (p=0.000 n=10+10)
HashMapAcyclic-6       202 ± 0%       202 ± 0%     ~     (all equal)
```

util/deephash: export a Hash func for use by the control plane

---

ipn/ipnlocal/local.go

ipnlocal: move log line inside if statement

---

tstest/integration/vms/vms_test.go

This makes sure `tailscale status` and `tailscale ping` works. It also
switches goexpect to use a batch instead of manually banging out each
line, which makes the tests so much easier to read.

tstest/integration/vms: make first end to end test

---

util/deephash/deephash.go
util/deephash/deephash_test.go

util/deephash: prevent infinite loop on map cycle

---

util/deephash/deephash.go
util/deephash/deephash_test.go

```
Hash-6               173µs ± 4%     101µs ± 3%   -41.69%  (p=0.000 n=10+9)
HashMapAcyclic-6     101µs ± 5%     105µs ± 3%    +3.52%  (p=0.001 n=9+10)
TailcfgNode-6       29.4µs ± 2%    16.4µs ± 3%   -44.25%  (p=0.000 n=8+10)
name              old alloc/op   new alloc/op   delta
Hash-6              3.60kB ± 0%    1.13kB ± 0%   -68.70%  (p=0.000 n=10+10)
HashMapAcyclic-6    2.53kB ± 0%    2.53kB ± 0%      ~     (p=0.137 n=10+8)
TailcfgNode-6         528B ± 0%        0B       -100.00%  (p=0.000 n=10+10)
name              old allocs/op  new allocs/op  delta
Hash-6                84.0 ± 0%      40.0 ± 0%   -52.38%  (p=0.000 n=10+10)
HashMapAcyclic-6       202 ± 0%       202 ± 0%      ~     (all equal)
TailcfgNode-6         11.0 ± 0% …
```

util/deephash: optimize hashing of byte arrays, reduce allocs in Hash

---

net/tstun/wrap.go

To remove some multi-case selects, we intentionally allowed
sends on closed channels (cc23049cd286f137536d011b7840b3be5fdc8cb4).
However, we also introduced concurrent sends and closes,
which is a data race.
This commit fixes the data race. The mutexes here are uncontended,
and thus very cheap.

net/tstun: fix data races

---

net/uring/io_uring_linux.go
util/endian/big.go
util/endian/encoding_test.go
util/endian/little.go

Instead of calling out to C for ntohs, just implement it in Go for effiency.

net/uring: add go ntohs

---

.github/workflows/xe-experimental-vm-test.yml

Hopefully this will catch situations like
https://github.com/tailscale/tailscale/pull/2372

Run tests on integration test changes

---

tstest/integration/integration_test.go

Signed-off-by: Simeng He <simeng@tailscale.com>
The IP addresses returned from `AwaitIP` had newlines in them.

tstest/integration: change return type of AwaitIP from string to netaddr.IP

---

tstest/integration/vms/test.log
tstest/integration/vms/udp_tester.go
tstest/integration/vms/vms_test.go

Reverts tailscale/tailscale#2364
TODO(Xe): Fix this tomorrow

Revert "Revert "tstest/integration/vms: end-to-end UDP test""

---

derp/derp_server.go

derp: use a dedicated queue for disco traffic.

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go

This PR is designed to precede PR #2391 and provide a place to write a test for it.

cmd/tailscale/cli: factor out more up code for testing

---

derp/derp_server.go

It was once believed that it might be useful. It wasn't. We never used it.
Remove it so we don't slowly leak memorya

derp: remove "fine for now" intentional slow memory leak from derp server

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go
ipn/handle.go
ipn/prefs.go

This one doesn't bother me so much, as long term we want a synonym here.
Fixes #2384
Fixes #2386

ipn: another controlplane synonym

---

cmd/derper/derpprobe/derpprobe.go
derp/derp_client.go
derp/derphttp/derphttp_client.go

cmd/derper/derpprobe: add derp prober

---

derp/derp_server.go

derp: allow self node when verifying clients

---

tstest/integration/vms/vms_test.go

This test used to try to run this only once, but this variant of the
test attempts to run `tailscale status` up to 6 times in a loop with
exponential backoff.
This fixes the flakiness found in previous instances of this test.

tstest/integration/vms: deflake the tailscale_status test

---

tstest/integration/vms/vms_test.go

Apparently this test was flaking because I critically misunderstood how
the kernel buffers UDP packets for senders. I'm trying to send more UDP
packets and will see if that helps.

tstest/integration/vms: attempt to send more UDP packets

---

ipn/ipnlocal/local.go
ipn/ipnlocal/state_test.go
tstest/integration/integration.go
tstest/integration/integration_test.go
tstest/integration/testcontrol/testcontrol.go

ipn/ipnlocal: stay out of map poll when down

---

util/deephash/deephash.go

Seed the hash upon first use with the current time.
This ensures that the stability of the hash is bounded within
the lifetime of one program execution.
Hopefully, this prevents future bugs where someone assumes that
this hash is stable.

util/deephash: introduce deliberate instability

---

net/portmapper/upnp.go

Previously, this was incorrectly returning the internal port, and using that with the external
exposed IP when it did not use WANIPConnection2. In the case when we must provide a port, we
return it instead.
Noticed this while implementing the integration test for upnp.

net/portmapper: return correct upnp port

---

util/deephash/deephash.go
util/deephash/deephash_test.go

A Go interface may hold any number of different concrete types.
Just because two underlying value hashes to the same thing
does not mean two values are identical if they have different
concrete types. As such, include the type in the hash.

util/deephash: include type as part of hash for interfaces

---

wgengine/netstack/netstack.go

TCP was done in 662fbd4a09664e849f0b898d1e8df13325d36efa.
This does the same for UDP.
Tested by hand. Integration tests will have to come later. I'd wanted
to do it in this commit, but the SOCKS5 server needed for interop
testing between two userspace nodes doesn't yet support UDP and I
didn't want to invent some whole new userspace packet injection
interface at this point, as SOCKS seems like a better route, but
that's its own bug.
Fixes #2302
RELNOTE=netstack mode can now UDP relay to subnets

wgengine/netstack: implement UDP relaying to advertised subnets

---

net/dns/resolver/forwarder.go

net/dns/resolver: bound DoH usage on iOS

---

wgengine/userspace.go

Updates #2458 (maybe fixes it)

wgengine: re-set DNS config on Linux after a major link change

---

ipn/ipnlocal/local.go

ipn/ipnlocal: populate Hostinfo.Package on Android

---

derp/derphttp/derphttp_client.go
net/dnscache/dnscache.go

Not yet used in the dialer, but plumbed around.

net/dnscache: cache all IPs per hostname

---

.github/workflows/xe-experimental-vm-test.yml

This experiment apparently failed.

disable vm tests on every commit to main

---

Dockerfile

Well, it will save at least one step/layer

refactor: remove extra COPY steps in Dockerfile

---

cmd/derper/mesh.go
derp/derphttp/derphttp_client.go

cmd/derper: mesh over VPC network

---

util/deephash/deephash.go

The swapping of bufio.Writer between hasher and mapHasher is subtle.
Just embed a hasher in mapHasher to avoid complexity here.
No notable change in performance:
Hash-8              76.7µs ± 1%    77.0µs ± 1%    ~            (p=0.182 n=9+10)
HashMapAcyclic-8    62.4µs ± 1%    62.5µs ± 1%    ~            (p=0.315 n=10+9)
TailcfgNode-8       10.3µs ± 1%    10.3µs ± 1%  -0.62%         (p=0.004 n=10+9)
HashArray-8         1.07µs ± 1%    1.06µs ± 1%  -0.98%          (p=0.001 n=8+9)

util/deephash: simplify hasher.hashMap

---

util/deephash/deephash.go
util/deephash/deephash_test.go

Instead of hashing the humanly formatted forms of a number,
hash the native machine bits of the integers themselves.
There is a small performance gain for this:
Hash-8              75.7µs ± 1%    76.0µs ± 2%    ~            (p=0.315 n=10+9)
HashMapAcyclic-8    63.1µs ± 3%    61.3µs ± 1%  -2.77%        (p=0.000 n=10+10)
TailcfgNode-8       10.3µs ± 1%    10.2µs ± 1%  -1.48%        (p=0.000 n=10+10)
HashArray-8         1.07µs ± 1%    1.05µs ± 1%  -1.79%        (p=0.000 n=10+10)

util/deephash: hash uint{8,16,32,64} explicitly

---

logpolicy/logpolicy.go

Given that https://github.com/golang/go/issues/42888 is coming, this
catches most practical panics without interfering in our development
environments.

logpolicy: only log panics when running under systemd

---

hostinfo/hostinfo.go

hostinfo: add fly.io detection

---

net/portmapper/igd_test.go
net/portmapper/pcp.go
net/portmapper/portmapper.go
net/portmapper/portmapper_test.go

And work around GitHub Actions localhost UDP firewalls. Empirically,
localhost UDP (at least on certain ports) doesn't work on GitHub
actions. So use 0.0.0.0 there instead, as discovered by Julian.
Co-Author: @JulianKnodt

net/portmapper: actually test something in TestProbeIntegration

---

net/portmapper/igd_test.go
net/portmapper/pcp_test.go
net/portmapper/portmapper_test.go

This adds a PCP test to the IGD test server, by hardcoding in a few observed packets from
Denton's box.
Signed-off-by: julianknodt <julianknodt@gmail.com>

net/portmapper: add PCP tests

---

tsweb/tsweb.go
tsweb/tsweb_test.go

To be used by control, per linked bug's plan.
Updates #2635

tsweb: make VarzHandler capable of walking structs with reflect

---

words/scales.txt
words/tails.txt

Updates #1235
Signed-off-by: Charlotte Brandhorst-Satzkorn <charlotte@catzkorn.dev>

words: these are a few more of my favorite words

---

cmd/tailscaled/tailscaled.go

tailscaled: try migrating old state on synology devices

---

net/tstun/tun_linux.go

net/tstun: fix build on arm

---

wgengine/userspace.go

The number of peers we have will be pretty stable across time.
Allocate roughly the right slice size.
This reduces memory usage when there are many peers.

wgengine: predict min.Peers length across calls

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: restore a bit of logging on node becoming active

---

api.md
control/controlclient/direct.go
derp/derp_server.go
net/dns/resolver/tsdns.go
net/flowtrack/flowtrack.go
net/netcheck/netcheck.go
safesocket/unixsocket.go
tstest/natlab/natlab.go
tsweb/tsweb.go
util/deephash/deephash.go
util/groupmember/groupmember.go
wgengine/magicsock/magicsock.go

fix typo spelling grammar, and replace to corrects word
more readable code comments
related pr fixing #2701

fix: typo spelling grammar

---

tstest/integration/integration.go

By default httptest listens only on the loopback adapter.
Instead, listen on the IP the user asked for.
The VM test needs this, as it wants to start DERP and STUN
servers on the host that can be reached by guest VMs.

tstest/integration: listen on the specified IP

---

wgengine/userspace.go

wgengine: fix link monitor / magicsock Start race

---

tstest/integration/integration.go

The VM test has two tailscaled instances running and interleaves the
logs. Without a prefix it is impossible to figure out what is going on.
It might be even better to include the [ABCD] node prefix here as well.
Unfortunately lots of interesting logs happen before tailscaled has a
node key, so it wouldn't be a replacement for a short ID.

tstest/integration: prefix logs with logid

---

tstime/rate/rate_test.go

This test is highly dependent on the accuracy of OS timers.
Reduce the number of failures by decreasing the required
accuracy from 0.999 to 0.995.
Also, switch from repeated time.Sleep to using a time.Ticker
for improved accuracy.
Updates #2727

tstime/rate: deflake TestLongRunningQPS

---

util/deephash/deephash_test.go

Unfortunately this test fails on certain architectures.
The problem comes down to inconsistencies in the Go escape analysis
where specific variables are marked as escaping on certain architectures.
The variables escaping to the heap are unfortunately in crypto/sha256,
which makes it impossible to fixthis locally in deephash.
For now, fix the test by compensating for the allocations that
occur from calling sha256.digest.Sum.
See golang/go#48055
Fixes #2727

util/deephash: fix TestArrayAllocs

---

cmd/derper/derper.go

cmd/derper: add missing read/write timeouts

---

derp/derp.go
derp/derp_client.go
derp/derp_test.go

derp: add new health update and server restarting frame types

---

cmd/derper/derper.go

Didn't notice this one in earlier 00b3c1c0422d033a479a2efedbbd239c05dab68c
Updates tailscale/corp#2486

cmd/derper: also add port 80 timeouts

---

cmd/tailscale/cli/up.go

At "Starting", the DERP connection isn't yet up. After the first netmap
and DERP connect, then it transitions into "Running".
Fixes #2708

cmd/tailscale/cli: make up block until state Running, not just Starting

---

cmd/derper/derper.go

cmd/derper: listen on host of flag server addr for port 80 and 3478

---

go.mod

go.mod: tidy.

---

ipn/ipnlocal/local.go

In prep for other bug fixes & tests. It's hard to test when it was
intermingled into LocalBackend.authReconfig.
Now it's a pure function.
And rename variable 'uc' (user config?) to the since idiomatic
'prefs'.

ipn/ipnlocal: pull out dns.Config construction to its own func

---

ipn/ipnlocal/dnsconfig_test.go
tstest/log.go
wgengine/router/router_linux_test.go
wgengine/userspace_test.go
wgengine/watchdog_test.go

ipn/ipnlocal: start adding some netmap to DNS config tests

---

ipn/ipnlocal/dnsconfig_test.go
ipn/ipnlocal/local.go
net/tsaddr/tsaddr.go

ipn/ipnlocal: add MagicDNS records for IPv6-only nodes

---

ipn/ipnlocal/dnsconfig_test.go
ipn/ipnlocal/local.go

ipn/ipnlocal: flesh out the dnsConfigForNetmap tests

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: fix crash introduced in recent cleanups

---

api.md

api: document new API to authorize a device

---

cmd/tailscaled/tailscaled.go
net/netns/netns.go
tstest/integration/tailscaled_deps_test_darwin.go
tstest/integration/tailscaled_deps_test_freebsd.go
tstest/integration/tailscaled_deps_test_linux.go
tstest/integration/tailscaled_deps_test_openbsd.go
tstest/integration/tailscaled_deps_test_windows.go

cmd/tailscaled: disable netns in userspace-networking mode

---

portlist/portlist_linux.go
portlist/portlist_linux_test.go

Notably, it no longer allocates proportional to the number of open
sockets on the machine. Any alloc reduction numbers are a little
contrived with such a reduction but e.g. on a machine with 50,000
connections open:
```
name          old time/op    new time/op    delta
ParsePorts-6    57.7ms ± 6%    32.8ms ± 3%   -43.04%  (p=0.000 n=9+10)
name          old alloc/op   new alloc/op   delta
ParsePorts-6    24.0MB ± 0%     0.0MB ± 0%  -100.00%  (p=0.000 n=10+9)
name          old allocs/op  new allocs/op  delta
ParsePorts-6      100k ± 0%        0k ± 0%   -99.99%  (p=0.000 n=10+10)
```
Updates tailscale/corp#2566

portlist: reduce allocs on Linux

---

portlist/portlist_linux.go
portlist/portlist_linux_test.go

Avoid splitting fields in the common case. Field splitting was 84% of
the overall CPU.
```
name          old time/op    new time/op    delta
ParsePorts-6    33.3ms ± 2%     6.3ms ± 4%  -80.97%  (p=0.000 n=9+10)
name          old alloc/op   new alloc/op   delta
ParsePorts-6      520B ±79%      408B ± 0%  -21.49%  (p=0.046 n=10+8)
name          old allocs/op  new allocs/op  delta
ParsePorts-6      7.00 ± 0%      7.00 ± 0%     ~     (all equal)
```
Updates tailscale/corp#2566

portlist: reduce CPU parsing portlist

---

portlist/portlist_linux.go

```
name          old time/op    new time/op    delta
ParsePorts-6    6.41ms ± 7%    3.15ms ± 2%  -50.84%  (p=0.000 n=9+9)
name          old alloc/op   new alloc/op   delta
ParsePorts-6      408B ± 0%      216B ± 0%  -47.06%  (p=0.002 n=8+10)
name          old allocs/op  new allocs/op  delta
ParsePorts-6      7.00 ± 0%      4.00 ± 0%  -42.86%  (p=0.000 n=10+10)
```
Updates tailscale/corp#2566

portlist: cache field index position between runs, cut two more allocs (Linux)

---

disco/disco.go
net/tstun/wrap.go
net/tstun/wrap_test.go
wgengine/userspace.go

Updates #1526 (maybe fixes? time will tell)

net/tstun: block looped disco traffic

---

tailcfg/tailcfg.go
tailcfg/tailcfg_test.go

(Discovered while writing a test elsewhere)

tailcfg: don't panic on clone of nil RegisterRequest

---

client/tailscale/tailscale.go

cmd/tailscale: provide a better error message when tailscaled isn't running

---

derp/derp_client.go
derp/derp_server.go
derp/derp_test.go

derp: throttle client sends if server advertises rate limits

derp: throttle client sends if server advertises rate limits

---

control/controlclient/sign.go
control/controlclient/sign_supported.go
tailcfg/tailcfg.go

This iterates on the original signature format.

control/controlclient: update machine certificate signature version

---

.github/dependabot.yml
net/dnsfallback/dns-fallback-servers.json

.github: add dependabot config to update go.mod and github actions.

---

cmd/tailscale/cli/web.go

pfSense stores its SSL certificate and key in the PHP config.
We wrote PHP code to pull the two out of the PHP config and
into environment variables before running "tailscale web".
The pfSense web UI is served over https, we need "tailscale web"
to also support https in order to put it in an <iframe>.

cmd/tailscale/web: support TLS from env vars.

---

ipn/store_test.go

ipn: test TestFileStore in a fresh subdirectory

---

paths/paths_unix.go

paths: skip unix chmod if state directory is already 0700

---

cmd/tailscale/cli/up.go

cmd/tailscale: let up --authkey be of form file:/path/to/secret

---

types/opt/bool.go

types/opt: implement Bool.Scan

---

hostinfo/hostinfo_linux.go

hostinfo: look up Synology hardware a more specific way

---

cmd/tailscale/cli/up.go
cmd/tailscale/cli/web.css
cmd/tailscale/cli/web.go
cmd/tailscale/cli/web.html

A couple of gnarly assumptions in this code, as always with the async
message thing.
UI button is based on the DNS settings in the admin panel.

cli: web advertise exit node button

---

cmd/tailscaled/tailscaled_windows.go

This feature wasn't working until I realized that we also need to opt into
the events. MSDN wasn't so generous as to make this easy to deduce.
Updates #2956

cmd/tailscaled: set the correct flag for receiving session change events

---

logtail/filch/filch.go
logtail/filch/filch_test.go

If for some reason there is no network connectivity, the log files keep growing.  This attempts to limit the max size we consume to 50MB per file.

logtail/filch: limit buffer file size to 50MB

---

scripts/installer.sh

scripts/installer: handle fedora

---

.github/workflows/linux.yml
tstest/archtest/archtest_test.go
tstest/archtest/qemu_test.go

tstest/archtest: add GOARCH-specific tests, run via qemu-user

---

cmd/tailscaled/tailscaled.go
cmd/tailscaled/tailscaled_windows.go
tsnet/tsnet.go
wgengine/netstack/netstack.go

Even if not in use. We plan to use it for more stuff later.

cmd/tailscaled, wgengine/netstack: always wire up netstack

---

ipn/ipnlocal/peerapi.go

For debugging Synology. Like the existing goroutines handler, in that
it's owner-only.

ipn/ipnlocal: add owner-only debug handler to get process env

---

cmd/tailscaled/tailscaled.go
ipn/ipnlocal/local.go
ipn/ipnserver/server.go

cmd/tailscaled, ipn: add tailscaled --statedir flag for var directory

---

tstest/integration/integration_test.go
tstest/integration/testcontrol/testcontrol.go

tstest: extend node key expiration integration test.

---

tsnet/tsnet.go

This makes tsnet work on https://gokrazy.org! 🎉

tsnet: set varRoot state directory field

---

ipn/ipnlocal/local.go
ipn/ipnlocal/state_test.go
tstest/integration/integration_test.go

ipn/ipnlocal: handle key extensions after key has already expired

---

control/controlclient/direct.go
hostinfo/hostinfo.go
hostinfo/hostinfo_test.go

hostinfo, control/controlclient: tell control when Ubuntu has disabled Tailscale's sources

---

cmd/tailscale/cli/debug.go

It was a mess of flags. Use subcommands under "debug" instead.
And document loudly that it's not a stable interface.

cmd/tailscale/cli: migrate hidden debug subcommand to use subcomands

---

net/dns/resolved.go

Don't set all the *.arpa. reverse DNS lookup domains if systemd-resolved
is old and can't handle them.
Fixes #3188

net/dns: work around old systemd-resolved setLinkDomain length limit

---

cmd/tailscale/cli/debug.go

This adds a new --watch flag that prints out a block of metric changes
every second, if anything changed.
Example output:
```
magicsock_disco_recv_ping    +1 => 254
magicsock_disco_recv_pong    +1 => 218
magicsock_disco_recv_udp     +2 => 472
magicsock_disco_send_udp     +2 => 536
magicsock_disco_sent_udp     +2 => 536
magicsock_recv_data_ipv6     +1 => 82
magicsock_send_data          +1 => 86
magicsock_send_udp           +3 => 620
magicsock_recv_data_ipv6    +1 => 83
magicsock_send_data         +1 => 87
magicsock_send_udp          +1 => 621
magicsock_disco_recv_ping    +1 => 255
magicsock_disco_recv_pong    +1 => 219
magicsock_disco_recv_udp     +2 => 474
magicsock_disco_send_udp     +2 => 538
magicsock_disco_sent_udp     +2 => 538
magicsock_recv_data_ipv6     +1 => 84 …
```

cmd/tailscale/cli: add --watch flag to "debug metrics" subcommand

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

- wgengine/magicsock: fix typo in comment
- wgengine/magicsock: fix bug in peerMap.upsertEndpoint
- wgengine/magicsock: simplify peerMap.upsertEndpoint

wgengine/magicsock: improve/fix peermap.upsertEndpoint

---

util/clientmetric/clientmetric.go

util/clientmetric: optimize memory layout for finding updates

---

net/tstun/wrap.go
wgengine/userspace.go

Primarily tstun work, but some MagicDNS stuff spread into wgengine.
No wireguard reconfig metrics (yet).
Updates #3307

net/tstun, wgengine: add packet-level and drop metrics

---

wgengine/magicsock/magicsock.go

endpoint.discoKey is protected by endpoint.mu.
endpoint.sendDiscoMessage was reading it without holding the lock.
This showed up in a CI failure and is readily reproducible locally.
The fix is in two parts.
First, for Conn.enqueueCallMeMaybe, eliminate the one-line helper method endpoint.sendDiscoMessage; call Conn.sendDiscoMessage directly.
This makes it more natural to read endpoint.discoKey in a context
in which endpoint.mu is already held.
Second, for endpoint.sendDiscoPing, explicitly pass the disco key
as an argument. Again, this makes it easier to read endpoint.discoKey
in a context in which endpoint.mu is already held.

wgengine/magicsock: fix data race on endpoint.discoKey

---

ipn/ipnlocal/peerapi.go

ipn/ipnlocal: export client metrics over peerapi to owner

---

wgengine/monitor/monitor_windows.go

wgengine/monitor: reduce Windows log spam

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: remove some log spam

---

control/controlclient/direct.go
derp/derphttp/derphttp_client.go
logpolicy/logpolicy.go
net/dns/resolver/forwarder.go
net/dnsfallback/dnsfallback.go
net/netcheck/netcheck.go
net/netns/netns.go
net/netns/netns_android.go
net/netns/netns_darwin_tailscaled.go
net/netns/netns_default.go
net/netns/netns_linux.go
net/netns/netns_test.go
net/netns/netns_windows.go
net/portmapper/portmapper.go
net/portmapper/upnp.go
wgengine/magicsock/magicsock.go

So that darwin can log there without panicking during tests.

net/netns: thread logf into control functions

---

cmd/tailscaled/tailscaled.go

cmd/tailscaled: disambiguate some startup failure error messages

---

wgengine/router/router_linux.go
wgengine/userspace.go

wgengine{,/router}: annotate some more errors

---

health/health.go
net/dns/manager.go
net/dns/resolved.go

Fixes #3327
I suggest a commit-by-commit review.

net/dns: reprogram systemd-resolved when it restarts.

---

wgengine/router/router_linux.go

wgengine/router: don't assume Linux was built with IP_MULTIPLE_TABLES

---

net/portmapper/portmapper.go

There are lots of lines in the logs of the form:
portmapper: unexpected PMP probe response: {OpCode:128 ResultCode:3
SecondsSinceEpoch:NNN MappingValidSeconds:0 InternalPort:0
ExternalPort:0 PublicAddr:0.0.0.0}
ResultCode 3 here means a network failure, e.g. the NAT box itself has
not obtained a DHCP lease. This is not an indication that something
is wrong in the Tailscale client, so change the wording here
to reflect that.

net/portmapper: PMP probe failures are not unexpected

---

hostinfo/hostinfo.go

hostinfo: report when running in Docker Desktop.

---

ipn/ipnstate/ipnstate.go

And document the other fields, as long as we're here.
Updates #1182

ipn/ipnstate: clarify PeerStatusLite.LastHandshake

---

cmd/tailscaled/tailscaled.go
ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go
net/dns/manager.go
wgengine/userspace.go
wgengine/watchdog.go

ipn/ipnlocal: start adding DoH DNS server to peerapi when exit node

---

cmd/tailscale/cli/ip.go

- cmd/tailscale: improve ip subcommand docs
- cmd/tailscale: add ip -1 flag

cmd/tailscale: add ip -1 flag

---

scripts/installer.sh

Updates https://github.com/tailscale/tailscale/issues/2915

scripts/installer.sh: add more Linux variants.

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Remove "what is the FR" as that's the same content as the title basically

.github: feature request template change

---

ipn/ipnlocal/peerapi.go
net/dns/resolver/forwarder.go
net/dns/resolver/tsdns.go

net/dns/resolver, ipn/ipnlocal: wire up peerapi DoH server to DNS forwarder

---

logpolicy/logpolicy.go

Android doesn't use logpolicy and currently has enough
unique stuff about its logging that makes it difficult to
do so. For example, its logsDir comes from Gio.
Export NewLogtailTransport to let Android use it.
Updates https://github.com/tailscale/tailscale/issues/3046

logpolicy: export NewLogtailTransport for Android

---

ipn/ipnlocal/local.go
wgengine/magicsock/magicsock.go

ipn/ipnlocal: populate self status from netmap in ipnlocal, not magicsock.

---

cmd/derper/derper.go

It's a basic "deny everything" policy, since DERP's HTTP
server is very uninteresting from a browser POV. But it
stops every security scanner under the sun from reporting
"dangerously configured" HTTP servers.
Updates tailscale/corp#3119

cmd/derper: set Content-Security-Policy on DERPs.

---

net/dns/resolver/forwarder.go
net/dns/resolver/tsdns.go

net/dns/resolver: add clientmetrics for DNS

---

cmd/tailscaled/tailscaled.go
ipn/store/aws/store_aws.go

Support sub-paths in SSM state store

---

ipn/ipnlocal/dnsconfig_test.go
ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go
net/dns/resolver/forwarder.go
net/dns/resolver/tsdns.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go

tailcfg, ipn/ipnlocal, net/dns: forward exit node DNS on Unix to system DNS

---

ipn/ipnlocal/local.go
tailcfg/tailcfg.go

tailcfg, ipn/ipnlocal: advertise a Service when exit node DNS proxy available

---

tstest/integration/integration.go

tstest/integration: stop leaking zstd.Decoders

---

types/logger/logger.go
types/logger/logger_test.go

We often need both a log function and a context.
We can do this by adding the log function as a context value.
This commit adds helper glue to make that easy.
It is designed to allow incremental adoption.
Updates tailscale/corp#3138

types/logger: add Context and related helpers

---

cmd/tailscale/cli/status.go
ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go

cmd/tailscale, ipn/ipnstate: note which nodes are exit nodes in status

---

ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go
net/dns/resolver/forwarder.go

ipn/ipnlocal, net/dns/resolver: use exit node's DoH proxy when available

---

net/tsdial/tsdial.go

With this, I'm able to send a Taildrop file (using "tailscale file cp")
from a Linux machine running --tun=userspace-networking.
Updates #2179

net/tsdial: make dialing to peerapi work in netstack mode

---

tstest/integration/integration_test.go

tstest/integration: use t.Cleanup

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go

If you're online, let tailscale up --exit-node=NAME map NAME to its IP.
We don't store the exit node name server-side in prefs, avoiding
the concern raised earlier.
Fixes #3062

cmd/tailscale: let --exit-node= take a machine name in addition to IP

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go

cmd/tailscale: don't allow setting exit node to known invalid value

---

build_docker.sh

build_docker.sh: prefix version tags with `v`

---

.gitattributes

.: add .gitattributes entry to use Go hunk-header driver

---

Makefile

(using the new https://github.com/tailscale/tailscale-synology/pull/94)

Makefile: add spk and pushspk targets for iterative Synology development

---

cmd/tailscale/cli/up.go

Print JSON to stdout containing everything needed for
authentication.

cmd/tailscale: add --json for up

---

cmd/derper/derper.go

Following on https://github.com/tailscale/tailscale/pull/3231
This PR aims to allow the configuration of the unsecure HTTP port, which serves both the debug/profiling and acme challenges if enabled.
I added 1 new CLI flags:
- `--http-port`
Fixes #3232

cmd/derper: allow unsecure port configuration

---

cmd/tailscale/cli/status.go
ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go

ipn/ipnstate, cmd/tailscale: add Online bool to tailscale status & --json

---

net/dns/direct.go

net/dns: bound how long we block looking for, restarting systemd-resolved

---

ipn/ipnlocal/local.go
net/dns/resolver/tsdns.go
net/dns/resolver/tsdns_server_test.go
net/dns/resolver/tsdns_test.go

net/dns/resolver: add Windows ExitDNS service support, using net package

---

scripts/installer.sh

scripts/installer.sh: press Y on RHEL

---

scripts/installer.sh

After apt install, Kali Linux had not enabled nor started
the tailscaled systemd service. Add a quirks mode to enable
and start it after apt install for debian platforms.

install.sh: add linuxmint, kali, several more.

---

README.md

Update platform support. This matches content in https://tailscale.com/kb/1062/reviewer-guide/#which-platforms-does-it-run-on

README.md: update platforms

---

ipn/ipnlocal/state_test.go

I'm sick of this flaking. Even if this isn't the right fix, it
stops the alert fatigue.
Updates #3020

ipn/ipnlocal: deflake (mostly) TestStateMachine

---

tstest/integration/integration_test.go

testNodes have a reference to a testing.TB via their env.
Use it instead of making the caller pass theirs.
We did this in some methods but not others; finish the job.
This simplifies the call sites.

tstest/integration: remove t param in testNode methods

---

ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go

Make shrinkDefaultRoute a pure function.
Instead of calling interfaceRoutes, accept that information as parameters.
Hard-code those parameters in TestShrinkDefaultRoute.
Fixes #3580

ipn/ipnlocal: make TestShrinkDefaultRoute hermetic

---

cmd/tailscaled/tailscaled_windows.go

cmd/tailscaled: log Windows service change requests

---

api.md

The new /keys endpoint allows you to list API and machine auth keys.
You can also create machine auth key.
It currently does not support creating another API key.

api: document API endpoint to manipulate keys

---

wgengine/netstack/netstack.go

wgengine/netstack: don't remove 255.255.255.255/32 from netstack

---

net/dns/resolver/forwarder.go

Don't just ignore them. See if this makes them calm down.
Updates #3363

net/dns/resolver: send NXDOMAIN to iOS DNS-SD/Bonjour queries

---

net/dns/resolver/tsdns.go

net/dns/resolver: add metrics to PTR lookup misses

---

cmd/tailscaled/tailscaled.go
ipn/ipnlocal/peerapi.go
wgengine/magicsock/debughttp.go

A start.
Billion things more to do.
Not sure whether you want this in as-is or you want me to add the billion other things first.

wgengine/magicsock: add HTML debug handler to see magicsock state

---

health/health.go
ipn/ipnlocal/peerapi.go
net/dns/resolver/debug.go
net/dns/resolver/forwarder.go

net/dns/resolver: add debug HTML handler to see what DNS traffic was forwarded

---

derp/derphttp/derphttp_client.go
derp/derphttp/derphttp_test.go

Continuing work in 434af15a043, to make it possible for magicsock to
probe whether a DERP server is still there.
Updates #3619

derp/derphttp: add Client.Ping, SendPing methods

---

tsnet/tsnet.go

tsnet: add Dial method to allow dialing out to the tailnet.

---

ipn/ipnlocal/local.go
ipn/localapi/localapi.go

And more later probably.
Updates #3619

ipn/localapi: add debug handler to Rebind, ReSTUN magicsock

---

build_docker.sh

build_docker.sh: add env overrides

---

tsnet/tsnet.go

tsnet: add Start method to allow connecting to the tailnet without requiring a call to Dial/Listen

---

derp/derp_server.go

derp: add metrics to server got pings, sent pongs

---

wgengine/magicsock/magicsock.go

Bigger changes coming later, but this should improve things a bit in
the meantime.
Updates #3363

wgengine/magicsock: reduce disco ping heartbeat aggressiveness a bit

---

cmd/printdep/printdep.go

cmd/printdep: add flag to print out Go toolchain tarball URL

---

wgengine/netstack/netstack.go

Except for the super verbose packet-level dumps. Keep those disabled
by default with a const.
Updates #2642

wgengine/netstack: add env knob to turn on netstack debug logs

---

Dockerfile.base

Dockerfile.base: update to alpine:3.15

---

ipn/ipnserver/server.go

ipn/ipnserver: provide means of setting debug env vars on Windows

---

.github/workflows/vm.yml

The rest of our workflows use v2.1.4.

.github/workflows: upgrade to setup-go@v2

---

scripts/installer.sh

Fixes #3685
Fixes #3528
Fixes #3649

scripts: install gnupg deb, pass --yes to apt-get

---

net/dns/resolver/tsdns.go

On Synology, the /etc/resolv.conf has tabs in it, which this
resolv.conf parser (we have two, sigh) didn't handle.
Updates #3710

net/dns/resolver: handle tabs as whitespace when ExitDNS parses resolv.conf

---

scripts/installer.sh

scripts/installer.sh: add support to use the unstable track.

---

wgengine/netstack/netstack.go
wgengine/netstack/netstack_linux.go

wgengine/netstack: make userspace ping work when tailscaled has CAP_NET_RAW

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: fix lock ordering deadlock with derphttp

---

wgengine/netstack/netstack.go

-W is milliseconds on darwin, not seconds, and empirically it's
milliseconds after a 1 second base.

wgengine/netstack: fix netstack ping timeout on darwin

---

wgengine/netstack/netstack.go

wgengine/netstack: add missing error logging in a RST case

---

wgengine/netstack/netstack.go
wgengine/netstack/netstack_test.go

Fixes #3762
Updates #3745 (probably fixes?)

wgengine/netstack: add a missing refcount decrement after packet injection

---

wgengine/magicsock/magicsock.go

This fixes a deadlock on shutdown.
One goroutine is waiting to send on c.derpRecvCh before unlocking c.mu.
The other goroutine is waiting to lock c.mu before receiving from c.derpRecvCh.
#3736 has a more detailed explanation of the sequence of events.
Fixes #3736

wgengine/magicsock: fix deadlock on shutdown

---

net/dns/resolvd.go

Currently only search domains are stored. This was an oversight
(under?) on my part.
As things are now, when MagicDNS is on and "Override local DNS" is
off, the dns forwarder has to timeout before names resolve. This
introduces a pretty annoying lang that makes everything feel
extremely slow. You will also see an error: "upstream nameservers
not set".
I tested with "Override local DNS" on and off. In both situations
things seem to function as expected (and quickly).
Signed-off-by: Aaron Bieber <aaron@bolddaemon.com>

net/dns/resolvd: store nameservers

---

.gitignore
Makefile

Makefile: update `make spk` target to use the new go spk builder

---

cmd/derper/derper.go

Surveying the fleet prior to turning off old/unused/insecure
TLS versions.
Updates tailscale/corp#3615

cmd/derper: record TLS versions used for requests.

---

net/dns/manager_linux.go
net/dns/manager_linux_test.go

net/dns: log why resolved does not look like it's on use [Linux]

---

scripts/installer.sh

Blocked on package server support being deployed

scripts/installer: add Centos Stream 9 support

---

ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go
types/netmap/netmap.go

`RELNOTE=tailscale status --json | jq .TailnetName`
Fixes tailscale/corp#3665

ipn/ipnstate: add TailnetName to status

---

cmd/derpprobe/derpprobe.go
derp/derphttp/derphttp_client.go

cmd/derpprobe: check derper TLS certs too

---

.github/workflows/cross-darwin.yml

.github/workflows: add some iOS CI coverage

---

cmd/derper/derper.go

cmd/derper: disable TLS 1.0 and 1.1.

---

derp/derphttp/derphttp_client.go
wgengine/magicsock/magicsock.go

derp/derphttp, wgengine/magicsock: prefer IPv6 to DERPs when IPv6 works

---

logtail/id.go

These are for use in our internal systems.

logtail: add a few new methods to PublicID

---

ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go
wgengine/netstack/netstack.go

We're finding a bunch of host operating systems/firewalls interact poorly
with peerapi. We either get ICMP errors from the host or users need to run
commands to allow the peerapi port:
https://github.com/tailscale/tailscale/issues/3842#issuecomment-1025133727
... even though the peerapi should be an internal implementation detail.
Rather than fight the host OS & firewalls, this change handles the
server side of peerapi entirely in netstack (except on iOS), so it
never makes its way to the host OS where it might be messed with. Two
main downsides are:
1) netstack isn't as fast, but we don't really need speed for peerapi.
And actually, with fewer trips to/from the kernel, we might
actually make up for some of the netstack performance loss by
staying in userspace.
2) tcpdump / Wireshark etc …

ipn/ipnlocal, wgengine/netstack: use netstack for peerapi server

---

chirp/chirp.go
chirp/chirp_test.go

Also add tests to verify the parsing logic.
Fixes tailscale/corp#3639

chirp: handle multiline responses from BIRD

---

wgengine/netstack/ssh.go

wgengine/netstack: start supporting different SSH users

---

chirp/chirp.go

chirp: remove regex dependency

---

api.md

cc @maisem I also added docs for the tags endpoint.

api.md: add docs for device tags and keys endpoints

---

words/tails.txt

In honor of this post[1] inspiring me to remember that ferrets exist and
have tails.
[1]: https://tech.davidfield.co.uk/what-is-tailscale/

words: add ferret to tails.txt

---

scripts/installer.sh

install.sh failed on prompt in void. Tested with -y and installation finished.

add -y flag for xbps to allow installation on void

---

cmd/derper/bootstrap_dns.go
cmd/derper/bootstrap_dns_test.go

- cmd/derper: add BenchmarkHandleBootstrapDNS
- cmd/derper: optimize handleBootstrapDNS
- cmd/derper: stop setting content header in handleBootstrapDNS

cmd/derper: optimize bootstrap DNS serving

---

envknob/envknob.go
ipn/ipnlocal/local.go

envknob: track, log env knobs in use

---

logtail/logtail.go
logtail/logtail_test.go

For analysis of log spam.
Bandwidth is ~unchanged from had we not stripped the "[vN] " from
text; it just gets restructed intot he new "v":N, field.  I guess it
adds one byte.
Updates #1548

logtail: don't strip verbose level on upload

---

net/dnscache/dnscache.go

No behavior changes (intended, at least).
This is in prep for future changes to this package, which would get
too complicated in the current style.

net/dnscache: refactor from func-y closure-y state to types & methods

---

logtail/id.go

logtail: add MustParsePublicID

---

control/controlclient/map.go
tailcfg/tailcfg.go
types/netmap/netmap.go

tailcfg: add start of SSH policy to be sent from control plane to nodes

---

health/health.go
net/dns/manager_linux.go

Updates #3937 (need to write docs before closing)

net/dns: add health check for particular broken-ish Linux DNS config

---

control/controlclient/direct.go
tailcfg/tailcfg.go
tstest/integration/integration_test.go
tstest/integration/testcontrol/testcontrol.go

And log it when provided in map responses.
The test uses the date on which I joined Tailscale. :)

tailcfg: add MapResponse.ControlTime field

---

api.md

api: document preauthorized auth keys

---

ipn/ipnlocal/local.go
ipn/ipnlocal/ssh.go
ipn/ipnlocal/ssh_stub.go
ssh/tailssh/tailssh.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go

tailcfg, ipn/ipnlocal: add Hostinfo.SSH_HostKeys, send when SSH enabled

---

control/controlclient/direct.go
tstest/integration/integration.go
tstest/integration/integration_test.go

control/controlclient: use structured logging for MapResponse.ControlTime

---

types/logger/logger.go

types/logger: add more reserved top level field names

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go
tailcfg/tailcfg.go

ssh/tailssh: evaluate tailcfg.SSHPolicy on incoming connections

---

ssh/tailssh/tailssh.go

And also reject attempts to use other users.
Updates #3802

ssh/tailssh: get login shell when running as non-root

---

ipn/ipnserver/server.go

Don't make users map their system's "caddy" (or whatever) system user
to its userid. We can do that. Support either a uid or a username.
RELNOTE=TS_PERMIT_CERT_UID can contain a uid or username

ipn/ipnserver: let TS_PERMIT_CERT_UID contain a username too, not just uid

---

ipn/localapi/cert.go

ipn/localapi: treat ACME "invalid" state as terminal, log more

---

cmd/tailscale/cli/debug.go

(I used this to test my earlier NSIS vs MSI change.)

cmd/tailscale: add "tailscale debug hostinfo" subcommand

---

tsnet/tsnet.go

tsnet: fix typo in Ephemeral

---

cmd/tailscale/cli/configure-host.go

cmd/tailscale: make configure-host on Synology also add CAP_NET_RAW

---

ssh/tailssh/tailssh.go

ssh/tailssh: flesh out env, support non-pty commands

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

So it's not confused for a context.Context and we can add contexts
later and not look like we have two.
Updates #3802

ssh/tailssh: rename sshContext to sshConnInfo

---

ssh/tailssh/context.go
ssh/tailssh/tailssh.go

ssh/tailssh: break a method into half in prep for testing

---

ssh/tailssh/tailssh.go

ssh/tailssh: fix non-interactive commands as non-root user

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

ssh/tailssh: add start of real ssh tests

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

ssh/tailssh: add more SSH tests, blend in env from ssh session 

---

tstime/rate/rate_test.go

Previous de-flakings:
* 8cf1af8a0703c36256fc58e98ddb63b8907848f1 for #3733
* 30458c71c81a3d680aacecafa67fabc1c728c52d for #2727
Fixes #4044

tstime/rate: deflake TestLongRunningQPS even more

---

ssh/tailssh/tailssh_test.go

ssh/tailssh: skip flaky test on CI for now

---

types/views/views.go

types/views: add ContainsExitRoutes to IPPrefixSlice

---

tailcfg/tailcfg.go

tailcfg: add OverTLSPublicKeyResponse for the new response from /key

---

control/controlclient/direct.go
tstest/integration/testcontrol/testcontrol.go

From https://github.com/tailscale/tailscale/pull/4062#issuecomment-1060961980
Updates https://github.com/tailscale/tailscale/issues/3488

control/controlclient: start fetching the server noise key

---

wgengine/router/router_linux.go

This was just cleanup for an ancient version of Tailscale. Any such machines
have upgraded since then.

wgengine/router: delete legacy netfilter rule cleanup [Linux]

---

control/controlclient/direct.go
tailcfg/tailcfg.go

    control/controlclient: make SetDNS attempt to go over Noise first

---

cmd/derper/derper.go

And flesh out docs on the --http-port flag.

cmd/derper: add --stun-port flag

---

control/controlclient/auto.go
control/controlclient/direct.go
tstest/integration/testcontrol/testcontrol.go

Updates https://github.com/tailscale/tailscale/issues/3488

control/controlclient: make RegisterRequest go over Noise

---

control/controlclient/auto.go

This was causing a flake in another repo.

control/controlclient: call direct.Close after map requests are complete

---

ssh/tailssh/incubator.go

ssh/tailssh: use lu.Username not lu.Name.

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

ssh/tailssh: handle local port forwarding

---

control/controlclient/direct.go

control/controlclient: make MapRequests go over noise.

---

cmd/tailscale/cli/cli.go

Enable use of command line arguments with tailscale cli on gokrazy. Before this change using arguments like "up" would cause tailscale cli to be repeatedly restarted by gokrazy process supervisor.
We never want to have gokrazy restart tailscale cli, even if user would manually start the process.
Expected usage is that user creates files:
`flags/tailscale.com/cmd/tailscale/flags.txt`:
up
`flags/tailscale.com/cmd/tailscaled/flags.txt`:
--statedir=/perm/tailscaled/
--tun=userspace-networking
Then tailscale prints URL for user to log in with browser.
Alternatively it should be possible to use up with auth key to allow unattended gokrazy installs.
cc @bradfitz @stapelberg

Allow using tailscale cli with gokrazy

---

tailcfg/tailcfg.go

tailcfg: bump capVer for Noise

---

ipn/ipnlocal/local.go

ipn/ipnlocal: migrate all platforms to controlplane.tailscale.com

---

ssh/tailssh/incubator.go

ssh/tailssh: start login shell, fix arg passing, width/height mismatch

---

ssh/tailssh/tailssh.go

Maisem figured out the real problem but will take several commits
(e.g. tailscale/ssh#2) in different repos to get it fixed
properly. This is an interim hack.
Details of real fix:
https://github.com/tailscale/tailscale/issues/4146#issuecomment-1065952947
Updates #4146
Updates #3802

ssh/tailssh: fix terminal corruption (temporary hack)

---

ssh/tailssh/incubator.go
ssh/tailssh/incubator_linux.go
ssh/tailssh/tailssh.go

- ssh/tailssh: start sending the server version
- ssh/tailssh: set DBUS_SESSION_BUS_ADDRESS and SSH_TTY variables

ssh/tailssh: set DBUS_SESSION_BUS_ADDRESS, SSH_TTY and server version

---

ssh/tailssh/incubator.go
ssh/tailssh/tailssh.go
tailcfg/tailcfg.go

ssh/tailssh: add support for agent forwarding.

---

ssh/tailssh/tailssh.go
tailcfg/tailcfg.go

tailcfg: add field to allow LocalPortForwarding in SSHAction

---

logtail/logtail.go

logtail: add Logger.PrivateID accessor

---

cmd/tailscale/cli/file.go

This addresses #3548 for the tailscale users who use 'tailscale file get' to receive Taildrops.

cmd/tailscale: add file get options for dealing with existing files

---

ipn/localapi/localapi.go
net/dns/resolver/tsdns.go
tsweb/jsonhandler.go
tsweb/tsweb.go
types/netmap/netmap.go
util/dnsname/dnsname.go
wgengine/filter/tailcfg.go

all: use Go 1.18's strings.Cut

---

cmd/derpprobe/derpprobe.go

There is a Cosmic Background level of DERP Unreachability,
with individual nodes or regions becoming unreachable briefly
and returning a short time later.
Returning a 500 error pages a human. Being awoken at 3am for
a transient error is annoying.
For relatively small levels of badness don't page a human,
just post to Slack. If the outage impacts a significant fraction
of the DERP fleet, then page a human.

cmd/derpprobe: don't alert for smaller failures.

---

ssh/tailssh/tailssh_test.go

ssh/tailssh_test: Skip the env test in CI

---

types/views/views.go

From https://github.com/tailscale/corp/pull/4370#pullrequestreview-913732761

types/views: rename Generic to Unwrap

---

.github/workflows/go-generate-without-stringer.sh
.github/workflows/go_generate.yml
net/dnsfallback/dnsfallback.go
net/dnsfallback/generate.go

.github/workflows: work around golang/go#51629

---

Makefile

Makefile: use ./tool/go everywhere

---

tsweb/tsweb.go

When the request comes in say over http://mon, the current
implementation would rewrite it https://mon which causes the cert
validation to fail. This PR keeps the existing behavior intact but also
allows passing in a FQDN to the handler to reroute to the correct
hostname.
Related to https://github.com/tailscale/tailscale/pull/4208#pullrequestreview-913832340

tsweb: add FQDN to Port80Handler to allow HTTPS redirects

---

ssh/tailssh/tailssh_test.go

ssh/tailssh_test: skip TestSSH/stdin in CI

---

ssh/tailssh/tailssh_test.go
tstest/archtest/qemu_test.go
util/cibuild/cibuild.go

all: use cibuild.On

---

ssh/tailssh/tailssh.go

To asciinema cast format.
Updates #3802

ssh/tailssh: start of implementing optional session recording

---

prober/http.go
prober/prober.go
prober/prober_test.go
prober/tcp.go
prober/tls.go

prober: library to build healthchecking probers.

---

control/controlbase/conn.go

Uses 4KB less per Conn.
Updates #4113

control/controlbase: use less memory when idle (remove txState.buf)

---

net/tstun/wrap.go
wgengine/netstack/netstack.go

( child change of #4222 )
Plumb the outbound injection path to allow passing netstack
PacketBuffers down to the tun Read, where they are decref'd to enable
buffer re-use. This removes one packet alloc & copy, and reduces GC
pressure by pooling outbound injected packets.
Fixes #2741
The following before and after heap samples are taken from a fresh instance of tailscaled running in userspace mode, transporting a 383mb file over http between lan connected nodes:
Before:
```
Showing nodes accounting for 1.92GB, 96.19% of 2GB total
Dropped 234 nodes (cum <= 0.01GB)
Showing top 10 nodes out of 58
flat  flat%   sum%        cum   cum%
0.54GB 27.10% 27.10%     0.54GB 27.10%  golang.zx2c4.com/wireguard/device.(*Device).PopulatePools.func1
0.39GB 19.45% 46.55%     0.41GB 20.50% …
```

wgengine: inject packetbuffers rather than bytes

---

control/controlclient/direct.go
control/controlclient/map.go
ipn/ipnlocal/local.go
tailcfg/tailcfg.go

control/controlclient, ipn/ipnlocal, tailcfg: add MapResponse.PopBrowserURL

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

ssh/tailssh: support placeholders in SSHAction.HoldAndDelegate URL

---

ssh/tailssh/tailssh.go
tailcfg/tailcfg.go

ssh/tailssh, tailcfg: add more HoldAndDelegate expansions, document

---

go.mod
go.sum

go.mod: bump x/crypto for SSH change

---

cmd/proxy-to-grafana/proxy-to-grafana.go

cmd/proxy-to-grafana: fix package doc code snippet

---

client/tailscale/tailscale.go
envknob/envknob.go
ipn/ipnlocal/local.go

envknob, ipn/ipnlocal: add SSH admin kill switch

---

cmd/tailscale/cli/nc.go

Adds missing file from fc12cbfcd381b31de905ac431d76fb8c054006a2.
GitHub was having issues earlier and it was all green because the
checks never actually ran, but the DCO non-Actions check at least did,
so "green" and I merged, not realizing it hadn't really run anything.
Updates #3802

client/tailscale, cmd/tailscale, localapi: add 'tailscale nc' (actually)

---

hostinfo/hostinfo.go
tsnet/tsnet.go

tsnet: set Hostinfo.Package to "tsnet" on use

---

ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go

ipn/ipnstate: put SSH Host Keys in ipnstate.PeerStatus

---

cmd/tailscale/cli/ssh.go

cmd/tailscale: generate known_hosts file for 'tailscale ssh'

---

cmd/tailscale/cli/ssh.go
net/tsdial/dnsmap.go

cmd/tailscale: write fewer known_hosts, resolve ssh host to FQDN early

---

envknob/envknob.go

envknob: use the correct key when logging

---

go.mod
go.sum

Signed-off-by: Matt Layher <mdlayher@gmail.com>
I'm stabilizing some of my repos that haven't changed in some time. This should be a noop.

go.mod: github.com/mdlayher/sdnotify@v1.0.0

---

api.md

Expected input is JSON formatted []policy.ACLTest

api: update acl/validate data format

---

cmd/mkpkg/main.go
go.mod
go.sum

cmd/mkpkg: use package flag

---

cmd/tailscale/cli/file.go

To "automatically receive taildrop files to my Downloads directory,"
a user currently has to run 'tailscale file get' in a loop.
Add a "looping" / daemon option to the file get command so no shell
scripts will be required for this behavior.   Addresses #2312.
Signed-off-by: David Eger <david.eger@gmail.com>

cmd/tailscale: Add file get --loop flag.

---

client/tailscale/tailscale.go
cmd/tailscale/cli/cli.go
cmd/tailscale/cli/id-token.go
ipn/localapi/localapi.go

cmd/tailscale: add id-token subcommand

---

ipn/ipnstate/ipnstate.go

Signed-off-by: Ilya Mateyko <me@astrophena.name>

ipn/ipnstate: make status page more mobile-friendly

---

control/controlclient/direct.go
control/controlclient/direct_test.go
ipn/ipnstate/ipnstate.go
tailcfg/tailcfg.go

We could land this now, I've tested a round-trip.

control/controlclient: wire up PingRequest for disco & TSMP

---

client/tailscale/apitype/apitype.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go
tailcfg/tailcfg.go
wgengine/filter/filter.go
wgengine/filter/filter_test.go
wgengine/filter/match.go
wgengine/filter/match_clone.go
wgengine/filter/tailcfg.go

all: add arbitrary capability support

---

ipn/ipnlocal/local.go

And rename to updateFilterLocked to prevent future mistakes.
Fixes #4427

ipn/ipnlocal: only call updateFilter with mutex held

---

ipn/ipnlocal/local.go
ssh/tailssh/tailssh.go

ssh/tailssh: close sessions on policy change if no longer allowed

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

ssh/tailssh: cache public keys fetched from URLs

---

cmd/tailscale/cli/up.go

cmd/tailscale: unhide 'up --ssh' behind WIP env var

---

cmd/tailscale/cli/ssh.go

cmd/tailscale: [ssh] enable StrictHostKeyChecking mode

---

ipn/ipnlocal/local.go
ssh/tailssh/tailssh.go

ipn/ipnlocal: also use SSHPolicies when updating filterHash

---

tailcfg/tailcfg.go

tailcfg: clarify how SSHPolicy.Rules are evaluated between auth phases

---

net/dns/resolver/forwarder.go

If all N queries failed, we waited until context timeout (in 5
seconds) to return.
This makes (*forwarder).forward fail fast when the network's
unavailable.

net/dns/resolver: count errors when racing DNS queries, fail earlier

---

derp/derphttp/derphttp_client.go
net/netcheck/netcheck.go

Updates #4377
In cases where tailscale is operating behind a MITM proxy, we need to consider that a lot more of the internals of our HTTP requests are visible and may be used as part of authorization checks. As such, we need to 'behave' as closely as possible to ideal.
- Some proxies do authorization or consistency checks based the on Host header or HTTP URI, instead of just the IP/hostname/SNI. As such, we need to construct a `*http.Request` with a valid URI everytime HTTP is going to be used on the wire, even if its over TLS.
Aside from the singular instance in net/netcheck, I couldn't find anywhere else a http.Request was constructed incorrectly.
- Some proxies may deny requests, typically by returning a 403 status code. We should not consider these requests as a valid latency check, …

derp/derphttp,net/netcheck: improve netcheck behavior under MITM proxies

---

wgengine/router/router_linux.go

wgengine/router: make supportsV6NAT check catch more cases

---

envknob/envknob.go
ipn/ipnlocal/local.go
ssh/tailssh/tailssh.go

ipn/ipnlocal: reject tailscale up --ssh if disabled on tailnet

---

tstest/iosdeps/iosdeps.go
tstest/iosdeps/iosdeps_test.go

tstest/iosdeps: add test for forbidden iOS dependencies

---

ipn/ipnlocal/peerapi.go

We intercept the peerapi port in netstack anyway, so there's no reason
the linux kernel on Android needs to know about it. It's only getting
in the way and causing problems for reasons we don't fully understand.
But we don't even need to understand it because it's not relevant
anymore.
Instead, provide a dummy net.Listener that just sits and blocks to
pacify the rest of the code that assumes it can be stuck in a
Listener.Accept call and call Listener.Close and Listener.Addr.
We'll likely do this for all platforms in the future, if/when we also
link in netstack on iOS.
Updates #4449
Updates #4293
Updates #3986

ipn/ipnlocal: make peerapi listener on Android avoid the kernel

---

ipn/ipnlocal/peerapi.go

The previous commit (1b89662eff) this for Android, but we can also use
this on any platform if we we would otherwise fail.

ipn/ipnlocal: use the fake peerapi listener as fallback if netstack available

---

go.mod
go.sum
ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go
tempfork/gliderlabs/ssh/server.go

ssh/tailssh: terminate ssh auth early if no policy can match

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

ssh/tailssh: support expansions in public key fetch URL too

---

cmd/tailscale/cli/debug.go
net/tsaddr/tsaddr.go

```
$ tailscale debug via 0xb 10.2.0.0/16
fd7a:115c:a1e0:b1a:0:b:a02:0/112
$ tailscale debug via fd7a:115c:a1e0:b1a:0:b:a02:0/112
site 11 (0xb), 10.2.0.0/16
```
Previously: 3ae701f0ebe053a1f7b6a3fa345a56b3132c818f
This adds a little debug tool to do CIDR math to make converting between
those ranges easier for now.
Updates #3616

cmd/tailscale: add "debug via" subcommand to do CIDR math for via ranges

---

tailcfg/tailcfg.go

From f74ee80abe8819f3d3bfd9138056a46820f4fc54 which lacked docs.
Updates #3802

tailcfg: document SSHPrincipal.PubKeys URL expansions

---

ssh/tailssh/tailssh.go
tailcfg/tailcfg.go

Noted by @danderson.
Updates #3802

tailcfg: fix typo in SessionDuration field name

---

ssh/tailssh/incubator.go
ssh/tailssh/tailssh.go

ssh/tailssh: set groups and gid in the incubated process

---

ssh/tailssh/tailssh.go

ssh/tailssh: chmod the auth socket to be only user accessible

---

ssh/tailssh/tailssh.go

ssh/tailssh: simplify matchRule with Reject rules

---

net/tshttpproxy/tshttpproxy_linux.go
net/tshttpproxy/tshttpproxy_synology.go
net/tshttpproxy/tshttpproxy_synology_test.go

tshttpproxy: support synology proxy configuration

---

wgengine/magicsock/magicsock.go
wgengine/userspace.go

wgengine/{,magicsock}: add metrics for rebinds and restuns

---

ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go

ipn/ipnlocal: do not initialize peer api listeners when shutting down

---

wgengine/monitor/monitor_darwin.go

wgengine/monitor: do not ignore changes to pdp_ip*

---

safesocket/unixsocket.go

Tested three macOS Tailscale daemons:
- App Store (Network Extension)
- Standalone (macsys)
- tailscaled
And two types of local IPC each:
- IPN
- HTTP
And two CLI modes:
- sandboxed (running the GUI binary as the CLI; normal way)
- open source CLI hitting GUI (with #4525)
Bonus: simplifies the code.
Fixes tailscale/corp#4559

safesocket: fix CLI on standalone mac GUI build

---

wgengine/netstack/netstack.go

Setting keepalive ensures that idle connections will eventually be
closed. In userspace mode, any application configured TCP keepalive is
effectively swallowed by the host kernel, and is not easy to detect.
Failure to close connections when a peer tailscaled goes offline or
restarts may result in an otherwise indefinite connection for any
protocol endpoint that does not initiate new traffic.
This patch does not take any new opinion on a sensible default for the
keepalive timers, though as noted in the TODO, doing so likely deserves
further consideration.
Update #4522

wgengine/netstack: always set TCP keepalive

---

ipn/ipnlocal/peerapi.go

ipn/ipnlocal/peerapi: add endpoint to list local interfaces

---

control/controlhttp/client.go

control/controlhttp: start port 443 fallback sooner if 80's stuck

---

api.md

api.md: document new ACL validate mode

---

control/controlhttp/client.go
control/controlhttp/http_test.go

Just because we get an HTTP upgrade response over port 80, don't
assume we'll be able to do bi-di Noise over it. There might be a MITM
corp proxy or anti-virus/firewall interfering. Do a bit more work to
validate the connection before proceeding to give up on the TLS port
443 dial.
Updates #4557 (probably fixes)

control/controlhttp: don't assume port 80 upgrade response will work

---

net/tshttpproxy/tshttpproxy_synology.go
net/tshttpproxy/tshttpproxy_synology_test.go

This updates the fix from #4562 to pick the proxy based on the request scheme.
Updates #4395, #2605, #4562

net/tshttpproxy: synology: pick proxy by scheme

---

go.mod
go.sum

go.mod: bump github.com/tailscale/golang-x-crypto/ssh

---

safesocket/safesocket_darwin.go

It won't work, provide a clue in the error output.
Fixes #3063

safesocket: log warning when running sandboxed Mac binary as root

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/file.go
cmd/tailscaled/ssh.go
net/netcheck/netcheck.go
wgengine/winnet/winnet_windows.go

Well, goimports actually (which adds the normal import grouping order we do)

all: gofmt all

---

net/dns/manager.go
net/tstun/wrap.go
tsnet/tsnet.go
wgengine/netstack/netstack_test.go

This were intended to be pushed to #4408, but in my excitement I forgot to `git add` :/ better late than never.
See #4408 for context on why these changes were requested.

Follow-on to #4408 (missed the git add :/)

---

tailcfg/tailcfg.go

tailcfg: remove some documented DebugFlags that no longer exist

---

ssh/tailssh/ctxreader.go
ssh/tailssh/tailssh.go

ssh/tailssh: handle Control-C during hold-and-delegate prompt

---

api.md

api.md: update GET tailnet key detail docs to show preauthorized, tags

---

net/dns/manager.go
net/dns/manager_tcp_test.go
wgengine/netstack/netstack.go

net/dns, wgengine: implement DNS over TCP

---

ipn/ipnlocal/local.go
wgengine/netstack/netstack.go

wgengine/netstack, ipn/ipnlocal: serve http://100.100.100.100/

---

cmd/viewer/tests/tests.go
cmd/viewer/tests/tests_clone.go
cmd/viewer/tests/tests_view.go
cmd/viewer/viewer.go
tailcfg/tailcfg.go
tailcfg/tailcfg_view.go
types/views/views.go
types/views/views_test.go

cmd/viewer,types/views: add support for views of maps

---

types/views/views.go
types/views/views_test.go

types/views: remove alloc in hot path

---

tsweb/tsweb.go

tsweb: support recording unabridged HTTP status codes as well.

---

tsweb/tsweb.go

Saves 1-2 allocs per HTTP request after warmup, thanks to
avoiding strconv and fmt.

tsweb: memoize the string forms of HTTP response codes.

---

api.md

Updates https://github.com/tailscale/tailscale/issues/2120
Updates https://github.com/tailscale/tailscale/issues/4571
Updates https://github.com/tailscale/tailscale/issues/1369

api.md: document preauthorized and tags fields

---

types/key/node.go

Needed for an experiment in Control: see https://github.com/tailscale/corp/pull/5259

types/key: make NodePublic implement Shardable

---

ipn/ipnserver/proxyconnect.go
ipn/ipnserver/proxyconnect_js.go

Broken by 3dedcd1640 but we don't have CI coverage yet.

ipn/ipnserver: fix build on js/wasm

---

.github/workflows/cross-wasm.yml

For now just checks that we can build cmd/tailscale/cli, will be
broadened once we can actually build more things.
Updates #3157

.github/workflows: add cross-builder for Wasm

---

.github/workflows/cross-wasm.yml

.github/workflows: fix duplicated build target in Wasm action

---

scripts/installer.sh

Fixes https://github.com/tailscale/tailscale/issues/4718

install.sh: add RHEL9.

---

logtail/logtail.go

Saves some allocs. Not hot, but because we can now.
And a const instead of a var.

logtail: use http.NewRequestWithContext

---

cmd/tailscale/cli/ping.go
ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go
tailcfg/tailcfg.go
types/netmap/netmap.go

For debugging when stuff like #4750 isn't working.

cmd/tailscale, ipn/ipnlocal: add "peerapi" ping type

---

net/tstun/constants.go
net/tstun/tun.go
wgengine/netstack/netstack.go

wgengine/netstack: make netstack MTU be 1280 also

---

wgengine/netstack/netstack.go

Per post-submit code review feedback of 1336fb740b7f from @maisem.

wgengine/netstack: replace a 1500 with a const + doc

---

words/scales.txt
words/tails.txt

words: The lists continue to drag-on.

---

cmd/tailscale/cli/up.go

Updates tailscale/corp#5468
Updates #3802

cmd/tailscale/cli: disallow --ssh on Synology

---

logpolicy/logpolicy.go

Ongoing log writing keeps the spinning disks from hibernating.
Fixes https://github.com/tailscale/tailscale/issues/3551
Tested on DSM6 and DSM7.

logpolicy: put Synology logs buffer in /tmp

---

build_docker.sh
docs/k8s/Dockerfile
docs/k8s/Makefile
docs/k8s/README.md
docs/k8s/proxy.yaml
docs/k8s/role.yaml
docs/k8s/run.sh
docs/k8s/sa.yaml
docs/k8s/sidecar.yaml
docs/k8s/subnet.yaml
docs/k8s/userspace-sidecar.yaml

build_docker.sh: add run.sh as an entrypoint to the docker image

---

control/controlclient/direct.go
ipn/ipnlocal/local.go

cmd/controlclient: wire up PingRequest peerapi pings too

---

tailcfg/tailcfg.go

tailcfg: add HostinfoView version of TailscaleSSHEnabled

---

tsweb/tsweb.go
tsweb/tsweb_test.go

Updates https://github.com/tailscale/corp/issues/5605

tsweb: implement interceptor for error page presentation

---

control/controlhttp/client_js.go

Forcing the insecure protocol (and perserving the port number) is only
desired for localhost testing, in prod we need to use wss:// to avoid
mixed-content errors.

control/controlhttp: use secure WebSockets protocol by default

---

util/deephash/deephash.go
util/deephash/deephash_test.go

util/deephash: fix map hashing to actually hash elements

---

util/deephash/deephash.go
util/deephash/deephash_test.go

Regression from 09afb8e35b56c1150ae9872d781c7ae3c151b848, in which the
same reflect.Value scratch value was being used as the map iterator
copy destination.
Also: make nil and empty maps hash differently, add test.
Fixes #4871
Co-authored-by: @josharian

util/deephash: fix map hashing when key & element have the same type

---

tailcfg/tailcfg.go

tailcfg: define some Node.Capabilities about SSH, its config

---

cmd/tailscale/cli/up.go
ipn/ipnlocal/local.go

cmd/tailscale/cli, ipn/ipnlocal: give SSH tips when off/unconfigured

---

control/controlclient/auto.go
control/controlclient/client.go
control/controlclient/direct.go
control/controlclient/direct_test.go
ipn/ipnlocal/local.go
ipn/ipnlocal/state_test.go
types/netmap/netmap.go

(tests elsewhere are fine without it)

control/controlclient, types/netmap: remove unused LocalPort field

---

control/controlclient/auto.go
control/controlclient/client.go
control/controlclient/direct.go
ipn/ipnlocal/local.go
ipn/ipnlocal/state_test.go

It can't change at runtime. Make it an option.

control/controlclient: remove Client.SetStatusFunc

---

util/deephash/deephash.go
util/deephash/deephash_test.go

util/deephash: fix collisions between different types

---

client/tailscale/acl.go

Co-authored-by: Will Norris <will@tailscale.com>

client/tailscale: update ACLRow and ACLTest with new ACL fields

---

util/deephash/deephash_test.go

(breaking up parts of another change)
This adds a PacketFilter hashing benchmark with an input that both
contains every possible field, but also is somewhat representative in
the shape of what real packet filters contain.

util/deephash: add packet filter benchmark

---

util/deephash/deephash.go
util/deephash/deephash_test.go

Currently unused. (breaking up a bigger change)

util/deephash: add canMemHash func + typeInfo property

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

Fixes #4920
Fixes tailscale/corp#5633
Updates #4479

ssh/tailssh: allow multiple sessions on the same conn
