tailscale/tailscale

ipn/ipnlocal/serve.go
The context can get canceled during backoff, and binding after that makes the listener impossible to close afterwards.
Fixes #12620.
=> ipn/ipnlocal: don't bind localListener if its context is canceled

cmd/tailscale/cli/exitnode.go
The exit node suggestion CLI command was written with the assumption that it's possible to provide a stableid on the command line, but this is incorrect. Instead, it will now emit the name of the exit node.
Fixes #12618
Change-Id: Id7277f395b5fca090a99b0d13bfee7b215bc9802
=> cmd/tailscale/cli: correct command emitted by exit node suggestion

.github/workflows/checklocks.yml, envknob/envknob.go, ipn/store/mem/store_mem.go, net/stun/stuntest/stuntest.go, net/wsconn/wsconn.go, proxymap/proxymap.go
This turns the checklocks workflow into a real check, and adds annotations to a few basic packages as a starting point.
Updates #12625
Change-Id: I2b0185bae05a843b5257980fc6bde732b1bdd93f
=> ci: enable checklocks workflow for specific packages

util/winutil/s4u/s4u_windows.go
This was correct before, I think I just made a copy/paste error when updating that PR.
Updates #12383
=> util/winutil/s4u: fix incorrect token type specified in s4u Login

net/dns/manager.go, net/dns/resolver/forwarder.go, net/dns/resolver/tsdns.go
And some misc doc tweaks for idiomatic Go style.
=> net/dns: move mutex before the field it guards

go.mod, go.sum, tsweb/promvarz/promvarz.go
Prometheus commons unexported the [FmtText in prometheus/common v0.48](https://github.com/prometheus/common/pull/576) and instead exported the NewFormat function passing in a format type.
=> go.mod: Update prometheus/client_golang

cmd/tailscale/cli/serve_v2_test.go, ipn/serve.go, ipn/serve_test.go
This is not valid in many situations, specifically when running a local astro site that listens on localhost, but ignores 127.0.0.1
Fixes: https://github.com/tailscale/tailscale/issues/12201
=> cmd/serve: don't convert localhost to 127.0.0.1

health/health.go, health/health_test.go, ipn/ipnlocal/profiles.go
When auto-udpates are enabled, we don't need to nag users to update after a new release, before we release auto-updates.
Updates https://github.com/tailscale/corp/issues/20081
=> health,ipn/ipnlocal: hide update warning when auto-updates are enabled

go.mod, go.sum
This pulls in device.WaitPool fixes from tailscale/wireguard-go@1e08883 and tailscale/wireguard-go@cfa4567.
Updates tailscale/corp#21095
=> go.mod: update wireguard-go

control/controlclient/direct.go, control/controlclient/direct_test.go, ipn/ipnlocal/network-lock.go, ipn/ipnlocal/network-lock_test.go, tka/sig.go, tka/sig_test.go
Detection of duplicate Network Lock signature chains added in 01847e0123dee3b7a6f9645155da69270f01155e failed to account for chains originating with a SigCredential signature, which is used for wrapped auth keys. This results in erroneous removal of signatures that originate from the same re-usable auth key.
This change ensures that multiple nodes created by the same re-usable auth key are not getting filtered out by the network lock.
Updates tailscale/corp#19764
=> ipn/ipnlocal: allow multiple signature chains from the same SigCredential

cmd/xdpderper/xdpderper.go, net/netutil/default_interface_portable.go, net/netutil/default_interface_portable_test.go
This makes deployment easier in hetrogenous environments.
Updates ENG-4274
=> cmd/xdpderper: add autodetection for default interface name

tool/gocross/gocross-wrapper.sh, tool/gocross/gocross_wrapper_test.go
Fix regression from #8108 (Mar 2023). Since that change, gocross has always been rebuilt on each run of ./tool/go (gocross-wrapper.sh), adding ~100ms.  (Well, not totally rebuilt; cmd/go's caching still ends up working fine.)
The problem was $gocross_path was just "gocross", which isn't in my path (and "." isn't in my $PATH, as it shouldn't be), so this line was always evaluating to the empty string:
gotver="$($gocross_path gocross-version 2>/dev/null || echo '')"
The ./gocross is fine because of the earlier `cd "$repo_root"`
Updates tailscale/corp#21262
Updates tailscale/corp#21263
=> tool/gocross: fix regression detecting when gocross needs rebuild

control/controlclient/direct.go, control/controlclient/direct_test.go, ipn/ipnlocal/network-lock.go, ipn/ipnlocal/network-lock_test.go, tka/sig.go, tka/sig_test.go
Cherry-pick #12638 into the stable release branch.
Updates https://github.com/tailscale/corp/issues/19764
=> ipn/ipnlocal: allow multiple signature chains from the same SigCredential (cherry-pick) 

net/dns/manager.go, net/dns/resolver/forwarder.go, net/dns/resolver/tsdns.go
Fixes tailscale/corp#20677
Replaces the original attempt to rectify this (by injecting a netMon event) which was both heavy handed, and missed cases where the netMon event was "minor".
On apple platforms, the fetching the interface's nameservers can and does return an empty list in certain situations. Apple's API in particular is very limiting here. The header hints at notifications for dns changes which would let us react ahead of time, but it's all private APIs.
To avoid remaining in the state where we end up with no nameservers but we absolutely need them, we'll react to a lack of upstream nameservers by attempting to re-query the OS.
We'll rate limit this to space out the attempts. It seems relatively harmless to attempt a reconfig every 5 seconds (triggered by an incoming query) if …
=> net/dns: recheck DNS config on SERVFAIL errors (cherry-pick)

net/dns/resolver/forwarder.go
Updates tailscale/corp#20677
The recover function wasn't getting set in the benchmark tests.  Now defaults to an empty func to things don't blow up if it's not set.
=> net/dns: fix broken dns benchmark tests

health/health.go, health/warnings.go
High severity health warning = a system notification will appear, which can be quite disruptive to the user and cause unnecessary concern in the event of a temporary network issue.
Per design decision (@sonovawolf), the severity of all warnings but "network is down" should be tuned down to medium/low. ImpactsConnectivity should be set, to change the icon to an exclamation mark in some cases, but without a notification bubble.
I also tweaked the messaging for update-available, to reflect how each platform gets updates in different ways.
=> health: reduce severity of some warnings, improve update messages

cmd/tailscale/cli/exitnode.go, cmd/tailscale/cli/exitnode_test.go
This change expands the `exit-node list -filter` command to display all location based exit nodes for the filtered country. This allows users to switch to alternative servers when our recommended exit node is not working as intended.
This change also makes the country filter matching case insensitive, e.g. both USA and usa will work.
Before:
After: 
Updates #12698
=> cmd/tailscale/cli: exit node filter should display all exit node options

health/state.go, health/warnings.go
We should make sure to send the value of ImpactsConnectivity over to the clients using LocalAPI as they need it to display alerts in the GUI properly.
=> health: send ImpactsConnectivity value over LocalAPI

cmd/containerboot/main.go, cmd/containerboot/main_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/testutils_test.go, util/linuxfw/fake.go
Don't skip installing egress forwarding rules for IPv6, and set headless services ipFamilyPolicy to PreferDualStack to optionally enable both IP families when possible. Note that even with PreferDualStack set, testing a dual-stack GKE cluster with the default DNS setup of kube-dns did not correctly set both A and AAAA records for the headless service, and instead only did so when switching the cluster DNS to Cloud DNS. For both IPv4 and IPv6 to work simultaneously in a dual-stack cluster, we require headless services to return both A and AAAA records.
Fixes #12215
Testing steps for GKE single stack, dual-stack, and EKS IPv6-only:
```shell-session
kubectl apply -f-<<EOF
apiVersion: v1
kind: Service
metadata:
annotations:
tailscale.com/tailnet-fqdn: tailnet-node.abc123.ts.net
name: …
```
=> cmd/containerboot,cmd/k8s-operator: enable IPv6 for fqdn egress proxies

go.mod, go.sum
For https://github.com/tailscale/wireguard-go/commit/2f5d148bcfe13a65d0f85dca8698200543c226da
Updates tailscale/corp#20732
=> go.mod: bump github.com/tailscale/wireguard-go

control/controlknobs/controlknobs.go, tailcfg/tailcfg.go, wgengine/magicsock/debugknobs.go, wgengine/magicsock/debugknobs_stubs.go, wgengine/magicsock/derp.go
The DERP Return Path Optimization (DRPO) is over four years old (and
on by default for over two) and we haven't had problems, so time to
remove the emergency shutoff code (controlknob) which we've never
used. The controlknobs are only meant for new features, to mitigate
risk. But we don't want to keep them forever, as they kinda pollute
the code.
Updates #150
=> control/controlknobs,tailcfg,wgengine/magicsock: remove DRPO shutoff switch

tailcfg/tailcfg.go, wgengine/magicsock/debugknobs.go, wgengine/magicsock/debugknobs_stubs.go, wgengine/magicsock/magicsock.go
For testing. Lee wants to play with 'AWS Global Accelerator Custom
Routing with Amazon Elastic Kubernetes Service'. If this works well
enough, we can promote it.
Updates #12578
=> wgengine/magicsock: add debug envknob for injecting an endpoint

client/tailscale/localclient.go
I apparently missed this in 4b6a0c42c89a6a004686a13e16d6a0821680d74d.
Updates tailscale/corp#18266
=> client/tailscale: use safesocket.ConnectContext

clientupdate/clientupdate.go, cmd/tailscale/cli/set.go, ipn/ipnlocal/autoupdate.go, ipn/ipnlocal/c2n.go
While `clientupdate.Updater` won't be able to apply updates on macsys, we use `clientupdate.CanAutoUpdate` to gate the EditPrefs endpoint in localAPI. We should allow the GUI client to set AutoUpdate.Apply on macsys for it to properly get reported to the control plane. This also allows the tailnet-wide default for auto-updates to propagate to macsys clients.
Updates https://github.com/tailscale/corp/issues/21339
=> clientupdate: return true for CanAutoUpdate for macsys

cmd/k8s-operator/spdy-hijacker.go
Adds the name of the container that is being exec-d to CastHeader, so that it gets sent to the session recorder.
Updates tailscale/corp#19821
=> cmd/k8s-operator: send container name to session recorder

wgengine/magicsock/debugknobs.go, wgengine/magicsock/debugknobs_stubs.go, wgengine/magicsock/magicsock.go
Load Balancers often have more than one ingress IP, so allowing us to
add multiple means we can offer multiple options.
Updates #12578
=> wgengine/magicsock: allow a CSV list for pretendpoint

ipn/ipnlocal/c2n.go, posture/hwaddr.go, tailcfg/c2ntypes.go
If an optional `hwaddrs` URL parameter is present, add network interface hardware addresses to the posture identity response.
Just like with serial numbers, this requires client opt-in via MDM or `tailscale set --posture-checking=true`
(https://tailscale.com/kb/1326/device-identity)
Updates tailscale/corp#21371
=> posture: add network hardware addresses to posture identity

api.md, publicapi/device.md, publicapi/deviceinvites.md, publicapi/readme.md, publicapi/tailnet.md, publicapi/userinvites.md
Add note that API docs have moved to `https://tailscale.com/api` to the top of existing API docs markdown files.
Updates https://github.com/tailscale/corp/issues/1301
=> publicapi: add note that API docs have moved to existing docs files

net/dns/publicdns/publicdns.go, net/dns/publicdns/publicdns_test.go
This commit truncates any additional information (mainly hostnames) that's passed to controlD via DOH URL in `DoHIPsOfBase`. This change is to make sure only resolverID is passed to `controlDv6Gen` but not the additional information.
Before the  change, `DoHIPsOfBase` woud try to pass something like `abc123def45/kevin-macbook` to `controlDv6Gen` and parse it as a base-36 int. `controlDv6Gen` then swallows error and pretends nothing happens while returning empty ipv6 address.
Updates: #7946
=> net/dns/publicdns: remove additional information in DOH URL passed to IPv6 address generation for controlD.

health/health.go, health/health_test.go, health/state.go, health/warnings.go
To reduce the likelihood of presenting spurious warnings, add the ability to delay the visibility of certain Warnables, based on a TimeToVisible time.Duration field on each Warnable. The default is zero, meaning that a Warnable is immediately visible to the user when it enters an unhealthy state. Watchers of the Tracker are only notified via their callback once an unhealthy Warnable becomes visible.
=> health: support delayed Warnable visibility

cmd/cloner/cloner.go, cmd/viewer/tests/tests.go, cmd/viewer/tests/tests_clone.go, cmd/viewer/tests/tests_view.go, cmd/viewer/viewer.go, ipn/ipn_clone.go, tailcfg/tailcfg_clone.go, util/codegen/codegen.go, util/codegen/codegen_test.go
This adds support for generic types and interfaces to our cloner and viewer codegens. It updates these packages to determine whether to make shallow or deep copies based on the type parameter constraints. Additionally, if a template parameter or an interface type has View() and Clone() methods, we'll use them for getters and the cloner of the owning structure.
Updates #12736
=> cmd/cloner, cmd/viewer, util/codegen: add support for generic types and interfaces

syncs/syncs.go, syncs/syncs_test.go
Some operations cannot be implemented with the prior API:
* Iterating over the map and deleting keys
* Iterating over the map and replacing items
* Calling APIs that expect a native Go map
Add a Map.WithLock method that acquires a write-lock on the map
and then calls a user-provided closure with the underlying Go map.
This allows users to interact with the Map as a regular Go map,
but with the gaurantees that it is concurrent safe.
Updates tailscale/corp#9115
=> syncs: add Map.WithLock to allow mutations to the underlying map

cmd/tailscale/cli/drive.go
As suggested in #12258, resolve relative paths in `tailscale drive share` from `tailscale`'s working directory.
=> cmd/tailscale: resolve taildrive share paths

health/health_test.go
Fixes tailscale/tailscale#12794
We were printing some leftover debug logs within a callback function that would be executed after the test completion, causing the test to fail. This change drops the log calls to address the issue.
=> health: drop unnecessary logging in TestSetUnhealthyWithTimeToVisible

ipn/ipnlocal/local.go, log/sockstatlog/logger.go, log/sockstatlog/logger_test.go
=> log/sockstatlog: don't block for more than 5s on shutdown

cmd/tailscale/cli/exitnode.go, ipn/prefs.go, ipn/prefs_test.go
To match the format of exit node suggestions and ensure that the result is not ambiguous, relax exit node CLI selection to permit using a FQDN including the trailing dot.
Updates #12618
Change-Id: I04b9b36d2743154aa42f2789149b2733f8555d3f
=> ipn: allow FQDN in exit node selection

client/tailscale/acl.go
This change allows ACL contents to include node attributes https://tailscale.com/kb/1337/acl-syntax#node-attributes-nodeattrs
Updates tailscale/corp#20583
=> client/tailscale: add the nodeAttrs section

cmd/k8s-operator/proxyclass.go, cmd/k8s-operator/proxyclass_test.go
Adds a new `k8s_proxyclass_resources` gauge to track currently managed `ProxyClass` resources.
Also starts adding finalizers to `ProxyClass`es to ensure that the reconciler can correctly update the gauge when `ProxyClass` is being deleted.
A side effect of this is that if users downgrade the operator version to one that does not clean up finalizers from `ProxyClass`, they will need to manually remove finalizers to be able to delete any `ProxyClass`es created from this or newer version. That should be acceptable.
Updates tailscale/tailscale#10709
=> cmd/k8s-operator: add a metric to track the amount of ProxyClass resources

client/tailscale/acl.go
And justify its legacy name.
Updates #1931
=> client/tailscale: document ACLTestFailureSummary.User field

cmd/k8s-operator/deploy/chart/templates/deployment.yaml, cmd/k8s-operator/deploy/chart/values.yaml
Fixes #12857
Signed-off-by: Lee Briggs <lee@leebriggs.co.uk>
=> cmd/k8s-operator/deploy/chart: allow setting extra env vars in the operator

client/tailscale/localclient.go, cmd/tailscale/cli/cert.go, ipn/ipnlocal/cert.go, ipn/localapi/cert.go
Some users run "tailscale cert" in a cron job to renew their
certificates on disk. The time until the next cron job run may be long
enough for the old cert to expire with our default heristics.
Add a `--min-validity` flag which ensures that the returned cert is
valid for at least the provided duration (unless it's longer than the
cert lifetime set by Let's Encrypt).
Updates #8725
=> cmd/tailscale: add --min-validity flag to the cert command

cmd/viewer/tests/tests.go, cmd/viewer/tests/tests_clone.go, cmd/viewer/tests/tests_view.go, cmd/viewer/viewer.go, types/views/views.go, types/views/views_test.go, util/codegen/codegen.go
This adds support for container-like types such as Container[T] that don't explicitly specify a view type for T. Instead, a package implementing a container type should also implement and export a ContainerView[T, V] type and a ContainerViewOf(*Container[T]) ContainerView[T, V] function, which returns a view for the specified container, inferring the element view type V from the element type T.
Updates #12736
=> cmd/viewer, types/views, util/codegen: add viewer support for custom container types

util/slicesx/slicesx.go, util/slicesx/slicesx_test.go
The standard library includes these for strings and byte slices, but it lacks similar functions for generic slices of comparable types. Although they are not as commonly used, these functions are useful in scenarios such as working with field index sequences (i.e., []int) via reflection.
Updates #12687
=> util/slicesx: add HasPrefix, HasSuffix, CutPrefix, and CutSuffix functions

types/lazy/lazy.go, types/lazy/sync_test.go
It is sometimes necessary to change a global lazy.SyncValue for the duration of a test. This PR adds a (*SyncValue[T]).SetForTest method to facilitate that.
Updates #12687
=> types/lazy: add (*SyncValue[T]).SetForTest method

ipn/conf.go, ipn/ipnlocal/local.go, wgengine/magicsock/magicsock.go
See https://github.com/tailscale/tailscale/pull/12735 for context - the new `TS_DEBUG_PRETENDPOINTS` env var has been tested and seems like a good solution for getting direct connections if you are on EKS and willing to use an NLB.
This PR attempts to allow configuring the same via the tailscaled configfile:
- Adds a new `StaticEndpoints` field to tailscaled config that can be used to statically configure the endpoints that the node advertizes
- Adds a method to magicsock to reset the static endpoints and asynchronously call ReSTUN to propagate the update
- Updates the method that is called when the configfile is reloaded to call the new magicsock method if there is a change in static endpoints
(Currently nothing calls the reload endpoint though. I've tested this PR by calling `curl -X …
=> ipn,wgengine/magicsock: allow setting static node endpoints via tailscaled configfile

types/lazy/lazy.go, types/lazy/sync_test.go
=> types/lazy: re-init SyncValue during test cleanup if it wasn't set before SetForTest

net/dnsfallback/dns-fallback-servers.json
Updates tailscale/corp#21949
As discussed with @raggi, this PR updates the static DERPMap embedded in the client to reflect the availability of HTTP on the DERP servers run by Tailscale.
=> net/dnsfallback: set CanPort80 in static DERPMap

util/osuser/user.go
Remove the restriction that getent is skipped on non-Linux unixes. Improve validation of the parsed output from getent, in case unknown systems return unusable information.
This is a long-standing TODO; Tailscale only uses getent on Linux to get the correct login shell: https://github.com/tailscale/tailscale/blob/d2fef01206cd7a96d684f9c69ba9e767de824ab4/util/osuser/user.go#L54-L58
There is a special workaround for macOS/Darwin in `ssh/tailssh`: https://github.com/tailscale/tailscale/blob/d2fef01206cd7a96d684f9c69ba9e767de824ab4/ssh/tailssh/user.go#L59-L61
...but other Unixes end up falling back to `/bin/sh` because the Go standard library functions don't return shell information.
`getent` isn't POSIX but is available on many, many systems. It makes sense to try it and handle error cases …
=> util/osuser: run getent on non-Linux Unixes

tsweb/tsweb.go, tsweb/tsweb_test.go
This PR adds a QuietLogging option to tsweb.LogOptions so that we can use its OnCompletion callbacks without decorating all handlers for each of logging, tracing and metrics. We have some services we'd like to add these to without also adding logging of every request.
Opened for discussion.
Fixes https://github.com/tailscale/tailscale/issues/12837
=> tsweb: add QuietLogging option to allow use of only OnCompletion for instrumentation

go.mod, go.sum
This picks up https://github.com/tailscale/xnet/pull/1 so that clients can move files even when holding only a lock for the source file.
Updates #12941
=> go.mod: pull in latest github.com/tailscale/xnet

health/args.go, net/dns/manager.go, net/dns/manager_tcp_test.go, net/dns/resolver/forwarder.go, net/dns/resolver/forwarder_test.go, net/dns/resolver/tsdns.go, net/dns/resolver/tsdns_test.go
updates tailscale/corp#21823
Broken/misconfigured or blocked DNS presents as "internet is broken'" to the end user.  This  plumbs the health tracker into the dns manager and forwarder and adds a health warning with a 5 second delay to filter out spurious errors.  This warning is raised on all failures in the forwarder and lowered on all successes.
=> net/dns: raise health warning for failing forwarded DNS queries

util/osuser/user.go
All wasi* are GOARCH wasm, so check that instead.
Updates #12732
=> util/osuser: turn wasm check into a const expression

Dockerfile
Add a warning that the Dockerfile in the OSS repo is not the currently used mechanism to build the images we publish - for folks who want to contribute to image build scripts or otherwise need to understand the image build process that we use.
=> Dockerfile: add a warning that this is not used to build our published images

build_docker.sh
It is no longer correct to state that we don't support running Tailscale in containers or on Kubernetes.
Updates tailscale/tailscale#12842
=> build_docker.sh: update script comment

cmd/tailscaled/tailscaled.go, net/dns/manager.go
fixes tailscale#12968
The dns manager cleanup func was getting passed a nil health tracker, which will cause a panic.   It's much happier with the system health tracker.   Non-nil requirement for the health tracker clarified in the docs.
=> net/dns, cmd: plumb system health tracker into dns cleanup

ipn/ipnlocal/local.go, net/captivedetection/captivedetection.go
Fixes tailscale/tailscale#12973
Updates tailscale/tailscale#1634
There was a logic issue in the captive detection code we shipped in https://github.com/tailscale/tailscale/pull/12707.
Assume a captive portal has been detected, and the user notified. Upon switching to another Wi-Fi that does *not* have a captive portal, we were issuing a signal to interrupt any pending captive detection attempt. However, we were not also setting the `captive-portal-detected` warnable to healthy. The result was that any "captive portal detected" alert would not be cleared from the UI.
Also fixes a broken log statement value.
=> net/captivedetection: call SetHealthy once connectivity restored

net/tlsdial/tlsdial.go
It seems some security software or macOS itself might be MITMing TLS
(for ScreenTime?), so don't warn unless it fails x509 validation
against system roots.
Updates #3198
=> net/tlsdial: relax self-signed cert health warning

wgengine/netstack/netstack.go, wgengine/netstack/netstack_tcpbuf_default.go, wgengine/netstack/netstack_tcpbuf_ios.go
wgengine/netstack: increase gVisor's TCP send and receive buffer sizes
This commit increases gVisor's TCP max send (4->6MiB) and receive
(4->8MiB) buffer sizes on all platforms except iOS. These values are
biased towards higher throughput on high bandwidth-delay product paths.
The iperf3 results below demonstrate the effect of this commit between
two Linux computers with i5-12400 CPUs. 100ms of RTT latency is
introduced via Linux's traffic control network emulator queue
discipline.
The first set of results are from commit f0230ce prior to TCP buffer
resizing.
gVisor write direction:
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   180 MBytes   151 Mbits/sec    0  sender
[  5]   0.00-10.10  sec   179 MBytes   149 Mbits/sec …
=> wgengine/netstack: increase gVisor's TCP send and receive buffer sizes

util/linuxfw/nftables_runner.go, wgengine/userspace.go
It was returning a nil `*iptablesRunner` instead of a nil `NetfilterRunner` interface which would then fail checks later.
Fixes #13012
=> util/linuxfw: return nil interface not concrete type

net/packet/checksum/checksum.go, net/packet/checksum/checksum_test.go, tailcfg/tailcfg.go
We were copying 12 out of the 16 bytes which meant that the 1:1 NAT required would only work if the last 4 bytes happened to match between the new and old address, something that our tests accidentally had. Fix it by copying the full 16 bytes and make the tests also verify the addr and use rand addresses.
Updates #9511
=> net/packet/checksum: fix v6 NAT

wgengine/capture/ts-dissector.lua
It was using a v4 field for a v6 address.
Updates tailscale/corp#8020
=> wgengine/capture: fix v6 field typo in wireshark dissector

cmd/tailscale/cli/network-lock.go
During review of #8644 the `recover-compromised-key` command was renamed to `revoke-key`, but the old name remained in some messages printed by the command.
Fixes tailscale/corp#19446
=> cmd/tailscale/cli: fix `revoke-keys` command name in CLI output

control/controlclient/direct.go, net/dnsfallback/dnsfallback.go, net/tsdial/tsdial.go
I noticed a few places with custom http.Transport where we are not closing idle connections when transport is no longer used.
Updates tailscale/corp#21609
=> {control,net}: close idle connections of custom transports

cmd/derpprobe/derpprobe.go, prober/prober.go, prober/prober_test.go, prober/status.go, prober/status.html
- Keep track of the last 10 probe results and successful probe latencies;
- Add an HTTP handler that triggers a given probe by name and returns it result as a plaintext HTML page or JSON, including recent probe results as a baseline
- Add a status page showing a list of all probes, their status, and a button that allows triggering a specific probe.
- Move `cmd/derpprobe` to the new status page.
Example:
Updates tailscale/corp#20583
=> prober: add HTTP endpoints for running probes and getting status

control/controlhttp/client.go, control/controlhttp/http_test.go
The same context we use for the HTTP request here might be re-used by the dialer, which could result in `GotConn` being called multiple times. We only care about the last one.
Fixes #13009
=> control/controlhttp: extract the last network connection

cmd/tsidp/tsidp.go, ipn/ipnlocal/local.go, ipn/ipnlocal/serve.go
Updates #10263.
Draft because currently local tailscaled mode doesn't correctly clean up IP:port bindings in the serve config.
=> cmd/tsidp: add funnel support

cmd/gitops-pusher/gitops-pusher.go
For cases where users want to be extra careful about not overwriting manual changes, add a flag to hard-fail. This is only useful if the etag cache is persistent or otherwise reliable. This flag should not be used in ephemeral CI workers that won't persist the cache.
Updates https://github.com/tailscale/corp/issues/22177
=> cmd/gitops-pusher: add --fail-on-manual-edits flag

cmd/gitops-pusher/gitops-pusher.go
In a situation when manual edits are made on the admin panel, around the GitOps process, the pusher will be stuck if `--fail-on-manual-edits` is set, as expected.
To recover from this, there are 2 options:
1. revert the admin panel changes to get back in sync with the code
2. check in the manual edits to code
The former will work well, since previous and local ETags will match control ETag again. The latter will still fail, since local and control ETags match, but previous does not.
For this situation, check the local ETag against control first and ignore previous when things are already in sync.
Updates https://github.com/tailscale/corp/issues/22177
=> cmd/gitops-pusher: ignore previous etag if local acls match control

net/dns/resolver/forwarder.go, net/dns/resolver/forwarder_test.go
Troubleshooting DNS resolution issues often requires additional information. This PR expands the effect of the `TS_DEBUG_DNS_FORWARD_SEND` envknob to `forwarder.forwardWithDestChan`, and includes the request type, domain name length, and the first 3 bytes of the domain's SHA-256 hash in the output.
Fixes #13070
=> net/dns/resolver: log forwarded query details when TS_DEBUG_DNS_FORWARD_SEND is enabled

cmd/stunstamp/stunstamp.go, cmd/stunstamp/stunstamp_default.go, cmd/stunstamp/stunstamp_linux.go
'stun' has been removed from metric names and replaced with a protocol label. This refactor is preparation work for HTTPS & ICMP support.
Updates tailscale/corp#22114
=> cmd/stunstamp: refactor to support multiple protocols

client/tailscale/acl.go
This adds the Via field for the https://tailscale.com/kb/1378/via feature to the ACLPreview response.
Updates tailscale/corp#22239
=> client/tailscale: add Via to UserRuleMatch

cmd/tailscaled/tailscaled.go, tstest/integration/tailscaled_deps_test_darwin.go, tstest/integration/tailscaled_deps_test_freebsd.go, tstest/integration/tailscaled_deps_test_linux.go, tstest/integration/tailscaled_deps_test_openbsd.go, tstest/integration/tailscaled_deps_test_windows.go
=> cmd/tailscaled: allow setting env via linux cmdline for integration tests

cmd/stunstamp/stunstamp.go, cmd/stunstamp/stunstamp_default.go, cmd/stunstamp/stunstamp_linux.go
HTTPS mirrors current netcheck behavior and TCP uses tcp_info->rtt.
Updates tailscale/corp#22114
=> cmd/stunstamp: implement HTTPS & TCP latency measurements

cmd/stunstamp/stunstamp.go, cmd/stunstamp/stunstamp_default.go, cmd/stunstamp/stunstamp_linux.go
getConns() is now responsible for returning both stable and unstable conns. conn and measureFn are now passed together via connAndMeasureFn. newConnAndMeasureFn() is responsible for constructing them.
TCP measurement timeouts are adjusted to more closely match netcheck.
=> cmd/stunstamp: refactor connection construction

cmd/tailscaled/tailscaled.go
=> cmd/tailscaled: add env knob to control default verbosity

gokrazy/go.mod, gokrazy/tsapp/builddir/github.com/gokrazy/gokrazy/go.mod, gokrazy/tsapp/builddir/github.com/gokrazy/gokrazy/go.sum, tstest/integration/nat/nat_test.go, tstest/natlab/vnet/conf.go, tstest/natlab/vnet/vnet.go
Using https://github.com/gokrazy/gokrazy/pull/275
This is much lower latency than logcatcher, which is higher latency
and chunkier. And this is better than getting it via 'tailscale debug
daemon-logs', which misses early interesting logs.
Updates #13038
=> tstest/natlab: get tailscaled logs from gokrazy via syslog

cmd/tailscale/cli/cli.go
=> cmd/tailscale/cli: don't run CLI as a service on gokrazy

cmd/k8s-operator/dnsrecords.go, cmd/k8s-operator/dnsrecords_test.go
This fixes a bug where DNS reconciler logic was always assuming that no more than one `EndpointSlice` exists for a `Service`. In fact, there can be multiple, for example, in dual-stack clusters, but also in other cases this is valid (as per kube docs), see #13056 for context.
This PR:
- allows for multiple EndpointSlices
- picks out the ones for IPv4 family
- deduplicates addresses
I have tested this on dual-stack cluster and observed that two `EndpointSlice` objects get created and our logic now correctly picks and uses the one for IPv4 address family.
Updates tailscale/tailscale#13056
=> cmd/k8s-operator: fix DNS reconciler for dual-stack clusters

cmd/tailscale/cli/cli.go
The change in b7e48058c8d2 was too loose; it also captured the CLI
being run as a child process under cmd/tta.
Updates #13038
Updates #1866
=> cmd/tailscale/cli: fix gokrazy CLI-as-a-service detection

tstest/integration/nat/nat_test.go
It's too new to be supported in Debian bookworm so just remove it.
It doesn't seem to matter or help speed anything up.
Updates #13038
=> tstest/integration/nat: remove -audio none flag from qemu

go.mod, go.sum
This latest version allows for building on various OpenBSD architectures.
=> go.mod: pull in latest github.com/creack/pty

wgengine/netstack/netstack.go
A SIGSEGV was observed around packet merging logic in gVisor's GRO package.
Updates tailscale/corp#22353
=> wgengine/netstack: disable gVisor TCP GRO for Linux

cmd/viewer/tests/tests.go, cmd/viewer/tests/tests_clone.go, cmd/viewer/tests/tests_view.go, cmd/viewer/viewer.go
This PR modifies viewTypeForContainerType to use the last type parameter of a container type as the value type, enabling the implementation of map-like container types where the second-to-last (usually first) type parameter serves as the key type.
It also adds a MapContainer type to test the code generation.
Updates #12736
=> cmd/viewer: add support for map-like container types

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_notwindows.go, wgengine/magicsock/magicsock_windows.go
By default, Windows sets the SIO_UDP_CONNRESET and SIO_UDP_NETRESET options on created UDP sockets. These behaviours make the UDP socket ICMP-aware; when the system gets an ICMP message (e.g. an "ICMP Port Unreachable" message, in the case of SIO_UDP_CONNRESET), it will cause the underlying UDP socket to throw an error. Confusingly, this can occur even on reads, if the same UDP socket is used to write a packet that triggers this response.
The Go runtime disabled the SIO_UDP_CONNRESET behavior in 3114bd6, but did not change SIO_UDP_NETRESET–probably because that socket option isn't documented particularly well.
Various other networking code seem to disable this behaviour, such as the Godot game engine (godotengine/godot#22332) and the Eclipse TCF agent (link below). Others appear to work …
=> wgengine/magicsock: disable SIO_UDP_NETRESET on Windows

wgengine/magicsock/batching_conn_linux.go
In a93dc6cdb10bcc87742011d3746660f06cf8cd1e tryUpgradeToBatchingConn() moved to build tag gated files, but the runtime.GOOS condition excluding Android was removed unintentionally from batching_conn_linux.go. Add it back.
Updates tailscale/corp#22348
=> wgengine/magicsock: don't upgrade to linuxBatchingConn on Android

net/dns/resolver/forwarder.go
Fixes tailscale/tailscale#13151
`DNS unavailable` was marked as a high severity warning. If people enter an area with bad cellular reception, they're bound to receive so many of these notifications as soon as the DNS can't be reached anymore. On Android (and other platforms), high severity notifications trigger a system notification. To reduce notification fatigue, here we reduce the severity level to medium. A medium severity warning will still display the warning icon on platforms with a tray icon because of the `ImpactsConnectivity=true` flag being set here, but it won't show a notification anymore.
=> health/dns: reduce severity of DNS unavailable warning

posture/hwaddr.go
Some machines have multiple network interfaces with the same MAC address.
Updates tailscale/corp#21371
=> posture: deduplicate MAC addresses before returning them

ipn/ipnlocal/local.go, util/syspolicy/policy_keys.go
Updates tailscale/corp#22120
Adds the ability to start the backend by reading an authkey stored in the syspolicy database (MDM). This is useful for devices that are provisioned in an unattended fashion.
=> ipnlocal: support setting authkey at login using syspolicy

ipn/ipnlocal/network-lock.go
While working on a load generator utility, spinning up and down a huge amount of clients, I encountered a panic when trying to _close_ a tsnet client when network lock attempts to get the public key of a node here.
It occurred quite rarely, and only when doing 100s of clients and I have been unable to figure where the key is unset before this line is called. 
Based on the function where this line exists, it seem reasonable to return an error instead of panicking.
=> ipn/ipnlocal: network-lock, error if no pubkey instead of panic

cmd/k8s-operator/deploy/chart/templates/deployment.yaml, cmd/k8s-operator/deploy/chart/values.yaml, cmd/k8s-operator/ingress.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/svc.go
Closes #12421
This PR adds support for defining `PROXY_DEFAULT_CLASS` as an operator env var - this defines a `ProxyClass` CR that will apply to _all_ exposed `Service` and `Ingress` resources. If defined, `tailscale.com/proxy-class` label will still take precedence.
=> cmd/k8s-operator: support default proxy class in k8s-operator

wgengine/netstack/gro/gro.go, wgengine/netstack/gro/gro_default.go, wgengine/netstack/gro/gro_ios.go
In df6014f1d7bf437adf239b75a62fd4c2f389ea2a we removed build tag gating preventing importation, which tripped a NetworkExtension limit test in corp. This was a reversal of
25f0a3fc8f6f9cf681bb5afda8e1762816c67a8b which actually made the situation worse, hence the simplification.
This commit goes back to the strategy in
25f0a3fc8f6f9cf681bb5afda8e1762816c67a8b, and gets us back under the limit in my local testing. Admittedly, we don't fully understand the effects of importing or excluding importation of this package, and have seen mixed results, but this commit allows us to move forward again.
Updates tailscale/corp#22125
=> wgengine/netstack/gro: exclude importation of gVisor GRO pkg on iOS

wgengine/netstack/netstack.go
net/tstun.Wrapper.InjectInboundPacketBuffer is not GSO-aware, which can break quad-100 TCP streams as a result.
Updates tailscale/corp#22511
Updates #13211
=> wgengine/netstack: disable gVisor GSO on Linux

cmd/systray/README.md, cmd/systray/logo.go, cmd/systray/systray.go, go.mod, go.sum
This adds a systray app for linux, similar to the apps for macOS and windows. There are already a number of community-developed systray apps, but most of them are either long abandoned, are built for a specific desktop environment, or simply wrap the tailscale CLI.
This uses fyne.io/systray (a fork of github.com/getlantern/systray) which uses newer D-Bus specifications to render the tray icon and menu. This results in a pretty broad support for modern desktop environments.
This initial commit lacks a number of features like profile switching, device listing, and exit node selection. This is really focused on the application structure, the interaction with LocalAPI, and some system integration pieces like the app icon, notifications, and the clipboard.
=> cmd/systray: add a basic linux systray app

cmd/systray/systray.go
Otherwise you get "Access denied: watch IPN bus access denied, must
set ipn.NotifyNoPrivateKeys when not running as admin/root or
operator".
This lets a non-operator at least start the app and see the status, even
if they can't change everything. (the web UI is unaffected by operator)
A future change can add a LocalAPI call to check permissions and guide
people through adding a user as an operator (perhaps the web client
can do that?)
Updates #1708
=> cmd/systray: set ipn.NotifyNoPrivateKeys, permit non-operator use

tstest/natlab/vnet/vip.go, tstest/natlab/vnet/vnet.go
All the magic service names with virtual IPs will need IPv6 variants.
Pull this out in prep.
Updates #13038
=> tstest/natlab: make a new virtualIP type in prep for IPv6 support

cmd/cloner/cloner.go, cmd/viewer/tests/tests.go, cmd/viewer/tests/tests_clone.go, cmd/viewer/tests/tests_view.go, cmd/viewer/viewer.go, util/codegen/codegen.go, util/codegen/codegen_test.go
Go 1.23 updates the `go/types` package to produce Alias type nodes for type aliases, unless disabled with `gotypesalias=0`. This new default behavior breaks `codegen.LookupMethod`, which uses checked type assertions to `types.Named` and `types.Interface`, as only named types and interfaces have methods.
In this PR, we update `codegen.LookupMethod` to perform method lookup on the right-hand side of the alias declaration and clearly switch on the supported type nodes types. We also improve support for various edge cases, such as when an alias is used as a type parameter constraint, and add tests for the `LookupMethod` function.
Additionally, we update `cmd/viewer/tests` to include types with aliases used in type fields and generic type constraints.
Updates #13224
Updates #12912
=> util/codegen, cmd/cloner, cmd/viewer: update codegen.LookupMethod to support alias type nodes

cmd/cloner/cloner.go, cmd/viewer/tests/tests.go, cmd/viewer/tests/tests_clone.go, cmd/viewer/tests/tests_view.go, cmd/viewer/viewer.go, util/codegen/codegen.go
We have several checked type assertions to `*types.Named` in both `cmd/cloner` and `cmd/viewer`. As Go 1.23 updates the `go/types` package to produce Alias type nodes for type aliases, these type assertions no longer work as expected unless the new behavior is disabled with `gotypesalias=0`.
In this PR, we add `codegen.NamedTypeOf(t types.Type)`, which functions like `t.(*types.Named)` but also unrolls type aliases. We then use it in place of type assertions in the `cmd/cloner` and `cmd/viewer` packages where appropriate.
We also update type switches to include `*types.Alias` alongside `*types.Named` in relevant cases, remove `*types.Struct` cases when switching on `types.Type.Underlying` and update the tests with more cases where type aliases can be used.
Updates #13224
Updates #12912
=> cmd/cloner, cmd/viewer, util/codegen: add support for aliases of cloneable types

ipn/ipnlocal/local.go
This is the equivalent of quad-100, but for IPv6. This is technically already contained in the Tailscale IPv6 ULA prefix, but that is only installed when remote peers are visible via control with contained addrs. The service addr should always be reachable.
Updates #1152
=> ipn/ipnlocal: install IPv6 service addr route

wgengine/netstack/netstack.go
=> wgengine/netstack: use types/logger.Logf instead of stdlib log.Printf

wgengine/netstack/netstack.go
This was previously disabled in 8e42510 due to missing GSO-awareness in tstun, which was resolved in d097096.
Updates tailscale/corp#22511
=> wgengine/netstack: re-enable gVisor GSO on Linux

net/tstun/wrap.go, wgengine/netstack/netstack.go
buffs[0] was not sized to hold pkt with GSO, resulting in a panic.
Updates tailscale/corp#22511
=> net/tstun: fix gvisor inbound GSO packet injection

tstest/natlab/vnet/conf.go, tstest/natlab/vnet/vnet.go, tstest/natlab/vnet/vnet_test.go
This adds support for sending packets to 33:33:00:00:01 at IPv6
multicast address ff02::1 to send to all nodes.
Nothing in Tailscale depends on this (yet?), but it makes debugging in
VMs behind natlab easier (e.g. you can ping all nodes), and other
things might depend on this in the future.
Mostly I'm trying to flesh out the IPv6 support in natlab now that we
can write vnet tests.
Updates #13038
=> tstest/natlab/vnet: add IPv6 all-nodes support

ipn/ipnlocal/drive.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_notwindows.go, ipn/ipnlocal/profiles_test.go, ipn/ipnlocal/profiles_windows.go
In preparation for multi-user and unattended mode improvements, we are refactoring and cleaning up `ipn/ipnlocal.profileManager`. The concept of the "current user", which is only relevant on Windows, is being deprecated and will soon be removed to allow more than one Windows user to connect and utilize `LocalBackend` according to that user's access rights to the device and specific Tailscale profiles.
We plan to pass the user's identity down to the `profileManager`, where it can be used to determine the user's access rights to a given `LoginProfile`. While the new permission model in `ipnauth` requires more work and is currently blocked pending PR reviews, we are updating the `profileManager` to reduce its reliance on the concept of a single OS user being connected to the backend at the …
=> ipn/ipnlocal: refactor and cleanup profileManager

tstest/natlab/vnet/conf.go, tstest/natlab/vnet/vnet.go, tstest/natlab/vnet/vnet_test.go
This adds tests for DNS requests, and ignoring IPv6 packets on v4-only
networks.
No behavior changes. But some things are pulled out into functions.
And the mkPacket helpers previously just for tests are moved into
non-test code to be used elsewhere to reduce duplication, doing the
checksum stuff automatically.
Updates #13038
=> tstest/natlab/vnet: add more tests

ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go
The `LocalBackend`'s state machine starts in `NoState` and soon transitions to `NeedsLogin` if there's no auto-start profile, with the `profileManager` starting with a new empty profile. Notably, entering the `NeedsLogin` state blocks engine updates. We expect the user to transition out of this state by logging in interactively, and we set `WantRunning` to `true` when `controlclient` enters the `StateAuthenticated` state.
While our intention is correct, and completing an interactive login should set `WantRunning` to `true`, our assumption that logging into the current Tailscale profile is the only way to transition out of the `NeedsLogin` state is not accurate. Another common transition path includes an explicit profile switch (via `LocalBackend.SwitchProfile`) or an implicit switch when …
=> ipn/ipnlocal: set WantRunning upon an interactive login, but not during a seamless renewal or a profile switch

net/tstun/wrap.go, net/tstun/wrap_test.go, wgengine/netstack/netstack.go, wgengine/netstack/netstack_test.go
Throughput improves substantially when measured via netstack loopback
(TS_DEBUG_NETSTACK_LOOPBACK_PORT).
Before (d21ebc2):
jwhited@i5-12400-2:~$ iperf3 -V -c 100.100.100.100
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  5.77 GBytes  4.95 Gbits/sec    0 sender
[  5]   0.00-10.01  sec  5.77 GBytes  4.95 Gbits/sec      receiver
After:
jwhited@i5-12400-2:~$ iperf3 -V -c 100.100.100.100
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  12.7 GBytes  10.9 Gbits/sec    0 sender
[  5]   0.00-10.00  sec  12.7 GBytes  10.9 Gbits/sec      receiver …
=> net/tstun,wgengine/netstack: implement TCP GRO for local services

net/dns/resolver/forwarder.go
Updates tailscale/tailscale#13314
Some users are reporting 'DNS unavailable' spurious (?) warnings, especially on Android:
https://old.reddit.com/r/Tailscale/comments/1f2ow3w/health_warning_dns_unavailable_on_tailscale/ https://old.reddit.com/r/Tailscale/comments/1f3l2il/health_warnings_dns_unavailable_what_does_it_mean/
I suspect this is caused by having a too low TimeToVisible setting on the Warnable, which triggers the unhealthy state during slow network transitions.
=> dns: increase TimeToVisible before DNS unavailable warning

ssh/tailssh/incubator.go, tailcfg/tailcfg.go
Introduces ssh-behavior-v2 node attribute to override ssh-behavior-v1.
Updates #11854
=> ssh/tailssh: add ability to force V2 behavior using new feature flag

ipn/ipnlocal/local.go, ipn/ipnlocal/serve.go, ipn/ipnlocal/serve_test.go
=> ipn/ipnlocal: fix race condition that results in a panic sending on a closed channel

tstest/natlab/vnet/vnet.go, tstest/natlab/vnet/vnet_test.go
And clean up some of the test helpers in the process.
Updates #13038
=> tstest/natlab/vnet: add DHCP tests, ignore DHCPv4 on v6-only networks

tailcfg/tailcfg.go
I should've bumped capver in 65fe0ba7b5 but forgot.
This lets us turn off the cryptokey routing change from control for
the affected panicky range of commits, based on capver.
Updates #13332
Updates tailscale/corp#20732
=> tailcfg: bump capver for earlier cryptokey panic fix [capver 106]

client/tailscale/acl.go
I was working on a downstream library to parse ACL rules. I noticed the Protocol field was missing in ACL rules and tests when parsing from the API or a file. I'm assuming this was just not needed on the client side and it's done correctly on the server-side :). This PR simply adds the missing fields to the type on the client, although they are unused fields in the source code.
=> Adding missing proto field in ACL parsing structures

cmd/tailscale/cli/debug.go
To dump runtime/debug.BuildInfo.
Updates #1866
=> cmd/tailscale/cli: add 'debug go-buildinfo' subcommand

util/syspolicy/internal/loggerx/logger.go, util/syspolicy/internal/metrics/metrics.go, util/syspolicy/internal/metrics/metrics_test.go, util/syspolicy/internal/metrics/test_handler.go, util/syspolicy/setting/errors.go, util/syspolicy/source/policy_reader.go, util/syspolicy/source/policy_reader_test.go, util/syspolicy/source/policy_source.go, util/syspolicy/source/policy_store_windows.go, util/syspolicy/source/policy_store_windows_test.go, util/syspolicy/source/test_store.go
We add package defining interfaces for policy stores, enabling creation of policy sources and reading settings from them. It includes a Windows-specific `PlatformPolicyStore` for GP and MDM policies stored in the Registry, and an in-memory `TestStore` for testing purposes.
We also include an internal package that tracks and reports policy usage metrics when a policy setting is read from a store. Initially, it will be used only on Windows and Android, as macOS, iOS, and tvOS report their own metrics. However, we plan to use it across all platforms eventually.
Updates #12687
=> util/syspolicy/source: add package for reading policy settings from external stores

cmd/stunstamp/stunstamp.go, cmd/stunstamp/stunstamp_default.go, cmd/stunstamp/stunstamp_linux.go
This adds both userspace and kernel timestamping.
Updates tailscale/corp#22114
=> cmd/stunstamp: implement ICMP{v6} probing

cmd/stunstamp/stunstamp.go, cmd/stunstamp/stunstamp_default.go, cmd/stunstamp/stunstamp_linux.go
=> cmd/stunstamp: use measureFn more consistently in naming/signatures

cmd/stunstamp/stunstamp.go
We've added more probe targets recently which has resulted in more timeouts behind restrictive NATs in localized testing that don't like how many flows we are creating at once. Not so much an issue for datacenter or cloud-hosted deployments.
Updates tailscale/corp#22114
=> cmd/stunstamp: increase probe jitter

ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go
This PR changes how `LocalBackend` handles interactive (initiated via `StartLoginInteractive`) and non-interactive (e.g., due to key expiration) logins, and when it sends the authURL to the connected clients.
Specifically,
- When a user initiates an interactive login by clicking Log In in the GUI, the LocalAPI calls `StartLoginInteractive`. If an `authURL` is available and hasn't expired, we immediately send it to all connected clients, suggesting them to open that URL in a browser. Otherwise, we send a login request to the control plane and set a flag indicating that an interactive login is in progress.
- When `LocalBackend` receives an `authURL` from the control plane, we check if it differs from the previous one and whether an interactive login is in progress. If either condition is …
=> ipn/ipnlocal: always send auth URL notifications when a user requests interactive login

control/controlclient/sign_supported.go, posture/serialnumber_ios.go, util/syspolicy/policy_keys.go
With the upcoming `syspolicy` changes, it's imperative that all policy setting keys are defined in the `syspolicy` package for proper registration. Otherwise, the corresponding policy settings will not be read.
This updates a couple of places where we still use string literals rather than `syspolicy` consts.
Updates #12687
=> control/controlclient,posture,util/syspolicy: use predefined syspolicy keys instead of string literals

ipn/ipnlocal/network-lock.go, ipn/ipnlocal/network-lock_test.go, tka/sig.go, tka/sig_test.go
When a rotation signature chain reaches a certain size, remove the oldest rotation signature from the chain before wrapping it in a new rotation signature.
Since all previous rotation signatures are signed by the same wrapping pubkey (node's own tailnet lock key), the node can re-construct the chain, re-signing previous rotation signatures. This will satisfy the existing certificate validation logic.
Updates #13185
=> tka: truncate long rotation signature chains

net/dns/osconfig.go, net/dns/osconfig_test.go, tstest/reflect.go
Discovered this while investigating the following issue; I think it's unrelated, but might as well fix it. Also, add a test helper for checking things that have an IsZero method using the reflect package.
Updates tailscale/support-escalations#55
Change-Id: I57b7adde43bcef9483763b561da173b4c35f49e2
=> net/dns: fix IsZero and Equal methods on OSConfig

cmd/systray/systray.go
When tailscaled restarts and our watch connection goes down, we get stuck in an infinite loop printing `ipnbus error: EOF` (which ended up consuming all the disk space on my laptop via the log file). Instead, handle errors in `watchIPNBus` and reconnect after a short delay.
Updates #1708
=> cmd/systray: handle reconnects to IPN bus

ipn/ipnserver/server.go
We no longer need this on Windows, and it was never required on other platforms. It just results in more short-lived connections unless we use HTTP/2.
Updates tailscale/corp#18342
=> ipn/ipnserver: remove IdleTimeout

k8s-operator/sessionrecording/hijacker.go, k8s-operator/sessionrecording/hijacker_test.go, sessionrecording/connect.go
When a kubectl exec/ Tailscale SSH session needs to be recorded, the node (kube operator or SSH server) attempts to connect to a list of matching tsrecorder instances till it succeeds connecting to one (if at all). Log the address of the successfully connected recorder, so that if multiple recorders match, users know where the recording was sent to.
I have tested that the expected log line appears for both Tailscale SSH and kubectl exec session recording.
How it looks in logs (kubectl exec session recording):
```
{"level":"info","ts":"2024-09-05T06:49:09Z","logger":"apiserver-proxy","msg":"Connected to recorder at [fd7a:115c:a1e0::4d01:537d]:80"}
```
Updates tailscale/corp#19821
=> sessionrecording,ssh/tailssh,k8s-operator: log connected recorder address

net/dns/manager_windows.go
We already disable dynamic updates by setting `DisableDynamicUpdate` to `1` for the Tailscale interface. However, this does not prevent non-dynamic DNS registration from happening when `ipconfig /registerdns` runs and in similar scenarios. Notably, `dns/windowsManager.SetDNS` runs `ipconfig /registerdns`, triggering DNS registration for all interfaces that do not explicitly disable it.
In this PR, we update `dns/windowsManager.disableDynamicUpdates` to also set `RegistrationEnabled` to `0`.
Fixes #13411
=> net/dns: disable DNS registration for Tailscale interface on Windows

ipn/ipnlocal/dnsconfig_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
This mimics having Tailscale in the 'Stopped' state by programming an empty DNS configuration when the current node key is expired.
Updates tailscale/support-escalations#55
Change-Id: I68ff4665761fb621ed57ebf879263c2f4b911610
=> ipn/ipnlocal: don't program system DNS when node key is expired

cmd/stunstamp/stunstamp.go
We started out with a single protocol & port, now it's many.
=> cmd/stunstamp: add protocol context to timeout logs

util/linuxfw/detector.go, util/linuxfw/iptables.go
When the desired netfilter mode was unset, we would always try to use the `iptables` binary. In such cases if iptables was not found, tailscaled would just crash as seen in https://github.com/tailscale/tailscale/issues/13440. To work around this, in those cases check if the `iptables` binary even exists and if it doesn't fall back to the nftables implementation.
Verified that it works on stock Ubuntu 24.04.
Updates https://github.com/tailscale/tailscale/issues/5621
Updates https://github.com/tailscale/tailscale/pull/8555
Updates https://github.com/tailscale/tailscale/pull/8762
Fixes https://github.com/tailscale/tailscale/issues/13440
=> util/linuxfw: fall back to nftables when iptables not found

derp/derp_client.go, derp/derp_test.go
In prep for reducing mutex contention on Server.mu.
Updates #3560
=> derp: add new concurrent server benchmark

tailcfg/tailcfg.go
Add a node attr for enabling SSH environment variable handling logic.
Updates https://github.com/tailscale/corp/issues/22775
=> tailcfg: add node attr for SSH environment variables

net/netcheck/netcheck.go, net/netcheck/netcheck_test.go, wgengine/magicsock/magicsock.go
netcheck.Client.GetReport() applies its own deadlines. This 2s deadline was causing GetReport() to never fall back to HTTPS/ICMP measurements as it was shorter than netcheck.stunProbeTimeout, leaving no time for fallbacks.
Updates #13394
=> wgengine/magicsock: remove redundant deadline from netcheck report call

flake.nix, go.mod, gokrazy/go.mod, gokrazy/natlabapp.arm64/builddir/github.com/gokrazy/kernel.arm64/go.mod, gokrazy/natlabapp.arm64/builddir/tailscale.com/go.mod, gokrazy/natlabapp/builddir/tailscale.com/go.mod, gokrazy/natlabapp/builddir/tailscale.com/go.sum, gokrazy/tsapp/builddir/tailscale.com/go.mod
This un-breaks vim-go (which doesn't understand "go 1.23") and allows the natlab tests to work in a Nix shell (by adding the "qemu-img" and "mkfs.ext4" binaries to the shell). These binaries are available even on macOS, as I'm testing on my M1 Max.
Updates #13038
Change-Id: I99f8521b5de93ea47dc33b099d5b243ffc1303da
=> gokrazy, various: use point versions of Go and update Nix deps

safeweb/http.go
This is mainly intended to make it a little easier to drop in safeweb as a
replacement for existing http.Server use. What do you think?
Updates #13497
Change-Id: I398e9fa58ad0b9dc799ea280c9c7a32150150ee4
=> safeweb: add a ListenAndServe method to the Server type

net/dns/resolver/forwarder.go, net/dns/resolver/forwarder_test.go
mdnsResponder at least as of macOS Sequoia does not find NXDOMAIN responses to these dns-sd PTR queries acceptable unless they include the question section in the response. This was found debugging #13511, once we turned on additional diagnostic reporting from mdnsResponder we witnessed:
```
Received unacceptable 12-byte response from 100.100.100.100 over UDP via utun6/27 -- id: 0x7F41 (32577), flags: 0x8183 (R/Query, RD, RA, NXDomain), counts: 0/0/0/0,
```
If the response includes a question section, the resposnes are acceptable, e.g.:
```
Received acceptable 59-byte response from 8.8.8.8 over UDP via en0/17 -- id: 0x2E55 (11861), flags: 0x8183 (R/Query, RD, RA, NXDomain), counts: 1/0/0/0,
```
This may be contributing to an issue under diagnosis in #13511 wherein some combination of …
=> net/dns/resolver: fix dns-sd NXDOMAIN responses from quad-100

tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_view.go
Add an `AcceptEnv` field to `SSHRule`. This will contain the collection of environment variable names / patterns that are specified in the `acceptEnv` block for the SSH rule within the policy file. This will be used in the tailscale client to filter out unacceptable environment variables.
Updates: https://github.com/tailscale/corp/issues/22775
=> tailcfg: add AcceptEnv field to SSHRule

.github/workflows/checklocks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker-file-build.yml, .github/workflows/flakehub-publish-tagged.yml, .github/workflows/golangci-lint.yml, .github/workflows/govulncheck.yml, .github/workflows/installer.yml, .github/workflows/kubemanifests.yaml, .github/workflows/ssh-integrationtest.yml, .github/workflows/test.yml, .github/workflows/update-flake.yml, .github/workflows/update-webclient-prebuilt.yml, .github/workflows/webclient.yml
Pin actions/checkout usage to latest 3.x or 4.x as appropriate. These were previously pointing to `@4` or `@3` which pull in the latest versions at these tags as they are released, with the potential to break our workflows if a breaking change or malicious version for either of these streams are released.
Changing this to a pinned version also means that dependabot will keep this in the pinend version format (e.g., referencing a SHA) when it opens a PR to bump the dependency.
=> .github: pin actions/checkout to latest v3 or v4 as appropriate

.github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml, .github/workflows/test.yml
Pin actions/checkout usage to latest 5.x. These were previously pointing to `@4` which pulls in the latest v4 as they are released, with the potential to break our workflows if a breaking change or malicious version on the `@4` stream is ever pushed.
Changing this to a pinned version also means that dependabot will keep this in the pinend version format (e.g., referencing a SHA) when it opens a PR to bump the dependency.
The breaking change between v4 and v5 is that v5 requires Node 20 which should be a non-issue where it is used.
=> .github: pin actions/setup-go usage to latest 5.x

.github/workflows/codeql-analysis.yml
Pin codeql actions usage to latest 3.x. These were previously pointing to `@2` which pulls in the latest v2 as they are released, with the potential to break our workflows if a breaking change or malicious version on the `@2` stream is ever pushed.
Changing this to a pinned version also means that dependabot will keep this in the pinend version format (e.g., referencing a SHA) when it opens a PR to bump the dependency.
The breaking change between v2 and v3 is that v3 requires Node 20 which is a non-issue as we are running this on ubuntu latest.
=> .github: pin codeql actions to latest 3.x

.github/workflows/govulncheck.yml, .github/workflows/test.yml
Use slackapi/slack-github-action across the board and pin to latest 1.x. Previously we were referencing the 1.27.0 tag directly which is vulnerable to someone replacing that version tag with malicious code.
Replace usage of ruby/action-slack with slackapi/slack-github-action as the latter is the officially supported action from slack.
=> .github: use and pin slackapi/slack-github-action to latest 1.x

.github/workflows/test.yml
Update and pin actions/cache usage to latest 4.x. These were previously pointing to `@3` which pulls in the latest v3 as they are released, with the potential to break our workflows if a breaking change or malicious version on the `@3` stream is ever pushed.
Changing this to a pinned version also means that dependabot will keep this in the pinned version format (e.g., referencing a SHA) when it opens a PR to bump the dependency.
The breaking change between v3 and v4 is that v4 requires Node 20 which should be a non-issue where this is run.
=> .github: update and pin actions/cache to latest 4.x

.github/workflows/test.yml
Update and pin actions/upload-artifact usage to latest 4.x. These were previously pointing to @3 which pulls in the latest v3 as they are released, with the potential to break our workflows if a breaking change or malicious version on the @3 stream is ever pushed.
Changing this to a pinned version also means that dependabot will keep this in the pinned version format (e.g., referencing a SHA) when it opens a PR to bump the dependency.
=> .github: update and pin actions/upload-artifact to latest 4.x

.github/workflows/test.yml
Pin re-actors/alls-green usage to latest 1.x. This was previously pointing to `@release/v2` which pulls in the latest changes from this branch as they are released, with the potential to break our workflows if a breaking change or malicious version on this stream is ever pushed.
Changing this to a pinned version also means that dependabot will keep this in the pinned version format (e.g., referencing a SHA) when it opens a PR to bump the dependency.
=> .github: pin re-actors/alls-green to latest 1.x

release/dist/synology/pkgs.go, release/dist/synology/targets.go, version/mkversion/mkversion.go
Add separate builds for DSM7.2 for synology so that we can encode separate versioning information in the INFO file to distinguish between the two.
Fixes https://github.com/tailscale/corp/issues/22908
=> {release,version}: add DSM7.2 specific synology builds

tool/gocross/gocross-wrapper.sh, tool/gocross/toolchain.go
So it doesn't delete and re-pull when switching between branches.
Updates tailscale/corp#17686
=> tool/gocross: make gocross-wrapper.sh keep multiple Go toolchains around

cmd/tailscaled/tailscaled.go, go.mod, health/health.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/loglines_test.go, ipn/ipnlocal/peerapi_test.go, ipn/ipnlocal/serve_test.go, ipn/ipnlocal/state_test.go, ipn/localapi/localapi.go, ipn/localapi/localapi_test.go, metrics/multilabelmap.go, net/tstun/wrap.go, net/tstun/wrap_test.go, ssh/tailssh/tailssh_test.go, tsd/tsd.go, tsnet/tsnet.go, tsnet/tsnet_test.go, util/usermetric/usermetric.go, util/usermetric/usermetric_test.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/netstack/netstack_test.go, wgengine/userspace.go, wgengine/userspace_ext_test.go, wgengine/userspace_test.go, wgengine/watchdog_test.go
This PR changes usermetrics to be non-global, it does not change any or introduce new metrics.
I've tried to make each commit meaningful and it might be easier to review it commit by commit.
It is mostly patching usermetrics through in the same way as the HealthTracker.
This PR is pulled out of #13309.
Updates #13420
=> util/usermetrics: make usermetrics non-global

wgengine/magicsock/magicsock.go
When querying for an exit node suggestion, occasionally it triggers a new report concurrently with an existing report in progress. Generally, there should always be a recent report or one in progress, so it is redundant to start one there, and it causes concurrency issues.
Fixes #12643
Change-Id: I66ab9003972f673e5d4416f40eccd7c6676272a5
=> wgengine/magicsock: only used cached results for GetLastNetcheckReport

metrics/multilabelmap.go, metrics/multilabelmap_test.go
This breaks its ability to be used as an expvar and is blocking a trunkd deploy. Revert for now, and add a test to ensure that we don't break it in a future change.
Updates #13550
Change-Id: I1f1221c257c1de47b4bff0597c12f8530736116d
=> metrics: revert changes to MultiLabelMap's String method

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
Like Linux, macOS will reply to sendto(2) with EPERM if the firewall is currently blocking writes, though this behavior is like Linux undocumented. This is often caused by a faulting network extension or content filter from EDR software.
Updates #11710
Updates #12891
Updates #13511
=> wgengine/magicsock: fix check for EPERM on macOS

ssh/tailssh/accept_env.go, ssh/tailssh/accept_env_test.go
Add logic for parsing and matching against our planned format for AcceptEnv values. Namely, this supports direct matches against string values and matching where * and ? are treated as wildcard characters which match against an arbitrary number of characters and a single character respectively.
Actually using this logic in non-test code will come in subsequent changes.
Updates https://github.com/tailscale/corp/issues/22775
=> ssh/tailssh: add logic for matching against AcceptEnv patterns

client/web/web.go, cmd/tailscale/cli/up.go, ipn/ipnlocal/local.go, net/netutil/routes.go, net/tsaddr/tsaddr.go, net/tsaddr/tsaddr_test.go
This PR moves and reuses some common exit route checks to `tsaddr` and hunts down uses and redefinitions of commonly used prefixes and checks related to exit nodes.
I did notice that in various parts of the codebase we do slightly inconsistent checks:
when checking if a route is an exit node, sometimes we do a full compare to `0.0.0.0/0` and sometimes we just check
if the bits is 0. I've added one testcase demonstrating the difference, see comment.
when checking if there are exit nodes, we are also sometimes checking if either (`0.0.0.0/0` _and_ `::/0`) or one of (`0.0.0.0/0` _or_ `::/0`) are present.
I dont address this in this PR, just an observation that might some times be relevant.
=> net/tsaddr: add WithoutExitRoutes and IsExitRoute

net/captivedetection/captivedetection.go
Updates tailscale/tailscale#1634
Logs from some iOS users (see `BUG-09a33c527e6c3b613b7334b5c232bc65c8fd8975f6aac406e1af1f406b642e3f-20240926003847Z-714344129d81d7e3`) indicate that we're pointlessly performing captive portal detection on certain interfaces named `ipsec*`. These are tunnels with the cellular carrier that do not offer Internet access, and are only used to provide internet calling functionality (VoLTE / VoWiFi).
```
attempting to do captive portal detection on interface ipsec1
attempting to do captive portal detection on interface ipsec6
```
This PR excludes interfaces with the `ipsec` prefix from captive portal detection.
=> net/captivedetection: exclude ipsec interfaces from captive portal detection

cmd/containerboot/main.go, cmd/containerboot/services.go, cmd/containerboot/services_test.go, cmd/containerboot/settings.go, kube/egressservices/egressservices.go, kube/egressservices/egressservices_test.go, kube/kubeclient/client.go, util/linuxfw/iptables_for_svcs.go, util/linuxfw/iptables_for_svcs_test.go, util/linuxfw/iptables_runner.go, util/linuxfw/nftables_for_svcs.go, util/linuxfw/nftables_for_svcs_test.go, util/linuxfw/nftables_runner.go, wgengine/router/router_linux_test.go
This is first part of the work to allow running multiple replicas of the Kubernetes operator _egress_ proxies per tailnet service + to allow exposing multiple tailnet services via each proxy replica.
This expands the existing iptables/nftables-based proxy configuration mechanism.
A proxy can now be configured to route to one or more tailnet targets via a (mounted) config file that, for each tailnet target, specifies:
- the target's tailnet IP or FQDN
- mappings of container ports to which cluster workloads will send traffic to tailnet target ports where the traffic should be forwarded.
Example configfile contents (this will be created by the operator, not users):
```json
{
"some-svc": {"tailnetTarget":{"fqdn":"foo.tailnetxyz.ts.net","ports"{"tcp:4006:80":{"protocol":"tcp","matchPort":4006, …
```
=> cmd/containerboot,kube,util/linuxfw: configure kube egress proxies to route to 1+ tailnet targets

cmd/tsidp/tsidp.go
To better control where the tsnet state is being stored.
Updates #10263
=> cmd/tsidp: add --dir flag

cmd/tailscale/cli/debug.go, control/controlhttp/client.go, control/controlhttp/constants.go
This pulls out the clock and forceNoise443 code into methods on the
Dialer as cleanup in its own commit to make a future change less
distracting.
Updates #13597
=> control/controlhttp: factor out some code in prep for future change

net/portmapper/portmapper.go
=> net/portmapper: don't treat 0.0.0.0 as a valid IP

net/captivedetection/captivedetection.go
Updates tailscale/tailscale#1634
Updates tailscale/tailscale#13265
Captive portal detection uses a custom `net.Dialer` in its `http.Client`. This custom Dialer ensures that the socket is bound specifically to the Wi-Fi interface. This is crucial because without it, if any default routes are set, the outgoing requests for detecting a captive portal would bypass Wi-Fi and go through the default route instead.
The Dialer did not have a Timeout property configured, so the default system timeout was applied. This caused issues in #13265, where we attempted to make captive portal detection requests over an IPsec interface used for Wi-Fi Calling. The call to `connect()` would fail and remain blocked until the system timeout (approximately 1 minute) was reached.
In #13598, I simply excluded the …
=> net/captivedetection: set Timeout on net.Dialer

control/controlclient/noise.go, control/controlhttp/client.go, control/controlhttp/constants.go, net/dnscache/dnscache.go, tstest/integration/integration_test.go
**[3 commits]**
1eaad7d3deb regressed some tests in another repo that were starting up
a control server on `http://127.0.0.1:nnn`. Because there was no https
running, and because of a bug in 1eaad7d3deb (which ended up checking
the recently-dialed-control check twice in a single dial call), we
ended up forcing only the use of TLS dials in a test that only had
plaintext HTTP running.
Instead, plumb down support for explicitly disabling TLS fallbacks and
use it only when running in a test and using `http` scheme control
plane URLs to 127.0.0.1 or localhost.
This fixes the tests elsewhere.
Updates #13597
=> control/control{client,http}: don't noise dial localhost:443 in http-only tests

net/dns/resolver/forwarder.go
Updates tailscale/tailscale#6148
This is the result of some observations we made today with @raggi. The DNS over HTTPS client currently doesn't cap the number of connections it uses, either in-use or idle. A burst of DNS queries will open multiple connections. Idle connections remain open for 30 seconds (this interval is defined in the dohTransportTimeout constant). For DoH providers like NextDNS which send keep-alives, this means the cellular modem will remain up more than expected to send ACKs if any keep-alives are received while a connection remains idle during those 30 seconds. We can set the IdleConnTimeout to 10 seconds to ensure an idle connection is terminated if no other DNS queries come in after 10 seconds. Additionally, we can cap the number of connections to 1. This ensures …
=> net/dns: tweak DoH timeout, limit MaxConnsPerHost, require TLS 1.3

tstest/test-wishlist.md, wf/firewall.go
When an Exit Node is used, we create a WFP rule to block all inbound and outbound traffic, along with several rules to permit specific types of traffic. Notably, we allow all inbound and outbound traffic to and from `LocalRoutes` specified in `wgengine/router.Config`. The list of allowed routes always includes routes for internal interfaces, such as loopback and virtual Hyper-V/WSL2 interfaces, and may also include LAN routes if the "Allow local network access" option is enabled. However, these permitting rules do not allow link-local multicast on the corresponding interfaces. This results in broken mDNS/LLMNR, and potentially other similar issues, whenever an exit node is used.
In this PR, we update `(*wf.Firewall).UpdatePermittedRoutes()` to create rules allowing outbound and inbound …
=> wf/firewall: allow link-local multicast for permitted local routes when the killswitch is on on Windows

wgengine/magicsock/magicsock.go
The new logging in 2dd71e64ac11675e is spammy at shutdown:
Receive func ReceiveIPv6 exiting with error: *net.OpError, read udp [::]:38869: raw-read udp6 [::]:38869: use of closed network connection
Receive func ReceiveIPv4 exiting with error: *net.OpError, read udp 0.0.0.0:36123: raw-read udp4 0.0.0.0:36123: use of closed network connection
Skip it if we're in the process of shutting down.
Updates #10976
=> wgengine/magicsock: avoid log spam from ReceiveFunc on shutdown

control/controlclient/direct.go
Not just its code.
Updates tailscale/corp#23584
=> control/controlclient: include HTTP status string in error message too

logpolicy/logpolicy.go
Updates tailscale/tailscale#3363
We know `log.tailscale.io` supports TLS 1.3, so we can enforce its usage in the client to shake some bytes off the TLS handshake each time a connection is opened to upload logs.
=> logpolicy: force TLS 1.3 handshake

cmd/containerboot/forwarding.go, cmd/containerboot/main.go, cmd/containerboot/services.go, util/linuxfw/iptables_runner.go, util/linuxfw/iptables_runner_test.go, util/linuxfw/nftables_for_svcs_test.go, util/linuxfw/nftables_runner.go, util/linuxfw/nftables_runner_test.go, wgengine/router/router_linux_test.go
This PR ensures that when the kube egress proxies firewall rules are refreshed, we don't end up with more than one SNAT rule for a match destination.
The [NetfilterRunner#AddSNATRuleForDst](https://github.com/tailscale/tailscale/blob/6de6ab015f3edc18565aecb9609467bab88a8ed7/util/linuxfw/nftables_runner.go#L564)  (currently only used from containerboot, mostly in kube proxy setups) method was adding a new rule each time it was called including:
- if a rule already existed
- if a rule matching the destination, but with different desired source IP already existed
This was causing issues especially for the in-progress egress HA proxies work, where the rules are now refreshed more frequently, so more redundant rules were being created.
- only creates the rule if it doesn't already exist
- if a …
=> cmd/containerboot,util/linuxfw: ensure that only one SNAT rule exists for a given match destination

cmd/tailscale/cli/network-lock.go
Fixes tailscale/corp#11355
Before, with unusable disablement secrets on init failure:
```
➜  ~ tailscale lock init --gen-disablement-for-support --gen-disablements 10 --confirm tlpub:c5ddcf8264c93419c995bd19a047cd8b6cb41af6d993e631958aabe2bafd4927 tlpub:f32054d78442a6a6cb51479093ddf657b5c3e90572f27ee228d62e9ed7b6be7d
Warning: client version "1.74.1-t0ca17be4a" != tailscaled server version "1.75.47-t77832553e-g425477bf6"
You are initializing tailnet lock with the following trusted signing keys:
- tlpub:c5ddcf8264c93419c995bd19a047cd8b6cb41af6d993e631958aabe2bafd4927 (25519 key)
- tlpub:f32054d78442a6a6cb51479093ddf657b5c3e90572f27ee228d62e9ed7b6be7d (25519 key)
10 disablement secrets have been generated and are printed below. Take note of them now, they WILL NOT be shown again. …
```
=> cmd/tailscale/cli: don't print disablement secrets if init fails

safeweb/http.go, safeweb/http_test.go
Extend safeweb.Config with the ability to pass a http.Server that
safeweb will use to server traffic.
Updates corp#8207
Signed-off-by: Patrick O'Doherty <patrick@tailscale.com>
=> safeweb: allow passing http.Server in safeweb.Config

tool/gocross/gocross-wrapper.sh
To avoid warning:
find: warning: you have specified the global option -maxdepth after the argument -type, but global options are not positional, i.e., -maxdepth affects tests specified before it as well as those specified after it.  Please specify global options before other arguments.
Fixes tailscale/corp#23689
=> tool/gocross: fix argument order to find

cmd/tailscale/cli/cli_test.go, types/key/nl.go
Fixes tailscale/corp#19442
The change is done by switching the logic flow such that checking `tlpub:` is the fallback and its error message is the one that falls through.
Test was updated and passes with the new code. Manual testing also seems good: if you provide `nlpub:` it still works but the error for `foo:bar` tells you to use `tlpub:`
```
➜  tailscale git:(erisa/tlpub-prefix-warning) ./tool/go run ./cmd/tailscale lock init foo:bar
Warning: client version "1.75.84-t6d8acc267" != tailscaled server version "1.75.72-t1f8eea53a-ge56e13a96"
parsing key 1: key hex string doesn't have expected type prefix tlpub:
exit status 1
➜  tailscale git:(erisa/tlpub-prefix-warning) ./tool/go run ./cmd/tailscale lock init nlpub:bar
Warning: client version "1.75.84-t6d8acc267" != tailscaled server …
```
=> types/key: use tlpub: in error message

cmd/k8s-operator/deploy/crds/tailscale.com_proxygroups.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/egress-eps.go, cmd/k8s-operator/egress-eps_test.go, cmd/k8s-operator/egress-services.go, cmd/k8s-operator/egress-services_test.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/svc.go, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_proxygroup.go
This PR ensures that, for ProxyGroups that are for egress, a ConfigMap for egress services config gets created.
Also contains a bunch of smaller fixes:
- ensures that if a ProxyGroup does not exist (i.e it was deleted) Configured condition is removed from the user-created Service
- fixes the label selectors for egress service resources to match the currently applied labels
- only reconciles ProxyGroup _state_ Secrets
- ensures that the existing Services reconciler does not look at ExternalName Services for ProxyGroup
I have e2e tested this against a bunch of edge cases
=> cmd/k8s-operator,k8s-operator: create ConfigMap for egress services + small fixes for egress services

types/lazy/deferred.go, types/lazy/deferred_test.go
It is sometimes necessary to defer initialization steps until the first actual usage or until certain prerequisites have been met. For example, policy setting and policy source registration should not occur during package initialization. Instead, they should be deferred until the `syspolicy` package is actually used. Additionally, any errors should be properly handled and reported, rather than causing a panic within a package’s `init` function.
In this PR, we add `DeferredInit` to facilitate the registration and invocation of deferred initialization functions.
Updates #12687
=> types/lazy: add DeferredInit type

cmd/containerboot/settings.go
Rearrange conditionals to reduce indentation and make it a bit easier to read the logic. Also makes some error message updates for better consistency with the recent decision around capitalising resource names and the upcoming addition of config secrets.
=> cmd/containerboot: simplify k8s setup logic

cmd/containerboot/main.go, cmd/containerboot/services.go, cmd/containerboot/settings.go, cmd/k8s-operator/egress-eps.go, cmd/k8s-operator/egress-eps_test.go, cmd/k8s-operator/proxygroup_specs.go, kube/egressservices/egressservices.go
Currently egress Services for ProxyGroup only work for Pods and Services with IPv4 addresses. Ensure that it works on dual stack clusters by reading proxy Pod's IP from the `.status.podIPs` list that always contains both IPv4 and IPv6 address (if the Pod has them) rather than `.status.podIP` that, in a dual stack cluster, could contain the IPv6 address of the Pod.
Updates tailscale/tailscale#13406
=> cmd/{k8s-operator,containerboot},kube/egressservices: fix Pod IP check for dual stack clusters

cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-operator/proxygroup_test.go
As discussed in #13684, base the ProxyGroup's proxy definitions on the same scaffolding as the existing proxies, as defined in proxy.yaml
Updates #13406
=> cmd/k8s-operator: base ProxyGroup StatefulSet on common proxy.yaml definition

cmd/k8s-operator/egress-eps.go, cmd/k8s-operator/egress-eps_test.go
Ensure that `.status.podIPs` field is used to select Pod's IP in all reconcilers.
Updates tailscale/tailscale#13406
=> cmd/k8s-operator: fix Pod IP selection

cmd/k8s-operator/egress-services-readiness.go, cmd/k8s-operator/egress-services-readiness_test.go, cmd/k8s-operator/egress-services.go, cmd/k8s-operator/operator.go, k8s-operator/apis/v1alpha1/types_connector.go
Set a readiness condition on ExternalName Services that define a tailnet target to route cluster traffic to via a ProxyGroup's proxies. The condition is set to true if at least one proxy is currently set up to route.
This is implemented as another reconciler that reconciles the ExternalName Services. It determines readiness by checking how many of the current proxy Pod IPs are found on the EndpointSlice for the service.
**What the condition looks like:**
If none of the proxies are able to route traffic:
```
status:
conditions:
- lastTransitionTime: "2024-10-09T13:17:45Z"
message: 0 out of 6 replicas are ready to route traffic
reason: NotReadyToRouteTraffic
status: "False"
type: TailscaleEgressSvcReady
```
If one has been configured to route traffic:
```
status:
conditions:
- …
```
=> cmd/k8s-operator,k8s-operator/apis: set a readiness condition on egress Services for ProxyGroup

syncs/syncs.go
Add Keys, Values, and All to iterate over
all keys, values, and entries, respectively.
Updates #11038
=> syncs: add iterators to Map

util/vizerror/vizerror.go, util/vizerror/vizerror_test.go
These new functions allow constructing vizerrors that combine a message appropriate for display to users with a wrapped underlying error.
=> util/vizerror: add WrapWithMessage(F)

syncs/syncs.go
One primary purpose of WithLock is to mutate the underlying map. However, this can lead to a panic if it happens to be nil. Thus, always allocate a map before passing it to f.
Updates tailscale/corp#11038
=> syncs: allocate map with Map.WithLock

taildrop/taildrop.go
PR #13756 switched from using syncs.Map.Range to the All iterator.
However, this affects the scope of a defer.
Updates #11038
=> taildrop: fix defer in loop

safesocket/safesocket_ps.go, tstest/iosdeps/iosdeps_test.go
There's never a tailscaled on iOS. And we can't run child processes to
look for it anyway.
Updates tailscale/corp#20099
=> safesocket: don't depend on go-ps on iOS

tsnet/tsnet_test.go
Updates #13773
Change-Id: I95e03eb6aef1639bd4a2efd3a415e2c10cdebc5a
=> tsnet: fix panic caused by logging after test finishes

net/netcheck/netcheck.go
=> net/netcheck: fix netcheck cli-triggered nil pointer deref

client/tailscale/tailscale.go, cmd/get-authkey/main.go, cmd/k8s-operator/operator.go, cmd/tailscale/cli/up.go, tsnet/tsnet.go
This will allow us to distinguish OSS client activity from our other Go client, and will also allow us to distinguish k8s activity.
Updates tailscale/corp#23838
=> client/tailscale,cmd/k8s-operator: set distinct User-Agents

net/dns/resolver/forwarder.go, net/dns/resolver/forwarder_test.go, net/dns/resolver/tsdns.go, net/dns/resolver/tsdns_test.go
[3 commits]
As per the docstring, `(*forwarder).forwardWithDestChan` should either send to `responseChan
` and returns nil, or returns a non-nil error (without sending to the channel). However, this does not hold when all upstream DNS servers replied with an error.
We've been handling this special error path in `(*Resolver).Query` but not in `(*Resolver).HandlePeerDNSQuery`.
As a result, SERVFAIL responses from upstream servers were being converted into HTTP 503 responses,
instead of being properly forwarded as SERVFAIL within a successful HTTP response, as per [RFC 8484, section 4.2.1](https://datatracker.ietf.org/doc/html/rfc8484#section-4.2.1):
> DNS response codes indicate either success or failure for the DNS
> query.  A successful HTTP response with a 2xx status code (see
> [Section …
=> net/dns/resolver: forward SERVFAIL responses over PeerDNS

net/connstats/stats.go, wgengine/magicsock/derp.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go
connstats currently increments the packet counter whenever it is called
to store a length of data, however when udp batch sending was introduced
we pass the length for a series of packages, and it is only incremented
ones, making it count wrongly if we are on a platform supporting udp
batches.
=> {net/connstats,wgengine/magicsock}: fix packet counting in connstats

net/netcheck/netcheck.go
=> net/netcheck: fix netcheck cli-triggered nil pointer deref (#13782)

build_docker.sh, hostinfo/hostinfo.go, hostinfo/hostinfo_container_linux_test.go, hostinfo/hostinfo_linux_test.go, tailcfg/tailcfg.go
Our existing container-detection tricks did not work on Kubernetes, where Docker is no longer used as a container runtime. Extends the existing go build tags for containers to the other container packages and uses that to reliably detect builds that were created by Tailscale for use in a container. Unfortunately this doesn't necessarily improve detection for users' custom builds, but that's a separate issue.
Updates #13825
Note: the `hostinfo` package value is [set to](https://github.com/tailscale/tailscale/blob/a8f9c0d6e40a99e091e06572cd5e9b20db7baa21/tsnet/tsnet.go#L288) "tsnet" for any `tsnet` applications, which is a little awkward because it's not mutually exclusive with being in a container. I think it would also be reasonable to try to untangle that, but this change seems like a …
=> hostinfo,build_docker.sh,tailcfg: more reliably detect being in a container

cmd/derpprobe/derpprobe.go
For a customer that wants to run their own DERP prober, let's add a /healthz endpoint that can be used to monitor derpprobe itself.
Updates #6526
Change-Id: Iba315c999fc0b1a93d8c503c07cc733b4c8d5b6b
=> cmd/derpprobe: add /healthz endpoint

util/syspolicy/internal/internal.go, util/syspolicy/rsop/change_callbacks.go, util/syspolicy/rsop/resultant_policy.go, util/syspolicy/rsop/resultant_policy_test.go, util/syspolicy/rsop/rsop.go, util/syspolicy/rsop/store_registration.go, util/syspolicy/setting/policy_scope.go, util/syspolicy/setting/setting.go, util/syspolicy/source/test_store.go
In this PR we add `syspolicy/rsop` package that facilitates policy source registration and provides access to the resultant policy merged from all registered sources for a given scope.
Updates #12687
=> util/syspolicy: add rsop package that provides access to the resultant policy

wgengine/magicsock/magicsock_test.go
While looking at deflaking TestTwoDevicePing/ping_1.0.0.2_via_SendPacket,
there were a bunch of distracting:
WARNING: (non-fatal) nil health.Tracker (being strict in CI): ...
This pacifies those so it's easier to work on actually deflaking the test.
Updates #11762
Updates #11874
=> wgengine/magicsock: fix CI-only test warning of missing health tracker

tool/gocross/autoflags.go
Updates ENG-5321
Allow gocross to build a static library for the Apple TV Simulator.
=> tool/gocross: add support for tvOS Simulator

derp/derp_server.go
Write timeouts can be indicative of stalled TCP streams. Understanding changes in the rate of such events can be helpful in an ops context.
Updates tailscale/corp#23668
=> derp: add sclient write deadline timeout metric

ipn/ipnauth/actor.go, ipn/ipnauth/ipnauth_notwindows.go, ipn/ipnauth/test_actor.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnserver/actor.go, ipn/localapi/localapi.go, ipn/localapi/localapi_test.go
We add the `ClientID()` method to the `ipnauth.Actor` interface and updated `ipnserver.actor` to implement it. This method returns a unique ID of the connected client if the actor represents one. It helps link a series of interactions initiated by the client, such as when a notification needs to be sent back to a specific session, rather than all active sessions, in response to a certain request.
We also add `LocalBackend.WatchNotificationsAs` and `LocalBackend.StartLoginInteractiveAs` methods, which are like `WatchNotifications` and `StartLoginInteractive` but accept an additional parameter specifying an `ipnauth.Actor` who initiates the operation. We store these actor identities in `watchSession.owner` and `LocalBackend.authActor`, respectively, and implement `LocalBackend.sendTo` and …
=> ipn/{ipnauth,ipnlocal,ipnserver}: send the auth URL to the user who started interactive login

net/netcheck/netcheck_test.go
=> net/netcheck: remove arbitrary deadlines from GetReport() tests

health/health.go, net/dns/manager.go, net/dns/resolved.go
Fixes tailscale/tailscale#13871
- Drops the legacy SysDNSOS subsystem in the health framework, as subsystems are deprecated.
- Adds two separate Warnables, with user-friendly errors for errors that might occur when either reading or setting the system DNS configuration. Unlike the previous subsystem errors, these two Warnables have their `DependsOn` set to `health.NetworkStatusWarnable`, meaning that if the network is down, the Warnables won't fire and no warning will be presented to the user if unhealthy.
=> health: remove SysDNSOS, add two Warnables for read+set system DNS config

cmd/tailscale/cli/netcheck.go, net/netcheck/netcheck.go, net/netcheck/netcheck_test.go
This allows us to print the time that a netcheck was run, which is useful in debugging.
Updates #10972
Change-Id: Id48d30d4eb6d5208efb2b1526a71d83fe7f9320b
=> net/netcheck: add a Now field to the netcheck Report

ipn/store/kubestore/store_kube.go, ipn/store/mem/store_mem.go
This PR changes kubestore to write tailscale state to memory (as well as a Secret) on writes and read from memory only. On startup state is loaded from Secret if any exists.
This should:
- fix bugs caused by temporary errors connecting to kube API server (see https://github.com/tailscale/tailscale/issues/13900#issuecomment-2439483086)
- improve performance
I've tested this extensively with various setups (upgrade, a precreated Secret, etc)
This PR just picks up https://github.com/tailscale/tailscale/pull/7673 with a few small fixes
Fixes #7671
Updates https://github.com/tailscale/tailscale/issues/12079
Updates https://github.com/tailscale/tailscale/issues/13900
=> ipn/store/kubestore: cache state in memory

ipn/store/kubestore/store_kube.go
Preloading of tailscale state from kube Secret should not error if the Secret does not exist.
Updates tailscale/tailscale#7671
=> ipn/store/kubestore: don't error if state cannot be preloaded because Secret does not exist

net/dns/resolvd.go
During resolv.conf update, old 'search' lines are cleared but '\n' is not deleted, leaving behind a new blank line on every update.
This adds 's' flag to regexp, so '\n' is included in the match and deleted when old lines are cleared.
Also, insert missing `\n` when updated 'search' line is appended to resolv.conf.
=> Fix blank lines being added to resolv.conf on OpenBSD

tstest/natlab/vnet/conf.go, tstest/natlab/vnet/conf_test.go, tstest/natlab/vnet/vnet.go
A simple implementation of latency and loss simulation, applied to writes to the ethernet interface of the NIC. The latency implementation could be optimized substantially later if necessary.
Updates #13355
=> tstest/natlab: add latency & loss simulation

tool/gocross/autoflags.go, tool/gocross/autoflags_test.go
trimpath can be inconvenient for IDEs and LSPs that do not always correctly handle module relative paths, and can also contribute to caching bugs taking effect. We rarely have a real need for trimpath of test produced binaries, so avoiding it should be a net win.
Updates #2988
=> tool/gocross: remove trimpath from test builds

ipn/ipnlocal/c2n.go
If the client cannot fetch a serial number, write a log message helping the user understand what happened. Also, don't just return the error immediately, since we still have a chance to collect network interface addresses.
Updates #5902
=> ipn/ipnlocal: log errors while fetching serial numbers

ipn/ipnlocal/local.go, tsnet/tsnet_test.go
Not confident this is the right way to expose this, so let's remote it for now.
=> ipn/ipnlocal: remove the primary routes gauge for now

cmd/tailscale/cli/cli.go, cmd/tailscale/cli/metrics.go, ipn/localapi/localapi.go
- `tailscale metrics print`: to show metric values in console
- `tailscale metrics write`: to write metrics to a file (with a tempfile & rename dance, which is atomic on Unix).
Also, remove the `TS_DEBUG_USER_METRICS` envknob as we are getting more confident in these metrics.
=> cmd/tailscale/cli: add 'tailscale metrics' command

tstest/tailmac/Swift/TailMac/TailMac.swift
updates tailscale/corp#24197
Generation of the Host.app path was erroneous and tailmac run would not work unless the pwd was tailmac/bin.  Now you can be able to invoke tailmac from anywhere.
Signed-off-by: Jonathan Nobels <jonathan@tailscale.com>
=> tstest/tailmac: fix Host.app path generation

tstest/tailmac/Swift/Common/Config.swift, tstest/tailmac/Swift/Common/TailMacConfigHelper.swift, tstest/tailmac/Swift/Host/HostCli.swift, tstest/tailmac/Swift/Host/VMController.swift, tstest/tailmac/Swift/TailMac/TailMac.swift
updates tailscale/corp#24197
tailmac run now supports the --share option which will allow you to specify a directory on the host which can be mounted in the guest using  mount_virtiofs vmshare local/path.
Signed-off-by: Jonathan Nobels <jonathan@tailscale.com>
=> tstest/tailmac: add support for mounting host directories in the guest

util/syspolicy/source/env_policy_store.go
=> util/syspolicy/source: use errors instead of github.com/pkg/errors

net/netcheck/netcheck.go, net/netcheck/netcheck_test.go
In an environment with unstable latency, such as upstream bufferbloat,
there are cases where a full netcheck could drop the prior preferred
DERP (likely home DERP) from future netcheck probe plans. This will then
likely result in a home DERP having a missing sample on the next
incremental netcheck, ultimately resulting in a home DERP move.
This change does not fix our overall response to highly unstable
latency, but it is an incremental improvement to prevent single spurious
samples during a full netcheck from alone triggering a flapping
condition, as now the prior changes to include historical latency will
still provide the desired resistance, and the home DERP should not move
unless latency is consistently worse over a 5 minute period.
Note that there is a nomenclature and semantics …
=> net/netcheck: ensure prior preferred DERP is always in netchecks

wgengine/magicsock/derp.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go
The user-facing metrics are intended to track data transmitted at the overlay network level, so we should not increment them for outgoing disco packages that go over DERP.
=> wgengine/magicsock: exclude disco from throughput metrics

net/tstun/wrap.go, net/tstun/wrap_test.go, util/usermetric/metrics.go, util/usermetric/usermetric.go, wgengine/magicsock/derp.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
Another take on #13637.
This required sharing the dropped packet metric between two packages (tstun and magicsock), so I've moved its definition to `util/usermetric`.
=> wgengine/magicsock: export packet drop metric for outbound errors

ipn/conf.go, tailcfg/tailcfg.go
Make it possible to advertise app connector via a new conffile field.
This is the first step towards #11113 
Updates tailscale/tailscale#11113
=> ipn: add app connector config knob to conffile

safeweb/http.go, safeweb/http_test.go
By counting "/" elements in the pattern we catch many scenarios, but not the root-level handler. If either of the patterns is "/", compare the pattern length to pick the right one.
=> safeweb: add support for "/" and "/foo" handler distinction

net/sockstats/sockstats_tsgo.go
Fixes tailscale/tailscale#13983
As @raggi pointed out, DefaultRouteInterface and Interface are set at different points in time. The map lookup in `setNetMon` should check whether the map contains a value for the interface name before getting the interface index. If it doesn't, it returns a zero value containing a pointer which will be nil in the zero value case, causing the panic.
=> net/sockstats: prevent crash in setNetMon

safeweb/http.go, safeweb/http_test.go
To allow more flexibility with CSPs, add a fully customizable `CSP` type that can be provided in `Config` and encodes itself into the correct format. Preserve the `CSPAllowInlineStyles` option as is today, but maybe that'll get deprecated later in favor of the new CSP field.
In particular, this allows for pages loading external JS, or inline JS with nonces or hashes (see
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_inline_script)
=> safeweb: add support for custom CSP

net/netcheck/netcheck_test.go
Add an explicit case for exercising preferred DERP hysteresis around the branch that compares latencies on a percentage basis.
=> net/netcheck: add addReportHistoryAndSetPreferredDERP() test case

wgengine/userspace.go
Add OpenBSD to the list of platforms that need DNS reconfigured on link changes.
This fixes a problem with Magic DNS that often stops working on OpenBSD with following error message in `tailscale status`: "Tailscale can't reach the configured DNS servers. Internet connectivity may be affected.".
Without this change, I have to force reload tailscale (`tailscale down && tailscale up`) whenever DNS stops working.
=> Fix MagicDNS on OpenBSD

cmd/tailscaled/tailscaled.go, cmd/tsconnect/wasm/wasm_js.go, tsnet/tsnet.go, wgengine/netstack/netstack.go, wgengine/netstack/netstack_test.go
A filesystem was plumbed into netstack in 993acf4475b22d693
but hasn't been used since 2d5d6f5403f3. Remove it.
Noticed while rebasing a Tailscale fork elsewhere.
=> wgengine/netstack: remove unused taildrive deps

cmd/k8s-operator/operator.go
Allow to optionally configure port for the Kubernetes Operator using the same PORT env var that's usually used by tailscaled.
This is to allow configuring a specific port for enforcing direct connections.
Updates tailscale/tailscale#13981
=> cmd/k8s-operator: allow to optionally configure tailscaled port via PORT env var

cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, envknob/envknob.go, kube/kubetypes/metrics.go
Sets a custom hostinfo app type for ProxyGroup replicas, similarly to how we do it for all other Kubernetes Operator managed components.
Updates tailscale/tailscale#13406,tailscale/corp#22920
=> envknob,kube/kubetypes,cmd/k8s-operator: add app type for ProxyGroup

client/tailscale/localclient.go, ipn/ipnlocal/local.go, ipn/localapi/localapi.go
Adds a /disconnect-control local API endpoint that just shuts down control client. This can be run before shutting down an HA subnet router/app connector replica - it will ensure that all connection to control are dropped and control thus considers this node inactive and tells peers to switch over to another replica. Meanwhile the existing connections keep working (assuming that the replica is given some graceful shutdown period).
I have tested this with a multi-replica subnet router on kube, see https://github.com/tailscale/tailscale/blob/irbekrm/connector_multireplica/cmd/containerboot/hafailover.md which incorporates the contents of this PR
Updates tailscale/tailscale#14020
=> client/tailscale,ipn/{ipnlocal,localapi}: add a pre-shutdown localAPI endpoint that terminates control connections

cmd/tailscaled/deps_test.go, cmd/tailscaled/ssh.go, tstest/deptest/deptest.go
Some environments would like to remove Tailscale SSH support for the
binary for various reasons when not needed (either for peace of mind,
or the ~1MB of binary space savings).
Updates tailscale/corp#24454
Updates #1278
Updates #12614
=> cmd/tailscaled: support "ts_omit_ssh" build tag to remove SSH

ipn/ipnlocal/c2n.go
Perhaps I was too opimistic in #13323 thinking we won't need logs for this. Let's log a summary of the response without logging specific identifiers.
Updates tailscale/corp#24437
=> ipn/ipnlocal: log a summary of posture identity response

util/codegen/codegen.go, util/codegen/codegen_test.go
It doesn't need a Clone method, like a time.Time, etc.
And then, because Go 1.23+ uses unique.Handle internally for
the netip package types, we can remove those special cases.
Updates #14058 (pulled out from that PR)
Updates tailscale/corp#24485
=> util/codegen: treat unique.Handle as an opaque value type

cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-operator/proxygroup_test.go
We currently annotate pods with a hash of the tailscaled config so that we can trigger pod restarts whenever it changes. However, the hash updates more frequently than is necessary causing more restarts than is necessary. This commit removes two causes reasons for the hash changing; scaling up/down and removing the auth key after pods have initially authed to control. However, note that pods will still restart on scale-up/down because of the updated set of volumes mounted into each pod. Hopefully we can fix that in a planned follow-up PR.
Updates #13406
In theory we might rip this out entirely in the very near future now that config reload should work better after #13979, but this is still a low-risk improvement if we don't manage to do that larger piece of validation/work before the next …
=> cmd/k8s-operator: restart ProxyGroup pods less

cmd/containerboot/main.go, cmd/k8s-operator/operator_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/testutils_test.go, k8s-operator/utils.go
This PR removes some custom logic that we added in 1.66 where we needed to both introduce some changes in how the operator configures the proxies, but also needed to support proxies back till 1.64 as per our version compatibility policy.
We are now at 1.77, so no more need to support proxies older than 1.66.
Updates tailscale/tailscale#13984
=> cmd/{k8s-operator,containerboot},k8s-operator: remove support for proxies below capver 95

control/controlclient/noise.go
Previously we required the program to be running in a test or have TS_CONTROL_IS_PLAINTEXT_HTTP before we disabled its https fallback on "http" schema control URLs to localhost with ports.
But nobody accidentally does all three of "http", explicit port number, localhost and doesn't mean it. And when they mean it, they're testing a localhost dev control server (like I was) and don't want 443 getting involved.
As of the changes for #13597, this became more annoying in that we were trying to use a port which wasn't even available.
Updates #13597
=> control/controlclient: disable https on for http://localhost:$port URLs

tstest/integration/testcontrol/testcontrol.go
Back in the day this testcontrol package only spoke the
nacl-boxed-based control protocol, which used this.
Then we added ts2021, which didn't, but still sometimes used it.
Then we removed the old mode and didn't remove this parameter
in 2409661a0da956.
Updates #11585
=> tstest/integration/testcontrol: remove a vestigial unused parameter

k8s-operator/sessionrecording/hijacker.go, k8s-operator/sessionrecording/hijacker_test.go, sessionrecording/connect.go, sessionrecording/connect_test.go, ssh/tailssh/tailssh.go, ssh/tailssh/tailssh_test.go
The v2 endpoint supports HTTP/2 bidirectional streaming and acks for received bytes. This is used to detect when a recorder disappears to more quickly terminate the session.
Updates https://github.com/tailscale/corp/issues/24023
=> sessionrecording: implement v2 recording endpoint support

cmd/tailscale/cli/debug.go, ipn/backend.go, ipn/ipnlocal/bus.go, ipn/ipnlocal/bus_test.go, ipn/ipnlocal/local.go
Limit spamming GUIs with boring updates to once in 3 seconds, unless
the notification is relatively interesting and the GUI should update
immediately.
This is basically @barnstar's #14119 but with the logic moved to be
per-watch-session (since the bit is per session), rather than
globally. And this distinguishes notable Notify messages (such as
state changes) and makes them send immediately.
Updates tailscale/corp#24553
=> ipn/ipnlocal: add IPN Bus NotifyRateLimit watch bit NotifyRateLimit

cmd/containerboot/kube.go, cmd/containerboot/services.go, cmd/k8s-operator/deploy/chart/templates/proxy-rbac.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/deploy/manifests/proxy.yaml, cmd/k8s-operator/deploy/manifests/userspace-proxy.yaml, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-operator/testutils_test.go, ipn/store/kubestore/store_kube.go, kube/kubeapi/api.go, kube/kubeclient/client.go, kube/kubeclient/client_test.go, kube/kubeclient/fake_client.go
This PR adds logic to emit [kube Events](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/) on a `Pod` running tailscale in response to events related to loading state from a Kubernetes `Secret`.
This is to make debugging easier in case of transient errors related to retrieving/writing state to a `Secret` (i.e because the API server was unable to serve the request).
A subset of these errors would result in container restarts meaning that we cannot really debug the issue by logging more because the logs of the original issue would be lost post-restart. The `Event`s are for a tied to a `Pod` (by name/namespace/uid), so they can still be viewed (i.e by `kubectl describe <pod-name>`) even after N restarts of a `Pod` that's in crashloop-ing)
The event logic is …
=> kube/{kubeapi,kubeclient},ipn/store/kubestore,cmd/{containerboot,k8s-operator}: emit kube Events for kube store operations

cmd/k8s-operator/tsrecorder_specs.go, docs/k8s/proxy.yaml, docs/k8s/role.yaml, docs/k8s/sidecar.yaml, docs/k8s/subnet.yaml, docs/k8s/userspace-sidecar.yaml, kube/kubeclient/client_test.go
This is a follow-up to #14112 where our internal kube client was updated to allow it to emit Events - this updates our sample kube manifests and tsrecorder manifest templates so they can benefit from this functionality.
Updates tailscale/tailscale#14080
=> cmd/k8s-operator,kube/kubeclient,docs/k8s: update manifest templates to ensure kube client can emit Events

net/tsaddr/tsaddr.go, net/tsaddr/tsaddr_test.go
Extracts tsaddr.IsTailscaleIPv4 out of tsaddr.IsTailscaleIP.
This will allow for checking valid Tailscale assigned IPv4 addresses without checking IPv6 addresses.
Updates #14168
Updates tailscale/corp#24620
=> net/tsaddr: extract IsTailscaleIPv4 from IsTailscaleIP

cmd/tailscale/cli/debug.go, control/controlhttp/constants.go
Otherwise we'll see a panic if we hit the dnsfallback code and try to call NewDialer with a nil NetMon.
Updates #14161
Change-Id: I81c6e72376599b341cb58c37134c2a948b97cf5f
=> cmd/tailscale/cli: create netmon in debug ts2021

cmd/tailscale/cli/risks.go, cmd/tailscale/cli/set.go, cmd/tailscale/cli/up.go
Updates tailscale/tailscale#1748
App connectors should not be run on macOS as described in the KB topic. We should not prevent users from doing so if they want to, but let's present a warning in the CLI to make sure the user fully understands the implications.
=> cli: present risk warning when setting up app connector on macOS

cmd/k8s-operator/deploy/chart/templates/deployment.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml
A small follow-up to #14112- ensures that the operator itself can emit Events for its kube state store changes.
Updates tailscale/tailscale#14080
=> cmd/k8s-operator/deploy: ensure that operator can emit Events for kube state store changes

ipn/ipnlocal/local_test.go, ipn/ipnlocal/state_test.go, ipn/localapi/localapi_test.go, wgengine/netstack/netstack_test.go
We have several places where `LocalBackend` instances are created for testing, but they are rarely shut down when the tests that created them exit.
In this PR, we update `newTestLocalBackend` and similar functions to use `testing.TB.Cleanup(lb.Shutdown)` to ensure `LocalBackend` instances are properly shut down during test cleanup.
Updates #12687
=> ipn/{ipnlocal,localapi}, wgengine/netstack: call (*LocalBackend).Shutdown when tests that create them complete

cmd/tailscaled/tailscaled_windows.go
In this PR, we move the `syspolicy.FlushDNSOnSessionUnlock` check from service startup to when a session change notification is received. This ensures that the most recent policy setting value is used if it has changed since the service started.
We also plan to handle session change notifications for unrelated reasons and need to decouple notification subscriptions from DNS anyway.
Updates #12687
Updates tailscale/corp#18342
=> cmd/tailscaled: flush DNS if FlushDNSOnSessionUnlock is true upon receiving a session change notification

cmd/tailscaled/tailscaled_windows.go
This updates the `syspolicy.LogSCMInteractions` check to run at the time of an interaction, just before logging a message, instead of during service startup. This ensures the most recent policy setting is used if it has changed since the service started.
Updates #12687
=> cmd/tailscaled: log SCM interactions if the policy setting is enabled at the time of interaction

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
[2] commits
First, we move code that handles `ExitNodeID`/`ExitNodeIP` `syspolicy` settings from `(*LocalBackend).setExitNodeID` to `applySysPolicy`.
Second, we update `LocalBackend` to subscribe to policy change notifications and reapply `syspolicy` settings to the current profile's `ipn.Prefs` whenever a change occurs.
Updates #12687
=> ipn/ipnlocal: update ipn.Prefs when there's a change in syspolicy settings

control/controlclient/sign_supported.go
This PR removes the `sync.Once` wrapper around retrieving the `MachineCertificateSubject` policy setting value, ensuring the most recent version is always used if it changes after the service starts.
Although this policy setting is used by a very limited number of customers, support escalations earlier this year have showed issues caused by outdated or incorrect policy values being applied.
Updates #12687
=> control/controlclient: use the most recent syspolicy.MachineCertificateSubject value

cmd/containerboot/metrics.go
A small fix to only write status code header after adding the other headers copied from response as [header map cannot be modified after calling `WriteHeader`](https://cs.opensource.google/go/go/+/refs/tags/go1.23.3:src/net/http/server.go;l=101)
Updates tailscale/tailscale#11292
=> cmd/containerboot: preserve headers of metrics endpoints responses

net/netmon/netmon_darwin.go
I was hoping we'd catch an example input quickly, but the reporter had rebooted their machine and it is no longer exhibiting the behavior. As such this code may be sticking around quite a bit longer and we might encounter other errors, so include the panic in the log entry.
Updates #14201
Updates #14202
Updates golang/go#70528
=> net/netmon: improve panic reporting from #14202

ipn/ipnlocal/local.go
In https://github.com/tailscale/tailscale/pull/13726 we added logic to `checkExitNodePrefsLocked` to error out on platforms where using an exit node is unsupported in order to give users more obvious feedback than having this silently fail downstream.
The above change neglected to properly check whether the device in question was actually trying to use an exit node when doing the check and was incorrectly returning an error on any calls to `checkExitNodePrefsLocked` on platforms where using an exit node is not supported as a result.
This change remedies this by adding a check to see whether the device is attempting to use an exit node before doing the `CanUseExitNode` check.
Updates https://github.com/tailscale/corp/issues/24835
=> ipn/ipnlocal: only check CanUseExitNode if we are attempting to use one

cmd/tailscale/cli/syspolicy.go
=> cmd/tailscale/cli: fix format string

control/controlhttp/http_test.go
Observed during another PR:
https://github.com/tailscale/tailscale/actions/runs/12040045880/job/33569141807
Change-Id: I9e0f49a35485fa2e097892737e5e3c95bf775a90
=> control/controlhttp: set *health.Tracker in tests

logtail/logtail.go
Re-use a pre-allocated bytes.Buffer struct and
shallow the copy the result of bytes.NewBuffer into it to avoid allocating the struct.
Note that we're only reusing the bytes.Buffer struct itself and not the underling []byte temporarily stored within it.
Updates golang/go#67004
=> logtail: avoid bytes.Buffer allocation

health/health.go, health/health_test.go, tsnet/tsnet_test.go, wgengine/magicsock/magicsock.go
To unpack and improve reliability of metrics integration tests:
- Move health metrics tests into the health package
- Reduce the data sent between test nodes (10MB to 1MB) and add better waiter
- Split advertised routes and data sent integration tests 
Tests ran locally over 10 000 times without any flake.
In addition, [afa3299](https://github.com/tailscale/tailscale/pull/14211/commits/afa3299dc0e4fa10fcbf4ebad6a690411630a36f), fixes a path in magicsock where discopackages was counted as data.
Updates #13420
=> metrics: improve flaky tests

cmd/k8s-operator/egress-services.go, cmd/k8s-operator/egress-services_test.go, cmd/k8s-operator/testutils_test.go
See https://github.com/tailscale/tailscale/issues/13406#issuecomment-2507230388
This PR ensures that the ExternalName Service port names are always synced to the ClusterIP Service, to fix a bug where if users created a Service with a single unnamed port and later changed to 1+ named ports, the operator attempted to apply an invalid multi-port Service with an unnamed port. Also, fixes a small internal issue where not-yet Service status conditons were lost on a spec update.
I have updated the tests to so they would now catch this bug and also verified e2e that the scenario as described in https://github.com/tailscale/tailscale/issues/13406#issuecomment-2507230388 now works
Updates tailscale/tailscale#10102
=> cmd/k8s-operator: fix port name change bug for egress ProxyGroup proxies

Makefile, build_docker.sh
See the reasoning here https://github.com/tailscale/corp/pull/24908#issuecomment-2507952962
I think this is fine because the make target for building the image remains the same and I don't think anyone external relies on this build script.
Updates tailscale/corp#24540
Updates tailscale/tailscale#12914
=> Makefile,./build_docker.sh: update kube operator image build target name

cmd/k8s-operator/operator_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/testutils_test.go
This is a cleanup PR that ensures that stateful filtering that was briefly defaulted to true in https://github.com/tailscale/tailscale/pull/12025, but then disabled in https://github.com/tailscale/tailscale/pull/12197 is also disabled for the operator proxies.
For context, this config option was added in https://github.com/tailscale/tailscale/pull/12075 because at that point stateful filtering was defaulted to true and broke the egress proxies. We then also added a setting to set it to true for all the other proxies to match the default at the time. As the default has now changed, also changing it here.
(I've tested this a bunch with the different proxy types, but also this can't possibly break anything)
Updates tailscale/tailscale#12108
=> cmd/k8s-operator: always set stateful filtering to false

cmd/checkmetrics/checkmetrics.go, util/usermetric/usermetric.go
This commit adds a command to validate that all the metrics that
are registring in the client are also present in a path or url.
It is intended to be ran from the KB against the latest version of
tailscale.
Used in www https://github.com/tailscale/tailscale-www/pull/7094
Updates tailscale/corp#24066
Closes #13884
=> cmd/checkmetrics: validates if metrics are documented

ipn/doc.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/serve.go
This PR updates ServeConfig to allow configuration to Services (VIPServices for now) via Serve.
The scope of this commit is only adding the Services field to ServeConfig. The field doesn't actually
allow packet flowing yet. The purpose of this commit is to unblock other work on k8s end.
Updates #22953
=> IPN: Update ServeConfig to accept configuration for Services.

cmd/k8s-operator/egress-services.go
When the operator enables metrics on a proxy, it uses the port 9001, and in the near future it will start using 9002 for the debug endpoint as well. Make sure we don't choose ports from a range that includes 9001 so that we never clash. Setting TS_SOCKS5_SERVER, TS_HEALTHCHECK_ADDR_PORT, TS_OUTBOUND_HTTP_PROXY_LISTEN, and PORT could also open arbitrary ports, so we will need to document that users should not choose ports from the 10000-11000 range for those settings.
Updates #13406
=> cmd/k8s-operator: avoid port collision with metrics endpoint

cmd/k8s-operator/deploy/chart/templates/deployment.yaml, cmd/k8s-operator/deploy/chart/templates/operator-rbac.yaml, cmd/k8s-operator/deploy/chart/values.yaml
This is an alternative approach to #11270 / #12213
It does intentionally _not_ follow the `extraVolumes`/`extraMounts` pattern to increase ease-of-use, but solves the very specific problem of using [secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver).
Not setting the new object results in falling back to the previous default behavior.
=> cmd/k8s-operator/deploy/chart: allow reading OAuth creds from a CSI driver's volume and annotating operator's Service account

cmd/k8s-operator/connector.go, cmd/k8s-operator/egress-services-readiness.go, cmd/k8s-operator/egress-services.go, cmd/k8s-operator/nameserver.go, cmd/k8s-operator/proxyclass.go, cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/svc.go, cmd/k8s-operator/tsrecorder.go
All these checks were comparing a pointer to a concrete type so we were always running the update that should have only been run if there was a diff.
The update was a no-op without the diff, but was causing issues in cases where the operator would not been allowed to modify the resources, see #14269 + the unnecessary API server calls.
I've verified that with this fix the operator no longer throws errors on GKE Autopilot (see #14269 )
Updates tailscale/tailscale#14269
=> cmd/k8s-operator: fix a bunch of status equality checks

cmd/containerboot/kube.go, cmd/containerboot/kube_test.go, cmd/containerboot/main.go, cmd/containerboot/main_test.go, cmd/containerboot/serve.go, cmd/containerboot/settings.go, cmd/k8s-operator/connector.go, cmd/k8s-operator/ingress.go, cmd/k8s-operator/ingress_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/svc.go, kube/kubetypes/types.go
This PR attempts to make Kubernetes Operator L7 Ingress setup failures more explicit:
- the `Ingress` resource now only advertises HTTPS endpoint via `status.ingress.loadBalancer.hostname` when/if the proxy has succesfully loaded serve config
- the proxy attempts to catch cases where HTTPS is disabled for the tailnet and logs an error (see https://github.com/tailscale/tailscale/issues/12079#issuecomment-2473912067)
For this I've added two new fields to proxy's state `Secret`:
- `https_endpoint` - this gets set to the advertised HTTPS endpoint when serve config is successfully loaded. (It be unset if tailnet has HTTPS disabled and will get dynamically set/unset if HTTPS setting changes while the proxy is running)
- `tailscale_capver` - this advertises the capability version + Pod UID of …
=> cmd/{containerboot,k8s-operator},kube/kubetypes: kube Ingress L7 proxies only advertise HTTPS endpoint when ready

net/tstun/wrap.go, net/tstun/wrap_test.go
=> net/tstun: remove tailscaled_outbound_dropped_packets_total reason=acl metric for now

client/tailscale/localclient.go, cmd/tailscale/cli/debug.go, ipn/ipnlocal/local.go, ipn/localapi/localapi.go, net/netcheck/netcheck.go, net/netcheck/netcheck_test.go, wgengine/magicsock/magicsock.go
This provides an interface for a user to force a preferred DERP outcome for all future netchecks that will take precedence unless the forced region is unreachable.
The option does not persist and will be lost when the daemon restarts.
Updates tailscale/corp#18997
Updates tailscale/corp#24755
=> cmd/tailscale,net/netcheck: add debug feature to force preferred DERP

cmd/k8s-operator/connector.go, cmd/k8s-operator/dnsrecords.go, cmd/k8s-operator/egress-services.go, cmd/k8s-operator/ingress.go, cmd/k8s-operator/nameserver.go, cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/svc.go, cmd/k8s-operator/tsrecorder.go
Every so often, the ProxyGroup controller loses an optimistic locking race with other controllers that update the objects it creates. Stop treating this as an error event, and instead just log an info level log line for it.
Fixes #14072
=> cmd/k8s-operator: don't error for transient failures

net/netcheck/netcheck.go
In https://github.com/tailscale/tailscale/pull/14261 we removed the defaulting of the STUN port to 3478 to not set it for cases where it's set to -1 (disable). However, with that we also lost the previous behaviour where STUN ports set to 0 are defaulted to 3478, which is intended (see [this comment](https://github.com/tailscale/tailscale/blob/7f9ebc0a83f82922787f4e8336b9f626d895a08c/tailcfg/derpmap.go#L159))
That caused some nodes to incorrectly report that they have no UDP connectivity, see https://github.com/tailscale/tailscale/issues/14287
@bradfitz - I don't know if this is the right fix or rather the derpmaps received on clients should already have ports defaulted to 3478?
When I curl derpmap on my client via localapi (which seems to be [how a client would get the derpmap for the …
=> net/netcheck: preserve STUN port defaulting to 3478

cmd/derper/cert.go, cmd/derper/cert_test.go, cmd/derper/derper.go, cmd/derper/derper_test.go
=> cmd/derper: allow absent SNI when using manual certs and IP literal for hostname

cmd/gitops-pusher/gitops-pusher.go
If previousEtag is empty, then we assume control ACLs were not modified manually and push the local ACLs. Instead, we defaulted to localEtag which would be different if local ACLs were different from control.
AFAIK this was always buggy, but never reported?
Fixes #14295
=> cmd/gitops-pusher: default previousEtag to controlEtag

logpolicy/logpolicy.go
This package grew organically over time and
is an awful mix of explicitly declared options and globally set parameters via environment variables and other subtle effects.
Add a new Options and TransportOptions type to
allow for the creation of a Policy or http.RoundTripper with some set of options.
The options struct avoids the need to add yet more NewXXX functions for every possible combination of ordered arguments.
The goal of this refactor is to allow specifying the http.Client to use with the Policy.
Updates tailscale/corp#18177
=> logpolicy: cleanup options API and allow setting http.Client

cmd/stunc/stunc.go
Enforce a read timeout deadline waiting for response from the stun server provided in the args. Otherwise the program will never exit.
Fixes https://github.com/tailscale/tailscale/issues/14267
=> cmd/stunc: enforce read timeout deadline

hostinfo/hostinfo_linux_test.go
Previously this unit test failed if it was run in a container. Update the assert to focus on exactly the condition we are trying to assert: the package type should only be 'container' if we use the build tag.
Updates #14317
=> hostinfo: fix testing in container

derp/derphttp/derphttp_client.go, prober/derp.go
Make dev-mode DERP probes work without TLS. Properly dial port `3340` when not using HTTPS when dialing nodes in `derphttp_client`. Skip verifying TLS state in `newConn` if we are not running a prober.
Updates tailscale/corp#24635
=> prober,derp/derphttp: make dev-mode DERP probes work without TLS

hostinfo/hostinfo_linux_test.go
Backports #14330 into the 1.78 release branch so that upstream users who package Tailscale can successfully run the unit tests against the version they're building in their own pipelines that might run inside a container.
Previously this unit test failed if it was run in a container. Update the assert to focus on exactly the condition we are trying to assert: the package type should only be 'container' if we use the build tag.
Closes #14317
=> hostinfo: fix testing in container (#14330)

cmd/containerboot/main.go
A method on kc was called unconditionally, even if was not initialized, leading to a nil pointer dereference when TS_SERVE_CONFIG was set outside Kubernetes.
Add a guard symmetric with other uses of the kubeClient.
Fixes #14354.
=> cmd/containerboot: guard kubeClient against nil dereference

cmd/containerboot/serve.go
A follow-up to https://github.com/tailscale/tailscale/pull/14357, fixes a second place where the `https_endpoint` field was written to the kube Secret without a check + adds some tests that would have caught this.
I've tested that non-kube containers work with `TS_SERVE_CONFIG` with this change, i.e
```
docker run -it -e TS_AUTHKEY=<key> -v $(pwd)/serve-config.json:/serve-config.json -e TS_SERVE_CONFIG=/serve-config.json --privileged=true <image>
```
Updates tailscale/tailscale#14354
=> cmd/containerboot: don't attempt to write kube Secret in non-kube environments

cmd/containerboot/main_test.go, cmd/containerboot/settings.go
Add more tests for containerboot startup (including that would have caught https://github.com/tailscale/tailscale/pull/14357), add a validation that egress services config is only set for instances running on Kubernetes.
Updates tailscale/tailscale#14357
=> cmd/containerboot: add more tests, check that egress service config  is only set when running on kube

cmd/containerboot/kube.go, cmd/containerboot/serve.go, cmd/containerboot/settings.go
We can still have some Kubernetes clients running that don't have PATCH permissions against the state Secret (maybe?). Check for PATCH permissions before attempting to write Secret field.
=> cmd/containerboot: don't attempt to patch a Secret field without permissions

cmd/containerboot/kube.go, cmd/containerboot/main.go, cmd/containerboot/serve.go, cmd/containerboot/settings.go
This is a cherry-pick that contains the three PRs that fixed the nil pointer exception for 1.78.1 Tailscale containers with `TS_SERVE_CONFIG` set (https://github.com/tailscale/tailscale/issues/14354):
- https://github.com/tailscale/tailscale/pull/14357
- https://github.com/tailscale/tailscale/pull/14358
- https://github.com/tailscale/tailscale/pull/14365
=> cmd/containerboot: fix nil pointer exception (cherry-pick of #14357, #14358)

types/iox/io.go, types/iox/io_test.go
Throughout our codebase we have types that only exist only to implement an io.Reader or io.Writer, when it would have been simpler, cleaner, and more readable to use an inlined function literal that closes over the relevant types.
This is arguably more readable since it keeps the semantic logic in place rather than have it be isolated elsewhere.
Note that a function literal that closes over some variables is semantic equivalent to declaring a struct with fields and having the Read or Write method mutate those fields.
=> types/iox: add function types for Reader and Writer

Makefile, ssh/tailssh/tailssh.go, ssh/tailssh/tailssh_test.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_view.go
When we first made Tailscale SSH, we assumed people would want public key support soon after. Turns out that hasn't been the case; people love the Tailscale identity authentication and check mode.
In light of CVE-2024-45337, just remove all our public key code to not distract people, and to make the code smaller. We can always get it back from git if needed.
Updates tailscale/corp#25131
Updates golang/go#70779
=> ssh/tailssh: remove unused public key support

cmd/k8s-operator/proxygroup.go
Fix the ProxyGroup hostname if derived from `.spec.hostnamePrefix` so that the ordinal is separated by dash.
This will change hostnames of existing replicas on upgrade, but that should be fine (not ingress, nothing should connect via MagicDNS name)
Updates tailscale/tailscale#14325
=> cmd/k8s-operator: fix ProxyGroup hostname

types/opt/value_test.go
The omitzero tag option has been backported to v1 "encoding/json" from the "encoding/json/v2" prototype and will land in Go1.24. Until we fully upgrade to Go1.24, adjust the test to be agnostic to which version of Go someone is using.
Updates tailscale/corp#25406
=> types/opt: fix test to be agnostic to omitzero support

docs/k8s/operator-architecture.md
This is an experiment to see how useful we will find it to have some text-based diagrams to document how various components of the operator work. There are no plans to link to this from elsewhere yet, but hopefully it will be a useful reference internally.
=> docs/k8s: add some high-level operator architecture diagrams

cmd/derpprobe/derpprobe.go, prober/derp.go, prober/histogram.go, prober/histogram_test.go, prober/prober.go, prober/prober_test.go, prober/status.go, prober/status.html
This replaces #14122. It keeps the framework changes to support continuous probing, but instead of performing continuous bandwidth probing, it adds continuous queuing delay probing.
=> cmd/derpprobe,prober: add ability to perform continuous queuing delay measurements against DERP servers

cmd/systray/logo.go, cmd/systray/systray.go
Some notification managers crop the application icon to a circle, so ensure we have enough padding to account for that.
Before and after with swaync configured to use circular application icons:
Updates #1708
=> cmd/systray: add extra padding around notification icon

cmd/k8s-operator/deploy/crds/tailscale.com_proxygroups.yaml, cmd/k8s-operator/deploy/crds/tailscale.com_recorders.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_proxygroup.go, k8s-operator/apis/v1alpha1/types_recorder.go
When reading https://doc.crds.dev/github.com/tailscale/tailscale/tailscale.com/ProxyGroup/v1alpha1@v1.78.3 I noticed there is no top-level description for ProxyGroup and Recorder. Add one to give some high-level direction.
Change-Id: I3666c5445be272ea5a1d4d02b6d5ad4c23afb09f
=> cmd/k8s-operator,k8s-operator: include top-level CRD descriptions

prober/histogram.go, prober/histogram_test.go
Histogram buckets should include counts for all values under the bucket ceiling, not just those between the ceiling and the next lower ceiling.
See https://prometheus.io/docs/tutorials/understanding_metric_types/#histogram
Updates tailscale/corp#24522
=> prober: make histogram buckets cumulative

tailcfg/tailcfg.go
Updates tailscale/corp#22743.
In #14046, this was accidentally made a PeerCapability when it should have been NodeCapability. Also, renaming it to use the nomenclature that we decided on after #14046 went up (ServiceHost instead of ServiceDestination).
This shouldn't break anything, since no one was using this string or variable yet.
=> tailcfg: rename and retype ServiceHost capability

version/distro/distro.go, wgengine/router/router_linux.go, wgengine/router/router_linux_test.go
Hello Tailscale Team,
I'm contributing my first PR, focusing on UDM-Pro support. I realize the current form may not be ready for merge, and I'm seeking guidance for integration without negatively affecting other clients. Though it should be mentioned that this PR does function correctly on the UDM-Pro and eliminates the need for any additional scripts.
One idea was a CLI flag (`--ip-rule-mark ${priority}:${table}`), but its niche use might not be ideal. Detecting UDM-Pro programmatically could be a solution, though I'm unsure how to implement it effectively.
```sh
tailscale up --ip-rule-mark 21:201 --ip-rule-mark 22:202
```
Any advice or direction to better align this with Tailscale's architecture would be valuable.
This aims to address issue #4038 and is linked to the discussion in …
=> wgengine/router: add ip rules for unifi udm-pro

scripts/installer.sh
Tested working in a VM on PikaOS 4. Older versions not tested but should in theory work, and I don't believe are supported anyway.
Fixes #14460
=> scripts/installer.sh: add support for PikaOS

.github/workflows/installer.yml
Remove EOL Ubuntu versions that were broken.
Add new Ubuntu LTS.
Update Alpine to test latest version.
Also, make the test run when its workflow is updated and installer.sh isn't.
Parrot OS is still failing but that's due to our installer not supporting it and not because the OS is broken.
=> .github: update matrix of installer.sh tests

scripts/installer.sh
Newer Deepin Linux versions use `deepin` as their ID, older ones used `Deepin`. 
Change makes the script not break on Deepin 23. Tested in VM.
Fixes #13570
=> scripts/installer.sh: accept different capitalisation of deepin

cmd/systray/logo.go, cmd/systray/systray.go
A two-part change:
- first refactor `tsLogo` allow adding custom masks and overlays, needed for the exit node icons
- then use the logos, and refactor some icon-setting code to be more consistent.
Updates #1708
=> cmd/systray: add and use exit node icons

cmd/systray/systray.go
On Linux, systray.SetTitle actually seems to set the tooltip on all desktops I've tested on.  But on macOS, it actually does set a title that is always displayed in the systray area next to the icon. This change should properly set the tooltip across platforms.
Updates #1708
=> cmd/systray: properly set tooltip on different platforms

scripts/installer.sh
Their `os-release` doesn't follow convention, so we do some special casing to get it work. 
Specifically note the lack of an `ID_LIKE` and the `ID` being Debian rather than the ID of their distro like other derivatives. 
The script interprets this as being Debian Lory which obviously isn't a thing so it fails to supported version check. We capture this based on `NAME` (the only consistent value, not ideal to match on but there aren't many other choices) and rewrite it to Debian Bookworm so that the script succeeds its checks.
Make sure the Actions tests pass before approving/merging, there are tests for Debian and for Parrot Security.
Fixes https://github.com/tailscale/tailscale/issues/10778
old:
```
$ docker run -it parrotsec/core:lts-amd64
┌─[root@718076d0be7e]─[/]
└──╼ #cat …
```
=> scripts/install.sh: add special case for Parrot Security

ipn/backend.go, ipn/ipnlocal/local.go
Using context.CancelFunc as the type (instead of func()) answers
questions like whether it's okay to call it multiple times, whether
it blocks, etc. And that's the type it actually is in this case.
=> ipn/ipnlocal: use context.CancelFunc type for doc clarity

version/distro/distro.go, wgengine/router/router_linux.go, wgengine/router/router_linux_test.go
After collaboration with @notheotherben I realized my original implementation was quite narrow and left many Ubiquiti Network devices unsupported.
This is also more performant since it detects the device using a file path instead of reading file contents.
Fixes #14453
=> wgengine/router: refactor udm-pro into broader ubnt support

control/controlclient/map.go, control/controlclient/map_test.go
While working on #13390, I ran across this non-idiomatic
pointer-to-view and parallel-sorted-map accounting code that was all
just to avoid a sort later.
But the sort later when building a new netmap.NetworkMap is already a
drop in the bucket of CPU compared to how much work & allocs
mapSession.netmap and LocalBackend's spamming of the full netmap
(potentially tens of thousands of peers, MBs of JSON) out to IPNBus
clients for any tiny little change (node changing online status, etc).
Removing the parallel sorted slice let everything be simpler to reason
about, so this does that. The sort might take a bit more CPU time now
in theory, but in practice for any netmap size for which it'd matter,
the quadratic netmap IPN bus spam (which we need to fix soon) will
overshadow that little sort. …
=> control/controlclient: remove optimization that was more convoluted than useful

ipn/serve.go, types/views/views.go
The remaining range funcs in the tree are RangeOverTCPs and
RangeOverWebs in ServeConfig; those will be cleaned up separately.
Updates #12912
=> types/views: remove various Map Range funcs; use iterators everywhere

ipn/ipnlocal/local.go, ipn/serve.go
These were the last two Range funcs in this repo.
Updates #12912
=> ipn: convert ServeConfig Range methods to iterators

cmd/tailscale/cli/up.go
It was failing about an unaccepted risk ("mac-app-connector") because
it was checking runtime.GOOS ("darwin") instead of the test's env.goos
string value ("linux", which doesn't have the warning).
Fixes #14544
=> cmd/tailscale/cli: fix TestUpdatePrefs on macOS

client/systray/logo.go, client/systray/systray.go, cmd/systray/systray.go
Move `cmd/systray` to `client/systray`, and then make `cmd/systray` a tiny wrapper around the client package.  This prepares for calling the `client/systray` package from `cmd/tailscale`.
PR in two commits best reviewed individually, one that just renames the files, and then a second to add the wrapper.
=> client/systray: move cmd/systray to client/systray

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_notplan9.go, wgengine/magicsock/magicsock_plan9.go
Observed in the wild some macOS machines gain broken sockets coming out of sleep (we observe "time jumped", followed by EPIPE on sendto). The cause of this in the platform is unclear, but the fix is clear: always rebind if the socket is broken. This can also be created artificially on Linux via `ss -K`, and other conditions or software on a system could also lead to the same outcomes.
Updates tailscale/corp#25648
=> wgengine/magicsock: rebind on EPIPE/ECONNRESET

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_notplan9.go, wgengine/magicsock/magicsock_plan9.go, wgengine/magicsock/magicsock_test.go
Remove the platform specificity, it is unnecessary complexity.
Deduplicate repeated code as a result of reduced complexity.
Split out error identification code.
Update call-sites and tests.
Updates #14551
Updates tailscale/corp#25648
=> wgengine/magicsock: refactor maybeRebindOnError

go.mod, go.sum
=> go.mod: bump tailscale/wireguard-go for Solaris/Illumos

net/netmon/netmon_darwin.go
This was an extra defense added for #14201 that is no longer required.
Fixes #14201
=> net/netmon: remove extra panic guard around ParseRIB

cmd/addlicense/main.go, cmd/k8s-operator/proxy.go, cmd/tailscale/cli/risks.go, cmd/tsconnect/tsconnect.go, net/tshttpproxy/tshttpproxy_synology.go, net/tshttpproxy/tshttpproxy_synology_test.go, ssh/tailssh/incubator.go, tstest/integration/testcontrol/testcontrol.go
These erroneously blocked a recent PR, which I fixed by simply re-running CI. But we might as well fix them anyway. These are mostly `printf` to `print` and a couple of `!=` to `!Equal()`
=> all: fix golangci-lint errors

cmd/k8s-operator/deploy/crds/tailscale.com_proxygroups.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/egress-services.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-operator/proxygroup_test.go, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_proxygroup.go
This PR adds support for creating ingress `ProxyGroup` type.
Currently this ProxyGroup does not yet do anything apart from creating the ProxyGroup resources like StatefulSet.
This PR:
- adds support for creating 'ingress' type
- adds a new displayed `Type` field to `ProxyGroup`
```sh
$ k get proxygroup
NAME              STATUS            TYPE
egress-proxies1   ProxyGroupReady   egress
```
- adds more tests for ingress/egress `ProxyGroup` types
- improves ProxyGroup CR/Service validation in a few places
The `ProxyGroup` type is made immutable.
=> cmd/k8s-operator,k8s-operator: support ingress ProxyGroup type

hostinfo/hostinfo.go
DBus doesn't imply desktop.
Updates #1708
=> hostinfo: improve accuracy of Linux desktop detection heuristic

prober/derp.go
This will enable Prometheus queries to look at the bandwidth over time windows, for example 'increase(derp_bw_bytes_total)[1h] / increase(derp_bw_transfer_time_seconds_total)[1h]'.
Updates tailscale/corp#25503
=> prober: record total bytes transferred in DERP bandwidth probes

types/views/views.go, types/views/views_test.go
If the total number of differences is less than a small amount, just do the dumb quadratic thing and compare every single object instead of allocating a map.
Updates tailscale/corp#25479
Change-Id: I8931b4355a2da4ec0f19739927311cf88711a840
=> types/views: optimize SliceEqualAnyOrderFunc for small slices

.github/workflows/test.yml, cmd/tailscaled/tailscaled.go, ipn/ipnlocal/local.go, ipn/ipnserver/actor.go, ipn/ipnstate/ipnstate.go, ipn/localapi/localapi.go, ipn/localapi/localapi_test.go, net/dns/manager_default.go, net/dns/manager_solaris.go, net/dns/resolver/tsdns.go, net/netutil/ip_forward.go, net/tstun/tstun_stub.go, net/tstun/tun.go, paths/paths_unix.go
Based on some quick testing on my machine, this correctly causes binaries built for illumos to default to userspace only and things appear to work. This includes doing a taildrive share from the userspace only illumos node and mounting it from  a Linux client.
This is part of #14565
=> all: add userspace support for Solaris / illumos 

ipn/conf.go
This is not used by anything just yet.
I am not bumping capver this time- although normally we would need to do it when adding a new field here that's meant to be used by kube operator/proxies (see https://github.com/tailscale/tailscale/pull/13942/commits/e045805c941069765fb9c77d8fa466562ce6dec4#r1822767271), this time it will not be used by any proxies created from a tailscale version older than this change.
I've verified that when the new field is set and config is reloaded, the advertised services appear in prefs.
=> ipn/conf.go: add VIPServices to tailscaled configfile

cmd/containerboot/main.go, cmd/containerboot/tailscaled.go, cmd/k8s-operator/operator_test.go, cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-operator/proxygroup_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/testutils_test.go
Reload tailscaled mounted tailscaled config when file contents have changed instead of restarting the proxies.
I have tested that the reloading with a hostname change for ProxyGroup and advertised routes change for a Connector.
Updates tailscale/tailscale#13032
=> cmd/containerboot,cmd/k8s-operator: reload tailscaled config

cmd/containerboot/serve.go, cmd/containerboot/serve_test.go
Fixes an issue where, if a tailnet has HTTPS disabled, no serve config set via TS_SERVE_CONFIG gets loaded,  even if the config does not contain an HTTPS endpoint.
Now serve config provided to containerboot is considered invalid (and not loaded) for tailnets with no HTTPS only if there is an HTTPS endpoint defined in the config.
I've tested by hand that the existing behaviour is retained and also serve config without HTTPS endpoint can now gets loaded for tailnets with HTTPS disabled.
Fixes tailscale/tailscale#14495
=> cmd/containerboot: load containerboot serve config that does not contain HTTPS endpoint in tailnets with HTTPS disabled

ipn/ipnlocal/c2n.go, ipn/ipnlocal/local.go, tailcfg/c2ntypes.go
This commit updates the return body of c2n endpoint /vip-services to keep hash generation logic on client side.
Updates tailscale/corp#24510
=> ipn/ipnlocal: add VIPServices hash to return body of vip-services c2n endpoint

go.mod, net/dns/nm.go, util/cstruct/cstruct.go, util/linuxfw/nftables.go
We still use josharian/native (hi @josharian!) via
netlink, but I also sent https://github.com/mdlayher/netlink/pull/220
Updates #8632
=> all: use Go 1.21's binary.NativeEndian

prober/derp.go
Previously, we did not actually accumulate the bytes transferred, leaving the counter constant. This fixes that, and also makes sure to only count what was successfully read.
Updates tailscale/corp#25503
=> prober: accumulate the bytes transferred in DERP bandwidth probes

cmd/tailscale/cli/cli.go
This reverts commit b7e48058c8d243adf1ff687e3e92d3fb02b035ea (cc @bradfitz )
That commit broke all documented ways of starting Tailscale on gokrazy: https://gokrazy.org/packages/tailscale/ — both Option A (tailscale up) and Option B (tailscale up --auth-key) rely on the tailscale CLI working.
fixes https://github.com/gokrazy/gokrazy/issues/286
I verified that the tailscale CLI just prints it help when started without arguments, i.e. it does not stay running and is not restarted:
I verified that the tailscale CLI successfully exits when started with tailscale up --auth-key, regardless of whether the node has joined the tailnet yet or not.
I verified that the tailscale CLI successfully waits and exits when started with tailscale up, as expected.
=> Revert "cmd/tailscale/cli: don't run CLI as a service on gokrazy"

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go
This will prevent `tailscale up` from resetting the posture checking client pref.
Fixes #12154
=> cmd/tailscale/cli: add --posture-checking to tailscale up

ipn/ipnlocal/peerapi.go
This doesn't seem to have any immediate impact, but not allowing access via the IPv6 masquerade address when an IPv4 masquerade address is also set seems like a bug.
Updates #14570 (found when working on it)
=> ipn/ipnlocal: allow Peer API access via either V4MasqAddr or V6MasqAddr when both are set

control/controlbase/conn_test.go, control/controlclient/map.go, control/controlclient/map_test.go, ipn/ipnlocal/expiry.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go, tstest/integration/testcontrol/testcontrol.go, types/netmap/netmap.go, types/netmap/netmap_test.go, types/netmap/nodemut.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/pendopen.go, wgengine/wgcfg/nmcfg/nmcfg.go
This deprecates the old "DERP string" packing a DERP region ID into an
IP:port of 127.3.3.40:$REGION_ID and just uses an integer, like
PeerChange.DERPRegion does.
We still support servers sending the old form; they're converted to
the new form internally right when they're read off the network.
Updates #14636
=> all: add Node.HomeDERP int, phase out "127.3.3.40:$region" hack [capver 111]

client/tailscale/localclient.go, ipn/ipnauth/actor.go, ipn/ipnlocal/local.go, ipn/ipnserver/actor.go, ipn/ipnserver/server.go, ipn/ipnserver/server_test.go
[4 commits]
In the first two commits, we make `ipn/ipnserver.Server` testable with test user identities and add basic tests.
The next two commits fix two bugs in `(*ipn/ipnserver.Server).addActiveHTTPRequest` and add corresponding test coverage.
Can be reviewed either by commit or all at once.
Fixes tailscale/corp#25804
=> ipn/ipnserver: fix resetting LocalBackend's state when a different user connects

control/controlclient/map.go, control/controlclient/map_test.go, tailcfg/tailcfg.go
=> tailcfg,control/controlclient: treat nil AllowedIPs as Addresses [capver 112]

cmd/derper/derper.go, cmd/derper/mesh.go
The --mesh-with flag now supports the specification of hostname tuples like derp1a.tailscale.com/derp1a-vpc.tailscale.com, which instructs derp to mesh with host 'derp1a.tailscale.com' but dial TCP connections to 'derp1a-vpc.tailscale.com'.
For backwards compatibility, --mesh-with still supports individual hostnames.
The logic which attempts to auto-discover '[host]-vpc.tailscale.com' dial hosts has been removed.
Updates tailscale/corp#25653
=> cmd/derper: support explicit configuration of mesh dial hosts

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
There's at least one example of stored routes and advertised routes getting out of sync. I don't know how they got there yet, but this would backfill missing advertised routes on startup from stored routes.
Updates #14606
=> ipn/ipnlocal: re-advertise appc routes on startup

types/lazy/deferred.go, types/lazy/deferred_test.go
This test verifies, among other things, that init functions cannot be deferred after `(*DeferredFuncs).Do` has already been called and that all subsequent calls to `(*DeferredFuncs).Defer` return `false`.
However, the initial implementation of this check was racy: by the time `(*DeferredFuncs).Do` returned, not all goroutines that successfully deferred an init function may have incremented the atomic variable tracking the number of deferred functions. As a result, the variable's value could differ immediately after `(*DeferredFuncs).Do` returned and after all goroutines had completed execution (i.e., after `wg.Wait()`).
In this PR, we replace the original racy check with a different one. Although this new check is also racy, it can only produce false negatives. This means that if the test …
=> types/lazy: fix flaky TestDeferAfterDo

cmd/tailscaled/tailscaled_test.go
As we look to add github.com/prometheus/client_golang/prometheus to
more parts of the codebase, lock in that we don't use it in tailscaled,
primarily for binary size reasons.
Updates #12614
=> cmd/tailscaled: add some more depchecker dep tests

ipn/ipnserver/server.go, ipn/ipnserver/server_test.go
If the server was in use at the time of the initial check, but a user disconnected and was removed from the `activeReqs` map by the time we registered a waiter, the `ready` channel will never be closed, resulting in a deadlock. To avoid this, we check whether the server is still busy after registering the wait.
Fixes #14655
=> ipn/ipnserver: fix a deadlock in (*Server).blockWhileIdentityInUse

cmd/k8s-operator/operator.go
Most users should not run into this because it's set in the helm chart and the deploy manifest, but if namespace is not set we get confusing authz errors because the kube client tries to fetch some namespaced resources as though they're cluster-scoped and reports permission denied. Try to detect namespace from the default projected volume, and otherwise fatal.
To test in a real cluster, delete just the `OPERATOR_NAMESPACE` environment variable from the deployment's spec first, and observe it still runs smoothly. Then set `automountServiceAccountToken: false` in the pod spec and it should fatal with the new log line as the namespace file is no longer available.
Fixes #cleanup
Change-Id: I64b34191e440b61204b9ad30bbfa117abbbe09c3
=> cmd/k8s-operator: require namespace config

net/dns/manager.go, net/dns/manager_test.go
Previously we were doing this unconditionally.
Updates #14428
=> net/dns: only populate OSConfig.Hosts when MagicDNS is enabled

ipn/ipnlocal/local.go, util/syspolicy/policy_keys.go
Updates tailscale/corp#25936
This defines a new syspolicy 'Hostname' and allows an IT administrator to override the value we normally read from `os.Hostname()`. This is particularly useful on Android and iOS devices, where the hostname we get from the OS is really just the device model (a platform restriction to prevent fingerprinting).
If we don't implement this, all devices on the customer's side will look like `google-pixel-7a-1`, `google-pixel-7a-2`, `google-pixel-7a-3`, etc. and it is not feasible for the customer to use the API or worse the admin console to manually fix these names.
=> ipnlocal: allow overriding os.Hostname() via syspolicy

ipn/serve.go, ipn/serve_test.go
As I was looking to fix https://github.com/tailscale/tailscale/issues/11572 I noticed that we `IsFunnelOn` method to check if funnel is actually enabled, but that only checks serve config set in background mode.
This change makes it also check foreground config, thus fixing #11049 
To test that it works on a Linux machine
1. Set shields up
```sh
$ tailscale set --shields-up=true
```
2. Attempt to run funnel in foreground mode and observe error
```sh
$ tailscale funnel 9090
sending serve config: updating config: Unable to turn on Funnel while shields-up is enabled
```
(It will also error out if the order is reversed)
(Looking at #11049 it seems like we might also want a similar check that checks that serve config is not being enabled for nodes that don't allow incoming connections, but …
=> ipn: [serve] warn that funnel in foreground mode won't work if shields are up

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go
This PR is part of a fix for a bug, where a node with any 'AllowFunnel' block set in tailscale serve was being displayed as if having funnel enabled in the admin panel. It adds a new Hostinfo.IngressEnabled field that is set to true if the node has funnel actually enabled.
This will be sent to control and used to determine whether the node should have the 'Funnel' badge.
Updates tailscale/tailscale#11572
Updates tailscale/corp#25931
=> tailcfg,ipn/ipnlocal: send control info whether funnel is actually enabled

cmd/containerboot/serve.go, cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/ingress-for-pg_test.go, cmd/k8s-operator/ingress.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-operator/proxygroup_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/testutils_test.go, cmd/k8s-operator/tsclient.go, cmd/k8s-operator/tsrecorder.go, kube/kubetypes/types.go
This PR adds logic to create/delete/update VIPServices for Kubernetes Ingresses with `tailscale.com/proxy-group` annotation as well as ensure that there is serve config mounted to all the ProxyGroup hosts with VIPService endpoint -> backend Kubernetes Services configuration.
To try this out/workflow:
1. Create an ingress ProxyGroup (day 0)
```
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
name: ts-ing
spec:
type: ingress
replicas: 3
```
2. Create an Ingress resource that refers to the ProxyGroup with a hostname `my-app-eu` (day N)
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
annotations:
tailscale.com/proxy-group: ts-ing
name: my-app
namespace: default
spec:
ingressClassName: tailscale
tls:
- hosts:
- my-app-eu
rules:
- http:
paths:
- backend:
service: …
```
=> cmd/{k8s-operator,containerboot},kube/kubetypes: parse Ingresses for ingress ProxyGroup

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
This reverts commit 1b303ee5baef3ddab40be4d1c2 (#14609).
It caused a deadlock; see tailscale/corp#25965
Updates tailscale/corp#25965
Updates #13680
Updates #14606
=> Revert "ipn/ipnlocal: re-advertise appc routes on startup (#14609)"

prober/derp.go
If unable to accept a connection from the bandwidth probe listener, return from the goroutine immediately since the accepted connection will be nil.
Updates tailscale/corp#25958
=> prober: fix nil pointer access in tcp-in-tcp probes

tailcfg/tailcfg.go
As of tailscale/corp#26003
Updates tailscale/tailscale#11572
=> tailcfg: remove now-unused TailscaleFunnelEnabled method

cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/ingress-for-pg_test.go, cmd/tailscale/cli/advertise.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/serve.go, ipn/ipnlocal/serve_test.go, ipn/serve.go, tailcfg/tailcfg.go, types/netmap/netmap.go
Rather than using a string everywhere and needing to clarify that the string should have the svc: prefix, create a separate type for Service names.
Updates tailscale/corp#24607
Change-Id: I720e022f61a7221644bb60955b72cacf42f59960
=> tailcfg: add ServiceName

cmd/tailscale/cli/cli.go, cmd/tailscale/cli/configure-kube.go, cmd/tailscale/cli/configure-kube_omit.go, cmd/tailscale/cli/configure-synology-cert.go, cmd/tailscale/cli/configure-synology.go, cmd/tailscale/cli/configure.go, cmd/tailscale/cli/configure_apple-all.go, cmd/tailscale/cli/configure_apple.go
Updates tailscale/corp#25278
Adds definitions for new CLI commands getting added in v1.80.
=> cmd/tailscale: define CLI tools to manipulate macOS network and system extensions

cmd/k8s-operator/operator.go
The new ProxyGroup-based Ingress reconciler is causing a fatal log at startup because it has the same name as the existing Ingress reconciler. Explicitly name both to ensure they have unique names that are consistent with other explicitly named reconcilers.
Updates #14583
Change-Id: Ie76e3eaf3a96b1cec3d3615ea254a847447372ea
=> cmd/k8s-operator: fix reconciler name clash

derp/derp.go, wgengine/magicsock/derp.go
Remove "unexpected" labelling of PeerGoneReasonNotHere.
A peer being no longer connected to a DERP server is not an unexpected case and causes confusion in looking at logs.
Fixes tailscale/corp#25609
=> derp,wgengine/magicsock: remove unexpected label

appc/appconnector.go, appc/appconnector_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi.go
If we fail to parse the upstream DNS response in an app connector, we might miss new IPs for the target domain. Log parsing errors to be able to diagnose that.
Updates #14606
=> appc,ipn/ipnlocal: log DNS parsing errors in app connectors

cmd/tailscaled/tailscaled_windows.go, tstest/integration/tailscaled_deps_test_windows.go, util/syspolicy/source/policy_store_windows.go, util/winutil/gp/policylock_windows.go
In v1.78, we started acquiring the GP lock when reading policy settings. This led to a deadlock during Tailscale installation via Group Policy Software Installation because the GP engine holds the write lock for the duration of policy processing, which in turn waits for the installation to complete, which in turn waits for the service to enter the running state.
In this PR, we prevent the acquisition of GP locks (aka `EnterCriticalPolicySection`) during service startup and update the Windows Registry-based `util/syspolicy/source.PlatformPolicyStore` to handle this failure gracefully. The GP lock is somewhat optional; it’s safe to read policy settings without it, but acquiring the lock is recommended when reading multiple values to prevent the Group Policy engine from modifying settings …
=> cmd/tailscaled,util/syspolicy/source,util/winutil/gp: disallow acquiring the GP lock during service startup

net/tstun/wrap.go, util/usermetric/metrics.go, wgengine/filter/filter.go, wgengine/filter/filter_test.go
This PR  adds back the outgoing drop metric that was removed in https://github.com/tailscale/tailscale/pull/14281.
This returns the most common drop reasons when we evaluate the package. We could instead instrument the filter struct with a metrics pointer, but it is quite a lot more involved so I wanted to hear opinions on this first.
Updates #14280
=> util/usermetric: add more drop labels

cmd/derper/derper.go, derp/derp.go, derp/derp_server.go
This PR includes two commits.
1. Move the Conn interface to `derp.go` to clarify that it's used by both the server and client code.
2. Add a command-line flag for configuring the write timeout
Updates tailscale/corp#26045.
=> cmd/derper,derp: make TCP write timeout configurable

util/clientmetric/clientmetric.go
Fixes an oversight where underlying aggregated metrics was published as gauge and not counter.
Fixes #14743
=> util/clientmetric: use counter in aggcounter

ipn/ipnlocal/cert.go
The CN field is technically deprecated; set the requested name in a DNS SAN extension in addition to maximise compatibility with RFC 8555.
I've manually tested issuing a cert before and after this change and there are no differences in the CN or DNS SAN fields in the created cert. I also checked that it does not trigger early renewal - the cache is only keyed on the domain which isn't changing.
Fixes #14762
Change-Id: If5d27f1e7abc519ec86489bf034ac98b2e613043
=> ipn/ipnlocal: include DNS SAN in cert CSR

client/web/src/components/views/login-view.tsx
Removing the advanced options collapsible from the web client login for now ahead of our next client release.
Updates https://github.com/tailscale/tailscale/issues/14568
=> client/web: remove advanced options from web client login

go.mod, go.sum
Manually update the `web-client-prebuilt` package as the GitHub action is failing for some reason.
Updates https://github.com/tailscale/tailscale/issues/14568
=> go.{mod,sum}: update web-client-prebuilt

ipn/ipnlocal/cert.go, ipn/ipnlocal/cert_test.go
Adds an envknob setting for changing the client's ACME directory URL. This allows testing cert issuing against LE's staging environment, as well as enabling local-only test environments, which is useful for avoiding the production rate limits in test and development scenarios.
If this turns out to be more generally useful than just for pre-prod and integration testing, we might want to think about graduating it to a non-debug option in the future, but starting small for now.
Fixes #14761
Change-Id: I191c840c0ca143a20e4fa54ea3b2f9b7cbfc889f
=> ipn/ipnlocal: add debug envknob for ACME directory URL

control/controlclient/map.go
=> control/controlclient: sanitize invalid DERPMap nil Region from control

envknob/featureknob/featureknob.go
Ref: #14372
This PR removes the restriction preventing Unraid installations from using exit nodes.
I have been unable to find a reason for this action. After the restriction was reported to me by Unraid users, I attempted to get information via #14372 and by reaching out to Tailscale directly, with no response via either method.
After removing the restriction, I ran this build on my Unraid test cluster and exit nodes worked properly.
=> fix: allow exit node on unraid

control/controlknobs/controlknobs.go, control/controlknobs/controlknobs_test.go
The AsDebugJSON method (used only for a LocalAPI debug call) always
needed to be updated whenever a new controlknob was added. We had a
test for it, which was nice, but it was a tedious step we don't need
to do. Use reflect instead.
Updates #14788
=> control/controlknobs: make Knobs.AsDebugJSON automatic, not require maintenance

health/health.go, health/health_test.go, health/state.go
Previously we were depending on the GUI(s) to do it.
By doing it in tailscaled, GUIs can be simplified and be
guaranteed to render consistent results.
If warnable A depends on warnable B, if both A & B are unhealhy, only
B will be shown to the GUI as unhealthy. Once B clears up, only then
will A be presented as unhealthy.
Updates #14687
=> health: do Warnable dependency filtering in tailscaled

ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go, ipn/prefs_test.go, types/persist/persist.go, types/persist/persist_clone.go, types/persist/persist_test.go, types/persist/persist_view.go
It was a temporary migration over four years ago. It's no longer
relevant.
Updates #610
=> types/persist: remove Persist.LegacyFrontendPrivateMachineKey

cmd/tailscale/cli/up.go
The warning text is adapted from https://tailscale.com/kb/1028/key-expiry#renewing-keys-for-an-expired-device .
There is already https://github.com/tailscale/tailscale/pull/7575 which presents a warning when connected over Tailscale, however the detection is done by checking SSH environment variables, which are absent within systemd's run0*. That means `--force-reauth` will happily bring down Tailscale connection, leaving the user in despair.
Changing only the help text is by no means a complete solution, but hopefully it will stop users from blindly trying it out, and motivate them to search for a proper solution.
*: https://www.freedesktop.org/software/systemd/man/devel/run0.html
For https://github.com/tailscale/tailscale/issues/3849
=> tailscale/cmd: Add warning to help text of `--force-reauth`

types/views/views.go, types/views/views_test.go
This was flagged by @tkhattra on the merge commit; thanks!
Updates tailscale/corp#25479
Change-Id: Ia8045640f02bd4dcc0fe7433249fd72ac6b9cf52
=> types/views: fix SliceEqualAnyOrderFunc short optimization

cmd/containerboot/healthz.go, cmd/containerboot/main.go, cmd/containerboot/main_test.go, cmd/containerboot/services.go, cmd/containerboot/services_test.go, cmd/containerboot/settings.go, cmd/k8s-operator/egress-eps.go, cmd/k8s-operator/egress-services.go, cmd/k8s-operator/egress-services_test.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-operator/proxygroup_test.go, cmd/k8s-operator/sts.go, k8s-operator/conditions.go, kube/egressservices/egressservices.go, kube/egressservices/egressservices_test.go, kube/kubetypes/types.go
This PR is part of work to reduce downtime during ProxyGroup replica restarts when updates are rolled out.
A ProxyGroup replica can now only be terminated once we've ran a best effort check that cluster traffic for any configured egress endpoints is no longer routed to it.
This PR cannot be tested alone to verify the downtime fix- https://github.com/tailscale/tailscale/pull/14792 is also needed which is rebased on top of this
Currently when a replica N needs to be terminated (for an update rollout):
1. kubelet terminates the Pod N when it sees that the previous replica has been updated and is now ready, as per [statefulset rolling update strategy](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates)
2. `egress-eps reconciler` gets triggered on `Pod` …
=> cmd/{k8s-operator,containerboot},kube: ensure egress ProxyGroup proxies don't terminate while cluster traffic is still routed to them

cmd/k8s-operator/deploy/crds/tailscale.com_proxygroups.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/operator.go, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_proxygroup.go
The HA Ingress functionality is not actually doing anything valuable yet, so don't run the controller in 1.80 release yet.
Updates tailscale/tailscale#24795
=> cmd/k8s-operator temporarily disable HA Ingress controller

ipn/doc.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/network-lock.go, ipn/ipnlocal/network-lock_test.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_test.go, ipn/ipnlocal/serve.go, ipn/ipnlocal/serve_test.go, ipn/localapi/localapi.go
Conventionally, we use views (e.g., `ipn.PrefsView`, `tailcfg.NodeView`, etc.) when dealing with structs that shouldn't be accidentally mutated. However, `ipn.LoginProfile` has been an exception so far, with a mix of passing and returning `LoginProfile` by reference (allowing accidental mutations) and by value (which is wasteful, given its current size of 192 bytes).
In this PR, we generate an `ipn.LoginProfileView` and use it instead of passing/returning `LoginProfiles` by mutable reference or copying them when passing/returning by value. Now, `LoginProfiles` can only be mutated by `(*profileManager).setProfilePrefs`.
Updates #14823
=> ipn: generate LoginProfileView and use it instead of *LoginProfile where appropriate

ipn/ipnauth/access.go, ipn/ipnauth/actor.go, ipn/ipnauth/self.go, ipn/ipnauth/test_actor.go, ipn/ipnlocal/local.go, ipn/ipnserver/actor.go, ipn/localapi/localapi.go, util/syspolicy/policy_keys.go
[3 commits; can be reviewed either by commit or all at once]
In this PR, we update `LocalBackend` to set `WantRunning=true` when applying policy settings to the current profile's prefs, if the "always-on" mode is enabled.
We also implement a new `(*LocalBackend).EditPrefsAs()` method, which is like `EditPrefs` but accepts an `ipnauth.Actor` (e.g., a LocalAPI client's identity) that initiated the change. If `WantRunning` is being set to false, the new `EditPrefsAs` method checks whether the actor has `ipnauth.Disconnect` access to the profile and propagates an error if they do not.
To facilitate this check, we extend the `ipnauth.Actor` interface with a `CheckProfileAccess` method, and implement it for the legacy `ipnserver.actor` to allow a disconnect only if the "always-on" mode is not …
=> ipn/ipn{auth,server,local}: initial support for the always-on mode

ipn/ipnlocal/local.go
The AlwaysOn policy can be applied by `(*LocalBackend).applySysPolicy`, flipping `WantRunning` from false to true before `(*LocalBackend).Start()` has been called for the first time and set a control client in `b.cc`. This results in a `nil` pointer dereference and a panic when `setPrefsLockedOnEntry` applies the change and calls `controlclient.Client.Login()`.
In this PR, we fix it by only doing a login if `b.cc` has been set.
Updates #14823
=> ipn/ipnlocal: fix a panic in setPrefsLockedOnEntry when cc is nil

util/syspolicy/internal/metrics/metrics.go
Dots are not allowed in metric names and cause panics. Since we use dots in policy setting names like `AlwaysOn.OverrideWithReason`, let's replace them with underscores. We don’t want to use `setting.KeyPathSeparator` here just yet to make it fully hierarchical, but we will decide as we progress on the (experimental) `AlwaysOn.*` policy settings.
tailscale/corp#26146
=> util/syspolicy/internal/metrics: replace dots with underscores for metric names

client/tailscale/apitype/apitype.go, client/tailscale/localclient.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnserver/actor.go, ipn/ipnserver/server.go, util/syspolicy/policy_keys.go
In this PR, we update `client/tailscale.LocalClient` to allow sending requests with an optional `X-Tailscale-Reason` header. We then update `ipn/ipnserver.{actor,Server}` to retrieve this reason, if specified, and use it to determine whether `ipnauth.Disconnect` is allowed when the `AlwaysOn.OverrideWithReason` policy setting is enabled. For now, we log the reason, along with the profile and OS username, to the backend log.
Finally, we update `LocalBackend` to remember when a disconnect was permitted and do not reconnect automatically unless the policy changes.
Updates tailscale/corp#26146
=> client/tailscale,ipn/ipn{local,server},util/syspolicy: implement the AlwaysOn.OverrideWithReason policy setting

cmd/tailscale/cli/down.go
If specified, the reason is sent via the LocalAPI for auditing purposes.
Updates tailscale/corp#26146
=> cmd/tailscale/cli: update tailscale down to accept an optional --reason

derp/derphttp/derphttp_server.go, ipn/localapi/debugderp.go, net/captivedetection/captivedetection.go, net/captivedetection/captivedetection_test.go
Observed on some airlines, Squid is configured to cache and transform
these results, which is disruptive. The server and client should both
actively request that this is not done by setting Cache-Control headers.
Send a timestamp parameter to further work against caches that do not
respect the cache-control headers.
Updates https://github.com/tailscale/tailscale/issues/14856
=> derp/derphttp,ipn/localapi,net/captivedetection: add cache resistance to captive portal detection

cmd/sniproxy/sniproxy.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go, types/netmap/netmap.go
Many places that need to work with node/peer capabilities end up with a something-View and need to either reimplement the helper code or make an expensive copy. We have the machinery to easily handle this now.
Change-Id: Ic3f55be329f0fc6c178de26b34359d0e8c6ca5fc
=> tailcfg: add JSON unmarshal helper for view of node/peer capabilities

net/netmon/netmon_darwin.go
We once again have a report of a panic from ParseRIB. This panic guard should probably remain permanent.
Updates #14201
This reverts commit de9d4b2f886b6bf5cf0fe9be6c17d080267acef1.
=> net/netmon: add extra panic guard around ParseRIB

cmd/k8s-operator/deploy/crds/tailscale.com_proxygroups.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/ingress-for-pg_test.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/testutils_test.go, cmd/k8s-operator/tsclient.go, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_proxygroup.go
This change:
- reinstates the HA Ingress controller that was disabled for 1.80 release (reverts https://github.com/tailscale/tailscale/pull/14833)
- fixes the API calls to manage VIPServices as the API was changed
- triggers the HA Ingress reconciler on ProxyGroup changes
I have tested that creation, hostname change and deletion works as expected with this change
(see https://github.com/tailscale/tailscale/pull/14583 for instructions how to test this)
Updates tailscale/tailscale#24795
=> cmd/k8s-operator: reinstate HA Ingress reconciler

ipn/ipnauth/actor.go, ipn/ipnauth/policy.go, ipn/ipnauth/self.go, ipn/ipnauth/test_actor.go, ipn/ipnlocal/local.go, ipn/ipnserver/actor.go
In this PR, we move the code that checks the AlwaysOn policy from `ipnserver.actor` to `ipnauth`. It is intended to be used by `ipnauth.Actor` implementations, and we temporarily make it exported while these implementations reside in `ipnserver` and in corp. We'll unexport it later.
We also update `ipnauth.Actor.CheckProfileAccess` to accept an `auditLogger`, which is called to write details about the action to the audit log when required by the policy, and update `LocalBackend.EditPrefsAs` to use an `auditLogger` that writes to the regular backend log.
Updates tailscale/corp#26146
=> ipn/{ipnauth,ipnlocal,ipnserver}: move the AlwaysOn policy check from ipnserver to ipnauth

ipn/ipnserver/server.go, ipn/localapi/localapi.go, tsnet/tsnet.go
With #14843 merged, `(*localapi.Handler).servePrefs()` now requires a non-nil `Handler.Actor`, and other places may soon require it as well.
In this PR, we update `localapi.NewHandler` with a new required parameter for the actor. We then update `tsnet` to use `ipnauth.Self`.
We also rearrange the code in `(*ipnserver.Server).serveHTTP()` to pass the actor via `Handler`'s constructor instead of the field.
Updates #14823
=> ipn/{ipnserver,localapi},tsnet: use ipnauth.Self as the actor in tsnet localapi handlers

clientupdate/clientupdate.go
When running via tsnet, c2n will be hooked up so requests to update can reach the node. But it will then apply whatever OS-specific update function, upgrading the local tailscaled instead.
We can't update tsnet automatically, so refuse it.
Fixes #14892
=> clientupdate: refuse to update in tsnet binaries

cmd/derper/derper.go
A previous PR accidentally logged the key as part
of an error. Remove logging of the key.
Add logging for setec store setup.
Updates tailscale/corp#25756
=> cmd/derper: remove logging of mesh key

ssh/tailssh/incubator.go
Shells on FreeBSD don't support the -l option. This means that when handling SSH in-process, we can't give the user a login shell, but this change at least allows connecting at all.
Updates #13338
=> ssh: don't use -l option for shells on FreeBSD

docs/windows/policy/tailscale.admx
Something I accidentally added in #14217.
It doesn't seem to impact Intune or the Administrative Templates MMC extension, but it should still be fixed.
=> docs/windows/policy: remove an extra closing >

client/tailscale/localclient_aliases.go
localclient_aliases.go was missing some package level functions from client/local. This adds them.
Updates tailscale/corp#22748
=> client: add missing localclient aliases

ipn/ipnserver/server.go, safesocket/safesocket_darwin.go, safesocket/safesocket_darwin_test.go
updates tailscale/corp#25687
The darwin appstore and standalone  clients now support XPC and the keychain for passing user credentials securely between the gui process and an NEVPNExtension hosted tailscaled. Clients that can communicate directly with the network extension, via XPC or the keychain, are now expected to call SetCredentials and supply credentials explicitly, fixing issues with the cli breaking if the current user cannot read the contents of /Library/Tailscale due to group membership restrictions. This matches how those clients source and supply credentials to the localAPI http client.  
Non-platform-specific code that has traditionally been in the client is moved to safesocket.
/Libraray/Tailscaled/sameuserproof has its permissions changed to that it's readably only by users …
=> safesocket: add ability for Darwin clients to set explicit credentials

cmd/derper/derper.go
Since dynamic reload of setec is not supported in derper at this time, close the server after the secret is loaded.
Updates tailscale/corp#25756
=> cmd/derper: close setec after use

cmd/derper/derper.go
Incorrect disabled support for not having a mesh key in d5316a4fbb4a1105ce2ba6f92d9688452b7747cd
Allow for no mesh key to be set.
Fixes #14928
=> cmd/derper: support no mesh key

scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/14745
Tested on Vultr
Also adds --yes to pkg to match other package managers as it was causing issues when piping the script to `sh`.
=> scripts/installer.sh: add FreeBSD 14

wgengine/netstack/netstack.go
The gVisor RACK implementation appears to perfom badly, particularly in scenarios with higher BDP. This may have gone poorly noticed as a result of it being gated on SACK, which is not enabled by default in upstream gVisor, but itself has a higher positive impact on performance. Both the RACK and DACK implementations (which are now one) have overlapping non-completion of tasks in their work streams on the public tracker.
Updates #9707
=> wgengine/netstack: disable RACK on all platforms

cmd/tailscale/cli/ssh.go
When tailscale is built with the ``ts_include_cli`` tag and the tailscaled binary is symlinked to tailscale (https://tailscale.com/kb/1207/small-tailscale), tailscale ssh fails like:
```console
$ tailscale ssh host -v
...
debug1: Local version string SSH-2.0-OpenSSH_9.7
2024/05/12 22:57:44 tailscaled does not take non-flag arguments: ["nc" "host" "22"]
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```
Closes #12125
=> cmd/tailscale: make ssh command work when tailscaled is built with the ts_include_cli tag

cmd/natc/natc.go
These tunings reduced memory usage while the implementation was struggling with earlier bugs, but will no longer be necessary after those bugs are addressed.
Depends #14933
Depends #14934
Updates #9707
Updates #10408
Updates tailscale/corp#24483
Updates tailscale/corp#25169
=> cmd/natc: remove speculative tuning from natc

wgengine/netstack/netstack.go
When in tun mode on Linux, AllowedIPs are not automatically added to netstack because the kernel is responsible for handling subnet routes. This ensures that virtual IPs are always added to netstack.
When in tun mode, pings were also not being handled, so this adds explicit support for ping as well.
Fixes tailscale/corp#26387
Change-Id: I6af02848bf2572701288125f247d1eaa6f661107
=> wgengine/netstack: respond to service IPs in Linux tun mode

scripts/installer.sh
This argument apparently has to be before the package name
Updates #14745
=> scripts/installer.sh: fix --yes argument for freebsd

ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_test.go
Currently, `profileManager` filters profiles based on their creator/owner and the "current user"'s UID. This causes `DefaultUserProfileID(uid ipn.WindowsUserID)` to work incorrectly when the `uid` doesn't match the current user.
While we plan to remove the concept of the "current user" completely, we're not there yet.
In this PR, we fix `DefaultUserProfileID` by updating `profileManager` to allow checking profile access for a given UID and modifying helper methods to accept UID as a parameter when returning matching profiles.
Updates #14823
=> ipn/ipnlocal: fix (*profileManager).DefaultUserProfileID for users other than current

ipn/ipnlocal/local.go, ipn/ipnserver/server.go
There’s `(*LocalBackend).ResetForClientDisconnect`, and there’s also `(*LocalBackend).resetForProfileChangeLockedOnEntry`. Both methods essentially did the same thing but in slightly different ways. For example, `resetForProfileChangeLockedOnEntry` didn’t reset the control client until `(*LocalBackend).Start()` was called at the very end and didn’t reset the `keyExpired` flag, while `ResetForClientDisconnect` didn’t reinitialize TKA.
Since `SetCurrentUser` can be called with a nil argument to reset the currently connected user and internally calls `resetForProfileChangeLockedOnEntry`, we can remove `ResetForClientDisconnect` and let `SetCurrentUser` and `resetForProfileChangeLockedOnEntry` handle it.
Updates #14823
=> ipn/ipn{local,server}: remove ResetForClientDisconnect in favor of SetCurrentUser(nil)

control/controlclient/direct.go, control/controlclient/map.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/serve_test.go, ipn/ipnstate/ipnstate.go, types/netmap/netmap.go
Smaller.
Updates tailscale/corp#26058 (@andrew-d noticed during this)
=> types/netmap,*: pass around UserProfiles as views (pointers) instead

tailcfg/tailcfg.go
This is deprecated anyway, and we don't need to be sending `"Bits":null` on the wire for the majority of clients.
Updates tailscale/corp#20965
Updates tailscale/corp#26353
Change-Id: I95a3e3d72619389ae34a6547ebf47043445374e1
=> tailcfg: make NetPortRange.Bits omitempty

ipn/ipnlocal/local.go, ipn/ipnlocal/profiles.go, ipn/ipnserver/server.go
Currently, we disconnect Tailscale and reset `LocalBackend` on Windows when the last LocalAPI client disconnects, unless Unattended Mode is enabled for the current profile. And the implementation is somewhat racy since the current profile could theoretically change after `(*ipnserver.Server).addActiveHTTPRequest` checks `(*LocalBackend).InServerMode()` and before it calls `(*LocalBackend).SetCurrentUser(nil)` (or, previously, `(*LocalBackend).ResetForClientDisconnect()`).
Additionally, we might want to keep Tailscale running and connected while a user is logged in rather than tying it to whether a LocalAPI client is connected (i.e., while the GUI is running), even when Unattended Mode is disabled for a profile. This includes scenarios where the new AlwaysOn mode is enabled, as well as …
=> ipn/ipn{local,server}: move "staying alive in server mode" from ipnserver to LocalBackend

docs/windows/policy/en-US/tailscale.adml, docs/windows/policy/tailscale.admx
This adds a new policy definition for the `AlwaysOn.Enabled` policy setting as well as the `AlwaysOn.OverrideWithReason` sub-option.
Group Policy:
Intune:
Updates #14823
Updates tailscale/corp#26247
=> docs/windows/policy: update ADMX/ADML policy definitions to include the new Always On setting

control/controlclient/map.go
This reverts commit 413fb5b93311972e3a8d724bb696607ef3afe6f2.
See long story in #14992
Updates #14992
Updates tailscale/corp#26058
=> Revert "control/controlclient: delete unreferenced mapSession UserProfiles"

ipn/ipnlocal/local.go, ipn/ipnlocal/profiles.go, ipn/ipnserver/actor.go
In this PR, we further refactor `LocalBackend` and Unattended Mode to extract the logic that determines which profile should be used at the time of the check, such as when a LocalAPI client connects or disconnects. We then update `(*LocalBackend).switchProfileLockedOnEntry()` to to switch to the profile returned by `(*LocalBackend).resolveBestProfileLocked()` rather than to the caller-specified profile, and rename it to `switchToBestProfileLockedOnEntry()`.
This is done in preparation for updating `(*LocalBackend).getBackgroundProfileLocked()` to support Always-On mode by determining which profile to use based on which users, if any, are currently logged in and have an active foreground desktop session.
Updates #14823
Updates tailscale/corp#26247
=> ipn/ipn{local,server}: extract logic that determines the "best" Tailscale profile to use

types/bools/bools.go
The Select function was renamed as IfElse.
=> types/bools: fix doc typo

cmd/tailscale/cli/file.go, ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go
Introduce new TaildropTargetStatus in PeerStatus
Refactor getTargetStableID to solely rely on Status() instead of calling FileTargets(). This removes a possible race condition between the two calls and provides more detailed failure information if a peer can't receive files.
Updates tailscale/tailscale#14393
=> ipn, tailscale/cli: add TaildropTargetStatus and remove race with FileTargets

control/controlclient/map.go, tailcfg/tailcfg.go, types/netmap/netmap.go, types/netmap/nodemut.go
This will be used by clients to make better decisions on when to warn users about impending key expiry.
Updates tailscale/corp#16016
=> tailcfg: read max key duration from node cap map [capver 114]

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, tailcfg/tailcfg.go
See https://github.com/tailscale/tailscale/pull/14688#discussion_r1921631506 for context
Hostinfo.WireIngress is used as a hint that the node intends to use funnel. We now send another field, IngressEnabled, in cases where funnel is explicitly enabled, and the logic control-side has been changed to look at IngressEnabled as well as WireIngress in all cases where previously the hint was used - so we can now stop sending WireIngress when IngressEnabled is true to save some bandwidth.
I have tested that with this new logic an ingress DNS record still gets created for a node whose serve config contains a disabled funnel endpoint as well as that enabled funnel endpoint can be reached from the internet.
Updates tailscale/tailscale#11572
Updates tailscale/corp#25931
=> ipn/ipnlocal,tailcfg: don't send WireIngress if IngressEnabled is true

appc/appconnector.go, appc/appconnector_test.go, appc/appctest/appctest.go
`routeAdvertiser` is the `iplocal.LocalBackend`. Calls to `Advertise/UnadvertiseRoute` end up calling `EditPrefs` which in turn calls `authReconfig` which finally calls `readvertiseAppConnectorRoutes` which calls `AppConnector.DomainRoutes` and gets stuck on a mutex that was already held when `routeAdvertiser` was called.
Make all calls to `routeAdvertiser` in `app.AppConnector` go through the execqueue instead as a short-term fix.
Updates tailscale/corp#25965
=> appc: fix a deadlock in route advertisements

cmd/gitops-pusher/gitops-pusher.go
This will help debug unexpected issues encountered by consumers of the gitops-pusher.
Updates tailscale/corp#26664
=> cmd/gitops-pusher: log error details when unable to fetch ACL ETag

cmd/derper/derper.go, net/ktimeout/ktimeout_linux_test.go
There's nothing about it on
https://github.com/multipath-tcp/mptcp_net-next/issues/ but empirically MPTCP doesn't support this option on awly's kernel 6.13.2 and in GitHub actions.
Updates #15015
=> various: disable MPTCP when setting TCP_USER_TIMEOUT sockopt

go.mod, go.sum, tempfork/acme/acme.go, tempfork/acme/acme_test.go, tempfork/acme/http.go, tempfork/acme/types.go
https://github.com/tailscale/golang-x-crypto/commit/9a281fd8facad954dae80ef984c5d5d763f8ff91
Updates #15015
=> tempfork/acme: pull in latest changes for Go 1.24

client/tailscale/acl.go, client/tailscale/tailscale.go, client/tailscale/tailscale_test.go
This method uses `path.Join` to build the URL. Turns out with 1.24 this
started stripping consecutive "/" characters, so "http://..." in baseURL
becomes "http:/...".
Also, `c.Tailnet` is a function that returns `c.tailnet`. Using it as a
path element would encode as a pointer instead of the tailnet name.
Finally, provide a way to prevent escaping of path elements e.g. for `?`
in `acl?details=1`.
Updates #15015
=> client/tailscale: fix Client.BuildURL and Client.BuildTailnetURL

scripts/installer.sh
Fixes #15075 (TSS-53630)
Tested in VM
=> scripts/installer.sh: add SparkyLinux as a Debian derivative

tstest/deptest/deptest.go
For tests (in another repo) that use cgo, we'd like to set CGO_ENABLED=1
explicitly when evaluating cross-compiled deps with "go list".
Updates tailscale/corp#26717
Updates tailscale/corp#26737
=> tstest/deptest: add DepChecker.ExtraEnv option for callers to set

docs/windows/policy/en-US/tailscale.adml, docs/windows/policy/tailscale.admx, ipn/ipnlocal/local.go, util/syspolicy/policy_keys.go
In this PR, we update the `LocalBackend` so that when the `ReconnectAfter` policy setting is configured and a user disconnects Tailscale by setting `WantRunning` to `false` in the profile prefs, the `LocalBackend` will now start a timer to set `WantRunning` back to `true` once the timer expires.
We also update the ADMX/ADML policy definitions to allow configuring this policy setting for Windows via Group Policy and Intune.
Updates #14824
=> ipn/ipnlocal,util/syspolicy,docs/windows/policy: implement the ReconnectAfter policy setting

cmd/derper/derper.go, derp/derp_server.go
=> cmd/derper: add --socket flag to change unix socket path to tailscaled

go.mod, go.sum
There were two recent CVEs. The one that sorta affects us is https://groups.google.com/g/golang-announce/c/qN_GDasRQSA (SSH DoS).
Full diff: https://github.com/golang/crypto/compare/v0.33.0...v0.35.0
Updates #15124
=> go.mod: bump golang.org/x/crypto

maths/ewma.go, maths/ewma_test.go
In order to improve latency tracking, we will use an exponentially weighted moving average that will smooth change over time and suppress large outlier values.
Updates tailscale/corp#26649
=> maths: add exponentially weighted moving average type

scripts/installer.sh
Ensures default Linux umask 022 for the installer script to make sure that files created by the installer can be accessed by other tools, such as apt-get
I have tested that with this setting the installer script succeeds on a system where umask is 027 (and tested that without this setting it fails).
Alternatively, I could have modified permissions on individual artifacts created by this script (i.e. chmod `/usr/share/keyrings/tailscale-archive-keyring.gpg` to make sure `apt-get` can read it- but that would have the downside that as we are adding more install methods to the script this could break again).
I have only tested this on Debian, but `umask` should work on all Linux flavours and MacOS.
Updates tailscale/tailscale#15133
=> scripts/installer.sh: ensure default umask for the installer

go.mod, go.sum, types/opt/value.go, types/prefs/item.go, types/prefs/list.go, types/prefs/map.go, types/prefs/prefs.go, types/prefs/prefs_example/prefs_types.go, types/prefs/prefs_test.go, types/prefs/struct_list.go, types/prefs/struct_map.go, util/syspolicy/internal/internal.go, util/syspolicy/setting/origin.go, util/syspolicy/setting/raw_item.go, util/syspolicy/setting/snapshot.go, util/syspolicy/setting/summary.go
The upstream module has seen significant work making the v1 emulation layer a high fidelity re-implementation of v1 "encoding/json".
This addresses several upstream breaking changes:
* MarshalJSONV2 renamed as MarshalJSONTo
* UnmarshalJSONV2 renamed as UnmarshalJSONFrom
* Options argument removed from MarshalJSONV2
* Options argument removed from UnmarshalJSONV2
Updates #791
=> go.mod: bump github.com/go-json-experiment/json

types/opt/value_test.go, types/prefs/list.go, types/prefs/prefs.go, types/prefs/prefs_example/prefs_types.go, types/prefs/prefs_test.go, util/syspolicy/setting/origin.go, util/syspolicy/setting/raw_item.go, util/syspolicy/setting/snapshot.go, util/syspolicy/setting/summary.go
The json/v2 prototype is still in flux and API can/will change.
Statically enforce that types implementing the v2 methods satisfy the correct interface so that changes to the signature can be statically detected by the compiler.
Updates tailscale/corp#791
=> all: statically enforce json/v2 interface satisfaction

client/web/web.go, client/web/web_test.go
Fix the order of the CSRF handlers (HTTP plaintext context setting, _then_ enforcement) in the construction of the web UI server. This resolves false-positive "invalid Origin" 403 exceptions when attempting to update settings in the web UI.
Add unit test to exercise the CSRF protection failure and success cases for our web UI configuration.
Updates #14822
Updates #14872
=> client/web: fix CSRF handler order in web UI (#15143)

ipn/ipnlocal/cert.go, ipn/ipnlocal/cert_test.go, ipn/store/kubestore/store_kube.go, ipn/store/kubestore/store_kube_test.go, kube/kubeclient/fake_client.go
This PR ensures that newly issued (or renewed) TLS cert and key are written to kube state store in a single update rather two separate ones, to reduce the chances for duplicate issuances/slowness if another request is received while the Secret contains the old (and still valid) cert, but has already been updated with a new key.
See tailscale/tailscale#15134 for context how this will improve the general case for kube nodes, however my primary goal is enable cert sharing between proxies that serve the same VIPService, see [design](https://docs.google.com/document/d/1o5HB5dwt0aciioTYYYSDqw_USj6a9tntHuGf13_vXsQ/edit?tab=t.0#heading=h.wv25t32lpzd9) (not a public link).
This PR:
- introduces a single method for writing cert and key to store
- the file store keeps the existing behaviour
- the …
=> ipn/{ipnlocal,store},kube/kubeclient: store TLS cert and key pair to a Secret in a single update

safesocket/safesocket_darwin.go, safesocket/safesocket_darwin_test.go
fixes tailscale/corp#26806
Fixes a regression where LocalTCPPortAndToken needs to error out early if we're not running as sandboxed macOS so that we fallback to the 'normal' unix socket machinery.
=> safesocket: return an error for LocalTCPPortAndToken for non-sandboxed clients

licenses/README.md
Add description of the license reports in this directory and brief instructions for reviewers. I recently needed to convert these to CSV, so I also wanted to place to stash that regex so I didn't lose it.
=> licenses: add README

go.mod, go.sum, util/eventbus/bus.go, util/eventbus/bus_test.go, util/eventbus/doc.go, util/eventbus/publish.go, util/eventbus/queue.go, util/eventbus/subscribe.go
This PR has early bits and pieces of debugging facilities plumbed in (tracking of publishers/subscribers, abillity to dump queue contents), but not complete or exposed yet. I can remove them if desired, but they seemed harmless enough and are a minor pain to extract.
=> util/eventbus: initial implementation of an in-process event bus

ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go
We previously were not merging in the TaildropTarget into the PeerStatus because we did not update AddPeer.
Updates tailscale/tailscale#14393
=> ipn: update AddPeer to include TaildropTarget

scripts/installer.sh
The fix in https://github.com/tailscale/tailscale/pull/15139 for ensuring that downloaded files are readable by apt-get on systems with restricted umask was not really working - when we `curl <file> | sudo tee <path>` the umask set at the top of the install script is not inherited by `sudo`, so this was only working if the whole script was run with `sudo`, see https://github.com/tailscale/tailscale/issues/15133#issuecomment-2686551161
This instead chmods the files that I observed are otherwise created with `0640` permission when umask is `027`.
I think this time I've tested it properly:
```
$ umask
0027
$ sudo less /etc/sudoers | grep umask
Defaults umask=027
$ ./installer.sh  # installer script from this PR
Installing Tailscale for debian bookworm, using method apt
+ sudo mkdir -p …
```
=> scripts/installer.sh: explicitly chmod 0644 installed files

ipn/store/kubestore/store_kube.go, ipn/store/kubestore/store_kube_test.go
Reads use the sanitized form, so unsanitized keys being stored in memory resulted in lookup failures, for example for serve config, where the key in non-sanitized form is like `serve/xyz`, in sanitized form `serve_xyz`.
Updates tailscale/tailscale#15134
=> ipn/store/kubestore: sanitize keys loaded to in-memory store

safesocket/safesocket_darwin.go, safesocket/safesocket_darwin_test.go
fixes tailscale/corp#26806
The fix for this was incorrect. We care only if the caller is the macSys or macOs app.  isSandBoxedMacOS doesn't give us the correct answer for macSys because technically, macsys isn't sandboxed anymore.
This is the correct logic:
version.IsMacAppStore() || version.IsMacSysApp()
=> safesocket: correct logic for determining if we're a macOS GUI client

safesocket/safesocket_darwin.go
fixes tailscale/corp#26806
IsMacSysApp is not returning the correct answer... It looks like the rest of the code base uses
isMacSysExt (when what they really want to know is isMacSysApp).   To fix the immediate issue (localAPI and 
the CLA are broken entirely in corp), we'll add this check to safesocket which matches other usages, despite
the confusing naming.
=> safesocket: add isMacSysExt Check

cmd/hello/hello.go, tailcfg/tailcfg.go
We are soon going to start assinging shared-in nodes a CGNAT IPv4 in the Hello tailnet when necessary, the same way that normal node shares assign a new IPv4 on conflict.
But Hello wants to display the node's native IPv4, the one it uses in its own tailnet. That IPv4 isn't available anywhere in the netmap today, because it's not normally needed for anything.
We are going to start sending that native IPv4 in the peer node CapMap, only for Hello's netmap responses. This change enables Hello to display that native IPv4 instead, when available.
Updates https://github.com/tailscale/corp/issues/25393
Change-Id: I87480b6d318ab028b41ef149eb3ba618bd7f1e08
Signed-off-by: Brian Palmer <brianp@tailscale.com>
=> hello: display native ipv4

util/eventbus/bus.go, util/eventbus/bus_test.go, util/eventbus/client.go, util/eventbus/doc.go, util/eventbus/publish.go, util/eventbus/subscribe.go
The Client carries both publishers and subscribers for a single actor. This makes the APIs for publish and subscribe look more similar, and this structure is a better fit for upcoming debug facilities.
Updates #15160
---
Package docs in HTML form are at http://rigel.corp.ts.net:8185/pkg/tailscale.com/util/eventbus/
=> util/eventbus: rework to have a Client abstraction

util/eventbus/bus.go, util/eventbus/publish.go, util/eventbus/subscribe.go
This makes the helpers closer in behavior to cancelable contexts and taskgroup.Single, and makes the worker code use a more normal and easier to reason about context.Context for shutdown.
Updates #15160
=> util/eventbus: adjust worker goroutine management helpers

cmd/tsidp/Dockerfile, cmd/tsidp/README.md
Adds documentation in a README for the tsidp tool. ~Adds the setup script written by @IronicBadger.~ Adds a Dockerfile for deployment.
Updates #15204
=> cmd/tsidp: add README and Dockerfile

.github/workflows/natlab-integrationtest.yml
The natlab VM tests are flaking on GitHub Actions.
To not distract people, disable them for now (unless they're touched
directly) until they're made more reliable, which will be some painful
debugging probably.
Updates #13038
=> .github/workflows: descope natlab CI for now until GitHub flakes are fixed

util/eventbus/bus.go, util/eventbus/client.go, util/eventbus/publish.go, util/eventbus/queue.go, util/eventbus/subscribe.go
Just a preparation step to adding APIs that let debugging tools look at this information. The 3 commits are properly scoped changes and can be looked at individually, or all together.
Updates #15160
=> util/eventbus: track additional event metadata on their trip through the bus

cmd/tsidp/tsidp.go
Use secure constant time comparisons for the client ID and secret values
during the allowRelyingParty authorization check.
Signed-off-by: Patrick O'Doherty <patrick@tailscale.com>
=> cmd/tsidp: use constant time comparison for client_id/secret

cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/ingress-for-pg_test.go, cmd/k8s-operator/ingress.go, cmd/k8s-operator/operator.go
This PR ensures that the HA Ingress can operate in multi-cluster mode.
This adds multi-cluster support to the main reconcile flow (i.e. there is no need for user to explicitly opt-in).
The goal is to ensure that VIPServices are cleaned up when an Ingress(es) for whom they were created are deleted, but also ensures that a VIPService is not deleted when there are still Ingresses using them.
We use the VIPService's Comment field to store an operator-specific owner reference to a list of such owner references.
The lifecycle flow is:
- if during HA Ingress resource creation, a VIPService with some other operator's owner reference is already found, just update the owner references to add one for this operator
- if during HA Ingress deletion, the VIPService is found to have owner reference(s) …
=> cmd/k8s-operator: ensure HA Ingress can operate in multicluster mode.

util/eventbus/bus.go, util/eventbus/client.go, util/eventbus/debug.go, util/eventbus/publish.go, util/eventbus/subscribe.go
Updates #15160 
---
This is just the internal machinery, with no exported interfaces yet. I added hooks at 3 points: in each publisher right before it tries to enqueue (i.e. the earliest possible point to observe an event), in the router after it's looked up subscribers but before it distributes the event to them (where an observer sees things in the global linear order, and can see the 1:N fanout to subscribers), and in subscribers right after an event has been delivered (where you can see e2e delivery latency, and total order as perceived by that one subscriber).
I'm honestly unsure if all these hook points have value, or if we'll end up retooling towards something more like trace spans once we've build out the debug facilities. But, this is a simple and straightforward place to start.
=> util/eventbus: initial plumbing for introspection hooks

cmd/derper/cert.go, cmd/derper/cert_test.go, derp/derphttp/derphttp_client.go, net/tlsdial/tlsdial.go, tailcfg/derpmap.go
For people who can't use LetsEncrypt because it's banned.
Per https://github.com/tailscale/tailscale/issues/11776#issuecomment-2520955317
This does two things:
1) if you run derper with --certmode=manual and --hostname=$IP_ADDRESS
we previously permitted, but now we also:
* auto-generate the self-signed cert for you if it doesn't yet exist on disk
* print out the derpmap configuration you need to use that
self-signed cert
2) teaches derp/derphttp's derp dialer to verify the signature of
self-signed TLS certs, if so declared in the existing
DERPNode.CertName field, which previously existed for domain fronting,
separating out the dial hostname from how certs are validates,
so it's not overloaded much; that's what it was meant for.
Fixes #11776
=> cmd/derper, derp/derphttp: support, generate self-signed IP address certs

control/controlclient/direct.go, control/controlclient/map.go, tstest/integration/nat/nat_test.go, wgengine/magicsock/derp.go, wgengine/magicsock/endpoint.go
If we get a packet in over some DERP and don't otherwise know how to
reply (no known DERP home or UDP endpoint), this makes us use the
DERP connection on which we received the packet to reply. This will
almost always be our own home DERP region.
This is particularly useful for large one-way nodes (such as
hello.ts.net) that don't actively reach out to other nodes, so don't
need to be told the DERP home of peers. They can instead learn the
DERP home upon getting the first connection.
This can also help nodes from a slow or misbehaving control plane.
Updates tailscale/corp#26438
=> wgengine/magicsock: use learned DERP route as send path of last resort

ipn/ipnlocal/local.go
We're computing the list of services to hash by iterating over the values of a map, the ordering of which is not guaranteed. This can cause the hash to fluctuate depending on the ordering if there's more than one service hosted by the same host.
Updates tailscale/corp#25733.
=> ipn: sort VIP services before hashing

net/portmapper/upnp.go, net/portmapper/upnp_test.go
We previously retried getting a UPnP mapping when the device returned error code 725, "OnlyPermanentLeasesSupported". However, we've seen devices in the wild also return 402, "Invalid Args", when given a lease duration. Fall back to the no-duration mapping method in these cases.
Updates #15223
Change-Id: I6a25007c9eeac0dac83750dd3ae9bfcc287c8fcf
=> net/portmapper: retry UPnP when we get an "Invalid Args"

.github/workflows/test.yml
Delete files from `$(go env GOCACHE)` and `$(go env GOMODCACHE)/cache`
that have not been modified in >= 90 minutes as these files are not
resulting in cache hits on the current branch.
These deltions have resulted in the uploaded / downloaded compressed
cache size to go down to ~1/3 of the original size in some instances
with the extracted size being ~1/4 of the original extraced size.
Updates https://github.com/tailscale/tailscale/issues/15238
=> .github/workflows: tidy go caches before uploading

util/eventbus/bus.go, util/eventbus/client.go, util/eventbus/debug.go, util/eventbus/doc.go, util/eventbus/publish.go, util/eventbus/subscribe.go
Enables monitoring events as they flow, listing bus clients, and snapshotting internal queues to troubleshoot stalls.
Updates #15160
=> util/eventbus: initial debugging facilities for the event bus

util/eventbus/bus.go, util/eventbus/client.go
If any debugging hook might see an event, Publisher.ShouldPublish should tell its caller to publish even if there are no ordinary subscribers.
Updates #15160
=> util/eventbus: don't allow publishers to skip events while debugging

util/eventbus/client.go, util/eventbus/debug.go, util/eventbus/subscribe.go
This lets debug tools list the types that clients are wielding, so that they can build a dataflow graph and other debugging views.
Updates #15160
=> util/eventbus: add debugger methods to list pub/sub types

cmd/tsidp/tsidp.go
Add support for Cross-Origin XHR requests to the openid-configuration
endpoint to enable integrations like Grafana whose web UI auto-populates 
the OIDC setup data from its contents.
Updates https://github.com/tailscale/tailscale/issues/10263
Signed-off-by: Patrick O'Doherty <patrick@tailscale.com>
=> cmd/tsidp: allow CORS requests to openid-configuration

net/netmon/loghelper.go, net/netmon/loghelper_test.go, wgengine/magicsock/magicsock.go
This adds a new helper to the netmon package that allows us to rate-limit log messages, so that they only print once per (major) LinkChange event. We then use this when constructing the portmapper, so that we don't keep spamming logs forever on the same network.
Updates #13145
Change-Id: I6e7162509148abea674f96efd76be9dffb373ae4
=> net/netmon, wgengine/magicsock: be quieter with portmapper logs

tsweb/debug.go
Allow customizing the title on the debug index page.  Also add methods for registering http.HandlerFunc to make it a little easier on callers.
Updates tailscale/corp#27058
=> tsweb: add title to DebugHandler and helper registration methods

envknob/envknob.go, ipn/ipnlocal/cert.go, ipn/ipnlocal/cert_test.go
Make it possible to run cert logic in 'read only' mode, so that, for the given tailscale instance, it only returns certs from store, but never attempts to issue or renew them.
This is primarily for the Kubernetes Operator's HA Ingress where multiple replicas will be serving the same HTTPS endpoint. We don't want each replica to issue a cert for the endpoint (LE rate limits), so we'll be designating one replica to pre-issue and renew the cert. We will be able to ensure that cert issuance is done (attempted) before a non-primary replica would get an HTTPS request, so there isn't really a need to synchronize first issuance, however, renewal can be triggered at any point, so we need 'read only' mode to prevent redundant issuances during renewal
The read-only mode is configurable via a new …
=> ipn/ipnlocal, envknob: make it possible to configure the cert client to act in read-only mode

cmd/containerboot/certs.go, cmd/containerboot/certs_test.go, cmd/containerboot/main.go, cmd/containerboot/serve.go, cmd/containerboot/serve_test.go, cmd/containerboot/settings.go, cmd/containerboot/tailscaled.go
When ran as HA Ingress node, containerboot now can determine whether it should manage TLS certs for the HA Ingress replicas and call the LocalAPI cert endpoint to ensure initial issuance and renewal of the shared TLS certs.
This PR is just the containerboot section of the whole of the work to ensure that HA Ingress replicas share TLS certs. See https://github.com/tailscale/tailscale/tree/irbekrm/certsharev2 for full changes to containerboot, kube store and the operator.
The rest of the changes will be in:
- https://github.com/tailscale/tailscale/pull/15307
- https://github.com/tailscale/tailscale/pull/15308
=> cmd/containerboot: manage HA Ingress TLS certs from containerboot

client/tailscale/devices.go
These are documented, but have not yet been defined in the client.
https://tailscale.com/api#tag/devices/GET/device/{deviceId}
Updates tailscale/corp#27050
=> client/tailscale: add tailnet lock fields to Device struct

util/eventbus/debughttp.go, util/eventbus/debughttp_ios.go
The use of html/template causes reflect-based linker bloat. Longer term we have options to bring the UI back to iOS, but for now, cut it out.
Updates #15297 
---
First step of getting eventbus wired into tailscaled without the dependency sadness happening.
=> util/eventbus: remove debug UI from iOS build

cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_test.go
There was a flaky failure case where renaming a TLS hostname for an ingress might leave the old hostname dangling in tailscaled config. This happened when the proxygroup reconciler loop had an outdated resource version of the config Secret in its cache after the ingress-pg-reconciler loop had very recently written it to delete the old hostname. As the proxygroup reconciler then did a patch, there was no conflict and it reinstated the old hostname.
This commit updates the patch to an update operation so that if the resource version is out of date it will fail with an optimistic lock error. It also checks for equality to reduce the likelihood that we make the update API call in the first place, because most of the time the proxygroup reconciler is not even making an update to the Secret in …
=> cmd/k8s-operator: update ProxyGroup config Secrets instead of patch

client/web/web.go, client/web/web_test.go
This makes the web server running inside tailscaled on 100.100.100.100:80 support requests with
`Host: 100.100.100.100:80` and its IPv6 equivalent.
Prior to this commit, the web server replied to
such requests with a redirect to the node's Tailscale IP:5252.
This fix should be fine because:
1. Specifying port 80 in the Host header for requests to port 80 is permitted.
2. Prometheus, when pointed to scrape 100.100.100.100/metrics sends "Host: 100.100.100.100:80" and there's no way to make it not specify the port in that header.
Fixes https://github.com/tailscale/tailscale/issues/14415
=> web: Support Host 100.100.100.100:80 in tailscaled web server

ipn/conf.go, ipn/ipnlocal/local_test.go
If conffile is used to configure tailscaled, always update currently advertised services from conffile, even if they are empty in the conffile, to ensure that it is possible to transition to a state where no services are advertised.
=> ipn: ensure that conffile is source of truth for advertised services.

ipn/ipnlocal/local.go
`(*LocalBackend).setControlClientLocked()` is called to both set and reset `b.cc`. We shouldn't attempt to start the audit logger when `b.cc` is being reset (i.e., `cc` is `nil`).
However, it's fine to start the audit logger if `b.cc` implements `auditlog.Transport`, even if it's not a `controlclient.Auto` but a mock control client.
In this PR, we fix both issues and add an assertion that `*controlclient.Auto` is an `auditlog.Transport`. This ensures a compile-time failure if `*controlclient.Auto` ever stops being a valid transport due to future interface or implementation changes.
Updates tailscale/corp#26435
=> ipn/ipnlocal: do not attempt to start the auditlogger with a nil transport

net/portmapper/igd_test.go, net/portmapper/portmapper.go, net/portmapper/portmapper_test.go, net/portmapper/select_test.go, net/portmapper/upnp_test.go
When an event bus is configured, publish an event each time a new port mapping
is updated. Publication is unconditional and occurs prior to calling any
callback that is registered. For now, the callback is still fired in a separate
goroutine as before -- later, those callbacks should become subscriptions to
the published event.
For now, the event type is defined as a new type here in the package. We will
want to move it to a more central package when there are subscribers. The event
wrapper is effectively a subset of the data exported by the internal mapping
interface, but on a concrete struct so the bus plumbing can inspect it.
Add a basic functionality test just to verify that the publication occurs.
I changed a bit of the control flow to support publication, but there is a lot
more …
=> net/portmapper: fire an event when a port mapping is updated

cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/ingress-for-pg_test.go, internal/client/tailscale/vip_service.go
Switch from using the Comment field to a ts-scoped annotation for tracking which operators are cooperating over ownership of a VIPService.
Change-Id: I72d4a48685f85c0329aa068dc01a1a3c749017bf
=> cmd/k8s-operator,internal/client/tailscale: use VIPService annotations for ownership tracking

tstest/integration/integration_test.go
As an example, without this patch you might get:
```
integration_test.go:1945: failure/timeout waiting for transition to Running status: decoding tailscale status JSON: invalid character 'a' in literal true (expecting 'r')
```
(and that line of code is the `AwaitRunning` function itself)
With the patch you'd get:
```
integration_test.go:534: failure/timeout waiting for transition to Running status: decoding tailscale status JSON: invalid character 'a' in literal true (expecting 'r')
json:
tailscale.toolchain.rev = "4fdaeeb8fe43bcdb4e8cc736433b9cd9c0ddd221", want "2b494987ff3c1a6a26e10570c490394ff0a77aa4"; but ignoring due to TS_PERMIT_TOOLCHAIN_MISMATCH=1
{
"Version": "1.81.118-t504c0203b",
"TUN": false,
"BackendState": "Running",
"HaveNodeKey": true,
...
```
Which makes it much clearer …
=> tstest: make it clearer where AwaitRunning failed and why

safesocket/safesocket.go
Noticed while working on a dev tool that uses local.Client.
=> safesocket: respect context timeout when sleeping for 250ms in retry loop

pkgdoc_test.go
The `.git/` directory is the Git repository and not part of the working tree.
This patch fixes spurious failures because something inside `.git/` has a `.go` suffix. For example, there’s a branch named `c22wen/magicsock.go` which is definitely not a Go source file.
``` console
sfllaw@host:~/tailscale$ git fetch origin c22wen/magicsock.go
From https://github.com/tailscale/tailscale
* branch                c22wen/magicsock.go -> FETCH_HEAD
sfllaw@host:~/tailscale$ go test . -run 'TestPackageDocs'
=== RUN   TestPackageDocs
pkgdoc_test.go:46: failed to ParseFile ".git/logs/refs/remotes/origin/c22wen/magicsock.go": .git/logs/refs/remotes/upstream/c22wen/magicsock.go:1:1: expected 'package', found 0000000000000000000000000000000000000000 (and 1 more errors)
--- FAIL: TestPackageDocs (0.01s) …
```
=> all: skip looking for package comments in .git/ repository

tstest/mts/mts.go
To let you easily run multiple tailscaled instances for development
and let you route CLI commands to the right one.
Updates #15145
=> tstest/mts: add multiple-tailscaled development tool

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi.go, net/netmon/interfaces_test.go, net/netmon/netmon.go, net/netmon/state.go
Currently nobody calls SetTailscaleInterfaceName yet, so this is a
no-op. I checked oss, android, and the macOS/iOS client. Nobody calls
this, or ever did.
But I want to in the future.
Updates #15408
Updates #9040
=> net/netmon: use Monitor's tsIfName if set by SetTailscaleInterfaceName

ipn/ipnlocal/local.go
On Windows and Android, peerAPIListeners may be initialized after a link change. This commit adds log statements to make it easier to trace this flow.
Updates #14393
=> ipn/ipnlocal: add more logging for initializing peerAPIListeners

prober/derp.go, prober/prober.go
Add a label which differentiates the address family for STUN checks.
Also initialize the derpprobe_attempts_total and
derpprobe_seconds_total metrics by adding 0 for
the alternate fail/ok case.
Updates tailscale/corp#27249
=> prober: add address family label for udp metrics

ipn/ipnlocal/local.go
fixes tailscale/tailscale#15394
In the current iteration, usage of the memstore for the audit logger is expected on some platforms.
=> ipn/ipnlocal: remove misleading [unexpected] log for auditlog

control/controlhttp/client.go, control/controlhttp/constants.go
Minimal mitigation that doesn't do the full refactor that's probably
warranted.
Updates #15402
=> control/controlhttp: quiet "forcing port 443" log spam

tsnet/tsnet.go
When compiled into TailscaleKit.framework (via the libtailscale repository), os.Executable() returns an error instead of the name of the executable.  which manifests in the following error from Swift when starting a `TailscaleNode`:
```
TailscaleNode Error: internalError(Optional("tenet: cannot find executable path"))
```
This commit adds another branch to the switch statement that enumerates platforms which behave in this manner, and defaults to "tsnet" in the same manner as those other platforms.
=> tsnet: Default executable name on iOS

ipn/store/kubestore/store_kube.go, ipn/store/kubestore/store_kube_test.go
This is to avoid issues where stale cache after Ingress recreation causes the certs not to be re-issued.
With this PR:
- the kube nodes that don't run in cert-share mode (which is all nodes, except for the currently experimental HA Ingress backends) read from cache, write to the state Secret through cache (behaviour unchanged)
- read replicas in cert-share mode attempt to read from cache, else look certs up in a Secret and refresh cache if found (unchanged)
- write replicas in cert-share mode write to Secret only (changed behaviour).
I have tested that with this change, the following workflow:
1. An HA Ingress is created
2. The Ingress gets deleted
3. The Ingress is recreated again
Results in TLS cert being issued at step 3 and stored in a Secret, so that when the replicas are next …
=> ipn/store/kubestore: skip cache for the write replica in cert share mode

cmd/containerboot/certs.go, cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/ingress-for-pg_test.go, cmd/k8s-operator/operator.go
This PR attempts to solve two issues:
- in a multi-cluster setup where in some clusters the Ingress resources are availble, but some are unable to provision certs (rate limits), we want to ensure that a client does not get routed to a cluster where cert issuance failed
- users should be able to tell when Ingress is ready, including when a cert is ready
The change:
- For HA Ingresses that expose port 443 only, the VIPService is only advertised when TLS cert has been provisioned
- Port 443 on Ingress status is only set once cert has been provisoned
- Fixes a small timeout issue
This allows to wait for an Ingress' HTTPS endpoint to be ready with:
```
$ kubectl wait --timeout=70s  ingress tails --for=jsonpath='{.status.loadBalancer.ingress[0].ports[0].port}'=443 
```
Note that the behaviour …
=> cmd/{k8s-operator,containerboot}: check TLS cert before advertising VIPService

build_docker.sh
We now have a tailscale/alpine-base:3.19- use that as the default base image.
Note that this change only applies to local dev builds.
Our image build infra uses ALPINE.txt file and I already build images using the 3.19 base (`unstable-v1.81.209` tag)
Updates tailscale/tailscale#15328
=> build_docker.sh: bump default base image

cmd/k8s-operator/deploy/crds/tailscale.com_proxygroups.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/operator.go, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_proxygroup.go
Temporarily make sure that the HA Ingress reconciler does not run, as we do not want to release this to stable just yet.
=> cmd/k8s-operator,k8s-operator: disable HA Ingress before stable release

net/dns/config.go, net/dns/manager.go
=> net/dns: add debug envknob to enable dual stack MagicDNS

scripts/installer.sh
When the install script is run on a system with DNF as package manager, first it detects if is using version 3 or 5.
The form of detecting version 5 only works if command `dnf --version` returns exactly `dnf5  version`. This can change with locales that are not C or english based.
For example, on my Nobara install, I'm running with locale `LANG=es_ES.utf8`, and `dnf --version` returns this:
```bash
$ dnf --version
dnf5 versión 5.2.10.0
dnf5 versión de API de plugin 2.0
libdnf5 versión 5.2.10.0
versión de API de plugin de libdnf5 2.1
```
With that in mind, `$DNF_VERSION` is incorrectly set at 3:
```bash
$ DNF_VERSION="3"
$ if dnf --version | grep -q '^dnf5 version'; then
DNF_VERSION="5"
fi
$ echo $DNF_VERSION
3
```
In order to fix it, we can run `dnf --version` with `LANG=C-UTF.8` to …
=> scripts/installer.sh: fix DNF 5 detection on all locales

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/state_test.go
`LocalBackend` transitions to `ipn.NoState` when switching to a different (or new) profile. When this happens, we should unconfigure `wgengine` to clear routes, DNS configuration, firewall rules that block all traffic except to the exit node, etc.
In this PR, we update `(*LocalBackend).enterStateLockedOnEntry` to do just that.
Fixes #15316
Updates tailscale/corp#23967
=> ipn/ipnlocal: unconfigure wgengine when switching profiles

ipn/ipnlocal/local.go
initPeerAPIListener may be returning early unexpectedly. Add debug logging to see what causes it to return early when it does.
Updates #14393
=> ipn/ipnlocal: add debug logging to initPeerAPIListener

net/netcheck/netcheck.go
It only affected js/wasm and tamago.
Updates tailscale/corp#24697
=> net/netcheck: use NoMeasureNoHome in another spot

net/netmon/netmon.go
Otherwise you can get stuck finding minor ones nonstop.
Fixes #15484
=> net/netmon: always remember ifState as old state, even on minor changes

disco/disco.go, disco/disco_test.go, net/udprelay/server.go, net/udprelay/server_test.go
This commit implements an experimental UDP relay server. The UDP relay server leverages the Disco protocol for a 3-way handshake between client and server, along with 3 new Disco message types for said handshake. These new Disco message types are also considered experimental, and are not yet tied to a capver.
The server expects, and imposes, a Geneve (Generic Network Virtualization Encapsulation) header immediately following the underlay UDP header. Geneve protocol field values have been defined for Disco and WireGuard. The Geneve control bit must be set for the handshake between client and server, and unset for messages relayed between clients through the server.
Updates tailscale/corp#27101
=> net/udprelay: start of UDP relay server implementation

wgengine/userspace.go
fixes tailscale/corp#27506
The source address link selection for forwarded DNS queries on sandboxed macOS doesn't deal with loopback addresses correctly resulting in "network unreachable" errors.   This adds an explicit check to ensure we return the loopback interface for loopback addresses instead of the default empty interface when the runtime.GOOS is darwin. 
Tested on both macos, macsys and tailscaled with a simple DNS proxy.  Forwarded requests to 127/8 are now all routed correctly.
=> wgengine: return explicit lo0 for loopback addrs on sandboxed macOS

cmd/natc/ipx.go, cmd/natc/ipx_test.go, cmd/natc/natc.go, cmd/natc/natc_test.go
Avoid the unbounded runtime during random allocation, if random allocation fails after a first pass at random through the provided ranges, pick the next free address by walking through the allocated set.
The new ipx utilities provide a bitset based allocation pool, good for small to moderate ranges of IPv4 addresses as used in natc.
=> cmd/natc: fix ip allocation runtime

cmd/tsidp/Dockerfile, cmd/tsidp/README.md, cmd/tsidp/tsidp.go
Fixes #14491
TS_HOSTNAME and TS_STATE_DIR are now actually used as advertised in the README.
(Since tsnet doesn't parse TS_HOSTNAME or TS_STATE_DIR by itself tmk).
Also changed Dockerfile to use `idp` to preserve the existing behavior.
=> cmd/tsidp: use advertised env vars for config

net/routetable/routetable_linux.go, net/routetable/routetable_other.go, net/tstun/linkattrs_linux.go, net/tstun/linkattrs_notlinux.go, wgengine/router/router_android.go, wgengine/router/router_linux.go
Android >=14 forbids the use of netlink sockets by apps, which results in either initialization failures or getting killed by the sandbox.
This should not affect the Tailscale android app in https://github.com/tailscale/tailscale-android, since it uses its own libtailscale shim to construct a data plane with a router that plugs into Android's native networking APIs. This only affects builds of tsnet programs targeting android, since without the additional logic from tailscale-android, Go considers `android` to be a subset of the `linux` GOOS, and thus selects implementations that try to use netlink.
Fixes #9836
---
I don't love sprinkling more build tags to deal with this, better HAL APIs would be preferable... But tactically, this unblocks other work until we get to refactors.
=> Stop trying to use netlink on android

client/systray/systray.go
This shouldn't be necessary, but while we're continuing to figure out the root cause, this is better than having to restart the app or switch profiles on the command line.
Updates #15528
=> client/systray: add menu item to rebuild the menu

cmd/natc/natc.go, cmd/natc/natc_test.go
Make the perPeerState objects able to function independently without a shared reference to the connector.
We don't currently change the values from connector that perPeerState uses at runtime. Explicitly copying them at perPeerState creation allows us to, for example, put the perPeerState into a consensus algorithm in the future.
Updates #14667
=> cmd/natc: separate perPeerState from connector

cmd/natc/ippool/ippool.go, cmd/natc/ippool/ippool_test.go, cmd/natc/ippool/ipx.go, cmd/natc/ippool/ipx_test.go, cmd/natc/natc.go, cmd/natc/natc_test.go
Adds IPPool and moves all IP address management concerns behind that.
Updates #14667
=> cmd/natc: move address storage behind an interface

util/testenv/testenv.go, util/testenv/testenv_test.go
For future in-memory network changes (#15558) to be able to be
stricter and do automatic leak detection when it's safe to do so, in
non-parallel tests.
Updates tailscale/corp#27636
=> util/testenv: add func to report whether a testing.TB is in parallel mode

client/local/local_test.go, client/web/web_test.go, control/controlclient/noise_test.go, net/tsdial/tsdial.go, tstest/nettest/nettest.go, util/testenv/testenv.go
To avoid ephemeral port / TIME_WAIT exhaustion with high --count
values, and to eventually detect leaked connections in tests. (Later
the memory network will register a Cleanup on the TB to verify that
everything's been shut down)
Updates tailscale/corp#27636
=> nettest, *: add option to run HTTP tests with in-memory network

client/local/local.go
Helps to fix: https://github.com/tailscale/tailscale/issues/12255 and needed for https://github.com/tailscale/tailscale/pull/15150
This fixes a bug in the local client where the DELETE request was not being sent correctly. The route was missing a slash before the url and this now matches the switch profile function.
This was included in https://github.com/tailscale/tailscale/pull/15150 but moved to its own PR by request of @bradfitz.
=> client/local: fix path with delete profile request

cmd/nardump/nardump.go, cmd/nardump/nardump_test.go
This adds the missing symlink support to the nardump tool.
I tested it locally with a few folders, and can confirm the produced nar output is identical to nix's.
If tests are required, I would like some guidance on how to create proper tests (fuzz tests?) along with a few basic golden tests.
cc @bradfitz
Edit: added a basic test which tests the main() directly for the two main use cases `--sri` and outputting nar. Rather than testing writeNar, etc. i.e. unit tests.
Edit2: simplified the test, directly testing writeNAR
=> cmd/nardump: support symlinks

flake.lock, flake.nix, go.mod.sri, shell.nix
Updates #15015
This fixes building with `nix build` on latest code.
=> nix: update nix and use go 1.24

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/set.go, cmd/tailscale/cli/set_test.go, cmd/tailscale/cli/up.go
Some CLI flags support multiple values separated by commas. These flags are intended to be declared only once and will silently ignore subsequent instances. This will now throw an error if multiple instances of advertise-tags and advertise-routes are detected.
Fixes #6813
=> cmd/tailscale/cli: return error on duplicate multi-value flags

README.md, docs/commit-messages.md
So we can link open source contributors to it.
=> commit-messages.md: make our git commit message style guide public

cmd/tailscale/cli/cli.go, cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/set.go, cmd/tailscale/cli/set_test.go, cmd/tailscale/cli/up.go
The earlier #15534 prevent some dup string flags. This does it for all flag types.
Updates #6813
=> cmd/tailscale/cli: prevent all dup flags, not just strings

cmd/containerboot/healthz.go, cmd/containerboot/main.go, cmd/containerboot/metrics.go, cmd/containerboot/serve.go, cmd/k8s-operator/proxygroup_specs.go
Ensure no services are advertised as part of shutting down tailscaled. Prefs are only edited if services are currently advertised, and if they're edited we wait for control's ~15s (+ buffer) delay to failover.
Note that editing prefs will trigger a synchronous write to the state Secret, so it may fail to persist state if the ProxyGroup is getting scaled down and therefore has its RBAC deleted at the same time, but that failure doesn't stop prefs being updated within the local backend, doesn't  affect connectivity to control, and the state Secret is about to get deleted anyway, so the only negative side effect is a harmless error log during shutdown. Control still learns that the node is no longer advertising the service and triggers the failover.
Note that the first version of this used a …
=> cmd/{containerboot,k8s-operator},kube/kubetypes: unadvertise ingress services on shutdown

cmd/tailscale/cli/up_test.go
`tailscale set` was created to set preferences, which used to be overloaded into `tailscale up`. To move people over to the new command, `tailscale up` was supposed to be frozen, so no new preference flags would be added. But people forgot it was frozen, there was no test, and so new flags were added anyway.
TestUpFlagSetIsFrozen complains when new flags are added to `tailscale up`. This doesn’t try all combinations of GOOS, but the CI builds run in every OS, so this should be caught in the PR.
This problem is described, in detail, in #15460.
=> cmd/tailscale: tailscale up is frozen

.github/workflows/installer.yml
Installer tests only run when changes are made to pkgserve. This PR schedules the tests to be run daily (10 AM EST) and report any failures to Slack.
Fixes [tailscale/corp#19103](https://github.com/tailscale/corp/issues/19103)
=> .github: add cron schedule to installer tests

ipn/ipnlocal/peerapi.go
The http.StatusMethodNotAllowed status code was being erroneously set instead of http.StatusBadRequest in multiple places.
=> ipn/ipnlocal: fix peerapi ingress endpoint

logpolicy/logpolicy.go, logpolicy/logpolicy_test.go
This makes sure that the log target override is respected even if a custom HTTP client is passed to logpolicy.
Updates tailscale/maple#29
=> logpolicy: fix log target override with a custom HTTP client

drive/driveimpl/drive_test.go, drive/driveimpl/fileserver.go, drive/driveimpl/shared/pathutil.go, drive/driveimpl/shared/pathutil_test.go
Fix the index out of bound panic when a request is made to the local fileserver mux with a valid secret-token, but missing share name.
Example error:
http: panic serving 127.0.0.1:40974: runtime error: slice bounds out of range [2:1]
Additionally, we documentation the edge case behavior of utilities that this fileserver mux depends on.
=> drive: fix index out of bounds when parsing request local paths

build_dist.sh
Default tags to `$TAGS` if set, so that people can choose arbitrary subsets of features.
Updates #12614
=> build_dist.sh: allow settings custom build tags

tstest/resource.go, tstest/resource_test.go
ResourceCheck was previously using cmp.Diff on multiline goroutine stacks The produced output was difficult to read for a number of reasons:
- the goroutines were sorted by count, and a changing count caused them to jump around
- diff is performed per-line, rather than per-stack
Instead, we now parse the pprof/goroutines?debug=1 format goroutines and only diff whole stacks.
Here's an example of the old cmp.Diff output. Any relevant details about why ResourceCheck is erroring are hidden in the `... // 102 identical, 2 removed, and 2 inserted lines` at the bottom, despite the massive diff that it produces:
```
resource.go:58: goroutine diff:
bytes.Join({
- 	"goroutine profile: total 34",
+ 	"goroutine profile: total 36",
"2 @ 0x104d23558 0x104ce6e38 0x104d22710 0x104d6b708 0x104d6ffdc …
```
=> tstest: parse goroutines for diff in ResourceCheck

ipn/ipnlocal/desktop_sessions.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_test.go, ipn/prefs.go
Ultimately, we'd like to get rid of the concept of the "current user". It is only used on Windows, but even then it doesn't work well in multi-user and enterprise/managed Windows environments.
In this PR, we update `LocalBackend` and `profileManager` to decouple them a bit more from this obsolete concept. This is done in a preparation for extracting `ipnlocal.Extension`-related interfaces and types, and using them to implement optional features like tailscale/corp#27645, instead of continuing growing the core `ipnlocal` logic.
Notably, we rename `(*profileManager).SetCurrentUserAndProfile()` to `SwitchToProfile()` and change its signature to accept an `ipn.LoginProfileView` instead of an `ipn.ProfileID` and `ipn.WindowsUserID`. Since we're not removing the "current user" completely just …
=> ipn, ipn/ipnlocal: reduce coupling between LocalBackend/profileManager and the Windows-specific "current user" model

docs/k8s/operator-architecture.md
Adds a new diagram for ProxyGroups running in Ingress mode. Documentation is currently not publicly available, but a link needs adding once it is.
Change-Id: I0d5dd6bf6f0e1b8b0becae848dc97d8b4bfb9ccb
=> docs/k8s: add architecture diagram for ProxyGroup Ingress

ipn/ipnstate/ipnstate.go, wgengine/magicsock/magicsock.go
This reverts commit 476a4c6ff174d46ce3b125c018c07c43713e1c10.
Reason: redundant with `tailscale status --json | jq '.Self.Relay'`
which we all forgot about. Whoops.
Updates #15625
=> Revert "ipn/ipnstate: add home DERP to tailscale status JSON"

tsconsensus/tsconsensus_test.go
If this stops the flakes, we can follow up and try to diagnose why.
Updates #15627
=> tsconsensus: skip 2 tests that were flaky in CI

ipn/ipnext/ipnext.go, ipn/ipnlocal/extension_host.go, ipn/ipnlocal/extension_host_test.go, ipn/ipnlocal/local.go
In this PR, we add two methods to facilitate extension lookup by both extensions, and non-extensions (e.g., PeerAPI or LocalAPI handlers):
- `FindExtensionByName` returns an extension with the specified name. It can then be type asserted to a given type.
- `FindMatchingExtension` is like `errors.As`, but for extensions. It returns the first extension that matches the target type (either a specific extension or an interface).
Updates tailscale/corp#27645
=> ipn/ipn{ext,local}: allow extension lookup by name or type

ipn/ipnlocal/local_test.go
=> ipn/ipnlocal: skip broken TestOnTailnetDefaultAutoUpdate on macOS

ipn/desktop/mksyscall.go, ipn/desktop/sessions_windows.go, ipn/desktop/zsyscall_windows.go
`[G,S]etWindowLongPtrW` are not available on 32-bit Windows, where `[G,S]etWindowLongW` should be used instead. The initial revision of #14945 imported the `win` package for calling and other Win32 API functions, which exported the correct API depending on the platform. However, the same logic wasn't implemented when we removed the win package dependency in a later revision, resulting in panics on Windows 10 x86 (there's no 32-bit Windows 11).
In this PR, we update the `ipn/desktop` package to use either `[G,S]etWindowLongPtrW` or `[G,S]etWindowLongW` depending on the platform.
Fixes #15684
Signed-off-by: Nick Khyl <nickk@tailscale.com>
(cherry picked from commit 60614fa)
=> ipn/desktop: fix panics on Windows 10, x86

cmd/k8s-operator/deploy/crds/tailscale.com_connectors.yaml, cmd/k8s-operator/deploy/crds/tailscale.com_dnsconfigs.yaml, cmd/k8s-operator/deploy/crds/tailscale.com_proxyclasses.yaml, cmd/k8s-operator/deploy/crds/tailscale.com_proxygroups.yaml, cmd/k8s-operator/deploy/crds/tailscale.com_recorders.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, k8s-operator/apis/v1alpha1/types_connector.go, k8s-operator/apis/v1alpha1/types_proxyclass.go, k8s-operator/apis/v1alpha1/types_proxygroup.go, k8s-operator/apis/v1alpha1/types_recorder.go, k8s-operator/apis/v1alpha1/types_tsdnsconfig.go
This PR adds an 'Age' column to the ProxyGroup resource display in kubectl output.
The age is calculated from the resource's creation timestamp and will be displayed
in a human-readable format (e.g. "3h", "2d", etc.).
Changes:
- Added kubebuilder marker for the Age column in types_proxygroup.go
- The Age column uses the metadata.creationTimestamp field to calculate the resource's age
Fixes: #15499
=> k8s-operator: add Age column to all custom resources

ipn/auditlog/extension.go, ipn/ipnext/ipnext.go, ipn/ipnlocal/extension_host.go, ipn/ipnlocal/extension_host_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/profiles.go
In this PR, we enable extensions to track changes in the current `ipn.Prefs`. These changes can result from a profile switch or from the user or system modifying the current profile’s prefs. Since some extensions may want to distinguish between the two events, while others may treat them similarly, we rename the existing profile-change callback to become a profile-state-change callback and invoke it whenever the current profile or its preferences change. Extensions can still use the `sameNode` parameter to distinguish between situations where the profile information, including its preferences, has been updated but still represents the same tailnet node, and situations where a switch to a different profile has been made.
Having dedicated prefs-change callbacks is being considered, but …
=> ipn/{auditlog,ipnext,ipnlocal}: convert the profile-change callback to a profile-state-change callback

ipn/ipnlocal/local_test.go
https://github.com/tailscale/tailscale/pull/15395 changed the logic to skip `EditPrefs` when the platform doesn't support auto-updates. But the old logic would only fail `EditPrefs` if the auto-update value was `true`. If it was `false`, `EditPrefs` would succeed and store `false` in prefs. The new logic will keep the value `unset` even if the tailnet default is `false`.
Fixes #15691
=> ipn/ipnlocal: fix TestOnTailnetDefaultAutoUpdate on macOS

wgengine/netstack/netstack.go
Cherry-picked from 62182fc37d44c0a8185b7d96f30465710dd68b66.
Updates google/gvisor#11632
Updates tailscale/corp#27717
=> wgengine/netstack: revert cubic cc to reno cc (#15677)

cmd/dist/dist.go, release/dist/qnap/files/scripts/Dockerfile.qpkg, release/dist/qnap/files/scripts/sign-qpkg.sh, release/dist/qnap/pkgs.go, release/dist/qnap/targets.go
QNAP now requires builds to be signed with an HSM.
This removes support for signing with a local keypair.
This adds support for signing with a Google Cloud hosted key.
The key should be an RSA key with protection level `HSM` and that uses PSS padding and a SHA256 digest.
The GCloud project, keyring and key name are passed in as command-line arguments.
The GCloud credentials and the PEM signing certificate are passed in as Base64-encoded command-line arguments.
Updates tailscale/corp#23528
=> cmd/dist,release/dist: sign QNAP builds with a Google Cloud hosted key

cmd/k8s-operator/ingress.go, cmd/k8s-operator/ingress_test.go
as discovered by https://github.com/tailscale/tailscale/issues/14891, specifying an ingress resource containing a an empty path (a.k.a., `path: ""`) results in an unclear error message and an non-functional ingress.
Other ingress controllers (e.g., [Nginx Ingress Controller](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/#restrictions)) handle this behaviour by setting the path to `path: "/"` if found to be empty. This PR solves the problem by doing just that whilst also creating an event on the ingress resource to highlight this:
```
configured backend is missing a path, defaulting to '/'
```
Fixes: https://github.com/tailscale/tailscale/issues/14908
=> cmd/k8s-operator: default ingress paths to '/' if not specified by user

feature/relayserver/relayserver.go, feature/relayserver/relayserver_test.go
The relay server is still permanently disabled until node attribute changes are wired up in a future commit.
=> feature/relayserver: wire up profile/prefs changes

tstime/tstime.go, tstime/tstime_test.go
The encoding/json/v2 effort may end up changing
the default represention of time.Duration in JSON. See https://go.dev/issue/71631
The GoDuration type allows us to explicitly use
the time.Duration.String representation regardless of whether we serialize with v1 or v2 of encoding/json.
=> tstime: add GoDuration which JSON serializes with time.Duration.String

net/udprelay/server.go, net/udprelay/server_test.go
ServerEndpoint contains fields that naturally encode as JSON numbers, e.g. uint64 and time.Duration types. These should never be expressed as floats, and in some cases (VNI) they have specific bits limits.
ServerEndpoint is currently experimental, therefore breaking changes are tolerable.
=> net/udprelay: change ServerEndpoint time.Duration fields to tstime.GoDuration

cmd/tsidp/tsidp.go, cmd/tsidp/tsidp_test.go, tailcfg/tailcfg.go
This feature adds support for a `groups` claim in tsidp using the grants syntax:
```json
{
"grants": [
{
"src": ["group:admins"],
"dst": ["*"],
"ip":  ["*"],
"app": {
"tailscale.com/cap/tsidp": [
{
"includeInUserInfo": true,
"extraClaims": {
"groups": ["admin"],
"entitlements": ["admin-stuff"]
},
}
]
}
},
{
"src": ["group:reader"],
"dst": ["*"],
"ip":  ["*"],
"app": {
"tailscale.com/cap/tsidp": [
{
"includeInUserInfo": false,
"extraClaims": {
"groups": ["reader"],
"entitlements": ["read-stuff"]
},
}
]
}
}
]
}
```
For: #10263
Fixes: #15128
=> cmd/tsidp: add groups claim to tsidp

ipn/ipnlocal/serve.go
Both are populated from the current netmap's `MagicDNSSuffix`. But building a full `ipnstate.Status` (with peers!) is expensive and unnecessary.
=> ipn/ipnlocal: use MagicDNSName of the current profile instead of generating a full ipnstate.Status

client/tailscale/localclient_aliases.go, client/tailscale/tailscale.go
Add [godoc links](https://go.dev/doc/comment#doclinks) in `Deprecated` comments of package `tailscale.com/client/tailscale`.
=> client/tailscale: add godoc links in Deprecated comments

feature/relayserver/relayserver.go
This was recently added, use it to be consistent.
=> feature/relayserver: use PeerAPIHandler.Logf()

net/portmapper/portmapper.go
The `EventBus` in `net/portmapper.Config` is still optional and `Client.updates` can be `nil`.
Updates #15772
=> net/portmapper: fix nil pointer dereference in Client.createMapping

ipn/ipnlocal/extension_host_test.go, ipn/ipnlocal/state_test.go
These were likely added after everything else was updated to use `tsd.NewSystem`, in a feature branch, and before it was merged back into main.
Updates #15160
=> ipn/ipnlocal: use tsd.NewSystem instead of &tsd.System in a few more tests

types/jsonx/json.go, types/jsonx/json_test.go
The typical way to implement union types in Go
is to use an interface where the set of types is limited. However, there historically has been poor support
in v1 "encoding/json" with interface types where
you can marshal such values, but fail to unmarshal them since type information about the concrete type is lost.
The MakeInterfaceCoders function constructs custom marshal/unmarshal functions such that the type name is encoded in the JSON representation.
The set of valid concrete types for an interface
must be specified apriori for this to function.
Updates tailscale/corp#22024
=> types/jsonx: add package for json/v2 helpers

go.mod, go.sum
This is the same version as before, but the old one confuses govulncheck.
=> go.mod: bump gorilla/csrf@v1.7.3

feature/feature.go, feature/relayserver/relayserver.go, ipn/auditlog/extension.go, ipn/desktop/extension.go, ipn/ipnext/ipnext.go, ipn/ipnlocal/extension_host.go, ipn/ipnlocal/extension_host_test.go
Now that 25c4dc5fd70 removed unregistering hooks and made them into
slices, just expose the slices and remove the setter funcs.
This removes boilerplate ceremony around adding new hooks.
This does export the hooks and make them mutable at runtime in theory,
but that'd be a data race. If we really wanted to lock it down in the
future we could make the feature.Hooks slice type be an opaque struct
with an All() iterator and a "frozen" bool and we could freeze all the
hooks after init. But that doesn't seem worth it.
This means that hook registration is also now all in one place, rather
than being mixed into ProfilesService vs ipnext.Host vs FooService vs
BarService. I view that as a feature. When we have a ton of hooks and
the list is long, then we can rearrange the fields in the Hooks …
=> ipn/ipnext: remove some interface indirection to add hooks

net/udprelay/server.go, net/udprelay/server_test.go
The previous strategy assumed clients maintained adequate state to understand the relationship between endpoint allocation and the server it was allocated on.
magicsock will not have awareness of the server's disco key pre-allocation, it only understands peerAPI address at this point. The second client to allocate on the same server could trigger re-allocation, breaking a functional relay server endpoint.
If magicsock needs to force reallocation we can add opt-in behaviors for this later.
=> net/udprelay: change Server.AllocateEndpoint existing alloc strategy

feature/feature.go, ipn/ipnlocal/local.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_test.go
We update `profileManager` to allow registering a single state (profile+prefs) change hook. This is to invert the dependency between the `profileManager` and the `LocalBackend`, so that instead of `LocalBackend` asking `profileManager` for the state, we can have `profileManager` call `LocalBackend` when the state changes.
We also update `feature.Hook` with a new `(*feature.Hook).GetOk` method to avoid calling both `IsSet` and `Get`.
Updates tailscale/corp#28014
Updates #12614
Signed-off-by: Nick Khyl <nickk@tailscale.com>
=> feature,ipn/ipnlocal: add profileManager.StateChangeHook

net/portmapper/igd_test.go, net/portmapper/portmapper_test.go, net/portmapper/select_test.go, net/portmapper/upnp_test.go, tstest/log.go
=> net/portmapper: fix test flakes from logging after test done

tstest/integration/integration.go
TS_CONTROL_IS_PLAINTEXT_HTTP no longer does anything as of
8fd471ce5748d2129dba584b4fa14b0d29229299
Updates #13597
=> tstest/integration: remove vestigial env var set in tests

tool/gocross/gocross.go, tool/gocross/gocross_test.go
Instead of using the version package (which depends on tailcfg.CurrentCapabilityVersion) to get the git commit hash, do it directly using debug.BuildInfo. This way, when changing struct fields in tailcfg, we can successfully `go generate` it without compiler errors.
Updates #9634
Updates https://github.com/tailscale/corp/issues/26717
=> tool/gocross: break circular dependency on tailcfg

ipn/ipnlocal/taildrop.go
This fixes a refactoring bug introduced in 8b72dd7873201
Tests (that failed on this) are coming in a separate change.
Updates #15812
=> ipn/ipnlocal: fix Taildrop regression from refactoring

cmd/tailscaled/tailscaled.go, feature/taildrop/integration_test.go, feature/taildrop/localapi.go, tstest/integration/integration.go, tstest/integration/integration_test.go, tstest/integration/testcontrol/testcontrol.go
Taildrop has never had an end-to-end test since it was introduced.
This adds a basic one.
It caught two recent refactoring bugs & one from 2022 (0f7da5c7dc0).
This is prep for moving the rest of Taildrop out of LocalBackend, so
we can do more refactorings with some confidence.
Updates #15812
=> feature/taildrop: add integration test

cmd/tsidp/README.md
=> cmd/tsidp: remove backticks in README in shell example

ipn/ipnlocal/local.go, tailcfg/tailcfg.go
Until we turn on AAAA by default (which might make some people rely on
Happy Eyeballs for targets without IPv6), this lets people turn it on
explicitly if they want.
We still should add a peer cap as well in the future to let a peer
explicitly say that it's cool with IPv6.
Related: https://github.com/tailscale/tailscale/pull/9574
Updates #1813
Updaets #1152
=> ipn/ipnlocal, tailcfg: add MagicDNS opt-in attr for IPv6 AAAA records

cmd/tailscale/cli/cli.go, cmd/tailscale/cli/file.go
=> cmd/tailscale/cli: omit "file" subcommand if taildrop is omitted from build

control/controlclient/direct.go, tailcfg/tailcfg.go
This handle can be used in tests and debugging to identify the specific
client connection.
Updates tailscale/corp#28368
Change-Id: I48cc573fc0bcf018c66a18e67ad6c4f248fb760c
Signed-off-by: Brian Palmer <brianp@tailscale.com>
=> control/controlclient: send optional ConnectionHandleForTest with map requests

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, tsnet/packet_filter_test.go
This is an integration test that covers all the code in Direct, Auto, and LocalBackend that processes NetMaps and creates a Filter. The test uses tsnet as a convenient proxy for setting up all the client pieces correctly, but is not actually a test specific to tsnet.
Updates tailscale/corp#20514
=> tsnet: add test for packet filter generation from netmap

util/deephash/deephash_test.go, util/deephash/tailscale_types_test.go
This is done to prevent import cycles in tests.
Fixes #15923
=> util/deephash: move tests that depend on other tailscale packages to deephash_test

health/health.go, ipn/ipnlocal/local.go, ipn/ipnlocal/node_backend.go, ipn/ipnlocal/prefs_metrics.go, ipn/ipnlocal/profiles.go, ipn/localapi/localapi.go
updates tailscale/corp#28092
Adds metrics for various client events:
* Enabling an exit node
* Enabling a mullvad exit node
* Requesting a bug report ID
* Profile counts
* Captive portal detection
=> ipn/ipnlocal: add metrics for various client events

safeweb/http.go
Set Cross-Origin-Opener-Policy: same-origin for all browser requests to
prevent window.location manipulation by malicious origins.
Updates tailscale/corp#28480
Thank you to Triet H.M. Pham for the report.
Signed-off-by: Patrick O'Doherty <patrick@tailscale.com>
=> safeweb: Set Cross-Origin-Opener-Policy for browser requests

ipn/ipnserver/actor.go, ipn/ipnserver/server_fortest.go, ipn/ipnserver/server_test.go, ipn/ipnserver/waiterset_test.go, ipn/lapitest/backend.go, ipn/lapitest/client.go, ipn/lapitest/example_test.go, ipn/lapitest/opts.go, ipn/lapitest/server.go
In this PR, we extract the in-process LocalAPI client/server implementation from `ipn/ipnserver/server_test.go` into a new `ipntest` package to be used in high‑level black‑box tests, such as those for the tailscale CLI.
Updates #15575
=> ipn/ipn{server,test}: extract the LocalAPI test client and server into ipntest

ipn/ipnlocal/local.go, ipn/ipnlocal/node_backend.go, ipn/ipnlocal/peerapi.go
We previously kept these methods in `local.go` when we started moving node-specific state from `LocalBackend` to `nodeBackend`, to make those changes easier to review. But it's time to move them to `node_backend.go`.
Updates #12614
=> ipn/ipnlocal: move nodeBackend methods from local.go to node_backend.go

util/linuxfw/fake_netfilter.go, util/linuxfw/iptables_for_svcs.go, util/linuxfw/iptables_for_svcs_test.go, util/linuxfw/nftables_for_svcs.go, util/linuxfw/nftables_for_svcs_test.go, util/linuxfw/nftables_runner.go, wgengine/router/router_linux_test.go
Add new rules to update DNAT rules for Kubernetes operator's HA ingress where it's expected that rules will be added/removed frequently (so we don't want to keep old rules around or rewrite existing rules unnecessarily):
- allow deleting DNAT rules using metadata lookup
- allow inserting DNAT rules if they don't already exist (using metadata lookup)
The full working L3 HA ingress is at https://github.com/tailscale/tailscale/tree/irbekrm/ingress_services
Updates tailscale/tailscale#15895
=> util/linuxfw: add new netfilter rules for HA ingresses

docs/windows/policy/en-US/tailscale.adml, docs/windows/policy/tailscale.admx, net/dns/manager_windows.go, util/syspolicy/policy_keys.go, util/syspolicy/syspolicy.go
In this PR, we make DNS registration behavior configurable via the `EnableDNSRegistration` policy setting. We keep the default behavior unchanged, but allow admins to either enforce DNS registration and dynamic DNS updates for the Tailscale interface, or prevent Tailscale from modifying the settings configured in the network adapter's properties or by other means.
Updates #14917
=> net/dns,docs/windows/policy,util/syspolicy: register Tailscale IP addresses in AD DNS if required by policy

cmd/derpprobe/derpprobe.go
`cmd/derpprobe --once` didn’t respect the convention of non-zero exit status for a failed run. It would always exit zero (i.e. success), even. This patch fixes that, but only for `--once` mode.
Fixes: #15925
=> cmd/derpprobe: exit with non-zero status if --once fails

ipn/ipnlocal/local.go, wgengine/userspace.go
This avoids reconfiguring the dialer unless the router config has changed.
Updates #12027
=> ipn/ipnlocal,wgengine: move (*tsdial.Dialer).SetRoutes() calls from LocalBackend to userspaceEngine

prober/tls_test.go
Catch failing tests that have no expected error string.
Updates #15912
=> prober: fix test logic

feature/taildrop/ext.go, feature/taildrop/integration_test.go, ipn/ipnext/ipnext.go, ipn/ipnlocal/local.go
Currently, `LocalBackend`/`ExtensionHost` doesn't invoke the profile change callback for the initial profile. Since the initial profile may vary depending on loaded extensions and applied policy settings, it can't be reliably determined until all extensions are initialized. Additionally, some extensions may asynchronously trigger a switch to the "best" profile (based on system state and policy settings) during initialization.
We intended to address these issues as part of the ongoing `profileManager`/`LocalBackend` refactoring, but the changes didn't land in time for the v1.84 release and the Taildrop refactoring.
In this PR, we update the Taildrop extension to retrieve the current profile at initialization time and handle it as a profile change.
We also defer extension initialization …
=> feature/taildrop,ipn/ipn{ext,local}: initialize taildrop for initial profile

cmd/proxy-to-grafana/proxy-to-grafana.go, cmd/proxy-to-grafana/proxy-to-grafana_test.go
Update proxy-to-grafana to strip X-Webauth prefixed headers passed by the client in *every* request, not just those to /login.
`/api/` routes will also accept these headers to authenticate users, necessitating their removal to prevent forgery.
Updates tailscale/corp#28687
=> cmd/proxy-to-grafana: strip X-Webauth* headers from all requests

prober/prober.go, prober/prober_test.go
Content-type was responding as test/plain for probes accepting application/json. Set content type header before setting the response code to correct this.
Updates tailscale/corp#27370
=> prober: correct content-type response

wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/relaymanager.go, wgengine/magicsock/relaymanager_test.go
CallMeMaybeVia reception and endpoint allocation have been collapsed to a single event channel. discoInfo caching for active relay handshakes is now implemented.
=> wgengine/magicsock: implement relayManager handshaking

cmd/tailscale/cli/cli.go
The same message was used for "up" and "down" permission failures, but
"set" works better for both. Suggesting "up --operator" for a "down"
permission failure was confusing.
It's not like the latter command works in one shot anyway.
Fixes #16008
=> cmd/tailscale/cli: suggest using "tailscale set", not "up", to set operator

ipn/ipnext/ipnext.go, ipn/ipnlocal/extension_host.go, ipn/ipnlocal/extension_host_test.go
Taildrop wasn't working on iOS since #15971 because GetExt didn't work
until after init, but that PR moved Init until after Start.
This makes GetExt work before LocalBackend.Start (ExtensionHost.Init).
Updates #15812
=> ipn/ipnlocal: make GetExt work earlier, before extension init

wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/magicsock/relaymanager.go
This type improves code clarity and reduces the chance of heap alloc as we pass it as a non-pointer. VNI being a 3-byte value enables us to track set vs unset via the reserved/unused byte.
=> wgengine/magicsock: introduce virtualNetworkID type

cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/svc-for-pg_test.go, cmd/k8s-operator/testutils_test.go
It seems like there is some sort of general issue with either the internal client in this repo that attempts to parse the error returned from the API or with the logic API side- the error that we get in kube client is a pointer to our type if it's a 'feature flag not enabled' error, but a concrete type if it's a 404. Right now, I can't debug this and we need to fix the code, so this does that.
Updates tailscale/tailscale#15895
=> cmd/k8s-operator: fix Tailscale Service API errors check

feature/taildrop/ext.go, feature/taildrop/paths.go, feature/taildrop/send.go, feature/taildrop/send_test.go, feature/taildrop/taildrop.go
Create FileOps for calling platform-specific file operations such as SAF APIs in Taildrop Update taildrop.PutFile to support both traditional and SAF modes
Updates tailscale/tailscale#15263
=> ipn,ipnlocal,taildrop: use SAF for Android files

ipn/store/store_aws.go, ipn/store/store_kube.go, ipn/store/stores.go, ipn/store/stores_test.go
Registering a new store is cheap, it just adds a map entry. No need to lazy-init it with sync.Once and an intermediate slice holding init functions.
=> ipn/store: remove a layer of indirection for registering stores

cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/ingress-for-pg_test.go, cmd/k8s-operator/operator_test.go, cmd/k8s-operator/svc-for-pg.go, cmd/k8s-operator/svc-for-pg_test.go, cmd/k8s-operator/svc.go
This PR adds two new validations:
- Validates that any tags set on Tailscale Kubernetes Services via `tailscale.com/tags` annotation are valid ACL tags (for both HA and non-HA Services)
If invalid tags are found, sets `Service` to invalid and logs an error:
```
status:
conditions:
- lastTransitionTime: "2025-05-22T14:27:31Z"
message: 'invalid Service: invalid tag "k8s": tags must start with ''tag:'''
reason: IngressSvcInvalid
status: "False"
type: TailscaleIngressSvcValid
loadBalancer: {}
```
- Validates that no more than one Tailscale Kubernetes Service in HA mode refers to the same Tailscale Services
If more than one found, sets `Service` to invalid and logs an error:
```
conditions:
- lastTransitionTime: "2025-05-22T15:13:48Z"
message: found duplicate Service "multi2" for hostname …
```
=> cmd/k8s-operator: validate Service tags, catch duplicate Tailscale Services in one cluster

cmd/tsidp/tsidp.go
In accordance with the OIDC/OAuth 2.0 protocol, do not send an empty refresh_token and instead omit the field when empty.
Fixes https://github.com/tailscale/tailscale/issues/16073
=> cmd/tsidp: Fix sending string for refresh_token

feature/capture/dissector/ts-dissector.lua
Fix the wireshark lua dissector to support 0 bit position and not throw modulo div by 0 errors.
Add new disco frame types to the decoder.
Updates tailscale/corp#29036
=> feature/capture: fix wireshark decoding and add new disco frame types

.github/workflows/test.yml
Bumps Ubuntu version for test container images 22.04 -> 24.04.
(Could also change to `ubuntu-latest`, but it seems not a bad thing to be aware when versions change)
=> .github/workflows: use Ubuntu 24.04 images

wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/relaymanager.go, wgengine/magicsock/relaymanager_test.go
relayManager is responsible for disco ping/pong probing of relay endpoints once a handshake is complete.
Future work will enable relayManager to set a relay endpoint as the best UDP path on an endpoint if appropriate.
=> wgengine/magicsock: implement relayManager endpoint probing

util/set/smallset.go, util/set/smallset_test.go
This adds SmallSet.SoleElement, which I need in another repo for
efficiency. I added tests, but those tests failed because Add(1) +
Add(1) was promoting the first Add's sole element to a map of one
item. So fix that, and add more tests.
Updates tailscale/corp#29093
=> util/set: add SmallSet.SoleElement, fix bug, add more tests

go.mod, go.sum, wgengine/magicsock/batching_conn.go, wgengine/magicsock/batching_conn_linux.go, wgengine/magicsock/batching_conn_linux_test.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/magicsock/rebinding_conn.go, wgengine/wgcfg/device_test.go
Our conn.Bind implementation is updated to make Send() offset-aware for future VXLAN/Geneve encapsulation support.
=> go.mod,wgengine/magicsock: update wireguard-go

ipn/backend.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
Currently, any client with the latest client library in it (capver >= 117) will be able to handle `DisplayMessages` without URLs as they are mapped to the pre-existing `UnhealthyState` type. However they may not necessarily read the `PrimaryAction` field, which is a new field we added. We can't tell based on capver whether a client supports `PrimaryAction` or not.
This PR adds a `NotifyHealthActions` watch option, so when an app subscribes to the IPN bus via localapi it can signal if it understands `PrimaryAction`. If it does, we send it, if not then we concatenate the URL details to the message for compatibility with clients that have not implemented reading `PrimaryAction` yet.
Updates tailscale/corp#27759
=> ipn: add watch opt to include actions in health messages

wgengine/magicsock/magicsock_linux.go, wgengine/magicsock/magicsock_linux_test.go
Fragmented datagrams would be processed instead of being dumped right
away. In reality, thse datagrams would be dropped anyway later so there
should functionally not be any change. Additionally, the feature is off
by default.
Closes #16203
=> wgengine/magicsock: fix bpf fragmentation jump offsets

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
This commit fixes the bug that c2n requests are skiped when updating vipServices in serveConfig. This then resulted netmap update being skipped which caused inaccuracy of Capmap info on client side. After this fix, client always inform control about it's vipServices config changes.
Fixes tailscale/corp#29219
=> ipn/ipnlocal: Update hostinfo to control on service config change

cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/ingress-for-pg_test.go
Updates https://github.com/tailscale/corp/issues/24795
=> cmd/k8s-operator: explicitly set tcp on VIPService port configuration for Ingress with ProxyGroup

types/netmap/nodemut.go, types/netmap/nodemut_test.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go
This enables us to mark nodes as relay capable or not. We don't actually do that yet, as we haven't established a relay CapVer.
=> types/netmap,wgengine/magicsock: propagate CapVer to magicsock.endpoint

feature/relayserver/relayserver.go, net/netcheck/netcheck.go, net/udprelay/server.go, net/udprelay/server_test.go
The relay server now fetches IPs from local interfaces and external perspective IP:port's via netcheck (STUN).
=> feature/relayserver,net/{netcheck,udprelay}: implement addr discovery

ipn/ipnlocal/local.go
We renamed the type in #15866 but didn't update the comments at the time.
=> ipn/ipnlocal: replace nodeContext with nodeBackend in comments

ipn/ipnlocal/local.go, ipn/ipnlocal/node_backend.go, ipn/ipnlocal/node_backend_test.go
We update `LocalBackend` to shut down the current `nodeBackend` when switching to a different node, and to mark the new node's `nodeBackend` as ready when the switch completes.
Updates tailscale/corp#28014
Updates tailscale/corp#29543
Updates #12614
=> ipn/ipnlocal: signal nodeBackend readiness and shutdown

.github/workflows/test.yml, go.mod
This does a `go mod download` and stores its results in GitHub Actions' cache and does that job before all other jobs which restore it, so jobs don't need to all download stuff at runtime.
Updates tailscale/corp#28679
=> .github/workflows: do a go mod download & cache it before all jobs

tsconsensus/authorization.go
lock for access to a.peers
Fixes #16284
=> tsconsensus: protect from data race

cmd/natc/natc.go, cmd/natc/natc_test.go
If natc is running on a host with tailscale using `--accept-dns=true` then a DNS loop can occur. Provide a flag for some specific DNS upstreams for natc to use instead, to overcome such situations.
Updates #14667
=> cmd/natc: add a flag to use specific DNS servers

.github/workflows/checklocks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml, .github/workflows/kubemanifests.yaml, .github/workflows/natlab-integrationtest.yml, .github/workflows/ssh-integrationtest.yml, .github/workflows/update-flake.yml, .github/workflows/update-webclient-prebuilt.yml, .github/workflows/webclient.yml, version_test.go
Tests that go mod version matches ./tool/go version.
Mismatched versions result in incosistent Go versions being used i.e. in CI jobs as the version in go.mod is used to determine what Go version Github actions pull in.
Also fixes a typo that had been copy-pasted into all workflows
Currently failing as expected https://github.com/tailscale/tailscale/actions/runs/15684481497/job/44184059067?pr=16285#step:8:11
Updates tailscale/tailscale#16283
=> .github/workflows: test that ./go/tool version matches go mod version

cmd/tailscale/cli/dns-query.go, cmd/tailscale/cli/dns-status.go, cmd/tailscale/cli/dns.go
This patch contains the following cleanups:
1. Simplify `ffcli.Command` definitions;
2. Word-wrap help text, consistent with other commands;
3. `tailscale dns --help` usage makes subcommand usage more obvious;
4. `tailscale dns query --help` describes DNS record types.
``` console
sfllaw@h2co3:~/src/tailscale$ go run ./cmd/tailscale dns --help
Diagnose the internal DNS forwarder
USAGE
tailscale dns status [--all]
tailscale dns query <name> [a|aaaa|cname|mx|ns|opt|ptr|srv|txt]
The 'tailscale dns' subcommand provides tools for diagnosing the internal DNS
forwarder (100.100.100.100).
For more information about the DNS functionality built into Tailscale, refer to
https://tailscale.com/kb/1054/dns.
SUBCOMMANDS
status  Print the current DNS status and configuration
query …
```
=> cmd/tailscale: clean up dns --help messages

.github/workflows/test.yml, tool/go.cmd, tool/go.ps1
go.cmd lets you run just "./tool/go" on Windows the same as Linux/Darwin.
The cmd script then just invokes PowerShell which is more powerful than batch.
I wanted this while debugging Windows CI performance by reproducing slow tests on my local Windows laptop.
Updates tailscale/corp#28679
=> tool: add go toolchain wrapper for Windows

wgengine/magicsock/relaymanager.go
=> wgengine/magicsock: fix relay endpoint allocation URL

wgengine/magicsock/batching_conn_linux.go, wgengine/magicsock/rebinding_conn.go
Otherwise receives interpret as naked WireGuard.
=> wgengine/magicsock: set Geneve header protocol for WireGuard

wgengine/magicsock/relaymanager.go
Any return underneath this select case must belong to a type switch case.
=> wgengine/magicsock: remove premature return in handshakeServerEndpoint

release/dist/qnap/files/scripts/Dockerfile.qpkg
20.04 is no longer supported.
This pulls in changes to the QDK package that were required to make build succeed on 24.04.
Updates https://github.com/tailscale/corp/issues/29849
=> release/dist/qnap: upgrade to Ubuntu 24.04 Docker image

wgengine/magicsock/relaymanager.go
Premature cancellation was preventing the work from ever being cleaned up in runLoop().
=> wgengine/magicsock: fix relayManager alloc work cleanup

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
This PR cherry-picks https://github.com/tailscale/tailscale/pull/16146 into 1.84 release branch, so that we can cut a patch release for Kubernetes Operator with this change.
Without this fix the Kubernetes Operator's HA Ingress fails during initial setup (fails to provision TLS certs for the proxies).
Fixes tailscale/corp#29219
cc @tomhjp @ChaosInTheCRD 
(cherry picked from commit 7b06532ea108bd7d12785125c2423a1a4e9987b3)
=> ipn/ipnlocal: Update hostinfo to control on service config change (#16146)

tool/gocross/gocross-wrapper.sh
go(1) repsects GOROOT if set, but tool/go / gocross-wrapper.sh are explicitly intending to use our toolchain. We don't need to set GOROOT, just unset it, and then go(1) handles the rest.
Updates tailscale/corp#26717
=> tool/gocross: remove GOROOT to ensure correct toolchain use

.github/workflows/update-flake.yml, .github/workflows/update-webclient-prebuilt.yml
GitHub used to recommend the [tibdex/github-app-token](https://github.com/tibdex/github-app-token) GitHub Action until they wrote their own [actions/create-github-app-token](https://github.com/actions/create-github-app-token).
This patch replaces the use of the third-party action with the official one.
See also: https://github.com/tibdex/github-app-token/issues/99
=> .github/workflows: replace tibdex with official GitHub Action

atomicfile/atomicfile.go, cmd/tailscaled/tailscaled.go, cmd/tsconnect/src/lib/js-state-store.ts, cmd/tsconnect/src/types/wasm_js.d.ts, cmd/tsconnect/wasm/wasm_js.go, docs/windows/policy/en-US/tailscale.adml, docs/windows/policy/tailscale.admx, feature/tpm/tpm.go, feature/tpm/tpm_test.go, ipn/ipnlocal/state_test.go, ipn/store.go, ipn/store/awsstore/store_aws.go, ipn/store/kubestore/store_kube.go, ipn/store/mem/store_mem.go, ipn/store/stores.go, ipn/store_test.go, tailcfg/tailcfg.go, tstest/integration/integration.go, tstest/integration/integration_test.go, tstest/integration/tailscaled_deps_test_darwin.go, tstest/integration/tailscaled_deps_test_freebsd.go, tstest/integration/tailscaled_deps_test_linux.go, tstest/integration/tailscaled_deps_test_openbsd.go, util/syspolicy/policy_keys.go
Add a new `--encrypt-state` flag to `cmd/tailscaled`. Based on that flag, migrate the existing state file to/from encrypted format if needed.
In a separate PR I will also plumb this flag's value from the device policy for Windows.
cc @nickkhyl 
Updates #15830
=> ipn/store: automatically migrate between plaintext and encrypted state

cmd/containerboot/kube.go, cmd/containerboot/kube_test.go, cmd/containerboot/main.go, cmd/containerboot/main_test.go, cmd/k8s-operator/egress-services-readiness.go, cmd/k8s-operator/egress-services-readiness_test.go, cmd/k8s-operator/egress-services.go, cmd/k8s-operator/ingress-for-pg.go, cmd/k8s-operator/ingress-for-pg_test.go, cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-operator/proxygroup_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/svc-for-pg.go, cmd/k8s-operator/svc-for-pg_test.go, cmd/k8s-operator/tsrecorder.go, k8s-operator/apis/v1alpha1/types_connector.go, k8s-operator/conditions.go, kube/kubeclient/fake_client.go
Previously, the operator checked the `ProxyGroup` status fields for information on how many of the proxies had successfully authed. Use their state `Secrets` instead as a more reliable source of truth.
Containerboot has written `device_fqdn` and `device_ips` keys to the state `Secret` since inception, and `pod_uid` since 1.78.0, so there's no need to use the API for that data. Read it from the state `Secret` for consistency. However, to ensure we don't read data from a previous run of containerboot, make sure we reset containerboot's state keys on startup.
One other knock-on effect of that is `ProxyGroups` can briefly be marked not Ready while a `Pod` is restarting. Introduce a new `ProxyGroupAvailable` condition to more accurately reflect when downstream controllers can implement flows …
=> cmd/k8s-operator: use state Secret for checking device auth

wgengine/magicsock/endpoint.go, wgengine/magicsock/endpoint_test.go, wgengine/magicsock/magicsock.go
This was previously hooked around direct UDP path discovery / CallMeMaybe transmission, and related conditions. Now it is subject to relay-specific considerations.
=> wgengine/magicsock: move UDP relay path discovery to heartbeat()

cmd/tsconnect/src/lib/js-state-store.ts, cmd/tsconnect/src/types/wasm_js.d.ts, cmd/tsconnect/wasm/wasm_js.go, feature/tpm/tpm.go, feature/tpm/tpm_test.go, ipn/store.go, ipn/store/awsstore/store_aws.go, ipn/store/kubestore/store_kube.go, ipn/store/mem/store_mem.go, ipn/store/stores.go
This method is only needed to migrate between store.FileStore and tpm.tpmStore. We can make a runtime type assertion instead of implementing an unused method for every platform.
FYI @willh-ts @kari-ts @nickoneill 
Updates #15830
=> ipn/store: make StateStore.All optional

cmd/tsidp/README.md
We dropped the idea of the Experimental release stage in tailscale/tailscale-www#7697, in favour of [Community Projects](https://tailscale.com/community/community-projects).
=> tsidp: update README to refer to community projects

wgengine/magicsock/endpoint.go
Otherwise we can end up mirroring packets to them forever. We may eventually want to relax this to direct paths as well, but start with UDP relay paths, which have a higher chance of becoming untrusted and never working again, to be conservative.
=> wgengine/magicsock: clear UDP relay bestAddr's on disco ping timeout

client/local/local.go, client/systray/systray.go
Replace the existing systray_start counter metrics with a systray_running gauge metrics.
This also adds an IncrementGauge method to local client to parallel IncrementCounter. The LocalAPI handler supports both, we've just never added a client method for gauges.
Updates #1708
=> client/systray: replace counter metric with gauge

drive/driveimpl/drive_test.go, drive/driveimpl/local_impl.go, drive/local.go, ipn/ipnlocal/drive.go
Instead of calculating the PeerAPI URL at the time that we add the peer, we now calculate it on every access to the peer. This way, if we initially did not have a shared address family with the peer, but later do, this allows us to access the peer at that point. This follows the pattern from other places where we access the peer API, which also calculate the URL on an as-needed basis.
Additionally, we now show peers as not Available when we can't get a peer API URL.
Lastly, this moves some of the more frequent verbose Taildrive logging from [v1] to [v2] level.
Updates #29702
=> drive,ipn/ipnlocal: calculate peer taildrive URLs on-demand

feature/tpm/tpm.go, ipn/ipnlocal/local.go, ipn/store.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go
Report whether the client is configured with state encryption (which varies by platform and can be optional on some). Wire it up to `--encrypt-state` in tailscaled, which is set for Linux/Windows, and set defaults for other platforms. Macsys will also report this if full Keychain migration is done.
Updates #15830
=> tailcfg: report StateEncrypted in Hostinfo

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
[4 commits]
- fix checking whether an exit node candidate is online in the full netmap. This is mostly a no-op, since offline nodes don't have the `NodeAttrSuggestExitNode` `NodeCapability`, but it allows us to fix the incorrect `TestSetControlClientStatusAutoExitNode` without having to skip it.
- fix (and skip) `TestUpdateNetmapDeltaAutoExitNode`, as `suggestExitNode` doesn't currently handle delta updates. We'll fix that in a later commit after plumbing `nodeBackend` into it.
- remove the locked-on-entry pattern from `setAutoExitNodeIDLockedOnEntry`, rename it to `pickNewAutoExitNode` and use it instead of the original `pickNewAutoExitNode` that we added in #14517.
- simplify `pickNewAutoExitNode` a little bit.
Updates #16455
=> ipn/ipnlocal: clean up suggested exit nodes and skip a failing (and incorrect) test

Dockerfile, build_docker.sh
This PR ads a note for how to build local images using make.
This is following an internal discussion- given that this repo contains a Dockerfile, a Makefile and a containers build script, it is not obvious what's the most straightforward way to build a local image.
=> Dockerfile,build_docker.sh: add a note on how to build local images

feature/relayserver/relayserver.go, tailcfg/tailcfg.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
Inverts the nodeAttrs related to relay client/server enablement to disablement, and fixes up the corresponding logic that uses them. Also updates the doc comments on both.
Fixes tailscale/corp#30024
Signed-off-by: Dylan Bargatze <dylan@tailscale.com>
=> tailcfg, magicsock, feature/relayserver: Flip UDP relay nodeAttrs from enablement to disablement

wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/relaymanager.go, wgengine/magicsock/relaymanager_test.go
Just make [relayManager] always handle it, there's no benefit to checking bestAddr's.
Also, remove passing of disco.Pong to [relayManager] in endpoint.handlePongConnLocked(), which is redundant with the callsite in Conn.handleDiscoMessage().
=> wgengine/magicsock: simplify Geneve-encapsulated disco.Ping handling

wgengine/magicsock/magicsock.go
These were flipped. DstIP() and DstIPBytes() are used internally by wireguard-go as part of a handshake DoS mitigation strategy.
Updates tailscale/corp#20732
Updates tailscale/corp#30042
=> wgengine/magicsock: fix lazyEndpoint DstIP() vs SrcIP()

wgengine/netstack/netstack.go
TCP connections are two unidirectional data streams, and if one of these streams closes, we should not assume the other half is closed as well. For example, if an HTTP client closes its write half of the connection early, it may still be expecting to receive data on its read half, so we should keep the server -> client half of the connection open, while terminating the client -> server half.
Fixes tailscale/corp#29837.
=> wgengine/netstack: correctly proxy half-closed TCP connections

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, util/syspolicy/source/test_store.go
In this PR, we update `setExitNodeID` to retain the existing exit node if auto exit node is enabled, the current exit node is allowed by policy, and no suggested exit node is available yet.
=> ipn/ipnlocal,util/syspolicy/source: retain existing exit node when using auto exit node, if it's allowed by policy

ipn/ipnauth/self.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/localapi/localapi.go, util/syspolicy/syspolicy.go
[2 commits]: the first adds `syspolicy.HasAnyOf`, used by the main commit
We extract `checkEditPrefsAccessLocked`, `adjustEditPrefsLocked`, and `onEditPrefsLocked` from the `EditPrefs` execution path, defining when each step is performed and what behavior is allowed at each stage.
Currently, this is primarily used to support Always On mode, to handle the Exit Node enablement toggle, and to report prefs edit metrics.
We then use it to enforce Exit Node policy settings by preventing users from setting an exit node and making `EditPrefs` return an error when an exit node is enforced by policy. This enforcement is also extended to the Exit Node toggle.
These changes prepare for supporting Exit Node overrides when permitted by policy and preventing logout while Always On mode is enabled.
In …
=> ipn/{ipnauth,ipnlocal,localapi}: make EditPrefs return an error if changing exit node is restricted by policy

cmd/tailscale/cli/logout.go, cmd/tsconnect/wasm/wasm_js.go, ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go, ipn/localapi/localapi.go
In this PR, we start passing a LocalAPI actor to `(*LocalBackend).Logout` to make it subject to the same access check as disconnects made via `tailscale down` or the GUI.
We then update the CLI to allow `tailscale logout` to accept a reason, similar to `tailscale down`.
Updates tailscale/corp#26249
=> cmd/tailscale/cli,ipn/ipnlocal: restrict logout when AlwaysOn mode is enabled

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
Now that `applySysPolicy` is only called by `(*LocalBackend).reconcilePrefsLocked`, we can make it a method to avoid passing state via parameters and to support future extensibility.
Also factor out exit node-specific logic into `applyExitNodeSysPolicyLocked`.
=> ipn/ipnlocal: make applySysPolicy a method on LocalBackend

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, util/syspolicy/policy_keys.go, util/syspolicy/rsop/change_callbacks.go
When the policy setting is enabled, it allows users to override the exit node enforced by the `ExitNodeID` or `ExitNodeIP` policy. It's primarily intended for use when `ExitNodeID` is set to `auto:any`, but it can also be used with specific exit nodes. It does not allow disabling exit node usage entirely.
Once the exit node policy is overridden, it will not be enforced again until the policy changes, the user connects or disconnects Tailscale, switches profiles, or disables the override.
This policy setting is experimental and is subject to change.
=> ipn/ipnlocal,util/syspolicy: add support for ExitNode.AllowOverride policy setting

cmd/k8s-operator/deploy/chart/templates/NOTES.txt
Based on feedback that it wasn't clear what the user is meant to do with the output of the last command, clarify that it's an optional command to explore what got created.
Updates #13427
Change-Id: Iff64ec6d02dc04bf4bbebf415d7ed1a44e7dd658
=> cmd/k8s-operator/deploy: clarify helm install notes

wgengine/magicsock/magicsock.go
=> wgengine/magicsock: don't peer relay if NodeAttrOnlyTCP443 is set

cmd/k8s-operator/proxygroup.go, cmd/k8s-proxy/k8s-proxy.go, kube/k8s-proxy/conf/conf.go
This commit modifies the k8s-operator and k8s-proxy to support passing down the accept-routes configuration from the proxy class as a configuration value read and used by the k8s-proxy when ran as a distinct container managed by the operator.
Updates https://github.com/tailscale/tailscale/issues/13358
=> cmd/{k8s-operator,k8s-proxy}: apply accept-routes configuration to k8s-proxy

tailcfg/tailcfg.go
To signal when a tailnet has the `traffic-steering` feature flag, Control will send a `traffic-steering` NodeCapability in netmap’s AllCaps.
This patch adds `tailcfg.NodeAttrTrafficSteering` so that it can be used in the control plane. Future patches will implement the actual steering mechanisms.
Updates tailscale/corp#29966
=> ipn/ipnlocal: add traffic-steering nodecap

cmd/tailscale/cli/ping.go, ipn/ipnstate/ipnstate.go, tailcfg/tailcfg.go, wgengine/magicsock/magicsock.go
Updates the output for `tailscale ping` to indicate if a peer relay was traversed, just like the output for DERP or direct connections. Output should appear as:
```
jwhited@i5-12400-1:~$ tailscale ping i5-12400-2
pong from i5-12400-2 (100.78.139.4) via peer-relay(192.168.1.215:7777:vni:1) in 28ms
pong from i5-12400-2 (100.78.139.4) via DERP(lax) in 28ms
pong from i5-12400-2 (100.78.139.4) via 10.0.0.20:41641 in 79ms
```
Fixes tailscale/corp#30034
Signed-off-by: Dylan Bargatze <dylan@tailscale.com>
=> cmd/tailscale, ipn/ipnstate, wgengine/magicsock: Update ping output for peer relay

docs/windows/policy/en-US/tailscale.adml, docs/windows/policy/tailscale.admx
In this PR, we make `ExitNode.AllowOverride` configurable as part of the Exit Node ADMX policy setting, similarly to Always On w/ "Disconnect with reason" option.
=> docs/windows/policy: add ExitNode.AllowOverride as an option to ExitNodeID policy

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, tailcfg/tailcfg.go
When `tailscale exit-node suggest` contacts the LocalAPI for a suggested exit node, the client consults its netmap for peers that contain the `suggest-exit-node` peercap. It currently uses a series of heuristics to determine the exit node to suggest.
When the `traffic-steering` feature flag is enabled on its tailnet, the client will defer to Control’s priority scores for a particular peer. These scores, in `tailcfg.Hostinfo.Location.Priority`, were historically only used for Mullvad exit nodes, but they have now been extended to score any peer that could host a redundant resource.
Client capability version 119 is the earliest client that understands these traffic steering scores. Control tells the client to switch to rely on these scores by adding `tailcfg.NodeAttrTrafficSteering` to its …
=> ipn/ipnlocal: add traffic steering support to exit-node suggestions

cmd/tailscale/cli/configure-jetkvm.go, cmd/tailscale/cli/configure.go, version/distro/distro.go
To write the init script.
And fix the JetKVM detection to work during early boot while the filesystem
and modules are still being loaded; it wasn't being detected on early boot
and then tailscaled was failing to start because it didn't know it was on JetKVM
and didn't modprobe tun.
Updates #16524
=> cmd/tailscale/cli: add "configure jetkvm" subcommand

cmd/tsidp/tsidp.go
This makes it easier to track how widely tsidp is used in practice.
=> cmd/tsidp: set hostinfo.App in tsnet mode

cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_specs.go, cmd/k8s-proxy/k8s-proxy.go, kube/k8s-proxy/conf/conf.go
Recently, [Static Endpoints were implemented](https://github.com/tailscale/tailscale/pull/16115) for ProxyGroups. This PR implements Static Endpoints for the new HA kube-apiserver ProxyGroup type.
Note that this implementation uses `os.Setenv` in process the `k8s-proxy` container to configure `StaticEndpoints`. This is due to the fact that we cannot currently configure it via the `ipn.ConfigVAlpha`or prefs via tsnet.
Updates https://github.com/tailscale/tailscale/issues/13358
=>  cmd/{k8s-operator,k8s-proxy},kube/k8s-proxy: add static endpoints for kube-apiserver type ProxyGroups

wgengine/magicsock/endpoint.go
udpRelayEndpointReady used to write into the peerMap, which required holding Conn.mu, but this changed in f9e7131.
=> wgengine/magicsock: don't acquire Conn.mu in udpRelayEndpointReady

net/udprelay/server.go
Socket read errors currently close the server, so we need to understand when and why they occur.
Updates tailscale/corp#30118
=> net/udprelay: log socket read errors

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
With [auto exit nodes](https://tailscale.com/blog/auto-exit-nodes) enabled, the client picks exit nodes from the ones advertised in the network map. Usually, it picks the one with the highest priority score, but when the top spot is tied, it used to pick randomly. Then, once it made a selection, it would strongly prefer to stick with that exit node. It wouldn’t even consider another exit node unless the client was shutdown or the exit node went offline. This is to prevent flapping, where a client constantly chooses a different random exit node.
The major problem with this algorithm is that new exit nodes don’t get selected as often as they should. In fact, they wouldn’t even move over if a higher scoring exit node appeared.
Let’s say that you have an exit node and it’s overloaded. So you …
=> ipn/ipnlocal: use rendezvous hashing to traffic-steer exit nodes

client/systray/systray.go
Ubuntu gnome has a different name on at least 25.04.
Updates #1708
=> client/systray: look for ubuntu gnome

feature/tpm/tpm_linux.go
The tpmrm0 is a kernel-managed version of tpm0 that multiplexes multiple concurrent connections. The basic tpm0 can only be accessed by one application at a time, which can be pretty unreliable.
Updates #15830
=> feature/tpm: try opening /dev/tpmrm0 before /tmp/tpm0 on Linux

tstest/integration/capmap_test.go, tstest/integration/testcontrol/testcontrol.go
Fixes #16560
Peer CapMaps were missing from MapResponses in the test control server.
=> tstest/integration/testcontrol: include peer CapMaps in MapResponses

feature/tpm/tpm.go
This function is behind a sync.Once so we should only see errors at startup. In particular the error from `open` is useful to diagnose why TPM might not be accessible.
Updates #15830
=> feature/tpm: log errors on the initial info fetch

cmd/k8s-operator/api-server-proxy.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/proxygroup.go, cmd/k8s-operator/proxygroup_test.go, cmd/k8s-proxy/k8s-proxy.go, k8s-operator/api-proxy/proxy.go, k8s-operator/sessionrecording/hijacker.go, kube/k8s-proxy/conf/conf.go, kube/kubetypes/types.go, kube/kubetypes/types_test.go
Updates k8s-proxy's config so its auth mode config matches what we set in kube-apiserver ProxyGroups for consistency.
Updates #13358
Change-Id: I95e29cec6ded2dc7c6d2d03f968a25c822bc0e01
=> cmd/{k8s-operator,k8s-proxy},kube: use consistent type for auth mode config

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go
When a client selects a particular exit node, Control may use that as a signal for deciding other routes.
This patch causes the client to report whenever the current exit node changes, through [tailcfg.Hostinfo.ExitNodeID](https://pkg.go.dev/tailscale.com/tailcfg#Hostinfo.ExitNodeID). It relies on a properly set [ipn.Prefs.ExitNodeID](https://pkg.go.dev/tailscale.com/ipn#Prefs.ExitNodeID), which should already be resolved by `tailscale set`.
Updates tailscale/corp#30536
=> tailcfg: add Hostinfo.ExitNodeID to report the selected exit node

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
In #16625, I introduced a mechanism for sending the selected exit node to Control via tailcfg.Hostinfo.ExitNodeID as part of the MapRequest. @nickkhyl pointed out, in https://github.com/tailscale/tailscale/pull/16625#discussion_r2224054703, that LocalBackend.doSetHostinfoFilterServices needs to be triggered in order to actually send this update. This patch adds that command. It also prevents the client from sending `"auto:any"` in that field, because that’s not a real exit node ID.
This patch also fills in some missing checks in TestConfigureExitNode.
Updates tailscale/corp#30536
=> ipn/ipnlocal: send Hostinfo after resolveExitNode for "auto:any"

k8s-operator/sessionrecording/hijacker.go
This PR adds the session type to the cast header that is sent to tsrecorder.
Updates #16490
=> k8s-operator: adding session type to cast header

net/portmapper/portmapper.go
Ideally when we attempt to create a new port mapping, we should not return
without error when no mapping is available. We already log these cases as
unexpected, so this change is just to avoiding panicking dispatch on the
invalid result in those cases. We still separately need to fix the underlying
control flow.
Updates #16662
Change-Id: I51e8a116b922b49eda45e31cd27f6b89dd51abc8
=> net/portmapper: avert a panic when a mapping is not available

util/syspolicy/setting/snapshot.go, util/syspolicy/setting/snapshot_test.go
`jsonv2` now returns an error when you marshal or unmarshal a `time.Duration` without an explicit format flag. This is an intentional, temporary choice until the default `time.Duration` representation is decided (see golang/go#71631).
`setting.Snapshot` can hold `time.Duration` values inside a `map[string]any`, so the `jsonv2` update breaks marshaling. In this PR, we start using a custom marshaler until that decision is made or golang/go#71664 lets us specify the format explicitly.
This fixes `tailscale syspolicy list` failing when `KeyExpirationNotice` or any other `time.Duration` policy setting is configured.
Fixes #16683
=> util/syspolicy/setting: use a custom marshaler for `time.Duration`

util/syspolicy/setting/snapshot.go, util/syspolicy/setting/snapshot_test.go
`jsonv2` now returns an error when you marshal or unmarshal a `time.Duration` without an explicit format flag. This is an intentional, temporary choice until the default `time.Duration` representation is decided (see golang/go#71631).
`setting.Snapshot` can hold `time.Duration` values inside a map[string]any, so the `jsonv2` update breaks marshaling. In this PR, we start using a custom marshaler until that decision is made or golang/go#71664 lets us specify the format explicitly.
This fixes `tailscale syspolicy list` failing when `KeyExpirationNotice` or any other `time.Duration` policy setting is configured.
Fixes #16683
(cherry picked from commit 4df02bbb486d07b0ad23f59c4cb3675ab691e79b)
=> util/syspolicy/setting: use a custom marshaler for time.Duration

net/portmapper/portmapper.go
Ideally when we attempt to create a new port mapping, we should not return without error when no mapping is available. We already log these cases as unexpected, so this change is just to avoiding panicking dispatch on the invalid result in those cases. We still separately need to fix the underlying control flow.
Updates #16662
Change-Id: I51e8a116b922b49eda45e31cd27f6b89dd51abc8
(cherry picked from commit 5ce3845a021b8384814f8279546af80e9fddbf39)
=> net/portmapper: avert a panic when a mapping is not available (#16686)

k8s-operator/sessionrecording/hijacker.go
Cherry-picks https://github.com/tailscale/tailscale/pull/16660 into 1.86 branch to provide tsrecorder with the session type (`attach` or `exec`) for which is being recorded.
Updates https://github.com/tailscale/tailscale/issues/16490
=>  k8s-operator: adding session type to cast header (#16660)

cmd/tailscale/cli/serve_v2.go
This commit update the message for recommanding clear command after running serve for service. Instead of a flag, we pass the service name as a parameter.
Fixes tailscale/corp#30846
=> cmd/tailscale/cli: update message for disable service

cmd/tsidp/tsidp.go, tsnet/tsnet.go
The tsidp oidc-key.json ended up in the root directory or home dir of the user process running it.
Update this to store it in a known location respecting the TS_STATE_DIR and flagDir options.
Fixes #16734
=> cmd/tsidp,tsnet: update tsidp oidc-key store path

cmd/k8s-operator/deploy/crds/tailscale.com_proxyclasses.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/sts.go, cmd/k8s-operator/sts_test.go, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_proxyclass.go
Fixes #16682
Signed-off-by: Lee Briggs <lee@leebriggs.co.uk>
=> cmd/k8s-operator,k8s-operator: allow setting a `priorityClassName`

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
WireGuard message type is little-endian encoded.
Updates tailscale/corp#30903
=> wgengine/magicsock: fix looksLikeInitiationMsg endianness

client/systray/systray.go, cmd/systray/systray.go, cmd/tailscale/cli/systray.go
Pass a local.Client to systray.Run, so we can use the existing global localClient in the cmd/tailscale CLI.  Add socket flag to cmd/systray.
Updates #1708
=> client/systray: allow specifying tailscaled socket

scripts/installer.sh
Tested in a VM. We don't have packages for Bazzite but Bazzite has Tailscale preinstalled and people keep trying to run it and getting confused, so update the script to explain it's already installed by default and how to enable it. This is similar to advice we give NixOS users.
Fixes #14540
=> scripts/installer.sh: add bazzite handling

feature/taildrop/delete.go, feature/taildrop/delete_test.go, feature/taildrop/ext.go, feature/taildrop/fileops.go, feature/taildrop/fileops_fs.go, feature/taildrop/paths.go, feature/taildrop/peerapi_test.go, feature/taildrop/resume.go, feature/taildrop/resume_test.go, feature/taildrop/retrieve.go, feature/taildrop/send.go, feature/taildrop/send_test.go, feature/taildrop/taildrop.go, feature/taildrop/taildrop_test.go
In Android, we are prompting the user to select a Taildrop directory when they first receive a Taildrop: we block writes on Taildrop dir selection. This means that we cannot use Dir inside managerOptions, since the http request would not get the new Taildrop extension. This PR removes, in the Android case, the reliance on m.opts.Dir, and instead has FileOps hold the correct directory.
This expands FileOps to be the Taildrop interface for all file system operations.
Updates tailscale/corp#29211
Signed-off-by: kari-ts <kari@tailscale.com>
restore tstest
(cherry picked from commit d897d809d649b312a3f87d01d9f9426d518cdced)
=> feature/taildrop: do not use m.opts.Dir for Android (#16316)

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
This commit also extends the updateRelayServersSet unit tests to cover onNodeViewsUpdate.
Fixes tailscale/corp#31080
=> wgengine/magicsock: fix missing Conn.hasPeerRelayServers.Store() call

wgengine/magicsock/magicsock.go
=> wgengine/magicsock: add clientmetric for Peer Relay challenge reception

control/controlclient/direct.go
Grab a copy under mutex in sendMapRequest.
```
WARNING: DATA RACE
Read at 0x00c00cc833f8 by goroutine 83000:
tailscale.com/control/controlclient.(*Direct).sendMapRequest()
/home/awly/src/tailscale/control/controlclient/direct.go:909 +0x1404
tailscale.com/control/controlclient.(*Direct).SendUpdate()
/home/awly/src/tailscale/control/controlclient/direct.go:821 +0x35d
tailscale.com/control/controlclient.(*Auto).updateRoutine()
/home/awly/src/tailscale/control/controlclient/auto.go:85 +0x32d
tailscale.com/control/controlclient.(*Auto).Start.gowrap3()
/home/awly/src/tailscale/control/controlclient/auto.go:239 +0x33
Previous write at 0x00c00cc833f8 by goroutine 83294:
tailscale.com/control/controlclient.(*Direct).SetTKAHead()
/home/awly/src/tailscale/control/controlclient/direct.go:397 +0x114 …
```
=> control/controlclient: fix data race on tkaHead

client/tailscale/apitype/controltype.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/node_backend.go, tailcfg/tailcfg.go, types/dnstype/dnstype.go, types/dnstype/dnstype_clone.go, types/dnstype/dnstype_test.go, types/dnstype/dnstype_view.go
Updates #8237 
Fixes tailscale/corp#30906
Fixes tailscale/corp#30907
- dnstype.Resolver  adds a boolean UseWithExitNode that controls whether the resolver should be used in tailscale exit node contexts (not wireguard exit nodes)
- If UseWithExitNode resolvers are found, they are installed as the global resolvers
- If no UseWithExitNode resolvers are found, the exit node resolver continues to be installed as the global resolver
- Split DNS Routes referencing UseWithExitNode resolvers are also installed.
I wanted to get this PR up, but I am in parallel bringing these changes into corp, making sure it compiles, and doing some light local controller testing.
This PR also adds some test coverage split DNS routes with zero-length resolver lists, independent of UseWithExitNode routes.
A former …
=> dnstype, ipnlocal: dnstype.Resolver.UseWithExitNode controls exit node DNS behavior

types/key/hardware_attestation.go
Define the HardwareAttestionKey interface describing a platform-specific hardware backed node identity attestation key. Clients will register the key type implementations for their platform.
Updates tailscale/corp#31269
=> types/key: init HardwareAttestionKey implementation

release/dist/qnap/files/scripts/Dockerfile.qpkg, release/dist/qnap/files/scripts/sign-qpkg.sh
This pulls in a change from github.com/tailscale/QDK to verify code signing when using QNAP_SIGNING_SCRIPT.
It also upgrades to the latest Google Cloud PKCS#11 library, and reorders the Dockerfile to allow for more efficient future upgrades to the included QDK.
Updates tailscale/corp#23528
Depends on https://github.com/tailscale/QDK/pull/3
=> release/dist/qnap: verify code signing

cmd/derpprobe/derpprobe.go, prober/prober.go, prober/prober_test.go
Add a Run all probes handler that executes all probes except those that are continuous or the derpmap probe.
This is leveraged by other tooling to confirm DERP stability after a deploy.
Updates tailscale/corp#27370
=> cmd/derpprobe,prober: add run all probes handler

client/systray/systray.go
Thanks to /u/niftyrider for reporting the issue: https://www.reddit.com/r/Tailscale/comments/1mqe4ei/comment/n90grx0/
Updates #1708
=> client/systray: disable 'more settings' menu if backend not running

prober/prober.go, prober/prober_test.go
Update the runall handler to be more generic with an exclude param to exclude multiple probes as the requesters definition.
Updates tailscale/corp#27370
=> prober: update runall handler to be generic

cmd/natc/ippool/consensusippool.go, cmd/natc/natc.go, tsconsensus/tsconsensus.go
Add the ability for operators of natc in consensus mode to remove servers from the raft cluster config, without losing other state.
Updates #14667
=> cmd/natc,tsconsensus: add cluster config admin

cmd/k8s-proxy/k8s-proxy.go, k8s-operator/api-proxy/proxy.go
Cherry picks #16919 onto the 1.86 release branch, preparing for a v1.86.5 patch for containers.
The serve code leaves it up to the system's DNS resolver and netstack to figure out how to reach the proxy destination. Combined with k8s-proxy running in userspace mode, this means we can't rely on MagicDNS being available or tailnet IPs being routable. I'd like to implement that as a feature for serve in userspace mode, but for now the safer fix to get kube-apiserver ProxyGroups consistently working in all environments is to switch to using localhost as the proxy target instead.
This has a small knock-on in the code that does WhoIs lookups, which now needs to check the X-Forwarded-For header that serve populates to get the correct tailnet IP to look up, because the request's remote address …
=> cmd/k8s-proxy,k8s-operator: fix serve config for userspace mode (#16919)

ipn/backend.go, ipn/ipnlocal/bus.go, ipn/ipnlocal/local.go
fixes tailscale/corp#26369
The suggested exit node is currently only calculated during a localAPI request. For older UIs, this wasn't a bad choice - we could just fetch it on-demand when a menu presented itself.  For newer incarnations however, this is an always-visible field that needs to react to changes in the suggested exit node's value.
This change recalculates the suggested exit node ID on localBackend updates and broadcasts it on the IPN bus.   The localAPI version of this remains intact for the time being.
=> ipn/local: add the suggested exit node to the ipn bus

.github/workflows/request-dataplane-review.yml
@tailscale/dataplane almost never needs to review depaware.txt, when it is the only change to the DERP implementation.
Related #16372
=> .github/workflows: reviewing depaware.txt is unnecessary

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/profiles.go
To reduce risk to the shortly-upcoming release, revert some of the incremental
changes to locking behaviour in the LocalBackend. We can reapply these after
the release to get exercise in unstable builds, but for now the schedule is
close.
This reverts the following commits:
b411ffb52f13 "ipn/ipnlocal: remove UnlockEarly from doSetHostinfoFilterServices"
9002e5fd6b8e "ipn/ipnlocal: remove an unnecessary unlock shortcut"
2fb9472990ea "ipn/ipnlocal: remove unnecessary usees of lockAndGetUnlock"
6c8fef961eab "ipn/ipnlocal: replace the LockedOnEntry pattern with conventional lock/unlock discipline (#16925)"
Updates #11649
Updates #15160
Change-Id: I6b1006c18fd1c2f1abfb847761e480a60957b883
=> ipn/ipnlocal: revert some locking changes ahead of release branch cut

util/syspolicy/policyclient/policyclient.go
We should never use the real syspolicy implementation in tests by
default. (the machine's configuration shouldn't affect tests)
You either specify a test policy, or you get a no-op one.
Updates #16998
=> util/syspolicy/policyclient: always use no-op policyclient in tests by default

wgengine/magicsock/magicsock.go
=> wgengine/magicsock: log the peer failing disco writes are intended for

prober/prober.go, prober/prober_test.go
It was a bit confusing that provided history did not include the current probe results.
Updates tailscale/corp#20583
=> prober: include current probe results in run-probe text response

tstest/integration/integration_test.go, util/expvarx/expvarx_test.go
=> utils/expvarx, tstest/integration: mark two tests as known flaky

cmd/tailscaled/debug_forcereflect.go
This adds a file that's not compiled by default that exists just to
make it easier to do binary size checks, probing what a binary would
be like if it included reflect methods (as used by html/template, etc).
As an example, once tailscaled uses reflect.Type.MethodByName(non-const-string) anywhere,
the build jumps up by 14.5 MB:
$ GOOS=linux GOARCH=amd64 ./tool/go build -tags=ts_include_cli,ts_omit_webclient,ts_omit_systray,ts_omit_debugeventbus -o before ./cmd/tailscaled
$ GOOS=linux GOARCH=amd64 ./tool/go build -tags=ts_include_cli,ts_omit_webclient,ts_omit_systray,ts_omit_debugeventbus,ts_debug_forcereflect -o after ./cmd/tailscaled
$ ls -l before after
-rwxr-xr-x@ 1 bradfitz  staff  41011861 Sep  9 07:28 before
-rwxr-xr-x@ 1 bradfitz  staff  55610948 Sep  9 07:29 after
This is …
=> cmd/tailscaled: add disabled debug file to force reflect for binary size experiments

cmd/k8s-operator/e2e/acl.hujson, cmd/k8s-operator/e2e/ingress_test.go, cmd/k8s-operator/e2e/main_test.go, cmd/k8s-operator/e2e/proxy_test.go
Removes ACL edits from e2e tests in favour of trying to simplify the tests and separate the actual test logic from the environment setup logic as much as possible. Also aims to fit in with the requirements that will generally be filled anyway for most devs working on the operator; in particular using tags that fit in with our documentation.
Updates tailscale/corp#32085
Change-Id: I7659246e39ec0b7bcc4ec0a00c6310f25fe6fac2
=> cmd/k8s-operator: simplify scope of e2e tests

cmd/k8s-operator/operator_test.go, cmd/k8s-operator/svc.go
This commit fixes an issue within the service reconciler where we end
up in a constant reconciliation loop. When reconciling, the loadbalancer
status is appended to but not reset between each reconciliation, leading
to an ever growing slice of duplicate statuses.
Fixes https://github.com/tailscale/tailscale/issues/17105
Fixes https://github.com/tailscale/tailscale/issues/17107
=> k8s-operator: reset service status before append

wgengine/magicsock/magicsock.go
endpointState is used for tracking UDP direct connection candidate addresses. If it contains a DERP addr, then direct connection path discovery will always send a wasteful disco ping over it. Additionally, CLI "tailscale ping" via peer relay will race over DERP, leading to a misleading result if pong arrives via DERP first.
Disco pongs arriving via DERP never influence path selection. Disco ping/pong via DERP only serves "tailscale ping" reporting.
Updates #17121
=> wgengine/magicsock: don't add DERP addrs to endpointState

logpolicy/logpolicy.go
=> logpolicy: remove the deprecated and now-unused `NewWithConfigPath`

ipn/ipnlocal/local.go, net/netmon/netmon.go, net/netmon/netmon_test.go, wgengine/userspace.go
This makes things work slightly better over the eventbus.
Also switches ipnlocal to use the event over the eventbus instead of the
direct callback.
Updates #15160
What the graph looks like at this point:
=> net/netmon: make ChangeDelta event not a pointer

cmd/derper/ace.go
Updates tailscale/corp#32168
Updates tailscale/corp#32226
=> cmd/derper: permit port 80 in ACE targets

cmd/tailscale/cli/switch.go
Fixes #12255
Add a new command to the CLI to remove a profile from the local client. This also fixes a bug in the local client where the DELETE request was not being sent correctly.
I decided to go with this approach instead of what is mentioned as a request solution for the following reasons.
1. Since commands like `switch`, `login` and `logout` reference the user's account(s), I felt it made more sense to have it be a regular command instead of the functionality being contained under the `switch` command. 
2. This makes it more accessible for Linux users who do not have a GUI interface and would look towards `tailscale --help` for directions on how to remove an account
3. The command name `remove` seemed a bit clearer than using `delete` as `delete` could be interpreted as fully purging …
=> cmd/tailscale/cli: add `remove` command for accounts

control/controlknobs/controlknobs.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go
Previously, seamless key renewal was an opt-in feature.  Customers had to set a `seamless-key-renewal` node attribute in their policy file.
This patch enables seamless key renewal by default for all clients.
It includes a `disable-seamless-key-renewal` node attribute we can set in Control, so we can manage the rollout and disable the feature for clients with known bugs.  This new attribute makes the feature opt-out.
Updates tailscale/corp#31479
---
This is blocked on merging #17074 and #17090, and should not be merged until after the 1.88 release branch.
There will be a corresponding corp PR with a feature flag to set/unset this nodeattr.
=> control, ipn, tailcfg: enable seamless key renewal by default

util/eventbus/eventbustest/eventbustest.go, util/eventbus/eventbustest/eventbustest_test.go
When developing (and debugging) tests, it is useful to be able to see all the
traffic that transits the event bus during the execution of a test.
Updates #15160
Change-Id: I929aee62ccf13bdd4bd07d786924ce9a74acd17a
=> util/eventbus: add a LogAllEvents helper for testing

util/eventbus/eventbustest/eventbustest_test.go
When tests run in parallel, events from multiple tests on the same bus can
intercede with each other. This is working as intended, but for the test cases
we want to control exactly what goes through the bus.
To fix that, allocate a fresh bus for each subtest.
Fixes #17197
Change-Id: I53f285ebed8da82e72a2ed136a61884667ef9a5e
=> util/eventbus: fix flakes in eventbustest tests

util/eventbus/bus_test.go, util/eventbus/monitor.go
~WIP for discussion.~
The first commit is the library change, the second is an example of how it can
be applied to existing use. If this is approved, I will merge _only_ the first
commit in this PR, and will move the second commit to a new PR.
---
A common pattern in event bus usage is to run a goroutine to service a
collection of subscribers on a single bus client. To have an orderly shutdown,
however, we need a way to wait for such a goroutine to be finished.
This commit adds a Monitor type that makes this pattern easier to wire up:
rather than having to track all the subscribers and an extra channel, the
component need only track the client and the monitor.  For example:
cli := bus.Client("example")
m := cli.Monitor(func(c *eventbus.Client) {
s1 := eventbus.Subscribe[T](cli)
s2 := …
=> util/eventbus: add a Monitor type to manage subscriber goroutines

net/dnscache/dnscache.go, net/dnscache/dnscache_test.go
The controlhttp dialer with a ControlDialPlan IPv6 entry was hitting a
case where the dnscache Resolver was returning an netip.Addr zero
value, where it should've been returning the IPv6 address.
We then tried to dial "invalid IP:80", which would immediately fail,
at least locally.
Mostly this was causing spammy logs when debugging other stuff.
Updates tailscale/corp#32534
=> net/dnscache: fix case where Resolver could return zero IP with single IPv6 address

ipn/ipnauth/ipnauth.go, ipn/ipnauth/ipnauth_notwindows.go, ipn/ipnserver/actor.go
We never implemented the peercred package on OpenBSD (and I just tried
again and failed), but we've always documented that the creds pointer
can be nil for operating systems where we can't map the unix socket
back to its UID. On those platforms, we set the default unix socket
permissions such that only the admin can open it anyway and we don't
have a read-only vs read-write distinction. OpenBSD was always in that
camp, where any access to Tailscale's unix socket meant full access.
But during some refactoring, we broke OpenBSD in that we started
assuming during one logging path (during login) that Creds was non-nil
when looking up an ipnauth.Actor's username, which wasn't relevant (it
was called from a function "maybeUsernameOf" anyway, which threw away
errors).
Verified on an OpenBSD VM. …
=> ipn/ipnauth: don't crash on OpenBSD trying to log username of unknown peer

cmd/k8s-operator/logger.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/sts.go, tsnet/tsnet.go
This commit modifies the k8s operator to wrap its logger using the logtail
logger provided via the tsnet server. This causes any logs written by
the operator to make their way to Tailscale in the same fashion as
wireguard logs to be used by support.
This functionality can also be opted-out of entirely using the
"TS_NO_LOGS_NO_SUPPORT" environment variable.
Updates https://github.com/tailscale/corp/issues/32037
=> k8s-operator: send operator logs to tailscale

client/web/web.go
Also update to use the new DisplayNameOrDefault.
Updates tailscale/corp#30456
=> client/web: use network profile for displaying tailnet info

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/state_test.go, ipn/lapitest/backend.go
I think this was originally a brain-o in 9380e2dfc61a720d. It's
disabling the port _poller_, listing what open ports (i.e. services)
are open, not PMP/PCP/UPnP port mapping.
While there, drop in some more testenv.AssertInTest() in a few places.
=> ipn/ipnlocal: rename misnamed DisablePortMapperForTest to DisablePortPollerForTest

cmd/tailscale/cli/up.go
Ideally we would remove this warning entirely, as it is now possible to reauthenticate without losing connectivty. However, it is still possible to lose SSH connectivity if the user changes the ownership of the machine when they do a force-reauth, and we have no way of knowing if they are going to do that before they do it.
For now, let's just reduce the strength of the warning to warn them that they "may" lose their connection, rather than they "will".
Updates tailscale/corp#32429
=> cmd/tailscale/cli: reduce strength of lose-ssh risk warning

tstest/integration/integration_test.go, tstest/integration/testcontrol/testcontrol.go
This pull request contains some changes originally written (and reviewed) in #17074 to improve `tailscale up` for seamless key renewal. These two commits are unrelated to seamless and are uncontroversial to merge; we're still discussing the best approach to seamless so I've extracted these separately so they can be merged immediately.
=> tstest/integration: expand the tests for `tailscale up`

cmd/k8s-nameserver/main.go, cmd/k8s-nameserver/main_test.go, cmd/k8s-operator/deploy/crds/tailscale.com_dnsconfigs.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/dnsrecords.go, cmd/k8s-operator/dnsrecords_test.go, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_tsdnsconfig.go, k8s-operator/utils.go
This change adds full IPv6 support to the Kubernetes operator's DNS functionality, enabling dual-stack and IPv6-only cluster support.
Changes:
- Add IP6 field to Records struct for storing IPv6 addresses
- Update DNS records reconciler to handle both IPv4 and IPv6 from EndpointSlices
- Support dual-stack services with multiple ClusterIPs
- Implement AAAA record responses in k8s-nameserver
Fixes #16633
=> k8s-operator: add IPv6 support for DNS records

client/local/local.go, cmd/tailscaled/tailscaled.go, cmd/tsconnect/wasm/wasm_js.go, ipn/ipnserver/server.go, ipn/ipnserver/server_test.go, ipn/lapitest/server.go, ipn/localapi/localapi.go, util/syspolicy/pkey/pkey.go, util/syspolicy/policy_keys.go
A customer wants to allow their employees to restart `tailscaled` at will, when access rights and MDM policy allow it, as a way to fully reset client state and re-create the tunnel in case of connectivity issues.
On Windows, the main `tailscaled` process runs as a child of a service process. The service restarts the child when it exits (or crashes) until the service itself is stopped. Regular (non-admin) users can't stop the service, and allowing them to do so isn't ideal, especially in managed or multi-user environments.
In this PR, we add a LocalAPI endpoint that instructs `ipnserver.Server`, and by extension the `tailscaled` process, to shut down. The service then restarts the child `tailscaled`. Shutting down `tailscaled` requires LocalAPI write access and an enabled policy setting. …
=> various: allow tailscaled shutdown via LocalAPI

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
On platforms that are causing EPIPE at a high frequency this is resulting in non-working connections, for example when Apple decides to forcefully close UDP sockets due to an unsoliced packet rejection in the firewall.
Too frequent rebinds cause a failure to solicit the endpoints triggering the rebinds, that would normally happen via CallMeMaybe.
Updates #14551
Updates tailscale/corp#25648
=> wgengine/magicsock: fix rebind debouncing

feature/tpm/tpm.go
We can only register one key implementation per process. When running on macOS or Android, trying to register a separate key implementation from feature/tpm causes a panic.
Updates #15830
=> feature/tpm: only register HardwareAttestationKey on linux/windows

net/memnet/listener.go, net/memnet/memnet.go, net/memnet/memnet_test.go
Listen address reuse is allowed as soon as the previous listener is
closed. There is no attempt made to emulate more complex address reuse
logic.
Updates tailscale/corp#28078
Change-Id: I56be1c4848e7b3f9fc97fd4ef13a2de9dcfab0f2
Signed-off-by: Brian Palmer <brianp@tailscale.com>
=> net/memnet: allow listener address reuse

cmd/tailscale/cli/debug.go, control/controlclient/auto.go, control/controlclient/direct.go, control/controlclient/noise.go, internal/noiseconn/conn.go, ipn/ipnlocal/local.go, tsnet/tsnet.go
It never launched and I've lost hope of it launching and it's in my
way now, so I guess it's time to say goodbye.
Updates tailscale/corp#4383
Updates #17305
=> tsnet: remove AuthenticatedAPITransport (API-over-noise) support

appc/appconnector.go, appc/appconnector_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi_test.go
This is part of the change from #17180.
Replace the positional arguments to NewAppConnector with a Config struct.
Update the existing uses. Other than the API change, there are no functional
changes in this commit.
Updates #15160
Updates #17192
Change-Id: Ibf37f021372155a4db8aaf738f4b4f2c746bf623
=> appc: factor app connector arguments into a Config type

appc/appconnector.go, appc/appconnector_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi_test.go
This is part of the change from #17180.
I believe this change does not need any updates to the Apple, Windows, or
Android clients, as none of them or their tests appear to explicitly create
AppConnector values.
Require the presence of the bus, but does not use it yet.  Check for required
fields and update tests and production use to plumb the necessary arguments.
Updates #15160
Updates #17192
Change-Id: I8cefd2fdb314ca9945317d3320bd5ea6a92e8dcb
=> appc,ipn/ipnlocal: add a required event bus to the AppConnector type

cmd/k8s-operator/deploy/chart/templates/.gitignore, cmd/k8s-operator/generate/main.go, cmd/k8s-operator/operator.go
Add a .gitignore for the chart version of the CRDs that we never commit, because the static manifest CRD files are the canonical version. This makes it easier to deploy the CRDs via the helm chart in a way that reflects the production workflow without making the git checkout "dirty".
Given that the chart CRDs are ignored, we can also now safely generate them for the kube-generate-all Makefile target without being a nuisance to the state of the git checkout. Added a slightly more robust repo root detection to the generation logic to make sure the command works from the context of both the Makefile and the image builder command we run for releases in corp.
Updates tailscale/corp#32085
Change-Id: Id44a4707c183bfaf95a160911ec7a42ffb1a1287
=> cmd/k8s-operator: add .gitignore for generated chart CRDs

feature/relayserver/relayserver.go, feature/relayserver/relayserver_test.go
Note to reviewers: This may be easier to read with whitespace disabled.
Instead of using separate channels to manage the lifecycle of the eventbus
client, use the recently-added eventbus.Monitor, which handles signaling the
processing loop to stop and waiting for it to complete.  This allows us to
simplify some of the setup and cleanup code in the relay server.
Updates #15160
Change-Id: Ia1a47ce2e5a31bc8f546dca4c56c3141a40d67af
=> feature/relayserver: use eventbus.Monitor to simplify lifecycle management

control/controlclient/direct.go, control/ts2021/client.go, control/ts2021/conn.go, util/set/handle.go
In the earlier http2 package migration (1d93bdce20ddd2, #17394) I had
removed Direct.Close's tracking of the connPool, thinking it wasn't
necessary.
Some tests (in another repo) are strict and like it to tear down the
world and wait, to check for leaked goroutines. And they caught this
letting some goroutines idle past Close, even if they'd eventually
close down on their own.
This restores the connPool accounting and the aggressife close.
Updates #17305
Updates #17394
=> control/controlclient: restore aggressive Direct.Close teardown

ipn/ipnlocal/local.go
This patch removes some code that didn’t get removed before merging the changes in #16580.
Updates #16551
=> ipn/ipnlocal: remove junk from suggestExitNodeUsingTrafficSteering

wgengine/magicsock/endpoint.go
Switching to a Geneve-encapsulated (peer relay) path in endpoint.handlePongConnLocked is expected around port rebinds, which end up clearing endpoint.bestAddr.
Fixes tailscale/corp#33036
=> wgengine/magicsock: remove misleading unexpected log message

types/lazy/lazy.go
Updates #8419
Updates github.com/golang#62202
=> types/lazy: document difference from sync.OnceValue

tailcfg/tailcfg.go
The fix that was applied in e44e28efcd95596c0a86270c177ef912119bf851.
Updates tailscale/corp#32978
=> tailcfg: bump CapVer for magicsock deadlock fix

cmd/testwrapper/flakytest/flakytest.go, cmd/testwrapper/flakytest/flakytest_test.go
=> cmd/testwrapper/flakytest: use t.Attr annotation on flaky tests

appc/appconnector.go, appc/appconnector_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi_test.go
This is the main substance of the change from #17180.
There are multiple commits in this PR for convenience in review.
They are set up so they could be separately merged, but I would be inclined to
squash them since they are all closely related and should ideally travel
together. If we _do_ want to separate them, they will need a bit more
splitting.
---
(1) ipn/ipnlocal: add subscribers for AppConnector events
(2) appc: make the RouteAdvertiser field optional
Now that events are published for route updates and storage, the
RouteAdvertiser is no longer required. We cannot yet remove it because the
tests still depend on it to verify correctness. We will need to separately
update the test fixtures to remove that dependency, then we can remove the
field entirely.
(3) appc: remove the …
=> appc,ipn/ipnlocal: receive AppConnector updates via the event bus

ipn/ipnlocal/peerapi_test.go
Some of the test cases access fields of the backend that are supposed to be
locked while the test is running, which can trigger the race detector.  I fixed
a few of these in #17411, but I missed these two cases.
Updates #15160
Updates #17192
Change-Id: I45664d5e34320ecdccd2844e0f8b228145aaf603
=> ipn/ipnlocal: fix another racy test

build_dist.sh
Historically, and until recently, --extra-small produced a usable build.
When I recently made osrouter be modular in 39e35379d41fc788 (which is
useful in, say, tsnet builds) after also making netstack modular, that
meant --min now lacked both netstack support for routing and system
support for routing, making no way to get packets into
wireguard. That's not a nice default to users.  (we've documented
build_dist.sh in our KB)
Restore --extra-small to making a usable build, and add --min for
benchmarking purposes.
Updates #12614
=> build_dist.sh: keep --extra-small making a usable build, add --min

ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go
Before we introduced seamless, the "blocked" state was used to track:
* Whether a login was required for connectivity, and therefore we should keep the engine deconfigured until that happened
* Whether authentication was in progress
"blocked" would stop authReconfig from running. We want this when a login is required: if your key has expired we want to deconfigure the engine and keep it down, so that you don't keep using exit nodes (which won't work because your key has expired).
Taking the engine down while auth was in progress was undesirable, so we don't do that with seamless renewal. However, not entering the "blocked" state meant that when we entered the authenticated state, we could no longer tell if we had just brought the tunnel up, or had done a reauthentication. This in turn …
=> ipn/ipnlocal: track whether an auth is in progress

util/eventbus/bus_test.go, util/eventbus/client.go, util/eventbus/subscribe.go
We discussed tradeoffs of this style of API when we were first building the
bus, and decided not to do it. Now that we have more experience of using it for
real, this seems worth revisiting.
---
Proposed by @bradfitz in #17413.
In practice, a lot of subscribers have only one event type of interest, or a
small number of mostly independent ones. In that case, the overhead of running
and maintaining a goroutine to select on multiple channels winds up being more
noisy than we'd like for the user of the API.
For this common case, add a new SubscriberFunc[T] type that delivers events to
a callback owned by the subscriber, directly on the goroutine belonging to the
client itself. This frees the consumer from the need to maintain their own
goroutine to pull events from the channel, and to watch …
=> util/eventbus: add a function-based subscriber type
