.github/workflows/staticcheck.yml
As of a couple commits ago, the codebase is staticcheck-clean. Let's try to keep it that way.
=> meta: add a staticcheck CI step.

cmd/relaynode/debian/gen-changelog
It seems changelog generation got broken by moving the code between
corp and OSS repos, because one of the commit SHAs doesn't have an
associated tag.
In the interest of fixing the build, and because we're not yet trying
to upstream the debian package, I fixed this by allowing hash-based
versions to show up in the changelog. This maybe wrong from a
debian standards perspective, but for our current point in life
it'll work until we learn to do it better.
=> debian: fix changelog generation.

cmd/tailscaled/ipnd.go, wgengine/router_default.go, wgengine/router_openbsd.go
This contains early but working support for OpenBSD: 
I was also able to connect an IRC client to the IRC party line 🎉 
I'd welcome early guidance on how you would the PR to evolve. I littered the code with TODOs as the thoughts came to me. There's also a lot of potential re-use between it and the Linux router.
=> Add OpenBSD support

cmd/tailscale/ipn.go, cmd/tailscaled/ipnd.go, ipn/backend.go, ipn/e2e_test.go, ipn/fake.go, ipn/handle.go, ipn/ipnserver/server.go, ipn/local.go, ipn/message_test.go, ipn/prefs.go, ipn/store.go, ipn/store_test.go
In our current codebase, the agent frontend (e.g. CLI, windows UI) owns a user's state and passes it in on startup. There were good reasons for that on Windows, due to limitations of the OS's IPC mechanisms. However, we've decided we need to move the state into the backend.
This change adds support for owned state in LocalBackend, as well as a file-based implementation that `tailscaled` can use. Frontends can choose whether LocalBackend will use purely frontend state, purely backend state, or import frontend state into the backend before use (as a migration path for existing machine keys).
Other existing frontends (Windows, MacOS, iOS UIs) are unchanged for the moment, and continue to pass in state owned by the frontend.
=> Support state storage in the backend.

wgengine/monitor/monitor.go, wgengine/monitor/monitor_freebsd.go, wgengine/monitor/monitor_linux.go, wgengine/monitor/monitor_unsupported.go, wgengine/router_bsd.go, wgengine/router_darwin.go, wgengine/router_fake.go, wgengine/router_linux.go, wgengine/router_windows.go, wgengine/userspace.go, wgengine/wgengine.go
And make the monitor package portable with no-op implementations on
unsupported operating systems.
=> wgengine: move link monitor to be owned by the engine, not the router

go.mod, go.sum, wgengine/monitor/monitor_linux.go
Bump golang.org/x/sys/unix to get the RTMGRP_* consts and use them.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
=> wgengine/monitor: use RTMGRP_* consts from x/sys/unix

control/controlclient/direct.go, control/controlclient/persist_test.go, ipn/prefs.go, ipn/prefs_test.go
This is a prelude to supporting relaynode's --routes in
tailscaled. The daemon needs to remembers routes to
advertise, and the CLI needs to be able to change the
set of advertised routes. Prefs is the thing used for
both of these.
=> ipn: add AdvertiseRoutes to Prefs.

wgengine/router_freebsd.go, wgengine/router_openbsd.go
#63 was failing due to a destination address not being set on the interface address add.  There were also a few other tweaks made to the interface/router logic to get a more sensible setup and map closer to what the linux build is doing.  I split the implementation into its own freebsd build target so I wouldn't break anything on the openbsd side.
=> wgengine: create freebsd-specific implementation

cmd/tailscale/tailscale.go, ipn/local.go, ipn/prefs.go, ipn/prefs_test.go, tailcfg/tailcfg.go, tailcfg/tailcfg_test.go
With this change, you can advertise routes to the Tailscale network with tailscaled, feature parity with relaynode \o/
The CLI is still super janky. You have to provide the exact non-default settings you want on the CLI every time you invoke it, or it'll undo changes you cared about. It's okay as a one-off-and-never-touch-again configuration tool, but nothing more.
=> ipn: handle advertised routes provided by frontend.

cmd/tailscale/tailscale.go, cmd/tailscaled/tailscaled.go, ipn/ipnserver/server.go, safesocket/basic_test.go, safesocket/pipe_windows.go, safesocket/unixsocket.go
On unix, we want to provide a full path to the desired unix socket.
On windows, currently we want to provide a TCP port, but someday
we'll also provide a "path-ish" object for a named pipe.
For now, simplify the API down to exactly a path and a TCP port.
=> safesocket: simplify API.

cmd/tailscale/tailscale.go, ipn/backend.go, ipn/e2e_test.go, ipn/fake.go, ipn/handle.go, ipn/ipnserver/server.go, ipn/local.go, ipn/message_test.go, ipn/prefs.go, ipn/prefs_test.go
We can't rely on a frontend to provide a control
server URL for tailscaled, so this naturally belongs
in server-persisted state.
=> ipn: move Options.ServerURL into Prefs.

cmd/relaynode/relaynode.go, cmd/taillogin/taillogin.go, cmd/tailscale/tailscale.go, cmd/tailscaled/tailscaled.go, logpolicy/logpolicy.go
We want the config to persist, but logs should live in logs-ey
places.
=> logpolicy: automatically figure out storage paths.

wgengine/router_linux.go
=> wgengine: resolv.conf spelling corrections

wgengine/magicsock/magicsock.go
Intended to help with upgrading from DERP to direct UDP connections.
In particular, this is designed to catch the case where a
HandshakeInitiation packet is sent out but the intermediate NATs
have not been primed, so the packet passes over DERP.
In that case, the HandshakeResponse also comes back over DERP,
and the connection proceeds via DERP without ever trying to punch
through the NAT.
With this change, the HandshakeResponse (which was sprayed out
and so primed one NAT) triggers an UpdateDst, which marks the
next 5 non-handshake packets for spraying. At this point both
NATs are primed, one of these 5 packets will make it through,
triggering an UpdateDst on the other side and then both sides
will be talking directly without DERP.
=> magicsock: spray some packets after an endpoint change

go.mod, wgengine/userspace.go
For 3 seconds after a successful handshake, wgengine will send a
ping packet every 300ms to its peer. This ensures the spray logic
in magicsock has something to spray.
=> wgengine: add pinger to generate initial spray packets

wgengine/faketun.go, wgengine/router_freebsd.go, wgengine/userspace.go
The routes and interfaces will get cleaned up on close, so there's no need to try updating interfaces and routes with empty addresses.  device.Close() will properly close and clean up the device.
this resolves #72
=> wgengine: properly clean up freebsd routes and interfaces on close

cmd/tailscale/netcheck.go, cmd/tailscale/tailscale.go, go.mod, go.sum, interfaces/interfaces.go, ipn/local.go, ipn/local_test.go, netcheck/netcheck.go, tailcfg/tailcfg.go, tailcfg/tailcfg_test.go
* adds new packet "netcheck" to do the checking of UDP, IPv6, and
nearest DERP server, and the Report type for all that (and more
in the future, probably pulling in danderson's natprobe)
* cmd/tailscale netcheck subcommand (tentative name, likely to
change/move) to print out the netcheck.Report.
=> Start of netcheck package & including network state in Hostinfo.

cmd/tailscale/netcheck.go, cmd/tailscale/tailscale.go, go.mod, go.sum
Two commands for now, `up` and `netcheck`. The commands and the flags they take
will change a bunch in the future, but this is good enough to launch on parity
with relaynode.
=> cmd/tailscale: switch to an ffcli based CLI.

interfaces/interfaces.go
When running `tsshd` on macOS, I found that no Tailscale interfaces are found because the interfaces code does not look for `utun` addresses. This small change enabled it and I was happily sshing around my network :smile:.
=> Recognize utun addresses as a possible Tailscale interface name prefix

control/controlclient/netmap.go, tailcfg/tailcfg.go, tailcfg/tailcfg_test.go
We still include them directly in the controlclient network map
just where we have been. Client plumbing we can do later.
=> controlclient, tailcfg: deliver DERP addresses in a separate field

paths/paths.go, paths/paths_unix.go
On BSD, /var/db is what linux calls /var/lib.
On modern linux, /run and /var/run are the same directory, but
on BSD the correct path is /var/run, so use that.
Fixes #79
=> paths: use /var/db for state on BSDs, and /var/run for sockets.

cmd/derper/derper.go, metrics/metrics.go, tsweb/tsweb.go
This lets us publish sets of vars that are breakdowns along one
dimension in a format that Prometheus and Grafana natively know
how to do useful things with.
=> metrics: add a LabelMap type for variables with 1 label dimension.

wgengine/magicsock/magicsock.go
Signed-Off-By: David Anderson <danderson@tailscale.com>
=> wgengine/magicsock: never set a DERP server as a roamAddr.

cmd/tailscaled/tailscaled.go, wgengine/router_darwin.go, wgengine/router_default.go, wgengine/router_freebsd.go, wgengine/router_linux.go, wgengine/router_openbsd.go, wgengine/router_windows.go
The device name "tailscale0" will be used for all platforms except for OpenBSD where "tun" is enforced by the kernel. [CreateTUN](https://github.com/tailscale/wireguard-go/blob/master/tun/tun_openbsd.go#L127-L131) in `wireguard-go` will select the next available "tunX" device name on the OpenBSD system.
Aims to resolve: https://github.com/tailscale/tailscale/issues/38
Signed-off-by: Martin Baillie <martin@baillie.email>
=> wgengine: define default tunname for each platform

wgengine/magicsock/magicsock_test.go
Is this right? Have you seen any reliability problems in the first single-ping test?
=> magicsock: unskip subtests that are reliable

go.sum, netcheck/netcheck.go, netcheck/netcheck_test.go, stunner/stunner.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
It used to make assumptions based on having Anycast IPs that are super
near. Now we're intentionally going to a bunch of different distant
IPs to measure latency.
Also, optimize how the hairpin detection works. No need to STUN on
that socket. Just use that separate socket for sending, once we know
the other UDP4 socket's endpoint. The trick is: make our test probe
also a STUN packet, so it fits through magicsock's existing STUN
routing.
This drops netcheck from ~5 seconds to ~250-500ms.
=> stunner: re-do how Stunner works

ipn/local.go, portlist/netstat_test.go, portlist/poller.go, portlist/portlist.go, portlist/portlist_darwin.go, portlist/portlist_linux.go, portlist/portlist_other.go, portlist/portlist_test.go, portlist/portlist_windows.go
I noticed portlist when looking at some profiles and hadn't looked at
the code much before. This is a first pass over it. It allocates a
fair bit. More love remains, but this does a bit:
```
name       old time/op    new time/op    delta
GetList-8    9.92ms ± 8%    9.64ms ±12%     ~     (p=0.247 n=10+10)
name       old alloc/op   new alloc/op   delta
GetList-8     931kB ± 0%     869kB ± 0%   -6.70%  (p=0.000 n=10+10)
name       old allocs/op  new allocs/op  delta
GetList-8     4.59k ± 0%     3.69k ± 1%  -19.71%  (p=0.000 n=10+10)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/186)
=> portlist: document, clean up, fix an open fd spike, optimize a bit

testy/clock.go, testy/doc.go, tsweb/log.go, tsweb/tsweb.go, tsweb/tsweb_test.go
Also adds tests for StdHandler, because it's getting a bit complex. And a virtual clock type, so as to not have to implement the arrow of time again.
StdHandler has to pass through `http.Handler`, `http.Flusher` and `http.Hijacker` in order to support all our HTTP servers. This leads to a small menagerie of wrappers, in order to correctly handle cases where the underlying ResponseWriter doesn't implement some of the optionals (which can happen in our servers). I believe the wrapper logic works correctly regardless of which underlying interfaces are provided vs. used. Please check carefully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/194)
=> tsweb: use ResponseWriter wrapper to log better.

cmd/derper/derper.go, derp/derp_server.go
Related changes:
- Remove per-node rate limiter, rely entirely on kernel fair queuing+limiting for now.
- Fix server->client keepalives. Code used to send 1 keepalive and then stop.
- Packet drop counters broken down by drop reason.
Missing:
- New test that overloads queues & verifies receivers don't block. Working on that after zzz, but code is good for review meanwhile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/200)
=> derp: add one send queue per client, queue packets from receivers.

ipn/local.go
It was being called back into ultimately from magicsock before there
was a control client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/210)
=> ipn: call SetNetInfoCallback later, in Start

control/controlclient/direct.go
The DEBUG_INCLUDE_IPV6 environment variable is now an opt-out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/231)
=> control/controlclient: flip IPv6 to be on by default

control/controlclient/auto.go, control/controlclient/direct.go
This should never happen, so log when it does so we can fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/241)
=> controlclient: do not send duplicate hostinfo/netinfo

cmd/microproxy/microproxy.go, tsweb/tsweb.go, tsweb/tsweb_test.go
The name's been bugging me for a long time.
I liked neither the overlap between tsweb.Handler and http.Handler,
nor the name "ServeHTTPErr" which sounds like it's an error being
returned, like it's an error handler and not sometimes a happy path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/258)
=> tsweb: rename Handler to ReturnHandler

logtail/logtail.go
Just useless bytes on the wire. Especially with HTTP/1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/257)
=> logtail: don't send a User-Agent

tstime/tstime.go, tstime/tstime_test.go
Go's time.Parse always allocates a FixedZone. This avoids that allocation,
at the cost of adding a cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/260)
=> tstime: add new package for time utilities, starting with Parse3339

tstime/tstime.go, tstime/tstime_test.go
It doesn't allocate and it's half the time of time.Parse (which
allocates), and 2/3rds the time of time.ParseInLocation (which
doesn't).
Go with a UTC time:
```
BenchmarkGoParse3339/Z-8                 2200995               534 ns/op               0 B/op          0 allocs/op
BenchmarkGoParse3339/Z-8                 2254816               554 ns/op               0 B/op          0 allocs/op
BenchmarkGoParse3339/Z-8                 2159504               522 ns/op               0 B/op          0 allocs/op
```
Go allocates with a "-08:00" suffix instead of ending in "Z":
```
BenchmarkGoParse3339/TZ-8                1276491               884 ns/op             144 B/op          3 allocs/op
BenchmarkGoParse3339/TZ-8                1355858               942 ns/op             144 B/op          3 …
```
=> tstime: write Parse3339 parse that doesn't use time.Parse

wgengine/magicsock/magicsock.go
While skimming the magicsock code, I noticed a tiny doc issue and figured I'd send a fix. The docs on `magicsock.Conn` currently state that they implement the `wireguard/device.Bind` interface, yet this type does not exist. It appears that the `Conn` type actually implements the [`wireguard/conn.Bind`](https://pkg.go.dev/github.com/tailscale/wireguard-go@v0.0.0-20200325185614-bd634ffe2ded/conn?tab=doc#Bind) interface, so I tweaked the docs to reflect this.
I also fixed a small typo in the same file. :v:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/266)
=> wgengine/magicsock: fix Conn docs type reference

derp/derp_server.go
`unregisterClient()` isn't called if `sendServerInfo()` fails in `accept()`. Fixed this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/262)
=> derp/derp_server: fixed unbalanced {register,unregister}Client() calls.

wgengine/userspace.go
This was only done occasionally, but was extremely disruptive
when done and is no longer necessary.
It used to be that when switching links, we had to immediately
generate handshakes to everyone we were communicating with to
punch a hole in any NAT we were talking through. (This ended up
not really working, because in the process we got rid of our
session keys and ended up having a futile conversation for many
seconds.)
Now we have DERP, our link change propogates to the other side
as a new list of endpoints, so they start spraying packets.
We will definitely get one thanks to DERP, which will cause us
to spray, opening any NAT we are behind.
The result is that for good connections, we don't trash session
keys and cause an interruption.
Signed-off-by: David Crawshaw …
=> wgengine: remove IpcSetOperation on LinkChange

derp/derp_server.go
When unregistering a replaced client connection, move the
still-connected peers over to the current client connection. Inform
the peers that we've gone only when unregistering the active
client connection.
Signed-off-by: Dmitry Adamushko <da@stablebits.net>
P.S. Not tested locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/263)
=> derp/derp_server: unregisterClient() for replaced client connections.

derp/derp.go
Comments already suggest that it should do this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/271)
=> derp: prevent readFrame() from reading more than len(b) bytes

tstime/tstime.go, tstime/tstime_test.go
tstime: hand-implement parseInt for specific needs of rfc3339 parsing.
Makes parsing 4.6x faster.
```
name         old time/op  new time/op  delta
ParseInt-12  32.1ns ± 1%   6.9ns ± 2%  -78.55%  (p=0.000 n=10+9)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/298)
=> tstime: hand-implement parseInt for specific needs of rfc3339 parsing.

wgengine/monitor/monitor_linux.go, wgengine/monitor/monitor_unsupported.go
Netlink is not supported on Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/321)
=> wgengine/monitor: disable monitor on Android

net/dnscache/dnscache.go
Just like on iOS, there is no local resolver on Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/331)
=> net/dnscache: don't use the Go resolver on Android

wgengine/ifconfig_windows.go
OLE calls sometimes unexpectedly fail, but retries can succeed. Instead of calls to panic(), return errors. This way ConfigureInterface() retries can succeed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/90)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171687648683959) by [Unito](https://www.unito.io/learn-more)
=> Error handling after OLE calls

cmd/tailscaled/tailscaled.go, ipn/e2e_test.go, scripts/check_license_headers.sh, wgengine/router/ifconfig_windows.go, wgengine/router/router.go, wgengine/router/router_darwin.go, wgengine/router/router_darwin_support.go, wgengine/router/router_default.go, wgengine/router/router_fake.go, wgengine/router/router_freebsd.go, wgengine/router/router_linux.go, wgengine/router/router_openbsd.go, wgengine/router/router_windows.go, wgengine/userspace.go, wgengine/watchdog_test.go, wgengine/wgengine.go
The router implementations are logically separate, with their own API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/342)
=> wgengine/router: split out from wgengine.

go.mod, go.sum
No tidy, because it doesn't work for me:
$ go mod tidy
go: finding module for package tailscale.io/control
go: finding module for package tailscale.io/control/cfgdb
tailscale.com/control/controlclient tested by
tailscale.com/control/controlclient.test imports
tailscale.io/control: cannot find module providing package tailscale.io/control: unrecognized import path "tailscale.io/control": parse https://tailscale.io/control?go-get=1: no go-import meta tags (meta tag tailscale.com did not match import path tailscale.io/control)
tailscale.com/control/controlclient tested by
tailscale.com/control/controlclient.test imports
tailscale.io/control/cfgdb: cannot find module providing package tailscale.io/control/cfgdb: unrecognized import path "tailscale.io/control/cfgdb": parse …
=> go.mod,go.sum: bump golang.org/x/sys for the Android dup2 fix

cmd/mkpkg/main.go
This eventually fixes #341, pending update to the packaging script.
As suggested in [this comment](https://github.com/tailscale/tailscale/issues/341#issuecomment-622064118), it turns out that adding an empty directory at `/var/cache/tailscale` to the `%files` section of the rpm package fixes the issue (tested on a clean CentOS 8.1.1911 VM).
Since this may be useful for other directories in the future, this patch implements a generic way of adding empty directories to a package. In particular, it works for an empty list of empty directories, which is the default. This is not the case for `--files` and `--configs`, which always expect a nonempty list as an argument; hence the special treatment of `""` in `parseEmptyDirs`.
=> cmd/mkpkg: support adding empty directories.

control/controlclient/auto_test.go
I believe this is the issue behind the most recent test flake. The second half of the hostinfo test lacked synchronization, so it was possible to see `peer.Hostinfo.OS` with its old value (`macOS`) instead of `iOS` as expected. The error message message arising from this, `peer hostinfo does not have OS`, was eminently confusing, so I changed it as well.
=> control/controlclient: synchronize hostinfo test.

control/controlclient/auto_test.go
I apologize: in tailscale/tailscale#352, I wrongly assumed that simply running `go test ./...` in this repo is enough to ensure that tests pass. In fact, this is wrong (I believe due to `auto_test.go` having `// +build depends_on_currently_unreleased`), and the newly added synchronization actually breaks the previously flaky test reliably.
This does not quite revert that PR, as I think that the improved error logging is still helpful. However, this line does need to be reverted to prevent an impending test breakage. I will investigate the issue further, this time running the tests properly.
=> control/controlclient: revert extreneous synchronization.

wgengine/router/ifconfig_windows.go, wgengine/router/router.go, wgengine/router/router_darwin.go, wgengine/router/router_darwin_support.go, wgengine/router/router_fake.go, wgengine/router/router_freebsd.go, wgengine/router/router_linux.go, wgengine/router/router_openbsd.go, wgengine/router/router_windows.go, wgengine/userspace.go
Instead, pass in only exactly the relevant configuration pieces
that the OS network stack cares about.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/361)
=> wgengine/router: remove wireguard-go config from settings.

go.mod, go.sum, wgengine/router/ifconfig_windows.go, wgengine/router/router.go, wgengine/router/router_freebsd.go, wgengine/router/router_linux.go, wgengine/router/router_openbsd.go, wgengine/userspace.go
For your consideration. I'm neutral on this change, but I'm thinking of moving router out to be a sibling, rather than a child, of wgengine, with glue logic in the ipn package. With that in mind, it makes some sense to cut out wireguard-go entirely from this package. WDYT?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/362)
=> wgengine/router: use inet.af/netaddr, not wgcfg.CIDR.

cmd/tailscaled/tailscaled.go, ipn/e2e_test.go, ipn/ipnserver/server_test.go, types/logger/logger.go, types/logger/logger_test.go
Addresses issue #317, where logs can get spammed with the same message
nonstop. Created a rate limiting closure on logging functions, which
limits the number of messages being logged per second based on format
string.
Signed-off-by: Wendi Yu <wendi@tailscale.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/356)
=> Implement rate limiting on log messages

portlist/portlist.go, portlist/portlist_linux.go
staticcheck (called by `redo pr`) used to fail on macOS (and presumably 
windows) due to a variable declared in a common package that was only used
by the Linux build, which would prevent `redo pr` from passing on Mac. 
Moved variable declaration from the common file to the Linux-specific one 
to resolve the compiler complaint.
Signed-off-by: Wendi Yu <wendi.yu@yahoo.ca>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/364)
=> Fix macOS build

ipn/local.go, wgengine/router/ifconfig_windows.go, wgengine/router/router.go, wgengine/router/router_darwin.go, wgengine/router/router_darwin_support.go, wgengine/router/router_fake.go, wgengine/router/router_freebsd.go, wgengine/router/router_linux.go, wgengine/router/router_openbsd.go, wgengine/router/router_windows.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
This saves a layer of translation, and saves us having to
pass in extra bits and pieces of the netmap and prefs to
wgengine. Now it gets one Wireguard config, and one OS
network stack config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/373)
=> wgengine: generate and plumb router.Settings in from ipn.

wgengine/tstun/tun.go, wgengine/userspace.go
Unfortunately, in my tstun patch I overlooked that `router_windows.go` asserts that the `tun.Device` it receives is a `tun.(*NativeDevice)`. I hoped to avoid providing `Unwrap()`, but it seems like the best solution. If I change the interface of `newUserspaceEngineAdvanced` back to receiving a `tun.Device` and wrapping it inside, then callers cannot get at the wrapped TUN without `userspaceEngine` exposing it. I'm not sure that that would be cleaner.
I have verified that both native and fake modes start without issues on Linux and Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/390)
=> wgengine: pass tun.NativeDevice to router

cmd/tailscale/tailscale.go
This is a really trivial change that just exposes in the tailscale CLI a flag already present in prefs. As far as I know, this setting is togglable at least on Windows, so I presume we intend to support it. I named the CLI flag consistently with `--no-snat`, even though the pref name is different. Renaming the pref would have to work around existing clients, I imagine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/385)
=> cmd/tailscale: expose --enable-derp

net/netcheck/netcheck.go, net/netns/netns.go, wgengine/magicsock/magicsock.go
net/netns: add package for start of network namespace support
And plumb in netcheck STUN packets.
TODO: derphttp, logs, control.
Updates #144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/422)
=> net/netns: add package for start of network namespace support

derp/derphttp/derphttp_test.go, net/netcheck/netcheck_test.go, net/netns/netns.go, net/netns/netns_default.go, net/netns/netns_linux.go, wgengine/magicsock/magicsock_test.go, wgengine/router/router_linux.go, wgengine/watchdog_test.go
This allows tailscaled's own traffic to bypass Tailscale-managed routes,
so that things like tailscale-provided default routes don't break
tailscaled itself.
Fixes #144.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/423)
=> net/netns: set the bypass socket mark on linux.

control/controlclient/direct.go, derp/derphttp/derphttp_client.go, logpolicy/logpolicy.go, net/netns/netns.go, net/netns/socks.go
This lets control & logs also use SOCKS dials.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/427)
=> net/netns: move SOCKS dialing to netns for now

wgengine/filter/filter.go, wgengine/filter/filter_test.go
Right now, `q` from `tstun` escapes to the heap, as reported by
```sh
go install --gcflags=tailscale.com/wgengine/...=-m ./wgengine/tstun
```
Namely, we have
```
wgengine/tstun/tun.go:179:6: moved to heap: q
```
in
```go
179	var q packet.QDecode
180	if filt.RunOut(buf, &q, t.filterFlags) == filter.Accept {
```
and
```
wgengine/tstun/tun.go:221:6: moved to heap: q
```
in
```go
221	var q packet.QDecode
222	if filt.RunIn(buf, &q, t.filterFlags) == filter.Accept {
```
In turns out that this is because `q` is directly passed to `logf` in one case, and `logf` is an interface, so escape is inevitable. This slight reordering fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/ta …
=> filter: prevent escape of QDecode to the heap

ipn/local.go, ipn/prefs.go, ipn/prefs_test.go
Overriding the hostname is required for Android, where os.Hostname
is often just "localhost".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/429)
=> ipn: add Hostname override to Options

wgengine/router/router_linux.go, wgengine/router/router_linux_test.go
We have a filter in tailscaled itself now, which is more robust
against weird network topologies (such as the one Docker creates).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/433)
=> wgengine/router: don't filter subnet routing in netfilter.

cmd/derper/derper.go, cmd/derper/derper_test.go, derp/derp.go, derp/derp_client.go, derp/derp_server.go, derp/derp_test.go, derp/derphttp/derphttp_client.go
This lets a trusted DERP client that knows a pre-shared key subscribe
to the connection list. Upon subscribing, they get the current set
of connected public keys, and then all changes over time.
This lets a set of DERP server peers within a region all stay connected to
each other and know which clients are connected to which nodes.
Updates #388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/430)
=> derp, cmd/derper: add frameWatchConns, framePeerPresent for inter-DERP routing

wgengine/router/router_linux.go, wgengine/router/runner.go
iproute2 3.16.0-2 from Debian Jessie (oldoldstable) doesn't return
exit code 2 when deleting a non-existent IP rule.
Fixes #434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/435)
=> wgengine/router: also accept exit code 254 from `ip rule del`.

go.mod
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/438)
=> go.mod: require Go 1.14, since we use some of its features.

wgengine/userspace.go
macOS incorrectly sends packets for the local Tailscale IP
into our tunnel interface. We have to turn the packets around
and send them back to the kernel.
Fixes tailscale/corp#189.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/450)
=> wgengine: loop back tuntap packets destined for local IPs.

control/controlclient/direct.go, ipn/local.go, types/logger/logger.go, types/logger/logger_test.go
Besides making more sense, this also eliminates a data race wherein `controlclient.New` and `readPoller` would concurrently access `Hostinfo`, the former without any synchronization. This, together with tailscale/wireguard-go#16, should allow us to enable the `ipn` race test again (resolving tailscale/corp#255).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/456)
=> ipn: refactor (*LocalBackend).Start and move port polling into it.

wgengine/router/router_darwin.go, wgengine/router/router_freebsd.go, wgengine/router/router_userspace_bsd.go
Darwin and FreeBSD are compatible enough to share the userspace router.
The OSX router delegates to the BSD userspace router unless `SetRoutesFunc` is set.
That preserves the mechanism that allows `ipn-go-bridge` to specify its own routing behavior.
Fixes #177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/461)
=> wgengine: add BSD userspace router to darwin

wgengine/router/router_darwin.go
The NetworkExtension brings up the interface itself and does not have
access to `ifconfig`, which the underlying BSD userspace router attempts
to use when Up is called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/512)
=> wgengine/router: do not call ifconfig up if SetRoutesFunc is set

wgengine/userspace.go, wgengine/watchdog_test.go
This gets `userspaceEngine.Close` to close components in reverse order of bringup, which eliminates a deadlock that occasionally surfaces under the race detector. Also, an unrelated log-after-exit issue is fixed in `watchdog_test` by closing the engine before leaving.
This may seem like merely "masking the problem", but relying on the Wireguard device being around at Close time seems reasonable. In fact, this fix has to be done anyway for graceful shutdown (it is included in #514), since the router already doesn't like the interface disappearing from underneath it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/520)
=> wgengine: eliminate deadlock in Close

version/describe.txt.do
So it doesn't vary based on who's doing the release with which version
of git.
Fixes tailscale/corp#419
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/522)
=> version: explicitly use 9 hex digits in git describe version number

go.mod, wgengine/monitor/monitor.go, wgengine/monitor/monitor_freebsd.go, wgengine/monitor/monitor_linux.go, wgengine/monitor/monitor_unsupported.go
Fixes tailscale/corp#412 ("flood of link change events at start-up")
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/528)
=> wgengine/monitor: parse Linux netlink messages, ignore our own events

version/mkversion.sh, version/mkversion_test.go
Our primary version format is git describe --long --abbrev=9.
Our Apple scheme is:
(major+100).minor.(patch*10,000+gitDescribeCommits).
This CL gets rid of the third, which was:
major.minor.(patch*10,000+gitDescribeCommits).
Now the "About" box in the macOS app shows the same version that we
show on pkgs.tailscale.com, userz, changelog, etc.
This will be more important once/if we get standalone DMG downloads
for macOS on pkgs.tailscale.com.
Fixes tailscale/corp#364
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/533)
=> version: don't have a third version number form for xcode

tstest/natlab/firewall.go, tstest/natlab/natlab_test.go
Was mucking about with NATs, but this is a nicely separable thing we may want (and it let me experiment with the API shape; we need a similar one for NAT mapping selectivity, which is how I ended up in this rabbit hole).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/546)
=> tstest/natlab: support different firewall selectivities.

ipn/backend.go, ipn/fake_test.go, ipn/handle.go, ipn/local.go, ipn/message.go, ipn/message_test.go
The StartLoginInteractive command is for delegating the sign-in flow
to a browser. The Android Gooogle Sign-In SDK inverts the flow by
giving the client ID tokens.
Add a new backend command for accepting such tokens by exposing the existing
controlclient.Client.Login support for OAuth2 tokens. Introduce a custom
TokenType to distinguish ID tokens from other OAuth2 tokens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/550)
=> ipn: add Login backend command for sign-in with token

wgengine/monitor/monitor.go, wgengine/monitor/monitor_freebsd.go, wgengine/monitor/monitor_linux.go, wgengine/router/dns.go, wgengine/router/dns_resolved.go
Fixing a few static check errors that popped up on Mac (due to things that are only built on Linux), namely: 
```
oss/wgengine/monitor/monitor.go:26:6: type unspecifiedMessage is unused (U1000)
oss/wgengine/router/dns.go:54:7: const dnsReconfigTimeout is unused (U1000)
```
I just moved a few things to be declared in the files built on Linux, but let me know if you'd want to organize it differently :)
Signed-off-by: Wendi Yu <wendi@tailscale.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/557)
=> wgengine: fix macos staticcheck errors

tstest/natlab/firewall.go, tstest/natlab/nat.go, tstest/natlab/natlab.go, tstest/natlab/natlab_test.go, wgengine/magicsock/magicsock_test.go
The new interface lets implementors more precisely distinguish
local traffic from forwarded traffic, and applies different
forwarding logic within Machines for each type. This allows
Machines to be packet forwarders, which didn't quite work
with the implementation of Inject.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/556)
=> tstest/natlab: refactor PacketHandler into a larger interface.

cmd/tailscale/cli/up.go
Following discussion with @apenwarr, this appears to be a common customer request and easy to implement. 
One considerations: should we also normalize existing hostnames / newly acquired ones from `os.Hostname` to satisfy `validateHostname`? This seems like a useful invariant, since such names can be used in a domain name without additional sanitization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/560)
=> cmd/tailscale: allow overriding hostname in tailscale up

wgengine/router/dns_networkmanager.go
Nameserver IP 10.11.12.13 would otherwise get written to resolv.conf as 13.12.11.10, as was happening on my client.
Signed-off-by: Eduardo Kienetz <eduardo@kienetz.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/568)
=> Use LittleEndian for correct byte order on DNS IPs

wgengine/router/dns_networkmanager.go, wgengine/router/dns_resolved.go
While debugging the endianness issue, I discovered:
1. That I had been holding `godbus` wrong and that I shouldn't close connections, since they will are shared and get reused on subsequent invocations.
2. That there is a better way of changing connection settings (with compare-and-set semantics on the version value). This way also doesn't litter the disk with old configs. `dns-priority` logic is changed to accommodate it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/569)
=> wgengine/router: use better NetworkManager API

wgengine/router/router_linux.go, wgengine/router/router_linux_test.go
We originally picked those numbers somewhat at random, but with the idea
that 8 is a traditionally lucky number in Chinese culture. Unfortunately,
"88" is also neo-nazi shorthand language.
Use 52 instead, because those are the digits above the letters
"TS" (tailscale) on a qwerty keyboard, so we're unlikely to collide with
other users. 5, 2 and 52 are also pleasantly culturally meaningless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/584)
=> wgengine/router: don't use 88 or 8888 as table/rule numbers.

cmd/tailscale/cli/up.go
As it turned out in #589, this is currently missing.
I'm not sure that `--corp-dns` is the best name for it, given that it is more of a toggle for _all_ DNS settings and not just corporate DNS servers specifically, which will become a useful distinction soon, but that's what it is in prefs and on other platforms, so it seems reasonable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/593)
=> cmd/tailscale: add corpDNS flag

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/tstun/tun.go, wgengine/userspace.go
wireguard-go uses 3 goroutines per peer (with reasonably large stacks
& buffers).
Rather than tell wireguard-go about all our peers, only tell it about
peers we're actively communicating with. That means we need hooks into
magicsock's packet receiving path and tstun's packet sending path to
lazily create a wireguard peer on demand from the network map.
This frees up lots of memory for iOS (where we have almost nothing
left for larger domains with many users).
We should ideally do this in wireguard-go itself one day, but that'd
be a pretty big change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/596)
=> wgengine: configure wireguard peers lazily, as needed

wgengine/filter/filter.go, wgengine/packet/ip.go, wgengine/packet/packet.go, wgengine/packet/packet_test.go
As prep for IPv6 log spam fixes in a future change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/612)
=> wgengine/packet: add IPVersion field, don't use IPProto to note version

cmd/tailscaled/tailscaled.go, ipn/ipnserver/server.go, ipn/ipnserver/server_test.go
So a backend in server-an-error state (as used by Windows) can try to
create a new Engine again each time somebody re-connects, relaunching
the GUI app.
This is a hacky temporary workaround while we fix Windows issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/614)
=> ipn/ipnserver: add a GetEngine "try again" hook

cmd/tailscaled/tailscaled.service
It appears that systemd has sensible defaults for limiting
crash loops:
DefaultStartLimitIntervalSec=10s
DefaultStartLimitBurst=5
Remove our insta-restart configuration so that it works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/626)
=> tailscaled.service: use default restart limiting

cmd/tailscaled/tailscaled.go, ipn/local.go
Fixes a race condition where the packet filter may reject all traffic
to a device's Tailscale IP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/630)
=> ipn: fix incorrect handling of packet filter changes

control/controlclient/direct.go, control/controlclient/direct_test.go, tailcfg/tailcfg.go
Should greatly reduce bandwidth for large networks (including our
hello.ipn.dev node).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/658)
=> tailcfg, control/controlclient: support delta-encoded netmaps

cmd/tailscale/cli/cli.go, cmd/tailscale/cli/ping.go, ipn/backend.go, ipn/fake_test.go, ipn/ipnstate/ipnstate.go, ipn/local.go, ipn/message.go, wgengine/magicsock/magicsock.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
For example:
```
$ tailscale ping -h
USAGE
ping <hostname-or-IP>
FLAGS
-c 10                   max number of pings to send
-stop-once-direct true  stop once a direct path is established
-verbose false          verbose output
$ tailscale ping mon.ts.tailscale.com
pong from monitoring (100.88.178.64) via DERP(sfo) in 65ms
pong from monitoring (100.88.178.64) via DERP(sfo) in 252ms
pong from monitoring (100.88.178.64) via [2604:a880:2:d1::36:d001]:41641 in 33ms
```
Fixes #661
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/663)
=> cmd/tailscale/cli: add ping subcommand

wgengine/magicsock/magicsock.go
Consider:
Hard NAT (A) <---> Hard NAT w/ mapped port (B)
If A sends a packet to B's mapped port, A can disco ping B directly,
with low latency, without DERP.
But B couldn't establish a path back to A and needed to use DERP,
despite already logging about A's endpoint and adding a mapping to it
for other purposes (the wireguard conn.Endpoint lookup also needed
it).
This adds the tracking to discoEndpoint too so it'll be used for
finding a path back.
Fixes tailscale/corp#556
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/681)
=> wgengine/magicsock: use disco ping src as a candidate endpoint

derp/derpmap/derpmap.go, tailcfg/derpmap.go
We're beginning to reference DERP region names in the admin UI, so it's best to consolidate this information in our DERP map.
There are a few other references to `tailcfg.DERPRegion` unchanged by this PR (netcheck_test.go, stuntest.go, magicsock_test.go), but since this new field isn't relied on anywhere, it seems fine to leave as an empty string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/686)
=> derpmap: add full region name

wgengine/tsdns/forwarder.go, wgengine/tsdns/tsdns.go, wgengine/tsdns/tsdns_test.go, wgengine/userspace.go
As per earlier discussion (synchronous delegation is too slow and its queue is too shallow). The two commits implement different approaches; I much prefer the second one, but it makes a certain assumption.
- first commit (d66d600) implements the "goroutine per request" approach. This uses more memory than necessary and has tricky synchronization.
- second commit (08775a7) changes this to a map keyed on DNS Transaction ID and a (spcket, 2 goroutines) per nameserver, which is leaner and more elegant. The downside is that this assumes Transaction IDs don't collide in a short enough period of time, which is questionable, as normally distinctness of ports makes makes it less relevant. A way to mitigate this this would be to have more sockets per nameserver and additionally key on the socket …
=> tsdns: delegate asynchronously

cmd/derper/derper.go, derp/derp.go, derp/derp_client.go, derp/derp_server.go, derp/derp_test.go, derp/derphttp/derphttp_client.go, derp/derphttp/derphttp_server.go
```
* advertise server's DERP public key following ServerHello
* have client look for that DEPR public key in the response
PeerCertificates
* let client advertise it's going into a "fast start" mode
if it finds it
* modify server to support that fast start mode, just not
sending the HTTP response header
Cuts down another round trip, bringing the latency of being able to
write our first DERP frame from SF to Bangalore from ~725ms
(3 RTT) to ~481ms (2 RTT: TCP and TLS).
```
Fixes #693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/695)
=> derp: advertise server public key following ServerHello

ipn/local.go, tailcfg/tailcfg.go, wgengine/router/dns/config.go, wgengine/tsdns/map.go, wgengine/tsdns/map_test.go, wgengine/tsdns/tsdns.go, wgengine/tsdns/tsdns_test.go, wgengine/userspace.go
This is important for future extensibility: client code should not hard-code the root domains.
An alternative to this would involve sending domains down from control, but this seems simpler, even if the resultant list is longer (usually `[]{"$workgroup.beta.tailscale.net.", "tailscale.com.beta.tailscale.net."}` instead of just `[]{"beta.tailscale.net."}`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/708)
=> tailcfg, tsdns: derive root domains from list of nodes

ipn/local.go, ipn/loglines_test.go, tstest/log.go, tstest/log_test.go
Tags lines that our logs grinding needs with `[GRINDER STATS LINE]` and tests to make sure that they get logged.
I don't think these lines specifically get logged in the fake versions of things that we use in our existing tests, so the tests I added just check that the functions that are supposed to log do in fact log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/711)
=> ipn: tag and test for grinder log lines 

cmd/tailscale/cli/up.go
Add a new flag `--force-reauth` to `tailscale up`. It can start the login process even the user is already logged in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/717)
=> cmd/tailscale/cli: add new flag --force-reauth to up subcommand

wgengine/router/ifconfig_windows.go, wgengine/router/ifconfig_windows_test.go
Updates #725 (I'd say "Fixes", but we plan to fix it in a number of ways)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/727)
=> wgengine/router: fix Windows route sorting that caused de-dup to not work

portlist/netstat.go, portlist/portlist_macos.go
Running tailscaled on my machine yields lots of entries like:
weird: missing {tcp 6060}
parsePortsNetstat is filtering out loopback addresses as uninteresting.
Then addProcesses is surprised to discover these listening ports,
which results in spurious logging.
Teach addProcesses to also ignore loopback addresses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/733)
=> portlist: reduce log spam on macOS

cmd/cloner/cloner.go
If you change a struct and don't re-run cloner,
your Cloner method might be inaccurate, leading to bad things.
To prevent this, write out the struct as it is at the moment that
cloner is caller, and attempt a conversion from that type.
If the struct gets changed in any way, this conversion will fail.
This will yield false positives: If you change a non-pointer field,
you will be forced to re-run cloner, even though the actual generated
code won't change. I think this is an acceptable cost: It is a minor
annoyance, which will prevent real bugs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/737)
=> cmd/cloner: ensure cloner gets re-run when structs change

log/logheap/logheap.go
LogHeap no longer logs to os.Stderr and instead uploads
the heap profile by means of an HTTP POST request to the
target URL endpoint.
While here, also ensured that an error from pprof.WriteHeapProfile
isn't ignored and will prevent the HTTP request from being made
if non-nil.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/741)
=> log/logheap: properly document LogHeap as performing HTTP upload

wgengine/router/ifconfig_windows.go
So it doesn't false positive if misused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/758)
=> wgengine/router: tighten isMissingIPv6Err

wgengine/router/router_linux.go
`6.4M/24.1M router: route del failed: running “ip route del 100.100.100.100/32 dev tailscale0 table 52” failed: exit status 2` 
`ip addr del` is called before `ip route del` leading to error above. Switching order of `cidrDiff("addr")` and `cidrDiff("route")` to avoid error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/756)
=> wgengine/router/router_linux.go: fixed " route del failed" error 

cmd/derper/derper.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/764)
=> cmd/derper: add missing html.EscapeString calls in /debug page

wgengine/magicsock/magicsock.go
Changed error message from "no discovery key for peer (pre 0.100?)" to "no discovery key for peer (old Tailscale version?)"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/746)
=> Updating error msg for no discovery key for peer

tsweb/jsonhandler.go, tsweb/jsonhandler_test.go
This way something is capable of logging errors on the server.
Fixes #766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/767)
=> tsweb: make JSONHandlerFunc implement ReturnHandler, not http.Handler

control/controlclient/direct.go, tailcfg/tailcfg.go
DebugForceDisco was a development & safety knob during the the transition
to discovery. It's no longer needed.
Add MapRequest.ReadOnly to prevent clients needing to do two
peer-spamming MapRequest at start-up.
This only adds the field, not the use of the field. (The control server
needs to support it first.)
Updates tailscale/corp#557
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/769)
=> tailcfg: add MapRequest.ReadOnly and OmitPeers; remove DebugForceDisco

util/uniq/slice.go, util/uniq/slice_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/802)
=> util/uniq: add new package

control/controlclient/direct.go, ipn/local.go, tailcfg/tailcfg.go
Also replaces the IPv6Overlay bool with use of DebugFlags, since
it's currently an experimental configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tailscale/tailscale/837)
=> tailcfg: add a DebugFlags field for experiments and debugging.

ipn/local.go
Without this change, newly installed Android clients crash on startup
with
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9881b9f8]
goroutine 29 [running]:
tailscale.com/ipn.(*LocalBackend).initMachineKeyLocked.func1(0x50cb1b9c, 0x503c9a00)
/home/elias/proj/tailscale/ipn/local.go:711 +0x2c
tailscale.com/ipn.(*LocalBackend).initMachineKeyLocked(0x503c9a00, 0x0, 0x0)
/home/elias/proj/tailscale/ipn/local.go:736 +0x728
tailscale.com/ipn.(*LocalBackend).loadStateLocked(0x503c9a00, 0x988be40e, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/elias/proj/tailscale/ipn/local.go:817 +0x1e8
tailscale.com/ipn.(*LocalBackend).Start(0x503c9a00, 0x0, 0x0, 0x988be40e, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, ...) …
=> ipn: don't temporarilySetMachineKeyInPersist for Android clients

version/version.sh
git worktrees have a .git file rather than a .git directory, so building
in a worktree caused version.sh to generate an error.
=> version: relax git detection logic

control/controlclient/filter.go, control/controlclient/netmap.go, ipn/local.go, wgengine/filter/filter.go, wgengine/filter/filter_test.go, wgengine/filter/match.go, wgengine/filter/match4.go, wgengine/filter/tailcfg.go, wgengine/magicsock/magicsock_test.go, wgengine/tstun/tun_test.go
We still use the packet.* alloc-free types in the data path, but
the compilation from netaddr to packet happens within the filter
package.
=> wgengine/filter: use netaddr types in public API.

go.sum, tsweb/jsonhandler.go, tsweb/jsonhandler_test.go
This PR refactors JSONHandler to handle errors more intuitively. If the handler function returns an error and it can be asserted to be of type tsweb.HTTPError, use the status code on that error type, rather than the status returned by the handler function. This encourages the error to be handled only by the original implementator of the error.
=> tsweb: refactor JSONHandler to take status code from error if it is present

Dockerfile
As documented in the README, tailscale only build with the latest Go
version (Go 1.15).  As a result, a handful of undefined errors would pop
up using an older verison.
This patch updates the base image to 1.15, allowing "docker build"
to function correctly once more.
=> Patch Dockerfile to use valid Go version

wgengine/router/router_linux.go
=> wgengine/router: disable IPv6 if v6 policy routing is unavailable.

net/interfaces/interfaces_darwin.go, util/lineread/lineread.go
likelyHomeRouterIPDarwinSyscall iterates through the list of routes,
looking for a private gateway, returning the first one it finds.
likelyHomeRouterIPDarwinExec does the same thing,
except that it returns the last one it finds.
As a result, when there are multiple gateways,
TestLikelyHomeRouterIPSyscallExec fails.
(At least, I think that that is what is happening;
I am going inferring from observed behavior.)
This implementation is slightly wasteful:
It always reads all lines from netstat,
even when we know we don't need them.
That's a consequence of the util/lineread API.
It's not worth fixing now.
=> net/interfaces: make syscall and netstat agree when multiple gateways are present

util/jsonutil/types.go, util/jsonutil/unmarshal.go, util/jsonutil/unmarshal_test.go
This significantly cuts allocations for some alloc-hot corp code. That benchmark:
```
name      old time/op    new time/op    delta
TimeOf-8    2.12µs ± 1%    1.96µs ± 0%   -7.36%  (p=0.000 n=9+8)
name      old alloc/op   new alloc/op   delta
TimeOf-8      296B ± 0%       48B ± 0%  -83.78%  (p=0.000 n=10+10)
name      old allocs/op  new allocs/op  delta
TimeOf-8      6.00 ± 0%      1.00 ± 0%  -83.33%  (p=0.000 n=10+10)
```
=> util/jsonutil: new package

ipn/local.go, ipn/prefs.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go
Including ShieldsUp in HostInfo with the goal of eventually being able to port this information through to the admin panel.
=> tailcfg: include ShieldsUp in HostInfo

tailcfg/tailcfg.go
The cloner tool adds static checks that the Clone methods are up to
date, so failing to update Clone causes a compiler error.
=> tailcfg: remove outdated comments about Clone methods

ipn/prefs.go, ipn/prefs_test.go
It appears some users have corrupted pref.conf files. Have LoadPrefs
treat these files as non-existent. This way tailscale will make user
login, and not crash.
Fixes #954
Signed-off-by: Alex Brainman <alex.brainman@gmail.com>
=> ipn: make LoadPrefs return os.ErrNotExist when reading corrupted files

syncs/syncs.go
Fix receiver in order to be consistent
=> Fix receiver in order to be consistent: syncs.WaitGroupChan

version/version.sh
This is a repeat of commit 3aa68cd3978b880b451cd41ac4f4ee4ff5c4cb2f
which was lost in a rework of version.sh.
git worktrees have a .git file rather than a .git directory, so building
in a worktree caused version.sh to generate an error.
=> version: relax git detection logic (again)

.gitignore
These removed lines ignore built files that don't exist anymore, and just serve to clutter up the `.gitignore` file. (I was initially confused when I saw those lines, since I (correctly) thought that the only Tailscale binaries were `tailscale` and `tailscaled`):
- `taillogin` was removed in d052586
- `relaynode` was removed in a56e853
=> Remove unused .gitignore lines

go.mod
This is actually already required, this just updates `go.mod` with that fact. If you try and fail to build Tailscale with an outdated Go version, an error like this is printed, which should hopefully make building Tailscale easier:
```
note: module requires Go 1.15
```
=> Require at least Go 1.15 in go.mod

types/logger/logger.go, types/logger/logger_test.go
This caused some confusion in issue #460, since usually raw format strings aren't printed directly. Hopefully by directly logging that they are intended to be raw format strings, this will be more clear. Rate limited format strings now look like
```
[RATE LIMITED] format string "control: sendStatus: %s: %v"
```
Closes #460.
=> Clarify that raw format strings are intentional

wgengine/router/dns/manager_windows.go
On Win10, there's a hardcoded GUID and this works.
On Win7, this GUID changes and we need to ask the tun for its
LUID and convert that from the GUID.
This commit uses the computed GUID that is placed in InterfaceName.
Diagnosed by Jason Donnenfeld. (Thanks!)
=> wgengine/router/dns: use the correct interface GUID

wgengine/router/dns/manager_windows.go
The windows key timeout is longer than the wgengine watchdog timeout,
which means we never reach the timeout, instead the process exits.
Reduce the timeout so if we do hit it, at least the process continues.
=> wgengine/router/dns: reduce windows registry key open timeout

cmd/tailscaled/tailscaled.service
While not a full capability lockdown of the systemd unit, this still improves sandboxing and security of the running process a good deal.
I also tried to add `ProtectClock` (since I don’t see how or why Tailscale should/would ever need to alter the clock…), but for some reason, Tailscale refused to start up with that. (Which I should probably open its own, separate issue for.)
Related issue: https://github.com/tailscale/tailscale/issues/77 (though not fully the same)
=> tailscaled.service: Harden systemd unit somewhat

cmd/tailscale/cli/cli.go
Remove duplicate 'to connect' in error message.
Fixes #1068
=> Fix typo in cmd/tailscale/cli/cli.go

.envrc, .gitignore, shell.nix
This enables users of nix-shell and lorri to automagically have the correct development environment by simply changing directory into a checkout of this repo. For more information on this see the following links:
- https://christine.website/blog/how-i-start-nix-2020-03-08
- https://direnv.net/
- https://www.tweag.io/blog/2019-03-28-introducing-lorri/
=> add nix-shell boilerplate

control/controlclient/direct.go, ipn/local.go, tailcfg/tailcfg.go, wgengine/tsdns/map.go, wgengine/tsdns/tsdns.go, wgengine/tsdns/tsdns_test.go
Previously the client had heuristics to calculate which DNS search domains
to set, based on the peers' names. Unfortunately that prevented us from
doing some things we wanted to do server-side related to node sharing.
So, bump MapRequest.Version to 9 to signal that the client only uses the
explicitly configured DNS search domains and doesn't augment it with its own
list.
Updates tailscale/corp#1026
=> ipn: delete domainsForProxying, require explicit DNS search domains (mapver 9)

tailcfg/tailcfg.go
It's not used by recent clients, so even more reason to omit it.
=> tailcfg: add omitempty to FilterRule.SrcBits

cmd/tailscaled/tailscaled.service
Research in issue https://github.com/tailscale/tailscale/issues/1063 uncovered why tailscaled would fail with ProtectClock enabled (it implicitly enabled DevicePolicy=closed).
This knowledge in turn also opens the door for locking down /dev further, e.g. explicitly setting DevicePolicy=strict (instead of closed), and making /dev private for the unit.
=> tailscaled.service: Lock down clock and /dev

wgengine/tsdns/tsdns.go, wgengine/tsdns/tsdns_test.go
This appears to have been the intent of the previous code, but in practice, it only returned A records.
=> wgengine/tsdns: respond with any available addrs for ALL queries

ipn/loglines_test.go, tstest/log.go, types/logger/logger.go, wgengine/userspace.go
The wireguard-go rebase restored the original wireguard-go logging. That logging occurs late during device shutdown, in a separate goroutine. This late logging caused test failures in one of our logging tests.
This PR fixes it two different ways: By suppressing some of the wireguard-go logging, and by making the log test robust to delayed logging.
=> all: fix log test failures with -race after wireguard-go rebase

net/netcheck/netcheck.go, net/netcheck/netcheck_test.go
Users in Amsterdam (as one example) were flipping back and forth
between equidistant London & Frankfurt relays too much.
=> net/netcheck: improve the preferred DERP hysteresis

logtail/logtail_test.go, net/netcheck/netcheck_test.go, portlist/portlist_test.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
The changes in this PR address most of the cases of non-deterministic code coverage which caused lines of code to be alternately added and removed from coverage reports. It does so by expressly testing the functionality in question. After this PR there may be one function in DERP left which is non-deterministically covered, plus any more which we notice over time. I'd expect to address all such areas similarly, by adding specific tests.
=> Fix non-deterministic code coverage, part 1.

api.md
Added the following:
* A brief explanation of "domain".
* A brief explanations of "device" and how to find a "deviceID".
* Renamed "domain" to "tailnet"
* Sample API format for solo plans.
* `DELETE /device/:deviceID` documentation
=> API.md: rename "domain" to "tailnet" in documentation

wgengine/tsdns/tsdns.go, wgengine/tsdns/tsdns_test.go
This is what every other DNS resolver I could find does, so `tsdns` should do it as well. This also helps avoid weird error messages about records don't exist being unimplemented, and thus fixes #848.
notes:
- `go fmt` makes the indentation on lines 218/219 look wrong, but AFAIK there's no way to make `go fmt` handle it right.
- `go.sum` wasn't correctly regenerated after 14af6773324c95488f9f0a68704e637c7d642e70, but I didn't include the updated version in this PR to avoid merge conflicts.
=> Return NOERROR instead of NOTIMP for most records

types/logger/logger.go, types/logger/logger_test.go
Here's an example log line in the new format:
```
[RATE LIMITED] format string "open-conn-track: timeout opening %v; no associated peer node" (example: "open-conn-track: timeout opening ([ip] => [ip]); no associated peer node")
```
This should make debugging logging issues a bit easier, and give more context as to why something was rate limited. Including an example was first mentioned at https://github.com/tailscale/tailscale/issues/1110#issuecomment-759073284.
edit: updated example
=> Provide example when format string is rate limited

wgengine/router/dns/manager_windows.go
Commit 68ddf1 removed code that reads
`SOFTWARE\Tailscale IPN\SearchList` registry value. But the commit
left code that writes that value.
So now this package writes and never reads the value.
Remove the code to stop pointless work.
Updates #853
Signed-off-by: Alex Brainman <alex.brainman@gmail.com>
=> wgengine/router/dns: remove unused code

ipn/ipnserver/conn_linux.go, ipn/ipnserver/conn_no_ucred.go, ipn/ipnserver/server.go, ipn/message.go, ipn/message_test.go, safesocket/unixsocket.go
This partially reverts d6e9fb1df0fd6, which modified the permissions
on the tailscaled Unix socket and thus required "sudo tailscale" even
for "tailscale status".
Instead, open the permissions back up but have the server look at the
peer creds and only permit read-only actions unless you're root.
In the future we'll also have a group that can do mutable actions.
=> ipn, ipnserver: only require sudo on Linux for mutable CLI actions

ipn/local.go, net/packet/header.go, net/packet/ip.go, net/packet/packet.go, net/packet/packet_test.go, net/packet/tsmp.go, net/packet/tsmp_test.go, wgengine/filter/filter.go, wgengine/pendopen.go, wgengine/tstun/tun.go
This adds a new "TSMP" IP Protocol type (99) for sending inter-tailscale
messages over WireGuard, currently just for why a peer rejects TCP
SYNs (ACL rejection, shields up, nothing listening, something listening on that port but wrong interface, etc)
Updates #1094
=> net/packet, wgengine, tstun: communicate SYN failure reason between nodes

wgengine/magicsock/legacy.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
Previously, this benchmark relied on behavior of the legacy
receive codepath, which I changed in 22507adf. With this
change, the benchmark instead relies on the new active discovery
path.
=> wgengine/magicsock: fix BenchmarkReceiveFrom.

go.mod, wgengine/magicsock/legacy.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
22507adf5489a8293e03a5af06bd6af41d031468 stopped relying on
our fork of wireguard-go's UpdateDst callback.
As a result, we can unwind that code,
and the extra return value of ReceiveIPv{4,6}.
=> wgengine/magicsock: adapt to wireguard-go without UpdateDst

wgengine/magicsock/magicsock.go
```
name           old time/op  new time/op  delta
ReceiveFrom-4  21.8µs ± 2%  20.9µs ± 2%  -4.27%  (p=0.000 n=10+10)
```
Updates #414
=> wgengine/magicsock: add single element IPPort->endpoint cache in receive path

wgengine/magicsock/legacy.go
DstToString is used in two places in wireguard-go: Logging and uapi.
We are switching to use uapi for wireguard-go config.
To preserve existing behavior, we need the full set of addrs.
And for logging, having the full set of addrs seems useful.
(The Addrs method itself is slated for removal. When that happens,
the implementation will move to DstToString.)
=> wgengine/magicsock: make legacy DstToString match Addrs

control/controlclient/direct.go, tailcfg/tailcfg.go
This adds a more wire-efficient way of updating peers' Node.LastSeen times.
(Will add tests before submitting, assuming design is fine.)
=> tailcfg, control/controlclient: add mapver 10: MapResponse.PeerSeenChange

LICENSE
Should be equivalent to the license before, but compatible with the library Github uses to detect the license for the project's metadata: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license
~Also bumped the copyright year, can undo that.~
Feel free to close if this is not desirable. This way the project will get a nice "BSD-3-Clause License" instead of "View License" in the project sidebar, and the code will be discoverable by license in Github search.
=> LICENSE: Reformat for Github

wgengine/userspace.go
=> wgengine: don't leak TUN device in NewUserspaceEngine error path

types/logger/logger.go
We log lines like this:
```go
c.logf("[v1] magicsock: disco: %v->%v (%v, %v) sent %v", c.discoShort, dstDisco.ShortString(), dstKey.ShortString(), derpStr(dst.String()), disco.MessageSummary(m))
```
The leading [v1] causes it to get unintentionally rate limited.
Until we have a proper fix, work around it.
Fixes #1216
=> types/logger: fix rateFree interaction with verbosity prefixes

wgengine/router/router_linux.go
=> wgengine/router: ignore IPv6 errors on Linux when IPv6 is unavailable

cmd/tailscaled/tailscaled.service
It broke Debian Stretch. We'll try again later.
Updates #1245
=> cmd/tailscaled/tailscaled.service: revert recent hardening for now

net/interfaces/interfaces_darwin_cgo.go
The code was using a C "int", which is a signed 32-bit integer.
That means some valid IP addresses were negative numbers.
(In particular, the default router address handed out by AT&T
fiber: 192.168.1.254. No I don't know why they do that.)
A negative number is < 255, and so was treated by the Go code
as an error.
This fixes the unit test failure:
$ go test -v -run=TestLikelyHomeRouterIPSyscallExec ./net/interfaces
=== RUN   TestLikelyHomeRouterIPSyscallExec
interfaces_darwin_cgo_test.go:15: syscall() = invalid IP, false, netstat = 192.168.1.254, true
--- FAIL: TestLikelyHomeRouterIPSyscallExec (0.00s)
=> net/interfaces: use a uint32_t for ipv4 address

ipn/message_test.go, portlist/portlist_test.go, tstest/resource.go, wgengine/magicsock/magicsock_test.go, wgengine/tsdns/tsdns_test.go
Use tb.Cleanup to simplify both the API and the implementation.
One behavior change: When the number of goroutines shrinks, don't log.
I've never found these logs to be useful, and they frequently add noise.
=> tstest: simplify goroutine leak tests

logpolicy/logpolicy.go, logtail/logtail.go
This will enable the log server target to be chosen by end users to point to an arbitrary server. This is intended to be used with corporate/onprem deployments of Tailscale, and should NOT be used by end users unless you want to make getting support difficult.
=> Add an environment variable to enable customizing the log target

net/packet/tsmp.go, net/packet/tsmp_test.go, wgengine/pendopen.go
Unused for now, but I want to backport this commit to 1.4 so 1.6 can
start sending these and then at least 1.4 logs will stringify nicely.
=> net/packet: add some more TSMP packet reject reasons

net/stun/stuntest/stuntest.go, tstest/natlab/natlab.go
Upstream wireguard-go decided to use errors.Is(err, net.ErrClosed)
instead of checking the error string.
It also provided an unsafe linknamed version of net.ErrClosed
for clients running Go 1.15. Switch to that.
This reduces the time required for the wgengine/magicsock tests
on my machine from ~35s back to the ~13s it was before
456cf8a3765948d6f1992162993eaf3844371592.
=> tstest/natlab: use net.ErrClosed instead of a new error

cmd/tailscale/cli/status.go, ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go
=> cmd/tailscale/cli: display currently active exit node in `tailscale status`.

wgengine/userspace.go
This was in place because retrieved allowed_ips was very expensive.
Upstream changed the data structure to make them cheaper to compute.
This commit is an experiment to find out whether they're now cheap enough.
=> wgengine: remove IpcGetOperation filter

util/cibuild/cibuild.go, wgengine/magicsock/magicsock_test.go
I based my estimation of the required timeout based on locally
observed behavior. But CI machines are worse than my local machine.
16s was enough to reduce flakiness but not eliminate it. Bump it up again.
=> wgengine/magicsock: increase legacy ping timeout again

wgengine/magicsock/legacy.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
This is part cleanup and part optimization.
See each commit message for details.
The optimization won't really kick in until we pull in our upstream standard library optimization, but it doesn't do any harm in the meanwhile either.
Paired with @soniaappasamy.
=> wgengine/magicsock: simplify and remove an alloc on receive

wgengine/magicsock/magicsock.go
Only do the type assertion to *net.UDPAddr when addr is non-nil.
This prevents a bunch of log spam during tests.
=> wgengine/magicsock: reduce log spam during tests

net/interfaces/interfaces_default_route_test.go, net/netns/netns_test.go
I meant for these to be part of 52e24aa966ffa.
=> net/{interfaces,netns}: add some new tests, missed from prior commit

wgengine/tsdns/tsdns_server_test.go, wgengine/tsdns/tsdns_test.go
=> wgengine/tsdns: skip test that requires local IPv6 when IPv6 unavailable

net/tshttpproxy/tshttpproxy.go, net/tshttpproxy/tshttpproxy_test.go
This closes #1047.
```
magicsock: [0xc0004f00c0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): invalid response status from HTTP proxy http://azurediamond:hunter2@192.168.122.154:38274 on CONNECT to derp1.tailscale.com:443: 407 Proxy Authentication Required
derp-1: backoff: 7131 msec
```
=> net/tshttpproxy: support Basic auth

net/tshttpproxy/tshttpproxy.go, net/tshttpproxy/tshttpproxy_test.go
=> net/tshttpproxy: support HTTP proxy environment credentials on Windows too

wgengine/wglog/wglog.go
=> wgengine/wglog: drop 1/s "interface is up" messages.

ipn/ipnserver/server.go
Regression from code movement in d3efe8caf636aaa9a8e02b65877878954ea980b7
=> ipn/ipnserver: fix Windows connection auth regression

cmd/derper/bootstrap_dns.go, cmd/derper/derper.go
For option (d) of #1405.
For an HTTPS request of /bootstrap-dns, this returns e.g.:
```
{
"log.tailscale.io": [
"2600:1f14:436:d603:342:4c0d:2df9:191b",
"34.210.105.16"
],
"login.tailscale.com": [
"2a05:d014:386:203:f8b4:1d5a:f163:e187",
"3.121.18.47"
]
}
```
=> cmd/derper: add /bootstrap-dns handler

util/systemd/systemd_linux.go
Signed-off-by: Matt Layher <mdlayher@gmail.com>
New (and Open) are documented to return os.ErrNotExist when systemd Type=notify is not in use. This is just a bit simpler than the previous check.
=> util/systemd: explicitly check for os.ErrNotExist from sdnotify

wgengine/tsdns/tsdns.go, wgengine/tsdns/tsdns_test.go
Tor has a location-hidden service feature that enables users to host services from inside the Tor network. Each of these gets a unique DNS name that ends with .onion. As it stands now, if a misbehaving application somehow manages to make
a .onion DNS request to our DNS server, we will forward that to the DNS server, which could leak that to malicious third parties. See the [recent bug Brave had with this][1] for more context.
RFC 7686 suggests that name resolution APIs and libraries MUST respond with NXDOMAIN unless they can actually handle Tor lookups. We can't handle .onion lookups, so we reject them.
[1]: https://twitter.com/albinowax/status/1362737949872431108
=> wgengine/tsdns: explicitly reject .onion lookups

ipn/ipnserver/server.go, safesocket/safesocket.go, safesocket/unixsocket.go
FreeBSD wasn't able to run "tailscale up" since the recent peercred
refactoring.
=> safesocket, ipn/ipnserver: unify peercred info, fix bug on FreeBSD etc

wgengine/monitor/monitor.go, wgengine/monitor/monitor_darwin.go, wgengine/monitor/monitor_test.go
Turning my wifi on & off now in the new debug mode, I see the output below.
Notably, note the:
```
logger.go:33: monitor: coalesced 33 changes
...
logger.go:33: monitor: coalesced 18 changes
=== RUN   TestMonitorMode
logger.go:33: monitor: read 140 bytes, 1 messages (0 skipped)
logger.go:33: monitor: read 96 bytes, 1 messages (0 skipped)
logger.go:33: monitor: coalesced 2 changes
monitor_test.go:60: cb: changed=true, ifSt=interfaces.State{defaultRoute=en0 ifs={en0:[10.0.0.85/16 2602:d1:b4cf:c100:1438:63ab:fe13:8130/64 2602:d1:b4cf:c100:21a5:9f19:ea0a:9f0a/64] en1:[10.0.0.86/16 2602:d1:b4cf:c100:44f:9bf7:1c78:4a4b/64 2602:d1:b4cf:c100:4cb8:5e95:9425:93d9/64]} v4=true v6global=true}
logger.go:33: monitor: read 140 bytes, 1 messages (0 skipped)
logger.go:33: monitor: read 96 bytes, 1 …
```
=> wgengine/monitor: skip some macOS route updates, fix debounce regression

net/tshttpproxy/tshttpproxy_windows.go
We often see things in logs like:
```
2021-03-02 17:52:45.2456258 +0800 +0800: winhttp: Open: The parameter is incorrect.
2021-03-02 17:52:45.2506261 +0800 +0800: tshttpproxy: winhttp: GetProxyForURL("https://log.tailscale.io/c/tailnode.log.tailscale.io/5037bb42f4bc330e2d6143e191a7ff7e837c6be538139231de69a439536e0d68"): ERROR_INVALID_PARAMETER [unexpected]
```
I have a hunch that WinHTTP has thread-local state. If so, this would fix it.
If not, this is pretty harmless.
=> net/tshttpproxy: call winhttp calls from a fixed OS thread

wgengine/monitor/monitor.go, wgengine/monitor/monitor_test.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
Rather than do some last minute rearchitecting of link state on
Android, just restore the old Engine.LinkChange hook (so the Android
client doesn't need any changes), but change how it's implemented to
instead inject an event into the link monitor.
Fixes #1427
=> wgengine{,/monitor}: restore Engine.LinkChange, add Mon.InjectEvent

net/interfaces/interfaces.go, wgengine/magicsock/magicsock.go
Also change the type to netaddr.IP while here, because it made sorting
easier.
Updates tailscale/corp#1397
=> net/interfaces: sort returned addresses from LocalAddresses

portlist/portlist_linux.go, portlist/portlist_linux_test.go
This is important because some of those v6 sockets are actually
dual-stacked sockets, so this is our only chance of discovering
some services.
Fixes #1443.
=> portlist: collect IPv6 listening sockets on linux.

derp/derp.go, derp/derp_client.go, derp/derp_test.go, derp/derphttp/derphttp_client.go, wgengine/magicsock/magicsock.go
No server support yet, but we want Tailscale 1.6 clients to be able to respond
to them when the server can do it.
Updates #1310
=> wgengine/magicsock, derp, derp/derphttp: respond to DERP server->client pings

ipn/ipnlocal/local.go, net/packet/packet.go, wgengine/filter/filter.go, wgengine/filter/filter_test.go, wgengine/tstun/tun_test.go
=> wgengine/filter: only log packets to/from non-default routes.

wgengine/router/router_windows.go
wgengine/router: flushdns in windows when router config changes
Fixes: https://github.com/tailscale/tailscale/issues/1430
Signed-off-by: Aleksandar Pesic <peske.nis@gmail.com>
=> flushdns in windows when router config changes

control/controlclient/hostinfo_windows.go, control/controlclient/hostinfo_windows_test.go
control/controlclient: use API to get windows version number
Fixes: https://github.com/tailscale/tailscale/issues/1478
Signed-off-by: Aleksandar Pesic <peske.nis@gmail.com>
=> use API to get windows version number

cmd/tailscale/cli/status.go, cmd/tailscale/cli/up.go
This change makes it impossible to set your own IP address as the exit node for this system.
=> cmd/tailscale/cli: Fix #1489

cmd/tailscale/cli/up.go
instead of just lowercase "bsd"
=> cmd/tailscale/cli: include GOOS in BSD warning message

net/interfaces/interfaces.go
We strip them control-side anyway, and we already strip IPv4 link
local, so there's no point uploading them.  And iOS has a ton of them,
which results in somewhat silly amount of traffic in the MapRequest.
We'll be doing same-LAN-inter-tailscaled link-local traffic a
different way, with same-LAN discovery.
=> net/interfaces: skip IPv6 link-local interfaces like we do for IPv4

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
"public IP" is defined as an IP address configured on the exit node
itself that isn't in the list of forbidden ranges (RFC1918, CGNAT,
Tailscale).
Fixes #1522.
=> ipn/ipnlocal: allow client access to exit node's public IPs.

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
=> wgengine/magicsock: prefer IPv6 transport if roughly equivalent latency

cmd/tailscale/cli/cli.go, cmd/tailscale/cli/ip.go
This adds an easy and portable way for us to document how to get
your Tailscale IP address.
```
$ tailscale ip
100.74.70.3
fd7a:115c:a1e0:ab12:4843:cd96:624a:4603
$ tailscale ip -4
100.74.70.3
$ tailscale ip -6
fd7a:115c:a1e0:ab12:4843:cd96:624a:4603
```
=> cmd/tailscale: add "tailscale ip [-4] [-6]" command

go.mod, go.sum, wgengine/magicsock/magicsock_test.go, wgengine/userspace.go, wgengine/wgcfg/device_test.go
Adapt to minor API changes in wireguard-go.
And factor out device.DeviceOptions variables.
=> wgengine: pass logger as a separate arg to device.NewDevice

wgengine/router/router.go, wgengine/router/router_darwin.go, wgengine/router/router_default.go, wgengine/router/router_fake.go, wgengine/router/router_freebsd.go, wgengine/router/router_linux.go, wgengine/router/router_linux_test.go, wgengine/router/router_openbsd.go, wgengine/router/router_userspace_bsd.go, wgengine/router/router_windows.go, wgengine/userspace.go
=> wgengine/router: remove unused wireguard *Device argument.

wgengine/watchdog_test.go
This works around the close syscall being slow.
We can revert this if we find a fix or if Apple makes close fast again.
=> wgengine: extend TestWatchdog timeout on macOS

wgengine/userspace.go, wgengine/userspace_test.go
On macOS/iOS, this removes a map lookup per outgoing packet.
Noticed it while reading code, not from profiles, but can't hurt.
```
BenchmarkGenLocalAddrFunc
BenchmarkGenLocalAddrFunc/map1
BenchmarkGenLocalAddrFunc/map1-4                16184868                69.78 ns/op
BenchmarkGenLocalAddrFunc/map2
BenchmarkGenLocalAddrFunc/map2-4                16878140                70.73 ns/op
BenchmarkGenLocalAddrFunc/or1
BenchmarkGenLocalAddrFunc/or1-4                 623055721                1.950 ns/op
BenchmarkGenLocalAddrFunc/or2
BenchmarkGenLocalAddrFunc/or2-4                 472493098                2.589 ns/op
```
=> wgengine: optimize isLocalAddr a bit

client/tailscale/tailscale.go, cmd/tailscale/cli/cli.go, safesocket/safesocket.go
Without this, `tailscale status` ignores the --socket flag on macOS and
always talks to the IPNExtension, even if you wanted it to inspect a
userspace tailscaled.
=> client/tailscale, cmd/tailscale/cli: plumb --socket through

wgengine/netstack/netstack.go
=> wgengine/netstack: stop re-adding IPs registered by active TCP connections

cmd/tailscale/cli/down.go, ipn/backend.go, ipn/fake_test.go, ipn/ipnlocal/local.go, ipn/message.go, ipn/prefs.go, ipn/prefs_test.go
This adds a new ipn.MaskedPrefs embedding a ipn.Prefs, along with a
bunch of "has bits", kept in sync with tests & reflect.
Then it adds a Prefs.ApplyEdits(MaskedPrefs) method.
Then the ipn.Backend interface loses its weirdo SetWantRunning(bool)
method (that I added in 483141094c for "tailscale down")
and replaces it with EditPrefs (alongside the existing SetPrefs for now).
Then updates 'tailscale down' to use EditPrefs instead of SetWantRunning.
In the future, we can use this to do more interesting things with the
CLI, reconfiguring only certain properties without the reset-the-world
"tailscale up".
Updates #1436
=> ipn: replace SetWantRunning(bool) with EditPrefs(MaskedPrefs)

wgengine/monitor/monitor_linux.go, wgengine/monitor/monitor_polling.go, wgengine/monitor/polling.go
Google Cloud Run does not implement NETLINK_ROUTE RTMGRP.
If initialization of the netlink socket or group membership
fails, fall back to a polling implementation.
=> wgengine/monitor: Linux fall back to polling

go.mod, go.sum, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/userspace.go
Part of a temporary change to make merging wireguard-go easier.
See https://github.com/tailscale/wireguard-go/pull/45.
=> wgengine/magicsock: adapt CreateEndpoint signature to match wireguard-go

tailcfg/tailcfg.go, tailcfg/tailcfg_test.go
Old macOS clients required we populate this field to a non-null
value so we were unable to remove this field before.
Instead, keep the field but change its type to a custom empty struct
that can marshal/unmarshal JSON. And lock it in with a test.
=> tailcfg: remove UserProfile.Roles field, add tests for legacy behavior

internal/deepprint/deepprint_test.go, ipn/ipnlocal/local.go, net/dns/config.go, net/dns/direct.go, net/dns/manager.go, net/dns/manager_windows.go, net/dns/nm.go, net/dns/noop.go, net/dns/resolvconf.go, net/dns/resolved.go, wgengine/router/router.go, wgengine/userspace.go, wgengine/userspace_test.go, wgengine/watchdog.go, wgengine/wgengine.go
The code flow is still a bit of a mess, and wgengine ends up splitting dns.Config into resolver.Config and dns.OSConfig internally. But wgengine's APIs handle the right configs now, another step of the refactor.
Opening PR mostly for a review of the docs and semantics of the dns.Config struct, the rest is a lot of mechanical moving around that amounts to a behavioral no-op.
Also submitting eagerly, so I can continue with the refactor, but would still like feedback.
=> Add new DNS config struct, and start plumbing it into wgengine and ipn.

ipn/ipnlocal/local.go, net/dns/config.go, net/dns/direct.go, net/dns/manager.go, net/dns/manager_test.go, net/dns/manager_windows.go, net/dns/nm.go, net/dns/noop.go, net/dns/osconfig.go, net/dns/resolvconf.go, net/dns/resolved.go, net/dns/resolver/tsdns.go, wgengine/router/callback.go
With this, and split DNS forced on in net/dns (not plumbed through tailcfg yet), split DNS works on Windows 7 through 10. Other DNS managers still need to implement the couple of API calls to make it go, but this is the meaty core of "figure out how to implement a requested DNS config based on what the OS can do".
Also includes exhaustive tests covering the possible configurations stemming from the high-level intent.
=> net/dns: Implement resolver vs. OS config splitting

client/tailscale/tailscale.go, cmd/tailscale/cli/cli.go, cmd/tailscale/cli/logout.go, control/controlclient/auto.go, control/controlclient/direct.go, ipn/ipnlocal/local.go, ipn/localapi/localapi.go
Adds `tailscale logout` and makes "Log out" from GUIs actually log out, telling the server that the node key should be immediately expired.
=> ipn/{ipnlocal,localapi}, cmd/tailscale: add logout command

disco/disco_fuzzer.go, net/stun/stun_fuzzer.go
Hello
I saw in the code that a fuzzing was on the to-do list:
https://github.com/tailscale/tailscale/blob/e4f53e9b6f1a4d3d6f00091ddef617989b1ea3e4/net/stun/stun_test.go#L16
I have run these on OSS-fuzz's infrastructure as well and would be happy to set up an integration application so they can run continuously free of charge by OSS-fuzz. 
Tagging @bradfitz since you were mentioned in the comment.
Signed-off-by: AdamKorcz <adam@adalogics.com>
=> Added 2 fuzzers

cmd/tailscaled/tailscaled.go
Adding the `mustUseNetstack()` function made it so the `ns` variable was never initialized, but `ns.DialContextTCP()` was used for SOCKS5 requests, causing a nil dereference/panic. This fixes that.
=> cmd/tailscaled: populate netstack variable to use dialer in SOCKS5

cmd/tailscale/cli/logout.go, cmd/tailscale/cli/up.go
Fixes the capitalization of a command so it's consistent with the rest:
```diff
SUBCOMMANDS
up         Connect to your Tailscale network
down       Disconnect from Tailscale
-   logout     down + expire current node key
+   logout     Down and expire current node key
netcheck   Print an analysis of local network conditions
ip         Show current Tailscale IP address(es)
status     Show state of tailscaled and its connections
ping       Ping a host at the Tailscale layer, see how it routed
version    Print Tailscale version
web        Run a web server for controlling Tailscale
push       Push a file to a host
bugreport  Print a shareable identifier to help diagnose issues
```
=> cmd/tailscale: fix capitalization

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go, ipn/fake_test.go, ipn/handle.go, ipn/ipnlocal/local.go, ipn/prefs.go
The ipn.NewPrefs func returns a populated ipn.Prefs for historical
reasons. It's not used or as important as it once was, but it hasn't
yet been removed. Meanwhile, it contains some default values that are
used on some platforms. Notably, for this bug (#1725), Windows/Mac use
its Prefs.RouteAll true value (to accept subnets), but Linux users
have always gotten a "false" value for that, because that's what
cmd/tailscale's CLI default flag is _for all operating systems_.  That
meant that "tailscale up" was rightfully reporting that the user was
changing an implicit setting: RouteAll was changing from true with
false with the user explicitly saying so.
An obvious fix might be to change ipn.NewPrefs to return
Prefs.RouteAll == false on some platforms, but the logic is
complicated by darwin: …
=> ipn{,/ipnlocal}, cmd/tailscale/cli: don't check pref reverts on initial up

ipn/backend.go, ipn/ipnlocal/peerapi.go
Let caller (macOS) do it so Finder progress bar can be dismissed
without races.
Updates tailscale/corp#1575
=> ipn{,/ipnlocal}: in direct file receive mode, don't rename partial file

cmd/tailscaled/tailscaled.go, ipn/ipnlocal/local.go, ipn/ipnserver/server.go, ipn/message.go
Logout used to be a no-op, so the ipnserver previously synthensized a Logout
on disconnect. Now that Logout actually invalidates the node key that was
forcing all GUI closes to log people out.
Instead, add a method to LocalBackend to specifically mean "the
Windows GUI closed, please forget all the state".
Fixes tailscale/corp#1591 (ignoring the notification issues, tracked elsewhere)
=> ipn: don't Logout when Windows GUI disconnects

wgengine/netstack/netstack.go
I see a bunch of these in some logs I'm looking at,
separated only by a few seconds.
Log the error so we can tell what's going on here.
=> wgengine/netstack: log error when acceptUDP fails

wgengine/wglog/wglog.go
I've spent two days searching for a theoretical wireguard-go bug
around receive functions exiting early.
I've found many bugs, but none of the flavor we're looking for.
Restore wireguard-go's logging around starting and stopping receive functions,
so that we can definitively rule in or out this particular theory.
=> wgengine/wglog: allow wireguard-go receive routines to log

cmd/tailscale/cli/up.go
=> cmd/tailscale/cli: don't force an interactive login on --reset.

health/health.go, wgengine/magicsock/magicsock.go
The existing implementation was completely, embarrassingly conceptually broken.
We aren't able to see whether wireguard-go's receive function goroutines
are running or not. All we can do is model that based on what we have done.
This commit fixes that model.
Fixes #1781
=> health, wgenegine: fix receive func health checks yet again

wgengine/router/ifconfig_windows.go, wgengine/router/ifconfig_windows_test.go, wgengine/router/router_linux_test.go, wgengine/router/router_test.go
=> wgengine/router{win}: ignore broadcast routes added by Windows when removing routes.

net/tstun/wrap.go, wgengine/bench/bench.go, wgengine/bench/bench_test.go, wgengine/bench/trafficgen.go, wgengine/bench/wg.go
This tries to generate traffic at a rate that will saturate the
receiver, without overdoing it, even in the event of packet loss. It's
unrealistically more aggressive than TCP (which will back off quickly
in case of packet loss) but less silly than a blind test that just
generates packets as fast as it can (which can cause all the CPU to be
absorbed by the transmitter, giving an incorrect impression of how much
capacity the total system has).
Initial indications are that a syscall about every 10 packets (TCP bulk
delivery) is roughly the same speed as sending every packet through a
channel. A syscall per packet is about 5x-10x slower than that.
The whole tailscale wireguard-go + magicsock + packet filter
combination is about 4x slower again, which is better than I thought
we'd do, but …
=> cmd/tailbench: speed test for channels, sockets, and wireguard-go.

net/dns/manager.go, net/dns/manager_test.go
=> net/dns: work around WSL DNS implementation flaws.

net/tstun/wrap.go, wgengine/userspace.go
We had a long-standing bug in which our TUN events channel
was being received from simultaneously in two places.
The first is wireguard-go.
At wgengine/userspace.go:366, we pass e.tundev to wireguard-go,
which starts a goroutine (RoutineTUNEventReader)
that receives from that channel and uses events to adjust the MTU
and bring the device up/down.
At wgengine/userspace.go:374, we launch a goroutine that
receives from e.tundev, logs MTU changes, and triggers
state updates when up/down changes occur.
Events were getting delivered haphazardly between the two of them.
We don't really want wireguard-go to receive the up/down events;
we control the state of the device explicitly by calling device.Up.
And the userspace.go loop MTU logging duplicates logging that
wireguard-go does when it received …
=> net/tstun: split TUN events channel into up/down and MTU

cmd/tailscale/cli/up.go
Signed-off-by: Ross Zurowski <ross@rosszurowski.com>
=> cmd/tailscale: fix typo in error message

ipn/ipnlocal/local.go
With this change, shared node names resolve correctly on split DNS-supporting
operating systems.
Fixes tailscale/corp#1706
=> ipn/ipnlocal: be authoritative for the entire MagicDNS record tree.

control/controlclient/auto.go, control/controlclient/client.go, control/controlclient/controlclient_test.go, control/controlclient/direct.go, control/controlclient/status.go, go.mod, ipn/backend.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/state_test.go
- Rename controlclient.Client to controlclient.AutoClient.
- Introduce a new controlclient.Client interface with the same
public functions.
- Let ipnlocal.Local accept a controlclient.Client constructor
function.
- Write a very long unit test that verifies the way the two objects
interact.
In this commit, I'm just moving some code around and adding a giant
sequential test of the state machine. The test passes, but only because
it's asserting all the wrong behaviour. I marked all the behaviour I
think is wrong with BUG comments, and several additional test
opportunities with TODO.
Note: the new test supercedes TestStartsInNeedsLoginState, which was
checking for incorrect behaviour (although we're still checking for the
same incorrect behaviour) and assumed .Start() would converge before …
=> ipn: mock controlclient.Client; big ipn.Backend state machine test.

wgengine/wglog/wglog.go, wgengine/wglog/wglog_test.go
Two commits; review one at a time.
=> wgengine/wglog: fix wireguard-go logging rate limiting

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go
There's no need to warn that it was not provided on the command line
after doing a sequence of up; logout; up --args. If you're asking for
tailscale to be up, you always mean that you prefer LoggedOut to become
false.
Fixes #1828
Signed-off-by: Avery Pennarun <apenwarr@tailscale.com>
=> cmd/tailscale/cli/up: "LoggedOut" pref is implicit.

go.mod, go.sum, ipn/ipnlocal/state_test.go
Per discussion, we want to have only one test assertion library,
and we want to start by exploring quicktest.
This was a mostly mechanical translation.
I think we could make this nicer by defining a few helper
closures at the beginning of the test. Later.
=> ipn/ipnlocal: switch from testify to quicktest

cmd/tailscaled/tailscaled_windows.go, logtail/filch/filch.go, net/tstun/ifstatus_windows.go, portlist/portlist_windows.go, safesocket/pipe_windows.go, wgengine/router/ifconfig_windows.go, wgengine/router/router_windows.go
We weren't running staticcheck with GOOS=windows.
Preditably, there were lots of failures.
Fix or suppress a bunch of little staticcheck complaints,
so that we can add windows staticcheck to CI.
=> all: make staticcheck happy on windows

cmd/tailscale/cli/cli.go
We were over-eager in running tailscale in GUI mode.
f42ded7acf63e2f3711f6512b701ddeac0e2d7a6 fixed that by
checking for a variety of shell-ish env vars and using those
to force us into CLI mode.
However, for reasons I don't understand, those shell env vars
are present when Xcode runs Tailscale.app on my machine.
(I've changed no configs, modified nothing on a brand new machine.)
Work around that by adding an additional "only in GUI mode" check.
=> cmd/tailscale/cli: fix running from Xcode

types/netmap/netmap.go, wgengine/netstack/netstack.go
=> wgengine/netstack: don't pass non-subnet traffic to netstack in hybrid mode

wgengine/netstack/netstack.go
The earlier eb06ec172f1d984bb87c589da1dd2d3f15dc6d82 fixed
the flaky SSH issue (tailscale/corp#1725) by making sure that packets
addressed to Tailscale IPs in hybrid netstack mode weren't delivered
to netstack, but another issue remained:
All traffic handled by netstack was also potentially being handled by
the host networking stack, as the filter hook returned "Accept", which
made it keep processing. This could lead to various random racey chaos
as a function of OS/firewalls/routes/etc.
Instead, once we inject into netstack, stop our caller's packet
processing.
=> wgengine/netstack: avoid delivering incoming packets to both netstack + host

net/dns/nm.go
NetworkManager has various combos of undocumented requirements for what you're allowed to configure, and also rejects unknown fields. This set of commits (reviewable individually) fixes our behavior on Ubuntu 18.04, such that NM config succeeds.
=> Fix NM configuration on older networkmanagers.

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go, ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go
The old way was way too fragile and had felt like it had more special
cases than normal cases. (see #1874, #1860, #1834, etc) It became very
obvious the old algorithm didn't work when we made the output be
pretty and try to show the user the command they need to run (in
5ecc7c7200bda43f02f9a04fb684ad4f3614c48a for #1746)
The new algorithm is to map the prefs (current and new) back to flags
and then compare flags. This nicely handles the OS-specific flags and
the n:1 and 1:n flag:pref cases.
No change in the existing already-massive test suite, except some ordering
differences (the missing items are now sorted), but some new tests are
added for behavior that was broken before. In particular, it now:
* preserves non-pref boolean flags set to false, and preserves exit
node IPs (mapping them …
=> cmd/tailscale: rewrite the "up" checker, fix bugs

ipn/ipnserver/server.go, ipn/message.go, ipn/message_test.go
If nobody is connected to the IPN bus, don't burn CPU & waste
allocations (causing more GC) by encoding netmaps for nobody.
This will notably help hello.ipn.dev.
Updates tailscale/corp#1773
=> ipn{,/ipnserver}: delay JSON marshaling of ipn.Notifies

wgengine/bench/bench_test.go, wgengine/bench/wg.go, wgengine/userspace.go
On benchmark completion, we shut down the wgengine.
If we happen to poll for status during shutdown,
we get an "engine closing" error.
It doesn't hurt anything; ignore it.
I'm not 100% sure that this will fix tailscale/corp#1776,
since I have been unable to reproduce it locally,
but it's a good place to start.
=> wgengine/bench: ignore "engine closing" errors

control/controlclient/direct.go, ipn/ipnlocal/local.go
These are small enough that they might be safe to include in v1.8.0, but are not regressions.
=> Two minor fixes encountered while chasing tailscale/corp#1756

control/controlclient/direct.go, ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go
This code path is very tricky since it was originally designed for the
"re-authenticate to refresh my keys" use case, which didn't want to
lose the original session even if the refresh cycle failed. This is why
it acts differently from the Logout(); Login(); case.
Maybe that's too fancy, considering that it probably never quite worked
at all, for switching between users without logging out first. But it
works now.
This was more invasive than I hoped, but the necessary fixes actually
removed several other suspicious BUG: lines from state_test.go, so I'm
pretty confident this is a significant net improvement.
Fixes tailscale/corp#1756.
(relies on RequestEngineStatusAndWait() deadlock fix)
=> ipnlocal: fix switching users while logged in + Stopped.

tstest/integration/integration_test.go, tstest/integration/testcontrol/testcontrol.go
Adds the fields such that when running Ping(ip netaddr.IP, useTSMP bool, cb func(*ipnstate.PingResult)), it calls peerForIP inside of userspace.go, inside that function it checks
```go
for _, p := range nm.Peers {
for _, a := range p.Addresses {
if a.IP() == ip && a.IsSingleIP() && tsaddr.IsTailscaleIP(ip) {
return p, nil
}
}
for _, cidr := range p.AllowedIPs {
if !cidr.Contains(ip) {
continue
}
if bestInNMPrefix.IsZero() || cidr.Bits() > bestInNMPrefix.Bits() {
bestInNMPrefix = cidr
bestInNM = p
}
}
}
```
but peers the Addresses, and AllowedIPs fields are nil, so these checks for bestInNM are not reached.
=> Added new Addresses / AllowedIPs fields to testcontrol when creating tailcfg.Node

ipn/ipnlocal/local.go, net/dns/config.go, net/dns/manager.go, net/dns/manager_test.go
Two commits, reviewable independently. One fixes #1886, the other refactors net/dns's configuration API to better capture these kinds of configurations. We can backport just the first commit to 1.8.x, and leave the cleanup commit for 1.10.
=> Always serve MagicDNS records from 100.100.100.100.

ipn/message.go, ipn/message_test.go
A couple of code paths in ipnserver use a NewBackendServer with a nil
backend just to call the callback with an encapsulated error message.
This covers a panic case seen in logs.
For #1920
=> ipn: allow b to be nil in NewBackendServer

internal/deephash/deephash.go, internal/deephash/deephash_test.go, internal/deephash/mapiter.go, internal/deephash/mapiter_future.go, wgengine/userspace.go
Hash and xor each entry instead, then write final xor'ed result.
```
name    old time/op    new time/op    delta
Hash-4    33.6µs ± 4%    34.6µs ± 3%  +3.03%  (p=0.013 n=10+9)
name    old alloc/op   new alloc/op   delta
Hash-4    1.86kB ± 0%    1.77kB ± 0%  -5.10%  (p=0.000 n=10+9)
name    old allocs/op  new allocs/op  delta
Hash-4      51.0 ± 0%      49.0 ± 0%  -3.92%  (p=0.000 n=10+10)
```
=> internal/deephash: hash maps without sorting in the acyclic common case

internal/deephash/deephash.go, internal/deephash/mapiter.go, internal/deephash/mapiter_future.go
For reference.
```
Hash-8              12.4µs ± 0%    12.4µs ± 0%    -0.33%  (p=0.002 n=10+9)
HashMapAcyclic-8    21.2µs ± 0%    21.3µs ± 0%    +0.45%  (p=0.000 n=8+8)
name              old alloc/op   new alloc/op   delta
Hash-8                793B ± 0%      408B ± 0%   -48.55%  (p=0.000 n=10+10)
HashMapAcyclic-8      128B ± 0%        0B       -100.00%  (p=0.000 n=10+10)
name              old allocs/op  new allocs/op  delta
Hash-8                9.00 ± 0%      6.00 ± 0%   -33.33%  (p=0.000 n=10+10)
HashMapAcyclic-8      1.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
Depends on https://github.com/golang/go/issues/46293.
```
=> internal/deephash: re-use MapIter

tailcfg/tailcfg.go, tailcfg/tailcfg_test.go, types/wgkey/key.go
Add MarshalText-like appending variants. Like:
https://pkg.go.dev/inet.af/netaddr#IP.AppendTo
To be used by @josharian's pending deephash optimizations.
=> tailcfg, types/wgkey: add AppendTo methods on some types

ipn/ipnlocal/local.go
On clean installs we didn't set use iptables, but during upgrades it
looks like we could use old prefs that directed us to go into the iptables
paths that might fail on Synology.
Updates #1995
Fixes tailscale/tailscale-synology#57 (I think)
=> ipn/ipnlocal: ignore NetfilterMode pref on Synology

tstest/integration/vms/vms_test.go
Instead of relying on a libvirtd bridge address that you probably won't have on your system.
Updates #1988 
=> tstest/integration/vms: use dynamically discovered bindhost

go.mod, go.sum, tstest/integration/integration.go, tstest/integration/integration_test.go, tstest/integration/vms/vms_test.go
Instead of pulling packages from pkgs.tailscale.com, we should use the
tailscale binaries that are local to this git commit. This exposes a bit
of the integration testing stack in order to copy the binaries
correctly.
This commit also bumps our version of github.com/pkg/sftp to the latest
commit.
If you run into trouble with yaml, be sure to check out the
commented-out alpine linux image complete with instructions on how to
use it.
Updates #1988
=> tstest/integration/vms: copy locally built binaries

tstest/integration/vms/vms_test.go
Don't try to do heuristics on the name. Use the net/interfaces package
which we already have to do this sort of stuff.
Fixes #2011
=> tstest/integration/vms: fix bindhost lookup

tstest/integration/vms/regex_flag.go, tstest/integration/vms/regex_flag_test.go, tstest/integration/vms/vms_test.go
If you set `-distro-regex` to match a subset of distros, only those
distros will be tested. Ex:
$ go test -run-vm-tests -distro-regex='opensuse'
=> tstest/integration/vms: regex-match distros using a flag

tstest/integration/vms/vms_test.go
This distro is about to be released. OpenSUSE has historically had the
least coverage for functional testing, so this may prove useful in the
future.
=> tstest/integration/vms: add OpenSUSE Leap 15.3

tstest/integration/vms/vms_test.go
Arch is a bit of a weirder distro, however as a side effect it is much
more of a systemd purist experience. Adding it to our test suite will
make sure that we are working in the systemd happy path.
Updates #1988
=> tstest/integration/vms: test on Arch Linux

go.mod, tstest/integration/vms/opensuse_leap_15_1_test.go, tstest/integration/vms/vms_test.go
The OpenSUSE 15.1 image we are using (and conseqentially the only one
that is really available easily given it is EOL) has cloud-init
hardcoded to use the OpenStack metadata thingy. Other OpenSUSE Leap
images function fine with the NoCloud backend, but this one seems to
just not work with it. No bother, we can just pretend to be OpenStack.
Thanks to Okami for giving me an example OpenStack configuration seed
image.
Updates #1988
=> tstest/integration/vms: fix OpenSUSE Leap 15.1

tstest/integration/vms/vms_test.go
Most of the time qemu will output nothing when it is running. This is
expected behavior. However when qemu is unable to start due to some
problem, it prints that to either stdout or stderr. Previously this
output wasn't being captured. This patch captures that output to aid in
debugging qemu issues.
Updates #1988
=> tstest/integration/vms: log qemu output

tstest/integration/vms/vms_test.go
The image downloads can take a significant amount of time for the tests.
This creates a new test that will download every distro image into the
local cache in parallel, optionally matching the distribution regex.
Updates #1988
=> tstest/integration/vms: add a command line flag to download everything

go.mod, go.sum, tstest/integration/vms/README.md, tstest/integration/vms/vms_test.go
This makes integration tests pull pristine VM images from Amazon S3 if
they don't exist on disk. If the S3 fetch fails, it will fall back to
grabbing the image from the public internet. The VM images on the public
internet are known to be updated without warning and thusly change their
SHA256 checksum. This is not ideal for a test that we want to be able to
fire and forget, then run reliably for a very long time.
This requires an AWS profile to be configured at the default path. The
S3 bucket is rigged so that the requester pays. The VM images are
currently about 6.9 gigabytes. Please keep this in mind when running
these tests on your machine.
Documentation was added to the integration test folder to aid others in
running these tests on their machine.
Updates #1988
Signed-off-by: …
=> tstest/integration/vms: download images from s3

control/controlclient/hostinfo_linux.go
Missed one comment from https://github.com/tailscale/tailscale/pull/1868
should be isAWSLambda not isAwsLambda
=> hostinfo: capitalization of AWS

tstest/integration/integration_test.go
Failing often now, we don't want people to get used to
routinely ignoring test failures.
Can be re-enabled when
https://github.com/tailscale/tailscale/issues/2079
is resolved.
=> tstest/integration: disable TestAddPingRequest

wf/firewall.go
I overlooked this when doing the initial implementation.
This is now the same as https://github.com/tailscale/tailscale/blob/main/tempfork/wireguard-windows/firewall/rules.go#L242.
I verified that all other MatchTypes are set correctly.
Fixes #2133, #2106, #2105
=> wf: loopback condition should use MatchTypeFlagsAllSet.

ipn/ipnlocal/local.go
=> ipn/ipnlocal: support exit node local access switching on darwin.

derp/derp_server.go
Before it was using the local address and port, so fix that.
The fields in the response from `ss` are:
State, Recv-Q, Send-Q, Local Address:Port, Peer Address:Port, Process
=> derp: fix traffic handler peer addresses

tailcfg/derpmap.go, tailcfg/tailcfg_clone.go
This adds a flag to derp maps which specifies that default Tailscale DERP servers should not be
used. If true and there are entries in this map, it indicates that the entries in this map
should take precedent and not hit any of tailscale's DERP servers.
This change is backwards compatible, as the default behavior should be false.
Updates #1264
=> tailcfg/derpmap: add flag to omit ts's derps

tstest/integration/vms/vms_test.go
Occasionally the test framework would fail with a timeout due to a virtual machine not phoning home in time. This seems to be happening whenever qemu can't bind the VNC or SSH ports for a virtual machine, usually when an orphaned virtual machine was left behind by a previously failed test run. This was fixed by taking the following actions:
1. Don't listen on VNC unless the `-use-vnc` flag is passed, this removes the need to listen on VNC at all in most cases. The option to use VNC is still left in for debugging virtual machines, but removing this makes it easier to deal with (VNC uses this odd system of "displays" that are mapped to ports above 5900, and qemu doesn't offer a decent way to use a normal port number, so we just disable VNC by default as a compromise).
2. Use a (hopefully) …
=> tstest/integration/vms: fix flake when testing

tstest/integration/integration.go, tstest/integration/integration_test.go, tstest/integration/vms/vms_test.go
Previously this test would reach out to the public DERP servers in order
to help machines connect with eachother. This is not ideal given our
plans to run these tests completely disconnected from the internet. This
patch introduces an in-process DERP server running on its own randomly
assigned HTTP port.
Updates #1988
=> tstest/integration/vms: add in-process DERP server

.github/workflows/xe-experimental-vm-test.yml, tstest/integration/vms/nixos_test.go, tstest/integration/vms/runner.nix, tstest/integration/vms/vms_test.go
Okay, so, at a high level testing NixOS is a lot different than
other distros due to NixOS' determinism. Normally NixOS wants packages to
be defined in either an overlay, a custom packageOverrides or even
yolo-inline as a part of the system configuration. This is going to have
us take a different approach compared to other distributions. The overall
plan here is as following:
1. make the binaries as normal
2. template in their paths as raw strings to the nixos system module
3. run `nixos-generators -f qcow -o $CACHE_DIR/tailscale/nixos/version -c generated-config.nix`
4. pass that to the steps that make the virtual machine
It doesn't really make sense for us to use a premade virtual machine image
for this as that will make it harder to deterministically create the image.
Nix commands …
=> tstest/integration/vms: build and run NixOS

cmd/tailscale/cli/debug.go
This adds a flag in tailscale debug for dumping the derp map to stdout.
Fixes #2249
=> cmd/tailscale: add debug flag to dump derp map

cmd/tailscaled/tailscaled_windows.go, ipn/ipnlocal/local.go, wgengine/router/router_windows.go
Note: This requires reconfiguring the firewall while it's enabled to allow the local routes through, the way we do this is by passing in a json encoded list of routes to the firewall process via stdin.
Updates #1527
=> wgengine/router_windows: support toggling local lan access when using exit nodes.

net/dns/manager_windows.go, net/dns/wsl_windows.go, util/winutil/winutil.go
It doesn't work. It needs to run as the user.
https://github.com/microsoft/WSL/issues/4803
The mechanism for doing this was extracted from:
https://web.archive.org/web/20101009012531/http://blogs.msdn.com/b/winsdk/archive/2009/07/14/launching-an-interactive-process-from-windows-service-in-windows-vista-and-later.aspx
=> net/dns: avoid running wsl.exe as LocalSystem

tstest/integration/vms/nixos_test.go, tstest/integration/vms/vms_test.go
This puts nix build logs on the filesystem so that we can debug them
later. This also disables nixos unstable until
https://github.com/NixOS/nixpkgs/issues/128783 is fixed.
=> tstest/integration/vms: verbosify nixos logs to fs, disable unstable

ipn/ipnlocal/local.go
We can't access b.netMap without holding b.mu.
We already grabbed it earlier in the function with the lock held.
Introduced in Nov 2020 in 7ea809897df1764ea420be2ff6ae58459b0e6902.
Discovered during stress testing.
Apparently it's a pretty rare?
=> ipn/ipnlocal: fix data race

internal/deephash/deephash.go, internal/deephash/deephash_test.go
Running hex.Encode(b, b) is a bad idea.
The first byte of input will overwrite the first two bytes of output.
Subsequent bytes have no impact on the output.
Wh::ps.
This caused us to spuriously ignore some wireguard config updates.
=> internal/deephash: 8 bits of output is not enough

build_docker.sh
`version/version.sh` was removed in commit 5088af68. Use `build_dist.sh shellvars` to provide version information instead.
=> build_docker.sh: use build_dist.sh to inject version information

.github/workflows/xe-experimental-vm-test.yml, tstest/integration/vms/vms_test.go
Oracle Linux[1] is a CentOS fork. It is not very special. I am adding it
to the integration jungle.
[1]: https://www.oracle.com/linux/
=> tstest/integration/vms: Oracle Linux Support

tstest/integration/vms/vms_test.go
This does two things:
1. Rewrites the tests so that we get a log of what individual tests failed at the end of a test run.
2. Adds a test that runs an SSH server via the tester tailscale node and then has the VMs connect to that over Tailscale.
3. Adds a test that makes SSH connections to each VM being tested and ensures that `tailscale ip` works.
This tests outgoing TCP connections.
=> tstest/integration/vms: bidirectional SSH tests

cmd/tailscaled/tailscaled.openrc, tstest/integration/integration.go, tstest/integration/integration_test.go, tstest/integration/vms/nixos_test.go, tstest/integration/vms/vms_test.go
This adapts the existing in-process logcatcher from tstest/integration
into a public type and uses it on the side of testcontrol. This also
fixes a bug in the Alpine Linux OpenRC unit that makes every value in
`/etc/default/tailscaled` exported into tailscaled's environment, a-la
systemd [Service].EnviromentFile.
=> tstest/integration/vms: use an in-process logcatcher

tstest/integration/vms/udp_tester.go, tstest/integration/vms/vms_test.go
This tests incoming and outgoing UDP traffic. It would test incoming UDP
traffic however our socks server doesn't seem to allow for connecting to
destinations over UDP. When the socks server gets that support the
incoming test should pass without issue.
=> tstest/integration/vms: end-to-end UDP test

safesocket/basic_test.go
This allows the test to be run inside a mounted filesystem,
which I'm doing now as a I develop on a linux VM.
Fixes #2367.
=> safesocket: create the test socket in a temp dir

tstest/integration/vms/nixos_test.go, tstest/integration/vms/vms_test.go
To avoid the generated nixos disk images from becoming immune from the
GC, I delete the symlink to the nix store at the end of tests.
`t.Cleanup` runs at the end of a test. I changed this part of the code
to have a separate timer for how long it takes to run NixOS builds, but
I did that by using a subtest. This means that it was creating the NixOS
image, deleting its symlink and then trying to use that symlink to find
the resulting disk image, making the whole thing ineffectual.
This was a mistake. I am reverting this change made in
https://github.com/tailscale/tailscale/pull/2360 to remove this layer of
subtesting.
=> tstest/integration/vms: unbreak nixos builds

tstest/integration/vms/vms_test.go
The upstream NixOS issue was fixed.
NixOS/nixpkgs#128783
=> Enable nixos unstable again

cmd/tailscale/cli/netcheck.go, net/portmapper/portmapper.go, net/portmapper/portmapper_test.go, wgengine/magicsock/magicsock.go
Making portmapping creation async so we can afford to make it slower (for UPnP) without stalling other parts of magicsock.
=> wgengine/magicsock: make portmapping async

tstest/integration/testcontrol/testcontrol.go, tstest/integration/vms/vms_test.go
Split from https://github.com/tailscale/tailscale/pull/2376
This adds IPv6 support to testcontrol so each member of the tailscale
network gets an IPv6 address too.
=> tstest/integration/testcontrol: add ipv6 support

tstest/integration/vms/derive_bindhost_test.go, tstest/integration/vms/distros.go, tstest/integration/vms/harness_test.go, tstest/integration/vms/vm_setup_test.go, tstest/integration/vms/vms_steps_test.go, tstest/integration/vms/vms_test.go
My spatial memory functions poorly with large files and the vms_test.go
file recently surpassed the point where it functions adequately. This
patch splits up vms_test.go into more files to make my spatial memory
function like I need it to.
=> tstest/integration/vms: split up test framework into files

cmd/tailscale/cli/web.go, cmd/tailscale/cli/web_test.go
When running `tailscale web` I saw no output and was unsure which address the server was listening on, so I added a log to display this.
Signed-off-by: Dan Bond <danbond@protonmail.com>
=> cmd/tailscale: log web listen addr

net/uring/capability_linux.go, net/uring/io_uring_test.go
Adds the ability to probe for various capabilities. It will not call into C unless
necessary. It also allocates one probe per call to new capability, which may be expensive, so in
theory they could be reused instead.
Re-opened version of https://github.com/tailscale/tailscale/pull/2366
onto different branch
=> net/uring: add probing capability

ipn/ipnlocal/local.go, tstest/integration/integration_test.go
Regression from 6d10655dc3887f1a161015514a8555c175802b4d, which added
UpdatePrefs but didn't write it out to disk.
I'd planned on adding tests to state_test.go which is why I'd earlier
added 46896a93118d0eecbacb4255da2df0349da9b409 to prepare for making
such persistence tests easier to write, but turns out state_test.go
didn't even test UpdatePrefs, so I'm staying out of there.
Instead, this is tested using integration tests.
Fixes #2321
=> ipn/ipnlocal: save prefs to disk on UpdatePrefs

wgengine/magicsock/magicsock_test.go
logBufWriter had no serialization.
It just so happens that none of its users currently ever log concurrently.
Make it safe for concurrent use.
=> wgengine/magicsock: fix latent data race in test

ipn/localapi/localapi.go
The localapi was double-unescaping: once by net/http populating
the URL, and once by ourselves later. We need to start with the raw
escaped URL if we're doing it ourselves.
Started to write a test but it got invasive. Will have to add those
tests later in a commit that's not being cherry-picked to a release
branch.
Fixes #2288
=> ipn/localapi: fix inability to receive taildrop files w/ escaped names

cmd/derper/derper.go
This adds some convenient defaults for -c, so that user-provided DERPs require less command line
flags.
=> cmd/derper: add default -c arguments

cmd/speedtest/speedtest.go, net/speedtest/speedtest.go, net/speedtest/speedtest_client.go, net/speedtest/speedtest_server.go, net/speedtest/speedtest_test.go
Added the speedtest package with code for running a speedtest server. The speedtest server takes a host and port to start on. It also takes a maximum number of connections. It then listens and waits for clients to connect to it. The client starts up using the server address and port. It then sends a json encoded TestConfig that contains test configs, like the type of test and duration of the test. After the server receives the TestConfig, it sends a response back to the client. This response contains any errors that the server has with the test parameters (for now, it only checks version). If there are no errors, it starts the test and starts sending messages filled with random data to the client. The client calculates an average speed at specific intervals. At the end of the test, it …
=> Add Speedtest CLI Command

net/dns/resolver/doh_test.go, net/dns/resolver/forwarder.go
Recognize Cloudflare, Google, Quad9 which are by far the
majority of upstream DNS servers that people use.
RELNOTE=MagicDNS now uses DNS-over-HTTPS when querying popular upstream resolvers,
so DNS queries aren't sent in the clear over the Internet.
Updates #915 (might fix it?)
Updates #988 (gets us closer, if it fixes Android)
Updates #74 (not yet configurable, but progress)
Updates #2056 (not yet configurable, dup of #74?)
=> net/dns/resolver: upgrade forwarded MagicDNS queries to DoH when IP known

tstest/integration/vms/harness_test.go, tstest/integration/vms/nixos_test.go, tstest/integration/vms/vm_setup_test.go, tstest/integration/vms/vms_steps_test.go, tstest/integration/vms/vms_test.go
This paves the way for future MagicDNS tests.
=> tstest/integration/vms: use one testcontrol instance per VM

wgengine/magicsock/magicsock.go
This would have been useful during debugging yesterday.
=> wgengine/magicsock: add debug envvar to disable UDP

cmd/tailscaled/tailscaled.go, cmd/tailscaled/tailscaled_windows.go, ipn/ipnlocal/local.go, tstest/integration/integration_test.go
With this, I can now:
* install Tailscale
* stop the GUI
* net stop Tailscale
* net start Tailscale
* tailscale up --unattended
(where the middle three steps simulate what would happen on a Windows
Server Core machine without a GUI)
Fixes #2137
=> ipn/ipnlocal: fix 'tailscale up' on Windows without GUI

ipn/ipnlocal/local.go, util/deephash/deephash.go, util/deephash/deephash_test.go, wgengine/userspace.go
The fact that Hash returns a [sha256.Size]byte leaks details about
the underlying hash implementation. This could very well be any other
hashing algorithm with a possible different block size.
Abstract this implementation detail away by declaring an opaque type
that is comparable. While we are changing the signature of UpdateHash,
rename it to just Update to reduce stutter (e.g., deephash.Update).
=> util/deephash: make hash type opaque

safesocket/safesocket_darwin.go, safesocket/unixsocket.go, tstest/integration/integration_test.go
- tstest/integration: shorten test names
- safesocket: reduce log spam while running integration tests
- safesocket: print full lsof command on failure
=> tstest/integration: fix tests on darwin

cmd/tailscaled/tailscaled.go, cmd/tailscaled/tailscaled_windows.go, wgengine/router/router.go, wgengine/router/router_darwin.go, wgengine/router/router_default.go, wgengine/router/router_freebsd.go, wgengine/router/router_linux.go, wgengine/router/router_linux_test.go, wgengine/router/router_openbsd.go, wgengine/router/router_userspace_bsd.go, wgengine/router/router_windows.go
Prep for #1591 which will need to make Linux's router react to changes
that the link monitor observes.
The router package already depended on the monitor package
transitively. Now it's explicit.
=> wgengine/router: take a link monitor

logpolicy/logpolicy.go, tstest/integration/integration_test.go
Filch doesn't like having multiple processes competing
for the same log files (#937).
Parallel integration tests were all using the same log files.
Add a TS_LOGS_DIR env var that the integration test can use
to use separate log files per test.
Fixes #2269
=> tstest/integration: fix filch test flake

syncs/syncs.go, wgengine/monitor/monitor.go, wgengine/monitor/monitor_linux.go, wgengine/router/router_linux.go
=> wgengine/{monitor,router}: restore Linux ip rules when systemd deletes them

util/deephash/deephash.go, util/deephash/deephash_test.go
Prepend size to AppendTo output.
Fixes #2443
=> util/deephash: disambiguate hashing of AppendTo

tstest/integration/vms/nixos_test.go
cloud-init broke with the upgrade to python 3.9:
https://github.com/NixOS/nixpkgs/issues/131098
=> tstest/integration/vms: disable nixos unstable

tstest/integration/vms/distros.go
This prevents centos tests from timing out because sshd does reverse dns
lookups on every session being established instead of doing it once on
the acutal ssh connection being established. This is odd. Appending this
to the sshd config and restarting it seems to fix it though.
Depends on #2491
=> tstest/integration/vms: disable rDNS for sshd on centos

control/controlclient/debug.go, control/controlclient/debug_test.go
To reduce binary size on iOS.
Updates tailscale/corp#2238
=> control/controlclient: don't use regexp in goroutine stack scrubbing

net/portmapper/disabled_stubs.go, net/portmapper/upnp.go
=> net/portmapper: disable UPnP on iOS for now

tsweb/tsweb.go
A previously added metric which was float64 was being ignored in tsweb, because it previously
only accepted int64 and ints. It can be handled in the same way as ints.
Fixes: #2506
=> tsweb: add case for f64 in logging

net/tstun/wrap.go
The handoff between tstun.Wrap's Read and poll methods
is one of the per-packet hotspots. It shows up in pprof.
Making outbound buffered increases throughput.
It is hard to measure exactly how much, because the numbers
are highly variable, but I'd estimate it at about 1%,
using the best observed max throughput across three runs.
=> net/tstun: buffer outbound channel

net/dns/resolver/forwarder.go
I don't know how to get access to a real packet. Basing this commit
entirely off:
```
+------------+--------------+------------------------------+
| Field Name | Field Type   | Description                  |
+------------+--------------+------------------------------+
| NAME       | domain name  | MUST be 0 (root domain)      |
| TYPE       | u_int16_t    | OPT (41)                     |
| CLASS      | u_int16_t    | requestor's UDP payload size |
| TTL        | u_int32_t    | extended RCODE and flags     |
| RDLEN      | u_int16_t    | length of all RDATA          |
| RDATA      | octet stream | {attribute,value} pairs      |
+------------+--------------+------------------------------+
```
From https://datatracker.ietf.org/doc/html/rfc6891#section-6.1.2
Signed-off-by: David Crawshaw …
=> net/dns/resolver: EDNS OPT record off-by-one

cmd/tsshd/tsshd.go, go.mod, go.sum
The kr/pty module moved to creack/pty per the kr/pty README[1].
creack/pty brings in support for a number of OS/arch combos that
are lacking in kr/pty.
Run `go mod tidy` while here.
[1] https://github.com/kr/pty/blob/master/README.md
=> cmd/tsshd: switch from github.com/kr/pty to github.com/creack/pty

net/dns/resolver/tsdns_test.go
Go 1.17 switches to a register ABI on amd64 platforms.
Part of that switch is that go and defer calls use an argument-less
closure, which allocates. This means that we have an extra
alloc in some DNS work. That's unfortunate but not a showstopper,
and I don't see a clear path to fixing it.
The other performance benefits from the register ABI will all
but certainly outweigh this extra alloc.
Fixes #2545
=> net/dns/resolver: allow an extra alloc for go closure allocation

ipn/ipnlocal/local.go
Could be extended in the future to support Docker?
=> ipnlocal: allow windows to use guest VMs/containers while using an exit node

net/interfaces/interfaces.go, net/interfaces/interfaces_test.go, net/tsaddr/tsaddr.go, net/tsaddr/tsaddr_test.go
Signed-off-by: Matt Layher <mdlayher@gmail.com>
IsPrivate covers both the RFC1918 IPv4 ranges and the IPv6 ULA ranges, so the IsULA helper is no longer necessary.
=> net/tsaddr: remove IsULA, replace with netaddr.IP.IsPrivate

net/dns/manager_windows.go
=> net/dns: correct log message.

tstime/mono/mono.go, tstime/mono/mono_test.go
This was the proximate cause of #2579.
#2582 is a deeper fix, but this will remain
as a footgun, so may as well fix it too.
=> tstime/mono: make json.Unmarshal of a zero time.Time yield a zero Time

cmd/tailscaled/tailscaled.go
Without this, the integration tests fail locally for me:
```
--- FAIL: TestCollectPanic (7.61s)
integration.go:74: built [tailscale.com/cmd/tailscaled tailscale.com/cmd/tailscale] in 1.59s
integration_test.go:102: initial run: tailscaled requires root; use sudo tailscaled (or use --tun=userspace-networking)
integration_test.go:108: cleanup failed: exit status 1: "tailscaled requires root; use sudo tailscaled (or use --tun=userspace-networking)\n"
stuntest.go:64: STUN server shutdown
FAIL
FAIL	tailscale.com/tstest/integration	9.678s
FAIL
```
=> cmd/tailscaled: don't require root for --cleanup

net/portmapper/pcp.go, net/portmapper/pcp_test.go, net/portmapper/portmapper.go, net/portmapper/upnp.go
This adds PCP portmapping, moving all existing PCP content into a separate file, and parsing the
response from PCP portmapping requests. It hooks into the existing way we handle PMP mapping.
Tested this out on Denton's router, and seems to work fine, but would appreciate others also checking it out.
Also seems to work on pfSense on Brad's DO instance.
Updates #2563
=> net/portmapper: add pcp portmapping

scripts/installer.sh
Before we didn't detect it properly. Since Oracle Linux is diet centos,
we can just make the centos logic detect Oracle linux and everything
should be fine.
=> scripts/installer: work on Oracle Linux

net/dns/resolver/forwarder.go, net/dns/resolver/tsdns_server_test.go, net/dns/resolver/tsdns_test.go
Previously, we hashed the question and combined it with the original
txid which was useful when concurrent queries were multiplexed on a
single local source port. We encountered some situations where the DNS
server canonicalizes the question in the response (uppercase converted
to lowercase in this case). This includes a new test to cover that
situation.
Fixes #2597
=> net/dns/resolver: use forwarded dns txid directly

tsnet/tsnet.go
Set a TS_AUTHKEY environment variable to "tskey-01234..."
=> tsnet: add AuthKey support.

tsweb/tsweb.go, tsweb/tsweb_test.go
We want to use tsweb to format Prometheus-style metrics from
our temporary golang.org/x/net/http2 fork, but we don't want http2
to depend on the tailscale.com module to use the concrete type
tailscale.com/metrics.LabelMap. Instead, let a expvar.Map be used
instead of it's annotated sufficiently in its name.
=> tsweb: also support LabelMaps from expvar.Map, without metrics

net/portmapper/portmapper.go, net/portmapper/upnp.go, net/portmapper/upnp_test.go
This logs some basic statistics for UPnP, so that tailscale can better understand what routers
are being used and how to connect to them.
Would it be better to just log the body, and then parse it later to understand what types are where?
=> net/portmapper: log upnp information

cmd/tailscaled/tailscaled.go
Allows FreeBSD to function as an exit node in the same way
that Windows and Tailscaled-on-MacOS do.
Updates https://github.com/tailscale/tailscale/issues/2498
=> Use hybrid netstack mode for FreeBSD

Dockerfile
golang:1.16-alpine is kept updates as Alpine versions
advance, we can't specify an older release without having
it break at some point due to incompatibility.
Reported by @kubeworm
https://twitter.com/kubeworm/status/1426751941519020033
=> Dockerfile: use alpine:latest.

logtail/filch/filch.go, logtail/filch/filch_test.go
Scanning log lines is a frequent source of allocations.
Pre-allocate a re-usable buffer.
This still doesn't help when there are giant log lines.
Those will still be problematic from an iOS memory perspective.
For more on that, see https://github.com/tailscale/corp/issues/2423.
(For those who cannot follow that link, it is a discussion
of particular problematic types of log lines for
particular categories of customers. The "categories of customers"
part is the reason that it is a private issue.)
There is also a latent bug here. If we ever encounter
a log line longer than bufio.MaxScanTokenSize,
then bufio.Scan will return an error,
and we'll truncate the file and discard the rest of the log.
That's not good, but bufio.MaxScanTokenSize is really big,
so it probably doesn't matter much in …
=> logtail/filch: preallocate a scanner buffer

logtail/logtail.go, logtail/logtail_test.go
- logtail: always send a json array
- logtail: add a re-usable buffer for uploads
=> logtail: simplify, reduce allocations

control/controlclient/direct.go, ipn/ipnlocal/local.go, types/netmap/netmap.go
- control/controlclient: do not periodically print full netmap
- ipn/ipnlocal: log number of packet filters rather than entire filter
=> all: prevent common large log lines

control/controlclient/direct.go, control/controlclient/direct_test.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go
Signed-off-by: Simeng He <simeng@tailscale.com>
Additions to the PingRequest struct that will be used when initiating TSMP pings from Control.
An IP field is added for the IP that we are trying to Ping (TSMP)
A Types field is added for future specification of what types of Pings we want to run.
=> tailcfg: add IP and Types field to PingRequest

wgengine/router/router_linux.go, wgengine/router/runner.go
=> wgengine/router: pass in AmbientCaps when calling `ip rule`

wgengine/userspace.go
Two optimizations.
Use values instead of pointers.
We were using pointers to make track the "peer in progress" easier.
It's not too hard to do it manually, though.
Make two passes through the data, so that we can size our
return value accurately from the beginning.
This is cheap enough compared to the allocation,
which grows linearly in the number of peers,
that it is worth doing.
=> wgengine/userspace: reduce allocations in getStatus

wgengine/router/router_windows.go
Intended to help in resolving customer issue with
DNS caching.
We currently exec `ipconfig /flushdns` from two
places:
- SetDNS(), which logs before invoking
- here in router_windows, which doesn't
We'd like to see a positive indication in logs that flushdns
is being run.
As this log is expected to be spammy, it is proposed to
leave this in just long enough to do an unstable 1.13.x build
and then revert it. They won't run an unsigned image that
I build.
=> wgengine: actively log FlushDNS.

cmd/testcontrol/testcontrol.go, tstest/integration/testcontrol/testcontrol.go
This is useful for manual performance testing
of networks with many nodes.
I imagine it'll grow more knobs over time.
=> cmd/testcontrol: add test control server

wgengine/router/router_windows.go
This log is quite verbose, it was only to be left in for one
unstable build to help debug a user issue.
This reverts commit 1dd25520326f0adc1d37c12710c9f33c830a7ef5.
=> Revert "wgengine: actively log FlushDNS."

ipn/ipnlocal/local.go
Fixes #2641
`Hostinfo.RequestTags` was only being set on Start which meant that modifying `--advertise-tags` on a running instance would do nothing unless a `--reset` or `--force-reauth` was also supplied.
=> ipn/ipnlocal: update requested tags in host info

net/dns/direct.go
noideadog.gif
I don't know if this is right, but I think the wrong err was being read before.
I am also unsure how to test this in its current state, but I'm working on that separately!
=> net/dns: resolveConfExists reading the wrong error

api.md
Includes example POST body for input and example outputs for passing and failing tests.
=> Adding api documentation for acl validation endpoint

tsweb/tsweb.go
To be scraped in the Go expvar JSON format, as a string is involved.
For a future tool to record when processes restarted exactly, and at
what version.
=> tsweb: add vars for unix process start time and version

api.md
* The right web address for configuring API keys seems to have changed
* Minor clarification on how basic authentication works (it's illustrated in the examples later, but can't hurt to be precise)
=> Minor corrections to the API documentation

tstest/integration/testcontrol/testcontrol.go
Without this tailscaled does not know the DERP of a peer.
=> testcontrol: plumb through DERP

tstest/integration/vms/harness_test.go
Always succeeds. Its output clutters the log.
=> vms: make ssh-keygen quiet by default

net/dns/resolver/tsdns_test.go, net/tsaddr/tsaddr_test.go, net/tstun/wrap_test.go, tstime/mono/mono_test.go, tstime/tstime_test.go, wgengine/magicsock/magicsock_test.go, wgengine/userspace_test.go
This ensures that we can properly track and catch allocation
slippages that could otherwise have been missed.
Fixes #2748
=> all: add (*testing.B).ReportAllocs() to every benchmark

derp/derp_server.go, derp/derp_test.go, derp/dropreason_string.go
A public key should only have max one connection to a given
DERP node (or really: one connection to a node in a region).
But if people clone their machine keys (e.g. clone their VM, Raspbery
Pi SD card, etc), then we can get into a situation where a public key
is connected multiple times.
Originally, the DERP server handled this by just kicking out a prior
connections whenever a new one came. But this led to reconnect fights
where 2+ nodes were in hard loops trying to reconnect and kicking out
their peer.
Then a909d37a59f6e36f47209db4e6b16497715f8de9 tried to add rate
limiting to how often that dup-kicking can happen, but empirically it
just doesn't work and ~leaks a bunch of goroutines and TCP
connections, tying them up for hour+ while more and more accumulate
and waste memory. Mostly …
=> derp: accept dup clients without closing prior's connection

tstest/integration/testcontrol/testcontrol.go, tstest/integration/vms/dns_tester.go, tstest/integration/vms/harness_test.go, tstest/integration/vms/vms_test.go
This uses a neat little tool to dump the output of DNS queries to
standard out. This is the first end-to-end test of DNS that runs against
actual linux systems. The /etc/resolv.conf test may look superflous,
however this will help for correlating system state if one of the DNS
tests fails.
Depends on #2491 and #2492
=> tstest/integration/vms: test DNS configuration

tstest/integration/vms/derive_bindhost_test.go, tstest/integration/vms/distros_test.go, tstest/integration/vms/harness_test.go, tstest/integration/vms/nixos_test.go, tstest/integration/vms/opensuse_leap_15_1_test.go, tstest/integration/vms/top_level_test.go, tstest/integration/vms/vm_setup_test.go, tstest/integration/vms/vms_steps_test.go, tstest/integration/vms/vms_test.go
The tests build fine off linux, they just can't run on other OSs.
But there is already a t.Skip by default, so `go test` ends up
working fine elsewhere and checks the code compiles.
=> tstest/integration/vms: change build tag restriction

tsweb/debug.go, tsweb/debug_test.go
It was accidentally deleted in the earlier 0022c3d2e (#2143) refactor.
Lock it in with a test.
Fixes tailscale/corp#2503
=> tsweb: restore CPU profiling handler

health/health.go, ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go, wgengine/magicsock/magicsock.go
And add health check errors to ipnstate.Status (tailscale status --json).
Updates #2746
Updates #2775
=> wgengine/magicsock, health, ipn/ipnstate: track DERP-advertised health

tstest/integration/testcontrol/testcontrol.go
I have seen this once in the VM test (caused by an EOF, I believe on
shutdown) that didn't need to cause the test to fail.
=> testcontrol: replace panic with error

.github/workflows/cross-darwin.yml, .github/workflows/cross-freebsd.yml, .github/workflows/cross-openbsd.yml, .github/workflows/cross-windows.yml, .github/workflows/depaware.yml, .github/workflows/go_generate.yml, .github/workflows/license.yml, .github/workflows/linux-race.yml, .github/workflows/linux.yml, .github/workflows/linux32.yml, .github/workflows/staticcheck.yml, .github/workflows/windows-race.yml, .github/workflows/windows.yml, Dockerfile, README.md, go.mod
In prep for using 1.17 features.
Note the go.mod changes are due to:
https://golang.org/doc/go1.17#go-command
=> all: bump minimum Go to 1.17

wgengine/wglog/wglog.go
@danderson linked this on Twitter and I noticed the mismatch.
=> Fix docstring on wireguardGoString to match args

hostinfo/hostinfo_freebsd.go, version/distro/distro.go
Add specific handling for common appliances based on FreeBSD:
- pfSense
HostInfo: {"OS":"freebsd","OSVersion":"pfSense 2.5.2-RELEASE; version=12.2-STABLE"
- OPNsense
HostInfo: {"OS":"freebsd","OSVersion":"OPNsense 21.7.1 (amd64/OpenSSL); version=12.1-RELEASE-p19-HBSD"
- TrueNAS
HostInfo: {"OS":"freebsd","OSVersion":"TrueNAS-12.0-U5.1 (6c639bd48a); version=12.2-RELEASE-p9"
- FreeNAS
HostInfo: {"OS":"freebsd","OSVersion":"FreeNAS-11.3-U5 (2e4ded5a0a); version=11.3-RELEASE-p14",
- regular FreeBSD
HostInfo: {"OS":"freebsd","OSVersion":"FreeBSD; version=12.2-RELEASE"
=> hostinfo: add FreeBSD support.

cmd/tailscale/cli/cli_test.go, ipn/ipnlocal/peerapi_test.go, net/dns/manager_linux_test.go, net/portmapper/upnp_test.go, tstest/log.go, wgengine/magicsock/magicsock_test.go
And give MemLogger a mutex, as one caller had, which does match the logf
contract better.
=> all: update tests to use tstest.MemLogger

cmd/derper/cert.go, cmd/derper/derper.go
In #2619, @hronro asked if users could provide an certificate by themself, instead of using the automatically retrieved one via Let's Encrypt.
This pull request adds a new "-certmode" argument for control certificate source. Default argument "letsencrypt" would keep the old behaviour. 
In "manual" mode, certs are searched in given "-certdir" argument. The filename being searched is decided by HTTPS request's SNI field, and in format `${certdir}/${hostname}.{crt/key}`. If cert can not be loaded on start, error is thrown.
Solves #2619 and #2794
Signed-off-by: SilverBut <SilverBut@users.noreply.github.com>
=> cmd/derper: support customized server certificate

cmd/tailscaled/tailscaled.go, net/netns/netns.go
The earlier 382b349c54ed38bbc4d2936a8c9de6cc2f905eb8 was too late,
as engine creation itself needed to listen on things.
Fixes #2827
Updates #2822
=> cmd/tailscaled: disable netns earlier in userspace-networking mode

portlist/portlist_linux.go, portlist/portlist_linux_test.go
```
name         old time/op    new time/op    delta
ListPorts-6    1.18ms ± 5%    1.16ms ± 5%     ~     (p=0.075 n=10+10)
name         old alloc/op   new alloc/op   delta
ListPorts-6    27.2kB ± 0%    14.9kB ± 0%  -45.14%  (p=0.001 n=8+9)
name         old allocs/op  new allocs/op  delta
ListPorts-6      90.0 ± 0%      84.0 ± 0%   -6.67%  (p=0.000 n=10+10)
```
Updates tailscale/corp#2566
=> portlist: reuse bufio.Reader between files

cmd/derper/derper.go, cmd/derper/derper_test.go
Real goal is to eliminate some allocs in the STUN path, but that requires
work in the standard library.
For now this just adds a benchmark.
=> cmd/derper: refactor STUN path for testing, add serverSTUN benchmark

derp/derp_test.go
On about 1 out of 500 runs, TestSendFreeze failed:
derp_test.go:416: bob: unexpected message type derp.PeerGoneMessage
Closing alice before bob created a race.
If bob closed promptly, the test passed.
If bob closed slowly, and alice's disappearance caused
bob to receive a PeerGoneMessage before closing, the test failed.
Deflake the test by closing bob first.
With this fix, the test passed 12,000 times locally.
Fixes #2668
=> derp: deflake TestSendFreeze

portlist/portlist_macos.go
These "weird" port lines show up in logs frequently.
They're the result of uninteresting races,
and they're not actionable. Remove the noise.
=> portlist: stop logging stray UDP ports

control/controlclient/client.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/loglines_test.go, ipn/ipnlocal/state_test.go, ipn/ipnserver/server_test.go, wgengine/userspace_test.go, wgengine/watchdog_test.go
- all: close fake userspace engines when tests complete
- ipn/ipnlocal: add failing test
- control/controlclient: replace TODO with explanation
- ipn/ipnlocal: only call UpdateEndpoints when the endpoints change
- ipn/ipnlocal: use a switch statement instead of an else-if chain
- ipn/ipnlocal: inline LocalBackend.getEngineStatus
- ipn/ipnlocal: add LocalBackend.broadcastStatusChanged
=> ipn/ipnlocal: add failing test, reduce UpdateEndpoints calls, start concurrency work

ipn/ipnlocal/local.go
- Revert "ipn/ipnlocal: remove locks around sync.Cond.Broadcast call"
- ipn/ipnlocal: add LocalBackend.broadcastStatusChanged
=> ipnlocal: fix sync.Cond-related test flakiness

ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go, wgengine/magicsock/magicsock_test.go
- ipn/ipnlocal: reduce line noise in tests
- ipn/ipnlocal: fix minor typo in comment
- ipn/ipnlocal: do not shut down the backend halfway through TestStateMachine
- wgengine/magicsock: skip alloc test with -race
=> ipn/ipnlocal: minor cleanup

cmd/cloner/cloner.go, ipn/prefs_clone.go, tailcfg/tailcfg_clone.go, types/dnstype/dnstype_clone.go, types/persist/persist_clone.go, util/codegen/codegen.go, wgengine/filter/match_clone.go, wgengine/wgcfg/clone.go
- util/codegen: add package
- util/codegen: add AssertStructUnchanged
- cmd/cloner: add Clone context to regen struct assignments
- cmd/cloner: simplify code
- cmd/cloner: delete some debug code
- util/codegen: add NamedTypes
- cmd/cloner: unify switch cases
- util/codegen: add ContainsPointers
=> util/codegen, cmd/cloner: organize and simplify cloner

control/controlclient/map.go, health/health.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go, types/netmap/netmap.go
So if the control plane knows that something's broken about the node, it can
include problem(s) in MapResponse and "tailscale status" will show it.
(and GUIs in the future, as it's in ipnstate.Status/JSON)
This also bumps the MapRequest.Version, though it's not strictly
required. Doesn't hurt.
=> tailcfg, health: add way for control plane to add problems to health check

ipn/ipnserver/server.go, log/filelogger/log.go, logpolicy/logpolicy.go, paths/migrate.go, paths/paths.go
ipn/ipnserver: move Windows state to ProgramData
C:\WINDOWS\system32\config\systemprofile\AppData\Local\
is frequently cleared for almost any reason: Windows updates,
System Restore, even various System Cleaner utilities.
The server-state.conf file in AppData\Local could be deleted
at any time, which would break login until the node is removed
from the Admin Panel allowing it to create a new key.
Carefully copy any AppData state to ProgramData at startup.
If copying the state fails, continue to use AppData so at
least there will be connectivity. If there is no state,
use ProgramData.
We also migrate the log.conf file. Very old versions of
Tailscale named the EXE tailscale-ipn, so the log conf was
tailscale-ipn.log.conf and more recent versions preserved
this filename and cmdName in logs. …
=> cmd/tailscaled: move Windows state to ProgramData

net/dns/flush_default.go, net/dns/flush_windows.go, net/dns/manager.go, wgengine/userspace.go
Fixes https://github.com/tailscale/tailscale/issues/2132
=> wgengine: flush DNS cache after major link change.

version/cmdname.go, version/modinfo_test.go
Don't return "wg64", "wg32", etc.
=> version: fix CmdName on the tailscale-ipn.exe binary

ipn/ipnserver/server.go, logpolicy/logpolicy.go, paths/migrate.go
tailscale-ipn.exe (the GUI) shouldn't use C:\ProgramData.
Also, migrate the earlier misnamed wg32/wg64 conf files if they're present.
(That was stopped in 2db877caa332c8968ee1b1eb08ef40a219ff3eec, but the
files exist from fresh 1.14 installs)
Updates #2856
=> logpolicy: don't use C:\ProgramData use for tailscale-ipn GUI's log dir

ipn/message.go
I believe this check was added when we were debugging the zero-bytes corruption on Windows, so I don't expect it to trigger again. I could also remove the 0b checks altogether?
=> ipn: don't log IPN messages that may contain an authkey.

cmd/tailscaled/debug.go
There are two reasons this can't ever go to actual logs,
but rewrite it to make it happy.
Fixes tailscale/corp#2695
=> cmd/tailscaled: appease a security scanner

.github/workflows/vm.yml
In a56520c3c7f12c2d060f7ce9b561142af1dbc5c4 dependabot attempted to bump
the setup-go action version. It appears to work for most builders, but
not the self-hosted VM builder. Revert for now.
=> .github: revert dependabot change for vm builder

net/tstun/wrap.go, net/tstun/wrap_test.go
It was in the wrong filter direction before, per CPU profiles
we now have.
Updates #1526 (maybe fixes? time will tell)
=> net/tstun: block looped disco traffic, take 17

net/dns/resolver/forwarder.go
DNSSEC is an availability issue, as recently demonstrated by the
Slack issue, with limited security advantage. DoH on the other hand
is a critical security upgrade. This change adds DoH support for the
non-DNSSEC endpoints of Quad9.
https://www.quad9.net/service/service-addresses-and-features#unsec
=> net/dns/resolver: add unsecured Quad9 resolvers

derp/derphttp/derphttp_client.go, go.mod, go.sum, net/dnsfallback/dnsfallback.go, net/tlsdial/tlsdial.go, net/tlsdial/tlsdial_test.go
We still try the host's x509 roots first, but if that fails (like if
the host is old), we fall back to using LetsEncrypt's root and
retrying with that.
tlsdial was used in the three main places: logs, control, DERP. But it
was missing in dnsfallback. So added it there too, so we can run fine
now on a machine with no DNS config and no root CAs configured.
Also, move SSLKEYLOGFILE support out of DERP. tlsdial is the logical place
for that support.
Fixes #1609
=> net/tlsdial: bake in LetsEncrypt's ISRG Root X1 root

client/tailscale/tailscale.go, cmd/tailscale/cli/cert.go
Lot of people have been hitting this.
Now it says:
$ tailscale cert tsdev.corp.ts.net
Access denied: cert access denied
Use 'sudo tailscale cert' or 'tailscale up --operator=$USER' to not require root.
=> cmd/tailscale: make cert subcommand give hints on access denied

.bencher/config.yaml
This config update will let tailscale use bencher without worrying about the bencher check appearing as failed due to a benchmark regressing.
Updates #2938
Signed-off-by: Nathan Dias <nathan@orijtech.com>
=> bencher: add config to suppress failures on benchmark regressions.

ipn/ipnlocal/local.go
The new frontends are better for battery.
Updates #2442
Updates tailscale/corp#2750
=> ipn/ipnlocal: make sure mobile clients don't use the old control server URL

ipn/ipnlocal/dnsconfig_test.go, ipn/ipnlocal/local.go, net/tsaddr/tsaddr.go
See https://github.com/tailscale/tailscale/issues/2970#issuecomment-931885268
=> ipn/ipnlocal: for IPv6-only nodes, publish IPv6 MagicDNS records of peers

hostinfo/hostinfo.go, ipn/ipnlocal/local.go, ipn/prefs.go
Turns out the iOS client has been only sending the OS version it first
started at. This whole hostinfo-via-prefs mechanism was never a good idea.
Start removing it.
=> hostinfo: add SetOSVersion like SetDeviceModel, deprecate ipn.Prefs way

ipn/ipnlocal/local.go, ipn/prefs.go, ipn/prefs_clone.go, ipn/prefs_test.go
iOS and Android no longer use these. They both now (as of today)
use the hostinfo.SetFoo setters instead.
=> ipn: remove unused Prefs.OSVersion and Prefs.DeviceModel

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/pendopen.go, wgengine/userspace.go, wgengine/userspace_test.go
=> wgengine/magicsock: use key.NodePublic instead of tailcfg.NodeKey.

wgengine/userspace.go, wgengine/userspace_test.go
=> wgengine: use key.NodePublic instead of tailcfg.NodeKey.

control/controlclient/direct.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tstest/integration/integration_test.go, tstest/integration/testcontrol/testcontrol.go, types/netmap/netmap_test.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/pendopen.go, wgengine/userspace.go, wgengine/userspace_test.go, wgengine/wgcfg/nmcfg/nmcfg.go
=> tailcfg: use key.NodePublic in wire protocol types.

Dockerfile, Makefile
Add multi-arch image build target. 
It uses docker buildx capability to build a single image for multi-arch image support. 
We are developing native tailscale support for our project (https://synpse.net) and would be good to have something like this in master branch :)
=> Add multi-arch image make target

control/controlclient/client.go, control/controlclient/direct.go, ipn/ipnlocal/local.go
Fixes regression from 81cabf48ec1f0d306f7dcf0c8a58a6eae6594c76 which made
all map errors be sent to the frontend UI.
Fixes #3230
=> ipn/ipnlocal, control/controlclient: don't propagate all map errors to UI

cmd/tailscaled/tailscaled.go, cmd/tailscaled/tailscaled_windows.go, ipn/ipnserver/server.go, ipn/ipnserver/server_test.go
More work towards removing the massive ipnserver.Run and ipnserver.Options
and making composable pieces.
Work remains. (The getEngine retry loop on Windows complicates things.)
For now some duplicate code exists. Once the Windows side is fixed
to either not need the retry loop or to move the retry loop into a
custom wgengine.Engine wrapper, then we can unify tailscaled_windows.go
too.
=> cmd/tailscaled, ipn/ipnserver: refactor ipnserver

net/interfaces/interfaces_windows.go, tsconst/interface.go
With wintun 0.14, we end up binding to the wrong default interface. This is likely related to the new installation mechanism which probably also changed the naming of the tunnel. We are looking for `Tailscale Tunnel` in the description, but now it's `Wintun Userspace Tunnel #24`. 
Fixes #3260
=> net/interfaces/windows: update Tailscale interface detection logic to account for new wintun naming.

tstest/integration/testcontrol/testcontrol.go
Fix race from 1ec99e99f4e701fa1b9edef9eb0fbe022c5efebd
Fixes #3289
=> tstest/integration/testcontrol: fix data race

client/tailscale/tailscale.go, cmd/tailscale/cli/debug.go
To let users inspect the tailscaled metrics easily.
Updates #3307
=> cmd/tailscale/cli: add "debug metrics" subcommand

wgengine/magicsock/magicsock_test.go
I believe that this should eliminate the flakiness.
If GitHub CI manages to be even slower that can be believed
(and I can believe a lot at this point),
then we should roll this back and make some more invasive changes.
Updates #654
Fixes #3247 (I hope)
=> wgengine/magicsock: increase TestDiscokeyChange connection timeout

wgengine/magicsock/magicsock_test.go
And add a peerMap validate method that checks its internal invariants.
Updates tailscale/corp#3016
Change-Id: I23708e68ed44d81986d9e2be82029d4555547592
=> wgengine/magicsock: add a stress test

wgengine/router/router_linux.go
Tailscale 1.18 uses netlink instead of the "ip" command to program the
Linux kernel.
The old way was kept primarily for tests, but this also adds a
TS_DEBUG_USE_IP_COMMAND environment knob to force the old way
temporarily for debugging anybody who might have problems with the
new way in 1.18.
Updates #391
=> wgengine/router: add debug knob to resort to Linux "ip" command usage

cmd/tailscaled/tailscaled_windows.go, log/filelogger/log.go, log/filelogger/log_test.go
At some point since filelogger was added on Windows, the log hierarchy
above it changed such that a log.Printf writes to filelogger and includes
the log package's own date. But then filelogger adds another.
Rather than debug everything above and risk removing the prefix when
run by tailscaled, instead just remove the log package's prefix
very late right before we go to add the filelogger's own.
=> log/filelogger: make filelogger remove redundant date before adding a date

wgengine/wgcfg/clone.go, wgengine/wgcfg/config.go, wgengine/wgcfg/device.go, wgengine/wgcfg/device_test.go, wgengine/wgcfg/parser.go, wgengine/wgcfg/parser_test.go, wgengine/wgcfg/writer.go
In rare circumstances (tailscale/corp#3016), the PublicKey
and Endpoints can diverge.
This by itself doesn't cause any harm, but our early exit
in response did, because it prevented us from recovering from it.
Remove the early exit.
=> wgengine/wgcfg: recover from mismatched PublicKey/Endpoints

wgengine/router/router_linux.go, wgengine/router/router_linux_test.go
Updates #3358 (should fix it)
Updates #391
=> wgengine/router: fix checkIPRuleSupportsV6 to actually use IPv6

.github/workflows/cifuzz.yml
Adds CIFuzz. This will run Tailscales fuzzers for 600 seconds in the CI when a pull request is made. The time can be changed.
Documentation of CIFuzz can be found here: https://google.github.io/oss-fuzz/getting-started/continuous-integration/
This is a service offered by OSS-fuzz to help catch bugs before they are merged as well as check if a pull request will break the fuzzers.
=> fuzzing: Add CIFuzz

cmd/derper/derper.go
Starting with a short lifetime, to verify nothing breaks.
Updates #3373
=> cmd/derper: enable HSTS when serving over HTTPS.

wgengine/router/router_linux_test.go
=> wgengine/router: demote TestDebugListRules fail to skip

Dockerfile, Dockerfile.base, Makefile, build_dist.sh, build_docker.sh
We recently added support for building cross platform docker containers using `docker buildx`. However, docker does cross platform builds by emulating the target arch using qemu. That is obviously very slow to build and consumes 100% of the cpu, and when run on `arm64` machines has a tendency to fail completely.
This in contrast, is a small go binary which uses `GOOS= GOARCH= go build` directly to compile the binaries and then uses [google/go-containerregistry](https://github.com/google/go-containerregistry) to create and publish the new containers based on the desired platform.
This does introduce an extra step to generate a base alpine image, however the base image is going to change less frequently than our code so I think the extra step is ok.
Signed-off-by: Maisem Ali …
=> build_docker.sh: use `github.com/tailscale/mkctr` instead of docker

cmd/derper/derper.go
=> cmd/derper: increase HSTS cache lifetime to 2 years.

net/tshttpproxy/tshttpproxy_windows.go
The Windows BOOL type is an int32. We were using a bool,
which is a one byte wide. This could be responsible for the
ERROR_INVALID_PARAMETER errors we were seeing for calls to
WinHttpGetProxyForUrl.
We manually checked all other existing Windows syscalls
for similar mistakes and did not find any.
Updates #879
Co-authored-by: Aaron Klotz <aaron@tailscale.com>
=> net/tshttpproxy: use correct size for Windows BOOL argument

.github/workflows/linux-race.yml, .github/workflows/linux.yml, .github/workflows/linux32.yml
Linux-only for now, to avoid having to figure out why
powershell doesn't like my shell scripting. (Not that I blame it.)
That'll be enough to catch most regressions.
Fixes #1083
Co-authored-by: Aaron Klotz <aaron@tailscale.com>
=> .github/workflows: check that repo is clean after build and test

net/interfaces/interfaces.go, net/interfaces/interfaces_test.go, wgengine/monitor/monitor.go, wgengine/monitor/polling.go
One of the most common "unexpected" log lines is:
"network state changed, but stringification didn't"
One way that this can occur is if an interesting interface
(non-Tailscale, has interesting IP address)
gains or loses an uninteresting IP address (link local or loopback).
The fact that the interface is interesting is enough for EqualFiltered
to inspect it. The fact that an IP address changed is enough for
EqualFiltered to declare that the interfaces are not equal.
But the State.String method reasonably declines to print any
uninteresting IP addresses. As a result, the network state appears
to have changed, but the stringification did not.
The String method is correct; nothing interesting happened.
This change fixes this by adding an IP address filter to EqualFiltered
in addition to the …
=> wgengine/monitor: ignore adding/removing uninteresting IPs

cmd/tsshd/tsshd.go
There was a bug where the code ended up doing:
```go
s.Exit(1)
s.Exit(0)
```
(SSH session `Exit()` is not same as `os.Exit()` which would not continue running the code)
=> tsshd: fix double exit with different exit codes

ipn/ipnlocal/local.go
We were missing an argument here.
Also, switch to %q, in case anything weird
is happening with these strings.
Updates tailscale/corp#461
=> ipn/ipnlocal: fix logging

net/dns/direct.go, net/dns/direct_test.go
Currently, comments in resolv.conf cause our parser to fail,
with error messages like:
ParseIP("192.168.0.100 # comment"): unexpected character (at " # comment")
Fix that.
Noticed while looking through logs.
=> net/dns: handle comments in resolv.conf

ipn/ipnlocal/local.go
If IP forwarding is disabled globally, but enabled per-interface on all interfaces,
don't complain. If only some interfaces have forwarding enabled, warn that some
subnet routing/exit node traffic may not work.
Fixes #1586
=> ipn/ipnlocal: warn more precisely about IP forwarding issues on linux.

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi.go, ipn/ipnlocal/peerapi_test.go, wgengine/filter/filter.go, wgengine/filter/filter_test.go
Don't be a DoH DNS server to peers unless the Tailnet admin has permitted
that peer autogroup:internet access.
Updates #1713
=> ipn/ipnlocal: restrict exit node DoH server based on ACL'ed packet filter

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go
=> cmd/tailscale/cli: don't complain about --accept-routes true->false on Synology

control/controlclient/auto.go
This isn't the ideal solution, but it's good enough for now.
=> control/controlclient: stop logging about goal.url invariant

client/tailscale/tailscale.go, cmd/tailscale/cli/file.go, ipn/localapi/localapi.go
So Taildrop sends work even if the local tailscaled is running in
netstack mode, as it often is on Synology, etc.
Updates #2179 (which is primarily about receiving, but both important)
=> cmd/tailscale: make file cp send files via tailscaled localapi

net/socks5/tssocks/tssocks.go, wgengine/pendopen.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
=> net/socks5/tssocks, wgengine: permit SOCKS through subnet routers/exit nodes

net/nettest/pipe.go, net/nettest/pipe_test.go
The block-write and block-read tests are both flaky,
because each assumes it can get a normal read/write
completed within 10ms. This isn’t always true.
We can’t increase the timeouts, because that slows down the test.
However, we don’t need to issue a regular read/write for this test.
The immediately preceding tests already test this code,
using a far more generous timeout.
Remove the extraneous read/write.
This drops the failure rate from 1 per 20,000 to undetectable
on my machine.
While we’re here, fix a typo in a debug print statement.
=> net/nettest: deflake TestPipeTimeout

net/dns/utf.go, net/dns/utf_test.go, net/dns/wsl_windows.go
=> net/dns: detect and decode UTF-16 from wsl.exe earlier.

net/portmapper/igd_test.go
Logging in goroutines after the test completed
caused data races and panics. Prevent that.
=> net/portmapper: deflake TestPCPIntegration

wgengine/monitor/monitor.go
The behavior was changed in March (in 7f174e84e627dc04bc91352e9897f22cf4724191)
but that change forgot to update these docs.
=> wgengine/monitor: fix docs on Mon.InterfaceState

control/noise/handshake_test.go
Close the server and client.
Without this, we leak system threads.
=> control/noise: clean up resources in TestNoReuse

ipn/ipnlocal/local.go
Without this, enabling an exit node immediately blackholes all traffic,
but doesn't correctly let it flow to the exit node until the next netmap
update.
Fixes #3447
=> ipn/ipnlocal: resolve exit node IP to ID at EditPrefs time.

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi.go, ipn/ipnlocal/peerapi_test.go
(prep for Synology Taildrop recv)
=> ipn/ipnlocal: run peerapi even if Taildrop storage not configured

cmd/tailscaled/tailscaled.go, cmd/tailscaled/tailscaled_windows.go, ipn/ipnlocal/local.go, ipn/ipnserver/server.go, ipn/ipnserver/server_test.go, net/tsdial/dnsmap.go, net/tsdial/dnsmap_test.go, net/tsdial/tsdial.go, tsnet/tsnet.go, wgengine/netstack/netstack.go
This starts to refactor tsdial.Dialer's name resolution to have
different stages: in-memory MagicDNS vs system resolution. A future
change will plug in ExitDNS resolution.
This also plumbs a Dialer into netstack and unexports the dnsMap
internals.
And it removes some of the async AddNetworkMapCallback usage and
replaces it with synchronous updates of the Dialer's netmap
from LocalBackend, since the LocalBackend has the Dialer too.
Updates #3475
=> net/tsdial: give netstack a Dialer, start refactoring name resolution

cmd/tailscale/cli/up.go
=> cmd/tailscale: clarify which prefless flags don't need revert protection

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go
It was using the wrong prefs (intended vs current) to map the current
exit node ID to an IP.
Fixes #3480
=> cmd/tailscale: fix setting revert checker's finding an exit node

cmd/tailscale/cli/diag.go
Before:
failed to connect to local tailscaled (which appears to be running). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": EOF
After:
failed to connect to local tailscaled (which appears to be running as IPNExtension, pid 2118). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": EOF
This was useful just now, as it made it clear that tailscaled I thought
I was connecting to might not in fact be running; there was
a second tailscaled running that made the error message slightly misleading.
=> cmd/tailscale: print more detail in connection failure error message

ipn/policy/policy.go
The control plane is currently still eating it.
Updates #1713
=> ipn/policy: treat DNS service as interesting so it's not filtered out

cmd/tailscaled/tailscaled.go, ipn/ipnlocal/local.go, net/tsdial/dohclient.go, net/tsdial/dohclient_test.go, net/tsdial/tsdial.go, tsnet/tsnet.go, wgengine/netstack/netstack.go
And simplify, unexport some tsdial/netstack stuff in the the process.
Fixes #3475
=> ipn/ipnlocal, net/tsdial: make SOCKS/HTTP dials use ExitDNS

wgengine/monitor/monitor_freebsd.go, wgengine/monitor/polling.go
Since devd apparently can't be made to work in a FreeBSD jail
fall back to polling.
Fixes tailscale#2858
=> support running in a FreeBSD jail

.github/dependabot.yml
So we can mass-process updates once now, then turn it off.
=> .github/dependabot.yml: make dependabot send all the updates right now.

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi.go, ipn/ipnserver/server.go
If the user has a "Taildrop" shared folder on startup and
the "tailscale" system user has read/write access to it,
then the user can "tailscale file cp" to their NAS.
Updates #2179 (would be fixes, but not super ideal/easy yet)
=> ipn/{ipnserver,ipnlocal}: support incoming Taildrop on Synology

ipn/ipnlocal/local.go, ipn/ipnserver/server.go, version/distro/distro.go
I was experimenting with TrueNAS for another reason and happened to see Brad's change to add this support for dropping files directly to Synology store.  This implements the same feature for TrueNAS.  I don't feel strongly about it and may not be using TrueNAS much in the future, but figured I'd mail the change in case it was wanted.  This was tested on both FreeBSD TrueNAS Core and Debian/Linux TrueNAS Scale.
=> Support "Taildrop" on TrueNAS

.github/dependabot.yml
Given our development cycle, we'll instead do big-bang updates
after every release, to give time for all the updates to soak in
unstable.
This does _not_ disable dependabot security-critical PRs.
=> .github/dependabot.yml: disable eager updates for Go.

ipn/ipnlocal/dnsconfig_test.go, ipn/ipnlocal/local.go, wgengine/router/callback.go, wgengine/userspace.go
Allow users of CallbackRouter to supply a GetBaseConfig
implementation. This is expected to be used on Android,
which currently lacks both a) platform support for
Split-DNS and b) a way to retrieve the current DNS
servers.
iOS/macOS also use the CallbackRouter but have platform
support for SplitDNS, so don't need getBaseConfig.
Updates https://github.com/tailscale/tailscale/issues/2116
Updates https://github.com/tailscale/tailscale/issues/988
=> net/dns: add GetBaseConfig to CallbackRouter.

ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go, wgengine/magicsock/magicsock.go
It's been a bunch of releases now since the TailscaleIPs slice
replacement was added.
=> ipn/ipnstate: remove old deprecated TailAddr IPv4-only field

client/tailscale/tailscale.go, cmd/tailscale/cli/cli.go, ipn/ipnserver/server_test.go, safesocket/basic_test.go, safesocket/pipe_windows.go, safesocket/safesocket.go, safesocket/safesocket_js.go, safesocket/safesocket_ps.go, safesocket/unixsocket.go, tstest/integration/integration_test.go
- all: minor code cleanup
- tstest/integration: fix running with -verbose-tailscale
- safesocket: let callers control whether to dial IPNExtension as a fallback
=> tstest/integration: allow tests to pass on machines also running the macOS GUI

wgengine/router/router_windows.go
While debugging a customer issue where the firewallTweaker was failing
the only message we have is `router: firewall: error adding
Tailscale-Process rule: exit status 1` which is not really helpful.
This will hopefully help diagnose the failure.
=> wgengine/router{windows}: return the output from the firewallTweaker on error

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go
One of the most annoying parts of using the Tailscale CLI on Windows
and the macOS GUI is that Tailscale's GUIs default to running with
"Route All" (accept all non-exitnode subnet routes) but the CLI--being
originally for Linux--uses the Linux default, which is to not accept
subnets.
Which means if a Windows user does, e.g.:
tailscale up --advertise-exit-node
Or:
tailscale up --shields-up
... then it'd warn about reverting the --accept-routes option, which the user
never explicitly used.
Instead, make the CLI's default match the platform/GUI's default.
=> cmd/tailscale: make --accept-routes default true on Windows, macOS GUI

tstest/integration/integration.go, tstest/integration/integration_test.go, tstest/integration/vms/harness_test.go, tstest/integration/vms/nixos_test.go, tstest/integration/vms/vm_setup_test.go, tstest/integration/vms/vms_test.go
The existing code relied on the Go build cache to avoid
needless work when obtaining the tailscale binaries.
For non-obvious reasons, the binaries were getting re-linked
every time, which added 600ms or so on my machine to every test.
Instead, build the binaries exactly once, before doing anything else.
This reduces the time to run 'go test -count=5' from 34s to 10s
on my machine.
=> tstest/integration: build binaries only once

cmd/tailscaled/tailscaled_windows.go
I broke it in 1.17.x sometime while rewiring some logs stuff,
mostly in 0653efb092be5fec2daa723231e4de1a31ccf4b0 (but with a handful
of logs-related changes around that time)
Fixes tailscale/corp#3265
=> cmd/tailscaled: fix windows logtail integration

ipn/ipnlocal/local.go, tstest/integration/integration_test.go, wgengine/netstack/netstack.go
- tstest/integration: make -verbose-tailscaled pass -verbose=2 to tailscaled
- ipn/ipnlocal: clear magicsock's netmap on logout
=> ipn/ipnlocal: clear magicsock's netmap on logout

health/health.go, ipn/ipnlocal/local.go
One option was to just hide "offline" in the text output, but that
doesn't fix the JSON output.
The next option was to lie and say it's online in the JSON (which then
fixes the "offline" in the text output).
But instead, this sets the self node's "Online" to whether we're in an
active map poll.
Fixes #3564
=> ipn/ipnlocal, health: populate self node's Online bit in tailscale status

cmd/tailscale/cli/ping.go, cmd/tailscale/cli/status.go
Refactor out the pretty status printing code from status, use it in ping.
Fixes #3549
=> cmd/tailscale: improve ping error message when logged out

scripts/installer.sh
fix error: 'sh: 411: APT_SYSTEMCTL_START: parameter not set' on certain debian distributions
=> scripts/installer.sh fix APT_SYSTEMCTL_START error

wgengine/magicsock/magicsock.go
We only tracked the transport type (UDP vs DERP), not what they were.
=> wgengine/magicsock: add metrics for sent disco messages

derp/derp_client.go, derp/derp_server.go, derp/derp_test.go, derp/derphttp/derphttp_client.go
In prep for a future change to have client ping derp connections
when their state is questionable, rather than aggressively tearing
them down and doing a heavy reconnect when their state is unknown.
We already support ping/pong in the other direction (servers probing
clients) so we already had the two frame types, but I'd never finished
this direction.
Updates #3619
=> derp: support client->server ping (and server->client pong)

net/dns/direct.go
=> net/dns: bound time we wait on restarting systemd-resolved in another place

derp/derp_client.go, derp/derp_server.go
So magicsock can later ask a DERP connection whether its source IP
would've changed if it reconnected.
Updates #3619
=> derp: add Client.LocalAddr method

client/tailscale/tailscale.go, cmd/tailscale/cli/debug.go
=> cmd/tailscale: add debug restun, rebind subcommands

net/interfaces/interfaces.go, net/interfaces/interfaces_darwin.go, net/interfaces/interfaces_defaultrouteif_todo.go, net/interfaces/interfaces_linux.go, net/interfaces/interfaces_test.go, net/interfaces/interfaces_windows.go
It was pretty ill-defined before and mostly for logging. But I wanted
to start depending on it, so define what it is and make Windows match
the other operating systems, without losing the log output we had
before. (and add tests for that)
=> net/interfaces: define DefaultRouteInterface and State.DefaultRouteInterface

derp/derphttp/derphttp_client.go, net/tsaddr/tsaddr.go, wgengine/magicsock/magicsock.go
Only if the source address isn't on the currently active interface or
a ping of the DERP server fails.
Updates #3619
=> wgengine/magicsock: don't unconditionally close DERP connections on rebind

build_dist.sh, build_docker.sh, tool/go
Also update build_dist.sh and build_docker.sh to use the wrapper.
Updates tailscale/corp#3385
=> tool/go: add wrapper to download and use go.toolchain.rev go version.

cmd/hello/hello.go
But still support hello.ipn.dev for a bit.
Updates tailscale/corp#1327
=> cmd/hello: migrate to hello.ts.net as the hostname

ipn/ipnlocal/dnsconfig_test.go, ipn/ipnlocal/local.go, net/dns/config.go, net/dns/manager.go, net/dns/resolver/tsdns.go, net/tsaddr/tsaddr.go, net/tsaddr/tsaddr_test.go, net/tstun/wrap.go, wgengine/userspace.go
Fixes #3660
RELNOTE=MagicDNS now works over IPv6 when CGNAT IPv4 is disabled.
=> ipnlocal, net/{dns,tsaddr,tstun}, wgengine: support MagicDNS on IPv6

cmd/hello/hello.go
I apparently only did HTTP before, not HTTPS.
Updates tailscale/corp#1327
=> cmd/hello: also redirect https://hello.ipn.dev to hello.ts.net

cmd/tailscale/cli/cert.go, ipn/ipnlocal/local.go
And clarify the directory they get written to when under the sandbox.
Fixes #3667
=> ipn/ipnlocal: fix cert fetching on macOS GUI platforms

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
The blockForeverConn was only using its sync.Cond one side. Looks like it
was just forgotten.
Fixes #3671
=> wgengine/magicsock: fix watchdog timeout on Close when IPv6 not available

ipn/prefs.go, ipn/prefs_test.go
This code was copied in a few places (Windows, Android), so unify it
and add tests.
=> ipn: add methods on Prefs to get/set exit node being advertised

net/dns/resolver/tsdns.go
=> net/dns/resolver: on Android, make ExitDNS use net package for DNS

wgengine/netstack/netstack.go
Every OS ping binary is slightly different. Adjust for Android's.
Updates #1738
=> wgengine/netstack: fake pings through netstack on Android too

go.toolchain.branch, pull-toolchain.sh
Also go.toolchain.branch.
Both migrated from the corp repo.
=> go.toolchain.rev: add update script

cmd/derper/cert.go
=> cmd/derper: in manual cert mode, don't discard error from VerifyHostname

net/dns/manager_openbsd.go, net/dns/resolvd.go
OpenBSD 6.9 and up has a daemon which handles nameserver configuration. This MR
teaches the OpenBSD dns manager to check if resolvd is being used. If it is, it
will use the route(8) command to tell resolvd to add the Tailscale dns entries
to resolv.conf
Signed-off-by: Aaron Bieber <aaron@bolddaemon.com>
=> net/dns: teach OpenBSD's manager to talk to resolvd(8).

net/dns/manager_windows.go
Tailscale seems to be breaking WSL configurations lately.  Until we
understand what changed, turn off Tailscale's involvement by default
and make it opt-in.
Updates #2815
=> net/dns: make WSL network configuration opt-in for now

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go
The --reset shouldn't imply that a Start is necessary.
Fixes #3702
=> cmd/tailscale: let 'tailscale up --reset' do a pref edit

net/netns/netns_linux.go
=> net/netns: remove a useless probe of the "ip" command

cmd/tailscale/cli/web.go
This caused the exit node toggle to stop working as ",10.0.6.1/32" is invalid.
=> cmd/tailscale/cli/web: fix typo where the html template data was being replaced instead of being appended to.

cmd/tailscale/cli/web.go
The GitHub code scanner flagged this as a security vulnerability.
I don't believe it was, but I couldn't convince myself of it 100%.
Err on the safe side and use html/template to generate the HTML,
with all necessary escaping.
=> cmd/tailscale: use html/template for synoTokenRedirect

wgengine/magicsock/magicsock.go
Turning this on at the beginning of the 1.21.x dev cycle, for 1.22.
Updates #150
=> wgengine/magicsock: enable DERP Return Path Optimization (DRPO)

logtail/logtail.go, logtail/logtail_test.go
This started as an attempt to placate GitHub's code scanner,
but it's also probably generally a good idea.
=> logtail: cap the buffer size in encodeText

net/dnscache/dnscache.go
Cancelling the context makes the timeout goroutine race with the write that
reports a successful TLS handshake, so you can end up with a successful TLS
handshake that mysteriously reports that it timed out after ~0s in flight.
The context is always canceled and cleaned up as the function exits, which
happens mere microseconds later, so just let function exit clean up and
thereby avoid races.
=> net/dnscache: don't cancel the TLS context before writing to the result channel.

tstime/rate/rate_test.go
This test set the bar too high.
Just a couple of missed timers was enough to fail.
Change the test to more of a sanity check.
While we're here, run it for just 1s instead of 5s.
Prior to this change, on a 13" M1 MPB, with
stress -p 512 ./rate.test -test.run=QPS
I saw 90%+ failures.
After this change, I'm at 30k runs with no failures yet.
Fixes #3733
=> tstime/rate: deflake TestLongRunningQPS

control/controlbase/conn.go, control/controlbase/conn_test.go, control/controlbase/handshake.go, control/controlbase/handshake_test.go, control/controlbase/interop_test.go, control/controlbase/messages.go, control/controlbase/noiseexplorer_test.go, control/controlhttp/client.go, control/controlhttp/http_test.go, control/controlhttp/server.go, scripts/check_license_headers.sh
Before I go deeper down this rabbithole, could you confirm that there's no easier way to do "get a net.Conn via 101 Switching Protocols" with net/http than this? I'm having to reimplement and paraphrase a bunch of net/http's connection establishment logic to deal with the various proxying cases. Not very much code, but quite subtle :(
On the plus side, with a little more work, this one piece of code could be used for both DERP and control protocol dialing. But I feel like I'm missing some obvious way to hijack a conn client-side and as a result be able to lean much more on net/http...
=> control/controlhttp: package to get a controlbase.Conn over HTTP(S)

words/scales.txt, words/tails.txt
Mudpuppies are salamanders, and as such have tails but no scales.
The management apologizes for the error.
=> words: correct inexcusable oversight re: mudpuppies.

client/tailscale/tailscale.go, cmd/tailscale/cli/cert.go, cmd/tailscale/cli/cli.go, cmd/tailscale/cli/file.go
linux users get helpful advice to run tailscale with --operator=$USER
when they try to 'tailscale file {cp,get}' but are mysteriously forbidden.
Signed-off-by: David Eger <david.eger@gmail.com>
=> cmd/tailscale: Propagate tailscaled 403s as AccessDeniedErrors

cmd/derper/derper.go
=> cmd/derper: export TLS vars with derper_ prefix, not stun_

ipn/ipnserver/server.go, ipn/localapi/cert.go, ipn/localapi/localapi.go
So you can run Caddy etc as a non-root user and let it have access to
get certs.
Updates caddyserver/caddy#4541
=> ipn/ipnserver: add TS_PERMIT_CERT_UID envknob to give webservers cert access

words/scales.txt
Salamanders also have no scales. I checked the interweb, and there
doesn't seem to be any subspecies that would let us claim that
*some* salamanders are scaley.
But they are tailey, for sure.
=> words: fallout from mudpuppy-gate.

wgengine/magicsock/debugknobs_ios.go
Can still be constant, just needs the extra methods.
Fixes #3812
=> wgengine/magicsock: make debugUseDerpRoute an opt.Bool.

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go, tstest/integration/vms/vms_test.go
Also fix a somewhat related printing bug in the process where
some paths would print "Success." inconsistently even
when there otherwise was no output (in the EditPrefs path)
Fixes #3830
Updates #3702 (which broke it once while trying to fix it)
=> cmd/tailscale: fix up --reset, again

net/dns/resolvd.go
This prevents adding an empty "search" line when no search domains are set.
Signed-off-by: Aaron Bieber <aaron@bolddaemon.com>
=> net/dns/resolvd: properly handle not having "search" entries

util/winutil/winutil_notwindows.go
It was broken on Windows:
```
Error: util\winutil\winutil_windows.go:15:7: regBase redeclared in this block
Error:                                       D:\a\tailscale\tailscale\util\winutil\winutil_notwindows.go:7:17: previous declaration
Error: util\winutil\winutil_windows.go:29:6: getRegString redeclared in this block
Error:                                       D:\a\tailscale\tailscale\util\winutil\winutil_notwindows.go:9:40: previous declaration
Error: util\winutil\winutil_windows.go:47:6: getRegInteger redeclared in this block
Error:                                       D:\a\tailscale\tailscale\util\winutil\winutil_notwindows.go:11:48: previous declaration
Error: util\winutil\winutil_windows.go:77:6: isSIDValidPrincipal redeclared in this block
Error: …
```
=> util/winutil: fix build

net/interfaces/interfaces_linux.go, net/interfaces/interfaces_linux_test.go
tailscaled was using 100% CPU on a machine with ~1M lines, 100MB+
of /proc/net/route data.
Two problems: in likelyHomeRouterIPLinux, we didn't stop reading the
file once we found the default route (which is on the first non-header
line when present). Which meant it was finding the answer and then
parsing 100MB over 1M lines unnecessarily. Second was that if the
default route isn't present, it'd read to the end of the file looking
for it. If it's not in the first 1,000 lines, it ain't coming, or at
least isn't worth having. (it's only used for discovering a potential
UPnP/PMP/PCP server, which is very unlikely to be present in the
environment of a machine with a ton of routes)
=> net/interfaces: bound Linux /proc/net/route parsing

scripts/installer.sh
Recent linuxmint releases now use VERSION_CODENAME for
a linuxmint release (like "uma") and set UBUNTU_CODENAME to
the Ubuntu release they branched from.
Tested in a linuxmint 20.2 VM.
=> installer.sh: accommodate linuxmint versioning.

control/controlclient/direct.go
We don't use it anyway, so be explicit that we're not using it.
=> control/controlclient: turn off Go's implicit compression

util/winutil/winutil_windows.go
It makes the most sense to have all our utility functions reside in one place.
There was nothing in corp that could not reasonably live in OSS.
I also updated `StartProcessAsChild` to no longer depend on `futureexec`,
thus reducing the amount of code that needed migration. I tested this change
with `tswin` and it is working correctly.
I have a follow-up PR to remove the corresponding code from corp.
=> util/winutil: migrate corp's winutil into OSS.

net/dns/manager_linux.go, net/dns/manager_linux_test.go, net/dns/resolved.go
If systemd-resolved is enabled but not running (or not yet running,
such as early boot) and resolv.conf is old/dangling, we weren't
detecting systemd-resolved.
This moves its ping earlier, which will trigger it to start up and
write its file.
Fixes #3362
Fixes #3531
=> net/dns: fix systemd-resolved detection race at boot

cmd/derper/bootstrap_dns.go
The commit b9c92b90db08bbcb7c726c307d2c7b2590278953 earlier today
caused a regression of serving an empty map always, as it was
JSON marshalling an atomic.Value instead of the DNS entries map
it just built.
=> cmd/derper: fix regression from bootstrap DNS optimization

control/controlclient/sign_supported.go, control/controlclient/sign_supported_test.go
If multiple certificates match when selecting a certificate, use the one
issued the most recently (as determined by the NotBefore timestamp).
This also adds some tests for the function that performs that
comparison.
Updates tailscale/coral#6
=> control/controlclient: select newer certificate

control/controlclient/direct.go
The TODO is done. Magicsock doesn't require any endpoints to create an
*endpoint now.  Verified both in code and empirically: I can use the
env knob and access everything.
=> control/controlclient: remove dummy endpoint in endpoint stripping mode

envknob/envknob.go
The strconv errors already stringified with the same.
=> envknob: remove some stutter from error messages

net/tstun/wrap.go
This TODO was both added and fixed in 506c727e3.
As I recall, I wasn't originally going to do it because it seemed
annoying, so I wrote the TODO, but then I felt bad about it and just
did it, but forgot to remove the TODO.
=> net/tstun: remove TODO that's done

ipn/ipnlocal/local.go
Our previous Hostinfo logging was all as a side effect of telling
control. And it got marked as verbose (as it was)
This adds a one-time Hostinfo logging that's not verbose, early in
start-up.
=> ipn/ipnlocal: log most of Hostinfo once non-verbose at start-up

scripts/installer.sh
When running this script against a totally fresh out of the box Debian
11 image, sometimes it will fail to run because it doesn't have a
package list cached. This patch adds an `apt-get update` to ensure that
the local package cache is up to date.
Signed-off-by: Xe Iaso <xe@tailscale.com>
=> scripts/installer: automagically run apt update

net/dnscache/dnscache.go, net/dnscache/dnscache_test.go
If we've already connected to a certain name's IP in the past, don't
assume the problem was DNS related. That just puts unnecessarily load
on our bootstrap DNS servers during regular restarts of Tailscale
infrastructure components.
Also, if we do do a bootstrap DNS lookup and it gives the same IP(s)
that we already tried, don't try them again.
=> net/dnscache: don't do bootstrap DNS lookup after most failed dials

ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go
We need this for some Docker-related features. There's currently no way to detect the MagicDNS status from the `status --json` output, so this commit adds it.
Fixes tailscale/corp#3670
Signed-off-by: Ross Zurowski <ross@rosszurowski.com>
=> ipn: add `CurrentTailnet` info to `tailscale status --json`

ipn/ipnlocal/ssh.go, ssh/tailssh/tailssh.go
Make tailssh ask LocalBackend for the SSH hostkeys, as we'll need to
distribute them to peers.
For now only the hacky use-same-as-actual-host mode is implemented.
Updates #3802
=> ipnlocal, tailssh: start moving host key stuff into the right spot

control/controlclient/direct.go, tailcfg/tailcfg.go, tstest/integration/testcontrol/testcontrol.go
Otherwise omitempty doesn't work.
This is wire-compatible with a non-pointer type, so switching
is safe, now and in the future.
=> tailcfg: make MapResponse.ControlTime a pointer

ipn/ipnlocal/local.go, logtail/logtail.go, logtail/logtail_test.go, types/logger/logger.go, types/logger/logger_test.go
e.g. the change to ipnlocal in this commit ultimately logs out:
```
{"logtail":{"client_time":"2022-02-17T20:40:30.511381153-08:00","server_time":"2022-02-18T04:40:31.057771504Z"},"type":"Hostinfo","val":{"GoArch":"amd64","Hostname":"tsdev","IPNVersion":"1.21.0-date.20220107","OS":"linux","OSVersion":"Debian 11.2 (bullseye); kernel=5.10.0-10-amd64"}}
```
=> types/logger, logtail: add mechanism to do structured JSON logs

cmd/tailscaled/tailscaled.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/loglines_test.go, ipn/ipnlocal/state_test.go, ipn/ipnserver/server.go, tsnet/tsnet.go, tstest/integration/tailscaled_deps_test_darwin.go, tstest/integration/tailscaled_deps_test_freebsd.go, tstest/integration/tailscaled_deps_test_linux.go, tstest/integration/tailscaled_deps_test_openbsd.go, tstest/integration/tailscaled_deps_test_windows.go
RELNOTE=`tailscaled --state=mem:` registers as an ephemeral node and
does not store state to disk.
=> cmd/tailscaled: add `-state=mem:` to support creation of an ephemeral node

ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go
This adds `Tags` and `PrimaryRoutes` to the output of `tailscale status --json`
cc @mayakacz 
=> ipn/{ipnlocal,ipnstate}: add Tags and PrimaryRoutes to PeerStatus

ipn/ipnlocal/peerapi.go, ipn/ipnserver/server.go, net/netutil/netutil.go, net/netutil/netutil_test.go
I introduced a bug in 8fe503057da26 when unifying oneConnListener
implementations.
The NewOneConnListenerFrom API was easy to misuse (its Close method
closes the underlying Listener), and we did (via http.Serve, which
closes the listener after use, which meant we were close the peerapi's
listener, even though we only wanted its Addr)
Instead, combine those two constructors into one and pass in the Addr
explicitly, without delegating through to any Listener.
=> net/netutil: fix regression where peerapi would get closed after 1st req

ipn/ipnlocal/ssh.go, ipn/ipnlocal/ssh_test.go
=> ipn/ipnlocal: generate tailscaled-owned SSH keys as needed

cmd/tailscaled/tailscaled_test.go
Turns out we're pretty good already at init-time work in tailscaled.
The regexp/syntax shows up but it's hard to get rid of that; zstd even
uses regexp. *shrug*
=> cmd/tailscaled: add a no-op test for profiling init-time memory allocs

ipn/store/stores.go, ipn/store/stores_test.go
Otherwise it would log warnings about an empty file.
```
stores.go:138: store.NewFileStore("/tmp/3777352782"): file empty; treating it like a missing file [warning]
```
=> ipn/store: [TestNewStore] do not use an empty file

hostinfo/hostinfo_linux.go, version/distro/distro.go, version/distro/distro_test.go
Now:
```
/tmp/breakglass3929186798 # /user/tailscale debug hostinfo
{
"IPNVersion": "1.23.0-date.20220107",
"OS": "linux",
"OSVersion": "Gokrazy; kernel=5.16.11",
"DeviceModel": "Raspberry Pi 4 Model B Rev 1.2",
"Hostname": "gokrazy",
"GoArch": "arm64"
}
```
Also, cache the distro lookup. It doesn't change while the program is
running:
```
name   old time/op    new time/op    delta
Get-6    5.21µs ± 5%    0.00µs ± 3%   -99.91%  (p=0.008 n=5+5)
name   old alloc/op   new alloc/op   delta
Get-6      792B ± 0%        0B       -100.00%  (p=0.008 n=5+5)
name   old allocs/op  new allocs/op  delta
Get-6      8.00 ± 0%      0.00       -100.00%  (p=0.008 n=5+5)
```
Updates #1866
/cc @stapelberg
=> version, hostinfo: recognize gokrazy as a distro

cmd/tailscaled/tailscaled.go, paths/paths.go, paths/paths_unix.go
One of the current few steps to run Tailscale on gokrazy is to
specify the --tun=userspace-networking flag:
https://gokrazy.org/userguide/install/tailscale/
Instead, make it the default for now. Later we can change the
default to kernel mode if available and fall back to userspace
mode like Synology, once #391 is done.
Likewise, set default paths for Gokrazy, as its filesystem hierarchy
is not the Linux standard one. Instead, use the conventional paths as
documented at https://gokrazy.org/userguide/install/tailscale/.
Updates #1866
RELNOTE=default to userspace-networking mode on gokrazy
/cc @stapelberg
=> cmd/tailscaled: default to userspace-networking mode on gokrazy, set paths

cmd/tailscale/cli/cli.go
In the future we'll probably want to run the "tailscale web"
server instead, but for now stop the infinite restart loop.
See https://gokrazy.org/userguide/process-interface/ for details.
Updates #1866
/cc @stapelberg
=> cmd/tailscale: tell gokrazy to not manage the CLI as a daemon

control/controlclient/direct.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go, tstest/integration/testcontrol/testcontrol.go
And add a CapabilityVersion type, primarily for documentation.
This makes MapRequest.Version, RegisterRequest.Version, and
SetDNSRequest.Version all use the same version, which will avoid
confusing in the future if Register or SetDNS ever changed their
semantics on Version change. (Currently they're both always 1)
This will requre a control server change to allow a
SetDNSRequest.Version value other than 1 to be deployed first.
=> tailcfg: rename map request version to "capability version"

control/controlclient/noise.go
Fix regression from 21069124db caught by tests in another repo.
The HTTP/2 Transport that was being returned had a ConnPool that never
dialed.
Updates #3488
=> control/controlclient: fix Noise HTTP/2 regression from earlier commit

net/socks5/socks5.go
Customer reported an issue where the connections were not closing, and
would instead just stay open. This commit makes it so that we close out
the connection regardless of what error we see. I've verified locally
that it fixes the issue, we should add a test for this.
=> net/socks5: always close client connections after serving

net/interfaces/interfaces_bsd.go, net/interfaces/interfaces_defaultrouteif_todo.go
Updates #4101 (probably fixes)
=> net/interfaces: add FreeBSD default route lookup (portmapping, etc)

control/controlbase/conn.go
Currently `Write` returns the number of ciphertext bytes written.
According to the docs for io.Writer, Write should return the amount
of bytes consumed from the input.
```
// Write writes len(p) bytes from p to the underlying data stream.
// It returns the number of bytes written from p (0 <= n <= len(p))
// and any error encountered that caused the write to stop early.
// Write must return a non-nil error if it returns n < len(p).
// Write must not modify the slice data, even temporarily.
Write(p []byte) (n int, err error)
```
Fixes #4126
=> control/controlbase: make Conn.Write return consumed bytes

control/controlclient/auto.go, control/controlclient/client.go, control/controlclient/direct.go, ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go, ipn/localapi/localapi.go
Builds on work in tailscale/corp#4205, which is where all the can't-extend-expiry logic is.
Usage like:
`curl -X POST http://foo/localapi/v0/shorten-expiry -d "expiry=1647242808"`
=> control/controlclient, localapi: shorten expiry time via localapi

control/controlclient/direct.go
When using Noise.
Updates #3488
=> control/controlclient: proactively close TLS connection after /key fetch

.github/workflows/windows.yml
- Remove the expanded module files, as Go can likely expand the zips
faster than tar can expand the extra copies.
- Add the go-build cache.
=> github/windows: attempt to improve cache performance

.github/workflows/windows-race.yml
Applying the same logic as for the non-race builder, using a dedicated cache key to avoid build cache trees from stomping each other.
=> github/windows: improve caching in -race builder

ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go, tailcfg/tailcfg.go, types/views/views.go, types/views/views_test.go
Also make IPPrefixSliceOf use Slice[netaddr.IPPrefix] as it also
provides additional functions besides the standard ones provided by
Slice[T].
I considered making `type StringSlice = Slice[string]` but decided against it.
=> types/views: add generic Slice[T] and remove StringSlice

cmd/tailscaled/tailscaled.go
=> cmd/tailscaled: fail early with nice error on macOS with go1.18

go.mod, go.sum, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/wgcfg/device_test.go
This pulls in a handful of fixes and an update to Go 1.18.
=> go.mod: upgrade to the latest wireguard-go

scripts/installer.sh
apt-key depends on gnupg but apt-key itself if not used
on modern systems (APT_KEY_TYPE=keyring).
Signed-off-by: Simon Deziel <simon@sdeziel.info>
=> scripts: install gnupg only when apt-key is needed

derp/derp_server.go, derp/derp_test.go
See https://github.com/golang/go/issues/51759#issuecomment-1071147836
Once we deploy this, tailscaled should work again for macOS users with
Go 1.18.
Updates golang/go#51759
=> derp: set Basic Constraints on metacert

client/tailscale/required_version.go, client/tailscale/tailscale.go, cmd/tailscaled/debug.go, cmd/tailscaled/install_darwin.go, cmd/tailscaled/install_windows.go, cmd/tailscaled/proxy.go, cmd/tailscaled/required_version.go, cmd/tailscaled/tailscaled.go, cmd/tailscaled/tailscaled_bird.go, cmd/tailscaled/tailscaled_notwindows.go, cmd/tailscaled/tailscaled_windows.go
Due to a bug in Go (golang/go#51778), cmd/go doesn't warn about your
Go version being older than the go.mod's declared Go version in that
case that package loading fails before the build starts, such as when
you use packages that are only in the current version of Go, like our
use of net/netip.
This change works around that Go bug by adding build tags and a
pre-Go1.18-only file that will cause Go 1.17 and earlier to fail like:
$ ~/sdk/go1.17/bin/go install ./cmd/tailscaled
./required_version.go:11:2: undefined: you_need_Go_1_18_to_compile_Tailscale
note: module requires Go 1.18
=> cmd/tailscaled: make build fail nicely on older Go versions

prober/prober.go, prober/prober_test.go
Turns out, it's annoying to have to wait the entire interval
before getting any monitorable data, especially for very long
interval probes like hourly/daily checks.
=> prober: run all probes once on initial registration.

ssh/tailssh/tailssh.go, ssh/tailssh/tailssh_test.go, tailcfg/tailcfg.go
=> tailcfg, ssh/tailssh: make SSHUser value '=' map ssh-user to same local-user

control/controlbase/conn.go, control/controlbase/conn_test.go
Uses 4KB less per Conn.
Fixes #4113
=> control/controlbase: use less memory when idle (remove rxState.buf)

prober/prober.go, prober/prober_test.go
This lets especially dynamically-registered probes export their results with a bunch more dimensions to slice by in dashboards, so you can e.g. show "only probes for DERP in Singapore", or "only production backup checks".
The labels are still static after probe creation, because prometheus doesn't deal well with per-datapoint cardinality explosion. This API forces you to think a little bit about adding labels that are about the probe, not about a particular probing event.
Two commits. First one is a pure refactor that uses PrometheusVar for exporting probe results, without altering the exported data. The second commit alters the probe export to include custom labels.
=> prober: support adding key/value labels to probes.

tsnet/tsnet.go
Like we did in ead16b24ec64ef1c82956011f119c500ae360d07 for tailscaled.
Updates #4258
Due to golang/go#51759
=> tsnet: fail with nice message with go1.18 on darwin

cmd/proxy-to-grafana/proxy-to-grafana.go
Moving this into cmd for now... can create a new repo if we decide to go in that direction. Now using the new whois rather than exec'ing status from the cli, and added tsnet so it can be easily served on 80/443.
@maisem I would like to include tls on this as well... the other tls work for the builder seems like a lot of boilerplate to configure 80->443 redirect, request a cert, etc. Does it makes sense to wrap that into some convenience that I we can reuse in the tsnet package?
=> cmd/proxy-to-grafana: use grafana's authproxy to log in tailnet users

cmd/tailscaled/tailscaled.go, tsnet/tsnet.go
We have worked around the issue in DERP,
so the vanilla Go 1.18 toolchain now works.
=> all: remove "no 1.18 support" failures

control/controlhttp/client.go, control/controlhttp/server.go, net/netutil/netutil.go
=> net/netutil: move some net utils from control/controlhttp to netutil

cmd/tailscale/cli/status.go
And return an error if you use non-flag arguments.
=> cmd/tailscale: make status --peers=false work earlier + in JSON mode

net/dnscache/dnscache.go, net/dnsfallback/dnsfallback.go
Two changes
```
net/dnsfallback: do not attempt lookups of IPs.
When the context is canceled, dc.dialOne returns an error from line 345.
This causes the defer on line 312 to try to resolve the host again, which
triggers a dns lookup of "127.0.0.1" from derp.
```
```
net/dnscache: do not call LookupIPFallback if the context was canceled.
Currently if the passed in host is an IP, Lookup still attempts to
resolve it with a dns server. This makes it just return the IP directly.
```
Updates tailscale/corp#4475
=> net/dnscache: do not call LookupIPFallback if the context was canceled.

ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go, wgengine/userspace.go, wgengine/wgengine.go
When `setWgengineStatus` is invoked concurrently from multiple
goroutines, it is possible that the call invoked with a newer status is
processed before a call with an older status. e.g. a status that has
endpoints might be followed by a status without endpoints. This causes
unnecessary work in the engine and can result in packet loss.
This patch adds an `AsOf time.Time` field to the status to specifiy when the
status was calculated, which later allows `setWgengineStatus` to ignore
any status messages it receives that are older than the one it has
already processed.
Updates tailscale/corp#2579
=> ipn/ipnlocal: do not process old status messages received out of order

prober/http.go
=> prober: used keyed initializer for LimitedReader.

control/controlclient/direct.go, ipn/ipnlocal/local.go, net/netutil/ip_forward.go, net/tsaddr/tsaddr.go
Combine the code between `LocalBackend.CheckIPForwarding` and
`controlclient.ipForwardingBroken`.
Fixes #4300
=> net/netutil: add CheckIPForwardingLinux

go.mod, go.sum, ssh/tailssh/tailssh.go, tempfork/gliderlabs/ssh/server.go
Prep for evaluating SSHPolicy earlier to decide whether certs are
required, which requires knowing the target SSH user.
Updates #3802
=> go.mod, ssh/tailssh, tempfork/gliderlabs: bump x/crypto/ssh fork for NoClientAuthCallback

derp/derp_server.go
This allows tests to verfiy that a DERP connection was actually
established.
Related to #4326
Updates tailscale/corp#2579
=> derp: add (*Server).IsClientConnectedForTest func. 

tailcfg/tailcfg.go, types/logger/logger_test.go
This reduces the noise when marshaling only a subset of this type.
=> tailcfg: add omitempty to all fields of Hostinfo

cmd/tailscale/cli/cli.go
No needed since gokrazy doesn't restart successful processes anymore: https://github.com/gokrazy/gokrazy/pull/127
The current behavior is breaking in my (old raspberry pi) case https://github.com/tailscale/tailscale/pull/4117#issuecomment-1086641950
cc @stapelberg
=> cmd/tailscale: drop special exit code 125 for gokrazy

net/dns/resolver/tsdns.go, net/dns/resolver/tsdns_test.go
Fixes #1233 
Open questions:
- What should the specific domain be? I yeeted `nodedns.tailscale-internals` but very open to bike-shed. In particular, should we make it an actual real domain, and make a corresponding forward A/AAAA record resolvable via public DNS?
- ~Should we provide a PTR record for `100.101.102.103` (hello) as well? Afaict its optional?~ Already works thanks to the existing PTR implementation for nodes on the tailnet
=> net/dns/resolver: return symbolic PTR records for TS service IPs

cmd/mkpkg/main.go, shell.nix
I would like to package proxy-to-grafana and similar tools in .deb/.rpm packages. As a first step to that, I want to be able to pass a package name and description to the `mkpkg` tool.
Also included is a patch to `shell.nix` to make it track recent changes in how `goimports` is referenced.
=> cmd/mkpkg: add name argument

control/controlbase/conn_test.go, control/controlbase/handshake.go, control/controlbase/handshake_test.go, control/controlbase/interop_test.go, control/controlbase/messages.go, control/controlclient/noise.go, control/controlclient/noise_test.go, control/controlhttp/client.go, control/controlhttp/http_test.go, control/controlhttp/server.go
This is so that we can plumb our client capability version through
the protocol as the Noise version. The capability version increments
more frequently than strictly required (the Noise version only needs
to change when cryptographically-significant changes are made to
the protocol, whereas the capability version also indicates changes
in non-cryptographically-significant parts of the protocol), but this
gives us a safe pre-auth way to determine if the client supports
future protocol features, while still relying on Noise's strong
assurance that the client and server have agreed on the same version.
Currently, the server executes the same protocol regardless of the
version number, and just presents the version to the caller so they
can do capability-based things in the upper RPC protocol. …
=> control/controlbase: make the protocol version number selectable.

control/controlbase/conn_test.go, control/controlbase/handshake.go, control/controlbase/handshake_test.go, control/controlbase/interop_test.go, control/controlhttp/http_test.go, control/controlhttp/server.go
Doing so makes development unpleasant, because we have to first break the
client by bumping to a version the control server rejects, then upgrade
the control server to make it accept the new version.
This strict rejection at handshake time is only necessary if we want to
blocklist some vulnerable protocol versions in the future. So, switch
to a default-permissive stance: until we have such a version that we
have to eagerly block early, we'll accept whatever version the client
presents, and leave it to the user of controlbase.Conn to make decisions
based on that version.
Noise still enforces that the client and server *agree* on what protocol
version is being used, and the control server still has the option to
finish the handshake and then hang up with an in-noise error, rather
than abort …
=> control/controlbase: don't enforce a max protocol version at handshake time.

cmd/tailscale/cli/web.go
Error message:
```js
(index):13 Mixed Content: The page at 'https://dsm.example.local/webman/3rdparty/Tailscale/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dsm.example.local/webman/login.cgi'. This request has been blocked; the content must be served over HTTPS.
```
=> cmd/tailscale: make web mode preserve URL scheme in Synology redirect

tstest/integration/vms/README.md
Due to a merge error on my part this did not make it into #4374, my bad
=> tstest/integration/vms: consistently use two dashes for cmd-line switches

net/dns/manager.go, net/dns/resolver/tsdns.go, net/dns/resolver/tsdns_test.go, wgengine/userspace.go
Previously, method calls into the DNS manager/resolver types handled DNS requests rather than DNS packets. This is fine for UDP as one packet corresponds to one request or response, however will not suit an implementation that supports DNS over TCP.
To support PRs implementing this in the future, wgengine delegates all handling/construction of packets to the magic DNS endpoint, to the DNS types themselves. Handling IP packets at this level enables future support for both UDP and TCP.
=> net/dns, net/dns/resolver, wgengine: refactor DNS request path

shell.nix
This change builds a derivation for tailscale-go and makes it available in the
users development environment. This is consistent with the shell.nix in corp/.
Once go1.18 is in a stable Nixpkgs release we can avoid relying on derivations
from nixpkgs head. For now, this works well, and the fetched derivations are
cached in the Nix store according to the usual rules.
Fixes #4231
Signed-off-by: Tom DNetto <tom@tailscale.com>
=> shell.nix: use tailscale-go for compilation

tstest/integration/vms/README.md, tstest/integration/vms/distros.go, tstest/integration/vms/distros.hujson, tstest/integration/vms/top_level_test.go, tstest/integration/vms/vm_setup_test.go
I would like to do some more customized integration tests in the future, (specifically, bringing up a mitm proxy and testing tailscaled through that) so hoping to bring back the nixos wiring to support that.
=> tstest/integration/vms: test on stable nixos (21.11)

wgengine/monitor/monitor_linux.go, wgengine/monitor/monitor_linux_test.go
Two commits, the first contains the introduction of an envknob for live inspection of this path. Using this envknob I discovered several follow-up issues described below and included in the change in the second commit.
--
Ignoring the events at this layer is the simpler path for right now, a
broader change should follow to suppress irrelevant change events in a
higher layer so as to avoid related problems with other monitoring paths
on other platforms.  This approach may also carry a small risk that it
applies an at-most-once invariant low in the chain that could be assumed
otherwise higher in the code.
I adjusted the newAddrMessage type to include interface index rather
than a label, as labels are not always supplied, and in particular on my
test hosts they were consistently missing for …
=> wgengine/monitor: ignore duplicate RTM_NEWADDRs

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go, ipn/ipnlocal/local.go, net/tsaddr/tsaddr.go, net/tsaddr/tsaddr_test.go, wgengine/netstack/netstack.go
This defines a new magic IPv6 prefix, fd7a:115c:a1e0:b1a::/64, a subset of our
existing /48, where the final 32 bits are an IPv4 address, and the middle 32 bits are
a user-chosen "site ID".
e.g., I can say my home LAN's "site ID" is "bbbb:0000" and then
advertise its IPv4 via IPv6, like:
tailscale up --advertise-routes=fd7a:115c:a1e0:b1a:bbbb::/80
Then people in my tailnet can:
$ curl '[fd7a:115c:a1e0:b1a:bbbb::10.2.0.230]'
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" ....
Or if only want to export 10.2.0.0/16:
tailscale up --advertise-routes=fd7a:115c:a1e0:b1a:bbbb::10.2.0.0/112
(112 being 128-16)
Updates #3616, etc
=> net/tsaddr, wgengine/netstack: add IPv6 range that forwards to site-relative IPv4

tstest/integration/vms/nixos_test.go, tstest/integration/vms/squid.conf, tstest/integration/vms/top_level_test.go, tstest/integration/vms/vm_setup_test.go, tstest/integration/vms/vms_test.go
Updates #4377
Very smoky/high-level test to ensure that derphttp internals play well with an aggressive (stare + bump) meddler-in-the-middle proxy.
=> tstest/integration/vms: smoke test derphttp through mitm proxies

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
Currently peerIPs doesn't do any sorting of the routes it returns. This
is typically fine, however imagine the case of an HA subnet router
failover. When a route R moves from peer A to peer B, the output of
peerIPs changes. This in turn causes all the deephash check inside
wgengine to fail as the hashed value of [R1, R2] is different than
the hashed value of [R2, R1]. When the hash check failes, it causes
wgengine to reconfigure all routes in the OS. This is especially
problematic for macOS and iOS where we use the NetworkExtension.
This commit makes it that the peerIPs are always sorted when returned,
thus making the hash be consistent as long as the list of routes remains
static.
=> ipn/ipnlocal: make peerIPs return a sorted slice

cmd/nginx-auth/.gitignore, cmd/nginx-auth/README.md, cmd/nginx-auth/mkdeb.sh, cmd/nginx-auth/nginx-auth.go, cmd/nginx-auth/tailscale.nginx-auth.service, cmd/nginx-auth/tailscale.nginx-auth.socket, go.mod, go.sum
This conforms to the NGINX subrequest result authentication protocol[1] using the NGINX module `ngx_http_auth_request_module`. This is based on the example that @peterkeen provided on Twitter[2], but with several changes to make things more tightly locked down:
* This listens over a UNIX socket instead of a TCP socket to prevent leakage to the network
* This uses systemd socket activation so that systemd owns the socket and can then lock down the service to the bare minimum required to do its job without having to worry about dropping permissions
* This provides additional information in HTTP response headers that can be useful for integrating with various services
* This has a script to automagically create debian and redhat packages for easier distribution
This will be written about on …
=> cmd/nginx-auth: create new Tailscale NGINX auth service

cmd/tailscaled/tailscaled.go
Usage of userspace-networking is increasing, and the aggressive GC
tuning causes a significant reduction in performance in that mode.
---
I was debugging a different issue and noticed that the GC frequency under moderate throughput (100mbit) in userspace mode was very high - multiple times per second.
The default tuning seems more suitable when running in userspace mode.
Observed metrics from the change tested against a 2015 macbook pro over wifi (not great test):
100mbit sustained UDP:
GOGC=10: dropping ~15% of packets
GOGC=100: dropping 0%
TCP throughput test:
GOGC=10:   100mbit
GOGC=100:  350mbit
Throughput wise for this scenario, the new tuning causes userspace mode and normal mode to perform the same.
=> tailscaled: reduce gc churn

net/dns/publicdns/publicdns.go
=> net/dns/publicdns: add missing call to sync.Once.Do

ipn/ipnlocal/local.go, tailcfg/tailcfg.go
To experiment with avoiding Chrome ERR_NETWORK_CHANGED errors on route
changes.
Updates #3102
=> tailcfg, ipn/ipnlocal: add debug flag to enable one-big-CGNAT/10 route

ssh/tailssh/incubator.go, ssh/tailssh/tailssh.go, ssh/tailssh/tailssh_test.go, tailcfg/tailcfg.go, wgengine/netstack/netstack.go
=> tailcfg, ssh/tailssh: optionally support SSH public keys in wire policy

go.mod, go.sum
We only use the termios subpackage, so we're unaffected by
CVE-2020-7665, but the bump will let dependabot return to slumber.
Fixes https://github.com/tailscale/tailscale/security/dependabot/2
=> go.mod: bump u-root

ipn/ipnlocal/peerapi.go, ipn/ipnlocal/peerapi_test.go, tailcfg/tailcfg.go
Controlled by server-sent capability policy.
To be initially used for SSH servers to record sessions to other
nodes. Not yet productized into something user-accessible. (Notably,
the list of Taildrop targets from the sender side isn't augmented
yet.) This purely permits expanding the set of expands a node will
accept a drop from.
Updates #3802
Updates #4217
=> ipn/ipnlocal: add start of inter-user Taildrop

wgengine/monitor/monitor.go
In `(*Mon).Start` we don't run a timer to update `(*Mon).lastWall` on iOS and
Android as their sleep patterns are bespoke. However, in the debounce
goroutine we would notice that the the wall clock hadn't been updated
since the last event would assume that a time jump had occurred. This would
result in non-events being considered as major-change events.
This commit makes it so that `(*Mon).timeJumped` is never set to `true`
on iOS and Android.
=> wgengine/monitor: do not set timeJumped on iOS/Android

client/tailscale/tailscale.go, cmd/tailscale/cli/up.go, ipn/ipnlocal/local.go, ipn/localapi/localapi.go
Fail on unsupported platforms (must be Linux or macOS tailscaled with
WIP env) or when disabled by admin (with TS_DISABLE_SSH_SERVER=1)
Updates #3802
=> cmd/tailscale, etc: make "tailscale up --ssh" fail fast when unavailable

ipn/ipnlocal/peerapi.go, tailcfg/tailcfg.go
The default is still users can debug their own nodes. But like
cd916b728b did, this adds support for admins to grant additional
capabilities with the new tailcfg.CapabilityDebugPeer cap.
Updates #4217
=> ipn/ipnlocal: add capability for debugging peers over peerapi

net/dns/resolver/forwarder.go, net/dns/resolver/forwarder_test.go, net/dnscache/dnscache.go, net/dnscache/dnscache_test.go
Simplify the ability to reason about the DoH dialing code by reusing the
dnscache's dialer we already have.
Also, reduce the scope of the "ip" variable we don't want to close over.
This necessarily adds a new field to dnscache.Resolver:
SingleHostStaticResult, for when the caller already knows the IPs to be
returned.
=> net/dns/resolver: make DoH dialer use existing dnscache happy eyeball dialer

control/controlclient/direct.go, logtail/logtail.go, tailcfg/tailcfg.go
For people running self-hosted control planes who want a global
opt-out knob instead of running their own logcatcher.
=> tailcfg, logtail: provide Debug bit to disable logtail

hostinfo/hostinfo.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go
From the machines tab its hard to differenciate desktop Linux installs from server Linux installs. Transmitting this information should make this determination a lot easier.
Due to the reality that tailscaled is likely a system process, the standard checks based on XDG_SESSION_TYPE or DISPLAY environment variables are not possible (those variables won't be set). Instead, we look for listening unix sockets that are typical of desktop installs.
=> hostinfo, tailcfg: add desktop environment to hostinfo

cmd/proxy-to-grafana/proxy-to-grafana.go
This commit changes proxy-to-grafana to report errors while polling for
tailscaled status instead of terminating at the first sign of an error.
This allows tailscale some time to come up before the proxy decides to
give up.
=> cmd/proxy-to-grafana: prevent premature termination

cmd/nginx-auth/README.md, cmd/nginx-auth/deb/postinst.sh, cmd/nginx-auth/deb/postrm.sh, cmd/nginx-auth/deb/prerm.sh, cmd/nginx-auth/mkdeb.sh, cmd/nginx-auth/nginx-auth.go, cmd/nginx-auth/rpm/postrm.sh, cmd/nginx-auth/rpm/prerm.sh
This adds the `Expected-Tailnet` header to the auth proxy. This allows you to set an expected tailnet so that you can be sure that node sharing users can't access certain internal services.
This also adds Debian and RPM maintainer scripts to the install process to ensure that systemd state is properly updated on a package update.
=> cmd/nginx-auth: maintainer scripts and tailnet checking

wgengine/monitor/monitor.go, wgengine/monitor/monitor_darwin.go, wgengine/monitor/monitor_freebsd.go, wgengine/monitor/monitor_linux.go, wgengine/monitor/monitor_windows.go, wgengine/monitor/polling.go
Currently we ignore these interfaces in the darwin osMon but then would consider it
interesting when checking if anything had changed.
=> wgengine/monitor: ignore OS-specific uninteresting interfaces

scripts/installer.sh
Also fix gentoo in certain situations by passing `--ask=n` to emerge.
=> scripts/install: add ParrotSec, LMDE, and Alma support

ipn/ipnlocal/local.go
For tests.
Now that we can always listen (whereas we used to fail prior to
a2c330c4961aea883a674aa530cc40bf74047bac), some goroutine leak
checks were failing in tests in another repo after that change.
=> ipn/ipnlocal: close peerapi listeners on LocalBackend.Shutdown

ssh/tailssh/tailssh.go
gliderlabs/ssh was already adding the "SSH-2.0-" prefix.
Updates #3802
=> ssh/tailssh: fix double SSH-2.0- prefix in greeting banner

ssh/tailssh/incubator.go, ssh/tailssh/tailssh_test.go
Noted by @danderson
Updates #3802
=> ssh/tailssh: filter accepted environment variables

shell.nix
Maybe in the future we should have `go.toolchain.rev` files like we have in control, and then (given control already pulls in OSS) controls `shell.nix` can read the values from OSS. Just an idea.
=> shell.nix: Update go toolchain

cmd/tailscale/cli/ssh.go
=> cmd/tailscale/cli: do not use syscall.Exec from macOS sandbox

ssh/tailssh/tailssh_test.go
The tests were hanging for me, probably waiting for `ssh` to exit, but it may not under some conditions, such as if it's matched my broad ControlMaster config. Avoiding the user config will avoid any such test unpredictability.
=> ssh/tailssh: avoid user ssh configuration in tests

net/dns/resolver/tsdns.go, net/dns/resolver/tsdns_test.go
For now, I've opted not to do the inverse (reverse-lookup on these IPs into these via domain names) because I think that would look weird in stuff like traceroute - but I can add it in if you like.
=> net/dns/resolver: support magic resolution of via-<siteid>.<ip4> domains

tsnet/tsnet.go
There was a typo in the check it was doing `!ok` instead of `ok`, this
restructures it a bit to read better.
Fixes #4506
=> tsnet: fix mem.Store check for normal nodes

net/dns/manager_darwin.go, net/dns/manager_default.go
This populates DNS suffixes ("ts.net", etc) in /etc/resolver/* files
to point to 100.100.100.100 so MagicDNS works.
It also sets search domains.
Updates #4276
=> net/dns: add start of a tailscaled-on-macOS DNS OSConfigurator

net/dns/resolver/forwarder.go, net/dns/resolver/tsdns.go
Updates #2067
This should help us determine if more robust control of edns parameters & implementing answer truncation is warranted, given its likely complexity.
=> net/dns/resolver: add metric for number of truncated dns packets

cmd/tailscale/cli/up.go
Looks like we accept both via CleanupArgs, but the other help output lists it as `auth-key` so this just makes that consistent.
=> cmd/tailscale: s/-authkey/-auth-key/ in help text

ipn/prefs.go, ipn/prefs_test.go
Like 888e50e1, but more aggressive.
Updates #4538 (likely fixes)
Updates #3488
=> ipn: always treat login.tailscale.com as controlplane.tailscale.com

control/controlclient/direct.go
In debugging #4541, I noticed this log print was always empty.
The value printed was always zero at this point.
Updates #4541
=> control/controlclient: fix log print with always-empty key

cmd/tailscaled/tailscaled.go, control/controlclient/direct.go, control/controlclient/direct_test.go, control/controlclient/noise.go, control/controlhttp/client.go, control/controlhttp/http_test.go, ipn/ipnlocal/local.go, net/tsdial/tsdial.go, tsnet/tsnet.go
The connections returned from SystemDial are automatically closed when
there is a major link change.
Also plumb through the dialer to the noise client so that connections
are auto-reset when moving from cellular to WiFi etc.
Updates #3363
=> net/tsdial: add SystemDial as a wrapper on netns.Dial

api.md
For consistency with the other parts of the TOC.
My vscode settings also removed some trailing spaces.
=> api.md: remove descriptions from TOC

net/tshttpproxy/tshttpproxy_synology.go, net/tshttpproxy/tshttpproxy_synology_test.go
Currently we try to use `https://` when we see `https_host`, however
that doesn't work and results in errors like `Received error: fetch
control key: Get "https://controlplane.tailscale.com/key?v=32":
proxyconnect tcp: tls: first record does not look like a TLS handshake`
This indiciates that we are trying to do a HTTPS request to a HTTP
server. Googling suggests that the standard is to use `http` regardless
of `https` or `http` proxy
Updates #4395, #2605
=> net/tshttpproxy: use http as the scheme for proxies

api.md
This reverts commit dd6472d4e87f823cb14a611a582afc25827cc46b.
Reason: it appears I was just really really wrong or confused.
We added it to the old internal API used by the website instead,
not to the "v2" API.
Updates #2120
Updates #4571
=> Revert "api: document preauthorized auth keys"

tailcfg/tailcfg_clone.go, util/codegen/codegen.go
goimports is a superset of gofmt that also groups imports.
(the goimports tool also adds/removes imports as needed, but that
part is disabled here)
=> util/codegen: format generated code with goimports, not gofmt

client/tailscale/tailscale.go, cmd/proxy-to-grafana/proxy-to-grafana.go, cmd/tailscale/cli/bugreport.go, cmd/tailscale/cli/cert.go, cmd/tailscale/cli/cli.go, cmd/tailscale/cli/debug.go, cmd/tailscale/cli/down.go, cmd/tailscale/cli/file.go, cmd/tailscale/cli/id-token.go, cmd/tailscale/cli/ip.go, cmd/tailscale/cli/logout.go, cmd/tailscale/cli/nc.go, cmd/tailscale/cli/netcheck.go, cmd/tailscale/cli/ping.go, cmd/tailscale/cli/ssh.go, cmd/tailscale/cli/status.go, cmd/tailscale/cli/up.go, cmd/tailscale/cli/version.go, cmd/tailscale/cli/web.go, tsnet/tsnet.go
Remove all global variables, and clean up tsnet and cmd/tailscale's usage.
This is in prep for using this package for the web API too (it has the
best package name).
=> client/tailscale: move/copy all package funcs to new LocalClient type

ipn/ipnlocal/local.go, ipn/prefs.go, ipn/prefs_test.go
The Mac client was using it, but it had the effect of the `RouteAll`
("Use Tailscale subnets") pref always being enabled at startup,
regardless of the persisted value.
enforceDefaults was added to handle cases from ~2 years ago where
we ended up with persisted `"RouteAll": false` values in the keychain,
but that should no longer be a concern. New users will get the default
of it being enabled via `NewPrefs`.
There will be a corresponding Mac client change to stop passing in
enforceDefaults.
For #3962
=> ipn: remove enforceDefaults option from PrefsFromBytes

ipn/backend.go, ipn/fake_test.go, ipn/handle.go, ipn/ipnlocal/local.go, ipn/message.go
No callers remain (last one was removed with
tailscale/corp@1c095ae08fcc21362db65035a117672a71b4a081), and it's
pretty esoteric.
=> ipn: remove FakeExpireAfter Backend function

ipn/ipnlocal/local.go, ssh/tailssh/tailssh.go
Currently the ssh session isn't terminated cleanly, instead the packets
are just are no longer routed to the in-proc SSH server. This makes it
so that clients get a disconnection when the `RunSSH` pref changes to
`false`.
Updates #3802
=> ssh/tailssh,ipn/ipnlocal: terminate any active sessions on `up --ssh=false`

client/tailscale/acl.go, client/tailscale/apitype/controltype.go, client/tailscale/devices.go, client/tailscale/dns.go, client/tailscale/localclient.go, client/tailscale/routes.go, client/tailscale/tailnet.go, client/tailscale/tailscale.go
This was work done Nov-Dec 2020 by @c22wen and @chungdaniel.
This is just moving it to another repo.
=> client/tailscale: move API client for the control admin API

cmd/tailscaled/tailscaled.go, ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi.go, net/dns/manager.go, net/dns/resolver/forwarder.go, net/dns/resolver/tsdns.go, net/dns/resolver/tsdns_test.go, net/tstun/wrap.go, tsnet/tsnet.go, wgengine/netstack/netstack.go, wgengine/netstack/netstack_test.go, wgengine/userspace.go, wgengine/watchdog.go
Note to reviewers: This change was not conducive to being split into multiple atomic PRs. Instead, I've split it into multiple commits that can be reviewed in progression.
=> Move magicDNS to netstack instead of handcrafted UDP

cmd/tailscale/cli/ping.go, control/controlclient/direct.go, ipn/backend.go, ipn/fake_test.go, ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go, ipn/message.go, net/packet/icmp.go, net/packet/packet.go, net/tstun/wrap.go, tailcfg/tailcfg.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
```
control: ping to 8.8.8.8 completed in 0.0129. pinger.Ping took 17.361535ms seconds
control: postPingResult: sending ping results to http://localhost:31544/pong/a42f028ba0636fea63d348a80bb6b185 ...
control: postPingResult complete to http://localhost:31544/pong/a42f028ba0636fea63d348a80bb6b185 (after 1ms)```
=> net/ping, control/controlclient: add ICMP pings

control/controlclient/auto.go, control/controlclient/controlclient_test.go, control/controlclient/direct.go, control/controlclient/status.go, ipn/ipnlocal/local.go
Currently, when SetNetInfo is called it sets the value on
hostinfo.NetInfo. However, when SetHostInfo is called it overrides all
of the hostinfo object which may race with SetNetInfo.
Instead of trying to solve that race, store NetInfo separately and combine when needed.
Updates #tailscale/corp#4824 (maybe fixes)
=> control/controlclient: store netinfo and hostinfo separately

words/scales.txt, words/tails.txt
There has been a lot of talk about Bees at Tailscale recently, and
naturally, with it being Tailscale, we thought to ourselves:
Do Bees have a tail and/or scales?
Tailscale has a long track record of [scientific](https://github.com/tailscale/tailscale/pull/3777) [rigor](https://github.com/tailscale/tailscale/pull/3778) around the
validity of the inclusions on the tails and scales list, and this time
will be no exception.
Our research has found that Bees, in particular the Honey Bee, produces
[wax scales](https://bee-health.extension.org/abdomen-of-the-honey-bee/#Wax_Scales) on their abdomens and thus should be included. As for tails;
'Stabby-tails' - Tailscale Employee, 2022
No further justification needed, it will be included.
This change includes Bee in both tails.txt and scales.txt. …
=> words: after a Series of discussions, Bees should be included

client/tailscale/localclient.go
It was using a mix.
Found by @maisem.
=> client/tailscale: fix ExpandSNIName on non-default LocalClient

util/clientmetric/clientmetric.go
Necessary to force flushing of client metrics more aggressively in
dev/test mode.
=> util/clientmetric: add ResetLastDeltaForTest function

util/clientmetric/clientmetric.go
Followup to 7966aed1e008936ea0fad6c63bd72461cdc55648 to pick up
review feedback that was accidentally left out.
=> util/clientmetric: switch to TestHooks struct for test-only functions

go.mod, go.sum, tstest/integration/vms/distros.go
The hujson package transition to just being a pure AST
parser and formatter for HuJSON and not an unmarshaler.
Thus, parse HuJSON as such, convert it to JSON,
and then use the standard JSON unmarshaler.
=> tstest/integration/vms: use hujson.Standardize instead of hujson.Unmarshal

ssh/tailssh/incubator.go, ssh/tailssh/incubator_linux.go
This has the added benefit of displaying the MOTD and reducing our
dependency on the DBus interface.
Fixes #4627
Updates #3802
=> ssh/tailssh: exec into `login` when launching a shell

cmd/tailscaled/tailscaled.go
Enables the behavior described in the statepath flag, where if only statedir is passed, then state is statedir/tailscaled.state.
=> cmd/tailscaled: use --statedir as documented

net/tstun/wrap.go, wgengine/userspace.go
We were marking them as gauges, but they are only ever incremented,
thus counter is more appropriate.
=> net/tstun, wgengine: use correct type for counter metrics

util/clientmetric/clientmetric.go, util/clientmetric/clientmetric_test.go
The prefix is a signal to tsweb to treat this as a gauge metric when
generating the Prometheus version.
=> util/clientmetric: add gauge_ name prefix when uploading names

wgengine/magicsock/magicsock.go
We don't increment the metricRecvData anywhere, just the per-protocol
ones.
=> wgengine/magicsock: remove unused metric

wgengine/filter/filter_test.go, wgengine/filter/tailcfg.go
Profiling identified this as a fairly hot path for growing a slice.
Given this is only used in control & when a new packet filter is recieved, this shouldnt be hot in the client.
=> wgengine/filter: preallocate some hot slices in MatchesFromFilterRules

ipn/ipnlocal/local.go
This fixes the "tailscale up --authkey=... --ssh" path which wasn't setting the bit.
Updates #3802
=> ipn/ipnlocal: add missing place where we set the SSH atomic

scripts/installer.sh
https://xcp-ng.org/
Fixes https://github.com/tailscale/tailscale/issues/4655
Tested on a VM running Xen Enterprise 8.2.1
=> scripts/installer.sh: add Xen Enterprise

logpolicy/logpolicy.go, logtail/logtail.go, logtail/logtail_test.go
Allows instances that are running with the same machine ID (due to
cloning) to be distinguished.
For tailscale/corp#5244
=> logtail: add instance metadata to the entry logtail

cmd/tailscale/cli/ssh.go, cmd/tailscale/cli/ssh_exec.go, cmd/tailscale/cli/ssh_exec_js.go, cmd/tailscale/cli/ssh_exec_windows.go
Adds a stub for syscall.Exec when GOOS=js. We also had a separate branch
for Windows, might as well use the same mechanism there too.
For #3157
=> cmd/tailscale/cli: fix ssh CLI command breaking the Wasm build

control/controlclient/direct.go
=> control/controlclient: avoid Noise protocol for js/wasm for now

ipn/localapi/localapi.go
Updates: #4738
This is the server-side change for implementing an Interactive Login via the localapi.
I noticed that the function `StartLoginInteractive()` on `LocalBackend` has no error return type, so i'll be looking to the core maintainers/reviewers if this is acceptable for localapi. I think it would be beneficial to catch errors and return 500 just like the logout api but i'm leaving that open for review.
=> ipn/localapi: implement LoginInteractive via localapi

wgengine/router/ifconfig_windows.go, wgengine/router/ifconfig_windows_test.go
Fixes #4647
It seems that Windows creates a link-local address for the TUN driver, seemingly based on the (fixed) adapter GUID. This results in a fixed MAC address, which for some reason doesn't handle loopback correctly. Given the derived link-local
address is preferred for lookups (thanks LLMNR), traffic which addresses the current node by hostname uses this broken address and never works.
To address this, we remove the broken link-local address from the wintun adapter.
@raggi IIRC you have a Windows machine? Are you able to test this live?
=> wgengine/router: delete hardcoded link-local address on Windows

ssh/tailssh/incubator.go
Otherwise, the shell exits immediately causing applications like mosh
and VSCode to fail.
=> ssh/tailssh: only use `login` with TTY sessions

ipn/ipnlocal/local.go, ipn/prefs.go, ssh/tailssh/tailssh.go
Also lazify SSHServer initialization to allow restarting the server on a
subsequent `tailscale up`
=> ipn/ipnlocal: shutdown sshServer on tailscale down

hostinfo/hostinfo_freebsd.go, hostinfo/hostinfo_linux.go
Use `unix.ByteSliceToString` in `osVersionFreebsd` and `osVersionLinux` to
convert the `Utsname.Release` `[]byte` field to `string`.
=>  hostinfo: use ByteSliceToString from golang.org/x/sys/unix

cmd/tailscale/cli/down.go, cmd/tailscale/cli/risks.go, cmd/tailscale/cli/ssh.go, cmd/tailscale/cli/ssh_unix.go, cmd/tailscale/cli/up.go
This makes it so that the user is notified that the action
they are about to take may result in them getting disconnected from
the machine. It then waits for 5s for the user to maybe Ctrl+C out of
it.
It also introduces a `--accept-risk=lose-ssh` flag for automation, which
allows the caller to pre-acknowledge the risk.
The two actions that cause this are:
- updating `--ssh` from `true` to `false`
- running `tailscale down`
=> cmd/tailscale/cli: add lose-ssh risk

net/dns/resolver/tsdns.go, net/dns/resolver/tsdns_test.go
Currently we only support `via-<site-id>.<IPv4>`, however that does not
work with Google Chrome which parses `http://via-1.10.0.0.1` as a search
string and not as a URL. This commit introduces `<IPv4>.via-<site-id>`
(`http://10.0.0.1.via-1`) which is parsed correctly by Chrome.
Updates #3616
=> net/dns/resolver: add support for <IPv4>.via-<site-id>

cmd/tailscale/cli/status.go, cmd/tailscale/cli/up.go, control/controlclient/auto.go, health/health.go, ipn/ipnlocal/local.go
This PR does two things:
1) It adds a `timeout` flag to `tailscale up`.
> maximum amount of time (in seconds) to wait for tailscaled to enter a Running state; default (0) blocks forever
2) It augments the `health` package with authentication routine error state. If authentication with coordination is desired and failing, the last error encountered will be surfaced via the `Health` field in localapi's status response.
Both of these changes are in response to #3713 where `tailscale up` was blocked indefinitely as coordination TLS cert validation failed due to a drifted clock. This can also happen when coordination is simply unreachable/firewalled from `tailscaled`, and in such a case the error will also be available via `tailscale status`.
Example:
start `tailscaled`:
```
% go run . …
```
=> surface authentication errors via status.Health

cmd/tailscale/cli/up.go
This reverts commit 03e3e6abcd39239eca710144e329d5e8ef935a2d
in favor of #4785.
=> Revert "cmd/tailscale/cli: disallow --ssh on Synology"

ipn/ipnlocal/local.go
On DSM7 as a non-root user it'll run into problems.
And we haven't tested on DSM6, even though it might work, but I doubt
it.
Updates #3802
Updates tailscale/corp#5468
=> ipn/ipnlocal: prevent attempting to run SSH on Synology for now

hostinfo/hostinfo_linux.go, version/distro/distro.go
```
root@WDMyCloud HD_a2 # ./tailscale debug hostinfo
{
"IPNVersion": "1.25.0-dev20220605-t7fea52e02",
"OS": "linux",
"OSVersion": "5.22.113",
"Desktop": false,
"DeviceModel": "WD My Cloud Gen2: Marvell Armada 375",
"Hostname": "WDMyCloud",
"GoArch": "arm"
}
```
Updates https://github.com/tailscale/tailscale/issues/4622
=> hostinfo,distro: Identify Western Digital MyCloud devices.

tsweb/tsweb.go, tsweb/tsweb_test.go
Fixes the current http://pkgs.tailscale.com/ redirect to https:///
as that server doesn't configure the Port80Handler.FQDN field.
=> tsweb: fix Port80Handler redirect to https with FQDN unset

cmd/tailscale/cli/ssh.go
Updates #3802
Updates #4518
Fixes #4628
=> cmd/tailscale/cli: disable 'tailscale ssh' on sandboxed macOS

ipn/ipnlocal/peerapi_h2c.go, ipn/localapi/cert.go, ipn/localapi/disabled_stubs.go, ipn/localapi/profile.go, net/netns/socks.go, net/portmapper/disabled_stubs.go, net/portmapper/upnp.go, portlist/netstat.go, portlist/netstat_exec.go, wgengine/magicsock/debugknobs.go, wgengine/magicsock/debugknobs_stubs.go
It has similar size constraints. Saves ~1.9MB from the Wasm build.
Updates #3157
=> wasm: exclude code that's not used on iOS for Wasm too

logpolicy/logpolicy.go, tsnet/tsnet.go
refactor logpolicy config loading to make it easier to reuse from outside the package.  Within tsnet, setup a basic logtail config.
Fixes #3866
=> tsnet: use proper log ID

tailcfg/tailcfg.go, tailcfg/tailcfg_test.go
This commit adds a helper to check if SSH is enabled. We're currently checking the SSH_HostKeys field in a few places, but later plan to add an explicit bool. This helper makes the check and any future changes easier.
Signed-off-by: Ross Zurowski <ross@rosszurowski.com>
=> tailcfg: add TailscaleSSHEnabled helper check

log/logheap/logheap.go, log/logheap/logheap_js.go, wgengine/watchdog.go, wgengine/watchdog_js.go
We can use the browser tools to profile, pprof adds 200K to the binary size.
Updates #3157
=> wasm: drop pprof dependency

logtail/id.go
It is not idiomatic for Go code to panic for situations that
can be normal. For example, if a server receives PrivateID
from a client, it is normal for the server to call
PrivateID.PublicID to validate that the PublicID matches.
However, doing so would panic prior to this change.
=> logtail: do not panic in PrivateID.PublicID

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
Specifically, when trying to use the Taildrop feature while not connected to the Tailnet.
For reference, the video below captures the error message. It's really minor but I didn't pay attention to my tailscale status and was checking everything else but my actual connection to the tailnet.
https://user-images.githubusercontent.com/1466314/172544322-fc7b4d2f-be3e-4613-8ad7-f3a3c332d5ec.mp4
=> Update a Taildrop error message

net/portmapper/disabled_stubs.go, net/portmapper/upnp.go, tstest/iosdeps/iosdeps_test.go
In the 1.27 unstable releases we set the min-version to iOS15,
which means we have 50 MBytes of RAM in the Network Extension.
https://tailscale.com/blog/go-linker/
Include the UPnP/NAT-PMP/PCP portmapper support now that there
is room for it.
Fixes https://github.com/tailscale/tailscale/issues/2495
=> net/portmapper: enable for iOS

tsnet/tsnet.go
Use the "tailscaled" prefix instead of "tsnet" for state file names:
1. It is consistent with the pre-existing `{{Dir}}/tailscaled.state` file.
2. It makes the file layout of `tsnet` and `tailscaled` identical,
so that they are compatible with each other.
=> tsnet: use tailscaled as prefix for state file names

util/deephash/deephash.go, util/deephash/deephash_test.go
```
Hash-8              67.3µs ±20%    76.5µs ±16%     ~     (p=0.143 n=10+10)
HashMapAcyclic-8    63.0µs ± 2%    56.3µs ± 1%  -10.65%  (p=0.000 n=10+8)
TailcfgNode-8       9.18µs ± 2%    6.52µs ± 3%  -28.96%  (p=0.000 n=9+10)
HashArray-8          732ns ± 3%     709ns ± 1%   -3.21%  (p=0.000 n=10+10)
name              old alloc/op   new alloc/op   delta
Hash-8               24.0B ± 0%     24.0B ± 0%     ~     (all equal)
HashMapAcyclic-8     0.00B          0.00B          ~     (all equal)
TailcfgNode-8        0.00B          0.00B          ~     (all equal)
HashArray-8          0.00B          0.00B          ~     (all equal)
name              old allocs/op  new allocs/op  delta
Hash-8                1.00 ± 0%      1.00 ± 0%     ~ …
```
=> util/deephash: don't track cycles on non-recursive types

go.mod, go.sum
Otherwise we crash at startup with Go 1.19beta1.
Updates #4872
=> go.mod: bump go4.org/unsafe/assume-no-moving-gc for Go 1.19beta1

control/controlclient/auto.go, control/controlclient/direct.go
Step 1 of many, cleaning up the direct/auto client & restarting map
requests that leads to all the unnecessary map requests.
Updates tailscale/corp#5761
=> control/controlclient: start simplifying netmap fetch APIs

control/controlclient/client.go, ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go
Client.SetExpirySooner isn't part of the state machine. Remove it from
the Client interface.
And fix a use of LocalBackend.cc without acquiring the lock that
guards that field.
=> control/controlclient, ipn/ipnlocal: remove Client.SetExpirySooner, fix race

ssh/tailssh/incubator.go, ssh/tailssh/incubator_darwin.go, ssh/tailssh/incubator_linux.go
Fixes #4931 - well seems to - with this change I am able to `ssh` in successfully.
I don't know if other versions of MacOS would be different, and I'm not sure the best way to make this conditional in the code, but thought I'd contribute this as a step in the direction of solving.
=> /usr/bin/login on Mac requires different argument ordering

cmd/tailscale/cli/ssh.go, cmd/tailscale/cli/ssh_exec.go, cmd/tailscale/cli/ssh_exec_js.go, cmd/tailscale/cli/ssh_exec_windows.go
I got problem with using msys2's ssh.exe via tailscale.exe. If typing CTRL-C, the ssh.exe is always stopped. To avoid this, I tried to add some hack for handling os.Interrupt but it seems not working with msys2 runtime. However C:\Windows\System32\OpenSSH\ssh.exe works good. Then I added code to use C:\Windows\System32\OpenSSH\ssh.exe always on Windows.
=> use C:\Windows\System32\OpenSSH\ssh.exe

ssh/tailssh/tailssh.go, ssh/tailssh/tailssh_test.go
Whenever the SSH policy changes we revaluate all open connections to
make sure they still have access. This check was using the wrong
timestamp and would match against expired policies, however this really
isn't a problem today as we don't have policy that would be impacted by
this check. Fixing it for future use.
=> ssh/tailssh: always use current time for policy evaluation

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go
Fixes: #3808 
change the implicit fields checks on the `--operator` flag to allow it to be explicitly set to an empty string
Signed-off-by: soypete <miriah@tailscale.com>
=> cmd/tailscale: make up respect explicitly empty --operator= value

cmd/tailscale/cli/cli.go, cmd/tailscale/tailscale.go
Not all distributions build from package main.
=> cmd/tailscale: move call to cli.CleanUpArgs() from main() into cli.Run()

wgengine/netstack/netstack.go
Fixes netstack.Impl leaking goroutines after shutdown.
=> wgengine/netstack: close ipstack when netstack.Impl is closed

wgengine/router/callback.go, wgengine/router/router.go, wgengine/router/router_test.go
The iOS and macOS networking extension API only exposes a single setter
for the entire routing and DNS configuration, and does not appear to
do any kind of diffing or deltas when applying changes. This results
in spurious "network changed" errors in Chrome, even when the
`OneCGNATRoute` flag from df9ce972c79023e0b0535bffee6afb3d88e61dc3 is
used (because we're setting the same configuration repeatedly).
Since we already keep track of the current routing and DNS configuration
in CallbackRouter, use that to detect if they're actually changing, and
only invoke the platform setter if it's actually necessary.
Updates #3102
=> wgengine/router: avoid unncessary routing configuration changes

.github/workflows/windows-race.yml
=> .github/workflows: downgrade MinGW to work around windows-race failures

docs/k8s/run.sh
- TSD_SOCKS5_SERVER, argument passed to tailscaled --socks5-server
- TSD_HTTP_PROXY, argument passed to tailscaled -outbound-http-proxy-listen
- TSD_EXTRA_ARGS extra arguments passed to tailscaled
Fixes #4985
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
=> Add env vars for enabling socks5 and http proxies

go.mod, go.sum
To get:
https://github.com/WireGuard/wireguard-go/commit/c31a7b1ab47807f01613a571cc480f79d5fb4181
Diff:
https://github.com/WireGuard/wireguard-go/compare/95b48cdb3961..c31a7b1ab47807f01613a571cc480f79d5fb4181
Fixes #4992
=> go.mod: bump wireguard-go to set CLOEXEC on tun/netlink fds

logpolicy/logpolicy.go
If ConfigFromFile cannot find the configuration file,
we must not initialize it with NewConfig.
Instead, we need it to fail validation so that it eventually writes
a newly constructed configuration file.
Otherwise, new tailscale instances will never be able store a persistent
log config and start with a new config file upon every bootup.
=> logpolicy: fix config initialization bug

go.mod, go.sum, tka/aum.go, tka/aum_test.go, tka/key.go, tka/key_test.go, tka/tka.go
This is the first in a series of PRs implementing the internals for the Tailnet Key Authority. This PR implements the `AUM` and `Key` types, which are used by pretty much everything else. Future PRs:
- The `State` type & related machinery
- The `Chonk` (storage) type & `Mem` implementation
- The `Authority` type and sync implementation
=> tka: implement AUM and Key types

tka/aum.go, tka/aum_test.go, tka/key.go, tka/state.go, tka/state_test.go
This is the second PR in a series implementing the Tailnet Key Authority. This PR implements the `State` type, which is the instantaneous value of the TKA at a moment in time. A `State` is mutated by applying an AUM, resulting in a new, independent state (like applying a log).
PRs to follow:
- The `Chonk` (storage) type & `Mem` implementation
- The `Authority` type and sync implementation
=> tka: implement State and logic for applying AUMs

ipn/localapi/localapi.go, util/clientmetric/clientmetric.go
Clients may have platform-specific metrics they would like uploaded
(e.g. extracted from MetricKit on iOS). Add a new local API endpoint
that allows metrics to be updated by a simple name/value JSON-encoded
struct.
=> ipn/localapi: add API for uploading client metrics

tka/tailchonk.go, tka/tailchonk_test.go
This PR is the third in a series implementing the Tailnet Key Authority. Chonks are responsible for efficient storage of AUMs and other TKA state.
For testing/prototyping I've implemented an in-memory version, but once we start to use this from tailscaled we'll implement a file-based version.
Future PRs:
- Implementing skeleton for `Authority` along with AUM-walking & chain resolution internals: `fastForward()`, `computeStateAt()`, `computeActiveChain()` etc
- `SyncOffer` computation and the remaining API surface
=> tka: implement Chonk type & an in-memory implementation

tsweb/tsweb.go, tsweb/tsweb_test.go
We make assertions about stringification of 0.5. IEEE floating point and
all reasonable proprietary floating point can exactly represent 0.5.
We don't make assertions about other floating point values, too brittle
in tests.
=> tsweb: add Float expvar support in varz

cmd/tailscaled/tailscaled.go
3f686688a6cff regressed the Windows beFirewallKillswitch code,
preventing the /firewall subprocess from running.
Fixes tailscale/corp#6063
=> cmd/tailscaled: fix Windows "Allow local LAN access" regression

tka/chaintest_test.go, tka/tka.go, tka/tka_test.go
This PR implements the nitty-gritty consensus internals. `fastForward` and `computeStateAt` are the 'core' algorithms that drive the whole thing.
A lot of the delta are tests or the new test helper `chaintest_test.go`.
=> tka: implement consensus & state computation internals

derp/derp_client.go
It's not the Tailscale version.
=> derp: add missing docs on clientInfo.Version

cmd/tailscale/cli/web.go
QTS 5.0 doesn't always pass a qtoken, in some circumstances
it sends a NAS_SID cookie for us to verify instead.
=> cmd/tailscale/cli/web: add QNAP NAS_SID authentication

cmd/tailscale/cli/cert.go
This was seeminlgy missed in 87ba528ae0c1138e8e8b2b1d91fbe2b97c84d9ae.
Fixes #5072
=> cmd/tailscale/cli: make cert use localClient

cmd/tailscale/cli/netcheck.go, net/netcheck/netcheck.go, net/netcheck/netcheck_test.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go
This lets us distinguish "no IPv6 because the device's ISP doesn't
offer IPv6" from "IPv6 is unavailable/disabled in the OS".
So far we've been inferring that based on peerapi binding behavior, this just tests the same binding behavior in netcheck directly.
=> net/netcheck: test for OS IPv6 support as well as connectivity.

control/controlclient/map.go, tailcfg/tailcfg.go
The control plane server doesn't send these to modern clients so we
don't need them in the tree. The server has its own serialization code
to generate legacy MapResponses when needed.
=> tailcfg: remove old DNS fields

.github/workflows/cross-wasm.yml, tstest/jsdeps/jsdeps.go
We now have the actual module that we need to build, so switch to
building it directly instead of its (expected) dependencies.
Also fix a copy/paste error in a jsdeps comment.
=> .github/workflows: update module that we try to build in cross-wasm

cmd/tsconnect/build.go, cmd/tsconnect/common.go, cmd/tsconnect/serve.go, cmd/tsconnect/tsconnect.go
When using tsconnect as a module in another repo, we cannot write to
the ./dist directory (modules directories are read-only by default -
there is a -modcacherw flag for `go get` but we can't count on it).
We add a -distdir flag that is honored by both the build and serve
commands for where to place output in.
Somewhat tedious because esbuild outputs paths relative to the working
directory, so we need to do some extra munging to make them relative
to the output directory.
=> cmd/tsconnect: allow building static resources in a different directory

control/controlclient/map.go, control/controlclient/map_test.go, tailcfg/tailcfg.go, wgengine/magicsock/magicsock.go
This adds a lighter mechanism for endpoint updates from control.
=> tailcfg, control/controlclient: add tailcfg.PeersChangedPatch [capver 33]

cmd/gitops-pusher/gitops-pusher.go
=> cmd/gitops-pusher: use fmt.Println for errors

Dockerfile, docs/k8s/run.sh
This has the benefit of propagating SIGINT to tailscaled, which in turn
can react to the event and logout in case of an ephemeral node.
Also fix missing run.sh in Dockerfile.
=> docs/k8s: use job control in run.sh

cmd/gitops-pusher/.gitignore, cmd/gitops-pusher/cache.go, cmd/gitops-pusher/gitops-pusher.go
This allows gitops-pusher to detect external ACL changes. I'm not sure what to call this problem, so I've been calling it the "three version problem" in my notes. The basic problem is that at any given time we only have two versions of the ACL file at any given point: the version in CONTROL and the one in the git repo. In order to check if there has been tampering of the ACL files in the admin panel, we need to have a _third_ version to compare against.
In this case I am not storing the old ACL entirely (though that could be a reasonable thing to add in the future), but only its sha256sum. This allows us to detect if the shasum in control matches the shasum we expect, and if that expectation fails, then we can react accordingly.
This will require additional configuration in CI, but I'm …
=> cmd/gitops-pusher: add etag cache file for the three version problem

net/dns/manager.go, net/dns/manager_windows.go, net/dns/manager_windows_test.go, net/dns/nrpt_windows.go
As discussed in previous PRs, we can register for notifications when group
policies are updated and act accordingly.
This patch changes nrptRuleDatabase to receive notifications that group policy
has changed and automatically move our NRPT rules between the local and
group policy subkeys as needed.
=> net/dns: add Windows group policy notifications to the NRPT rule manager

ipn/ipnlocal/local.go, logpolicy/logpolicy.go
Two commits in this PR:
----
logpolicy: put QNAP logs buffer in /tmp
Ongoing log writing keeps the spinning disks from hibernating.
Extends earlier implementation for Synology to also handle QNAP.
----
ipn/ipnlocal: prevent attempting to run SSH on QNAP for now
tailscaled runs as a non-root user, SSH is not immediately working.
=> QNAP: buffer logs & disable SSH

tool/go
Somewhere my local configuration or program versions are producing
marker files earlier in the process that lack a line terminator. This
doesn't need to cause an exit via set -e, we can just continue the
process. $extracted matches $REV anyway, so the process works.
=> tool/go: accept a marker file with no line terminator

.github/workflows/cross-wasm.yml, tool/yarn
Technically not the same as the wasm cross-compilation, but it's
closely connected to it.
Also includes some fixes to tool/yasm to make it actually work on
non-ARM platforms.
Fixes #5134
=> .github/workflows: add tsconnect static build to wasm GitHub action

go.mod
It was actually unused earlier, but I had a test program
in my git workdir, keeping go mod tidy from cleaning it.
(more CI needed, perhaps)
Updates #5162
=> go.mod: tidy, remove inet.af/netaddr

cmd/tailscaled/tailscaled.go, cmd/tailscaled/with_cli.go
Doesn't help much, though.
$ go install --tags=ts_include_cli ./cmd/tailscaled/
$ ls -lh ~/go/bin/tailscaled
-rwxr-xr-x 2 bradfitz bradfitz 34M Jul 27 11:00 /home/bradfitz/go/bin/tailscaled
$ go install --tags= ./cmd/tailscaled/
$ ls -lh ~/go/bin/tailscaled
-rwxr-xr-x 1 bradfitz bradfitz 23M Jul 27 11:00 /home/bradfitz/go/bin/tailscaled
$ ls -lh ~/go/bin/tailscale
-rwxr-xr-x 1 bradfitz bradfitz 13M Jul 25 21:30 /home/bradfitz/go/bin/tailscale
Fixes #2233
=> cmd/tailscaled: add opt-in support for linking CLI into daemon

scripts/check_license_headers.sh
=> scripts: update check_license_headers.sh to skip zsyscall_windows.go

cmd/tsconnect/src/index.ts, cmd/tsconnect/src/wasm_js.ts, cmd/tsconnect/wasm/wasm_js.go
The go wasm process exiting is a sign of an unhandled panic. Also
add a explicit recover() call in the notify callback, that's where most
logic bugs are likely to happen (and they may not be fatal).
Also fixes the one panic that was encountered (nill pointer dereference
when generating the JS view of the netmap).
Fixes #5132
=> cmd/tsconnect: add basic panic handling

build_dist.sh
- `--box` when ./cmd/tailscaled is built with this flag, it builds a
"toybox" style binary that includes tailscale and tailscaled.
- `--extra-small` strip the output binary and omit some dependencies
(currently AWS integration).
=> build_dist.sh: add --box and --extra-small flag to produce smaller and boxed binaries

cmd/tsconnect/build.go, cmd/tsconnect/common.go
Ensures that TypeScript checks pass before we deploy.
=> cmd/tsconnect: lint during build step

cmd/tsconnect/src/index.css
@import rules need to come first, they are (silently) ignored otherwise.
=> cmd/tsconnect: fix xterm CSS not being imported

ipn/ipnlocal/ssh.go, ipn/ipnlocal/ssh_test.go
If the host only has RSA, use its RSA + generate ecdsa + ed25519, etc.
Perhaps fixes https://twitter.com/colek42c/status/1550554439299244032 and something else that was reported.
=> ipn/ipnlocal: blend existing host SSH keys + newly-generated types as needed

tstest/resource.go
This fixes test failures like:
```
resource.go:34: goroutine count: expected 3, got 2
```
=> tstest: do not error if the there are fewer goroutines than at start

tka/chaintest_test.go, tka/scenario_test.go, tka/tka.go
- Fix a bug where processing valid-but-not-primary-chain AUMs from a peer would make processing explode, by supporting computing the state through non-primary chains.
- Start implementing some scenario-driven tests
=> tka: support processing non-primary forks, scenario-driven tests

cmd/tsconnect/index.html, cmd/tsconnect/src/index.css, cmd/tsconnect/src/login.ts, cmd/tsconnect/src/notifier.ts, cmd/tsconnect/src/ssh.ts, cmd/tsconnect/src/wasm_js.ts, cmd/tsconnect/wasm/wasm_js.go
Redoes the UI to be a form, with a username field and a host drop-down
(we also show non-Tailscale SSH hosts now, in a separate section)
Fixes #5139
=> cmd/tsconnect: allow SSH username to be specified

cmd/derper/derper.go
There aren't really any useful logs produced by derper.
=> cmd/derper: remove support for logtail logging

go.mod, go.sum
For https://github.com/google/gvisor/pull/7850 to quiet macOS warnings.
Updates #5240
=> go.mod: bump gvisor

tsweb/log.go
If the field is the zero value, then avoid serializing the field.
This reduces verbosity in server logs.
=> tsweb: mark AccessLogRecord fields as omitempty

ssh/tailssh/tailssh.go
Also rename it to expandDelegateURLLocked, previously it was trying
to acquire the mutex while holding the mutex.
Fixes #5235
=> ssh/tailssh: fix deadlock in expandDelegateURL

cmd/tailscale/cli/configure-host.go, cmd/tailscale/cli/debug.go, cmd/tailscale/cli/id-token.go, cmd/tailscale/cli/risks.go, cmd/tailscale/cli/up.go
Fix some fmt.Println and fmt.Printf calls that crept in since
5df7ac70d6a942d1bd4cb5b388aecbe161a1a0d1.
=> cmd/tailscale/cli: use printf and outln consistently

.github/workflows/cross-wasm.yml
Since we're keeping the JS support in the CLI (see https://github.com/tailscale/tailscale/pull/5265#issuecomment-1203078243),
make sure it keeps building.
=> .github/workflows: put back CLI in cross-wasm GitHub action

cmd/tsconnect/index.html, cmd/tsconnect/package.json, cmd/tsconnect/src/index.css, cmd/tsconnect/src/index.ts, cmd/tsconnect/src/login.ts, cmd/tsconnect/src/notifier.ts, cmd/tsconnect/src/ssh.ts, cmd/tsconnect/src/wasm_js.ts, cmd/tsconnect/wasm/wasm_js.go, cmd/tsconnect/yarn.lock
Makes the terminal container DOM node as large as the window (except for
the header) via flexbox. The xterm.js terminal is then sized to fit via
xterm-addon-fit. Once we have a computed rows/columns size, and we can
tell the SSH session of the computed size.
Required introducing an IPNSSHSession type to allow the JS to control
the SSH session once opened. That alse allows us to programatically
close it, which we do when the user closes the window with the session
still active.
I initially wanted to open the terminal in a new window instead (so that
it could be resizable independently of the main window), but xterm.js
does not appear to work well in that mode (possibly because it adds an
IntersectionObserver to pause rendering when the window is not visible,
and it ends up doing that when …
=> cmd/tsconnect: make terminal resizable

.github/workflows/cross-wasm.yml, cmd/tsconnect/build.go, cmd/tsconnect/common.go, cmd/tsconnect/index.html, cmd/tsconnect/serve.go, cmd/tsconnect/tsconnect.go
Avoids waterfalling of requests from the file (its load is triggered
from JavaScript).
Also has other cleanups to index.html, adding a <title> and moving the
<script> to being loaded sooner (but still not delaying page rendering
by using the defer attribute).
Also includes a `-fast-compression` flag when building that was useful in
speeding up the iteration loop when working on this.
=> cmd/tsconnect: prefetch main.wasm when serving

ipn/ipnlocal/peerapi.go, net/netaddr/netaddr.go, net/netcheck/netcheck.go, net/portmapper/igd_test.go, net/portmapper/portmapper.go, wgengine/magicsock/magicsock.go, wgengine/netstack/netstack.go
With caveat https://github.com/golang/go/issues/53607#issuecomment-1203466984
that then requires a new wrapper. But a simpler one at least.
Updates #5162
=> all: migrate code from netaddr.FromStdAddr to Go 1.18

cmd/tsconnect/src/wasm_js.ts, cmd/tsconnect/wasm/wasm_js.go
JS -> native nodes worked already, tested by exposing a fetch() method
to JS (it's Promise-based to be consistent with the native fetch() API).
Native nodes -> JS almost worked, we just needed to set the LocalBackend
on the user-space netstack.
Fixes #5130
=> cmd/tsconnect: make PeerAPI work

cmd/cloner/cloner.go, cmd/viewer/tests/tests.go, cmd/viewer/tests/tests_clone.go, cmd/viewer/tests/tests_view.go, cmd/viewer/viewer.go
This adds support for fields like `map[string]netaddr.IPPrefix`.
=> cmd/{cloner,viewer}: add support for map of structs without pointers

tka/sig.go, tka/sig_test.go, tka/tka.go, types/key/node.go, types/key/node_test.go
Am I holding `key.NodePublic` right?
Can I use `Raw32()` & `NodePublicFromRaw32()` and avoid the prefix overhead?
=> tka,types/key: implement direct node-key signatures

cmd/tsconnect/wasm/wasm_js.go, logtail/filch/filch_js.go, logtail/filch/filch_unix.go
Initialize logtail and provide an uploader that works in the
browser (we make a no-cors cross-origin request to avoid having to
open up the logcatcher servers to CORS).
Fixes #5147
=> cmd/tsconnect: make logtail uploading work

cmd/tsconnect/common.go, cmd/tsconnect/tsconnect.go, cmd/tsconnect/wasm/wasm_js.go
To improve the local development experience, this change allows a
control url to be passed in with the `--control-url=` flag.
If no flag is passed, the default remains the Tailscale controlled
control server set by `ipn.DefaultControlURL`.
=> tsconnect: add flag to specify control server

net/socks5/socks5.go
=> net/socks5: use new Go 1.19 binary.AppendByteOrder.AppendUintX

util/must/must.go
The Do function assists in calling of functions that must succeed.
It only interacts well with functions that return (T, err).
Signatures with more return arguments are not supported.
=> util/must: new package

tka/aum.go, tka/tailchonk.go, tka/tailchonk_test.go
This makes debugging easier, you can pass an AUMHash to a printf and get
a string that is easy to debug.
Also rearrange how directories/files work in the FS store: use the first
two characters of the string representation as the prefix directory, and
use the entire AUMHash string as the file name. This is again to aid
debugging: you can `ls` a directory and line up what prints out easily
with what you get from a printf in debug code.
=> tka: stable text representation of AUMHash

cmd/tsconnect/src/index.ts, cmd/tsconnect/src/wasm_js.ts, cmd/tsconnect/wasm/wasm_js.go
This change allows for an auth key to be specified as a url query param
for use in development mode. If an auth key is specified and valid, it
will authorize the client for use immediately.
Updates #5144
=> tsconnect: pass in authkey in dev mode

control/controlclient/direct.go, control/controlclient/map.go, control/controlclient/map_test.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go
=> tailcfg, control/controlclient: make Debug settings sticky in a map session [capver 37]

util/sha256x/sha256.go, util/sha256x/sha256_test.go
The hash.Hash provided by sha256.New is much more efficient
if we always provide it with data a multiple of the block size.
This avoids double-copying of data into the internal block
of sha256.digest.x. Effectively, we are managing a block ourselves
to ensure we only ever call hash.Hash.Write with full blocks.
Performance:
name    old time/op    new time/op    delta
Hash    33.5µs ± 1%    20.6µs ± 1%  -38.40%  (p=0.000 n=10+9)
The logic has gone through CPU-hours of fuzzing.
=> util/sha256: new package

util/sha256x/sha256.go, util/sha256x/sha256_test.go
Since Hash is a concrete type, we can make it such that
Sum never escapes the input.
=> util/sha256x: make Hash.Sum non-escaping

tailcfg/tailcfg.go, tailcfg/tailcfg_test.go
I documented capver 37 in 4ee64681a but forgot to bump the actual
constant. I've done this previously too, so add a test to prevent
it from happening again.
=> tailcfg: actually bump capver to 37, add test
