- tsnet/tsnet.go
... so callers can provide the AuthKey via mechanisms other than
environment variables which means multiple Servers can't be started
concurrently in the same process without coordination.
> tsnet: add Server.AuthKey field

- ssh/tailssh/incubator_linux.go
See https://github.com/tailscale/tailscale/issues/4924#issuecomment-1168201823
Arch uses a different login binary that makes the -h flag set the PAM
service to "remote". So if they don't have that configured, don't pass -h.
Thanks to @eddiezane for debugging!
Updates #4924
> ssh/tailssh: fix Tailscale SSH to Linux Arch machines

- Dockerfile
The Dockerfile directions said:
But that failed with:
Step 14/15 : FROM ghcr.io/tailscale/alpine-base:3.14
Head "https://ghcr.io/v2/tailscale/alpine-base/manifests/3.14": denied: denied
So I guess the Dockerfile.base part was undocumented. But it only had
one line anyway, so move it here to avoid the intermediate layer's
published permissions problem entirely.
> Dockerfile: fix build

- cmd/gitops-pusher/gitops-pusher.go
Apparently the API for running ACL tests returns a 200 if the ACL tests fail. This is weird, but we can handle it.
> cmd/gitops-pusher: correctly handle ACL tests failing

- cmd/proxy-to-grafana/proxy-to-grafana.go
> cmd/proxy-to-grafana: use localClient.GetCertificate

- ssh/tailssh/incubator.go
- ssh/tailssh/tailssh.go
Updates #4919
Co-authored-by: James Tucker <raggi@tailscale.com>
> ssh/tailssh: fix mosh over Tailscale SSH

- cmd/tailscaled/tailscaled.go
- net/tstun/tun.go
- net/tstun/tun_linux.go
- net/tstun/tun_macos.go
> net/tstun: diagnose /dev/net/tun fd leak, give better failure message

- ipn/localapi/cert.go
- version/distro/distro.go
- wgengine/router/router_linux.go
> ipn/localapi: define a cert dir for Synology DSM6

- tka/aum.go
- tka/tka.go
- tka/tka_test.go
After this, there should be one final PR to implement the Sync algorithm!
> tka: implement Authority API surface

- tka/sync.go
- tka/sync_test.go
Builds on #5080, review that first plz
This PR implements the synchronization mechanics for TKA: generating a SyncOffer, processing a SyncOffer to find an intersection, and computing the set of AUMs that should be transmitted to effect convergence.
This is the final PR implementing core mechanics for TKA.
> tka: implement synchronization mechanics

- cmd/tailscaled/tailscaled.go
- ipn/ipnlocal/local.go
> ipn/ipnlocal: logout ephemeral nodes on shutdown

- types/key/control.go
> types/key: add ControlPrivate.Shared wrapper too

- types/views/views.go
- types/views/views_test.go
We were starting to write these elsewhere as little unexported copies
in misc places.
> types/views: add SliceContains, View.ContainsFunc, View.IndexFunc

- ssh/tailssh/incubator.go
- ssh/tailssh/tailssh.go
- ssh/tailssh/tailssh_test.go
> ssh/tailssh: handle invalid connections in matchRule

- cmd/gitops-pusher/gitops-pusher.go
This is getting more complicated, so I want to port this to use ffcli like other commands instead of yoloing a command line framework. 
> cmd/gitops-pusher: port to use ffcli

- cmd/gitops-pusher/gitops-pusher.go
> cmd/gitops-pusher: fix minor bug with ACL tests

- types/key/machine.go
- types/key/machine_test.go
Follow-up to cfdb8626738d
Updates tailscale/corp#1709
> types/key: add MachinePrecomputedSharedKey.Open

- docs/k8s/README.md
Updates https://github.com/tailscale/tailscale-www/issues/1405.
Signed-off-by: Walter Poupore <walterp@tailscale.com>
> docs/k8s: add  `TS_` prefix to `AUTH_KEY`

- tailcfg/tailcfg.go
- tailcfg/tailcfg_clone.go
- tailcfg/tailcfg_view.go
> tailcfg: add views for SSHRule and SSHPrincipal

- types/views/views_test.go
```
goos: darwin
goarch: arm64
pkg: tailscale.com/types/views
BenchmarkSliceIteration/Cached-Len-10             380730              3144 ns/op
BenchmarkSliceIteration/Len-10                    372414              3147 ns/op
BenchmarkSliceIteration/direct-10                 367413              3144 ns/op
PASS
ok      tailscale.com/types/views       4.688s
```
> types/views: add BenchmarkSliceIteration

- util/deephash/deephash.go
- util/deephash/deephash_test.go
- util/deephash/testtype/testtype.go
> util/deephash: fix unexported time.Time hashing

- .github/workflows/linux.yml
- ipn/store/awsstore/store_aws.go
- ipn/store/awsstore/store_aws_stub.go
Drops tailscaled from 23M to 21M.
> ipn/store/awsstore: add "ts_omit_aws" build tag to reduce binary size

- logpolicy/logpolicy.go
- logtail/buffer.go
- logtail/logtail.go
Just reading the code again in prep for some alloc reductions.
> logtail,logpolicy: tweak minor cosmetic things

- tka/builder.go
- tka/builder_test.go
> tka: implement API surface for generating updates

- shell.nix
> shell.nix: update Go toolchain to 1.19

- tsweb/tsweb.go
The Hdr field allows the server to specify specific headers to set.
Example use case: server returns 429 with the "Retry-After" header set.
> tsweb: add HTTPError.Header

- tsnet/tsnet.go
> tsnet: log out ephemeral nodes on Close()

- tka/aum.go
- tka/scenario_test.go
- tka/state.go
- Finish `StaticValidate()`
- Add unit tests for attack scenarios: invalid AUM, unsigned AUM, badly-signed AUM
- Use the full keyID to de-dupe keys when calculating the signature weight out of an abundance of caution. The first 8 bytes are probably okay, but I'm not uber confident its a ful 64bits of entropy so best to be on the safe side.
> tka: add attack-scenario unit tests, defensive checks, resolve TODOs

- control/controlclient/direct.go
4001d0bf256 caused tests in another repo to fail with a crash, calling
a nil func. This might not be the right fix, but fixes the build.
> control/controlclient: fix crash in tests elsewhere when GetNLPublicKey is nil

- cmd/tsconnect/README.md
Outlines basic development, build and serving workflows.
> cmd/tsconnect: add README with instructions

- logtail/buffer.go
- logtail/logtail.go
- net/portmapper/igd_test.go
- wgengine/magicsock/magicsock.go
> logtail, net/portmapper, wgengine/magicsock: use fmt.Appendf

- control/controlclient/direct.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/peerapi.go
- net/dns/resolver/debug.go
- net/dns/resolver/forwarder.go
- net/tstun/wrap.go
- paths/paths.go
- version/prop.go
- wgengine/magicsock/magicsock.go
> all: use atomic.Pointer

- tsnet/tsnet.go
It should be safe to initialize multiple Server instances
without any resource leaks what-so-ever.
> tsnet: fix closing of filch buffer

- tsnet/tsnet.go
In a partially initialized state, we should cleanup
all prior resources when an error occurs.
> tsnet: cleanup resources upon start failure

- ipn/ipnlocal/local.go
> ipn/ipnlocal: fix log about local IPs when using exit nodes

- util/strs/strs.go
- util/strs/strs_test.go
> util/strs: add new package for string utility funcs

- util/must/must.go
> util/must: rename Do->Get, add Do

- net/dns/resolver/forwarder.go
Otherwise we just keep looping over the same thing again and again.
```
dns udp query: upstream nameservers not set
dns udp query: upstream nameservers not set
dns udp query: upstream nameservers not set
```
> net/dns/resolver: return SERVFAIL when no upstream resolvers set

- net/dns/resolver/forwarder.go
> net/dns/resolver: add comments clarifying nil error returns

- types/opt/bool.go
- types/opt/bool_test.go
> types/opt: support an explicit "unset" value for Bool

- util/deephash/deephash.go
- util/deephash/deephash_test.go
The logic of deephash is both simpler and easier to reason about
if values are always addressable.
In Go, the composite kinds are slices, arrays, maps, structs,
interfaces, pointers, channels, and functions,
where we define "composite" as a Go value that encapsulates
some other Go value (e.g., a map is a collection of key-value entries).
In the cases of pointers and slices, the sub-values are always addressable.
In the cases of arrays and structs, the sub-values are always addressable
if and only if the parent value is addressable.
In the case of maps and interfaces, the sub-values are never addressable.
To make them addressable, we need to copy them onto the heap.
For the purposes of deephash, we do not care about channels and functions.
For all non-composite kinds (e.g., strings and …
> util/deephash: always keep values addressable

- cmd/derper/cert.go
(Thanks for debugging, Roland!)
Fixes #4082
> cmd/derper: fix data race & server panic in manual cert mode

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/5192
> installer.sh: add manjaro-arm & EndeavourOS

- util/deephash/deephash.go
In Go 1.19, the reflect.Value.MapRange method uses "function outlining"
so that the allocation of reflect.MapIter is inlinable by the caller.
If the iterator doesn't escape the caller, it can be stack allocated.
See https://go.dev/cl/400675
Performance:
name               old time/op    new time/op    delta
HashMapAcyclic-24    31.9µs ± 2%    32.1µs ± 1%   ~     (p=0.075 n=10+10)
name               old alloc/op   new alloc/op   delta
HashMapAcyclic-24     0.00B          0.00B        ~     (all equal)
> util/deephash: avoid using sync.Pool for reflect.MapIter

- util/deephash/deephash.go
- util/deephash/deephash_test.go
Formatting a time.Time as RFC3339 is slow (see https://go.dev/issue/54093).
Now that we have efficient hashing of fixed-width integers,
just hash the time.Time as a binary value.
Performance:
Hash-24                19.0µs ± 1%    18.6µs ± 1%   -2.03%  (p=0.000 n=10+9)
TailcfgNode-24         1.79µs ± 1%    1.40µs ± 1%  -21.74%  (p=0.000 n=10+9)
> util/deephash: use binary encoding of time.Time

- atomicfile/atomicfile.go
> atomicfile: update docs to clarify behavior of argument

- net/dns/manager_windows.go
Like LLMNR, NetBIOS also adds resolution delays and we don't support it
anyway so just disable it on the interface.
Updates https://github.com/tailscale/tailscale/issues/1659
> net/dns: disable NetBIOS on Tailscale interfaces

- Makefile
> Makefile: add target for wasm and make it part of check

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/5377
> scripts/installer.sh: add `-y` for unattended install

- util/deephash/deephash.go
Any type that is memory hashable must not be recursive since
there are definitely no pointers involved to make a cycle.
> util/deephash: simplify typeIsRecursive

- util/deephash/deephash.go
Add support for maps and interfaces to the fast path.
Add cycle-detection to the pointer handling logic.
This logic is generally copied from the slow path.
A future commit will delete the slow path once
the fast path never falls back to the slow path.
Performance:
name                 old time/op    new time/op    delta
Hash-24                18.5µs ± 1%    14.9µs ± 2%  -19.52%  (p=0.000 n=10+10)
HashPacketFilter-24    2.54µs ± 1%    2.60µs ± 1%   +2.19%  (p=0.000 n=10+10)
HashMapAcyclic-24      31.6µs ± 1%    30.5µs ± 1%   -3.42%  (p=0.000 n=9+8)
TailcfgNode-24         1.44µs ± 2%    1.43µs ± 1%     ~     (p=0.171 n=10+10)
HashArray-24            324ns ± 1%     324ns ± 2%     ~     (p=0.425 n=9+9)
The additional cycle detection logic doesn't incur much slow down
since it only activates …
> util/deephash: expand fast-path capabilities

- tailcfg/tailcfg.go
Beginning to spitball what some of the regular TKA comms should look like. Thoughts?
> tailcfg: implement wire format for map request/response tka comms

- net/dns/publicdns/publicdns.go
- net/dns/resolver/forwarder.go
See https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/
> net/dns/publicdns: Add Mullvad DoH

- wgengine/pendopen.go
- wgengine/userspace.go
> wgengine: use a singleflight.Group to reduce status contention

- util/deephash/deephash.go
This helps pprof better identify which Go kinds take the most time
since the kind is always in the function name.
> util/deephash: move array and slice logic to separate function

- util/deephash/deephash.go
Rather than having two copies of []fieldInfo,
just maintain one and perform merging in the same pass.
> util/deephash: coalesce struct logic

- util/deephash/deephash.go
This helps pprof better identify which Go kinds take the most time
since the kind is always in the function name.
> util/deephash: move pointer and interface logic to separate function

- wgengine/wgcfg/writer.go
On sufficiently large tailnets, even writing the peer header (~95 bytes)
can result in a large amount of data that needs to be serialized and
deserialized. Only write headers for peers that need to have their
configuration changed.
> wgengine/wgcfg: only write peer headers if necessary

- wgengine/userspace.go
> wgengine: remove unused singleflight group

- .github/workflows/go_mod_tidy.yml
Fixes https://github.com/tailscale/tailscale/issues/4567
> CI: add `go mod tidy` workflow

- docs/k8s/proxy.yaml
Fixes https://github.com/tailscale/tailscale/issues/4999
> docs/k8s: add IPv6 forwarding in proxy.yaml

- ipn/localapi/cert.go
- version/version.go
Requested by a friend at Let's Encrypt.
cc @mcpherrinm
> ipn/localapi: send Tailscale version in ACME User-Agent

- tka/state.go
- tka/state_test.go
Was noodling around the code and saw a missing validation case.
> tka: static validate key computed from UpdateKey before applying state

- words/scales.txt
- words/tails.txt
> words: this title should have been a pun, but I chickened out

- tailcfg/tailcfg.go
- tailcfg/tka.go
Let the bikeshedding commence XD
/cc @bradfitz
> tailcfg: redo/implement TKA wire format for enablement, sync, disablement

- cmd/derper/bootstrap_dns.go
- cmd/derper/bootstrap_dns_test.go
- cmd/derper/derper.go
> cmd/derper: add support for unpublished bootstrap DNS entries

- docs/k8s/run.sh
It was previously using jobcontrol to achieve this, but that apparently
doesn't work when there is no tty. This makes it so that it directly
handles SIGINT and SIGTERM and passes it on to tailscaled. I tested this
works on a Digital Ocean K8s cluster.
Fixes #5512
> docs/k8s: make run.sh handle SIGINT

- go.mod
- go.sum
- wgengine/wgint/wgint.go
For https://github.com/WireGuard/wireguard-go/commit/b51010ba13f0a3e59808fbdb1566cd2c6b834b95
> go.mod, wgengine/wgint: bump wireguard-go

- wgengine/magicsock/magicsock.go
Both RebindingUDPConns now always exist. the initial bind (which now
just calls rebind) now ensures that bind is called for both, such that
they both at least contain a blockForeverConn. Calling code no longer
needs to assert their state.
> wgengine/magicksock: remove nullability of RebindingUDPConns

- wgengine/magicsock/magicsock.go
- wgengine/magicsock/magicsock_linux.go
Incoming disco packets are now dropped unless they match one of the
current bound ports, or have a zero port*.
The BPF filter passes all packets with a disco header to the raw packet
sockets regardless of destination port (in order to avoid needing to
reconfigure BPF on rebind).
If a BPF enabled node has just rebound, due to restart or rebind, it may
receive and reply to disco ping packets destined for ports other than
those which are presently bound. If the pong is accepted, the pinging
node will now assume that it can send WireGuard traffic to the pinged
port - such traffic will not reach the node as it is not destined for a
bound port.
*The zero port is ignored, if received. This is a speculative defense
and would indicate a problem in the receive path, or the BPF filter.
This …
> wgengine/magicsock: add filter to ignore disco to old/other ports

- wgengine/netstack/netstack.go
If we accept a forwarded TCP connection before dialing, we can
erroneously signal to a client that we support IPv6 (or IPv4) without
that actually being possible. Instead, we only complete the client's TCP
handshake after we've dialed the outbound connection; if that fails, we
respond with a RST.
> wgengine/netstack: only accept connection after dialing

- cmd/derper/derper.go
These errors aren't actionable and just fill up logs with useless data. See the following Go issue for more details:
https://golang.org/issue/26918
> cmd/derper: filter out useless HTTP error logs

- cmd/derper/derper.go
> cmd/derper: add robots.txt to disallow all

- net/dns/publicdns/publicdns.go
- net/dns/publicdns/publicdns_test.go
> net/dns/publicdns: support NextDNS DoH URLs with path parameters

- wgengine/router/router_linux.go
Fixes #3659
A common installation of OpenWRT involves use of the 'mwan3' package.
This package installs ip-tables rules like:
```
-A mwan3_fallback_policy -m mark --mark 0x0/0x3f00 -j MARK --set-xmark 0x100/0x3f00
```
which coupled with an ip rule:
```
2001: from all fwmark 0x100/0x3f00 lookup 1
```
has the effect of gobbling tailscale packets, because tailscale by default installs its policy routing rules at priority `52xx`. As such, if we are running on openWRT, detect a mwan3 config, AND detect a rule with a preference 2001 (corresponding to the first interface wman3 manages), we shift the priority of our policies to 13xx. This effectively puts us betwen mwan3's permit-by-src-ip rules and mwan3 lookup of its own routing table which would drop
the packet.
> wgengine/router: reduce routing rule priority for openWRT + mwan3

- net/dns/resolver/forwarder.go
> net/dns/resolver: set DNS-over-HTTPS Accept and User-Agent header on requests

- cmd/derper/derper.go
> cmd/derper: add /generate_204 endpoint

- net/stun/stun.go
- net/stun/stun_test.go
> net/stun: unmap IPv4 addresses in 16 byte STUN replies

- net/dns/resolved.go
Fixes #5619
Signed-off-by: nyghtowl <warrick@tailscale.com>
> net/dns: fix fmt error on Revert print

- cmd/tsconnect/src/lib/ssh.ts
The SSH session may be rendered in a different window that the one that is executing the script.
> cmd/tsconnect: use the parent window for `beforeunload` event listener

- net/dnscache/dnscache.go
- net/dnscache/dnscache_test.go
Change-Id: I4cde3a72e06dac18df856a0cfeac10ab7e3a9108
> net/dnscache: add better logging to bootstrap DNS path

- derp/derp.go
Makes the package description consistent with other documentation.
> derp: update DERP acronym expansion

- cmd/tailscaled/tailscaled.go
> cmd/tailscaled: respect $PORT on all platforms, not just Linux

- wgengine/magicsock/magicsock.go
From 5c42990c2fc019, not yet released in a stable build. Caught by existing tests.
Fixes #5685
> wgengine/magicsock: fix recently introduced data race

- tsweb/tsweb.go
> tsweb: export go_version in standard expvar vars

- wgengine/netstack/netstack.go
- wgengine/netstack/netstack_test.go
Change-Id: Ib6ebbaa11219fb91b550ed7fc6ede61f83262e89
> wgengine/netstack: handle 4via6 packets when pinging

- licenses/windows.md
Reverts tailscale/tailscale#5716
> Revert "licenses: update win/apple licenses"

- wgengine/netstack/netstack.go
- wgengine/netstack/netstack_test.go
As the comment in the code says, netstack should always respond to ICMP echo requests to a 4via6 address, even if the netstack instance isn't normally processing subnet traffic.
Follow-up to #5709
Change-Id: I504d0776c5824071b2a2e0e687bc33e24f6c4746
> wgengine/netstack: always respond to 4via6 echo requests

- tka/aum.go
- tka/builder.go
- tka/builder_test.go
- tka/tka.go
Should effectively limit how far tka needs to iterate backwards in time to build a chain.
> tka: Checkpoint every 50 updates

- chirp/chirp.go
- cmd/tailscale/cli/configure-host.go
- net/netcheck/netcheck.go
- net/nettest/listener.go
- wgengine/netstack/netstack.go
Fixes #5706
Signed-off-by: Emmanuel T Odeke <emmanuel@orijtech.com>
> all: fix resource leaks with missing .Close() calls

- util/singleflight/singleflight.go
Sync with golang.org/x/sync/singleflight at commit 8fcdb60fdcc0539c5e357b2308249e4e752147f1
Fixes #5790
Signed-off-by: Cuong Manh Le <cuong.manhle.vn@gmail.com>
> util/singleflight: sync with upstream

- docs/k8s/proxy.yaml
> docs/k8s: [proxy] fix sysctl command

- tsnet/tsnet.go
Identified while investigating a goroutine leak in a different repo.
> tsnet: fix netstack leak on Close

- go.mod
- go.sum
This PR addresses two potential known vulnerabilities by updating the dependencies that include the fixes.
> Address GO-2020-0042 and GO-2022-0969

- cmd/pgproxy/README.md
> cmd/pgproxy: link to blog post at the top.

- tailcfg/tailcfg.go
- tailcfg/tailcfg_clone.go
- tailcfg/tailcfg_view.go
> tailcfg: add views for ControlDialPlan

- logtail/logtail.go
The copy ID operates similar to a CC in email where a message is sent to both the primary ID and also the copy ID. A given log message is uploaded once, but the log server records it twice for each ID.
> logtail: support a copy ID

- net/tunstats/stats.go
- net/tunstats/stats_test.go
> net/tunstats: add Counts.Add

- ipn/ipnlocal/local.go
The macOS and iOS apps that used the /localapi/v0/file-targets handler were getting too many candidate targets. They wouldn't actually accept the file. This is effectively just a UI glitch in the wrong hosts being listed as valid targets from the source side.
> ipn/ipnlocal: fix taildrop target list UI bug

- go.mod
- go.sum
- ssh/tailssh/tailssh.go
- ssh/tailssh/tailssh_test.go
- tempfork/gliderlabs/ssh/context.go
- tempfork/gliderlabs/ssh/server.go
> ssh/tailssh: add support for sending multiple banners

- tsweb/tsweb.go
- tsweb/tsweb_test.go
This makes it easier to view prometheus metrics.
Added a test case which demonstrates the new behavior - the test initially failed as the output was ordered in the same order as the fields were declared in the struct (i.e. foo_a, bar_a, foo_b, bar_b). For that reason, I also had to change an existing test case to sort the fields in the new expected order.
Signed-off-by: Hasnain Lakhani <m.hasnain.lakhani@gmail.com>
> tsweb: sort varz by name after stripping prefix (#5778)

- ipn/localapi/localapi.go
Rather than a bunch of switch cases.
> ipn/localapi: put all the LocalAPI methods into a map

- cmd/ssh-auth-none-demo/ssh-auth-none-demo.go
ssh-auth-none.tailscale.dev port 2222
> cmd/ssh-auth-none-demo: put the hostname in the package doc

- tsweb/tsweb.go
- tsweb/tsweb_test.go
> tsweb: sort top-level expvars after removing type prefixes

- cmd/tailscaled/debug.go
- cmd/tailscaled/tailscaled.go
- cmd/tsconnect/common.go
- control/controlclient/auto.go
- ssh/tailssh/tailssh.go
- tsnet/example/tshello/tshello.go
- wgengine/bench/bench.go
Updates #5706
Signed-off-by: Emmanuel T Odeke <emmanuel@orijtech.com>
> all: fix more resource leaks found by staticmajor

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/4960
> scripts/installer.sh: add OSMC

- tstest/natlab/firewall.go
For future use in magicsock tests.
Updates #540
> tstest/natlab: add Firewall.Reset method to drop firewall state

- types/views/views.go
> types/view: add ContainsNonExitSubnetRoutes func

- logtail/logtail.go
The mobile implementation had a 2 minute ticker going all the time to do a channel send. Instead, schedule it as needed based on activity.
Then we can be actually idle for long periods of time.
Updates #3363
> logtail: change batched upload mechanism to not use CPU when idle

- logtail/logtail.go
Per chat. This is close enough to realtime but massively reduces number of HTTP requests. (which you can verify with TS_DEBUG_LOGTAIL_WAKES and watching tailscaled run at start)
By contrast, this is set to 2 minutes on mobile.
> logtail: default to 2s log flush delay on all platforms

- client/tailscale/localclient.go
- cmd/tailscale/cli/bugreport.go
- ipn/ipnlocal/local.go
- ipn/localapi/localapi.go
Change-Id: Id22e9f4a2dcf35cecb9cd19dd844389e38c922ec
> cmd/tailscale, ipn: enable debug logs when --report flag is passed to bugreport

- cmd/tailscale/cli/debug.go
> cmd/tailscale: correct --cpu-profile help text

- kube/client.go
> kube: handle 201 as a valid status code.

- control/controlhttp/http_test.go
Updates tailscale/corp#7446
Change-Id: Ifcf3b5176f065c2e67cbb8943f6356dea720a9c5
> control/controlhttp: try to avoid flakes in TestDialPlan

- cmd/tsconnect/src/app/ssh.tsx
- cmd/tsconnect/src/lib/ssh.ts
- cmd/tsconnect/src/types/wasm_js.d.ts
- cmd/tsconnect/wasm/wasm_js.go
Allows UI to display slightly more fine-grained progress when the SSH connection is being established.
Updates tailscale/corp#7186
> cmd/tsconnect: add progress and connection callbacks

- cmd/derper/derper.go
- cmd/derper/derper_test.go
- net/netcheck/netcheck.go
The Lufthansa in-flight wifi generates a synthetic 204 response to the DERP server's `/generate_204` endpoint. This PR adds a basic challenge/response to the endpoint; something sufficiently complicated that it's unlikely to be implemented by a captive portal. We can then check for the expected response to verify whether we're being MITM'd.
Follow-up to #5601
Change-Id: I94a68c9a16a7be7290200eea6a549b64f02ff48f
> cmd/derper, net/netcheck: add challenge/response to generate_204 endpoint

- api.md
> api.md: add expirySeconds as parameter to post Tailnet keys

- types/key/chal.go
> types/key: add ChallengePublic, ChallengePrivate, NewChallenge

- wgengine/magicsock/magicsock.go
During development of silent disco (#540), an alternate send policy for magicsock that doesn't wake up the radio frequently with heartbeats, we want the old & new policies to coexist, like we did previously pre- and post-disco.
We started to do that earlier in 5c42990c2fc01 but only set up the env+control knob plumbing to set a bool about which path should be used.
This starts to add a way for the silent disco code to update the send path from a separate goroutine. (Part of the effort is going to de-state-machinify the event based soup that is the current disco code and make it more Go synchronous style.)
So far this does nothing. (It does add an atomic load on each send but that should be noise in the grand scheme of things, and a even more rare atomic store of nil on node config …
> wgengine/magicsock: add start of alternate send path

- words/scales.txt
Beavers have scales, on their tails.
> words: beaver, the cutest of them all

- wgengine/router/router_linux.go
- wgengine/router/router_linux_test.go
Deleting may temporarily result in no addrs on the interface, which results in all other rules (like routes) to get dropped by the OS.
I verified this fixes the problem.
> wgengine/router: [linux] add before deleting interface addrs

- words/scales.txt
- words/tails.txt
What's better than getting a community request?
A community request from another Charlotte!
Bun and hops!
> words: for charlotte, by charlotte

- words/scales.txt
The cute little salak belongs there. It also evens the odds if tails start a mutiny against scales. Even though they outnumber scales, they should still know their place. Behind.
> words: even the odds with something that reminds you of vacation

- portlist/poller.go
- portlist/portlist.go
And respect envknob earlier. NewPoller has one caller and ignores errors; they just signal ipnlocal to log a warning and not use the portlist poller.
> portlist: add package doc, file comments, move a method to the right file

- portlist/portlist_test.go
To avoid annoying firewall dialogs on macOS and Windows, only run it on Linux by default without the flag.
> portlist: add a test that verifies changes are picked up over time

- scripts/installer.sh
> scripts/install.sh: add Ubuntu Kinetic Kudu

- shell.nix
Change-Id: Ic25e11a056a7624ebba923d2b87d947e24c41a20
> shell.nix: add graphviz

- ipn/ipnlocal/local.go
Caught this in a test in a different repo.
> ipn/ipnlocal: set prefs before calling tkaSyncIfNeeded

- cmd/tailscale/cli/cli.go
- cmd/tailscale/cli/cli_test.go
- cmd/tailscale/cli/set.go
- cmd/tailscale/cli/up.go
- ipn/prefs.go
- ipn/prefs_test.go
> cmd/tailscale/cli: add beginnings of `tailscale set`

- net/interfaces/interfaces_bsd.go
Fixes #6065
Change-Id: I7159b8cbb8d5f47c0668cf83e59167f182f1defd
> net/interfaces: don't dereference null pointer if no destination/netmask

- docs/webhooks/example.go
> docs/webhooks: add sample endpoint code

- control/controlclient/noise.go
In prep for stateful http2 noise connections.
Updates #5972
> control/controlclient: refactor noiseClient, connections, http2

- ipn/ipnlocal/local.go
This makes tags, creation time, exit node option and primary routes for the current node exposed via `tailscale status --json`
Fixes #6076
> ipn/ipnlocal: add tags and a few other details to self status

- cmd/tailscale/cli/cli.go
> cmd/tailscale/cli: make set's usage match up's, other than defaults

- cmd/tailscale/cli/ssh.go
Per user feedback.
Fixes #5877
> cmd/tailscale/cli: flesh out "tailscale ssh" CLI docs

- wgengine/netstack/netstack.go
Setting TCP KeepAlives for Tailscale SSH connections results in them unnecessarily disconnecting. However, we can't turn them off completely as that would mean we start leaking sessions waiting for a peer to come back which may have gone away forever (e.g. if the node was deleted from the tailnet during a session).
Updates #5021
> wgengine/netstack: use 72h as the KeepAlive Idle time for Tailscale SSH

- ssh/tailssh/incubator.go
> ssh/tailssh: use root / as cmd.Dir when users HomeDir doesn't exist

- prober/prober_test.go
This was tested by running 10000 test iterations and observing no flakes after this change was made.
Change-Id: Ib036fd03a3a17800132c53c838cc32bfe2961306
> prober: fix test flake

- go.mod
- go.sum
> go.mod: bump golang-x-crypto

- ipn/ipnlocal/state_test.go
- tstest/log.go
This switches from using an atomic.Bool to a mutex for reasons that are described in the commit, and should address the flakes that we're still seeing.
Fixes #3020
Change-Id: I4e39471c0eb95886db03020ea1ccf688c7564a11
> ipn/ipnlocal: fix test flake when we log after a test completes

- wgengine/netlog/logger.go
Exit node traffic is aggregated to protect the privacy of those using an exit node. However, it is reasonable to at least log which nodes are making most use of an exit node.
For a node using an exit node,
the source will be the taiscale IP address of itself, while the destination will be zeroed out.
For a node that serves as an exit node,
the source will be zeroed out,
while the destination will be tailscale IP address of the node that initiated the exit traffic.
> wgengine/netlog: preserve Tailscale addresses for exit traffic

- tailcfg/tailcfg.go
> tailcfg: bump CurrentCapabilityVersion for EarlyNoise

- net/netcheck/netcheck.go
- net/stun/stuntest/stuntest.go
- tailcfg/derpmap.go
> net/netcheck: deflake (maybe) magicsock's TestNewConn

- build_dist.sh
- cmd/tailscaled/tailscaled_bird.go
- net/tstun/tap_linux.go
- net/tstun/tap_unsupported.go
- net/tstun/tun.go
Change-Id: I7a39f4eeeb583b73ecffaf4c5f086a38e3a53e2e
> cmd/tailscaled, net/tstun: add build tags to omit BIRD and TAP

- cmd/containerboot/kube.go
> cmd/containerboot: don't write device ID into non-existent secret.

- cmd/containerboot/main.go
Only enable forwarding for an IP family if any forwarding is required for that family.
Fixes #6221.
> cmd/containerboot: be more targeted when enabling IP forwarding.

- docs/k8s/role.yaml
> docs/k8s: add secrets patching permission to the tailscale role.

- ipn/localapi/cert.go
I want to move the guts (after the HTTP layer) of the certificate fetching into the ipnlocal package, out of localapi.
As prep, refactor a bit:
* add a method to do the fetch-from-cert-or-as-needed-with-refresh, rather than doing it in the HTTP hander
* convert two methods to funcs, taking the one extra field (LocalBackend) then needed from their method receiver. One of the methods needed nothing from its receiver.
This will make a future change easier to reason about.
> ipn/localapi: refactor some cert code in prep for a move

- wgengine/netstack/netstack.go
It was eating TCP packets to peerapi ports to subnet routers.  Some of the TCP flow's packets went onward, some got eaten.  So some TCP flows to subnet routers, if they used an unfortunate TCP port number, got broken.
> wgengine/netstack: fix shouldProcessInbound peerapi non-SYN handling

- util/endian/little.go
Change-Id: I8275d158779c749a4cae2b4457d390871b4b8e3c
Signed-off-by: ysicing <i@ysicing.me>
> util/endian: add support on Loongnix-Server (loong64)

- cmd/tailscale/cli/debug.go
- ipn/ipn_clone.go
- ipn/ipn_view.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/serve.go
- ipn/store.go
> ipn/ipnlocal: start implementing web server bits of serve

- cmd/containerboot/main_test.go
- cmd/containerboot/test_tailscale.sh
- cmd/containerboot/test_tailscaled.sh
Right now just one test, because it's already a lot of scaffolding code to look at. In a followup I will table-ize the test and exercise other configurations.
> cmd/containerboot: add tests.

- cmd/containerboot/kube.go
- cmd/containerboot/main.go
- cmd/containerboot/main_test.go
- cmd/containerboot/test_tailscale.sh
Also fix a bug found while adding the tests, oops.
> cmd/containerboot: make a tests table, add more tests.

- ipn/ipn_clone.go
- ipn/ipn_view.go
- ipn/ipnlocal/peerapi.go
- ipn/ipnlocal/serve.go
- ipn/store.go
- tailcfg/tailcfg.go
> ipn/ipnlocal, tailcfg: wire up ingress peerapi

- ipn/ipnlocal/serve.go
- ipn/ipnlocal/serve_test.go
> ipn/ipnlocal: support https+insecure:// backend proxy targets

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/5763
> scripts/installer.sh: add Nobara Linux.

- ipn/ipnlocal/local.go
- ipn/ipnlocal/serve.go
- ipn/ipnlocal/serve_test.go
> ipn/ipnlocal: support serving files/directories too

- client/tailscale/localclient.go
- client/tailscale/localclient_test.go
> client/tailscale: document ServeConfig accessors a bit more

- .gitignore
> repo: add .vscode/ to .gitignore

- ipn/ipn_clone.go
- ipn/ipn_view.go
- ipn/ipnlocal/serve.go
- ipn/store.go
> ipn/ipnlocal: add optional TLS termination on proxied TCP connections

- ipn/prefs.go
> ipn: add AdvertisesExitNode and AdminPageURL accessors to PrefsView

- wgengine/router/router_userspace_bsd.go
Noticed when testing FUS on tailscale-on-macOS, that routing would break completely when switching between profiles. However, it would start working again when going back to the original profile tailscaled started with.
Turns out that if we change the addrs on the interface we need to remove and readd all the routes.
Updates #713
> wgengine/router: [bsd/darwin] remove and readd routes on profile change

- tsnet/tsnet.go
- tsnet/tsnet_test.go
> tsnet: be stricter about arguments to Server.Listen

- cmd/tailscale/cli/cli_test.go
> cmd/tailscale/cli: add outline of serve CLI tests

- cmd/tailscale/cli/cli_test.go
- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_test.go
(I should've done this to start with.)
> cmd/tailscale/cli: move earlier shell test to its own files

- cmd/tailscale/cli/cli.go
- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_test.go
The serve CLI doesn't exist yet, but we want nice tests for it when it does exist.
> cmd/tailscale/cli: continue fleshing out serve CLI tests

- ipn/ipnlocal/local.go
- ipn/ipnlocal/profiles.go
- ipn/ipnlocal/state_test.go
- tstest/integration/integration_test.go
> ipn/ipnlocal: delete profile on logout

- control/controlclient/direct.go
- health/health.go
- health/health_test.go
- ipn/ipnlocal/local.go
- net/dns/direct.go
- wgengine/router/ifconfig_windows.go
> health, DNS stuff

- ipn/ipnlocal/peerapi.go
> ipn/ipnlocal: fix error message typo in ingress peerapi handler

- tailcfg/tailcfg.go
> tailcfg: bump capver for ingress

- ipn/localapi/localapi.go
Exposes a REST-y API for interacting with the profile switching introduced in #6022.
> ipn/localapi: add LocalAPI endpoints for profile switching

- ipn/ipnlocal/network-lock.go
Found by @mihaip running tests in another repo. TKA code wasn't always checking enough to be sure a node-key was set for the current state.
Should fix some test breakages in https://github.com/tailscale/corp/pull/7904, but the failing `TestIPN` I don't think is network-lock related.
> ipn/ipnlocal: fix checks for node-key presence in TKA logic

- tsnet/tsnet.go
As requested in #6250 from @majst01.
> tsnet: add Server.ControlURL option

- ipn/ipnlocal/local.go
- ipn/ipnlocal/state_test.go
We do not need to wait for it to complete. And we might have to call Shutdown from callback from the controlclient which might already be holding a lock that Shutdown requires.
Updates #713
> ipn/ipnlocal: do controlclient.Shutdown in a different goroutine

- tailcfg/tailcfg.go
- tailcfg/tailcfg_clone.go
- tailcfg/tailcfg_test.go
- tailcfg/tailcfg_view.go
Yet unused. Future optimization for control.
> tailcfg: add Hostinfo.WireIngress bool

- ipn/ipnlocal/profiles.go
> ipn/ipnlocal: add client metrics for profile switching

- ssh/tailssh/tailssh.go
> ssh/tailssh: only call CloseWrite when both stdout and stderr are done

- control/controlclient/direct.go
No need for http://, etc. In case a control server sends a bogus value and GUIs don't also validate.
> control/controlclient: filter PopBrowserURL values to https schemes

- ipn/ipnlocal/local.go
> ipn/ipnlocal: check quad100 Host header in info page

- ipn/localapi/localapi.go
Change-Id: I5f570c04974598c7abae4017e4a7a0f63492c87c
> ipn/localapi: serve files with application/octet-stream Content-Type

- control/controlclient/direct.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/state_test.go
> ipn/ipnlocal: move URL validation to LocalBackend

- client/tailscale/apitype/apitype.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/peerapi.go
- net/tsdial/tsdial.go
> all: standardize on PeerAPI

- client/tailscale/apitype/apitype.go
- client/tailscale/localclient.go
- client/tailscale/tailscale.go
- cmd/containerboot/main.go
- cmd/tailscale/cli/debug.go
- cmd/tailscale/cli/up.go
- derp/derp_server.go
> all: standardize on LocalAPI

- ipn/ipnlocal/peerapi.go
- ipn/ipnlocal/peerapi_test.go
> ipn/ipnlocal: add some validation to PeerAPI

- ipn/ipnlocal/peerapi.go
- ipn/ipnlocal/peerapi_test.go
- tailcfg/tailcfg.go
> tailcfg: add CapabilityDebug

- ipn/ipnlocal/profiles.go
- ipn/ipnlocal/profiles_test.go
- ipn/prefs.go
> ipn/ipnlocal: prevent duplicate profiles of the same user

- ipn/localapi/localapi.go
The Mac and iOS LocalAPI clients make requests to it.
Slightly relaxes the checks added by #6346.
> ipn/localapi: also allow localhost as the LocalAPI host

- ipn/localapi/localapi.go
Change-Id: I028b6ab91229e2f824e5a69856ca9e1844f7486e
> ipn/localapi: set headers

- ipn/ipnlocal/local.go
> ipn/ipnlocal: fill out PeerAPIURLs in PeerStatus

- ipn/ipnserver/server.go
> ipn/ipnserver: validate Host header on debug ServeHTMLStatus status

- ipn/ipnlocal/local.go
- ipn/ipnlocal/state_test.go
> ipn/ipnlocal: strip NetworkLockKey from Prefs

- wgengine/magicsock/magicsock.go
This renames canP2P in magicsock to canP2PLocked to reflect
expectation of mutex lock, fixes a race we discovered in the meantime,
and updates the current stats.
> magicsock: clean up canp2p

- wgengine/magicsock/magicsock.go
- wgengine/magicsock/magicsock_test.go
There aren't any in the wild, other than one we ran on purpose to keep us honest, but we can bump that one forward to 0.100.
> control/controlclient, wgengine/magicsock: ignore pre-disco (pre-0.100) peers

- words/tails.txt
> words: add "coyote" to the wordlist for tailnet names

- words/tails.txt
> words: you goatta be kid'in me

- ipn/ipnlocal/local.go
- ipn/ipnstate/ipnstate.go
The earlier 5f6d63936f3 was not complete.
> ipn/ipnlocal: actually fill out PeerAPIURLs in PeerStatus

- ipn/ipnlocal/local.go
- version/prop.go
> ipn/ipnlocal: add health warning for unstable builds

- words/scales.txt
After consultation with @twitchyliquid64 , it has been agreed that a vibe, or vibes, can be felt in different quantifiable measures. That makes a vibe, or vibes, a scale thus it must be immortalized.
> words: good vibes only

- words/scales.txt
Scales do not exist without a banana.
> words: no explanation necessary

- words/tails.txt
The Bovini tribe is sorely underrepresented.
> words: add some cloven-hoofed ruminants

- ipn/ipnlocal/peerapi.go
> ipn/ipnlocal: send Content-Security-Policy, etc to peerapi browser requests

- cmd/tailscale/cli/risks.go
- tstest/integration/integration_test.go
The test would fail if I was running it over SSH.
> tstest/integration: add --accept-risk=all to tailscale down

- ipn/ipnlocal/profiles.go
- ipn/ipnlocal/profiles_test.go
Profile keys are not deleted but are instead set to `nil` which results in getting a nil error and we were not handling that correctly.
Updates #713
> ipn/ipnlocal: handle case when selected profile is deleted

- client/tailscale/localclient.go
- cmd/tailscale/cli/cli.go
- cmd/tailscale/cli/debug.go
- cmd/tailscale/cli/up.go
- cmd/tailscale/cli/web.go
- ipn/ipnlocal/local.go
- ipn/localapi/localapi.go
Updates #6417
Updates tailscale/corp#8051
> ipn, cmd/tailscale/cli: add LocalAPI IPN bus watch, Start, convert CLI

- net/dns/manager_windows.go
Updates #5753
Change-Id: I60f81bd3325d5ba5383b947c7a7aaa5b14e460f6
> net/dns: retry overwriting hosts file on Windows

- cmd/tailscale/cli/debug.go
> cmd/tailscale: fix 'debug local-creds' hostname

- cmd/derpprobe/derpprobe.go
Example output:
```
2022/11/23 16:11:00 Starting probe (may take up to 1m)
2022/11/23 16:11:00 (UDP→int1): 13ms
2022/11/23 16:11:00 derphttp.Client.Connect: connecting to derp-999 (int-int1)
2022/11/23 16:11:00 derphttp.Client.Connect: connecting to derp-999 (int-int1)
2022/11/23 16:11:00 (int1→int1): 13ms
2022/11/23 16:11:00 Probe results:
2022/11/23 16:11:00 good: (UDP→int1): 13ms, 0s ago
2022/11/23 16:11:00 good: (int1→int1): 13ms, 0s ago
2022/11/23 16:11:00 good: cert "derp2f.tailscale.com" good 2022-11-17T10:41:48Z - 2023-02-15T10:41:47Z
```
Updates #6478
> cmd/derpprobe: add -once flag for one-off CLI diagnostics

- cmd/tailscaled/tailscaled.go
- envknob/envknob.go
- envknob/envknob_nottest.go
- envknob/envknob_testable.go
- ipn/ipnlocal/profiles.go
- tstest/integration/integration_test.go
Centralize the fake GOOS stuff, start to use it more. To be used more in the future.
> envknob: add GOOS func

- control/controlclient/direct.go
- ipn/backend.go
- ipn/ipnlocal/local.go
- tailcfg/tailcfg.go
> tailcfg, ipn, controlclient: add MapResponse.ClientVersion, plumb to IPN bus

- ipn/ipnserver/server.go
> ipn/ipnserver: only permit the pre-HTTP LocalAPI protocol on Windows

- .github/workflows/linux.yml
> .github/workflows: use ubuntu-22.04 for qemu tests

- ipn/ipnlocal/local.go
- ipn/ipnlocal/profiles.go
- ipn/ipnlocal/profiles_test.go
Address comments from https://github.com/tailscale/tailscale/pull/6506#discussion_r1032454064
> ipn/ipnlocal,ipnserver: rename {,Set}CurrentUser to {,Set}CurrentUserID

- ipn/ipnlocal/local.go
- ipn/ipnlocal/network-lock.go
- ipn/ipnlocal/profiles.go
> ipn/ipnlocal: drop LocalBackend.inServerMode

- .gitignore
Also, updated ignore desc for .vscode/.
> gitignore: ignore direnv nix-shell environment cache

- client/tailscale/localclient.go
- cmd/tailscale/cli/network-lock.go
- ipn/ipnlocal/network-lock.go
- ipn/localapi/localapi.go
- tailcfg/tka.go
* Start implementing the UX as discussed
* Name updates
* Clientside-support / plumbing for optionally sending a disablement secret to support
> cmd/tailscale,ipn: improve UX of lock init command, cosmetic changes

- derp/derp_server.go
- derp/derp_test.go
Instead of iterating over the map to determine the preferred forwarder on every packet (which could happen concurrently with map mutations), store it separately in an atomic variable.
Fixes #6445
> derp: prevent concurrent access to multiForwarder map

- ipn/ipnlocal/local.go
> ipn/ipnlocal: sanitize prefs before sending over IPN Bus

- ipn/ipn_clone.go
- ipn/ipn_view.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/network-lock.go
- ipn/ipnlocal/profiles.go
- ipn/ipnlocal/state_test.go
- types/persist/persist.go
- types/persist/persist_clone.go
- types/persist/persist_test.go
- types/persist/persist_view.go
Supercedes https://github.com/tailscale/tailscale/pull/6557, precursor to trying https://github.com/tailscale/tailscale/pull/6546 again
> ipn,types/persist: add DisallowedTKAStateIDs, refactor as view type

- client/tailscale/localclient.go
- cmd/tailscale/cli/network-lock.go
- ipn/ipnlocal/network-lock.go
- ipn/ipnlocal/network-lock_test.go
- ipn/localapi/localapi.go
- tka/tka.go
Take 2 of https://github.com/tailscale/tailscale/pull/6546, builds on https://github.com/tailscale/tailscale/pull/6560
This time with (hopefully) more greenage! :grinning:
> cmd/tailscale,ipn: store disallowed TKA's in prefs, lock local-disable

- cmd/tailscale/cli/set.go
> cmd/tailscale/cli: add set --unattended on Windows

- docs/webhooks/example.go
Fixes #6572
Change-Id: I58610c46e0ea1d3a878f91d154db3da4de9cae00
> docs/webhooks: use subtle.ConstantTimeCompare for comparing signatures

- ipn/ipnlocal/peerapi.go
We were writing the error when getting the default interface before setting the content type, so we'd get HTML treated as plain text.
> ipn/ipnlocal: tweak error handling in interfaces PeerAPI debug endpoint

- cmd/tailscale/cli/network-lock.go
- ipn/ipnlocal/network-lock.go
- types/key/nl.go
- types/key/nl_test.go
/cc @mayakacz as discussed on meet
> types/key,cmd/tailscale/cli: support tlpub prefix for tailnet-lock keys

- cmd/tailscale/cli/cli.go
> cmd/tailscale/cli: unhide login and switch subcommands

- cmd/tailscale/cli/switch.go
Updates #713.
Signed-off-by: Walter Poupore <walterp@tailscale.com>
> cmd/tailscale/cli: Fix 'tailscale switch' error message

- cmd/tailscaled/tailscaled.go
renamed from `useNetstack` to `onlyNetstack` which is 1 letter more but
more descriptive because we always have netstack enabled and `useNetstack`
doesn't convey what it is supposed to be used for. e.g. we always use
netstack for Tailscale SSH.
Also renamed shouldWrapNetstack to handleSubnetsInNetstack as it was only used
to configure subnet routing via netstack.
Updates tailscale/corp#8020
> cmd/tailscaled: rename variables to be more descriptive

- ipn/ipnlocal/local.go
- ipn/localapi/localapi.go
For testing of Windows GUI client.
Updates #6480
> ipn/localapi: add debug (root-required) access to inject debug Notify

- ipn/ipnlocal/local.go
> ipn/ipnlocal: sanitize prefs in more notify code paths

- ipn/ipnserver/server.go
- ipn/ipnserver/server_test.go
- ipn/localapi/localapi.go
> ipn/{ipnserver,localapi}: fix InUseOtherUser handling with WatchIPNBus

- api.md
Signed-off-by: Julia Stein <julia@tailscale.com>
> api.md: change "admin panel" to "admin console"

- cmd/containerboot/kube.go
- cmd/containerboot/main.go
- cmd/containerboot/main_test.go
3 independent commits that prepare for the bigger change that comes later, using WatchIPNBus to monitor tailscaled state instead of looping on status+sleep. I suggest reviewing each commit separately.
> No-op refactors in preparation for changing containerboot's bringup

- cmd/containerboot/kube.go
- cmd/containerboot/main.go
- cmd/containerboot/main_test.go
> cmd/containerboot: check that k8s secret permissions are correct.

- cmd/containerboot/kube.go
- cmd/containerboot/main.go
- cmd/containerboot/main_test.go
> cmd/containerboot: gracefully degrade if missing patch permissions in k8s.

- cmd/containerboot/kube.go
- cmd/containerboot/main.go
- cmd/containerboot/main_test.go
Also includes some refactors that happened in 1.35, which are semantic no-ops but cause merge sadness with the bugfixes.
> Backport cmd/containerboot fixes.

- cmd/tailscale/cli/file.go
Trying to send some large movie files and not knowing if it was working was a vibe, not the vibe
Looks kinda like this:
```shell
[nix-shell:~/tailscale]$ go build -o tailscale ./cmd/tailscale && sudo ./tailscale --socket=/tmp/ts/ts1.sock file cp ~/Downloads/redacted.mp4 tom-workhorse:
redacted.mp4                                          		59616/713225 kb 	8.36%	6944 kb/s
```
> cmd/tailscale/cli: add progress to tailscale file cp

- cmd/tailscale/cli/network-lock.go
Signed-off-by: Walter Poupore <walterp@tailscale.com>
> cmd/tailscale/cli: update lock status help strings

- wgengine/router/router_linux_test.go
Adjust the expected system output by removing the unsupported mask component including and after the slash in expected output like:
```
fwmask 0xabc/0xdef
```
This package's tests now pass in an Alpine container when the 'go' and 'iptables' packages are installed (and run as privileged so /dev/net/tun exists).
Fixes #5928
Change-Id: Id1a3896282bfa36b64afaec7a47205e63ad88542
> wgengine/router: fix tests on systems with older Busybox 'ip' binary

- cmd/tailscale/cli/ssh.go
arugments => arguments
Signed-off-by: shayne <79330+shayne@users.noreply.github.com>
> cmd/tailscale/cli: [ssh] fix typo in help text

- go.mod
- go.sum
Updates tailscale/tailscale#6233
> go.mod: update deps to add support for GOARCH=loong64

- go.mod
- go.sum
Updates tailscale/tailscale#6233
> go.mod: bump tailscale/wireguard-go for loong64

- ipn/ipnlocal/peerapi.go
- ipn/localapi/localapi.go
Mainly motivated by wanting to know how much Taildrop is used, but also useful when tracking down how many invalid requests are generated.
> ipn/ipnlocal: add a few metrics for PeerAPI and LocalAPI

- ipn/ipnlocal/peerapi.go
Use multierr.Range to iterate through an error tree instead of multiple invocations of errors.As.
This scales better as we add more Go error types to the switch.
> ipn/ipnlocal: simplify redactErr

- Makefile
- build_docker.sh
> Makefile: add a target for doing dev builds of the k8s operator.

- net/dns/manager.go
- net/dns/manager_tcp_test.go
Previously, if a DNS-over-TCP message was received while there were existing queries in-flight, and it was over the size limit, we'd close the 'responses' channel. This would cause those in-flight queries to send on the closed channel and panic.
Instead, don't close the channel at all and rely on s.ctx being canceled, which will ensure that in-flight queries don't hang.
Fixes #6725
Change-Id: I8267728ac37ed7ae38ddd09ce2633a5824320097
> net/dns: don't send on closed channel when message too large

- cmd/gitops-pusher/gitops-pusher.go
Fixes https://github.com/tailscale/coral/issues/90
> cmd/gitops-pusher: support alternate api-server URLs

- cmd/k8s-operator/operator.go
We used to need to do timed requeues in a few places in the reconcile logic, and the easiest way to do that was to plumb reconcile.Result return values around. But now we're purely event-driven, so the only thing we care about is whether or not an error occurred.
Incidentally also fix a very minor bug where headless services would get completely ignored, rather than reconciled into the correct state. This shouldn't matter in practice because you can't transition from a headful to a headless service without a deletion, but for consistency let's avoid having a path that takes no definite action if a service of interest does exist.
Updates #502.
> cmd/k8s-operator: refactor reconcile loop, un-plumbing reconcile.Result.

- net/tstun/wrap.go
> net/tstun: don't return early from a partial tun.Read()

- ssh/tailssh/incubator.go
- ssh/tailssh/tailssh_test.go
As backup plan, just in case the earlier fix's logic wasn't correct and we want to experiment in the field or have users have a quicker fix.
Updates #5285
> ssh/tailssh: add envknob for default PATH

- ipn/ipnlocal/local.go
- ipn/ipnlocal/local_test.go
- ipn/ipnstate/ipnstate.go
- wgengine/magicsock/magicsock.go
- wgengine/magicsock/magicsock_test.go
- wgengine/userspace.go
Fixes #4311
Change-Id: Iaae0615148fa7154f4ef8f66b455e3a6c2fa9df3
Co-authored-by: Claire Wang <claire@tailscale.com>
> ipn/ipnlocal: fix StatusWithoutPeers not populating parts of Status

- cmd/tailscale/cli/cli.go
It's long & distracting for how low value it is.
Fixes #6766
> cmd/tailscale/cli: hide Windows named pipe default name in flag help

- cmd/sync-containers/main.go
- go.mod
> cmd/sync-containers: program to sync tags between container registries.

- cmd/sync-containers/main.go
Updates tailscale/corp#8461
---
For the inevitable iteration as I try to get the automation set up.
> cmd/sync-containers: add a dry-run option.

- go.mod
- go.sum
Bump to get https://github.com/golang/sys/commit/2204b6615fb84fc69a9e5d37b2d508ddf544dcea
Updates #5793
> go.mod: bump x/sys for linux/arm64 cpu SIGILL fix

- wgengine/magicsock/magicsock.go
> wgengine/magicsock: avoid ReadBatch/WriteBatch on old Linux kernels

- cmd/tailscale/cli/up.go
> cmd/tailscale: fix "up" warning about netfilter-mode on Synology

- ssh/tailssh/incubator.go
Thanks to @nshalman and @Soypete for debugging!
Updates #6054
> ssh/tailssh: don't swallow process exit code in be-child

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/6840
> scripts/installer.sh: add SUSE Enterprise Server.

- net/dns/resolvconffile/resolvconffile.go
- net/dns/resolvconffile/resolvconffile_test.go
> net/dns/resolvconffile: fix handling of multiple search domains

- cmd/cloner/cloner.go
- cmd/viewer/viewer.go
- ipn/ipnstate/ipnstate_clone.go
- types/dnstype/dnstype_clone.go
- types/dnstype/dnstype_view.go
- types/persist/persist_clone.go
- types/persist/persist_view.go
- util/codegen/codegen.go
- wgengine/filter/filter_clone.go
- wgengine/wgcfg/wgcfg_clone.go
> util/codegen, all: use latest year, not time.Now, in generated files

- ipn/ipnlocal/profiles.go
- ipn/ipnlocal/profiles_test.go
paired with @maisem.
fixes: https://github.com/tailscale/corp/issues/8417
updates: #6671
> ipn/profiles: set default prefs based on Windows registry

- cmd/tailscaled/tailscaled.go
- ipn/ipnlocal/c2n.go
- ipn/ipnlocal/local.go
- ipn/localapi/localapi.go
- logtail/logtail.go
- tailcfg/tailcfg.go
> ipn/ipnlocal: add c2n handler to flush logtail for support debugging

- README.md
And remove Darwin from the list, as macOS was already there.
> README.md: update with some new links, refresh

- cmd/tailscaled/ssh.go
- go.mod
- go.sum
- ipn/ipnlocal/local.go
- ipn/ipnlocal/ssh.go
- ipn/ipnlocal/ssh_stub.go
- ssh/tailssh/incubator.go
- ssh/tailssh/tailssh.go
- tstest/integration/tailscaled_deps_test_openbsd.go
Depends on https://github.com/u-root/u-root/pull/2593
> ssh/tailssh: add OpenBSD support for Tailscale SSH

- tailcfg/tailcfg.go
Change-Id: I50889f0205ecf66c415f50f9019c190448c991fc
> tailcfg: document zero value for KeyExpiry

- version/print.go
> version: advertise unstable track in CLI, daemon start-up

- cmd/tailscale/cli/web.go
- ipn/ipnlocal/local.go
- ipn/ipnstate/ipnstate.go
UI works remains, but data is there now.
Updates #4015
> cmd/tailscale/cli: plumb TUN mode into tailscale web template

- control/controlhttp/server.go
> control/controlhttp: fix header case-sensitivity

- cmd/tailscale/cli/web.go
- cmd/tailscale/cli/web.html
> cmd/tailscale/cli: make web show/link Synology outgoing connection mode/docs

- ipn/ipnlocal/local.go
- wgengine/magicsock/magicsock.go
Change-Id: Ic5f533f175a6e1bb73d4957d8c3f970add42e82e
> ipn/ipnlocal, wgengine/magicsock: check Expired bool on Node; print error in Ping

- cmd/tailscale/cli/web.css
- cmd/tailscale/cli/web.html
Follow-up to #6957
Updates #4015
cc @mayakacz for wording opinions.
> cmd/tailscale/cli: style synology outgoing access info

- wgengine/filter/filter.go
(2 commits)
In prep for #6423 fixes, to trim down the final PR
> wgengine/filter: clean up a couple things

- net/tstun/wrap_test.go
Signed-off-by: andig <cpuidle@gmx.de>
> Remove redundant type declaration

- client/tailscale/localclient.go
- cmd/tailscale/cli/debug.go
- ipn/localapi/localapi.go
- logtail/logtail.go
> cmd/tailscale, logtail: add 'tailscale debug daemon-logs' logtail mechanism

- control/controlhttp/client.go
Updates tailscale/docker-extension#49
> control/controlhttp: add TS_FORCE_NOISE_443, TS_DEBUG_NOISE_DIAL envknobs

- wgengine/magicsock/magicsock.go
When you hit control-C on a tailscaled (notably in dev mode, but also on any systemctl stop/restart), there is a flood of messages like:
```
magicsock: doing cleanup for discovery key d:aa9c92321db0807f
magicsock: doing cleanup for discovery key d:bb0f16aacadbfd46
magicsock: doing cleanup for discovery key d:b5b2d386296536f2
magicsock: doing cleanup for discovery key d:3b640649f6796c91
magicsock: doing cleanup for discovery key d:71d7b1afbcce52cd
magicsock: doing cleanup for discovery key d:315b61d7e0111377
magicsock: doing cleanup for discovery key d:9301f63dce69bf45
magicsock: doing cleanup for discovery key d:376141884d6fe072
....
```
It can be hundreds or even tens of thousands.
So don't do that. Not a useful log message during shutdown.
#cleanup
> wgengine/magicsock: quiet log flood at tailscaled shutdown

- tailcfg/tailcfg.go
Updates #6932
Change-Id: I96c2467fa49201eb3d8df5cb36486370f598928c
> tailcfg: bump capver for Node.Expired

- tstest/integration/integration_test.go
- wgengine/userspace_test.go
Updates #2855
Updates #3598
Updates #7008
Change-Id: I2b849e04646456b9f0c8a01563f2add752f4b2a4
> various: mark more tests as flaky

- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_test.go
Create an interface and mock implementation of `tailscale.LocalClient` for serve command tests.
Updates #6304
Closes #6372
> cmd/tailscale/cli: use mock impl of LocalClient for serve cmd

- ipn/ipnlocal/serve.go
On macOS (AppStore and macsys), we need to bind to ""/all-interfaces due to the network sandbox. Ideally we would only bind to the Tailscale interface, but that's not possible, macOS fails to listen on privileged ports when binding to a specific interface.
We also implement the lc.Control hook, same as we do for peerapi. It doesn't solve our problem but it's better that we do and would likely be required when Apple gets around to fixing per-interface priviliged port binding.
Fixes: #6364
> ipn/ipnlocal: [serve] listen on all-interfaces for macOS

- cmd/tailscale/cli/diag.go
Per recent user confusion on a QNAP issue.
> cmd/tailscale/cli: only give systemctl hint on systemd systems

- client/tailscale/localclient.go
- cmd/tailscale/cli/debug.go
- ipn/localapi/localapi.go
Updates tailscale/corp#8811
Updates tailscale/corp#8613
> cmd/tailscale/cli: add debug set-expire command for testing

- ipn/ipnlocal/local.go
> ipn/ipnlocal: add health warning for Tailscale SSH + SELinux

- client/tailscale/keys.go
Updates https://github.com/tailscale/tailscale/issues/7020
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203810144085942
> client/tailscale/keys: fix client.Keys unmarshalling

- cmd/mkpkg/main.go
> cmd/mkpkg: allow specifying recommended dependencies

- cmd/k8s-operator/operator.go
The dependency injection functionality has been deprecated a while back and it'll be removed in the 0.15 release of Controller Runtime. This changeset sets the Client after creating the Manager, instead of using InjectClient.
Signed-off-by: Vince Prignano <vince@prigna.com>
> cmd/k8s-operator: remove use of InjectClient (deprecated)

- wgengine/magicsock/magicsock.go
- wgengine/magicsock/magicsock_test.go
Spotted by Maisem.
Fixes #6680
> wgengine/magicsock: fix buggy fast path in Conn.SetNetworkMap

- cmd/tailscale/cli/web.html
> cmd/tailscale/cli: fix false positive on cli page

- cmd/nginx-auth/README.md
> cmd/nginx-auth: update Expected-Tailnet documentation

- tailcfg/tailcfg.go
Add capabilities and an SSH action for SSH session hauling.
Signed-off-by: Kris Brandow <kris@tailscale.com>
> tailcfg: add caps and SSH action for SSH hauling

- cmd/containerboot/main.go
- cmd/containerboot/main_test.go
- cmd/k8s-operator/operator.go
- cmd/k8s-operator/operator_test.go
- util/dnsname/dnsname.go
> cmd/k8s-operator: support setting a custom hostname.

- go.mod
- go.sum
For https://git.zx2c4.com/wintun-go/commit/?id=0fa3db229ce2036ae779de8ba03d336b7aa826bd
Updates #6647
> go.mod: bump wintun-go

- net/netstat/netstat_windows.go
The API documentation does claim to output empty strings under certain conditions, but we're sometimes seeing nil pointers in the wild, not empty strings.
Fixes https://github.com/tailscale/corp/issues/8878
> net/netstat: add nil checks to Windows OSMetadata implementation

- net/netstat/netstat_windows.go
And defensively bound allocation.
Updates tailscale/corp#8878
> net/netstat: document the Windows netstat code a bit more

- net/netns/netns_darwin.go
Follow-up to #7065 with some comments from Brad's review.
Change-Id: Ia1219f4fa25479b2dada38ffe421065b408c5954
> net/netns: add post-review comments

- build_docker.sh
> build_docker.sh: set good repo defaults based on the target.

- wgengine/magicsock/magicsock.go
> wgengine/magicsock: de-dup disco pings

- cmd/tailscaled/tailscaled.go
- cmd/tsconnect/wasm/wasm_js.go
- ipn/localapi/localapi.go
- safesocket/basic_test.go
- safesocket/pipe_windows.go
- safesocket/safesocket.go
- safesocket/safesocket_js.go
- safesocket/unixsocket.go
Also drop the port param from safesocket.Listen. #cleanup
> safesocket: remove the now unused WindowsLocalPort

- control/controlbase/conn_test.go
- control/controlbase/handshake_test.go
- control/controlbase/interop_test.go
- derp/derp_test.go
- net/memnet/conn.go
- net/memnet/conn_test.go
- net/memnet/listener.go
- net/memnet/listener_test.go
- net/memnet/memnet.go
- net/memnet/pipe.go
- net/memnet/pipe_test.go
- ssh/tailssh/tailssh_test.go
- tsnet/tsnet.go
This is just #cleanup to resolve a TODO
Also add a package doc.
> net/memnet: rename from net/nettest

- cmd/tailscaled/tailscaled.go
- cmd/tsconnect/wasm/wasm_js.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/local_test.go
- ipn/ipnlocal/loglines_test.go
- ipn/ipnlocal/network-lock_test.go
- ipn/ipnlocal/peerapi_test.go
- ipn/ipnlocal/profiles.go
- ipn/ipnlocal/profiles_test.go
- ipn/ipnlocal/ssh_test.go
- ipn/ipnlocal/state_test.go
- ssh/tailssh/tailssh_test.go
- tsnet/tsnet.go
- wgengine/netstack/netstack_test.go
This is #cleanup now that #7121 is merged.
> ipn/ipnlocal: drop not required StateKey parameter

- wgengine/magicsock/magicsock.go
> wgengine/magicsock: fix de-dup disco ping handling for netmap endpoints

- .github/workflows/static-analysis.yml
> ci: make gofmt check fail for a non-empty diff

- ipn/ipnlocal/local.go
- types/logger/logger.go
We can log too quickly for logtail to catch up, even when we opt out of log rate-limiting. When the user passes the `--diagnose` flag to bugreport, we use a token bucket to control how many logs per second are printed and sleep until we're able to write more.
Change-Id: If27672d66b621b589280bd0fe228de367ffcbd8f
> ipn/ipnlocal: rate-limit diagnose logs in bugreport

- .github/ISSUE_TEMPLATE/bug_report.yml
Add question about https://github.com/tailscale/tailscale/wiki/OtherSoftwareInterop in the issue template.
> .github/ISSUE_TEMPLATE: add link to wiki/OtherSoftwareInterop

- derp/derp_test.go
- derp/derphttp/derphttp_test.go
- ipn/store/mem/store_mem.go
- ipn/store/stores.go
- net/stun/stun.go
- tstest/natlab/natlab.go
- types/key/machine.go
- wgengine/netstack/netstack.go
Updates #7123
Updates #6257 (more to do in other repos)
> all: use Go 1.20's bytes.Clone

- wgengine/magicsock/magicsock.go
To aid in debugging where a customer has static port-forwards set up and there are issues establishing a connection through that port.
Change-Id: Ic5558bcdb40c9119b83f79dcacf2233b07777f2a
> wgengine/magicsock: add envknob to print information about port selection

- ipn/ipnlocal/local.go
If the user passes the --diagnose flag, print a warning if any of the default or fallback DNS resolvers are Tailscale IPs. This can interfere with the ability to connect to the controlplane, and is typically something to pay attention to if there's a connectivity issue.
Change-Id: Ib14bf6228c037877fbdcd22b069212b1a4b2c456
> ipn/ipnlocal: print warning about DNS servers in bugreport --diagnose

- tailcfg/tailcfg.go
No implementation yet.
Updates #7175
> tailcfg: add wire fields/docs for resuming streaming map sessions

- cmd/containerboot/main.go
- ipn/ipnlocal/cert.go
> ipn/ipnlocal: add support to store certs in k8s secrets

- cmd/get-authkey/.gitignore
- cmd/get-authkey/main.go
Updates https://github.com/tailscale/tailscale/issues/3243
> cmd/get-authkey: add an OAuth API client to produce an authkey

- ipn/ipnlocal/expiry.go
- ipn/ipnlocal/expiry_test.go
- ipn/ipnlocal/local.go
We now handle the case where the NetworkMap.SelfNode has already expired and do not return an expiry time in the past (which causes an ~infinite loop of timers to fire).
Additionally, we now add an explicit check to ensure that the next expiry time is never before the current local-to-the-system time, to ensure that we don't end up in a similar situation due to clock skew.
Finally, we add more tests for this logic to ensure that we don't regress on these edge cases.
Fixes #7193
Change-Id: Iaf8e3d83be1d133a7aab7f8d62939e508cc53f9c
> ipn/ipnlocal: handle more edge cases in netmap expiry timer

- .github/workflows/go_mod_tidy.yml
> .github/workflows: use ./tool/go in go mod tidy

- version/prop.go
- version/version.go
> version: unify and optimize the various not-version funcs

- cmd/k8s-operator/manifests/authproxy-rbac.yaml
- cmd/k8s-operator/manifests/operator.yaml
- cmd/k8s-operator/operator.go
- cmd/k8s-operator/proxy.go
- go.mod
> cmd/k8s-operator: add support for running an auth proxy

- ipn/ipnstate/ipnstate.go
> ipn/ipnstate: update field docs on PeerStatus.

- ipn/ipnlocal/peerapi.go
Useful when debugging issues (e.g. to see the full routing table), and easier to refer to the output via a browser than trying to read it from the logs generated by `bugreport --diagnose`.
Behind a `canDebug()` check, similar to the `/magicsock` and `/interfaces` endpoints.
Updates #7184
> ipn/ipnlocal: add PeerAPI endpoint for doctor output

- version-embed.go
- version/prop.go
- version/version.go
> version: return correct Meta.MajorMinorPatch in non-dev builds

- cmd/sync-containers/main.go
Fixes https://github.com/tailscale/tailscale/issues/7251
> cmd/sync-containers: update latest and stable tags

- types/lazy/lazy.go
- types/lazy/sync_test.go
- types/lazy/unsync.go
- types/lazy/unsync_test.go
> types/lazy: helpers for lazily computed values

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/6926
Fixes https://github.com/tailscale/tailscale/issues/7076
> scripts/installer.sh: add Mendel OS and OpenMandriva.

- cmd/tailscale/cli/web.css
- cmd/tailscale/cli/web.go
- cmd/tailscale/cli/web.html
Fixes #7238
Also cleaned up the debug info, so this is a full view:
> cmd/tailscale/cli: add logout and debug info to web

- .github/workflows/test.yml
> .github/workflows: simplify build-only go test invocation

- Dockerfile
- build_docker.sh
The stamp vars got renamed and I forgot to update these scripts.
> Dockerfile: fix docker build

- .github/workflows/update-flake.yml
> .github/workflows: fix typo

- tstest/integration/integration.go
> tstest/integration: enable go lookups from $PATH

- Makefile
https://rosszurowski.com/log/2022/makefiles#self-documenting-makefiles
> Makefile: add help text to Makefile

- .github/workflows/test.yml
https://github.com/google/oss-fuzz/pull/9729 fixed it
> .github/workflows: set TS_FUZZ_CURRENTLY_BROKEN to false

- cmd/tailscale/cli/configure-kube.go
This ensures that we put the kubeconfig in the correct directory from within the macOS Sandbox when paired with tailscale/corp@3035ef7
I tested locally and it works!
Updates #7220
> cmd/tailscale/cli: handle home dir correctly on macOS for kubeconfig

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/7300
> scripts/installer.sh: add postmarketos support.

- go.mod
- go.sum
No particular reason. Just good point of our release cycle for some #cleanup.
> go.mod: bump x/crypto

- client/tailscale/devices.go
> client/tailscale: add tags field to Device struct

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/6541
Fixes https://github.com/tailscale/tailscale/issues/6555
> scripts/installer.sh: add GalliumOS and Sangoma Linux

- ssh/tailssh/incubator.go
> ssh/tailssh: detect user shell correctly on darwin

- .gitignore
> gitignore: Add personal .gopath and nix build /result

- util/ringbuffer/ringbuffer.go
- util/ringbuffer/ringbuffer_test.go
Also add some basic tests for this implementation.
Change-Id: I307ebb6db91d0c172657befb276b38ccb638f828
> util/ringbuffer: move generic ringbuffer from corp repo

- cmd/tsconnect/common.go
trimmed builds don't have absolute path information in executable metadata, which leads the runtime.Caller approach failing mysteriously in yarn with complaints about relative package paths.
So, instead of using embedded package metadata to find paths, expect that we're being invoked within the tailscale repo, and locate the tsconnect directory that way.
---
(part of getting gocross open-sourced, which always -trimpaths binaries for reproducibility)
> cmd/tsconnect: find the build dir independently of -trimpath

- cmd/k8s-operator/operator.go
This allows identifying the operator.
Updates #5055
> cmd/k8s-operator: set hostinfo.Package

- tsnet/tsnet.go
> tsnet: add Up method to block until ready

- .gitignore
- cmd/dist/dist.go
- release/deb/debian.postinst.sh
- release/deb/debian.postrm.sh
- release/deb/debian.prerm.sh
- release/dist/dist.go
- release/dist/memoize.go
- release/dist/unixpkgs/pkgs.go
- release/dist/unixpkgs/targets.go
- release/rpm/rpm.postinst.sh
- release/rpm/rpm.postrm.sh
- release/rpm/rpm.prerm.sh
Mechanical copy from other repo. Only changes are package paths and paths to the deb/rpm helper scripts.
> release: open-source release build logic for unix packages

- cmd/tailscale/cli/cli_test.go
> cmd/tailscale/cli: fix TestUpdatePrefs over Tailscale SSH

- ssh/tailssh/incubator.go
> ssh/tailssh: try launching commands with /usr/bin/login on macOS

- cmd/nginx-auth/mkdeb.sh
Fixes https://github.com/tailscale/tailscale/issues/6978
> cmd/nginx-auth: build for arm64

- cmd/gitops-pusher/gitops-pusher.go
Add support for OAuth tokens for the gitops-pusher.
> Add support for OAuth tokens

- cmd/tailscale/cli/status.go
- cmd/tailscale/cli/up.go
"Device Authorization" was recently renamed to "Device Approval" on the control side. This change updates the linux cli to match.
> cmd/tailscale/cli: update device authorization copy

- cmd/containerboot/kube.go
- cmd/containerboot/main.go
- cmd/containerboot/main_test.go
- kube/client.go
We had two implemenetations of the kube client, merge them.
> cmd/containerboot,kube: consolidate the two kube clients

- cmd/derper/bootstrap_dns.go
This is to address a possible DNS failure on startup. Prior to this change IPv6 addresses would be listed first and the client dialer would fail for hosts without IPv6 connectivity.
> cmd/derper: randomize IPs on refreshBootstrapDNS

- net/interfaces/interfaces_test.go
Return a mock set of interfaces and a mock gateway during this test and verify that LikelyHomeRouterIP returns the outcome we expect. Also verify that we return an error if there are no IPv4 addresses available.
Follow-up to #7447
Change-Id: I8f06989e7f1f0bebd108861cbff17b820ed2e6e4
> net/interfaces: add better test for LikelyHomeRouterIP

- ipn/ipnlocal/local.go
- ipn/ipnlocal/local_test.go
Change-Id: Ic804efd24f5f536de1f2c910de3a24372d48d54d
> ipn/ipnlocal: reject unmasked routes

- ipn/localapi/localapi.go
Change-Id: I612f9ebf78d962e094bff908670b3ffd89f756e5
> ipn/localapi: fix panic after handler returns

- net/portmapper/portmapper.go
Per a packet capture provided, some gateways will reply to a UPnP discovery packet with a UDP packet with a source port that does not come from the UPnP port. Accept these packets with a log message.
Updates #7377
Change-Id: I5d4d5b2a0275009ed60f15c20b484fe2025d094b
> net/portmapper: relax source port check for UPnP responses

- ipn/ipnlocal/local.go
This prevents a panic where we synthesize a new netmap in setClientStatus after we've shut down and nil'd out the controlclient, since that function expects to be called while connected to control.
Fixes #7392
Change-Id: Ib631eb90f34f6afa008d69bbb386f70da145e102
> ipn/ipnlocal: stop netmap expiry timer when resetting control client

- tstime/tstime.go
Sleep is an interruptible sleep variation.
> tstime: add Sleep

- words/scales.txt
- words/tails.txt
I explained this tails/scales list to my 5yo and he looked at me like it was the most obvious idea ever. Of course we'd make such lists at work!  What else do grown-ups do all day? And then he wouldn't stop talking about coelacanths and I had no clue what he was saying or how to spell it until I asked my phone and the phone apparently understood me and I realized it was a fish and he was helping me? I think?
> words: add word we forgot

- cmd/sniproxy/snipproxy.go
Adds support for an HTTP server that promotes all requests to HTTPS.
The flag is `-promote-https` and defaults to true.
Updates #1748
> sniproxy: add promote-https

- tsnet/tsnet.go
> tsnet: explicit message for panic seen in CI

- derp/derphttp/derphttp_client.go
This was causing a leak in our CI!
> derp/derphttp: cleanup WebSocket connection on close

- net/sockstats/sockstats_tsgo.go
`withSockStats` may be called before `setLinkMonitor`, in which case we don't have a populated `knownInterfaces` map. Since we pre-populate the per-interface counters at creation time, we would end up with an empty map. To mitigate this, we do an on-demand request for the list of interfaces.
This would most often happen with the `logtail` instrumentation, since we initialize it very early on.
> net/sockstat: fix per-interface statistics not always being available

- net/sockstats/sockstats_tsgo.go
Though not fine-grained enough to be useful for detailed analysis, we might as well export that we gather as client metrics too, since we have an upload/analysis pipeline for them.
`clientmetric.Metric.Add()` is an atomic add, so it's pretty cheap to also do per-packet.
Updates #3363
> sockstats: export as client metrics

- ipn/localapi/debugderp.go
Updates #6526
Change-Id: Ic18d9ff288b9c7b8d5ab1bd77dd59693cd776cc4
> ipn/localapi: flesh out the 'debug derp' checks

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/7410
> scripts/installer: add PureOS and Amazon Linux Next

- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_test.go
- ipn/serve.go
- ipn/serve_test.go
- tsnet/example/tsnet-funnel/tsnet-funnel.go
- tsnet/tsnet.go
This lets a tsnet binary share a server out over Tailscale Funnel.
> tsnet: add ListenFunnel

- control/controlclient/direct.go
- control/controlhttp/client.go
- net/dns/resolver/forwarder.go
- net/dnsfallback/dnsfallback.go
- tsnet/tsnet.go
Updates #7537
Change-Id: Id89acab70ea678c8c7ff0f44792d54c7223337c6
> various: pass logger.Logf through to more places

- cmd/tailscale/cli/cli.go
- cmd/tailscale/cli/configure-kube.go
- cmd/tailscale/cli/configure-synology.go
- cmd/tailscale/cli/configure.go
Also call out Alpha.
Updates #7220
> cmd/tailscale/cli: update docs and unhide configure

- version/mkversion/mkversion.go
I thought our versioning scheme would make go.mod include a commit hash even on stable builds. I was wrong. Fortunately, the rest of this code wants anything that 'git rev-parse' understands (to convert it into a full git hash), and tags qualify.
> version/mkversion: don't break on tagged go.mod entries

- control/controlclient/auto.go
fix for https://github.com/tailscale/tailscale/issues/7501
feel free to close this PR if the tailscale author's intention is actually to reset the backoff
> control/controlclient: fix accidental backoff reset

- tsnet/tsnet.go
> tsnet: do not start logtail in tests

- tsnet/tsnet.go
- tsnet/tsnet_test.go
- tstest/integration/testcontrol/testcontrol.go
For the logic added in b797f77.
> tsnet: add test for Funnel connections

- net/interfaces/interfaces.go
In May 2021, Azure App Services used 172.16.x.x addresses:
```
10: eth0@if11: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
link/ether 02:42:ac:10:01:03 brd ff:ff:ff:ff:ff:ff
inet 172.16.1.3/24 brd 172.16.1.255 scope global eth0
valid_lft forever preferred_lft forever
```
Now it uses link-local:
```
2: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
link/ether 8a:30:1f:50:1d:23 brd ff:ff:ff:ff:ff:ff
inet 169.254.129.3/24 brd 169.254.129.255 scope global eth0
valid_lft forever preferred_lft forever
```
This is reasonable for them to choose to do, it just broke the handling in net/interfaces.
This PR proposes to:
1. Always allow link-local in LocalAddresses() if we have no better address available.
2. Continue to make …
> net/interfaces: also allow link-local for AzureAppServices.

- net/sockstats/sockstats_tsgo.go
Followup to #7518 to also export client metrics when the active interface is cellular.
Updates #3363
> net/sockstats: export cellular-only clientmetrics

- ssh/tailssh/incubator.go
Follow-up to #7615
Change-Id: Ib4256bff276f6d5cf95838d8e39c87b3643bde37
> ssh/tailssh: make uid an int instead of uint64

- words/tails.txt
> words: what?! a llama?! he's supposed to be dead!

- ssh/tailssh/tailssh.go
> ssh/tailssh: stream SSH recordings to configured recorders

- ssh/tailssh/tailssh.go
> ssh/tailssh: add more metadata to recording header

- ssh/tailssh/tailssh.go
Currently we only send down recorders in first action, allow the final action to replace them but not to drop them.
> ssh/tailssh: allow recorders to be configured on the first or final action

- ssh/tailssh/tailssh.go
Otherwise we see errors like
```
ssh-session(sess-20230322T005655-5562985593): recording: error sending recording to <addr>:80: Post "http://<addr>:80/record": context canceled
```
The ss.ctx is closed when the session closes, but we don't want to break the upload at that time. Instead we want to wait for the session to close the writer when it finishes, which it is already doing.
> ssh/tailssh: use background context for uploading recordings

- ssh/tailssh/incubator.go
This makes it less likely that we trip over bugs like golang/go#1435.
Updates #7616
Change-Id: Ic28c03c3ad8ed5274a795c766b767fa876029f0e
> ssh/tailssh: lock OS thread during incubator

- ssh/tailssh/tailssh.go
- ssh/tailssh/tailssh_test.go
> ssh/tailssh: enable recording of non-pty sessions

- log/sockstatlog/logger.go
> log/sockstatlog: make shutdown close idle connections

- net/netcheck/netcheck.go
- net/netcheck/netcheck_test.go
If multiple Go channels have a value (or are closed), receiving from them all in a select will nondeterministically return one of the two arms. In this case, it's possible that the hairpin check timer will have expired between when we start checking and before we check at all, but the hairpin packet has already been received. In such cases, we'd nondeterministically set report.HairPinning.
Instead, check if we have a value in our results channel first, then select on the value and timeout channel after. Also, add a test that catches this particular failure.
Fixes #1795
Change-Id: I842ab0bd38d66fabc6cabf2c2c1bb9bd32febf35
> net/netcheck: improve determinism in hairpinning test

- scripts/installer.sh
Fixes https://github.com/tailscale/corp/issues/8952
> scripts: use pkg server to determine supported deb/rpm distros

- net/dns/resolved.go
Fixes #7686 
Change-Id: Ibffb05539ab876b12407d77dcf2201d467895981
> net/dns: don't send on closed channel in resolvedManager

- ipn/ipnserver/proxyconnect.go
- log/sockstatlog/logger.go
- log/sockstatlog/logger_test.go
- logpolicy/logpolicy.go
> logpolicy: do not upload logs in tests

- net/tstun/wrap.go
> net/tstun: only log natConfig on changes

- ssh/tailssh/tailssh_test.go
> ssh/tailssh: add session recording test for non-pty sessions

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/7651
> scripts/installer: add VMWare PhotonOS.

- ssh/tailssh/tailssh.go
- ssh/tailssh/tailssh_test.go
> ssh/tailssh: add tests for recording failure

- ipn/ipnlocal/serve.go
The reverse proxy was sending the `ingressd` IPv6 down as the `X-Forwarded-For`. This update uses the actual remote addr.
Updates: tailscale/corp#9914
> ipn/ipnlocal: [serve/funnel] use actual SrcAddr as X-Forwarded-For

- ssh/tailssh/tailssh.go
There were two code paths that could fail depending on how fast the recorder responses. This fixes that by returning the correct error from both paths.
Fixes #7707
> ssh/tailssh: fix race in errors returned when starting recorder

- log/sockstatlog/logger.go
- logtail/logtail.go
Split apart polling of sockstats and logging them to disk.  Add a 3 second delay before writing logs to disk to prevent an infinite upload loop when uploading stats to logcatcher.  3 seconds is admittedly somewhat arbitrary, but seems to be long enough to address the problem, but not too long to worry about the memory usage of the buffered channel.
Fixes #7719
> log/sockstatlog: add delay before writing logs to disk

- ipn/ipnlocal/local.go
- ipn/ipnlocal/serve.go
- ipn/serve.go
> cmd/tailscale/cli: do not allow turning Funnel on while shields-up

- ssh/tailssh/tailssh_test.go
> ssh/tailssh: handle output matching better in tests

- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_test.go
> cmd/tailscale/cli: [serve] add support for proxy paths

- wgengine/magicsock/magicsock.go
> wgengine/magicsock: remove unused fields on discoInfo

- wgengine/magicsock/magicsock.go
- wgengine/magicsock/magicsock_test.go
> wgengine/magicsock: factor out receiveIPv4 & receiveIPv6 common code

- wgengine/magicsock/magicsock.go
The comment still said *magicsock.Conn implemented wireguard-go conn.Bind. That wasn't accurate anymore.
A doc #cleanup.
> wgengine/magicsock: update comments on what implements conn.Bind

- net/netcheck/netcheck_test.go
> net/netcheck: reenable TestNodeAddrResolve on Windows

- net/connstats/stats.go
Exclude traffic with 100.100.100.100 (for IPv4) and with fd7a:115c:a1e0::53 (for IPv6) since this traffic with the Tailscale service running locally on the node.
This traffic never left the node.
It also happens to be a high volume amount of traffic since DNS requests occur over UDP with each request coming from a unique port, thus resulting in many discrete traffic flows.
Fixes tailscale/corp#10554
> net/connstats: exclude traffic with internal Tailscale service

- ipn/localapi/debugderp.go
Updates #6526
Change-Id: I274b7ed53ee0be3fb94fdb00cafe06a1d676e1cf
> ipn/localapi: also verify STUN queries work in 'debug derp'

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/7862
Fixes https://github.com/tailscale/tailscale/issues/7899
> scripts/installer: add Deepin, RisiOS.

- net/tstun/wrap.go
- net/tstun/wrap_test.go
Change-Id: I630f852d9f16c951c721b34f2bc4128e68fe9475
> net/tstun: add tests for captureHook

- cmd/tailscale/cli/serve.go
> cmd/tailscale/cli: [serve] fix MinGW path conversion

- ssh/tailssh/tailssh.go
Previously we would error out when the recording server disappeared after the in memory buffer filled up for the io.Copy. This makes it so that we handle failing open correctly in that path.
> ssh/tailssh: also handle recording upload failure during writes

- ipn/ipnlocal/profiles.go
- ipn/ipnlocal/profiles_test.go
- ipn/ipnlocal/profiles_windows.go
This fix does not seem ideal, but the test infrastructure using a local goos doesn't seem to avoid all of the associated challenges, but is somewhat deeply tied to the setup.
The core issue this addresses for now is that when run on Windows there can be no code paths that attempt to use an invalid UID string, which on Windows is described in [1].
For the goos="linux" tests, we now explicitly skip the affected migration code if runtime.GOOS=="windows", and for the Windows test we explicitly use the running users uid, rather than just the string "user1". We also now make the case where a profile exists and has already been migrated a non-error condition toward the outer API.
Updates #7876
[1] https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifie …
> ipn/ipnlocal: reenable profile tests on Windows

- cmd/tailscale/cli/up.go
> cmd/tailscale/cli: [up] change oauth authkey format

- words/tails.txt
Can't have a dupe when the dupe is wrong. Clearly we need to up our spell checking game. Did anyone say AI?
> words: charlotte 1 spell-checking-linter 0

- syncs/syncs.go
> syncs: add documentation to Map.Range

- cmd/sniproxy/sniproxy.go
> cmd/sniproxy: Set App name in tsnet hostinfo

- ssh/tailssh/tailssh.go
Updates https://github.com/tailscale/corp/issues/10943
> ssh/tailssh: improve debug logging around revoked sessions

- net/tstun/wrap.go
- net/tstun/wrap_test.go
In the case where the exit node requires SNAT, we would SNAT all traffic not just the traffic meant to go through the exit node. This was a result of the default route being added to the routing table which would match basically everything.
In this case, we need to account for all peers in the routing table not just the ones that require NAT.
Fix and add a test.
Updates tailscale/corp#8020
> net/tstun: handle exit nodes in NAT configs

- derp/README.md
> derp: add a README.md with some docs

- ssh/tailssh/tailssh.go
> ssh/tailssh: restore support for recording locally

- .github/workflows/go-licenses.yml
- .github/workflows/update-flake.yml
Change-Id: I13757ee20240166af72606d166e840ae3ee797d7
> .github: mark bots for exemption by issuebot

- envknob/envknob.go
> envknob: support tailscaled-env.txt on macOS too

- ssh/tailssh/incubator.go
- ssh/tailssh/tailssh.go
- ssh/tailssh/tailssh_test.go
- ssh/tailssh/user.go
> ssh/tailssh: support LDAP users for Tailscale SSH

- ssh/tailssh/incubator.go
- ssh/tailssh/user.go
The previous commit 58ab66e added ssh/tailssh/user.go as part of working on #4945. So move some more user-related code over to it.
> ssh/tailssh: move some user-related code into new user.go

- cmd/k8s-operator/operator.go
> cmd/k8s-operator: print version in startup logs

- net/sockstats/sockstats_tsgo.go
- net/sockstats/sockstats_tsgo_test.go
Wait 2 minutes before we start reporting battery usage. There is always radio activity on initial startup, which gets reported as 100% high power usage.  Let that settle before we report usage data.
Update tailscale/corp#9230
> net/sockstats: wait before reporting battery usage

- cmd/tsconnect/wasm/wasm_js.go
Fix regression from 6e967446e41
Updates #8036
> cmd/tsconnect: fix forgotten API change for wasm

- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_test.go
Usage: `tailscale serve reset`
Fixes #8139
> cmd/tailscale/cli: [serve] add reset flag

- cmd/k8s-operator/operator.go
- cmd/k8s-operator/operator_test.go
- Closes #8155
- Allow specifying priorityClassName for the proxy statefulset as an environment variable
- Add tests
> cmd/k8s-operator: add support for priorityClassName

- ssh/tailssh/incubator.go
- ssh/tailssh/tailssh.go
We were only closing on side of the pty/tty pair.
Close the other side too.
Fixes #8119
cc @fritterhoff
> ssh/tailssh: close tty on session close

- derp/derp_server.go
~97% of the log messages derper outputs are related to the normal non-error state of a client disconnecting in some manner. Add a verbose logging feature that only logs these messages when enabled.
Fixes #8024
> derp: remove default logging of disconnecting clients

- tka/tailchonk_test.go
go vet complains when we copy a lock value. Create clone function that copies everything but the lock value.
Fixes #8207
> tka: fix go vet complaint on copy of lock value in tailchonk_test.go

- ipn/ipnlocal/profiles.go
- ipn/ipnlocal/profiles_windows.go
Updates tailscale/corp#11883
Change-Id: I3a3ca8f25bfefca139115b25ec4161c069da7e4a
> ipn/ipnlocal: add more logging during profile migration

- ipn/ipnlocal/cert.go
- ipn/ipnlocal/cert_test.go
Instead of renewing certificates based on whether or not they're expired at a fixed 14-day period in the future, renew based on whether or not we're more than 2/3 of the way through the certificate's lifetime. This properly handles shorter-lived certificates without issue.
Updates #8204
cc @aarongable
Change-Id: I5e82a9cadc427c010d04ce58c7f932e80dd571ea
> ipn/ipnlocal: renew certificates based on lifetime

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/8100
> scripts/installer.sh: add BlendOS support.

- words/tails.txt
Fixes #8269
Also, the commit messages in this package are **the best**. 🤟
> words: remove misspelling of trex

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/5633
> scripts/installer.sh: add sle-micro-rancher.

- net/dnscache/dnscache.go
Updates https://github.com/tailscale/tailscale/issues/5161
> net/dnscache: use PreferGo on Windows.

- util/cmpx/cmpx.go
- util/cmpx/cmpx_test.go
> util/cmpx: add package with cmp-like things from future Go releases

- wgengine/magicsock/magicsock.go
- wgengine/magicsock/magicsock_test.go
Switch our best address selection to use a scoring-based approach, where we boost each address based on whether it's a private IP or IPv6.
For users in cloud environments, this biases endpoint selection towards using an endpoint that is less likely to cost the user money, and should be less surprising to users.
This also involves updating the tests to not use private IPv4 addresses; other than that change, the behaviour should be identical for existing endpoints.
Updates #8097
Change-Id: I069e3b399daea28be66b81f7e44fc27b2943d8af
> wgengine/magicsock: prefer private endpoints to public ones

- util/slicesx/slicesx.go
- util/slicesx/slicesx_test.go
Change-Id: If97995ca9ee9fad40f327420dcb1857dd7ea2315
> util/slicesx: add Partition function

- words/tails.txt
If you start hearing everything in auto-tune for the rest of the day, I take no responsibility for it.
> words: here comes trouble

- net/tstun/tun.go
- tsnet/tsnet.go
Also fix a js/wasm issue with tsnet in the process. (same issue as WASI)
Updates #8320
Fixes #8315
> net/tstun, tsnet: make happier on WASI

- net/memnet/listener.go
> net/memnet: add optional Listener.NewConn config knob

- cmd/tailscale/cli/ping.go
(From https://github.com/tailscale/tailscale/pull/4147 which got closed before anybody noticed)
> tailscale ping: note that `-c` can take 0 for infinity

- Dockerfile
> Remove unused dependency from dockerfile

- .github/workflows/docker-file-build.yml
- Dockerfile
> .github/workflows: Add docker build check

- ipn/ipnlocal/serve.go
- ipn/ipnlocal/serve_test.go
Adds two new headers to HTTP serve proxy:
- `Tailscale-User-Login`: Filled with requester's login name.
- `Tailscale-User-Name`: Filled with requester's display name.
These headers only get filled when the SrcAddr is associated with a non-tagged (i.e. user-owned) node within the client's Tailnet.
The headers are passed through empty when the request originated from another tailnet, or the public internet (via funnel).
Updates https://github.com/tailscale/tailscale/issues/6954
> ipn/ipnlocal: add identity headers to HTTP serve proxy

- tool/gocross/autoflags.go
Fix from @agottardo, I am just a video-chat-to-keyboard interface
> tool/gocross: properly set simulator deployment target

- Dockerfile.base
> Dockerfile.base: install iputils

- go.mod
- go.sum
- net/dns/recursive/recursive.go
Change-Id: If4de6a84448a17dd81cc2a8af788bd18c3d0bbe3
> go.mod, net/dns/recursive: update github.com/miekg/dns

- types/views/views.go
- types/views/views_test.go
Updates #cleanup for change elsewhere.
> types/views: add Slice methods on Slice views

- cmd/tailscale/cli/funnel.go
- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_test.go
- ipn/ipn_clone.go
- ipn/ipn_view.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/serve.go
- ipn/serve.go
> {cmd/tailscale/cli,ipn}: add http support to tailscale serve

- ipn/ipnlocal/network-lock.go
> ipn/ipnlocal: quiet some spammy network lock logging

- ssh/tailssh/incubator.go
This reverts commit dc5bc32d8fbacd7e1dd34d138de542d401a11ebd.
It broke tests. (sadly, ones which we have disabled on CI, but go test ./ssh/tailssh broke)
> Revert "ssh/tailssh: change to user directory when running login/command"

- tool/gocross/gocross-wrapper.sh
Also switch the wrapper script to use bash not posix shell. We now depend on bash elsewhere for saner behavior in esoteric areas, so might as well use it everywhere for consistency.
Fixes #8425
> tool/gocross: make gocross behave with pre-release Go toolchains

- api.md
> api.md: add info for key description

- syncs/shardedmap.go
- syncs/shardedmap_test.go
> syncs: add ShardedMap type

- types/key/node_test.go
> types/key: add test for NodePublic.Shard

- api.md
- net/dns/resolver/tsdns.go
- net/netmon/netmon_linux.go
- wgengine/router/router_linux.go
> all: adjust case of "IPv4" and "IPv6"

- tailcfg/tailcfg.go
This change updates the documentation for the fields on the location struct.
Updates tailscale/corp#12146
> tailcfg: update location docs

- syncs/shardedmap.go
- syncs/shardedmap_test.go
To let callers do atomic/CAS-like operations.
> syncs: add ShardedMap.Mutate

- util/lru/lru.go
- util/lru/lru_test.go
> util/lru: add a package for a typed LRU cache

- cmd/testwrapper/flakytest/flakytest_test.go
> cmd/testwrapper/flakytest: clearly describe why TestFlakeRun fails

- cmd/testwrapper/testwrapper.go
Previously it would only print the failures without providing more information on which package the failures from.
This commit makes it so that it prints out the package information as well as the attempt numbers.
```
➜  tailscale.com git:(main) ✗ go run ./cmd/testwrapper ./cmd/...
ok       tailscale.com/cmd/derper
ok       tailscale.com/cmd/k8s-operator
ok       tailscale.com/cmd/tailscale/cli
ok       tailscale.com/cmd/tailscaled
=== RUN   TestFlakeRun
flakytest.go:38: flakytest: issue tracking this flaky test: https://github.com/tailscale/tailscale/issues/0
flakytest_test.go:41: First run in testwrapper, failing so that test is retried. This is expected.
--- FAIL: TestFlakeRun (0.00s)
FAIL     tailscale.com/cmd/testwrapper/flakytest
Attempt #2: Retrying flaky tests:
ok …
```
> cmd/testwrapper: output packages tested

- cmd/testwrapper/testwrapper.go
Previously it would wait for all tests to run before printing anything, instead stream the results over a channel so that they can be emitted immediately.
Updates #8493
> cmd/testwrapper: stream output results

- release/dist/dist.go
> release/dist: add helper to build Go binaries with custom tags

- metrics/metrics.go
- metrics/metrics_test.go
> metrics: add LabelMap.GetIncrFunc

- tempfork/heap/heap.go
- tempfork/heap/heap_test.go
> tempfork/heap: add copy of Go's container/heap but using generics

- ipn/ipnlocal/local.go
- ipn/ipnlocal/network-lock.go
- ipn/ipnlocal/network-lock_test.go
- tailcfg/tailcfg.go
Updates corp#8568
Signed-off-by: Tom DNetto <tom@tailscale.com>
> ipn: rename CapTailnetLockAlpha -> CapTailnetLock

- logtail/logtail.go
> logtail: fix race condition with sockstats label

- cmd/testwrapper/testwrapper.go
`go test -json` outputs invalid JSON when a build fails. Handle that case by reseting the json.Decode and continuing to read.
Updates #8493
> cmd/testwrapper: handle build failures

- tstest/clock.go
- tstest/clock_test.go
- tstime/tstime.go
> tstime: add Since method

- .github/workflows/govulncheck.yml
Run it daily with a Slack message on failures. Also allow manual triggering for testing.
> .github/workflows: add govulncheck workflow

- tsnet/example_tshello_test.go
- tsnet/example_tsnet_test.go
Closes #8288
Follows the examples from the KB[1].
[1]: https://tailscale.com/kb/1244/tsnet/
> tsnet: add examples

- tka/tka.go
Updates https://github.com/tailscale/corp/issues/8568
Signed-off-by: Tom DNetto <tom@tailscale.com>
> tka: allow checkpoint AUMs to change TKA state

- cmd/tailscale/cli/cli.go
> cmd/tailscale/cli: ensure custom UsageFunc is always set

- logtail/backoff/backoff.go
- logtail/logtail.go
- logtail/logtail_test.go
Updates #8587
Signed-off-by: Claire Wang <claire@tailscale.com>
> logtail: use tstime

- api.md
> api.md: add documentation to API endpoint about SCIM group warnings

- tailcfg/tailcfg.go
> tailcfg: deprecate Debug, flesh out Node.DERP docs

- tailcfg/tailcfg.go
- tailcfg/tailcfg_clone.go
- tailcfg/tailcfg_view.go
- types/persist/persist.go
- types/persist/persist_clone.go
- types/persist/persist_view.go
> tailcfg: add UserProfile.Groups

- cmd/tailscale/cli/update.go
Implement `tailscale update` on FreeBSD. This is much simpler than other platforms because `pkg rquery` lets us get the version in their repos without any extra parsing.
Updates #6995
> cmd/tailscale/cli: implement update on FreeBSD

- wgengine/magicsock/batching_conn.go
- wgengine/magicsock/blockforever_conn.go
- wgengine/magicsock/debugknobs.go
- wgengine/magicsock/debugknobs_stubs.go
- wgengine/magicsock/derp.go
- wgengine/magicsock/magicsock.go
- wgengine/magicsock/rebinding_conn.go
> wgengine/magicsock: factor out more separable parts

- wgengine/magicsock/magicsock.go
> wgengine/magicsock: document mysterious-looking assignment

- ipn/ipnlocal/c2n.go
- ipn/ipnlocal/cert.go
- ipn/ipnlocal/expiry.go
- ipn/ipnlocal/expiry_test.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/peerapi.go
- ipn/ipnlocal/peerapi_test.go
- ipn/localapi/localapi.go
Updates #8587
Signed-off-by: Claire Wang <claire@tailscale.com>
> ipn: use tstime

- tailcfg/tailcfg.go
> tailcfg: add helper to unmarshal PeerCap values

- derp/derphttp/derphttp_client.go
Like net/http.Server.BaseContext, this lets callers specify a base context for dials.
Updates tailscale/corp#12702
> derp/derphttp: add optional Client.BaseContext hook

- cmd/sniproxy/sniproxy.go
Count number of sessions, number of DNS queries answered successfully and in error, and number of http->https redirects.
Updates #1748
> cmd/sniproxy: add client metrics

- ipn/ipnlocal/local.go
- ipn/ipnlocal/peerapi.go
- net/interfaces/interfaces.go
- net/netcheck/netcheck.go
- net/netutil/ip_forward.go
> ipnlocal, net/*: deprecate interfaces.GetState, use netmon more for it

- tailcfg/tailcfg.go
> tailcfg: add CapabilityHTTPS const

- client/tailscale/localclient.go
- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_test.go
- ipn/localapi/localapi.go
- tailcfg/tailcfg.go
> tailcfg,ipn/localapi,client/tailscale: add QueryFeature endpoint

- ipn/ipnlocal/serve.go
- ipn/ipnlocal/serve_test.go
> ipn/ipnlocal: add profile pic header to serve HTTP proxy

- ipn/ipnlocal/local.go
> ipn/ipnlocal: make tests pass when offline

- derp/derp.go
- net/dns/recursive/recursive.go
> derp, net/dns/recursive: use Go 1.21 min

- control/controlhttp/http_test.go
These specific tests rely on some timers in the controlhttp code. Without time moving forward and timers triggering, the tests fail.
Updates #8587
> control/controlhttp: remove tstest.Clock from tests

- client/tailscale/localclient.go
- cmd/tailscale/cli/funnel.go
- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_test.go
- ipn/serve.go
- ipn/serve_test.go
- tailcfg/tailcfg.go
- tsnet/tsnet.go
- tstest/integration/testcontrol/testcontrol.go
> tailscale/cli: add interactive flow for enabling Funnel

- client/web/web.go
- cmd/tailscale/cli/web.go
> client/web: add web client Server struct

- tsnet/example/web-client/web-client.go
> tsnet: add new example serving the Tailscale web client

- ipn/ipnlocal/local.go
- net/tsdial/tsdial.go
> ipn/ipnlocal,net/tsdial: update docs/rename funcs

- client/web/index.html
- client/web/package.json
- client/web/src/components/app.tsx
- client/web/src/index.tsx
- client/web/yarn.lock
> client/web: pipe through to React in dev mode

- .github/workflows/test.yml
> .github: use testwrapper on windows

- client/web/package.json
- client/web/src/index.tsx
- client/web/tsconfig.json
- client/web/yarn.lock
Also allows us to use absolute import paths (see change in index.tsx).
> client/web: add tsconfig.json

- hostinfo/hostinfo.go
> hostinfo: add Home Assistant Add-On detection

- clientupdate/clientupdate.go
- clientupdate/clientupdate_test.go
Implement naive update for Synology packages, using latest versions from pkgs.tailscale.com. This is naive because we completely trust pkgs.tailscale.com to give us a safe package. We should switch this to some better signing mechanism later.
I've only tested this on one DS218 box, so all the CPU architecture munging is purely based on docs.
Updates #6995
> clientupdate: implement updates for Synology

- control/controlclient/auto.go
- control/controlclient/direct.go
See issue. This is a baby step towards passing through deltas
end-to-end from node to control back to node and down to the various
engine subsystems, not computing diffs from two full netmaps at
various levels. This will then let us support larger netmaps without
burning CPU.
But this change itself changes no behavior. It just changes a func
type to an interface with one method. That paves the way for future
changes to then add new NetmapUpdater methods that do more
fine-grained work than updating the whole world.
Updates #1909
> control/controlclient: refactor in prep for optimized delta handling

- control/controlclient/auto.go
No need to have it on Auto or be behind a mutex; it's only read/written
from a single goroutine. Move it there.
Updates tailscale/corp#5761
> control/controlclient: move lastUpdateGenInformed to tighter scope

- util/winutil/authenticode/authenticode_windows.go
> util/winutil/authenticode: add missing docs for CertSubjectError

- cmd/tailscale/cli/serve.go
When trying to use serve with https, send users through https cert provisioning enablement before editing the ServeConfig.
Updates tailscale/corp#10577
cc @samlinville
> cli/serve: add interactive flow for enabling HTTPS certs

- wgengine/pendopen.go
> wgengine: adjust debug logging for WireGuard-only peers

- wgengine/router/router_linux.go
> wgengine/router: always use nftables mode on gokrazy

- ssh/tailssh/user.go
Stupid mistake in earlier refactor.
Updates gokrazy/gokrazy#209
> ssh/tailssh: fix gokrazy SSH crash

- cmd/derper/mesh.go
- derp/derp.go
- derp/derp_client.go
- derp/derp_server.go
- derp/derp_test.go
- derp/derphttp/mesh_client.go
> derp: include src IPs in mesh watch messages

- client/tailscale/apitype/controltype.go
- tailcfg/tailcfg.go
- tailcfg/tailcfg_clone.go
- tailcfg/tailcfg_view.go
(Added earlier today in #8916, 57da1f150)
Updates tailscale/corp#13969
> tailcfg: rename prototype field to reflect its status

- CODEOWNERS
> CODEOWNERS: add the start of an owners file

- cmd/tailscale/cli/exitnode.go
- cmd/testwrapper/testwrapper.go
- util/osdiag/osdiag_windows_test.go
- wgengine/filter/filter_test.go
- wgengine/magicsock/endpoint.go
- wgengine/magicsock/magicsock_test.go
> all: import x/exp/maps as xmaps to distinguish from Go 1.21 "maps"

- control/controlclient/direct.go
- ipn/ipnlocal/local.go
- tailcfg/tailcfg.go
> tailcfg: add nodeAttrs for forcing OneCGNAT on/off [capver 71]

- clientupdate/clientupdate.go
- clientupdate/clientupdate_test.go
The hardware version in `/proc/sys/kernel/syno_hw_version` does not map exactly to versions in
https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures. It contains some slightly different version formats.
Instead, `/etc/synoinfo.conf` exists and contains a `unique` line with the CPU architecture encoded. Parse that out and filter through the list of architectures that we have SPKs for.
Tested on DS218 and DS413j.
Updates #8927
> clientupdate: parse /etc/synoinfo.conf to get CPU arch

- control/controlclient/map.go
- control/controlclient/map_test.go
- ipn/ipnlocal/local.go
- tailcfg/tailcfg.go
- types/netmap/netmap.go
- types/netmap/netmap_test.go
- wgengine/bench/wg.go
- wgengine/magicsock/magicsock.go
- wgengine/userspace.go
- wgengine/userspace_test.go
- wgengine/watchdog.go
- wgengine/wgengine.go
> all: remove some Debug fields, NetworkMap.Debug, Reconfig Debug arg

- clientupdate/clientupdate.go
- clientupdate/clientupdate_test.go
Cherry-pick #8940 into 1.48.1.
Fixes #8927
> clientupdate: parse /etc/synoinfo.conf to get CPU arch (#8940)

- util/linuxfw/nftables_runner.go
- util/linuxfw/nftables_runner_test.go
This commit tries to mimic the way iptables-nft work with the filewall rules. We follow the convention of using tables like filter, nat and the conventional chains, to make our nftables implementation work with ufw.
Updates: #391
> util/linuxfw: reorganize nftables rules to allow it work with ufw

- tailcfg/tailcfg.go
- tailcfg/tailcfg_clone.go
- tailcfg/tailcfg_view.go
- tstest/integration/testcontrol/testcontrol.go
> tailcfg: remove unused Domain field from Login/User

- tailcfg/tailcfg.go
> tailcfg: update docs on NetInfo.FirewallMode

- control/controlclient/direct.go
Just misc cleanups.
Updates #1909
> control/controlclient: scope a variable tighter, de-pointer a *time.Time

- tsnet/tsnet.go
Updates https://github.com/tailscale/tailscale/issues/1748
> tsnet: add support for clientmetrics.

- tailcfg/tailcfg.go
- util/linuxfw/nftables_runner.go
- util/linuxfw/nftables_runner_test.go
- wgengine/router/router_linux.go
Commits from 
* https://github.com/tailscale/tailscale/pull/8947
* https://github.com/tailscale/tailscale/pull/8953
> 1.48 cherry-picks for nftables

- control/controlclient/direct.go
- control/controlclient/map.go
- control/controlclient/map_test.go
Now mapSession has a bunch more fields and methods, rather than being
just one massive func with a ton of local variables.
So far there are no major new optimizations, though. It should behave
the same as before.
This has been done with an eye towards testability (so tests can set
all the callback funcs as needed, or not, without a huge Direct client
or long-running HTTP requests), but this change doesn't add new tests
yet. That will follow in the changes which flesh out the NetmapUpdater
interface.
Updates #1909
> control/controlclient: flesh out mapSession to break up gigantic method

- net/portmapper/upnp.go
Port 0 is interpreted, per the spec (but inconsistently among router software) as requesting to map every single available port on the UPnP gateway to the internal IP address. We'd previously avoided picking ports below 1024 for one of the two UPnP methods (in #7457), and this change moves that logic so that we avoid it in all cases.
Updates #8992
Change-Id: I20d652c0cd47a24aef27f75c81f78ae53cc3c71e
> net/portmapper: never select port 0 in UPnP

- net/portmapper/upnp.go
Port 0 is interpreted, per the spec (but inconsistently among router software) as requesting to map every single available port on the UPnP gateway to the internal IP address. We'd previously avoided picking ports below 1024 for one of the two UPnP methods (in #7457), and this change moves that logic so that we avoid it in all cases.
Updates #8992
Change-Id: I20d652c0cd47a24aef27f75c81f78ae53cc3c71e (cherry picked from commit 77ff705545d63b30c170d8958cd76be764bc8a6b)
> net/portmapper: never select port 0 in UPnP (1.48 cherry-pick)

- control/controlclient/map.go
Drop in the bucket, but have to start somewhere.
Real wins will come once this is done for peers.
│     before     │                after                │
│      B/op      │     B/op       vs base              │
MapSessionDelta/size_10-8      10.213Ki ± ∞ ¹   9.650Ki ± ∞ ¹  -5.51% (p=0.008 n=5)
MapSessionDelta/size_100-8      83.64Ki ± ∞ ¹   83.08Ki ± ∞ ¹  -0.67% (p=0.008 n=5)
MapSessionDelta/size_1000-8     800.8Ki ± ∞ ¹   800.3Ki ± ∞ ¹  -0.07% (p=0.008 n=5)
MapSessionDelta/size_10000-8    7.712Mi ± ∞ ¹   7.711Mi ± ∞ ¹  -0.01% (p=0.008 n=5)
geomean                         271.1Ki         266.8Ki        -1.59%
│    before    │               after                │
│  allocs/op   │  allocs/op    vs base              │
MapSessionDelta/size_10-8       73.00 ± ∞ ¹    72.00 ± ∞ ¹  -1.37% …
> control/controlclient: don't clone self node on each NetworkMap

- control/controlclient/map.go
- control/controlclient/map_test.go
The mapSession code was previously quadratic: N clients in a netmap
send updates proportional to N and then for each, we do N units of
work. This removes most of that "N units of work" per update. There's
still a netmap-sized slice allocation per update (that's #8963), but
that's it.
Bit more efficient now, especially with larger netmaps:
│     before     │                after                │
│     sec/op     │   sec/op     vs base                │
MapSessionDelta/size_10-8       47.935µ ±  3%   1.232µ ± 2%  -97.43% (p=0.000 n=10)
MapSessionDelta/size_100-8      79.950µ ±  3%   1.642µ ± 2%  -97.95% (p=0.000 n=10)
MapSessionDelta/size_1000-8    355.747µ ± 10%   4.400µ ± 1%  -98.76% (p=0.000 n=10)
MapSessionDelta/size_10000-8   3079.71µ ±  3%   27.89µ ± 3%  -99.09% (p=0.000 n=10)
geomean …
> control/controlclient: remove quadratic allocs in mapSession

- client/web/web.go
> client/web: track web client initializations

- release/dist/cli/cli.go
Add a new subcommand to generate a Ed25519 key pair for release signing. The same command can be used to generate both root and signing keys.
Updates #8760
> release/dist/cli: add gen-key command

- tsweb/debug.go
> tsweb: clean up pprof handler registration, document why it's there

- cmd/tailscale/cli/web.go
> cli/web: pass existing localClient to web client

- cmd/tailscaled/debug.go
- ipn/ipnlocal/local.go
- logtail/logtail.go
- net/netmon/netmon.go
- net/netmon/netmon_test.go
- net/sockstats/sockstats_tsgo.go
- net/tsdial/tsdial.go
- wgengine/userspace.go
> net/netmon: make ChangeFunc's signature take new ChangeDelta, not bool

- ipn/ipnlocal/local.go
- wgengine/magicsock/magicsock.go
- wgengine/magicsock/magicsock_test.go
Upcoming work on incremental netmap change handling will require some
replumbing of which subsystems get notified about what. Done naively,
it could break "tailscale status --json" visibility later. To make sure
I understood the flow of all the updates I was rereading the status code
and realized parts of ipnstate.Status were being populated by the wrong
subsystems.
The engine (wireguard) and magicsock (data plane, NAT traveral) should
only populate the stuff that they uniquely know. The WireGuard bits
were fine but magicsock was populating stuff stuff that LocalBackend
could've better handled, so move it there.
Updates #1909
> ipn/ipnlocal, wgengine/magicsock: move UpdateStatus stuff around

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/9010
> scripts/installer.sh: add CloudLinux and Alibaba Linux

- client/web/web.go
Under normal circumstances, you would typically want to keep the default behavior of requiring secure cookies.  In the case of the Tailscale web client, we are regularly serving on localhost (where secure cookies don't really matter), and/or we are behind a reverse proxy running on a network appliance like a NAS or Home Assistant. In those cases, those devices are regularly accessed over local IP addresses without https configured, so would not work with secure cookies.
cc @noncombatant @awly
> client/web: don't require secure cookies for csrf

- net/netmon/netmon.go
- net/netmon/polling.go
This simplifies some netmon code in prep for other changes.
It breaks up Monitor.debounce into a helper method so locking is easier to read and things unindent, and then it simplifies the polling netmon implementation to remove the redundant stuff that the caller (the Monitor.debounce loop) was already basically doing.
Updates #9040
> net/netmon: factor out debounce loop, simplify polling impl

- clientupdate/distsign/distsign.go
- release/dist/cli/cli.go
Now we have all the commands to generate the key hierarchy and verify that signing keys were signed correctly:
```
$ ./tool/go run ./cmd/dist gen-key --priv-path root-priv.pem --pub-path root-pub.pem
wrote private key to root-priv.pem
wrote public key to root-pub.pem
$ ./tool/go run ./cmd/dist gen-key --priv-path signing-priv.pem --pub-path signing-pub.pem
wrote private key to signing-priv.pem
wrote public key to signing-pub.pem
$ ./tool/go run ./cmd/dist sign-key --root-priv-path root-priv.pem --sign-pub-path signing-pub.pem
wrote signature to signature.bin
$ ./tool/go run ./cmd/dist verify-key-signature --root-pub-path root-pub.pem --sign-pub-path signing-pub.pem --sig-path signature.bin
signature ok
```
Updates #8760
> release/dist/cli: add sign-key and verify-key-signature commands

- cmd/containerboot/main.go
Previously we would not reapply changes to TS_HOSTNAME etc when then the container restarted and TS_AUTH_ONCE was enabled.
This splits those into two steps login and set, allowing us to only rerun the set step on restarts.
Updates #502
> cmd/containerboot: reapply known args on restart

- scripts/installer.sh
Fixes https://github.com/tailscale/tailscale/issues/8648
Fixes https://github.com/tailscale/tailscale/issues/8737
Fixes https://github.com/tailscale/tailscale/issues/9087
> scripts/installer: add Kaisen, Garuda, Fedora-Asahi.

- tsweb/tsweb.go
Fly apps all set X-Forwarded-For, which breaks debug access even with a preshared key otherwise.
> tsweb: check for key-based debug access before XFF check

- cmd/containerboot/main.go
On k8s the serve-config secret mount is symlinked so checking against the Name makes us miss the events.
Updates #7895
> cmd/containerboot: account for k8s secret reflection in fsnotify

- flake.lock
- flake.nix
> flake.nix: use Go 1.21 to build tailscale flake

- types/views/views.go
- types/views/views_test.go
> types/views: add SliceEqual, like std slices.Equal

- util/deephash/deephash.go
- util/deephash/deephash_test.go
> util/deephash: add IncludeFields, ExcludeFields HasherForType Options

- ipn/ipnlocal/c2n.go
- tailcfg/c2ntypes.go
> ipn/ipnlocal: move C2NUpdateResponse to c2ntypes.go

- control/controlclient/map.go
- control/controlclient/map_test.go
> control/controlclient: convert PeersChanged nodes to patches internally

- cmd/tailscale/cli/cli_test.go
- cmd/tailscale/cli/serve_test.go
- control/controlclient/map_test.go
- ipn/ipnlocal/profiles_test.go
- types/logger/logger.go
- types/logger/logger_test.go
Printing out JSON representation things in log output is pretty common.
> types/logger: add AsJSON

- control/controlclient/auto.go
De-pointer a *time.Time type, move it after the mutex which guard is,
rename two test-only methods with our conventional "ForTest" suffix.
> control/controlclient: clean up a few little things

- client/web/src/api.ts
- client/web/src/hooks/node-data.ts
> client/web: pull SynoToken logic into apiFetch

- clientupdate/clientupdate.go
On linux users can install Tailscale via package managers or direct tarball downloads. Detect when Tailscale is not installed via a package manager so we can pick the correct update mechanism. Leave the tarball update function unimplemented for now (coming in next PR!).
Updates #6995
Updates #8760
> clientupdate: detect when tailscale is installed without package manager

- client/web/web_test.go
> client/web: fix data race

- cmd/sniproxy/sniproxy.go
Add support for TS_APPC_* variables to supply arguments by
switching to https://github.com/peterbourgon/ff for CLI
flag parsing. For example:
TS_APPC_FORWARDS=tcp/22/github.com ./sniproxy
Updates https://github.com/tailscale/tailscale/issues/1748
> cmd/sniproxy: switch to peterbourgon/ff for flags

- cmd/k8s-operator/ingress.go
- cmd/k8s-operator/proxy.go
- cmd/k8s-operator/svc.go
- util/set/slice.go
> cmd/k8s-operator: add metrics to track usage

- control/controlclient/auto.go
- control/controlclient/controlclient_test.go
- control/controlclient/status.go
> control/controlclient: unexport Status.state, add test-only accessor

- control/controlclient/auto.go
- control/controlclient/status.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/state_test.go
> control/controlclient: de-pointer Status.PersistView, document more

- control/controlclient/direct.go
> control/controlclient: use slices package more

- cmd/tsconnect/wasm/wasm_js.go
- control/controlclient/auto.go
- control/controlclient/client.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/local_test.go
- ipn/ipnlocal/state_test.go
- tstest/log.go
- types/logger/logger.go
> control/controlclient: remove unused StartLogout

- ipn/ipnlocal/local.go
* don't try to re-Start (and thus create a new client) during Shutdown
* in tests, wait for controlclient to fully shut down when replacing it
* log a bit more
Updates tailscale/corp#14139
Updates tailscale/corp#13175 etc
Updates #9178 and its flakes.
> ipn/ipnlocal: deflake some tests

- tsnet/tsnet.go
LocalBackend.Shutdown already does it.
> tsnet: remove redundant ephemeral logout on close

- control/controlclient/auto.go
Then use the Locked variants in Shutdown while we already hold the lock.
> control/controlclient: rename Auto cancel methods, add missing Lock variant

- .github/workflows/test.yml
> .github: do not use testwrapper for benchmarks

- .github/workflows/test.yml
Drops time by several minutes.
Updates #9182
> .github/workflows: only run bench all on packages with benchmarks

- control/controlclient/direct.go
- ipn/ipnlocal/local.go
> control/controlclient, ipn/ipnlocal: unplumb a bool true literal opt

- control/controlclient/auto.go
Don't just start goroutines and hope for them to be ordered.
Fixes potential regression from earlier 7074a40c0.
> control/controlclient: serialize Observer calls

- cmd/testwrapper/testwrapper.go
It would just fail the entire pkg, but would not print any logs. It was already tracking all the logs, so have it emit them when the pkg fails/times out.
Updates #9231
> cmd/testwrapper: emit logs of failed tests on timeout

- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-file-build.yml
- .github/workflows/flakehub-publish-tagged.yml
- .github/workflows/go-licenses.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/govulncheck.yml
- .github/workflows/installer.yml
- .github/workflows/test.yml
- .github/workflows/update-flake.yml
- cmd/gitops-pusher/README.md
checkout@v3 is broken:
actions/checkout#1448
> .github,cmd/gitops-pusher: update to checkout@v4

- ipn/ipnlocal/local.go
It would acquire the lock, calculate `nextState`, relase the lock, then call `enterState` which would acquire the lock again. There were obvious races there which could lead to nil panics as seen in a test in a different repo.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x70 pc=0x1050f2c7c]
goroutine 42240 [running]:
tailscale.com/ipn/ipnlocal.(*LocalBackend).enterStateLockedOnEntry(0x14002154e00, 0x6)
tailscale.com/ipn/ipnlocal/local.go:3715 +0x30c
tailscale.com/ipn/ipnlocal.(*LocalBackend).enterState(0x14002154e00?, 0x14002e3a140?)
tailscale.com/ipn/ipnlocal/local.go:3663 +0x8c
tailscale.com/ipn/ipnlocal.(*LocalBackend).stateMachine(0x14001f5e280?)
tailscale.com/ipn/ipnlocal/local.go:3836 +0x2c …
```
> ipn/ipnlocal: fix race in enterState

- util/cmpver/version_test.go
> util/cmpver: add a few tests covering different OS versions

- net/dns/publicdns/publicdns.go
Updates #9255
Change-Id: I4213c29e0f91ea5aa0304a5a026c32b6690fead9
> net/dns/publicdns: add support for Wikimedia DNS

- cmd/tailscale/cli/cli.go
This also makes "HIDDEN: " work (requires the custom UsageFunc).
Updates #6995
> cmd/tailscale/cli: make update visible in list

- util/limiter/limiter.go
- util/limiter/limiter_test.go
- util/lru/lru.go
> util/limiter: add a keyed token bucket rate limiter

- tsweb/varz/varz.go
> tsweb/varz: fix exporting histograms

- metrics/metrics.go
> metrics: add missing comma in histogram JSON export

- cmd/tailscale/cli/serve_dev.go
Previously, foreground mode only worked in the simple case of `tailscale funnel <port>`. This PR ensures that whatever you can do in the background can also be done in the foreground such as setting mount paths or tcp forwarding.
Updates #8489
> cmd/tailscale: combine foreground and background serve logic

- ssh/tailssh/tailssh.go
> ssh/tailssh: log when recording starts and finishes

- types/netmap/netmap.go
> types/netmap: delete a copy of views.SliceEqual

- ipn/ipnstate/ipnstate.go
> ipn/ipnstate: add some missing docs

- ipn/ipnstate/ipnstate.go
- types/key/node.go
> ipn/ipnstate: address TODO about garbage during peer sorting

- cmd/tailscale/cli/serve_dev.go
This PR ensures calls to the LocalBackend are not happening multiples times and ensures the set/unset methods are only manipulating the serve config
Updates #8489
> **Note**
> Behind the `TAILSCALE_USE_WIP_CODE` flag
> cmd/tailscale: reduce duplicate calls to LocalBackend in funnel WIP

- tailcfg/tailcfg.go
- tailcfg/tailcfg_test.go
> tailcfg: flesh out some docs on MapResponse, clarify slices w/ omitempty

- cmd/testwrapper/testwrapper.go
Sometimes `go test` would exit and close its stdout before we started reading it, and we would return that "file closed" error then forget to os.Exit(1). Fixed to prefer the go test subprocess error and exit regardless of the type of error.
Fixes #9334
> cmd/testwrapper: fix exit deflake

- ipn/ipnlocal/serve.go
- ipn/ipnlocal/serve_test.go
- ipn/localapi/localapi.go
This PR adds optimistic concurrency control in the local client and api in order to ensure multiple writes of the ServeConfig do not conflict with each other.
Updates #9273
> ipn/localapi, ipn/ipnlocal: add etag support for SetServeConfig

- net/portmapper/igd_test.go
- net/portmapper/upnp.go
- net/portmapper/upnp_test.go
Some routers don't support lease times for UPnP portmapping; let's fall back to adding a permanent lease in these cases. Additionally, add a proper end-to-end test case for the UPnP portmapping behaviour.
Updates #9343
Change-Id: I17dec600b0595a5bfc9b4d530aff6ee3109a8b12
> net/portmapper: fall back to permanent UPnP leases if necessary

- clientupdate/clientupdate.go
DSM6 does not automatically restart packages on install, we have to do it explicitly.
Also, DSM6 has a filter for publishers in Package Center. Make the error message more helpful when update fails because of this filter not allowing our package.
Fixes #9361
> clientupdate: restart tailscale after install on DSM6

- control/controlclient/auto.go
- control/controlclient/direct.go
- control/controlclient/map.go
- control/controlknobs/controlknobs.go
- control/controlknobs/controlknobs_test.go
- ipn/ipnlocal/local.go
- ipn/ipnlocal/local_test.go
- tailcfg/tailcfg.go
- types/netmap/netmap.go
- types/netmap/netmap_test.go
- types/netmap/nodemut.go
- types/netmap/nodemut_test.go
- wgengine/magicsock/endpoint.go
- wgengine/magicsock/magicsock.go
Currently only the top four most popular changes: endpoints, DERP home, online, and LastSeen.
Updates #1909
> control/controlclient, types/netmap: start plumbing delta netmap updates

- net/netmon/netmon.go
This logs that the gateway/self IP address has changed if one of the new values differs.
Updates #8992
Change-Id: I0919424b68ad97fbe1204dd36317ed6f5915411f
> net/netmon: log when the gateway/self IP changes

- ipn/ipnlocal/local.go
We always have one. Stop pretending we might not.
Instead, add one early panic in NewLocalBackend if we actually don't.
> ipn/ipnlocal: remove defensiveness around not having a magicsock.Conn

- tailcfg/tailcfg.go
> tailcfg: remove completed TODO from IsWireGuardOnly

- words/tails.txt
Particularly of the polydactyl kind.
> words: holy mole we need some more mammals

- cmd/k8s-operator/operator.go
- cmd/k8s-operator/proxy.go
The kube-apiserver proxy in the operator would only run in auth proxy mode but thats not always desirable. There are situations where the proxy should just be a transparent proxy and not inject auth headers, so do that using a new env var APISERVER_PROXY and deprecate the AUTH_PROXY env.
THe new env var has three options `false`, `true` and `noauth`.
Updates #8317
> cmd/k8s-operator: add APISERVER_PROXY env

- cmd/tailscale/cli/funnel.go
- cmd/tailscale/cli/serve.go
- cmd/tailscale/cli/serve_dev.go
- cmd/tailscale/cli/serve_test.go
- control/controlclient/map_test.go
- control/controlknobs/controlknobs.go
- envknob/logknob/logknob.go
- envknob/logknob/logknob_test.go
- ipn/ipnlocal/local.go
- ipn/ipnstate/ipnstate.go
- ipn/serve.go
- ipn/serve_test.go
- tailcfg/tailcfg.go
- tailcfg/tailcfg_clone.go
- tailcfg/tailcfg_view.go
- tstest/integration/testcontrol/testcontrol.go
- types/netmap/netmap.go
- wgengine/filter/filter_test.go
Instead of untyped string, add a type to identify these.
> tailcfg: define a type for NodeCapability

- types/views/views.go
- types/views/views_test.go
> types/views: add SliceContainsFunc like slices.ContainsFunc

- net/portmapper/portmapper.go
- net/portmapper/upnp.go
This should allow us to gather a bit more information about errors that we encounter when creating UPnP mappings. Since we don't have a "LabelMap" construction for clientmetrics, do what sockstats does and lazily register a new metric when we see a new code.
Updates #9343
Change-Id: Ibb5aadd6138beb58721f98123debcc7273b611ba
> net/portmapper: add clientmetric for UPnP error codes

- util/lru/lru.go
- util/lru/lru_test.go
> util/lru: update c.head when deleting the most recently used entry

- net/tstun/wrap.go
It might as well have been spewing out gibberish. This adds a nicer output format for us to be able to read and identify whats going on.
Sample output
```
natV4Config{nativeAddr: 100.83.114.95, listenAddrs: [10.32.80.33], dstMasqAddrs: [10.32.80.33: 407 peers]}
```
Fixes tailscale/corp#14650
> net/tstun: add better logging of natV4Config

- cmd/netlogfmt/main.go
- go.mod
- go.sum
Update github.com/go-json-experiment/json to the latest version and fix the build in light of some breaking API changes.
> go.mod: update github.com/go-json-experiment/json

- control/controlclient/direct.go
- net/dns/manager.go
- net/dns/osconfig.go
- wgengine/magicsock/peermtu.go
> wgengine/magicsock, controlclient, net/dns: reduce some logspam

- api.md
Updates tailscale/terraform-provider-tailscale#144
> api.md: document the `invalid` field of Get Key API response

- cmd/tailscale/cli/debug.go
- ipn/ipnlocal/local.go
- ipn/localapi/localapi.go
For loading testing & profiling the cost of full netmap updates.
Updates #1909
> ipn/{ipnlocal,localapi}, cli: add debug force-netmap-update

- cmd/k8s-operator/operator.go
At the moment service and ingress reconcilers use the same filter to reconcile parent `Service`/parent `Ingress` when there is an event on a child resource. That means that if there is an event on parent `Service`s child resource, ingress-reconciler will also get triggered and look for an `Ingress` with a matching name and vice versa- this means some wasted CPU cycles and confusing log messages for users.
Thsi PR fixes the reconcile filters to prevent that.
Updates tailscale/tailscale#502
> cmd/k8s-operator: fix reconcile filters

- ipn/ipnlocal/peerapi.go
- ipn/ipnlocal/peerapi_test.go
Also adding tests to ensure this works.
> ipn/ipnlocal: prevent putting file if file already exists

- client/web/web.go
Remove the "JSON" ending, we no longer have a non-JSON version, it was removed in https://github.com/tailscale/tailscale/commit/d74c771fdaab75f9e1785074bc402f4c95ac62d1 when we switched from the legacy web client to React.
Also combine getNodeData into serveGetNodeData now that serveGetNodeData is the single caller of getNodeData.
A #cleanup
> client/web: refactor serveGetNodeData

- types/key/node.go
> types/key: update some doc strings for public key serialization

- cmd/testwrapper/testwrapper.go
For parsing by other tools.
Updates tailscale/corp#14975
> cmd/testwrapper: output machine-readable JSON on test flakes

- cmd/testwrapper/flakytest/flakytest.go
- cmd/testwrapper/testwrapper.go
> cmd/testwrapper: include flake URL in JSON metadata

- control/controlclient/client.go
- ipn/ipnlocal/local.go
- tsnet/tsnet.go
- tsnet/tsnet_test.go
Thanks to @qur and @eric for debugging!
Fixes #6973
> tsnet: add a test for restarting a tsnet server, fix Windows

- go.mod
- go.sum
> go.mod: bump wingoes for cross-platform HRESULT definition

- util/set/handle.go
- util/set/set.go
- util/set/set_test.go
- util/set/slice.go
Also give each type of set its own file.
> util/set: add some useful utility functions for Set

- wgengine/magicsock/magicsock_linux.go
> wgengine/magicsock: use x/sys/unix constants for UDP GSO

- go.mod
- go.sum
> go.mod: bump wireguard-go

- words/tails.txt
It's no conspiracy that I love learning about new words.
Updates tailscale/corp#14698
> words: i can't help but rave about these additions

- cmd/cloner/cloner.go
- cmd/viewer/tests/tests_clone.go
- tailcfg/tailcfg_clone.go
- wgengine/filter/filter_clone.go
- wgengine/wgcfg/wgcfg_clone.go
A wild @josharian appears with a good suggestion for a refactor, thanks Josh!
Updates #9410
> cmd/cloner,*: optimize nillable slice cloner

- clientupdate/distsign/distsign.go
- ipn/ipnlocal/c2n.go
- ssh/tailssh/tailssh.go
- util/httpm/httpm_test.go
> util/httpm, all: add a test to make sure httpm is used consistently

- tool/gocross/autoflags.go
- tool/gocross/autoflags_test.go
> tool/gocross: merge user's build tags and implicitly added build tags together

- util/race/race_test.go
Change-Id: Iff147268db50251d498fff5213adb8d4b8c999d4
> util/race: add test to confirm we don't leak goroutines

- control/controlclient/noise.go
Fixes a deadlock observed in a different repo.
Updates tailscale/corp#14950
Updates tailscale/corp#14515
Updates tailscale/corp#14139
Updates tailscale/corp#13175
> control/controlclient: fix deadlock in shutdown

- net/dns/resolver/forwarder_test.go
Change-Id: I2d073220bb6ac78ba88d8be35085cc23b727d69f
> net/dns/resolver: fix flaky test

- client/web/web.go
Adds browser session cache, to be used to store sessions for the full management web client.
> client/web: add browser session cache to web.Server

- ipn/ipnlocal/peerapi.go
This is being moved to taildrop, so clean it up to stop depending on so much unreleated functionality by removing a dependency on peerAPIHandler.
> ipn/ipnlocal: cleanup incomingFile

- tool/gocross/autoflags.go
- tool/gocross/autoflags_test.go
> tool/gocross: don't absorb --tags flags passed to subcommand

- ipn/ipnlocal/local.go
- ipn/ipnlocal/peerapi.go
- ipn/ipnlocal/peerapi_test.go
- taildrop/retrieve.go
- taildrop/send.go
- taildrop/taildrop.go
- taildrop/taildrop_test.go
Cleaning up taildrop logic for sending files.
> {ipn/ipnlocal, taildrop}: move put logic to taildrop

- posture/serialnumber_macos.go
- posture/serialnumber_macos_test.go
- posture/serialnumber_stub.go
Updates https://github.com/tailscale/tailscale/issues/5902
> posture: add get serial support for macOS

- tool/gocross/gocross-wrapper.sh
> tool/gocross: handle VERSION file not found

- net/tstun/wrap.go
- net/tstun/wrap_test.go
- types/ipproto/ipproto.go
Based on https://github.com/golang/go/wiki/CodeReviewComments#package-names.
> types/ipproto: drop IPProto from IPProtoVersion

- client/web/web.go
- cmd/tailscale/cli/web.go
- tsnet/example/web-client/web-client.go
> client/web: remove unused context param from NewServer

- util/nocasemaps/nocase.go
- util/nocasemaps/nocase_test.go
This is a dependency of other code being imported later.
Updates tailscale/corp#15043
> util/nocasemaps: import nocasemaps from corp

- words/tails.txt
So gnarly!
Updates tailscale/corp#14698
> words: Na na na na na na na na na na na na na na na na

- wgengine/filter/match.go
> wgengine/filter: use slices.Contains in another place

- ipn/ipnlocal/serve.go
These log paths were actually unexpected until the refactor in fe95d81b43df14c7b4dcf68c764816a430206d24. This moves the logs to the callsites where they are actually unexpected.
Fixes #9670
> ipn/ipnlocal: fix log spam from now expected paths

- words/tails.txt
These birds have been visually identified as having tails. Science prevails.
> words: flappy birds, but real life

- tailcfg/proto_port_range.go
- tailcfg/proto_port_range_test.go
> tailcfg: implement TextUnmarshaler on ProtoPortRange

- cmd/containerboot/main.go
This broke in a last minute refactor and seems to have never worked.
Fixes #9686
> cmd/containerboot: fix time based serveConfig watcher

- appctype/appconnector.go
- appctype/appconnector_test.go
> appctype: introduce a configuration schema for app connectors

- taildrop/resume.go
Perform the same m==nil check in Manager.{PartialFiles,HashPartialFile} as we do in the other methods.
Fix HashPartialFile is properly handle a length of -1.
> taildrop: minor cleanups and fixes

- control/controlclient/direct.go
- tailcfg/tailcfg.go
- tailcfg/tailcfg_clone.go
- tailcfg/tailcfg_view.go
- util/syspolicy/policy_keys.go
> tailcfg: add tailnet field to register request

- ipn/ipnlocal/local.go
> ipn/ipnlocal: include AutoUpdate prefs in HostInfo.AllowsUpdate

- cmd/tailscaled/tailscaled.go
- net/tstun/fake.go
- net/tstun/wrap.go
- net/tstun/wrap_test.go
- tsd/tsd.go
- tsnet/tsnet.go
- wgengine/magicsock/magicsock_test.go
> cmd/tailscaled,net/tstun: fix data race on start-up in TUN mode

- .github/workflows/test.yml
- cmd/testwrapper/testwrapper.go
- tstest/integration/integration.go
- tstest/integration/integration_test.go
- wgengine/magicsock/endpoint.go
- wgengine/magicsock/magicsock.go
Two commits:
* fix a race in magicsock (found by second commit)
* add integration test that runs as root in TUN mode & catches races (with @maisem)
Fixes #9801
Updates #7894
> tstest/integration: add test for root TUN mode (including race mode)

- tsnet/tsnet_test.go
> tsnet: fix data race in TestFallbackTCPHandler

- go.mod
- go.sum
For https://github.com/alexbrainman/sspi/pull/13
Fixes #9131 (hopefully)
> go.mod: bump alexbrainman/sspi

- ipn/ipnlocal/peerapi.go
- ipn/ipnlocal/peerapi_test.go
- ipn/localapi/localapi.go
> ipn/ipnlocal/peerapi: refactoring taildrop to just one endpoint

- .github/workflows/test.yml
- cmd/testwrapper/testwrapper.go
- tstest/integration/integration_test.go
- tstest/tstest.go
> tstest, tstest/integration, github/workflows: shard integration tests

- tstest/integration/integration_test.go
- tstest/tstest.go
> tstest/tstest: add t.Parallel that can be disabled by TS_SERIAL_TESTS=true

- .github/workflows/test.yml
- ipn/conf.go
- ipn/conffile/conffile.go
- ipn/ipnlocal/local.go
- tstest/integration/integration_test.go
- tstest/integration/testcontrol/testcontrol.go
- tstest/tstest.go
> ipn/{conffile,ipnlocal}: start booting tailscaled from a config file w/ auth key

- client/web/web.go
Moves request authorization back into Server.serve to be run at the start of any request. Fixes Synology unstable track bug where client would get stuck unable to auth due to not rendering the Synology redirect auth html on index.html load.
> client/web: refactor authorizeRequest

- ipn/ipnlocal/peerapi.go
- ipn/localapi/localapi.go
- taildrop/resume.go
- taildrop/resume_test.go
While the previous logic was correct, it did not perform well. Resuming is a dance between the client and server, where
1. the client requests hashes for a partial file,
2. the server then computes those hashes,
3. the client computes hashes locally and compares them.
While step 2 is running, the client is sitting idle. While step 3 is running, the server is sitting idle.
By streaming over the block hash immediately after the server computes it, the client can start checking the hash, while the server works on the next hash (in a pipelined manner). This performs dramatically better and also uses less memory as we don't need to hold a list of hashes, but only need to handle one hash at a time.
There are two detriments to this approach:
* The HTTP API relies on a JSON stream, which is not a …
> taildrop: switch hashing to be streaming based

- taildrop/delete.go
WaitGroup.Wait should not be concurrently called WaitGroup.Add. In other words, we should not start new goroutines after shutodwn is called. Thus, add a conditional to check that shutdown has not been called before starting off a new waitAndDelete goroutine.
> taildrop: fix theoretical race condition

- client/web/web.go
- client/web/web_test.go
> client/web: add tests for authorizeRequest

- .github/workflows/golangci-lint.yml
> .github/workflows: update golangci-lint

- tailcfg/tailcfg.go
> tailcfg: add ID field to WebClientAuthResponse

- client/web/web.go
- client/web/web_test.go
Stores ID from tailcfg.WebClientAuthResponse in browser session data, and uses ID to hit control server /wait endpoint.
No longer need the control url cached, so removed that from Server. Also added optional timeNow field, initially to manage time from tests.
> client/web: use auth ID in browser sessions

- cmd/tailscale/cli/serve_v2.go
> cmd/tailscale/cli: update serve/funnel CLI help text

- cmd/k8s-operator/sts.go
This PR fixes a bug where users where unable to clean up proxy cluster resources after having manually deleted the associated device from control, see #9773 
Users should delete proxies by deleting or modifying the k8s cluster resources that they used to tell the operator to create they proxy. With this flow, the tailscale operator will delete the associated device from the control. However, in some cases users might have already deleted the device from the control manually- we should be able to recover from this state.
Updates tailscale/tailscale#9773
> cmd/k8s-operator: allow cleanup of cluster resources for deleted devices

- client/web/web.go
> client/web: set Server.cgiMode field

- wgengine/userspace.go
> wgnengine: remove unused field in userspaceEngine

- cmd/tailscale/cli/set.go
- cmd/tailscale/cli/update.go
> cmd/tailscale/cli: unhide auto-update flags and mark update as Beta

- client/web/web.go
- client/web/web_test.go
> client/web: pipe Server.timeNow() through session funcs

- cmd/tailscale/cli/serve_legacy.go
- cmd/tailscale/cli/serve_v2.go
- cmd/tailscale/cli/serve_v2_test.go
The TestServeDevConfigMutations test has 63 steps that all run under the same scope. This tests breaks them out into isolated subtests that can be run independently.
Updates #8489
> cmd/tailscale/cli: refactor TestServeDevConfigMutations

- clientupdate/clientupdate.go
> clientupdate: disable auto-updates on Synology for now

- net/portmapper/portmapper.go
Simplify UPnP error metrics by using the new syncs.Map.LoadOrInit method.
> net/portmapper: convert UPnP metrics to new syncs.Map.LoadOrInit method

- cmd/tailscale/cli/serve_v2.go
- cmd/tailscale/cli/serve_v2_test.go
We prevent shodow configs when starting a foreground when a background serve config already exists for the serve type and port. This PR improves the messaging to let the user know how to remove the previous config.
Updates #8489
ENG-2314
> cmd/tailscale/cli: improve error when bg serve config is present

- net/portmapper/portmapper.go
Change-Id: Iea558024c038face24cc46584421998d10f13a66
> net/portmapper: avoid alloc in getUPnPErrorsMetric

- safesocket/basic_test.go
- safesocket/pipe_windows.go
- safesocket/pipe_windows_test.go
Follow-up to earlier #9049.
Updates #9049
> safesocket: make clear which net.Conns are winio types

- clientupdate/clientupdate.go
> clientupdate: check for privileges earlier

- tsnet/tsnet.go
- tsnet/tsnet_test.go
- tstest/integration/testcontrol/testcontrol.go
Terminating traffic to IPs which are not the native IPs of the node requires the netstack subsystem to intercept trafic to an IP it does not consider local. This PR switches on such interception. In addition to supporting such termination, this change will also enable exit nodes and subnet routers when running in userspace mode.
Tailscalars can review [this slack thread](https://tailscale.slack.com/archives/CQQ1AUCCE/p1698171962568549) for further context.
DO NOT MERGE until 1.52 is cut.
Updates: https://github.com/tailscale/corp/issues/15038
> tsnet: enable use-cases with non-native IPs by setting ns.ProcessSubnets

- go.mod
- go.sum
> go.mod: update wireguard-go to enable TUN UDP GSO/GRO

- cmd/derper/mesh.go
- derp/derphttp/derphttp_client.go
- derp/derphttp/derphttp_test.go
- derp/derphttp/mesh_client.go
Fix from #9968, tests from #9719
> derp/derphttp: fix race in mesh watcher

- util/set/set.go
- util/set/set_test.go
> util/set: add some more Set operations
