tailscale/tailscale

net/dnscache/dnscache.go
net/dnscache/dnscache_test.go

I saw our graph of IPv6 vs IPv4 connections, and I suspect that this is the reason that we're seeing so many v4 connections. It looks like we're trying the first IP and then waiting, which means we're trying an IPv4 address first and not actually racing a v6 connection.

net/dnscache: try IPv6 addresses first

---

net/dns/manager.go

Currently we forward unmatched queries to the default resolver on
Windows. This results in duplicate queries being issued to the same
resolver which is just wasted.
Updates #1659

net/dns: [win] respond with SERVFAIL queries when no resolvers

---

control/controlclient/direct.go
control/controlclient/noise.go
control/controlhttp/client.go

When connecting to `/ts2021` it is assumed that the control server is running in tcp/443 if using the fallback HTTPS method. This sometimes might not be the case :)
This PR allows to pass any addr to `controlhttp.Dial` - or if the addr does not include a port assume tcp/80 for http and tcp/443 for https.
Signed-off-by: Juan Font Alonso <juanfontalonso@gmail.com>

Allow any port for HTTPS when using Noise over TLS

---

.github/workflows/cifuzz.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cross-darwin.yml
.github/workflows/cross-freebsd.yml
.github/workflows/cross-openbsd.yml
.github/workflows/cross-wasm.yml
.github/workflows/cross-windows.yml
.github/workflows/depaware.yml
.github/workflows/go_generate.yml
.github/workflows/license.yml
.github/workflows/linux-race.yml
.github/workflows/linux.yml
.github/workflows/linux32.yml
.github/workflows/static-analysis.yml
.github/workflows/vm.yml
.github/workflows/windows.yml

Currently scheduled runs are not canceled when we update PRs, those
results are unused and the resources are just wasted. Instead of doing
that, this PR makes it so that when a PR is updated (force-pushed or new
commit added) the previous runs are canceled.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value

.github/workflows: cancel previous CI runs on PR update

---

cmd/tailscale/cli/debug.go
control/controlhttp/client_js.go

Accidental break from 64d482ff482b6a616d7f24f939dbc5093d93909b.

cmd/tailscale/cli: fix build break

---

tka/aum.go
tka/aum_test.go
tka/sig.go
tka/sig_test.go
tka/tailchonk.go
tka/tka.go
tka/tka_test.go

Unfortunately I can't use the regular names `MarshalBinary()` and `UnmarshalBinary()` due to cbor semantics :(

tka: Use strict decoding settings, implement Unserialize()

---

cmd/derper/derper.go
cmd/derpprobe/derpprobe.go
net/netcheck/netcheck.go
net/stun/stun.go
net/stun/stun_fuzzer.go
net/stun/stun_test.go
net/stun/stuntest/stuntest.go

Convert ParseResponse and Response to use netip.AddrPort instead of
net.IP and separate port.
Fixes #5281

net/stun: convert to use net/netip.AddrPort

---

ipn/ipnlocal/local.go
util/deephash/deephash.go
wgengine/userspace.go

Hashing []any is slow since hashing of interfaces is slow.
Hashing of interfaces is slow since we pessimistically assume
that cycles can occur through them and start cycle tracking.
Drop the variadic signature of Update and fix callers to pass in
an anonymous struct so that we are hashing concrete types
near the root of the value tree.

util/deephash: avoid variadic argument for Update

---

tailcfg/tailcfg.go

As result of https://github.com/tailscale/tailscale/pull/4323, clients can now connect to Noise over any HTTPS port. Although this is double encryption, it is common for Headscale users (as they tend to use random ports).
Given that Tailscale clients prior to merge that PR expect to have Noise-over-HTTPS in tcp/443, bumping CapabilityVersion helps us to identify which Noise-capable clients (capver<39) we should serve with the legacy protocol.
Signed-off-by: Juan Font Alonso <juanfontalonso@gmail.com>

Bump capver for clients to talk Noise over any HTTPS port

---

cmd/tailscaled/tailscaled.go

Apparently OpenBSD can forward packets with manual configuration,
https://github.com/tailscale/tailscale/issues/2498#issuecomment-1114216999
But this makes it work by default. People doing things by hand can
set TS_DEBUG_WRAP_NETSTACK=0 in the environment.

cmd/tailscaled: enable hybrid netstack mode on openbsd too

---

util/deephash/deephash.go
util/deephash/deephash_test.go

Put the t.Size() == 0 check first since this is applicable in all cases.
Drop the last struct field conditional since this is covered by the
sumFieldSize check at the end.

util/deephash: simplify canMemHash

---

util/deephash/deephash.go

No operation ever reads from this variable.

util/deephash: remove unused stack slice in typeIsRecursive

---

util/deephash/deephash.go
util/deephash/deephash_test.go
util/deephash/types.go
util/deephash/types_test.go

Also, rename canMemHash to typeIsMemHashable to be consistent.
There are zero changes to the semantics.

util/deephash: move typeIsRecursive and canMemHash to types.go

---

util/deephash/deephash.go
util/deephash/deephash_test.go
util/sha256x/sha256.go
util/sha256x/sha256_test.go

Rename Hash as Block512 to indicate that this is a general-purpose
hash.Hash for any algorithm that operates on 512-bit block sizes.
A subsequent commit will move the sha256x package to hashx.
This is done separately to avoid confusing git.

util/sha256x: rename Hash as Block512

---

cmd/tailscale/cli/configure-host.go

Several customers have had issues due to the permissions
on /dev/net. Set permissions to 0755.
Fixes https://github.com/tailscale/tailscale/issues/5048

cmd/tailscale: set /dev/net perms in configure-host

---

tailcfg/tailcfg.go

We're going to want to enable audit logging on a per-Tailnet basis. When this
happens, we want control to inform the Tailnet's clients of this capability.

tailcfg: add CapabilityDataPlaneAuditLogs.

---

cmd/tailscale/cli/up.go

this message shows up when running:
```sh
$ sudo tailscale up --advertise-routes=::/0 --advertise-exit-node
::/0 advertised without its IPv6 counterpart, please also advertise 0.0.0.0/0
```

fix typo in incomplete default routes error message

---

wgengine/magicsock/magicsock.go

The Start method was removed in 4c27e2fa22, but the comment on NewConn
still mentioned it doesn't do anything until this method is called.
Signed-off-by: Kris Brandow <kris.brandow@gmail.com>

wgengine/magicsock: Remove mention of Start

---

cmd/tsconnect/.gitignore
cmd/tsconnect/common.go

We can't write to src/ when tsconnect is used a dependency in another
repo (see also b763a12331d318d2dba52fb5b8ed8a407ba28b00). We therefore
need to switch from writing to src/ to using esbuild plugins to handle
the requests for wasm_exec.js (the Go JS runtime for Wasm) and the
Wasm build of the Go module.
This has the benefit of allowing Go/Wasm changes to be picked up without
restarting the server when in dev mode (Go compilation is fast enough
that we can do this on every request, CSS compilation continues to be
the long pole).
Fixes #5382

cmd/tsconnect: stop writing build artifacts into src/

---

cmd/nginx-auth/nginx-auth.go

When sharing nodes, the name of the sharee node is not exposed (instead it is hardcoded to "device-of-shared-to-user"), which means that we can't determine the tailnet of that node.  Don't immediately fail when that happens, since it only matters if "Expected-Tailnet" is used.

cmd/nginx-auth: allow use of shared nodes

---

ipn/ipnlocal/network-lock.go
tailcfg/tailcfg.go
tka/tka.go
tka/tka_test.go

- Transmit the nodeID so the server knows who we are. This is checked against the machine key used to authenticate the session, so attempts to spoof this value will result in an error.
- Implements a fast path for processing AUMs which just chain off of HEAD. I expect this to be the common case.

Fastpath for processing AUMs in the common case, tx NodeID during tka setup

---

.github/licenses.tmpl
.github/workflows/go-licenses.yml

This will update a licenses/tailscale.md file with all of our go dependencies and their respective licenses. Notices for other clients will be triggered by similar actions in other repos.
Example output that this will result in: https://github.com/willnorris/tailscale/blob/main/licenses/tailscale.md

licenses: add GitHub Action to update license notices

---

ipn/ipnlocal/local.go

The CapabilityFileSharingTarget capability added by eb32847d8525e61c7435
is meant to control the ability to share with nodes not owned by the
current user, not to restrict all sharing (the coordination server is
not currently populating the capability at all)
Fixes tailscale/corp#6669

ipn/ipnlocal: fix Taildrop not returning any sharing targets

---

tka/aum.go
tka/aum_test.go
tka/state.go
tka/state_test.go
tka/tailchonk_test.go
tka/tka.go
tka/tka_test.go

It doesn't make a ton of sense for disablement to be communicated as an AUM, because
any failure in the AUM or chain mechanism will mean disablement wont function.
Instead, tracking of the disablement secrets remains inside the state machine, but
actual disablement and communication of the disablement secret is done by the caller.

tka: move disablement logic out-of-band from AUMs

---

cmd/tsconnect/src/app/ssh.tsx
cmd/tsconnect/src/lib/ssh.ts
cmd/tsconnect/src/pkg/pkg.ts

Move it to lib/ so that it can be used in both the app and the package.
Updates #5415

cmd/tsconnect: expose runSSHSession in npm package

---

ipn/ipnlocal/local.go
ipn/ipnlocal/network-lock.go
ipn/ipnserver/server.go
tka/builder_test.go
tka/scenario_test.go
tka/sync.go
tka/sync_test.go
tka/tka.go
tka/tka_test.go

Updates #5435
Based on the discussion in #5435, we can better support transactional data models
by making the underlying storage layer a parameter (which can be specialized for
the request) rather than a long-lived member of Authority.
Now that Authority is just an instantaneous snapshot of state, we can do things
like provide idempotent methods and make it cloneable, too.
/cc @crawshaw

tka: make storage a parameter rather than an Authority struct member

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/licenses.go

`tailscale licenses` will direct users to https://tailscale.com/licenses/tailscale for dependencies and licenses.
I'm not currently adding license information to tailscaled, since I believe we pretty much always distribute them together, and the link above covers the dependencies for both binaries.

cmd/tailscale: add licenses subcommand

---

.github/workflows/go-licenses.yml

also set git committer, which is apparently what this action uses for signoff rather than git author.  Remove branch-suffix, which isn't proving useful, and add installation_id, which isn't technically necessary in the tailscale/tailscale repo, but makes this consistent with the workflows in other repos.

.github/actions: add signoff to go-licenses commits

---

util/deephash/deephash.go
util/deephash/deephash_test.go

Every implementation of typeHasherFunc always returns true,
which implies that the slow path is no longer executed.
Delete it.
`h.hashValueWithType(v, ti, ...)` is deleted as it is equivalent to:
ti.hasher()(h, v)
`h.hashValue(v, ...)` is deleted as it is equivalent to:
ti := getTypeInfo(v.Type())
ti.hasher()(h, v)

util/deephash: delete slow path

---

hostinfo/hostinfo.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go

So next time something like #5340 happens we can identify all affected
nodes and have the control plane send them health warnings.

tailcfg: add Hostinfo.GoVersion

---

util/deephash/deephash.go
util/deephash/deephash_test.go

Rather than separate functions to hash each kind,
just rely on the fact that these are direct memory hashable,
thus simplifying the code.

util/deephash: rely on direct memory hashing for primitive kinds

---

util/deephash/debug.go

When built with "deephash_debug", print the set of HashXXX methods.
Example usage:
$ go test -run=GetTypeHasher/string_slice -tags=deephash_debug
U64(2)+U64(3)+S("foo")+U64(3)+S("bar")+FIN

util/deephash: add debug printer

---

util/deephash/deephash.go
util/deephash/deephash_test.go
util/deephash/pointer.go
util/deephash/pointer_norace.go
util/deephash/pointer_race.go

Use of reflect.Value.SetXXX panics if the provided argument was
obtained from an unexported struct field.
Instead, pass an unsafe.Pointer around and convert to a
reflect.Value when necessary (i.e., for maps and interfaces).
Converting from unsafe.Pointer to reflect.Value guarantees that
none of the read-only bits will be populated.
When running in race mode, we attach type information to the pointer
so that we can type check every pointer operation.
This also type-checks that direct memory hashing is within
the valid range of a struct value.
We add test cases that previously caused deephash to panic,
but now pass.
Performance:
Hash              14.1µs ± 1%    14.1µs ± 1%    ~     (p=0.590 n=10+9)
HashPacketFilter  2.53µs ± 2%    2.44µs …

util/deephash: use unsafe.Pointer instead of reflect.Value

---

util/deephash/deephash.go
util/deephash/deephash_test.go

This helps pprof better identify which Go kinds take the most time
since the kind is always in the function name.
There is a minor adjustment where we hash the length of the map
to be more on the cautious side.

util/deephash: move map logic to separate function

---

util/deephash/deephash.go
util/deephash/deephash_test.go

The entry logic of Hash has extra complexity to make sure
we always have an addressable value on hand.
If not, we heap allocate the input.
For this reason we document that there are performance benefits
to always providing a pointer.
Rather than documenting this, just enforce it through generics.
Also, delete the unused HasherForType function.
It's an interesting use of generics, but not well tested.
We can resurrect it from code history if there's a need for it.

util/deephash: require pointer in API

---

util/deephash/deephash.go
util/deephash/deephash_test.go

Add a new lookupTypeHasher function that is just a cached front-end
around the makeTypeHasher function.
We do not need to worry about the recursive type cycle issue that
made getTypeInfo more complicated since makeTypeHasher
is not directly recursive. All calls to itself happen lazily
through a sync.Once upon first use.

util/deephash: remove getTypeInfo

---

chirp/chirp.go
chirp/chirp_test.go

Prior to this change, if BIRD stops responding wgengine.watchdogEngine
will crash tailscaled.
This happens because in wgengine.userspaceEngine, we end up blocking
forever trying to write a request to or read a response from BIRD with
wgLock held, and then future watchdog'd calls will block on acquiring
that mutex until the watchdog kills the process. With the timeout, we at
least get the chance to print an error message and decide whether we
want to crash or not.
Updates tailscale/coral#72

chirp: add a 10s timeout when communicating with BIRD

---

wgengine/watchdog.go
wgengine/watchdog_test.go

In addition to printing goroutine stacks, explicitly track all in-flight
operations and print them when the watchdog triggers (along with the
time they were started at). This should make debugging watchdog failures
easier, since we can look at the longest-running operation(s) first.

wgengine: print in-flight operations on watchdog trigger

---

util/cstruct/cstruct.go
util/cstruct/cstruct_example_test.go
util/cstruct/cstruct_test.go

I was working on my "dump iptables rules using only syscalls" branch and
had a bunch of C structure decoding to do. Rather than manually
calculating the padding or using unsafe trickery to actually cast
variable-length structures to Go types, I'd rather use a helper package
that deals with padding for me.
Padding rules were taken from the following article:
http://www.catb.org/esr/structure-packing/

util/cstruct: add package for decoding padded C structures

---

ipn/ipnstate/ipnstate.go

As I close in on opening the PR for #697 it would be nice for non-illumos machines to give their illumos peers a nicer emoji instead of the default alien.
I think the Sun is fitting for SunOS operating systems.
It looks prettier in my browser when running the status web view than it does in the PR.

cmd/tailscale: add emoji for illumos in status subcommand

---

types/logger/rusage_syscall.go

This will be helpful for illumos (#697) and should be safe
everywhere else.

logger: migrate rusage syscall use to x/sys/unix

---

wgengine/wgint/wgint.go
wgengine/wgint/wgint_test.go

wgengine/wgint: add shady temporary package to get at wireguard internals

---

net/dns/manager_windows.go

Somehow I accidentally set the wrong registry value here.
It should be DisableDynamicUpdate=1 and not EnableDNSUpdate=0.
This is a regression from 545639e.

net/dns: [win] fix regression in disableDynamicUpdate

---

wgengine/pendopen.go
wgengine/userspace.go
wgengine/watchdog_test.go

Avoid contention from fetching status for all peers, and instead fetch
status for a single peer.
Updates tailscale/coral#72

wgengine: remove all peer status from open timeout diagnostics

---

.github/workflows/cross-darwin.yml
.github/workflows/cross-freebsd.yml
.github/workflows/cross-openbsd.yml
.github/workflows/cross-wasm.yml
.github/workflows/cross-windows.yml
.github/workflows/depaware.yml
.github/workflows/go_generate.yml
.github/workflows/license.yml
.github/workflows/linux-race.yml
.github/workflows/linux.yml
.github/workflows/linux32.yml
.github/workflows/static-analysis.yml
.github/workflows/vm.yml
.github/workflows/windows.yml

The next time we update the toolchain, all of the CI
Actions will automatically use it when go.mod is updated.

CI: make all workflows get Go version from go.mod

---

logtail/logtail.go

We may be backing off due to rate-limiting.
Generating more logs is counter-productive.

logtail: do not log when backing off

---

cmd/gitops-pusher/gitops-pusher.go

This makes a "modified externally" error turn into a "modified externally" warning. It means CI won't fail if someone does something manually in the admin console.

cmd/gitops-pusher: be less paranoid about external modifications

---

cmd/tsconnect/src/lib/ssh.ts
cmd/tsconnect/src/types/wasm_js.d.ts
cmd/tsconnect/wasm/wasm_js.go

We were just outputting them to the terminal, but that's hard to debug
because we immediately tear down the terminal when getting an error.

cmd/tsconnect: output errors to the JS console too

---

net/dns/config.go
net/dns/manager.go
net/dns/manager_test.go
tailcfg/tailcfg.go

If ExtraRecords (Hosts) are specified without a corresponding split
DNS route and global DNS is specified, then program the host OS DNS to
use 100.100.100.100 so it can blend in those ExtraRecords.
Updates #1543

net/dns: set OS DNS to 100.100.100.100 for route-less ExtraRecords [cap 41]

---

util/uniq/slice.go
util/uniq/slice_test.go
wgengine/magicsock/magicsock.go

This takes 75% less time per operation per some benchmarks on my mac.

util/uniq: use generics instead of reflect

---

util/uniq/slice.go
util/uniq/slice_test.go

Follow-up to #5491. This was used in control... oops!

util/uniq: add ModifySliceFunc

---

ipn/ipnlocal/network-lock.go
tka/sig.go
tka/sig_test.go
tka/tka.go

This will be needed to support preauth-keys with network lock in the future, so getting the core mechanics out of the way now.

tka: implement credential signatures (key material delegation)

---

cmd/tsconnect/src/lib/ssh.ts

Remove test prefix added to validate the error code from 27f36f77c364562bc1ca660c241291e23606e54d.

cmd/tsconnect: remove debugging code

---

cmd/nginx-auth/nginx-auth.go

With MagicDNS GA, we are giving every tailnet a tailnet-<hex>.ts.net name.
We will only parse out if legacy domains include beta.tailscale.net; otherwise,
set tailnet to the full domain format going forward.

cmd/nginx-auth/nginx-auth: update auth to allow for new domains

---

cmd/gitops-pusher/gitops-pusher.go

Apparently the validate route doesn't check content-types or handle
hujson with comments correctly. This patch makes gitops-pusher convert
the hujson to normal json.

cmd/gitops-pusher: standardize hujson before posting to validate

---

cmd/tailscale/cli/cert.go

The help description for --key-file incorrectly mentioned "cert file", talk about "key file" instead.

cli/cert: Fix help message for --key-file

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go
ipn/ipn_clone.go
ipn/ipnlocal/local.go
ipn/prefs.go
ipn/prefs_test.go

cmd/tailscale/cli: add backwards compatibility 'up' processing for legacy client

---

net/dnscache/dnscache.go
net/dnscache/dnscache_test.go

Removes usage of net.IP and net.IPAddr where possible from net/dnscache.
Fixes #5282
Signed-off-by: Kris Brandow <kris.brandow@gmail.com>

net/dnscache: use net/netip

---

tsnet/tsnet.go
tsnet/tsnet_test.go

Allow callers to verify that a net.Listener is a tsnet.listener by type asserting against this Server method, as well as providing access to the underlying Server.
This is initially being added to support the caddy integration in caddyserver/caddy#5002.

tsnet: add Server method to listener

---

ipn/ipnlocal/local.go
ipn/ipnserver/server.go
net/dnsfallback/dnsfallback.go
net/dnsfallback/dnsfallback_test.go

This is especially helpful as we launch newer DERPs over time, and older
clients have progressively out-of-date static DERP maps baked in. After
this, as long as the client has successfully connected once, it'll cache
the most recent DERP map it knows about.
Resolves an in-code comment from @bradfitz

net/dnsfallback: cache most recent DERP map on disk

---

wgengine/magicsock/magicsock.go

1f959edeb0c6ad3a82fcdaa4ca65a02571493cc6 introduced a regression for JS
where the initial bind no longer occurred at all for JS.
The condition is moved deeper in the call tree to avoid proliferation of
higher level conditions.
Updates #5537

wgengine/magicsock: fix regression in initial bind for js

---

cmd/tsconnect/README.md
cmd/tsconnect/build-pkg.go
cmd/tsconnect/common.go
cmd/tsconnect/dev-pkg.go
cmd/tsconnect/tsconnect.go

Allows imports of the NPM package added by 1a093ef4822b973ec86d481924690349eddba5cb
to be replaced with import("http://localhost:9090/pkg/pkg.js"), so that
changes can be made in parallel to both the module and code that uses
it (without any need for NPM publishing or even building of the package).
Updates #5415

cmd/tsconnect: add dev-pkg command for two-sided development

---

wgengine/magicsock/debughttp.go

Fixes an panic in `(*magicsock.Conn).ServeHTTPDebug` when the `recentPongs` ring buffer for an endpoint wraps around.

wgengine/magicsock: fix panic in http debug server

---

tailcfg/tailcfg.go

gofmt in 1.19 is now opinionated about structured text formatting in comments. It did not like our style and kept fighting us whenever we changed these lines. Give up the fight and be a bulleted list for it.
See:
* https://go.dev/doc/go1.19#go-doc and
* https://go.dev/doc/comment
Updates #4872

tailcfg: reformat CurrentCapabilityVersion to be a bulleted list

---

tailcfg/tailcfg_test.go

Fix broken build from 255c0472fb0f5c13c40b90eb9da87337da312e63
"Oh, that's safe to commit because most tests are passing and it's just a comment change!", I thought, forgetting I'd added a test that parses its comments.

tailcfg: fix broken test from comment change

---

cmd/tsconnect/package.json
cmd/tsconnect/src/app/ssh.tsx
cmd/tsconnect/src/lib/ssh.ts
cmd/tsconnect/wasm/wasm_js.go
cmd/tsconnect/yarn.lock

Allows other work to be unblocked while xtermjs/xterm.js#4069 is worked
through.
To enable testing the popup window handling, the standalone app allows
opening of SSH sessions in new windows by holding down the alt key
while pressing the SSH button.
Also includes a fix for #5567 (handling of resizes before the SSH session
is opened).

cmd/tsconnect: temporarily switch to xterm.js fork that handles popup windows

---

net/dns/manager_test.go
net/dns/resolver/forwarder_test.go
types/dnstype/dnstype.go

Clarify & verify that some DoH URLs can be sent over tailcfg in some limited cases.
Updates #2452

net/dns, types/dnstypes: update some comments, tests for DoH

---

cmd/tsconnect/package.json
cmd/tsconnect/yarn.lock

xtermjs/xterm.js#4069 was merged and published (in 5.0.0-beta.58), no need for the fork added by 01e6565e8a0193ec940a8eca9129dadb2c05e29d.

cmd/tsconnect: switch back to public version of xterm npm package

---

cmd/tsconnect/package.json
cmd/tsconnect/src/app/app.tsx
cmd/tsconnect/src/lib/ssh.ts
cmd/tsconnect/yarn.lock

More user friendly, and as a side-effect we handle SSH check mode better, since the URL that's output is now clickable.
Fixes #5247

cmd/tsconnect: enable web links addon in the terminal

---

ipn/localapi/localapi.go
util/mak/mak.go
util/mak/mak_test.go

And put the rationale in the name too to save the callers the need for a comment.

util/mak: deprecate NonNil, add type-safe NonNilSliceForJSON, NonNilMapForJSON

---

net/dns/publicdns/publicdns.go
net/dns/publicdns/publicdns_test.go

The plan has changed. Doing query parameters rather than path + heades. NextDNS added support for query parameters.
Updates #2452

net/dns/publicdns: also support NextDNS DoH query parameters

---

cmd/tailscale/cli/licenses.go
cmd/tailscale/cli/web.go
cmd/tailscale/cli/web.html

The `tailscale web` UI is the primary interface for Synology and Home Assistant users (and perhaps others), so is the logical place to put our open source license notices.  I don't love adding things to what is currently a very minimal UI, but I'm not sure of a better option.

cmd/tailscale: add licenses link to web UI

---

cmd/tsconnect/src/lib/ssh.ts

The default WebLinksAddon handler uses `window.open()`, but that gets blocked by the popup blocker when the event being handled is another window. We instead need to invoke `open()` on the window that the event was triggered in.

cmd/tsconnect: fix xterm.js link opening not working when rendered into another window

---

cmd/tsconnect/src/types/wasm_js.d.ts
cmd/tsconnect/wasm/wasm_js.go

The auto-generated hostname is nice as a default, but there are cases where the client has a more specific name that it can generate.

cmd/tsconnect: allow hostname to be specified

---

net/netns/netns_linux.go
wgengine/magicsock/magicsock_linux.go

wgengine/magicsock: don't use BPF receive when SO_MARK doesn't work.

---

cmd/tsconnect/src/lib/ssh.ts

Allows clients to use a custom theme and other xterm.js customization options.
Fixes #5610

cmd/tsconnect: allow xterm.js terminal options to be passed in

---

wgengine/router/router_linux.go
wgengine/router/router_linux_test.go

Linux only.
This change masks the bitspace used when setting and querying the fwmark on packets. This allows tailscaled to play nicer with other networking software on the host, assuming the other networking software is also using fwmarks & a different mask.
IPTables / mark module has always supported masks (kversion 2.6 or something ridiculous), so this is safe on the netfilter front.
However on the `ip` utility front, busybox only gained support for parsing + setting masks in 1.33.0, so we make sure we arent such a version before we add the "/<mask>" syntax to an ip rule command. The 'OG' `ip` command from iproute2 has had support since 2016. In any case thats not hugely important, as in practice we only use the `ip` command if `TS_DEBUG_USE_IP_COMMAND=` is set.

wgengine: set fwmark masks in netfilter & ip rules

---

cmd/tailscaled/tailscaled.go
control/controlclient/direct.go
envknob/envknob.go
hostinfo/hostinfo.go
ipn/localapi/localapi.go
logpolicy/logpolicy.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go

As noted in #5617, our documented method of blocking log.tailscale.io DNS no longer works due to bootstrap DNS.
Instead, provide an explicit flag (--no-logs-no-support) and/or env variable (TS_NO_LOGS_NO_SUPPORT=true) to explicitly disable logcatcher uploads. It also sets a bit on Hostinfo to say that the node is in that mode so we can end any support tickets from such nodes more quickly.
This does not yet provide an easy mechanism for users on some platforms (such as Windows, macOS, Synology) to set flags/env. On Linux you'd used /etc/default/tailscaled typically. Making it easier to set flags for other platforms is tracked in #5114.
Fixes #5617
Fixes tailscale/corp#1475

cmd/tailscaled, tailcfg, hostinfo: add flag to disable logging + support

---

logpolicy/logpolicy.go

The version.CmdName implementation is buggy such that it does not correctly identify the binary name if it embeds other go binaries. For now, add a NewWithConfigPath API that allows the caller to explicitly specify this information.

logpolicy: add NewWithConfigPath

---

net/dns/resolver/forwarder.go

Timeout is now enforced elsewhere, see discussion in https://github.com/tailscale/tailscale/pull/4408#discussion_r970092333.

net/dns/resolver: remove unused responseTimeout constant

---

portlist/clean.go
portlist/clean_test.go

Some process names are not only separated by NUL and contains spaces. This PR will check for these special cases and extract the base process name.
This fixes #3781 and other similar cases:
`sshd_config [listener] 1 of 10-100 startups` -> `sshd_config`
`nginx worker` -> `nginx`
Not sure if this approach might have bad performance impact, and that it might be better to tackle this in the Linux specific code where we split by `\x00`.

portlist: normalise space delimited process names

---

cmd/derper/websocket.go
control/controlhttp/server.go

The data that we send over WebSockets is encrypted and thus not compressible. Additionally, Safari has a broken implementation of compression (see nhooyr/websocket#218) that makes enabling it actively harmful.
Fixes tailscale/corp#6943

cmd/derper, control/controlhttp: disable WebSocket compression

---

ipn/ipnlocal/peerapi.go
ipn/localapi/cert.go
ipn/localapi/cert_test.go

The GitHub CodeQL scanner flagged the localapi's cert domain usage as a problem because user input in the URL made it to disk stat checks.
The domain is validated against the ipnstate.Status later, and only authenticated root/configured users can hit this, but add some paranoia anyway.

ipn/{ipnlocal,localapi}: use strs.CutPrefix, add more domain validation

---

docs/k8s/README.md
docs/k8s/sidecar.yaml

This changes sidecar.yaml so it uses the same value for the `key` stanza as the README.md and run.sh
Fixes: https://github.com/tailscale/tailscale/issues/5653
Signed-off-by: Tyler Lee <tyler.lee@radius.ai>

Updated value for the kubernetes secret used by the sidecar container

---

Dockerfile

Tailscale @4a82b31 does not build in the container image due to using golang:1.18 image

Update Dockerfile to use golang:1.19-alpine

---

cmd/tailscale/cli/debug.go
control/controlclient/noise.go
control/controlhttp/client.go
control/controlhttp/client_js.go
control/controlhttp/constants.go
control/controlhttp/http_test.go

This turns 'dialParams' into something more like net.Dialer, where configuration fields are public on the struct.
Split out of #5648
Change-Id: I0c56fd151dc5489c3c94fb40d18fd639e06473bc

control/controlhttp: move Dial options into options struct

---

version_test.go

So things like #5660 don't happen in the future.

Dockerfile: add test that build-env Alpine version matches go.mod

---

cmd/tailscaled/tailscaled.go
cmd/tailscaled/tailscaled_windows.go
envknob/envknob.go
envknob/envknob_windows.go
ipn/ipnserver/server.go

ipnserver previously had support for a Windows-only environment variable mechanism that further only worked when Windows was running as a service, not from a console.
But we want it to work from tailscaed too, and we want it to work on macOS and Synology. So move it to envknob, now that envknob can change values at runtime post-init.
A future change will wire this up for more platforms, and do something more for CLI flags like --port, which the bug was originally about.
Updates #5114

envknob: generalize Windows tailscaled-env.txt support

---

tailcfg/tailcfg.go
wgengine/magicsock/debugknobs.go
wgengine/magicsock/debugknobs_stubs.go
wgengine/magicsock/magicsock.go

My notes from uhhhh six weeks ago aren't as clear as I remembered them being so this could be totally off base.
Change-Id: Idc9a72748e74145b068d67e6dd4a4ffe3932efd0

wgengine/magicsock: add client flag and envknob to disable heartbeat

---

net/netns/netns_android.go

Build fails on Android:
`../../../../go/pkg/mod/tailscale.com@v1.1.1-0.20220916223019-65c24b6334e9/wgengine/magicsock/magicsock_linux.go:133:12: undefined: netns.UseSocketMark`

net/netns: implement UseSocketMark for Android.

---

.github/workflows/cross-android.yml

This would've caught the regression from 7c49db02a before it was submitted so 42f1d92ae020c wouldn't have been necessary to fix it.
Updates #4482

.github/workflows: add cross-android

---

ipn/ipnlocal/c2n.go
ipn/ipnlocal/ssh.go
ipn/ipnlocal/ssh_stub.go
ipn/ipnlocal/ssh_test.go
tailcfg/c2ntypes.go

For control to fetch a list of Tailscale SSH username candidates to filter against the Tailnet's SSH policy to present some valid candidates to a user.
Updates #3802
Updates tailscale/corp#7007

ipn/ipnlocal: add c2n method to get SSH username candidates

---

ipn/ipnlocal/local.go
tailcfg/tailcfg.go

tailcfg: mark CapabilityFileSharingTarget as inter-node

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/down.go
cmd/tailscale/cli/risks.go
cmd/tailscale/cli/up.go

The check was happening too early and in the case of error would wait 5 s and then error out. This makes it so that it does validations before the SSH check.

cmd/tailscale/cli: [up] move lose-ssh check after other validations

---

cmd/tsconnect/src/lib/ssh.ts
cmd/tsconnect/src/types/wasm_js.d.ts
cmd/tsconnect/wasm/wasm_js.go

5 seconds may not be enough if we're still loading the derp map and connecting to a slow machine.
Updates #5693

cmd/tsconnect: allow SSH connection timeout to be overridden

---

cmd/tailscale/cli/up.go

cmd/tailscale: remove leftover debug prints from earlier commit

---

cmd/tailscale/cli/configure-host.go

d5e7e309 changed the `hostinfo.GetVersion` from distro and distro version
to UTS Name Release and moved distribution information under
`hostinfo.Distro*`.
`tailscale configure-host` command implementation for Synology DSM
environments relies on the old semantics of this string for matching DSM
Major version so it's been broken for a few days.
Pull in `hostinfo` and prefix match `hostinfo.DistroVersion` to match
DSM major version.

tailscale: Fix configure-host command for Synology

---

cmd/tailscale/cli/netcheck.go
net/netcheck/netcheck.go
net/netcheck/netcheck_test.go
tstest/integration/integration_test.go
tstest/integration/testcontrol/testcontrol.go

This doesn't change any behaviour for now, other than maybe running a full netcheck more often. The intent is to start gathering data on captive portals, and additionally, seeing this in the 'tailscale netcheck' command should provide a bit of additional information to users.
Updates #1634

net/netcheck: add check for captive portal

---

cmd/tsconnect/src/app/ssh.tsx
cmd/tsconnect/src/lib/ssh.ts

We were just logging them to the console, which is useful for debugging, but we may want to show them in the UI too.
Updates tailscale/corp#6939

cmd/tsconnect: add error callback for SSH sessions

---

docs/k8s/proxy.yaml
docs/k8s/subnet.yaml
docs/k8s/userspace-sidecar.yaml

I added `TS` prefix to auth key based on [READ.md](https://github.com/tailscale/tailscale/blob/main/docs/k8s/README.md)
The documentation describes the auth key as `TS_AUTH_KEY`, but the manifest uses `AUTH_KEY`, which did not work properly.

docs/k8s: add TS prefix

---

docs/k8s/run.sh

Allows for specifying a custom control socket in the docker entrypoint, which is useful for sharing it with sidecar containers

docker: add ability to use a custom control socket

---

tsweb/tsweb.go
tsweb/tsweb_test.go

Static resource handlers will generate lots of 304s, which are effectively successful responses.

tsweb: consider 304s as successful for quiet logging

---

cmd/speedtest/speedtest.go
net/speedtest/speedtest.go
net/speedtest/speedtest_server.go
net/speedtest/speedtest_test.go

- removed some in-flow time calls
- increase buffer size to 2MB to overcome syscall cost
- move relative time computation from record to report time

net/speedtest: retune to meet iperf on localhost in a VM

---

control/controlclient/direct.go
control/controlclient/noise.go

In prep for a future change that would've been very copy/paste-y.
And because the set-dns call doesn't currently use a context, so timeouts/cancelations are plumbed.

control/controlclient: add a noiseClient.post helper method

---

control/controlclient/auto.go
control/controlclient/direct.go
tailcfg/tailcfg.go

At some point we started restarting map polls on health change, but we don't remember why. Maybe it was a desperate workaround for something. I'm not sure it ever worked.
Rather than have a haunted graveyard, remove it.
In its place, though, and somewhat as a safety backup, send those updates over the HTTP/2 noise channel if we have one open. Then if there was a reason that a map poll restart would help we could do it server-side. But mostly we can gather error stats and show machine-level health info for debugging.

control/controlclient: stop restarting map polls on health change

---

control/controlclient/direct.go

SetDNS calls were broken by 6d04184325 the other day. Unreleased.
Caught by tests in another repo.

control/controlclient: fix recent set-dns regression

---

control/controlhttp/client_js.go

Control may not be bound to (just) localhost when sharing dev servers, allow the Wasm client to connect to it in that case too.

control/controlhttp: use custom port for non-localhost JS noise client connections

---

ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
tailcfg/tka.go

Updates https://github.com/tailscale/corp/pull/7024
Makes TKA RPCs use `NodeKey` to identify the client, as we discussed. TKA isnt used anywhere yet so its safe to change things without worrying about backwards-compat.

ipn/ipnlocal,tailcfg: Identify client using NodeKey in tka RPCs

---

util/deephash/deephash.go
util/deephash/deephash_test.go

This method can be used to obtain the hex-formatted deephash.Sum instance without allocations.

util/deephash: add AppendTo method

---

net/dns/osconfig.go
net/dns/osconfig_test.go

Fixes tailscale/tailscale#5669

net/dns: format OSConfig correctly with no pointers

---

tstime/tstime.go
tstime/tstime_test.go

More expressive than time.ParseDuration, also accepting d (days) and w (weeks) literals.

tstime: add ParseDuration helper function

---

wgengine/router/router_linux.go

Updates: #5588
Context: https://github.com/tailscale/tailscale/pull/5588#issuecomment-1260655929
It seems that if the interface at index 1 is down, the rule is not installed and hence the platform will not be detected as an mwan3 installation even though we need to.
The rule priorities correspond to interface index minus 2000, so we increase the range we detect up to 2004 in the hope that at least one of the interfaces 1-4 will be up.

wgengine/router: Increase range of rule priorities when detecting mwan3

---

ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
tka/tailchonk.go
tka/tailchonk_test.go

This implement the client-side of TKA sync. I've opted to implement mocks for testing on this end, I'll do the usual controlclient tests on the PR for control.

ipn/ipnlocal, tka: Implement TKA synchronization with the control plane

---

wgengine/userspace.go

Updates tailscale/coral#82
Change-Id: I398d75f7e178ff7c531ca09899c82cf974fc30c9

wgengine: log subnet router decision at v1 if we have a BIRD client

---

net/dns/publicdns/publicdns.go
net/dns/publicdns/publicdns_test.go

I brain-o'ed the math earlier. The NextDNS prefix is /32 (actually /33, but will guarantee last bit is 0), so we have 128-32 = 96 bits (12 bytes) of config/profile ID that we can extract. NextDNS doesn't currently use all those, but might.
Updates #2452

net/dns/publicdns: permit more NextDNS profile bits in its IPv6 suffix

---

logpolicy/logpolicy.go

Callers of LogHost often jump through hoops to undo the loss of information dropped by LogHost (e.g., the HTTP scheme).

logpolicy: directly expose the logtail server URL

---

cmd/tailscaled/tailscaled.go
cmd/tailscaled/tailscaled_windows.go
cmd/tsconnect/wasm/wasm_js.go
ipn/ipnlocal/local.go
net/dns/manager.go
tsnet/tsnet.go
wgengine/userspace.go

Most visible when using tsnet.Server, but could have resulted in dropped messages in a few other places too.
Fixes #5743

all: consistently initialize Logf when creating tsdial.Dialers

---

client/tailscale/localclient.go
cmd/tailscale/cli/debug.go
ipn/backend.go
ipn/ipnlocal/c2n.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go
ipn/store.go
tailcfg/tailcfg.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_linux.go

And start of mechanism for CLI or support to enable debug logging of a component for a fixed amount of time.
Updates #1548

wgengine/magicsock: make debug-level stuff not logged by default

---

cmd/pgproxy/README.md
cmd/pgproxy/pgproxy.go

This is:
- `mv` from our non-free repo into this one
- Add license headers
- Remove a couple TODOs for possible additional features that we ended up not needing
- Remove references to TS_LOGIN=1, which tsnet no longer supports.

cmd/pgproxy: open-source our postgres TLS-enforcing proxy.

---

net/tunstats/stats.go
net/tunstats/stats_test.go

High-level API:
type Statistics struct { ... }
type Counts struct { TxPackets, TxBytes, RxPackets, RxBytes uint64 }
func (*Statistics) UpdateTx([]byte)
func (*Statistics) UpdateRx([]byte)
func (*Statistics) Extract() map[flowtrack.Tuple]Counts
The API accepts a []byte instead of a packet.Parsed so that a future implementation can directly hash the address and port bytes, which are contiguous in most IP packets.
This will be useful for a custom concurrent-safe hashmap implementation.

net/tunstats: new package to track per-connection counters

---

cmd/tsconnect/package.json
cmd/tsconnect/yarn.lock

xterm 5.0 was released a few weeks ago, and it picks up xtermjs/xterm.js#4069, which was the main reason why we were on a 5.0 beta.

cmd/tsconnect: switch to non-beta versions of xterm and related packages

---

go.mod
go.sum
ssh/tailssh/tailssh.go

go.mod, ssh/tailssh: fix ImplictAuthMethod typo

---

tsweb/tsweb.go
tsweb/tsweb_test.go

This is needed for the changes in tailscale/corp#7296

tsweb: allow HTTPError to unwrap errors

---

ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
tka/state.go

* `tka.State.staticValidateCheckpoint` could call methods on a contained key prior to calling StaticValidate on that key
* Remove broken backoff / RPC retry logic from tka methods in ipn/ipnlocal, to be fixed at a later time
* Deduplicate `LocalBackend.sendAUMsLocked` as it does the same thing as `tkaDoSyncSend`
* Fix `ipn.LocalBackend.NetworkLockModify()` which would attempt to take `b.mu` twice and deadlock
* Add methods on ipnlocal.LocalBackend to be used in integration tests

ipn/ipnlocal,tka: Fix bugs found by integration testing

---

ipn/ipnlocal/network-lock.go

```
==================
WARNING: DATA RACE
Write at 0x00c000abf358 by goroutine 742:
tailscale.com/ipn/ipnlocal.(*LocalBackend).tkaBootstrapFromGenesisLocked()
/home/ubuntu/go/pkg/mod/tailscale.com@v1.1.1-0.20221005181234-8602061f32de/ipn/ipnlocal/network-lock.go:265 +0x480
tailscale.com/ipn/ipnlocal.(*LocalBackend).tkaSyncIfNeededLocked()
/home/ubuntu/go/pkg/mod/tailscale.com@v1.1.1-0.20221005181234-8602061f32de/ipn/ipnlocal/network-lock.go:115 +0x358
tailscale.com/ipn/ipnlocal.(*LocalBackend).setClientStatus()
/home/ubuntu/go/pkg/mod/tailscale.com@v1.1.1-0.20221005181234-8602061f32de/ipn/ipnlocal/local.go:778 +0x864
tailscale.com/ipn/ipnlocal.(*LocalBackend).setClientStatus-fm()
<autogenerated>:1 +0xa4
tailscale.com/control/controlclient.(*Auto).sendStatus() …
```

ipn/ipnlocal: fix data race from missed locking in NetworkLockStatus

---

logtail/logtail.go

Upstream optimizations to the Go time package will make unmarshaling of time.Time 3-6x faster. See:
* https://go.dev/cl/425116
* https://go.dev/cl/425197
* https://go.dev/cl/429862
The last optimization avoids a []byte -> string allocation if the timestamp string less than than 32B.
Unfortunately, the presence of a timezone breaks that optimization. Drop recording of timezone as this is non-essential information.
Most of the performance gains is upon unmarshal,
but there is also a slight performance benefit to
not marshaling the timezone as well.

logtail: always record timestamps in UTC

---

net/flowtrack/flowtrack.go

By convention, JSON serialization uses camelCase.
Specify such names on the Tuple type.

net/flowtrack: add json tags to Tuple

---

net/tstun/wrap.go
net/tstun/wrap_test.go

Rename StatisticsEnable as SetStatisticsEnabled to be consistent with other similarly named methods.
Rename StatisticsExtract as ExtractStatistics to follow the convention where methods start with a verb.
It was originally named with Statistics as a prefix so that statistics related methods would sort well in godoc, but that property no longer holds.

net/tstun: rename statististics method

---

cmd/tsconnect/src/lib/ssh.ts

The window may not end up getting unloaded (if other `beforeunload` handlers prevent the event), thus we should only close the SSH session if it's truly getting unloaded.
Updates tailscale/corp#7304

cmd/tsconnect: close the SSH session an unload event instead of beforeunload

---

control/controlclient/map.go
types/netmap/netmap.go
wgengine/wgcfg/config.go
wgengine/wgcfg/nmcfg/nmcfg.go
wgengine/wgcfg/wgcfg_clone.go

The node and domain audit log IDs are provided in the map response, but are ultimately going to be used in wgengine since that's the layer that manages the tstun.Wrapper.
Do the plumbing work to get this field passed down the stack.

wgengine/wgcfg: plumb down audit log IDs

---

ssh/tailssh/tailssh.go

This was assumed to be the fix for mosh not working, however turns out all we really needed was the duplicate fd also introduced in the same commit (af412e8874e94dc3ac57c37c3ec5e0606aa08fbb).
Fixes #5103

ssh/tailssh: do not send EOT on session disconnection

---

ssh/tailssh/context.go
ssh/tailssh/tailssh.go

This was preventing tailscaled from shutting down properly if there were active sessions in certain states (e.g. waiting in check mode).

ssh/tailssh: close sshContext on context cancellation

---

cmd/ssh-auth-none-demo/ssh-auth-none-demo.go

For SSH client authors to fix their clients without setting up Tailscale stuff.

cmd/ssh-auth-none-demo: add demo SSH server that acts like Tailscale SSH

---

tsweb/tsweb.go
tsweb/tsweb_test.go

This removes the ~9 allocs added by #5869, while still keeping struct fields sorted (the previous commit's tests still pass). And add a test to lock it in that this shouldn't allocate.
Updates #5778

tsweb: remove allocs introduced by earlier change

---

cmd/tailscaled/install_darwin.go

When Tailscale is installed via Homebrew, `/usr/local/bin/tailscaled` is a symlink to the actual binary.
Now when `tailscaled install-system-daemon` runs, it will not attempt to overwrite that symlink if it already points to the tailscaled binary. However, if executed binary and the link target differ, the path will be overwritten - this can happen when a user decides to replace Homebrew-installed tailscaled with a one compiled from source code.
Fixes #5353

cmd/tailscaled: handle tailscaled symlink on macOS

---

cmd/ssh-auth-none-demo/ssh-auth-none-demo.go
go.mod
go.sum
ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

If the username includes a suffix of +password, then we accept
password auth and just let them in like it were no auth.
This exists purely for SSH clients that get confused by seeing success
to their initial auth type "none".

ssh/tailssh: add password-forcing workaround for buggy SSH clients

---

net/tstun/wrap.go
wgengine/netlog/logger.go
wgengine/netlog/logger_test.go

The Logger type managers a logtail.Logger for extracting statistics from a tstun.Wrapper.
So long as Shutdown is called, it ensures that logtail and statistic gathering resources are properly cleared up.

wgengine/netlog: new package for traffic flow logging

---

wgengine/wgengine.go

wgengine: fix typo in Engine.PeerForIP

---

wgengine/netlog/logger.go
wgengine/netlog/logger_test.go
wgengine/userspace.go

This sets up Logger to handle statistics at the magicsock layer, where we can correlate traffic between a particular tailscale IP address and any number of physical endpoints used to contact the node that hosts that tailscale address.
We also export Message and TupleCounts to better document the JSON format that is being sent to the logging infrastructure.

wgengine/netlog: add support for magicsock statistics

---

wgengine/router/ifconfig_windows.go

Always set the MTU to the Tailscale default MTU. In practice we are
missing applying an MTU for IPv6 on Windows prior to this patch.
This is the simplest patch to fix the problem, the code in here needs
some more refactoring.
Fixes #5914

wgengine/router: fix MTU configuration on Windows

---

derp/derphttp/derphttp_client.go

NewNetcheckClient only initializes a subset of fields of derphttp.Client, and it's exepcted that only DialRegionTLS is called on it. We do not need to close it (as added by #5707), and it's an error to do so.
Fixes #5919

derp/derphttp: fix nil pointer dereference when closing a netcheck client

---

net/netcheck/netcheck.go

If netcheck happens before there's a derpmap.
This seems to only affect Headscale because it doesn't send a derpmap as early?

net/netcheck: fix crash in checkCaptivePortal

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_default.go
wgengine/magicsock/magicsock_linux.go
wgengine/magicsock/magicsock_unix_test.go

- At high data rates more buffer space is required in order to avoid
packet loss during any cause of delay.
- On slower machines more buffer space is required in order to avoid
packet loss while decryption & tun writing is underway.
- On higher latency network paths more buffer space is required in order
to overcome BDP.
- On Linux set with SO_*BUFFORCE to bypass net.core.{r,w}mem_max.
- 7MB is the current default maximum on macOS 12.6
- Windows test is omitted, as Windows does not support getsockopt for
these options.

wgengine/magicsock: set UDP socket buffer sizes to 7MB

---

go.mod
prober/http.go
prober/tls.go
prober/tls_test.go

TLS prober now checks validity period for all server certificates and verifies OCSP revocation status for the leaf cert.

prober: expand certificate verification logic in the TLS prober

---

control/controlclient/direct.go
ipn/ipnlocal/local.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

CAPVER 47
This change implements support for rotating the node-key signature during client registration.
Integration test for this behavior is in the corp PR (https://github.com/tailscale/corp/pull/7429).

control/controlclient,ipn/ipnlocal,tailcfg: rotate node-key signature on register

---

ipn/ipnlocal/local.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go

Running corp/ipn#TestNetworkLockE2E has a 1/300 chance of failing, and deskchecking suggests thats whats happening are two netmaps are racing each other to be processed through tkaSyncIfNeededLocked. This happens in the first place because we release b.mu during network RPCs.
To fix this, we make the tka sync logic an exclusive section, so two netmaps will need to wait for tka sync to complete serially (which is what we would want anyway, as the second run through probably wont need to sync).

ipn/ipnlocal: make tkaSyncIfNeededLocked an exclusive section

---

cmd/tsconnect/build-pkg.go
util/precompress/precompress.go

This way we can do that once (out of band, in the GitHub action), instead of increasing the time of each deploy that uses the package.
.wasm is removed from the list of automatically pre-compressed extensions, an OSS bump and small change on the corp side is needed to make use of this change.

cmd/tsconnect: pre-compress main.wasm when building the NPM package

---

derp/derp_server.go
derp/derp_server_default.go
derp/derp_server_linux.go

Periodically poll the TCP RTT metric from all open TCP connections and update a (bucketed) histogram metric.
Change-Id: I6214902196b05bf7829c9d0ea501ce0e13d984cf

derp: add TCP RTT metric on Linux

---

prober/notification.go

sendAlert will trigger the Incident Response system. sendWarning will post to Slack.

prober: add utilities to generate alerts and warnings.

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

This field seems seldom used and the documentation is wrong. It is simpler to just derive its original value dynamically when endpoint.DstToString is called.
This method is potentially used by wireguard-go,
but not in any code path is performance sensitive. All calls to it use it in conjunction with fmt.Printf, which is going to be slow anyways since it uses Go reflection.

wgengine/magicsock: remove endpoint.wgEndpoint

---

cmd/netlogfmt/main.go

This package parses a JSON stream of netlog.Message from os.Stdin and pretty prints the contents as a stream of tables.
It supports reverse lookup of tailscale IP addresses if given an API key and the tailnet that these traffic logs belong to.

cmd/netlogfmt: new package to pretty print network traffic logs

---

tsnet/example/tshello/tshello.go

Before this would silently fail if this program was running on a machine that was not already running Tailscale. This patch changes the WhoIs call to use the tsnet.Server LocalClient instead of the global tailscale LocalClient.

tsnet/examples/tshello: update example for LocalClient method

---

tka/sig.go
tka/sig_test.go
tka/tka.go

Duplicating this at each layer doesnt make any sense, and is another invariant where things could go wrong.

tka: make rotation signatures use nested keyID

---

control/controlclient/noise.go
control/controlhttp/client.go
control/controlhttp/client_common.go
control/controlhttp/client_js.go
control/controlhttp/http_test.go
control/controlhttp/server.go

Not currently used, but will allow us to usually remove a round-trip for a future feature.
Updates #5972

control/controlhttp: allow setting, getting Upgrade headers in Noise upgrade

---

.github/workflows/cross-wasm.yml

Starting with #5946 we're compressing main.wasm when building the package, but that should not show down the CI check.

.github/workflows: use fast compression for NPM package CI check

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml

Signed-off-by: Maya Kaczorowski <15946341+mayakacz@users.noreply.github.com>
Remove support@ email from issue template. Would prefer to have users fill in https://tailscale.com/contact/support as that has logged in information.

.github: update issue templates

---

net/dns/manager_linux.go
net/dns/manager_linux_test.go

The ResolvConfMode property is documented to return how systemd-resolved is currently managing /etc/resolv.conf. Include that information in the debug line, when available, to assist in debugging DNS issues.
Change-Id: I1ae3a257df1d318d0193a8c7f135c458ec45093e

net/dns: print systemd-resolved ResolvConfMode

---

prober/derp.go
prober/derp_test.go

This ensures that each DERP server is probed individually (TLS and STUN) and also manages per-region mesh probing. Actual probing code has been copied from cmd/derpprobe.

prober: add a DERP probe manager based on derpprobe

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/pathfinder.go

Sets up new file for separate silent disco goroutine, tentatively named pathfinder for now.
Updates #540

wgengine/magicsock: set up pathfinder

---

prober/prober.go
prober/prober_test.go

By default all probes with the same probe interval that have been added together will run on a synchronized schedule, which results in spiky resource usage and potential throttling by third-party systems (for example, OCSP servers used by the TLS probes).
To address this, prober can now run in "spread" mode that will introduce a random delay before the first run of each probe.

prober: optionally spread probes over time

---

Makefile

This builds and publishes the tailscale container image for dev testing.

Makefile: add publishdevimage target

---

net/netcheck/netcheck.go
tailcfg/tailcfg.go
wgengine/magicsock/magicsock.go

We had previously added this to the netcheck report in #5087 but never copied it into the NetInfo struct. Additionally, add it to log lines so it's visible to support.
Change-Id: Ib6266f7c6aeb2eb2a28922aeafd950fe1bf5627e

net/netcheck, tailcfg: track whether OS supports IPv6

---

portlist/poller.go
portlist/portlist.go
portlist/portlist_test.go

It's an internal implementation detail, and I plan to refactor it for performance (garbage) reasons anyway, so start by hiding it.
Updates #5958

portlist: unexport GetList

---

portlist/netstat.go
portlist/netstat_exec.go
portlist/netstat_test.go
portlist/poller.go
portlist/portlist.go
portlist/portlist_ios.go
portlist/portlist_js.go
portlist/portlist_linux.go
portlist/portlist_linux_test.go
portlist/portlist_macos.go
portlist/portlist_other.go
portlist/portlist_test.go
portlist/portlist_windows.go

In prep for reducing garbage, being able to reuse memory.  So far this doesn't actually reuse much. This is just changing signatures around.
But some improvement in any case:
bradfitz@tsdev:~/src/tailscale.com$ ~/go/bin/benchstat before after
name       old time/op    new time/op    delta
GetList-8    11.8ms ± 9%     9.9ms ± 3%  -15.98%  (p=0.000 n=10+10)
name       old alloc/op   new alloc/op   delta
GetList-8    99.5kB ± 2%    91.9kB ± 0%   -7.62%  (p=0.000 n=9+9)
name       old allocs/op  new allocs/op  delta
GetList-8     3.05k ± 1%     2.93k ± 0%   -3.83%  (p=0.000 n=8+9)
More later, once parsers can reuse strings from previous parses.
Updates #5958

portlist: update some internals to use append-style APIs

---

ipn/ipnlocal/local.go
portlist/poller.go

Poller.C and Poller.c were duplicated for one caller. Add an accessor returning the receive-only version instead. It'll inline.
Poller.Err was unused. Remove.
Then Poller is opaque.
The channel usage and shutdown was a bit sketchy. Clean it up.
And document some things.

portlist: unexport all Poller fields, removing unused one, rework channels

---

portlist/portlist.go
portlist/portlist_linux.go
portlist/portlist_linux_test.go

Make Linux parsePorts also an append-style API and attach it to caller's provided append base memory.
And add a little string intern pool in front of the []byte to string for inode names.
name       old time/op    new time/op    delta
GetList-8    11.1ms ± 4%     9.8ms ± 6%  -11.68%  (p=0.000 n=9+10)
name       old alloc/op   new alloc/op   delta
GetList-8    92.8kB ± 2%    79.7kB ± 0%  -14.11%  (p=0.000 n=10+9)
name       old allocs/op  new allocs/op  delta
GetList-8     2.94k ± 1%     2.76k ± 0%   -6.16%  (p=0.000 n=10+10)
More coming. (the bulk of the allocations are in addProcesses and filesystem operations, most of which we should usually be able to skip)
Updates #5958

portlist: further reduce allocations on Linux

---

portlist/portlist_test.go

In contrast to BenchmarkGetList, this new BenchmarkGetListIncremental acts like what happens in practice, remembering the previous run and avoiding work that's already been done previously.
Currently:
BenchmarkGetList
BenchmarkGetList-8                           100          11011100 ns/op           68411 B/op       2211 allocs/op
BenchmarkGetList-8                           100          11443410 ns/op           69073 B/op       2223 allocs/op
BenchmarkGetList-8                           100          11217311 ns/op           68421 B/op       2197 allocs/op
BenchmarkGetList-8                           100          11035559 ns/op           68801 B/op       2220 allocs/op
BenchmarkGetList-8                           100          10921596 ns/op           69226 B/op       2225 allocs/op …

portlist: add BenchmarkGetListIncremental

---

net/dnscache/dnscache.go

On Android, the system resolver can return IPv4 addresses as IPv6-mapped addresses (i.e. `::ffff:a.b.c.d`). After the switch to `net/netip` (19008a3), this case is no longer handled and a response like this will be seen as failure to resolve any IPv4 addresses.
Handle this case by simply calling `Unmap()` on the returned IP when it is a 4-in-6 address. Fixes #5698.

net/dnscache: Handle 4-in-6 addresses in DNS responses

---

portlist/netstat_test.go
portlist/poller.go
portlist/portlist.go
portlist/portlist_linux.go
portlist/portlist_linux_test.go
portlist/portlist_test.go

Add an osImpl interface that can be stateful and thus more efficient between calls. It will later be implemented by all OSes but for now this change only adds a Linux implementation.
Remove Port.inode. It was only used by Linux and moves into its osImpl.
Don't reopen /proc/net/* files on each run. Turns out you can just keep then open and seek to the beginning and reread and the contents are fresh.
name                    old time/op    new time/op    delta
GetListIncremental-8    7.29ms ± 2%    6.53ms ± 1%  -10.50%  (p=0.000 n=9+9)
name                   old alloc/op   new alloc/op   delta
GetListIncremental-8    1.30kB ±13%    0.70kB ± 5%  -46.38%  (p=0.000 n=9+10)
name                  old allocs/op  new allocs/op  delta
GetListIncremental-8      33.2 ±11%      18.0 ± 0%  -45.82% …

portlist: refactor, introduce OS-specific types

---

cmd/tsconnect/README.md
cmd/tsconnect/README.pkg.md
cmd/tsconnect/build-pkg.go

Makes the landing page at https://www.npmjs.com/package/@tailscale/connect look slightly nicer.
Fixes #5976

cmd/tsconnect: add README to generated NPM package

---

net/interfaces/interfaces.go

It looks like this was left by mistake in 4a3e2842.
Change-Id: Ie4e3d5842548cd2e8533b3552298fb1ce9ba761a

net/interfaces: don't call GetList in List.ForeachInterface

---

cmd/nginx-auth/mkdeb.sh

We need a new release to handle TCD changes
after MagicDNS GA
Updates https://github.com/tailscale/tailscale/issues/6048

cmd/nginx-auth: increment version.

---

wgengine/netstack/netstack.go

TCP selective acknowledgement can improve throughput by an order of magnitude in the presence of loss.

wgengine/netstack: enable TCP SACK

---

tka/tka_test.go
types/key/nl.go

This allows direct use of NLPublic with tka.Authority.KeyTrusted() and similar without using tricks like converting the return value of Verifier.

tka, types/key: add NLPublic.KeyID

---

control/controlhttp/http_test.go
control/controlhttp/server.go

New plan for #5972. Instead of sending the public key in the clear (from earlier unreleased 246274b8e91) where the client might have to worry about it being dropped or tampered with and retrying, we'll instead send it post-Noise handshake but before the HTTP/2 connection begins.
This replaces the earlier extraHeaders hook with a different sort of hook that allows us to combine two writes on the wire in one packet.
Updates #5972

control/controlhttp: add AcceptHTTP hook to add coalesced Server->Client write

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go
wgengine/netlog/logger.go
wgengine/userspace.go

There is utility in logging traffic statistics that occurs at the physical layer. That is, in order to send packets virtually to a particular tailscale IP address, what physical endpoints did we need to communicate with?
This functionality logs IP addresses identical to what had always been logged in magicsock prior to #5823, so there is no increase in PII being logged.
ExtractStatistics returns a mapping of connections to counts. The source is always a tailscale IP address (without port), while the destination is some endpoint reachable on WAN or LAN. As a special case, traffic routed through DERP will use 127.3.3.40 as the destination address with the port being the DERP region.
This entire feature is only enabled if data-plane audit logging is enabled on the tailnet (by default it is …

wgengine/magicsock: gather physical-layer statistics

---

types/netlogtype/netlogtype.go
wgengine/netlog/logger.go
wgengine/netlog/logger_test.go
wgengine/userspace.go
wgengine/wgcfg/config.go
wgengine/wgcfg/nmcfg/nmcfg.go
wgengine/wgcfg/wgcfg_clone.go

This allows network messages to be annotated with which node it came from.

wgengine/netlog: embed the StableNodeID of the authoring node

---

wgengine/netlog/logger.go

This is a temporary hack to prevent logtail getting stuck uploading the same excessive message over and over. A better solution will be discussed and implemented.

wgengine/netlog: enforce hard limit on network log message sizes

---

cmd/netlogfmt/main.go
go.mod
go.sum

Make netlogfmt useful regardless of the exact schema of the input. If a JSON object looks like a network log message, then unmarshal it as one and then print it.
This allows netlogfmt to support both a stream of JSON objects directly serialized from netlogtype.Message, or the schema returned by the /api/v2/tailnet/{{tailnet}}/network-logs API endpoint.

cmd/netlogfmt: handle any stream of network logs

---

control/controlhttp/client.go
control/controlhttp/client_common.go
control/controlhttp/client_js.go

It was just added and unreleased but we've decided to go a different route.
Details are in 5e9e57ecf531f.
Updates #5972

control/controlhttp: remove ClientConn.UntrustedUpgradeHeaders

---

wgengine/userspace.go

If the network logging configruation changes (and nothing else) we will tear down the network logger and start it back up. However, doing so will lose the router configuration state. Manually reconfigure it with the routing state.

wgengine: perform router reconfig for netlog-only changes

---

ipn/ipnlocal/local.go

Followup to using `ipn.PrefsView` (#6031).

ipn/ipnlocal: fix a log line having function pointers instead of values

---

net/dns/manager_darwin.go

Instead of returning a custom error, use ErrGetBaseConfigNotSupported that seems to be intended for this use case. This fixes DNS resolution on macOS clients compiled from source.

net/dns: getting base DNS config is not supported on macOS

---

control/controlclient/noise_test.go

Basic HTTP/2-over-noise client test. To be fleshed out in subsequent commits that add more functionality to the noise client.
Updates #5972

control/controlclient: add start of noise+http2 upgrade test

---

cmd/tailscale/cli/set.go

Make "tailscale set" by itself be equivalent to "tailscale set -h" rather than just say "you did it wrong" and make people do another -h step.

cmd/tailscale/cli: make set without args print usage

---

client/tailscale/apitype/controltype.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

It does nothing and never did and I don't think anybody remembers what the original goal for it was.
Updates #5229 (fixes, but need to clean it up in another repo too)

client/tailscale/apitype, tailcfg: delete never used mysterious PerDomain field

---

client/tailscale/localclient.go
cmd/tailscale/cli/network-lock.go
control/controlclient/auto.go
control/controlclient/client.go
control/controlclient/direct.go
ipn/ipnlocal/local.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
ipn/ipnlocal/state_test.go
ipn/localapi/localapi.go
tailcfg/tailcfg.go
tailcfg/tka.go

* Plumb disablement values through some of the internals of TKA enablement.
* Transmit the node's TKA hash at the end of sync so the control plane understands each node's head.
* Implement /machine/tka/disable RPC to actuate disablement on the control plane.
* Send the TKA head hash in the map request. Changes to this value are communicated via sync-send; the map request is not restarted.
There is a partner PR for the control server I'll send shortly.

cmd,ipn/ipnlocal,tailcfg: implement TKA disablement

---

cmd/tsconnect/wasm/wasm_js.go

If we never had a chance to open the SSH session we should not try to close it.
Fixes #6089

cmd/tsconnect: fix null pointer dereference when DNS lookups fail

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/up.go

It was from very early Tailscale and no longer makes sense.

cmd/tailscale/cli: hide old, useless --host-routes flag

---

control/controlclient/noise.go
control/controlclient/noise_test.go
tailcfg/tailcfg.go

Not yet used, but skipped over, parsed, and tested.
Updates #5972

control/controlclient, tailcfg: add support for EarlyNoise payload before http/2

---

client/tailscale/tailscale.go
control/controlclient/auto.go
control/controlclient/direct.go
control/controlclient/noise.go
ipn/ipnlocal/local.go
tsnet/tsnet.go
types/key/chal.go

client/tailscale, tsnet, ipn/ipnlocal: prove nodekey ownership over noise

---

wgengine/userspace.go

In the future this will cause a node to be unable to join the tailnet if network logging is enabled.

wgengine: respect --no-logs-no-support flag for network logging

---

client/tailscale/localclient.go
cmd/tailscale/cli/network-lock.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
ipn/localapi/localapi.go
tailcfg/tka.go

This implements `tailscale lock sign <node-key>`.

cmd/tailscale,ipn: implement lock sign command

---

wgengine/netstack/netstack.go

It's leftover from an earlier Tailscale SSH wiring and I forgot to delete it apparently.

wgengine/netstack: remove old unused handleSSH hook

---

control/controlclient/direct.go
control/controlclient/noise.go
control/controlclient/noise_test.go

This allows reusing the NoiseClient in other repos without having to reimplement the earlyPayload logic.

control/controlclient: export NoiseClient

---

util/winutil/winutil_windows.go

It's normal for HKLM\SOFTWARE\Policies\Tailscale to not exist but that currently produces a lot of log spam.

util/winutil: remove log spam for missing registry keys

---

cmd/tailscale/cli/web.go
ipn/backend.go
ipn/fake_test.go
ipn/ipnlocal/local.go
ipn/ipnlocal/state_test.go
ipn/prefs_test.go

It is currently a `ipn.PrefsView` which means when we do a JSON roundtrip, we go from an invalid Prefs to a valid one.
This makes it a pointer, which fixes the JSON roundtrip.

ipn: make Notify.Prefs be a *ipn.PrefsView

---

ipn/backend.go

This was missed in 6afe26575cf155bd0baba8e4770bc49c0d55e2c1

ipn: add missing check for nil Notify.Prefs

---

tsnet/example/tshello/tshello.go

strings.Cut allows us to be more precise here. This example was written before strings.Cut existed.

tsnet/example/tshello: use strings.Cut

---

cmd/containerboot/main.go

cmd/containerboot: don't write device ID when not in Kubernetes.

---

client/tailscale/localclient.go
cmd/tailscale/cli/debug.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go

Not for end users (unless directed by support). Mostly for ease of development for some upcoming webserver work.

cmd/tailscale, ipn/ipnlocal: add debug command to write to StateStore for dev

---

api.md

We added the tailnet organization name to to the settings page with tailscale/corp#6977, but the docs were not updated to reflect this. We later also changed "tailnet name" to refer to the MagicDNS hostname (tailscale/corp#7537), which further confuses things (see https://stackoverflow.com/questions/74132318).
Make it slightly clearer what is the expected value for tailnet names in API calls and how to get it.

api.md: make it clearer where to get the tailnet name in API calls

---

cmd/derper/derper_test.go
net/netcheck/netcheck.go

The derpers don't allow whitespace in the challenge.
Change-Id: I93a8b073b846b87854fba127b5c1d80db205f658

net/netcheck: don't use a space in the captive portal challenge

---

wgengine/netstack/netstack.go
wgengine/netstack/netstack_test.go

All IPv6 packets for the self address were doing netip.Prefix.Contains lookups.
If if we know they're for a self address (which we already previously computed and have sitting in a bool), then they can't be for a 4via6 range.

wgengine/netstack: optimize shouldProcessInbound, avoiding 4via6 lookups

---

ipn/doc.go
ipn/ipn_clone.go
ipn/ipn_view.go
ipn/ipnlocal/local.go
ipn/prefs.go
ipn/store.go

cmd/viewer couldn't deal with that map-of-map. Add a wrapper type instead, which also gives us a place to add future stuff.

ipn: add WebServerConfig, add views

---

types/netlogtype/netlogtype.go
types/netlogtype/netlogtype_test.go

There is a finite limit to the maximum message size that logtail can upload. We need to make sure network logging messages remain under this size. These constants allow us to compute the maximum number of ConnectionCounts we can buffer before we must flush.

types/netlogtype: add constants for maximum serialized sizes of ConnectionCounts

---

client/tailscale/localclient.go
cmd/tailscale/cli/debug.go
ipn/localapi/localapi.go
ipn/localapi/pprof.go

Avoids name collision with profiles for user switching.

ipn/localapi: rename /profile to /pprof

---

cmd/tailscale/cli/up.go
cmd/tailscale/cli/web.go
cmd/tailscaled/tailscaled.go
cmd/tsconnect/wasm/wasm_js.go
control/controlclient/auto.go
control/controlclient/direct.go
control/controlclient/status.go
ipn/backend.go
ipn/fake_test.go
ipn/ipnlocal/local.go
ipn/ipnlocal/local_test.go
ipn/ipnlocal/loglines_test.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
ipn/ipnlocal/peerapi_test.go
ipn/ipnlocal/profiles.go
ipn/ipnlocal/profiles_test.go
ipn/ipnlocal/ssh_test.go
ipn/ipnlocal/state_test.go
ipn/ipnserver/server.go
ipn/prefs.go
ipn/store.go
ssh/tailssh/tailssh_test.go
tsnet/tsnet.go
tstest/integration/integration_test.go
types/persist/persist.go
types/persist/persist_clone.go
types/persist/persist_test.go
types/persist/persist_view.go
wgengine/netstack/netstack_test.go

ipn/ipnlocal: add support for multiple profiles

---

ipn/ipnlocal/local.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go

Regression from #6022, caught in different repo.

ipn/ipnlocal: use updated prefs in tkaSyncIfNeeded

---

cmd/tailscale/cli/network-lock.go
ipn/ipnlocal/network-lock.go
ipn/ipnstate/ipnstate.go
tka/key.go
tka/tka.go
types/key/nl.go

* Fix broken add/remove key commands
* Make lock status display whether the node is signed

cmd/tailscale,ipn: minor fixes to tailscale lock commands

---

net/dns/resolver/tsdns.go
net/dns/resolver/tsdns_test.go

```
$ dig +short @100.100.100.100 aaaa 10-2-5-3-via-7.foo-bar.ts.net fd7a:115c:a1e0:b1a:0:7:a02:503
$ dig +short @100.100.100.100 aaaa 10-2-5-3-via-7
fd7a:115c:a1e0:b1a:0:7:a02:503
$ ping 10-2-5-3-via-7
PING 10-2-5-3-via-7(fd7a:115c:a1e0:b1a:0:7:a02:503 (fd7a:115c:a1e0:b1a:0:7:a02:503)) 56 data bytes ...
```

net/dns/resolver: add yet another 4via6 DNS form that's hopefully more robust

---

ipn/ipnlocal/network-lock_test.go

It left the envknob turned on which meant that running all the tests in the package had different behavior than running just any one test.

ipn/ipnlocal: make TKA tests not have side effects

---

ipn/ipnlocal/local.go

This makes it so that the backend also restarts when users change, otherwise an extra call to Start was required.
Updates #713

ipn/ipnlocal: call restart backend on user changes

---

ipn/ipnlocal/serve.go
net/interfaces/interfaces.go

ipn/ipnlocal: don't warn about serve listener failing on IPv6-less machines

---

cmd/tailscale/cli/debug.go
cmd/tailscale/cli/serve.go

The key changed, but also we have a localapi method to set it anyway, so use that.

cmd/tailscale/cli: update serve debug set command after FUS profile change

---

client/tailscale/localclient.go
cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/network-lock.go
ipn/localapi/localapi.go

* Support specifiying disablement values in lock init command
* Support specifying rotation key in lock sign command
* Implement lock disable command
* Implement lock disablement-kdf command
This PR represents another chunk of CLI improvements (along with https://github.com/tailscale/tailscale/pull/6182).

cmd/tailscale,ipn: support disablement args in lock cli, implement disable

---

cmd/tailscale/cli/web.go

QNAP 5.x works much better if we let Apache proxy
tailscale web, which means the URLs can no longer
be relative since apache sends us an internal
URL. Access QNAP authentication via
http://localhost:8080/ as documented in
https://download.qnap.com/dev/API_QNAP_QTS_Authentication.pdf

cmd/tailscale: access QNAP via localhost

---

cmd/tailscale/cli/network-lock.go
control/controlclient/direct.go
ipn/ipnlocal/local.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
ipn/ipnlocal/profiles.go
ipn/ipnserver/server.go
ipn/ipnstate/ipnstate.go
types/key/nl.go
types/persist/persist.go
types/persist/persist_clone.go
types/persist/persist_test.go
types/persist/persist_view.go

This moves the NetworkLock key from a dedicated StateKey to be part of the persist.Persist struct.
This struct is stored as part for ipn.Prefs and is also the place where we store the NodeKey.
It also moves the ChonkDir from "/tka" to "/tka-profile/<profile-id>". The rename was intentional
to be able to delete the "/tka" dir if it exists.
This means that we will have a unique key per profile, and a unique directory per profile.
Note: `tailscale logout` will delete the entire profile, including any keys. It currently does not
delete the ChonkDir.

all: store NL keys per profile

---

version/prop.go

It was previously only invoked from the CLI, which only runs from the main .app. However, starting with #6022 we also invoke it from the network extension.

version: make IsSandboxedMacOS handle the IPNExtension binary too

---

ipn/ipnlocal/local.go

ipn/ipnlocal: be more assertive about rules for applyPrefsToHostinfo (now Locked)

---

ipn/ipnlocal/local.go

I was too late with review feedback to 513780f4f8.

ipn/ipnlocal: move LocalBackend.validPopBrowserURL empty check from caller

---

ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go
ipn/ipnlocal/peerapi_test.go

The peerAPIHandler is instantiated per PeerAPI call so it is guaranteed to have the latest selfNode.

ipn/ipnlocal: move selfNode from peerAPIServer to peerAPIHandler

---

ipn/ipnlocal/local.go

Optimization for control.
Change-Id: Ie93b232ab3e543d53062b462bdc13e279176f7a9

ipn/ipnlocal: set Hostinfo.WireIngress when ingress enabled

---

logtail/id.go

This function is no longer necessary as you can trivially rewrite:
logtail.MustParsePublicID(...)
with:
must.Get(logtail.ParsePublicID(...))

logtail: remove MustParsePublicID

---

tstime/tstime.go
tstime/tstime_test.go

The cutset provided to strings.TrimRight was missing the digit '6', making it such that we couldn't parse something like "365d".

tstime: fix ParseDuration for '6' digit

---

portlist/portlist_macos.go

We were leaking processes otherwise.
Co-authored-by: Mihai Parparita <mihai@tailscale.com>

portlist: wait for lsof cmd to exit

---

ipn/localapi/localapi.go

The LocalClient.BugReport method already sends it via POST.

ipn/localapi: require POST to add a bugreport marker

---

ipn/ipnlocal/local.go
ipn/ipnlocal/profiles.go
ipn/ipnlocal/profiles_test.go
ipn/ipnlocal/state_test.go
ipn/prefs.go
types/persist/persist.go
types/persist/persist_clone.go
types/persist/persist_test.go
types/persist/persist_view.go

We would end up with duplicate profiles for the node as the UserID would have chnaged. In order to correctly deduplicate profiles, we need to look at both the UserID and the NodeID. A single machine can only ever have 1 profile per NodeID and 1 profile per UserID.
Note: UserID of a Node can change when the node is tagged/untagged, and the NodeID of a device can change when the node is deleted so we need to check for both.
Updates #713

ipn/ipnlocal: handle untagging nodes better

---

ipn/ipnlocal/local.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go

In main, some of the prefs handling was reworked and some of those changes were cherry picked to 1.32. This prevents failures for the internal integration test for TKA that was failing due to an uninitialized prefs.Persist.
cc @twitchyliquid64

ipn/ipnlocal: fix integration test failure in tkaSyncIfNeeded

---

tsweb/tsweb.go
tsweb/tsweb_test.go

Ideally we should strip other invalid characters too ([reference](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)), but that would call for a regexp replacement which increases the number of allocations and makes `TestVarzHandlerSorting` fail.

tsweb: avoid dashes in Prometheus metric names

---

tailcfg/tailcfg.go

Adding this convenience for tailscale/corp#8015 and to avoid leaking WireIngress.

tailcfg: add TailscaleFunnelEnabled to HostInfo

---

cmd/tailscale/cli/serve.go

Current behavior is broken. tailscale serve text / "" returns no error and shows up in tailscale serve status but requests return a 500 "empty handler".
Adds an error if the user passes in an empty string for the text handler.
Closes https://github.com/tailscale/tailscale/issues/6405

cmd/tailscale/cli: disallow empty text "" from serve CLI

---

net/dns/manager_windows.go
net/dns/manager_windows_test.go

This is safer given that we need to close the NRPT database.

net/dns: change windows DNS manager to use pointer receiver

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/login.go
cmd/tailscale/cli/set.go
cmd/tailscale/cli/up.go
ipn/ipn_clone.go
ipn/ipn_view.go
ipn/ipnlocal/local.go
ipn/ipnlocal/profiles.go
ipn/prefs.go
ipn/prefs_test.go

This adds a `--nickname` flag to `tailscale login|set`.
Updates #713

cmd/tailscale/cli: add ability to set short names for profiles

---

ipn/ipnlocal/local.go
wgengine/netstack/netstack_test.go

We were not calling checkPrefs on `opts.*Prefs` in (*LocalBackend).Start().
Updates #713

ipn/ipnlocal: call checkPrefs in Start too

---

ipn/ipnlocal/local.go

It's only read in a couple of places and we can read from Prefs directly.

ipn/ipnlocal: stop storing serverURL in LocalBackend

---

tsweb/tsweb.go
tsweb/tsweb_test.go

This will allow tracking build versions and runtime versions in Prometheus.

tsweb: export version metrics to Prometheus

---

client/tailscale/localclient.go
cmd/tailscale/cli/file.go
ipn/backend.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go

ipn{,/ipnlocal}, client/tailscale: move Taildrop recv notifications to LocalAPI HTTP method

---

ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go

By always firing off a sync after enablement, the control plane should know the node's TKA head at all times.

ipn/ipnlocal: always tx TKA sync after enablement

---

ipn/ipnlocal/network-lock.go
tka/state.go
tka/state_test.go

We generate a persistent 16-byte nonce thats fixed for the life of a tailnet key authority. The primary purpose of this is to randomize the genesis AUM hash, but such a value could be useful for future features.

ipn/ipnlocal,tka: generate a nonce for each TKA state

---

ipn/ipnlocal/local.go

Somewhere in the last week's changes to ipnlocal we broke TKA initialization. This manifests later, which upon getting a netmap TKA tries to initialize from scratch but finds it already had stored state:
```
tkaSyncIfNeeded: enabled=true, head=Q5UJDFVMPCZFQH6TLRE7KZSSBXOZGMKFLBV2LCGE75A7SSXFVL6A
TKA sync error: bootstrap: tka bootstrap: tailchonk is not empty
```
Is this the right place to call `initTKALocked` in the new, profiley world?

ipn/ipnlocal: call initTKALocked on backend start

---

ipn/ipnlocal/local.go

While reading the DNS code noticed that we were still using FallbackResolvers in this code path but the comment was out of date.

ipn/ipnlocal: update comment about using FallbackResolvers for exit nodes

---

ipn/ipnlocal/peerapi.go

Apparently there's no tracking bug?
Updates tailscale/corp#7515 for ingress/funnel at least.

ipn/ipnlocal: lock down unsigned peers more

---

envknob/envknob.go
ipn/ipnlocal/peerapi.go

This matches CanSSHD (TS_DISABLE_SSH_SERVER) for administratively disabling the code on a node, regardless of local or server configs.
This can be configured in /etc/default/tailscaled on Linux, %ProgramData%\Tailscale\tailscaled-env.txt on Windows, or /etc/tailscale/tailscaled-env.txt on Synology. (see getPlatformEnvFile)
Also delete some dead code and tidy up some docs.

envknob: add CanTaildrop (TS_DISABLE_TAILDROP) to disable taildrop on device

---

cmd/tailscale/cli/serve.go
cmd/tailscale/cli/serve_test.go
tailcfg/tailcfg.go

There are three specific requirements for Funnel to work:
1) They must accept an invite.
2) They must enable HTTPS.
3) The "funnel" node attribute must be appropriately set up in the ACLs.

cmd/tailscale/cli: Improve messaging when Funnel is unavailable.

---

tsnet/example/tshello/tshello.go

tsnet/example/tshello: use the correct LocalClient for certs

---

ipn/localapi/localapi.go

To force an EngineStatus update to the IPN bus.
This is a temporary measure while migrating the Windows GUI entirely to the LocalAPI and off the old IPN protocol. The old IPN protocol had RequestEngineStatus and LocalAPI didn't.
Updates #6417

ipn/localapi: add "enginestatus" debug command to LocalAPI

---

ipn/ipnauth/ipnauth.go
ipn/ipnserver/proxyconnect.go
ipn/ipnserver/proxyconnect_js.go
ipn/ipnserver/server.go

Now that everything's just HTTP, there's no longer a need to have a header-sniffing net.Conn wraper that dispatches which route to take. Refactor to just use an http.Server earlier instead.
Updates #6417

ipn/ipnserver: remove protoSwitchConn shenanigans; just use http.Server early

---

client/tailscale/localclient.go
ipn/backend.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go

So GUI clients don't need to poll for it.
We still poll internally (for now!) but that's still cheaper. And will get much cheaper later, without having to modify clients once they start sending this bit.

ipn: add a WatchIPNBus option bit to subscribe to EngineStatus changes

---

cmd/tailscale/cli/status.go

Still show original, but show de-punycode version in parens, similar to how we show DNS-less hostnames.

cmd/tailscale: de-punycode hostnames in status display

---

ipn/ipnauth/ipnauth.go
ipn/ipnlocal/local.go
ipn/ipnlocal/profiles.go
ipn/ipnserver/server.go
ipn/prefs.go

The "userID is empty everywhere but Windows" docs on lots of places but not everywhere while using just a string type was getting confusing. This makes a new type to wrap up those rules, however weird/historical they might be.

ipn/ipnauth: make new WindowsUserID type to consolidate docs

---

ipn/backend.go
ipn/ipnlocal/local_test.go

Only the macOS/iOS clients care about it still, so we'll move it to their repo.
But keep a test that makes sure that LocalBackend continues to implement it so we get an early warning sign before we break macOS/iOS.

ipn: remove unused Backend interface

---

cmd/tailscaled/tailscaled.go

This adds an envknob to make testing async startup more reproducible. We want the Windows GUI to behave well when wintun is not (or it's doing its initial slow driver installation), but during testing it's often too fast to see that it's working. This lets it be slowed down.
Updates #6522

cmd/tailscaled: add TS_DEBUG_BACKEND_DELAY_SEC for testing async startup

---

client/tailscale/localclient.go
cmd/tailscale/cli/network-lock.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
ipn/localapi/localapi.go
tka/tka.go
types/persist/persist.go
types/persist/persist_clone.go
types/persist/persist_test.go
types/persist/persist_view.go

Implements `tailscale lock local-disable`, which shuts down tailnet lock on the local node. This can be done on all nodes if the disablement secrets are lost by the admin but they want to disable network lock.
/cc @maisem for changes to `persist.Persist`, and that I'm doing the right sequence to update that struct in `(*LocalBackend).NetworkLockForceLocalDisable`.

ipn,types/persist: store disallowed TKA's in prefs, lock local-disable

---

ipn/ipnlocal/local.go

The Go style weirds people out so we try to stick to the more well-known double hyphen style in docs.

ipn/ipnlocal: use double dash flag style

---

ipn/ipnlocal/profiles.go
ipn/ipnlocal/profiles_test.go
ipn/prefs.go

We merge/dedupe profiles based on UserID and NodeID, however we were not accounting for ControlURLs.
Updates #713

ipn/ipnlocal: account for ControlURL when merging profiles

---

cmd/tailscale/cli/web.go

When running `tailscale web` as a standalone process, it was necessary to send auth requests to QTS using localhost to avoid hitting the proxy recursively.
However running `tailscale web` as a process means it is consuming RAM all the time even when it isn't actively doing anything.
After switching back to the `tailscale web` CGI mode, we don't need to specifically use localhost for QNAP auth.
This reverts commit e0cadc54968519eae7e37e0e65ab9a7052bd54e8.

Revert "cmd/tailscale: access QNAP via localhost"

---

cmd/tailscale/cli/network-lock.go

By specifying the rotation key, this allows the node being signed to rotate its own signature as its node-key rotates.

cmd/tailscale/cli: show rotation key when suggesting lock sign command

---

ipn/ipnlocal/local.go
ipn/ipnlocal/network-lock.go
tailcfg/tailcfg.go

**CAPVER 51**
Previously, `TAILSCALE_USE_WIP_CODE` was needed to hit a bunch of the TKA paths. With this change:
- Enablement codepaths (`NetworkLockInit`) and initialization codepaths (`tkaBootstrapFromGenesisLocked` via `tkaSyncIfNeeded`) require either the WIP envknob or `CapabilityTailnetLockAlpha`.
- Normal operation codepaths (`tkaSyncIfNeeded`, `tkaFilterNetmapLocked`) require TKA to be initialized, or either-or the envknob / capability.
- Auxillary commands (ie: changing tka keys) require TKA to be initialized.
The end result is that it shouldn't be possible to initialize TKA (or subsequently use any of its features) without being sent the capability or setting the envknob on tailscaled yourself.
I've also pulled out a bunch of unnecessary checks for `CanSupportNetworkLock()`.

ipn/ipnlocal,tailcfg: introduce capability to gate TKA init paths

---

ipn/ipnlocal/peerapi.go

The peerapi IPv6 listener has a nil listener.
But we didn't need the listener's address anyway, so don't try to use it.

ipn/ipnlocal: fix netstack peerapi crash over IPv6

---

cmd/tailscale/cli/cert.go

Signed-off-by: Maya Kaczorowski <15946341+mayakacz@users.noreply.github.com>
Fixes `tailscale cert` help text to be capitalized like all other short help

cmd/tailscale/cli: capitalize Get

---

net/dns/manager_linux.go

I couldn't find any logs that indicated which mode it was running in so adding that. Also added a gauge metric for dnsMode.

net/dns: [linux] log and add metric for dnsMode

---

ipn/ipnlocal/local.go

Missed when added recently in 8dd141877444ec3cefe0ba5765b07063f550b760

ipn/ipnlocal: set Notify.Version on initial Notifies

---

api.md

This documents the `If-Match: "ts-default"` header that can be set to only overwrite the default ACL contents, and also briefly mentions a few of the new top-level ACL fields.
Updates tailscale/terraform-provider-tailscale#182

api.md: update documentation for the "set ACL" endpoint

---

cmd/tailscale/cli/set.go
cmd/tailscale/cli/switch.go
cmd/tailscale/cli/up.go

Matches the UI clients
Updates #713

cmd/tailscale/cli: use "account" instead of "profile" in user-visible text

---

paths/paths.go
version/distro/distro.go

Resolves a TODO in the code noted while discussing QNAP defaults.
Tested on DSM6 and DSM7.

paths, version/distro: detect Synology DSM version better, use for socket path

---

ipn/backend.go
ipn/prefs.go

Things are slightly less tangled now that we've migrated prefs to the backend (and renamed the field to `LegacyMigrationPrefs`).

ipn: update comments that refer to Options.Prefs

---

paths/paths.go

paths: set QNAP socket to /tmp.

---

client/tailscale/localclient.go
cmd/tailscale/cli/network-lock.go
ipn/ipnlocal/network-lock.go
ipn/localapi/localapi.go

* Do not print the status at the end of a successful operation
* Ensure the key of the current node is actually trusted to make these changes
* `go fmt` on `network-lock.go`

ipn/ipnlocal,cmd/tailscale: minor improvements to lock modify command

---

cmd/containerboot/kube.go
cmd/containerboot/main.go
cmd/containerboot/main_test.go

We still have to shell out to `tailscale up` because the container image's API includes "arbitrary flags to tailscale up", unfortunately. But this should still speed up startup a little, and also enables k8s-bound containers to update their device information as new netmap updates come in.
Fixes #6657

cmd/containerboot: switch to IPN bus monitoring instead of polling.

---

cmd/tailscale/cli/serve.go
cmd/tailscale/cli/status.go
ipn/localapi/localapi.go
ipn/serve.go

Fixes https://github.com/tailscale/tailscale/issues/6400
open up GETs for localapi serve-config to allow read-only access to
ServeConfig
`tailscale status` will include "Funnel on" status when Funnel is
configured. Prints nothing if Funnel is not running.
Example:
```console
$ tailscale status
<nodes redacted>
```

cmd/tailscale/cli, ipn/localapi: add funnel status to status command

---

tsnet/example/tsnet-http-client/tsnet-http-client.go
tsnet/tsnet.go

This allows tsnet services to make requests to other services in the tailnet with the tsnet service identity instead of the identity of the host machine. This also enables tsnet services to make requests to other tailnet services without having to have the host machine join the tailnet.
Signed-off-by: Xe Iaso <xe@tailscale.com>

tsnet: add HTTP client method to tsnet.Server

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

We would replace the existing real implementation of `nettype.PacketConn` with a `blockForeverConn`, but that violates the contract of `atomic.`Value (where the type cannot change). Fix by switching to a pointer value (`atomic.Pointer[nettype.PacketConn]`).
A longstanding issue, but became more prevalent when we started binding connections to interfaces on macOS and iOS (#6566), which could lead to the bind call failing if the interface was no longer available.
Fixes #6641

wgengine/magicsock: fix panic when rebinding fails

---

net/tstun/wrap.go
net/tstun/wrap_test.go

We would call parsedPacketPool.Get() for all packets received in Read/Write. This was wasteful and not necessary, fetch a single *packet.Parsed for all packets.

net/tstun: reuse buffered packet from pool

---

client/tailscale/authkey.go
client/tailscale/keys.go

client/tailscale: add APIs for auth key management.

---

util/multierr/multierr.go
util/multierr/multierr_test.go

Errors in Go are no longer viewed as a linear chain, but a tree.
See golang/go#53435.
Add a Range function that iterates through an error in a pre-order, depth-first order.
This matches the iteration order of errors.As in Go 1.20.

util/multierr: add Range

---

cmd/k8s-operator/operator.go

cmd/k8s-operator: remove unused structs. Cleanup missed in #6718.

---

wgengine/magicsock/magicsock.go

wgengine/magicsock: fix panic in wireguard-go rate limiting path

---

cmd/k8s-operator/operator.go
cmd/k8s-operator/operator_test.go
go.mod

As is convention in the k8s world, use zap for structured logging. For development, OPERATOR_LOGGING=dev switches to a more human-readable output than JSON.
Updates #502

cmd/k8s-operator: sprinkle debug/info logging throughout.

---

cmd/k8s-operator/manifests/operator.yaml
cmd/k8s-operator/operator.go
go.mod

This automates both the operator's initial login, and provisioning/deprovisioning of proxies.

cmd/k8s-operator: use oauth credentials for API access.

---

util/multierr/multierr.go
util/multierr/multierr_test.go

Consider the following pattern:
err1 := foo()
err2 := bar()
err3 := baz()
return multierr.New(err1, err2, err3)
If err1, err2, and err3 are all nil, then multierr.New should not allocate. Thus, modify the logic of New to count the number of distinct error values and allocate the exactly needed slice. This also speeds up non-empty error situation since repeatedly growing with append is slow.
Performance:
name         old time/op    new time/op    delta
Empty-24       41.8ns ± 2%     6.4ns ± 1%   -84.73%  (p=0.000 n=10+10)
NonEmpty-24     120ns ± 3%      69ns ± 1%   -42.01%  (p=0.000 n=9+10)
name         old alloc/op   new alloc/op   delta
Empty-24        64.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)
NonEmpty-24      168B ± 0%       88B ± 0%   -47.62%  (p=0.000 n=10+10)
name …

util/multierr: optimize New for nil cases

---

ssh/tailssh/incubator.go
ssh/tailssh/tailssh_test.go

Fixes #5285
Co-authored-by: @andrew-d

ssh/tailssh: set default Tailscale SSH $PATH for non-interactive commands

---

cmd/k8s-operator/manifests/operator.yaml
cmd/k8s-operator/operator.go

The operator creates a fair bit of internal cluster state to manage proxying, dumping it all in the default namespace is handy for development but rude for production.
Updates #502

cmd/k8s-operator: move the operator into its own namespace.

---

ipn/ipnserver/server.go

This ensures that we capture error returned by `Serve` and exit with a non-zero exit code if it happens.

ipn/ipnserver: propagate http.Serve error

---

net/connstats/stats.go
net/connstats/stats_test.go
net/tstun/wrap_test.go
types/netlogtype/netlogtype.go
wgengine/magicsock/magicsock_test.go
wgengine/netlog/logger.go

The Tailscale logging service has a hard limit on the maximum log message size that can be accepted.
We want to ensure that network logging messages
never exceed this limit otherwise a client cannot transmit logs.
Move the goroutine for periodically dumping netlog messages from wgengine/netlog to net/connstats.
This allows net/connstats to manage when it dumps messages, either based on time or by size.
Updates tailscale/corp#8427

net/connstats: enforce maximum number of connections

---

cmd/containerboot/main.go
cmd/containerboot/main_test.go

In some configurations, user explicitly do not want to store tailscale state in k8s secrets, because doing that leads to some annoying permission issues with sidecar containers. With this change, TS_KUBE_SECRET="" and TS_STATE_DIR=/foo will force storage to file when running in kubernetes.
Fixes #6704.

cmd/containerboot: allow disabling secret storage in k8s.

---

net/dns/manager.go

We saw a few cases where we hit this limit; bumping to 4k seems relatively uncontroversial.
Change-Id: I218fee3bc0d2fa5fde16eddc36497a73ebd7cbda

net/dns: bump DNS-over-TCP size limit to 4k

---

ssh/tailssh/tailssh.go

"look up" is the verb. "lookup" is a noun.

ssh/tailssh: fix typo in error message

---

envknob/envknob.go
wgengine/magicsock/magicsock.go

envknob, magicsock: add TS_DISCO_PONG_IPV4_DELAY knob to bias IPv6 paths

---

wgengine/monitor/monitor_linux.go

These aren't handled, but it's not an error to get one.
Fixes #6806
Change-Id: I1fcb9032ac36420aa72a048bf26f58360b9461f9

wgengine/monitor: don't log unhandled RTM_{NEW,DEL}LINK messages

---

ipn/ipnlocal/local.go
ipn/ipnlocal/serve.go

By default, `http.Transport` keeps idle connections open hoping to re-use them in the future. Combined with a separate transport per request in HTTP proxy this results in idle connection leak.
I initially added simple transport caching per backend (see first commit) but then decided to keep proxy handlers per backend, which is a bit more complex given its interactions with prefs.

ipn/ipnlocal: maintain a proxy handler per backend

---

wgengine/netstack/netstack.go
wgengine/netstack/netstack_test.go

Noticed while looking at something else; #cleanup.
Change-Id: Icde7749363014eab9bebe1dd80708f5491f933d1

wgengine/netstack: delete some dead code, old comment, use atomic int types

---

cmd/tailscaled/tailscaled.go
cmd/tsconnect/wasm/wasm_js.go
tsnet/tsnet.go
wgengine/netstack/netstack.go
wgengine/netstack/netstack_test.go

Local backend is used in determining if tailscale 4via6 forwarding needs to be used - enforcing local backend to be passed into the netstack start method will ensure that all tailscale clients will have a local backend. The mac client didn't initialize netstack w/ a local backend, and thus 4via6 routing didn't work for macos clients. 
Updates tailscale/tailscale#6764 (then needs macOS client changes too)

wgengine/netstack: require local backend for netstack start

---

flake.lock
flake.nix
go.mod.sri
go.toolchain.sri
shell.nix
version/version.go

This lets me (and other brave souls) pull tailscale/tailscale into my NixOS configs as a source, and use the `tailscale-unstable` package to run dev builds on my home tailnet.
Because of the forced vendorSha256 semantics for go module builds, this flake is unfortunately going to be annoyingly brittle as we update go.mod during development. I don't want to force everyone to have a nix dep and fix things up every time they need to change go.mod, so this flake is expected to be brittle right now, with frequently broken builds that I'll need to fix up manually. I'm okay with this.
Longer term, I think we can reuse the NAR hash computation thing @bradfitz made to make it possible to update the vendor NAR hash without needing a full nix install, at which point we can add automation and testing …

flake.nix: make a flake that gives access to unstable tailscale builds.

---

cmd/nardump/README.md
cmd/nardump/nardump.go
flake.nix
go.toolchain.sri
pull-toolchain.sh
shell.nix
update-flake.sh

Keeps both the Go toolchain and go.mod SRI files up to date with `./update-flake.sh`. Incidentally, this also let me know I'd set the wrong toolchain SRI in the first place, and because of nix's cache-hit behavior it didn't tell me about it. Sigh.
This moves misc/nardump from our corp repo into oss, so that the tooling can invoke it here. Using git trickery, I made the nardump commit be authored by @bradfitz, to preserve authorship for posterity. I signed-off the commit though, since I'm the one pinky-swearing this code is okay per our DCO.

Add automation to maintain flake.nix hashes.

---

cmd/printdep/printdep.go
version-embed.go

cmd/printdep: support printing the toolchain SRI hash.

---

flake.nix

There is no unstability inherent in this package, it's just unstable if you choose to import the flake at the main branch.

flake.nix: rename package to just "tailscale".

---

cmd/tailscale/cli/web.go

When the user clicks on the Tailscale app in the QNAP App Center, we do a GET from /cgi-bin/authLogin.cgi to look up their SID.
If the user clicked "secure login" on the QNAP login page to use HTTPS, then our access to authLogin.cgi will also use HTTPS but the certiciate is self-signed. Our GET fails with:
`Get "https://10.1.10.41/cgi-bin/authLogin.cgi?sid=abcd0123": x509: cannot validate certificate for 10.1.10.41 because it doesn't contain any IP SANs`
or similar errors.
Instead, access QNAP authentication via http://localhost:8080/ as documented in
https://download.qnap.com/dev/API_QNAP_QTS_Authentication.pdf
Fixes https://github.com/tailscale/tailscale-qpkg/issues/62

cmd/tailscale: use localhost for QNAP authLogin.cgi

---

net/tlsdial/tlsdial_test.go
tstest/archtest/qemu_test.go
tstest/iosdeps/iosdeps_test.go
tstest/jsdeps/jsdeps_test.go
version/modinfo_test.go

Go now includes the GOROOT bin directory in $PATH while running tests and generate, so it is no longer necessary to construct a path using runtime.GOROOT().
Fixes #6689

net/tlsdial,tstest,version: use go command from $PATH

---

control/controlclient/map.go
ipn/localapi/localapi.go
types/netmap/netmap.go

For debugging #6423. This is easier than TS_DEBUG_MAP, as this means I can pipe things into jq, etc.
Updates #6423

ipn/localapi: add localapi debug endpoints for packet filter/matches

---

cmd/tailscale/cli/network-lock.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
tka/aum.go
tka/aum_test.go
tka/builder.go
tka/builder_test.go
tka/chaintest_test.go
tka/key.go
tka/key_test.go
tka/scenario_test.go
tka/sig_test.go
tka/state.go
tka/tka_test.go

* `tka.Key.KeyID()` now returns an error instead of panicking.
* Unknown AUM types are now correctly handled.
* Minor UX tweaks and fixes falling out of the alpha.
The former two changes won't matter now (no new key types or AUM types) but we'll need to lockstep `1.34` in the future :grimacing:

TKA tweaks, fixes, error handling

---

health/health.go
ipn/ipnlocal/network-lock.go

Looked like this during testing:
```
```

health,ipn/ipnlocal: report the node being locked out as a health issue

---

logtail/logtail.go

Instead of a static FlushDelay configuration value, use a FlushDelayFn function that we invoke every time we decide send logs. This will allow mobile clients to be more dynamic about when to send logs.
Updates #6768

logtail: make logs flush delay dynamic

---

ipn/ipnlocal/peerapi.go

Unsigned peers should not be allowed to generate Wake-on-Lan packets,
only access Funnel.
Updates #6934
Updates #7515
Updates #6475

ipn/ipnlocal: disallow unsigned peers from WoL

---

cmd/tailscale/cli/web.go

QNAP's "Force HTTPS" mode redirects even localhost HTTP to HTTPS, but uses a self-signed certificate which fails verification. We accommodate this by disabling checking of the cert.
Fixes https://github.com/tailscale/tailscale/issues/6903

cmd/tailscale: disable HTTPS verification for QNAP auth.

---

types/views/views.go
types/views/views_test.go

This is a copy of the tagsEqual func from corp/control/control.go, moved here so that it can be reused in other places.
I'm not sure if there is a better name for this, since these slices aren't truly equal, since they can be in different order.  But it's also not just a "ContainsAll" function.  Open to suggestions.
Signed-off-by: Will Norris <will@tailscale.com>

types/views: add SliceEqualAnyOrder func

---

net/flowtrack/flowtrack.go
net/flowtrack/flowtrack_test.go
wgengine/filter/filter.go

net/flowtrack,wgengine/filter: refactor Cache to use generics

---

net/portmapper/portmapper.go
net/portmapper/upnp.go

Gateway devices operating as an HA pair w/VRRP or CARP may send UPnP replies from static addresses rather than the floating gateway address. This commit relaxes our source address verification such that we parse responses from non-gateway IPs, and re-point the UPnP root desc URL to the gateway IP. This ensures we are still interfacing with the gateway device (assuming L2 security intact), even though we got a root desc from a non-gateway address.
This relaxed handling is required for ANY port mapping to work on certain OPNsense/pfsense distributions using CARP at the time of writing, as miniupnpd may only listen on the static, non-gateway interface address for PCP and PMP.
Fixes #5502

net/portmapper: relax handling of UPnP resp

---

ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go

Needed for clients that get information via the /v0/status LocalAPI endpoint (e.g. to not offer expired exit nodes as options).
Updates tailscale/corp#8702

ipn/ipnlocal: add Expired to PeerStatus

---

net/packet/packet.go
net/packet/packet_test.go
net/tstun/wrap_test.go
wgengine/filter/filter.go

01b90df2fa4f9101e4f0ae8334b00dd9c3ccc148 added SCTP support before (with explicit parsing for ports) and
69de3bf7bfddb37b4c0e076c93115f82a51ec407 tried to add support for arbitrary IP protocols (as long as the ACL permited a port of "*", since we might not know how to find ports from an arbitrary IP protocol, if it even has such a concept). But apparently that latter commit wasn't tested end-to-end enough. It had a lot of tests, but the tests made assumptions about layering that either weren't true, or regressed since 1.20. Notably, it didn't remove the (*Filter).pre bidirectional filter that dropped all "unknown" protocol packets both leaving and entering, even if there were explicit protocol matches allowing them in.
Also, don't map all unknown protocols to 0. Keep their IP protocol …

net/{packet,tstun},wgengine/filter: fix unknown IP protocol handling

---

wgengine/netstack/netstack_test.go

This uses the helper function added in #6173 to avoid flakes like:
https://github.com/tailscale/tailscale/actions/runs/3826912237/jobs/6511078024
Change-Id: If3f1d3b9c0f64ffcb4ba9a30d3522ec49484f993

wgengine/netstack: fix data race in tests

---

cmd/tailscale/cli/update.go
cmd/tailscale/cli/update_test.go

cmd/tailscale/cli: make 'tailscale update' support Debian/Ubuntu apt

---

cmd/tailscale/cli/version.go
tailcfg/tailcfg_export_test.go
tailcfg/tailcfg_test.go
version/prop.go
version/version.go

Add `tailscale version --json` JSON output mode. This will be used later for a double-opt-in (per node consent like Tailscale SSH + control config) to let admins do remote upgrades via `tailscale update` via a c2n call, which would then need to verify the cmd/tailscale found on disk for running tailscale update corresponds to the running tailscaled, refusing if anything looks amiss.
Plus JSON output modes are just nice to have, rather than parsing unstable/fragile/obscure text formats.
Updates #6995
Updates #6907

version, cmd/tailscale: add version.Meta, tailscale version --json

---

net/connstats/stats_test.go

net/connstats: mark TestConcurrent as flaky

---

cmd/testwrapper/flakytest/flakytest.go
tstest/integration/integration_test.go

Updates #7036
Change-Id: I3aec5ad680078199ba984bf8afc20b2f2eb37257

tstest/integration: mark all integration tests as flaky

---

wgengine/wglog/wglog.go
wgengine/wglog/wglog_test.go

wgengine/wglog: add a prefix for all wireguard logs

---

ipn/ipnlocal/local.go

The current node isn't in NetMap.Peers, so without this we would not have fired this timer on self expiry.
Updates #6932
Change-Id: Id57f96985397e372f9226802d63b42ff92c95093

ipn/ipnlocal: fire expiry timer when the current node expires

---

hostinfo/hostinfo.go

Set the `Env` field just like we do for some other runtimes.

hostinfo: add an environment type for Replit

---

ipn/ipnlocal/local.go
net/dnscache/dnscache.go
net/dnscache/dnscache_test.go
tailcfg/tailcfg.go

This allows us to temporarily enable/disable dnscache logging via a new node capability, to aid in debugging strange connectivity issues.
Change-Id: I46cf2596a8ae4c1913880a78d0033f8b668edc08

ipn/ipnlocal, net/dnscache: allow configuring dnscache logging via capability

---

hostinfo/hostinfo_windows.go

You can now install Tailscale on Windows via [Scoop](https://scoop.sh).
This change adds a check to `packageTypeWindows()`, looking at the exe's path, and checking if it starts with: `C:\User\<NAME>\scoop\apps\tailscale`. If so, it returns `"scoop"` as the package type.
Fixes: #6988

hostinfo: [windows] check if running via Scoop

---

cmd/sync-containers/main.go

Running sync-containers in a GitHub workflow will be simpler if we check github.Keychain, which uses the GITHUB_TOKEN if present.
Updates https://github.com/tailscale/corp/issues/8461

cmd/sync-containers: add github.Keychain

---

ipn/ipnlocal/local.go
net/netns/netns.go
net/netns/netns_darwin.go
net/netns/netns_darwin_test.go
tailcfg/tailcfg.go

When turned on via environment variable (off by default), this will use the BSD routing APIs to query what interface index a socket should be bound to, rather than binding to the default interface in all cases.
Updates https://github.com/tailscale/tailscale/issues/5719
Updates https://github.com/tailscale/tailscale/pull/5940
Change-Id: Ib4c919471f377b7a08cd3413f8e8caacb29fee0b

net/netns: add functionality to bind outgoing sockets based on route table

---

docs/k8s/README.md
docs/k8s/proxy.yaml
docs/k8s/sidecar.yaml
docs/k8s/subnet.yaml
docs/k8s/userspace-sidecar.yaml

Updates https://github.com/tailscale/tailscale-www/issues/2199.
Signed-off-by: Walter Poupore <walterp@tailscale.com>

docs/k8s: Use TS_AUTHKEY instead of TS_AUTH_KEY

---

ipn/ipnlocal/local.go
ipn/ipnlocal/profiles.go
ipn/localapi/localapi.go

The iOS has a command to reset the persisted state of the app, but it was doing its own direct keychain manipulation. This proved to be brittle (since we changed how preferences are stored with #6022), so we instead add a LocalAPI endpoint to do do this, which can be updated in tandem.
This clears the same state as the iOS implementation (tailscale/corp#3186), that is the machine key and preferences (which includes the node key). Notably this does not clear the logtail ID, so that logs from the device still end up in the same place.
Updates tailscale/corp#8923

ipn/ipnlocal: add /reset-auth LocalAPI endpoint

---

build_docker.sh

Since we now sync ghcr indirectly due to credential headaches.

build_docker.sh: don't push to ghcr by default.

---

build_docker.sh

build_docker.sh: use docker hub for base image hosting.

---

cmd/k8s-operator/manifests/operator.yaml

There is no stable release yet, and for alpha we want people on the unstable build while we iterate.
Updates #502

cmd/k8s-operator: use the unstable operator image

---

cmd/k8s-operator/manifests/operator.yaml

We need a post-1.36 tailscale image to handle custom hostnames correctly.
Updates #502

cmd/k8s-operator: use unstable tailscale image as well

---

flake.nix
go.mod.sri
shell.nix

flake.nix: update SRI hash for Go modules.

---

cmd/tsconnect/README.md
cmd/tsconnect/wasm/wasm_js.go

Makes the Wasm client more similar to the others, and allows the default profile to be correctly picked up when restarting the client in dev mode (where we persist the state in sessionStorage).
Also update README to reflect that Go Wasm changes can be picked up with just a reload (as of #5383).

cmd/tsconnect: use empty string as the default state store key

---

cmd/derpprobe/derpprobe.go
prober/derp.go
prober/prober.go
prober/prober_test.go

`prober.DERP` was created in #5988 based on derpprobe. Having used it instead of derpprobe for a few months, I think we have enough confidence that it works and can now migrate derpprobe to use the prober framework and get rid of code duplication.
A few notable changes in behaviour:
- results of STUN probes over IPv4 and IPv6 are now reported separately;
- TLS probing now includes OCSP verification;
- probe names in the output have changed slightly;
- ability to send Slack notification from the prober has been removed. Instead, the prober now exports metrics in Expvar (/debug/vars) and Prometheus (/debug/varz) formats.
Fixes https://github.com/tailscale/corp/issues/8497

cmd/derpprobe: migrate to the prober framework

---

cmd/tsconnect/package.json
cmd/tsconnect/yarn.lock

It includes xtermjs/xterm.js#4216, which improves handling of some escape sequences. Unfortunately it's not enough to fix the issue with `ponysay`, but it does not hurt to be up to date.
Updates #6090

cmd/tsconnect: update to xterm.js 5.1

---

flake.lock
flake.nix

Bleeding edge Tailscale Nix flake broke after updating to go1.20rc3.
Go 1.20 moved to Go 1.17 as a bootstarp toolchain. Fortunately nixpkgs nixos-unstable already had a 1.20.nix with bootstrap117.nix.
```
❯ ./result/bin/tailscale version
1.37.0-dev
track: unstable (dev); frequent updates and bugs are likely
go version: go1.20rc3-ts6a17f14c05
```

nix: update nixpkgs flake, override go_1_20 for tailscale_go

---

cmd/tailscale/cli/cli.go

It's since been rewritten in Swift.
#cleanup

cmd/tailscale/cli: delete ActLikeCLI

---

tsweb/tsweb.go
util/vizerror/vizerror.go
util/vizerror/vizerror_test.go

okay, NOW I get what you were suggesting [in this comment](https://github.com/tailscale/tailscale/pull/7120#discussion_r1091180336).

util/vizerror: add As function to get wrapped Error

---

go.toolchain.branch

go.toolchain.branch: update to Go 1.20

---

.github/workflows/cifuzz.yml

It doesn't yet support Go 1.20. We can bring it back later.
Updates #7123

.github/workflows: delete CIFuzz job

---

util/multierr/multierr.go

Now that Go 1.20 is released, multierr.Error can implement `Unwrap() []error`
Updates #7123
Change-Id: Ic28c2579de6799801836c447afbca8cdcba732cf

util/multierr: implement Go 1.20+'s multiple error Unwrap

---

ipn/localapi/localapi.go

Having this information near the "user bugreport" line makes it easier to identify the node and expiry without spelunking through the rest of the logs.
Change-Id: I1597c783efc06574fa4c8f211e68d835f20b6ccb

ipn/localapi: print node IDs, pubkeys, and expiry on bugreport

---

net/dns/resolver/tsdns.go
net/dns/resolver/tsdns_test.go

Add the envknob TS_DEBUG_EXIT_NODE_DNS_NET_PKG, which enables more verbose debug logging when calling the handleExitNodeDNSQueryWithNetPkg function. This function is currently only called on Windows and Android.
Change-Id: Ieb3ca7b98837d7dc69cd9ca47609c1c52e3afd7b

net/dns/resolver: add envknob to debug exit node DNS queries on on Windows

---

client/tailscale/apitype/apitype.go
hostinfo/hostinfo.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go
ipn/localapi/localapi_test.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go

questions in the form of a PR:
- I need to get this value out of the iOS app, not the networkextension, and localapi was handy. Is this a reasonable use of localAPI?
- should we send new stuff to control in Hostinfo? is there somewhere else this belongs? (it has the awkward property that on start the device token will be empty which I'm not a fan of, but otherwise looks like hostinfo stuff.)

tailcfg, localapi: plumb device token to server

---

net/dns/resolver/doh_test.go
net/dns/resolver/forwarder.go
net/dns/resolver/forwarder_test.go

It was originally added to control memory use on iOS (#2490), but then was relaxed conditionally when running on iOS 15 (#3098). Now that we require iOS 15, there's no need for the limit at all, so simplify back to the original state.

net/dns/resolver: remove maxDoHInFlight

---

ipn/ipnlocal/profiles.go
ipn/ipnlocal/profiles_test.go
ipn/ipnlocal/state_test.go

The profileManager was using the LoginName as a proxy to figure out if the profile had logged in, however the LoginName is not present if the node was created with an Auth Key that does not have an associated user.

ipn/ipnlocal: use presence of NodeID to identify logins

---

ipn/localapi/localapi.go

Previously, we only printed these at startup; print those when the user generates a bugreport as we so we don't have to go spelunking through the logs.
Change-Id: If5b0970f09fcb4cf8839958af5d37f84e0ba6ed2

ipn/localapi: print envknobs on bugreport

---

logtail/logtail.go
logtail/logtail_test.go

The 255 byte limit was chosen more than 3 years ago (tailscale/corp@929635c9d98642d34ac735e0c2004f6d3d53c706), when iOS was operating under much more significant memory constraints. With iOS 15 the network extension has an increased limit, so increasing it to 4K should be fine.
The motivating factor was that the network interfaces being logged by `linkChange` in wgengine/userspace.go were getting truncated, and it would be useful to know why in some cases we're choosing the `pdp_ip1` cell interface instead of the `pdp_ip0` one.
Updates #7184
Updates #7188

logtail: increase maximum log line size in low memory mode

---

net/netutil/ip_forward.go
net/netutil/netutil_test.go

net/netutil: only check Linux sysctls w/ procfs, assume absent means false

---

control/controlhttp/client.go
control/controlhttp/constants.go
control/controlhttp/http_test.go

We don't require any cert at all for Noise-over-plaintext-port-80-HTTP, so why require a valid cert chain for Noise-over-HTTPS? The reason we use HTTPS at all is to get through firewalls that allow tcp/443 but not tcp/80, not because we need the security properties of TLS.
Updates #3198

control/controlhttp: don't require valid TLS cert for Noise connection

---

ipn/ipnlocal/local.go
net/interfaces/interfaces.go
net/interfaces/interfaces_bsd.go
net/netns/netns.go
net/netns/netns_darwin.go
tailcfg/tailcfg.go

With #6566 we started to more aggressively bind to the default interface on Darwin. We are seeing some reports of the wrong cellular interface being chosen on iOS. To help with the investigation, this adds to knobs to control the behavior changes:
- `CapabilityDebugDisableAlternateDefaultRouteInterface` disables the alternate function that we use to get the default interface on macOS and iOS (implemented in tailscale/corp#8201). We still log what it would have returned so we can see if it gets things wrong.
- `CapabilityDebugDisableBindConnToInterface` is a bigger hammer that disables binding of connections to the default interface altogether.
Updates #7184
Updates #7188

net/interfaces, net/netns: add node attributes to control default interface getting and binding

---

cmd/get-authkey/main.go

Tailnet-owned auth keys (which all OAuth-created keys are) must include tags, since there is no user to own the registered devices.
Signed-off-by: Will Norris <will@tailscale.com>

get-authkey: require tags to be specified

---

net/connstats/stats.go
net/connstats/stats_test.go

`:=` was accidentally used, so `maxPeriod` never worked.

net/connstats: fix ticker in `NewStatistics`

---

pull-toolchain.sh

We no longer carry an SRI hash for the toolchain, so flake updating is no longer needed for toolchain changes.

pull-toolchain.sh: don't run update-flake.sh

---

version/prop.go
version/version.go

Four commits: first two revert back to before I refactored everything into init(), second two reapply the MajorMinorPatch fix, and lazily memoize more string slicing work (mac/windows flavor reporting).

version: revert my broken "optimization", redo it right

---

ipn/ipnlocal/peerapi.go

Followup to #7235, we were not treating the formatting arguments as variadic. This worked OK for single values, but stopped working when we started passing multiple values (noticed while trying out #7244).

ipn/ipnlocal: fix passthrough of formatting arguments in PeerAPI doctor output

---

net/routetable/routetable_bsd.go
net/routetable/routetable_darwin.go

As part of the work on #7248 I wanted to know all of the flags on the `RouteMessage` struct that we get back from macOS. Though it doesn't turn out to be useful (when using an exit node/Tailscale is the default route, the flags for the physical interface routes are the same), it still seems useful from a debugging/comprehensiveness perspective.
Adds additional Darwin flags that were output once I enabled this mode.

net/routetable: include unknown flags in the routetable doctor output

---

cmd/printdep/printdep.go

In the switch to static toolchains, we removed a legacy oddity from the toolchain URL structure, but forgot to update printdep.

cmd/printdep: print correct toolchain URL

---

.github/workflows/cross-android.yml
.github/workflows/cross-darwin.yml
.github/workflows/cross-freebsd.yml
.github/workflows/cross-loong64.yml
.github/workflows/cross-openbsd.yml
.github/workflows/cross-wasm.yml
.github/workflows/cross-windows.yml
.github/workflows/linux-race.yml
.github/workflows/linux.yml
.github/workflows/linux32.yml
.github/workflows/vm.yml
.github/workflows/windows.yml

We've never used the "[ci skip]" magic commit header in our history, across all our repos. This seems to be boilerplate we imported years ago and have since been copying around our CI configs.

.github/workflows: remove 'ci skip' boilerplate

---

.github/workflows/test.yml

OSS-Fuzz doesn't update their version of Go as quickly as we do, so we sometimes end up with OSS-Fuzz being unable to build our code for a few weeks. We don't want CI to be red for that entire time, but we also don't want to forget to reenable fuzzing when OSS-Fuzz does start working again.
This change makes two configurations worthy of a CI pass:
- Fuzzing works, and we expected it to work. This is a normal happy state.
- Fuzzing didn't compile, and we expected it to not compile. This is the "OSS-Fuzz temporarily broken" state.
If fuzzing is unexpectedly broken, or unexpectedly not broken, that's a CI failure because we need to either address a fuzz finding, or update TS_FUZZ_CURRENTLY_BROKEN to reflect the state of OSS-Fuzz.

.github/workflows: support disabling fuzz testing safely

---

wgengine/magicsock/magicsock.go

The stringification of the discokey type now prepends "discokey:"
Fixes https://github.com/tailscale/tailscale/issues/3074

wgengine/magicsock: remove superfluous "discokey" from log

---

.github/workflows/update-flakes.yml
update-flake.sh

So that I just get a quick PR to approve and merge instead of periodically discovering that the SRI hash has bitrotted.
---
I borrowed the credentials of the license updater, hoping it'll work out.

.github/workflows: add workflow to update go.mod Nix SRI hash

---

util/linuxfw/iptables.go
util/linuxfw/linuxfw_struct_linux_test.go
util/linuxfw/linuxfw_unsupported.go
util/linuxfw/nftables.go
util/linuxfw/nftables_types.go

This isn't currently supported due to missing support in upstream dependencies, and also we don't use this package anywhere right now. Just conditionally skip this for now.
Fixes #7268
Change-Id: Ie7389c2c0816b39b410c02a7276051a4c18b6450

util/linuxfw: add build constraints excluding GOARCH=arm

---

cmd/mkversion/mkversion.go
version/mkversion/mkversion.go
version/mkversion/mkversion_test.go

For now, direct copy from our other repo, with only license/documentation edits, plus the addition of Major/Minor/Patch attributes because some of our builds are going to need access to those (e.g. build_dist.sh).
This whole package could use a bit of a rewrite, and in its current form it only produces correct output when run in a git repository whose go.mod imports this repo... But I want to get it merged as-is and our other repo rewired before I go for deeper surgery.

version/mkversion: open-source version computation logic

---

.github/workflows/test.yml
.github/workflows/tsconnect-pkg-publish.yml
build_dist.sh
go.mod
version/mkversion/mkversion.go
version/mkversion/mkversion_test.go

And update build_dist.sh to use that code.

version/mkversion: support collecting version info from tailscale/tailscale only

---

.github/workflows/test.yml

CI status doesn't collapse into "everything OK" if a job gets skipped. Instead, always run the job, but skip its only step in PRs.

.github/workflows: fix non-collapsing CI status in PRs

---

.github/workflows/test.yml

armv5 because that's what we ship to most downstreams right now, armv7 becuase that's what we want to ship more of.
Fixes https://github.com/tailscale/tailscale/issues/7269

.github/workflows: add armv5 and armv7 cross tests

---

tailcfg/tka.go

These RPCs will be used to power the future 'tailscale lock remove' default behavior of resigning signatures for which trust is about to be removed.

tailcfg: add RPC structs for /tka/affected-sigs

---

tool/gocross/gocross.go

So that when importing and using gocross from other repos, there's an easy way to get at the right wrapper script that's in sync with the gocross binary.

tool/gocross: add command to print the wrapper shell script

---

tool/gocross/gocross.go

Turns out directing the printed script into the bootstrap location leads to irritating "text file busy" problems and then having to muck about with tempfiles and chmod and all that. Instead, have gocross write everything with the right values.

tool/gocross: write the wrapper script directly, rather than printing

---

tka/sig.go

This is needed in the coordination server.

tka: add public API on NodeKeySignature for key information

---

tool/gocross/gocross-wrapper.sh
tool/gocross/gocross.go

Two independent commits for sadnesses discovered while reimporting gocross into our other repo.

tool/gocross: adjust version management and envvar hermeticity.

---

tool/gocross/gocross-wrapper.sh
tool/gocross/toolchain.go

This makes gocross and its bootstrap script understand an absolute path in go.toolchain.rev to mean "use the given toolchain directly".

tool/gocross: support local toolchain for development

---

logtail/logtail.go
tsnet/tsnet.go
tsnet/tsnet_test.go

It works! Well, sort-of.
```
$ go test -v -run=TestConn ./tsnet
=== RUN   TestConn
tsnet_test.go:63: DERP httpsrv listener: 127.0.0.1:59689
tsnet_test.go:73: testcontrol listening on http://127.0.0.1:59691
tsnet_test.go:128: ping success: &ipnstate.PingResult{IP:"100.64.0.1", NodeIP:"100.64.0.1", NodeName:"s1", Err:"", LatencySeconds:5.219534209, Endpoint:"", DERPRegionID:0, DERPRegionCode:"", PeerAPIPort:0x0, PeerAPIURL:"", IsLocalIP:false}
tsnet_test.go:149: got: "hello"
stuntest.go:63: STUN server shutdown
--- PASS: TestConn (5.60s)
PASS
```
The ping takes 5 seconds: `LatencySeconds:5.219534209` That's a very familiar number. It suggests... something isn't working? The local DERP? But I can't quite figure it out.
Also if I remove the ping and just attempt the TCP connection …

tsnet: add data transfer test

---

cmd/dist/dist.go
release/dist/cli/cli.go
release/dist/dist.go
release/dist/memoize.go
release/dist/unixpkgs/pkgs.go
release/dist/unixpkgs/targets.go

So we can reuse it from other repos.

release/dist/cli: factor out the CLI boilerplace from cmd/dist

---

.github/workflows/test.yml

Github requires explicitly listing every single job within a workflow that is required for status checks, instead of letting you list entire workflows. This is ludicrous, and apparently this nonsense is the workaround.

.github/workflows: add a pass/fail verdict job to the test workflow

---

syncs/watchdog_test.go

We've updated to a different set of CI machines since this test was disabled.
Fixes https://github.com/tailscale/tailscale/issues/1513

syncs: re-enable TestWatchMultipleValues

---

ipn/ipnlocal/peerapi.go
net/interfaces/interfaces.go
net/interfaces/interfaces_darwin.go

Exposes the delegated interface data added by #7248 in the debug endpoint. I would have found it useful when working on that PR, and it may be handy in the future as well.
Also makes the interfaces table slightly easier to parse by adding borders to it. To make then nicer-looking, the CSP was relaxed to allow inline styles.

ipn/ipnlocal: add delegated interface information to /interfaces PeerAPI handler

---

cmd/k8s-operator/operator.go
hostinfo/hostinfo.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go

This allows us to differentiate between the various tsnet apps that we have like `golinks` and `k8s-operator`.
Feedback from https://github.com/tailscale/golink/pull/64

tailcfg,hostinfo: add App field to identify tsnet uses

---

ipn/localapi/localapi.go
ipn/localapi/localapi_test.go
tsnet/tsnet.go
tsnet/tsnet_test.go

This is for use by LocalAPI clients written in other languages that don't appear to be able to talk HTTP over a socket (e.g. java.net.http.HttpClient).

tsnet: add a LocalAPI listener on loopback, with required header

---

tsnet/tsnet.go

It turns out even with an AuthKey that pre-approves devices on a tailnet with machine auth turned on, we still temporarily see the NeedsMachineAuth state. So remove that error (for now).

tsnet: do not error on NeedsMachineAuth for Up

---

types/logid/id.go

Ever since the introduction of the "must" package, most MustXXX functions are no longer necessary.
Remove this as it is no longer depended upon
from within this repository and by the internal private repository.

types/logid: remove MustParsePublicID

---

cmd/tsconnect/src/app/app.tsx
cmd/tsconnect/src/app/header.tsx

"Device Authorization" was recently renamed to "Device Approval" on the control side. This change updates tsconnect to match.

cmd/tsconnect: update device authorization copy

---

tka/tailchonk.go
tka/tailchonk_test.go

Background:
- An `AUM` is a log entry. We don't want it to grow unbounded.
- A Checkpoint AUM is a log entry that contains the full state of the state machine, rather than just a delta. As such, you can store just the latest checkpoint and discard earlier log entries & still have a working state machine.
- But, we want to keep XX AUMs and recent AUMs around to deal with 'forks' (control data loss, rewriting history)
- AUMs can have a single parent, and multiple children. Only one child is part of the 'active chain' (read: same idea as bitcoin where you can have forks but only one is chosen to be 'the one')
This implementation attempts to implement compaction by deleting no-longer relevant AUMs. AUMs are no longer relevant if they are more than XX (`MinChain`) entries from HEAD, or older …

tka: implement compaction logic

---

cmd/k8s-operator/operator.go

"Device Authorization" was recently renamed to "Device Approval" on the control side. This change updates the k8s operator to match.

cmd/k8s-operator: update device authorization copy

---

release/dist/cli/cli.go
release/dist/dist.go

dist output can be really noisy for some of our builds because the tools we have to run are loud. This suppresses the output of successful commands by default, but still prints the output of failures. And, for those times when you really want your terminal saturated with how xcode's day is going, --verbose puts all the noise back.

release/dist: default to less noisy output, add a --verbose

---

cmd/tailscale/cli/web.go
cmd/tailscale/cli/web_test.go

QNAP allows users to set the port number for the management WebUI, which includes authLogin.cgi. If they do, then connecting to localhost:8080 fails.
https://github.com/tailscale/tailscale-qpkg/issues/74#issuecomment-1407486911
We have to use the Scheme+Path from the request but disable any TLS verification for https:
- The UI can force https, but presents a completely invalid certificate
- The UI can change the port number, and though https://download.qnap.com/dev/API_QNAP_QTS_Authentication.pdf documents the use of localhost:8080 for authentication this fails if the user changed the port number.
This reverts commit 467ace7d0c0655e69cc219ec380c0119d909f36b.
Fixes https://github.com/tailscale/tailscale/issues/7108

cmd/tailscale: use request Schema+Host for QNAP authLogin.cgi

---

logtail/logtail_test.go
types/logid/id.go
types/logid/id_test.go

Share the same underlying implementation for both PrivateID and PublicID. For the shared methods, declare them in the same order. Only keep documentation on methods without obvious meaning.

types/logid: simplify implementation

---

cmd/sniproxy/snipproxy.go
go.mod
go.sum

$ curl https://canhazip.com/
170.173.0.21
$ curl --resolve canhazip.com:443:100.85.165.81 https://canhazip.com/
34.223.127.151
Updates #1748

cmd/sniproxy: add start of a tsnet-based SNI proxy

---

net/dnsfallback/dnsfallback.go

This ensures that we're trying multiple returned IPs, since the DERP servers return the same response to all queries. This should increase the chances that we eventually reach a working IP.
Change-Id: Ie8d4fb93df96da910fae49ae71bf3e402b9fdecc

net/dnsfallback: shuffle returned IPs

---

version/distro/distro.go
wgengine/router/router_linux.go

WSL has started to set the eth0 default route interface default to 1280 MTU, which is too low to carry 1280 byte packets from tailscale0 once wrapped in WireGuard. The change down to 1280 is very likely smaller than necessary for almost all users. We can not easily determine the ideal MTU, but if all the preconditions match, we raise the MTU to 1360, which is just enough for Tailscale traffic to work.
Updates #4833
Updates #7346

version/distro,wgengine/router: raise WSL eth0 MTU when too low

---

client/tailscale/localclient.go
cmd/tailscale/cli/debug.go
cmd/tailscale/cli/netcheck.go
cmd/tailscaled/debug.go
ipn/localapi/localapi.go
net/portmapper/igd_test.go
net/portmapper/portmapper.go
net/portmapper/portmapper_test.go
net/portmapper/upnp.go
net/portmapper/upnp_test.go
tstest/integration/tailscaled_deps_test_darwin.go
tstest/integration/tailscaled_deps_test_freebsd.go
tstest/integration/tailscaled_deps_test_linux.go
tstest/integration/tailscaled_deps_test_openbsd.go
tstest/integration/tailscaled_deps_test_windows.go
wgengine/magicsock/magicsock.go

The debug flag on tailscaled isn't available in the macOS App Store build, since we don't have a tailscaled binary; move it to the 'tailscale debug' CLI that is available on all platforms instead.
Updates #7377
Change-Id: I47bffe4461e036fab577c2e51e173f4003592ff7

cmd/tailscale, cmd/tailscaled: move portmapper debugging into tailscale CLI

---

client/tailscale/localclient.go
cmd/tailscale/cli/network-lock.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
ipn/localapi/localapi.go

When `tailscale lock remove <keys>` is used, nodes which are signed by a valid to-be-removed signature are re-signed with the node's own key prior to being removed.

ipn,cmd/tailscale: implement resigning nodes on tka key removal

---

net/interfaces/interfaces.go

We weren't filtering out IPv6 addresses from this function, so we could be returning an IPv4 gateway IP and an IPv6 self IP. Per the function comments, only return IPv4 addresses for the self IP.
Change-Id: If19a4aadc343fbd4383fc5290befa0eff006799e

net/interfaces: always return an IPv4 LikelyHomeRouterIP

---

cmd/tailscale/cli/cli_test.go
net/dnscache/dnscache_test.go
net/netcheck/netcheck_test.go
tstest/tstest.go
tstest/tstest_test.go

We have many function pointers that we replace for the duration of test and restore it on test completion, add method to do that.

tstest: add method to Replace values for tests

---

net/portmapper/upnp.go

Some devices don't let you UPnP portmap a port below 1024, so let's just avoid that range of ports entirely.
Updates #7377
Change-Id: Ib7603b1c9a019162cdc4fa21744a2cae48bb1d86

net/portmapper: don't pick external ports below 1024

---

net/portmapper/upnp.go

We were previously sending a lower-case "udp" protocol, whereas other implementations like miniupnp send an upper-case "UDP" protocol. For compatibility, use an upper-case protocol instead.
Updates #7377
Change-Id: I4aed204f94e4d51b7a256d29917af1536cb1b70f

net/portmapper: send UPnP protocol in upper-case

---

ipn/localapi/localapi.go

This ensures that any mappings that are created are correctly cleaned up, instead of waiting for them to expire in the router.
Updates #7377
Change-Id: I436248ee7740eded6d8adae5df525e785a8f7ccb

ipn/localapi: close portmapper after debug

---

tsnet/tsnet.go
types/nettype/nettype.go
wgengine/netstack/netstack.go

To be used by tsnet and sniproxy later.
Updates #5871
Updates #1748

wgengine/netstack: add support for custom UDP flow handlers

---

cmd/sniproxy/snipproxy.go
tsnet/tsnet.go
tsnet/tsnet_test.go

No ListenPacket support yet, but Listen with a udp network type fit easier into netstack's model to start.
Then added an example of using it to cmd/sniproxy with a little udp :53 handler.
No tests in tsnet yet because we don't have support for dialing over UDP in tsnet yet. When that's done, a new test can test both sides.
Updates #5871
Updates #1748

tsnet: add UDP support to Server.Listen

---

net/socks5/socks5.go
net/socks5/socks5_test.go

Conforms to RFC 1929.
To support Java HTTP clients via libtailscale, who offer no other reliable hooks into their sockets.

net/socks5: add password auth support

---

tsnet/tsnet.go
tsnet/tsnet_test.go

Some languages do not give you any useful access to the sockets underlying their networking packages. E.g. java.net.http.HttpClient provides no official access to its dialing logic.
...but everyone supports proxies. So add a SOCKS5 proxy on the listener we are already running.
(The function being revamped is very new, I only added it in the last week and it wasn't part of any release, so I believe it is fine to redo its function signature.)

tsnet: generalize loopback listener to include SOCKS5

---

cmd/tsconnect/src/app/app.tsx
cmd/tsconnect/src/app/ssh.tsx
cmd/tsconnect/src/types/wasm_js.d.ts
cmd/tsconnect/wasm/wasm_js.go
flake.nix

Also fixed the lack of spacing when the 'you have no Tailscale SSH nodes' warning shows up.
I have no idea how frontend works, so apologies in advance for any grievous JS / Typescript mistakes.

cmd/tsconnect: pop CTA to make everything work with tailnet lock

---

net/dns/manager_windows.go
net/dns/wsl_windows.go

Despite the fact that WSL configuration is still disabled by default, we continue to log the machine's list of WSL distros as a diagnostic measure.
Unfortunately I have seen the "wsl.exe -l" command hang indefinitely. This patch adds a (more than reasonable) 10s timeout to ensure that tailscaled does not get stuck while executing this operation.
I also modified the Windows implementation of NewOSConfigurator to do the logging asynchronously, since that information is not required in order to continue starting up.
Fixes #7476

net/dns: deal with Windows wsl.exe hangs

---

cmd/sniproxy/snipproxy.go
tsnet/tsnet.go
tsnet/tsnet_test.go

Add a DNS server which always responds as its own IP addresses.
Additionally add a tsnet TailscaleIPs() function to return the IP addresses, both IPv4 and IPv6.
Updates https://github.com/tailscale/tailscale/issues/1748

cmd/sniproxy: draw the rest of the DNS owl.

---

util/truncate/truncate.go
util/truncate/truncate_test.go

Corresponding internal issue: https://github.com/tailscale/corp/issues/9642.
This package handles cases where we need to truncate human-readable text to fit a length constraint without leaving "ragged" multi-byte rune fragments at the end of the truncated value.
Change-Id: Id972135d1880485f41b1fedfb65c2b8cc012d416

util: add truncate package

---

.github/workflows/go-licenses.yml
.github/workflows/update-flake.yml

The main motivation for this change is to stop using the deprecated set-output function which triggers deprecation warnings in the action.
Change-Id: I80496c44ea1166b9c40d5cd9e450129778ad4aaf

.github: update tibdex/github-app-token to release v1.8.0

---

tsnet/tsnet.go
tsnet/tsnet_test.go
wgengine/netstack/netstack.go

Previously, it would accept all TCP connections and then close the ones it did not care about. Make it only ever accept the connections that it cares about.

tsnet: only intercept TCP flows that have listeners

---

control/controlclient/auto.go

Prior to this change, if we were in the middle of a lite map update we'd tear down the entire map session and restart it. With this change, we'll cancel an in-flight lite map request up to 10 times and restart before we tear down the streaming map request. We tear down everything after 10 retries to ensure that a steady stream of calls to sendNewMapRequest doesn't fail to make progress by repeatedly canceling and restarting.
Change-Id: I9392bf8cf674e7a58ccd1e476039300a359ef3b1

control/controlclient: improve handling of concurrent lite map requests

---

client/tailscale/localclient.go
cmd/tailscale/cli/network-lock.go
cmd/tailscale/cli/web_test.go
control/controlclient/direct.go
control/controlclient/direct_test.go
ipn/ipnlocal/network-lock.go
ipn/localapi/localapi.go

Design (internal doc): http://go/tailnet-lock-preauth-keys
The basic idea:
1. Admin goes to admin panel to generate a preauth key
2. Admin runs `tailscale lock tskey-wrap tskey-auth-XXXXXXX` to get a longer form of the same thing
3. Admin can now `tailscale up --authkey tskey-auth-XXXXXXX--NNNNNNNNNNNNN` to bring up nodes in a locked tailnet unattended.
Implementation details:
1. A new tailnet-lock key is generated for every wrapped key, to permit revocation on a per-authkey basis
2. The new tailnet-lock key has a smol amount of metadata that gets stamped into it: (that it backed a preauth key, when it was created, and the stable ID of the node that created it). EG: `map[purpose:pre-auth key wrapper_createtime:1677789199 wrapper_stableid:nwkXEu1CNTRL]`
3. There are two pieces to the …

all: implement preauth-key support with tailnet lock

---

logtail/logtail.go

Effectively reverts #249, since the server side was fixed (with #251?) to send a 200 OK/content-length 0 response.

logtail: remove unncessary response read

---

tstime/rate/rate.go
tstime/rate/value.go
tstime/rate/value_test.go

Add Value, which measures the rate at which an event occurs, exponentially weighted towards recent activity.
It is guaranteed to occupy O(1) memory and operate in O(1) runtime.

tstime/rate: add Value

---

syncs/syncs.go

The addition of WaitGroup.Go in the standard library has been repeatedly proposed and rejected.
See golang/go#18022, golang/go#23538, and golang/go#39863
In summary, the argument for WaitGroup.Go is that it avoids bugs like:
go func() {
wg.Add(1)
defer wg.Done()
...
}()
where the increment happens after execution (not before) and also (to a lesser degree) because:
wg.Go(func() {
...
})
is shorter and more readble.
The argument against WaitGroup.Go is that the provided function takes no arguments and so inputs and outputs must closed over by the provided function. The most common race bug for goroutines is that the caller forgot to capture the loop iteration variable, so this pattern may make it easier to be accidentally racy. However, that is changing with golang/go#57969.
In my …

syncs: add WaitGroup wrapper

---

ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go
ipn/ipnlocal/serve.go
ipn/serve.go
tsnet/example/tsnet-funnel/tsnet-funnel.go
tsnet/tsnet.go

Previously the part that handled Funnel connections was not
aware of any listeners that tsnet.Servers might have had open
so it would check against the ServeConfig and fail.
Adding a ServeConfig for a TCP proxy was also not suitable in this
scenario as that would mean creating two different listeners and have
one forward to the other, which really meant that you could not have
funnel and tailnet-only listeners on the same port.
This also introduces the ipn.FunnelConn as a way for users to identify
whether the call is coming over funnel or not. Currently it only holds
the underlying conn and the target as presented in the "Tailscale-Ingress-Target"
header.

ipn/ipnlocal: add support for funnel in tsnet

---

cmd/tailscale/cli/network-lock.go

Looks like this:
```
[xxx@tslptp:~/nl-test]$ sudo ./tailscale --socket n1/sock lock
Warning: client version "1.37.0-dev20230308-tce9947431-dirty" != tailscaled server version "1.37.0-dev20230308-tb95fa0a1f-dirty"
Tailnet lock is ENABLED.
This node is accessible under tailnet lock.
This node's tailnet-lock key: tlpub:c962606bf9cd8dd729c4e62e2321fe8db91af44252fafb3be30f48ce57624834
Trusted signing keys:
tlpub:c962606bf9cd8dd729c4e62e2321fe8db91af44252fafb3be30f48ce57624834	42	(self)
tlpub:4b43334e6de941f89d3a8bf384cf9a8e04f1b881a31caf473daf65c4176425a3	69	
tlpub:58b2f24f333037b4d703f4dc1fe9f8d308fe4cd5bbe64154c9e1270eb6d00949	1	(backing pre-auth key k7UagY1CNTRL)
The following nodes are locked out by tailnet lock and cannot connect to other nodes:
tslptp-9.tail1ef32.ts.net.	100.108.234.23, …
```

cmd/tailscale: annotate tailnet-lock keys which wrap pre-auth keys

---

ipn/ipnlocal/local.go

It kinda works fine now on macOS with the recent fixes in 0582829 and
5787989d.

ipn/ipnlocal: remove WIP restriction for Tailscale SSH on macOS

---

ipn/ipnlocal/peerapi.go
net/sockstats/sockstats.go
net/sockstats/sockstats_noop.go
net/sockstats/sockstats_tsgo.go

Followup to #7499 to make validation a separate function (`GetWithValidation` vs. `Get`). This way callers that don't need it don't pay the cost of a syscall per active TCP socket.
Also clears the conn on close, so that we don't double-count the stats.
Also more consistently uses Go doc comments for the exported API of the sockstats package.
Updates #3363

sockstats: refactor validation to be opt-in

---

tsnet/tsnet.go

We persist the ServeConfig, even for tsnet apps. It's quite possible for
the ServeConfig to be out of step with the code. Example: If you run
`ListenFunnel` then later turn it off, the ServeConfig will still show
it enabled, the admin console will show it enabled, but the packet
handler will reject the packets.
Workaround by clearing the ServeConfig in `tsnet.Up`

tsnet/tsnet: clear ipn.ServeConfig on Up for tsnet apps

---

cmd/k8s-operator/manifests/authproxy-rbac.yaml
cmd/k8s-operator/proxy.go

We were not handling tags at all, pass them through as Impersonate-Group headers.
And use the FQDN for tagged nodes as Impersonate-User.
Updates #5055

cmd/k8s-operator: pass through tags as Impersonate-Group

---

ipn/ipnlocal/c2n.go
ipn/ipnlocal/local.go
log/sockstatlog/logger.go

Add c2n endpoint for collecting sockstats logs from a device.

ipn: add c2n endpoint for sockstats logs

---

cmd/k8s-operator/proxy.go
tailcfg/tailcfg.go

Also update tailcfg docs.
Updates #5055

cmd/k8s-operator: drop trailing dot in tagged node name

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/funnel.go
cmd/tailscale/cli/serve.go
cmd/tailscale/cli/serve_test.go
cmd/tailscale/cli/status.go

Updates to the `serve` and `funnel` subcommands syntax below:
```console
$ tailscale serve https:<port> <mount-point> <source> [off]
$ tailscale serve tcp:<port> tcp://localhost:<local-port> [off]
$ tailscale serve tls-terminated-tcp:<port> tcp://localhost:<local-port> [off]
$ tailscale serve status [--json]
$ tailscale funnel <serve-port> {on|off}
$ tailscale funnel status [--json]
EXAMPLES
- To proxy requests to a web server at 127.0.0.1:3000:
$ tailscale serve https:443 / http://127.0.0.1:3000
- To serve a single file or a directory of files:
$ tailscale serve https:443 / /home/alice/blog/index.html
$ tailscale serve https:443 /images/ /home/alice/blog/images
- To serve simple static text:
$ tailscale serve https:443 / text:"Hello, world!"
- To forward raw TCP packets to a local TCP …
```

cmd/tailscale/cli: [serve] rework commands based on feedback

---

tsnet/tsnet.go
tsnet/tsnet_test.go

tsnet.Server.Close was calling listener.Close with the server mutex held, but the listener close method tries to grab that mutex, resulting in a deadlock.

tsnet: avoid deadlock on close

---

ipn/ipnlocal/peerapi.go
log/sockstatlog/logger_test.go
net/sockstats/sockstats.go
net/sockstats/sockstats_noop.go
net/sockstats/sockstats_tsgo.go

They're not needed for the sockstats logger, and they're somewhat expensive to return (since they involve the creation of a map per label). We now have a separate `GetInterfaces()` method that returns them instead (which we can still use in the PeerAPI debug endpoint).
If changing `sockstatlog` to sample at 10,000 Hz (instead of the default of 10Hz), the CPU usage would go up to 59% on a iPhone XS. Removing the per-interface stats drops it to 20% (a no-op implementation of `Get` that returns a fixed value is 16%).
Updates #3363

sockstats: remove per-interface stats from Get

---

tool/gocross/gocross-wrapper.sh

Sometimes, our cached toolchain ends up being an older version of Go, older than our go.mod allows. In that scenario, gocross-wrapper.sh would find a usable toolchain, but then fail to compile gocross.
This change makes the wrapper script check that the cached toolchain's minor version is good enough to build tailscale.com, and re-bootstraps in shell if not.

tool/gocross: bootstrap correctly on an older toolchain

---

tool/gocross/autoflags.go
tool/gocross/autoflags_test.go

Xcode changed how/what data it exports to build steps at some point recently, so our old way of figuring out the minimum support version for clang stopped working.
Updates tailscale/corp#4095

tool/gocross: adjust Xcode flags to match new Xcode env

---

build_dist.sh

For the sunos port I do cross compilation on GitHub to publish release binaries for anyone not using distro packages.
This is how I fixed `build_dist.sh` to work for me, but ultimately I have no strong feelings on how this is accomplished.
I do think it's worth keeping that script cross-compilation friendly.

build_dist.sh: make cross-compilation friendly

---

cmd/derpprobe/derpprobe.go
derp/derp_server.go
derp/derp_test.go
derp/derphttp/derphttp_client.go
prober/derp.go

This allows tracking packet flow via logs for prober clients. Note that the new `sclient.debug()` function is called on every received packet, but will do nothing for most clients.
I have adjusted sclient logging to print public keys in short format rather than full. This takes effect even for existing non-debug logging (mostly client disconnect messages).
Example logs for a packet being sent from client [SbsJn] (connected to derper [dM2E3]) to client [10WOo] (connected to derper [AVxvv]):
```
derper [dM2E3]:
derp client 10.0.0.1:35470[SbsJn]: register single client mesh("10.0.1.1"): 4 peers
derp client 10.0.0.1:35470[SbsJn]: read frame type 4 len 40 err <nil>
derp client 10.0.0.1:35470[SbsJn]: SendPacket for [10WOo], forwarding via <derphttp_client.Client [AVxvv] …
```

derp: add optional debug logging for prober clients

---

cmd/tailscale/cli/serve.go

Use the same local port number in both.

cmd/tailscale/cli: fix inconsistency between serve text and example command

---

ssh/tailssh/incubator.go
ssh/tailssh/privs_test.go

On FreeBSD and Darwin, changing a process's supplementary groups with setgroups(2) will also change the egid of the process, setting it to the first entry in the provided list. This is distinct from the behaviour on other platforms (and possibly a violation of the POSIX standard).
Because of this, on FreeBSD with no TTY, our incubator code would previously not change the process's gid, because it would read the newly-changed egid, compare it against the expected egid, and since they matched, not change the gid. Because we didn't use the 'login' program on FreeBSD without a TTY, this would propagate to a child process.
This could be observed by running "id -p" in two contexts. The expected output, and the output returned when running from a SSH shell, is:
andrew@freebsd:~ $ id -p
uid …

ssh/tailssh: fix privilege dropping on FreeBSD; add tests

---

tool/gocross/gocross-wrapper.sh

Previously, the build ended up embedding an empty string, which made the shell wrapper rebuild gocross on every invocation. This is still reasonably fast, but fixing the bypass shaves 80% off gocross's overhead when no rebuild is needed.

tool/gocross: correctly embed the git commit into gocross

---

tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

This change introduces the Recorders field to the SSHRule struct. The field is used to store and define addresses where the ssh recorder is located.

tailcfg: add recorders field to SSHRule struct

---

scripts/installer.sh

pkgs.tailscale.com added support in January, need to add it to the installer script.

scripts/installer.sh: Add Ubuntu Lunar Lobster 23.04.

---

prober/prober.go
prober/prober_test.go

This will make probe latency graphs on a dashboard more meaningful.
Updates https://github.com/tailscale/corp/issues/9916

prober: only record latency for successful probes

---

ipn/ipnlocal/c2n.go
ipn/ipnlocal/local.go
log/sockstatlog/logger.go

Switch to using logtail for logging sockstat logs. Always log locally (on supported platforms), but disable automatic uploading.  Change existing c2n sockstats request to trigger upload to log server and return log ID.
The main thing left to do here is figure out which logid to use.  @dsnet and I talked about this briefly the other day, but didn't arrive at a conclusive answer.  We can't use the main logid for the device because we're logging into a different collection, and that can cause issues.  We could derive the ID from the main logid (maybe `sha256(logid + "sockstats")` or something?)  It needs to be easily reproducible so we can get the sockstats for given node ID, but I don't know that it's worth the effort to plumb it all the way through control like we do for other IDs.  wdyt?

log: use logtail to log and upload sockstat logs

---

ssh/tailssh/incubator.go

Move the assertions about our post-privilege-drop UID/GID out of the conditional if statement and always run them; I haven't been able to find a case where this would fail. Defensively add an envknob to disable this feature, however, which we can remove after the 1.40 release.
Updates #7616
Change-Id: Iaec3dba9248131920204bd6c6d34bbc57a148185

ssh/tailssh: always assert our final uid/gid

---

ipn/store/kubestore/store_kube.go

Kubernetes doesn't allow slashes as keys in secrets, replace them with "__".
This shows up in the kubernetes-operator now that tsnet sets resets the ServeConfig at startup.
Fixes #7662

ipn/store/kubestore: handle "/" in ipn.StateKeys

---

cmd/k8s-operator/operator.go
cmd/k8s-operator/proxy.go

Kubernetes uses SPDY/3.1 which is incompatible with HTTP/2, disable it in the transport and server.
Fixes #7645
Fixes #7646

cmd/k8s-operator: disable HTTP/2 for the auth proxy

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

Previously it would dial out using the http.DefaultClient, however that doesn't work when tailscaled is running in userspace mode (e.g. when testing).

ssh/tailssh: handle session recording when running in userspace mode

---

scripts/installer.sh

Photon OS support crossed streams with using pkgserve to check for supported versions 6f9aed1656d0d9ff1a22ed6a022120c6a4f43688. Make Photon OS also rely on pkgserve.
Updates https://github.com/tailscale/tailscale/issues/7651 Updates https://github.com/tailscale/corp/issues/8952

scripts/installer.sh: check Photon OS version with pkg server.

---

ipn/ipnlocal/serve.go

This change trims the mountPoint from the request URL path before
sending the request to the reverse proxy.
Today if you mount a proxy at `/foo` and request to
`/foo/bar/baz`, we leak the `mountPoint` `/foo` as part of the request
URL's path.
This fix makes removed the `mountPoint` prefix from the path so
proxied services receive requests as if they were running at the root
(`/`) path.
This could be an issue if the app generates URLs (in HTML or otherwise)
and assumes `/path`. In this case, those URLs will 404.
With that, I still think we should trim by default and not leak the
`mountPoint` (specific to Tailscale) into whatever app is hosted.
If it causes an issue with URL generation, I'd suggest looking at configuring
an app-specific path prefix or running Caddy as a more advanced …

ipn/ipnlocal: [serve] Trim mountPoint prefix from proxy path

---

cmd/tailscale/cli/funnel.go
cmd/tailscale/cli/serve.go
ipn/serve.go
tailcfg/tailcfg.go

Updates CLI and docs to reference Funnel as beta

funnel: change references from alpha to beta

---

cmd/tailscale/cli/cli_test.go
cmd/tailscale/cli/up.go
util/dnsname/dnsname.go
util/dnsname/dnsname_test.go

In addition to checking the total length, enforce the 63-char limit on the first label. Use limits documented in RFC 1035.
Updates https://github.com/tailscale/corp/issues/10012

cmd/tailscale: extend hostname length checks

---

ipn/ipnlocal/local.go
log/sockstatlog/logger.go

Once we're confident about this, we can change ipnlocal to construct the sockstat logger on all clients, but then only enable it by default on unstable builds.

log: allow toggling sockstat logs via c2n component logging

---

util/codegen/codegen.go

I took the simple approach of declaring a flag directly in the codegen package, rather than threading it through (as a bool param, yuck) in two places.
I also opted for a bool rather than anything more complicated: The header contains a copyright holder and a license indicator, and trying to model all of that in flags was going to get ugly. (Multiple flags? Read from a file?)
I'm happy to alter either of those choices if you prefer, though.
Fixes #7702
Oh and btw, looks like the fallback dns server file could use regeneration.

util/codegen: add -copyright to control presence of copyright headers

---

go.mod
go.sum
net/tstun/tun.go
wgengine/magicsock/magicsock.go

This commit updates the wireguard-go dependency to pull in fixes for the tun package, specifically 052af4a and aad7fca.

go.mod, net/tstun, wgengine/magicsock: update wireguard-go

---

wgengine/netstack/netstack.go

Use the local context on Impl to check for shut down state in order to drop rather than inject packets after close has begun.
Netstack sets endpoint.dispatcher to nil during shutdown. After the recent adjustment in 920ec69241930c352818b0bf3eab20e62df93ed1 we now wait for netstack to fully shutdown before we release tests. This means that we may continue to accept packets and attempt to inject them, which we must prevent in order to avoid nil pointer panic.
References google/gvisor#8765
Fixes #7715

wgengine/netstack: do not send packets to netstack after close

---

tempfork/device/LICENSE
tempfork/device/README.md
tempfork/device/allowedips.go
tempfork/device/allowedips_rand_test.go
tempfork/device/allowedips_test.go
tempfork/device/peer.go

This will allow us to reuse the AllowedIPs for NAT decisions in a follow on commit.
The files `allowedips_*.go` are as-is, `peer.go` only keeps the `Peer` declaration with a single element required for AllowedIPs.
Upstream commit https://git.zx2c4.com/wireguard-go/commit/?id=052af4a8072bbbd3bfe7edf46fe3c1b350f71f08
Updates tailscale/corp#8020

tempfork/device: add a temp fork of golang.zx2c4.com/wireguard/device

---

ipn/ipnlocal/local.go
ipn/store.go
ipn/store/kubestore/store_kube.go
kube/client.go

For stores like k8s secrets we need to dial out to the k8s API as though Tailscale wasn't running. The issue currently only manifests when you try to use an exit node while running inside a k8s cluster and are trying to use Kubernetes secrets as the backing store.
This doesn't address cmd/containerboot, which I'll do in a follow up.
Updates #7695
cc @uhthomas

ipn/store: add support for stores to hook into a custom dialer

---

envknob/logknob/logknob.go
envknob/logknob/logknob_test.go
types/netmap/netmap.go

A LogKnob allows enabling logs with an envknob, netmap capability, and manually, and calling a logging function when logs are enabled.
Change-Id: Id66c608d4e488bfd4eaa5e867a8d9289686748be

envknob/logknob: add package for configurable logging

---

cmd/tsconnect/common.go
cmd/tsconnect/tsconnect.go

#7339 changed the root directory logic to find the ancestor of the cwd with a go.mod file. This works when running the the binary from this repo directly, but breaks when we're a dependency in another repo.
Allow the directory to be passed in via a `-rootdir` flag (the repo that depends on it can then use `go list -m -f '{{.Dir}}' tailscale.com` or similar to pass in the value).
Updates tailscale/corp#10165

cmd/tsconnect: allow root directory to be passed in

---

atomicfile/atomicfile.go
atomicfile/atomicfile_test.go

The intent of atomicfile is to overwrite regular files. Most use cases that would overwrite irregular files, unix sockets, named pipes, devices, and so on are more than likely misuse, so disallow them.
Fixes #7658

atomicfile: reject overwriting irregular files

---

cmd/tailscale/cli/cli.go
cmd/tailscale/cli/funnel.go
cmd/tailscale/cli/serve.go

Make serve and visible in the command list. Should've been done when they moved to
beta in v1.38.3.
Updates: #7613

cmd/tailscale/cli: make serve and funnel visible in list

---

client/tailscale/localclient.go

Fixes https://github.com/tailscale/tailscale/issues/7572
When handling an error during `StreamDebugCapture`, the response body is closed, even though the response struct is always nil. Thanks to https://github.com/darkrain42 for debugging this!!

client/tailscale: Fix NPE caused by erroneous close in error case

---

ipn/ipnlocal/local.go

Avoids needing a separate c2n call to get the logs uploaded.

ipn/ipnlocal: automatically upload sockstats logs when the period ends

---

ipn/ipnlocal/local.go

This makes the sockstat logger available on all builds, but only enables it by default for unstable.  For stable builds, the logger must be explicitly enabled via C2N component logger.
Updates #3363

ipn: add sockstat logger to stable builds

---

net/art/stride_table.go
net/art/stride_table_test.go
net/art/table.go

One of the main internal parts of ART tables. It's big enough that I figured it should get its own PR, before I wrap it in the external APIs that do multi-level lookups.
---
A stride table is an 8-bit routing table implemented as an array binary tree, with a special tree updating function (allot) that enables lightning fast address lookups and reasonably fast insertion and deletion.
Insertion, deletion and lookup are all allocation-free.
Updates #7781
```
│    sec/op    │
StrideTableInsertion/10/random_order       16.79n ± 2%
StrideTableInsertion/10/largest_first      16.83n ± 1%
StrideTableInsertion/10/smallest_first     16.83n ± 0%
StrideTableInsertion/50/random_order       17.84n ± 1%
StrideTableInsertion/50/largest_first      20.04n ± 1%
StrideTableInsertion/50/smallest_first …
```

net/art: implement the stride table building block of ART

---

net/neterror/neterror.go
net/neterror/neterror_linux.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_default.go
wgengine/magicsock/magicsock_linux.go
wgengine/magicsock/magicsock_test.go

This commit implements UDP offloading for Linux. GSO size is passed to and from the kernel via socket control messages. Support is probed at runtime.
UDP GSO is dependent on checksum offload support on the egress netdev. UDP GSO will be disabled in the event sendmmsg() returns EIO, which is a strong signal that the egress netdev does not support checksum offload.
Updates tailscale/corp#8734

net/neterror, wgengine/magicsock: use UDP GSO and GRO on Linux

---

go.mod
go.sum

Pull in TUN checksum optimizations and crypto channel changes.
Updates tailscale/corp#8734

go.mod: bump wireguard-go

---

util/clientmetric/clientmetric.go
util/clientmetric/clientmetric_test.go

Adds `NewGaugeFunc` and `NewCounterFunc` (inspired by `expvar.Func`), which allow the current value to be reported by a function. This allows some client metric values to be computed on-demand during uploading (at most every 15 seconds), instead of being continuously updated.
clientmetric uploading had a bunch of micro-optimizations for memory access (#3331) which are not possible with this approach. However, any performance hit from function-based metrics is contained to those metrics only, and we expect to have very few.
Also adds a `DisableDeltas()` option for client metrics, so that absolute values are always reported. This makes server-side processing of some metrics easier to reason about.

util/clientmetric: allow client metric values to be provided by a function

---

net/sockstats/sockstats_tsgo.go
net/sockstats/sockstats_tsgo_test.go

power state is very roughly approximated based on observed network activity and AT&T's state transition timings for a typical 3G radio.
Updates #3363

sockstats: add client metrics for radio power state

---

net/sockstats/sockstats_tsgo.go

net/sockstats: disable deltas for the cell radio power state metric

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

Identified in review in https://github.com/tailscale/tailscale/pull/7821 endpoint.discoKey and endpoint.discoShort
are often accessed without first taking endpoint.mu. The arrangement
with endpoint.mu is inconvenient for a good number of those call-sites,
so it is instead replaced with an atomic pointer to carry both pieces of
disco info. This will also help with https://github.com/tailscale/tailscale/pull/7821 that wants to add explicit
checks/guards to disable disco behaviors when disco keys are missing
which is necessarily implicitly mostly covered by this change.
Updates #7821

wgengine/magicsock: fix synchronization of endpoint disco fields

---

wgengine/netstack/netstack.go

Running tailscaled with the race detector enabled immediately fires on this field, as it is updated after first read.

wgengine/netstack: fix data-race on startup

---

ipn/ipnlocal/peerapi.go

Makes it more apparent in the PeerAPI endpoint that the client was not built with the appropriate toolchain or build tags.

ipn/ipnlocal: more explicitly say if sockstats are not available

---

ipn/ipnlocal/c2n.go

Otherwise there may be a panic if it's nil (and the control side of the c2n call will just time out).

ipn/ipnlocal: check that sockstatLogger is available in c2n endpoint

---

client/tailscale/localclient.go

client/tailscale: dial LocalAPI at 127.0.0.1 on macOS

---

log/sockstatlog/logger.go

log/sockstatlog: limit sockstat logs to 5 MB

---

.github/workflows/test.yml
net/sockstats/sockstats_noop.go
net/sockstats/sockstats_tsgo.go
net/sockstats/sockstats_tsgo_test.go

We use it to gate code that depends on custom Go toolchain, but it's currently only passed in the corp runners. Add a set on OSS so that we can catch regressions earlier.
To specifically test `sockstats` this required adding a build tag to explicitly enable them -- they're normally on for iOS, macOS and Android only, and we don't run tests on those platforms normally.

.github/workflows: run one set of tests with the tailscale_go build tag

---

control/controlclient/auto.go
control/controlhttp/client.go
derp/derphttp/derphttp_client.go
logtail/logtail.go
net/dns/resolver/forwarder.go
net/netcheck/netcheck.go
net/portmapper/portmapper.go
net/sockstats/sockstats.go
net/sockstats/sockstats_noop.go
net/sockstats/sockstats_tsgo.go
wgengine/magicsock/magicsock.go

Using `log.Printf` may end up being printed out to the console, which is not desirable. I noticed this when I was investigating some client logs with `sockstats: trace "NetcheckClient" was overwritten by another`. That turns to be harmless/expected (the netcheck client will fall back to the DERP client in some cases, which does its own sockstats trace).
However, the log output could be visible to users if running the `tailscale netcheck` CLI command, which would be needlessly confusing.

net/sockstats: pass in logger to sockstats.WithSockStats

---

net/art/stride_table.go
net/art/stride_table_test.go
net/art/table.go
net/art/table_test.go

The benchmarks are a bit noisy and there are a lot of them, so the short version: the table works, it's reasonably fast but could be much faster, but I wanted to get the simple version merged first to establish a baseline to measure further improvements.
The table is reasonably fast for IPv4+6 on lookup (>10M lookups/sec). IPv4 insert/delete performance is okay (>400k routes/sec), and IPv6 is mediocre but usable (>50k routes/sec). This is due entirely to the lack of path compression, which forces IPv6 to have 4x longer tree paths and 4x more allocs than IPv4. Once path compression is implemented, the two address families should be much closer together again.
There is 1 IP address-sized allocation that is completely avoidable in all of the insert/delete/lookup paths, just because I'm using …

net/art: implement the Table type, a multi-level art route table.

---

cmd/tailscale/cli/netcheck.go
net/netcheck/netcheck.go
net/netcheck/netcheck_test.go
wgengine/magicsock/magicsock.go

This also adds a bunch of tests for this function to ensure that we're returning the proper IP(s) in all cases.
Change-Id: I0d9d57170dbab5f2bf07abdf78ecd17e0e635399

net/netcheck: use dnscache.Resolver when resolving DERP IPs

---

net/art/art_test.go

To get the tree green again for other people.
Updates #7866

net/art: skip tests on CI for now

---

api.md

example was missing the "-auth" type in the key prefix, which all new keys now contain.  Also update key ID to match the full key, and fix indenting of closing braces.

api.md: update example auth key value

---

.github/workflows/test.yml
ipn/ipnlocal/profiles_test.go
net/netcheck/netcheck_test.go
safesocket/basic_test.go
syncs/watchdog_test.go
wgengine/magicsock/magicsock_test.go

We accidentally switched to ./tool/go in
https://github.com/tailscale/tailscale/commit/4022796484db7f44f0a8598ed9a5d880d1a5b6ae which resulted in no longer
running Windows builds, as this is attempting to run a bash script.
I was unable to quickly fix the various tests that have regressed, so
instead I've added skips referencing https://github.com/tailscale/tailscale/issues/7876, which we need to back and
fix.
Updates https://github.com/tailscale/tailscale/pull/7262
Updates https://github.com/tailscale/tailscale/issues/7876

 .github/workflows: reenable Windows CI, disable broken tests 

---

util/set/slice.go
util/set/slice_test.go

This is an exact copy of the files misc/set/set{,_test}.go from https://github.com/tailscale/corp/commit/a5415daa9ca80ce9b798cd80148e4bc8818f8e15, plus the license headers.
For use in #7877
Change-Id: I712d09c6d1a180c6633abe3acf8feb59b27e2866

util/set: move Slice type from corp to oss

---

.github/workflows/test.yml

Go artifact caching will help provided that the cache remains small enough - we can reuse the strategy from the Windows build where we only cache and pull the zips, but let go(1) do the many-file unpacking as it does so faster.
The race matrix was building once without race, then running all the tests with race, so change the matrix to incldue a `buildflags` parameter and use that both in the build and test steps.

.github/workflows: add artifact caching and remove double build on race

---

tsnet/tsnet_test.go

This test is not regularly passing on CI, but seems to pass reliably locally. Needs deeper debugging.
Updates #7876

tsnet: disable TestLoopbackSOCKS5 on Windows

---

wgengine/magicsock/magicsock_test.go

These tests are passing locally and on CI. They had failed earlier in
the day when first fixing up CI, and it is not immediately clear why. I
have cycled IPv6 support locally, but this should not have a substantial
effect.
Updates #7876

wgengine/magicsock: reenable magicsock tests on Windows

---

net/netcheck/netcheck.go

net/netcheck: remove unused method from interface

---

net/netcheck/netcheck.go
types/nettype/nettype.go
wgengine/magicsock/magicsock.go

wgengine/magicsock, etc: remove mostly unused WriteTo methods

---

net/dns/resolver/forwarder.go
net/netcheck/netcheck.go
net/portmapper/portmapper.go
net/stun/stuntest/stuntest.go
tstest/natlab/natlab.go
types/nettype/nettype.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

So we're staying within the netip.Addr/AddrPort consistently and avoiding allocs/conversions to the legacy net addr types.
Updates #5162

wgengine/magicsock, types/nettype, etc: finish ReadFromUDPAddrPort netip migration

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

Previously, when updating endpoints we would immediately stop advertising any endpoint that wasn't discovered during `determineEndpoints`. This could result in, for example, a case where we performed an incremental netcheck, didn't get any of our three STUN packets back, and then dropped our STUN endpoint from the set of advertised endpoints... which would result in clients falling back to a DERP connection until the next call to `determineEndpoints`.
Instead, let's cache endpoints that we've discovered and continue reporting them to clients until a timeout expires. In the above case where we temporarily don't have a discovered STUN endpoint, we would continue reporting the old value, then re-discover the STUN endpoint again and continue reporting it as normal, so clients never see a …

wgengine/magicsock: keep advertising endpoints after we stop discovering them

---

cmd/tailscaled/tailscaled.go
control/controlclient/direct.go
control/controlhttp/client.go
ipn/ipnlocal/local.go
logpolicy/logpolicy.go
net/dnsfallback/dnsfallback.go
net/dnsfallback/dnsfallback_test.go
tsnet/tsnet.go

Redoes the approach from #5550 and #7539 to explicitly pass in the `logf` function, instead of having global state that can be overridden.

net/dnsfallback: more explicitly pass through logf function

---

net/interfaces/interfaces_bsd.go
net/netns/netns_darwin.go

It's somewhat common (e.g. when a phone has no reception), and leads to lots of logspam.
Updates #7850

net/netns: don't log errors when we can't get the default route on Darwin

---

net/sockstats/sockstats_tsgo.go
net/sockstats/sockstats_tsgo_test.go

When splitting the radio monitor usage array, we were splitting at `now % 3600` to get values into chronological order.  This caused the value for the final second to be included at the beginning of the ordered slice rather than the end.  If there was activity during that final second, an extra five seconds of high power usage would get recorded in some cases. This could result in a final calculation of greater than 100% usage.
This corrects that by splitting values at `(now+1) % 3600`.
This also simplifies the percentage calculation by always rounding values down, which is sufficient for our usage.

net/sockstats: fix calculation of radio power usage

---

ipn/ipnlocal/c2n.go
ipn/ipnlocal/peerapi.go
net/sockstats/sockstats.go
net/sockstats/sockstats_noop.go
net/sockstats/sockstats_tsgo.go
net/sockstats/sockstats_tsgo_test.go

Exposes some internal state of the sockstats package via the C2N and PeerAPI endpoints, so that it can be used for debugging. For now this includes the estimated radio on percentage and a second-by-second view of the times the radio was active.
Also fixes another off-by-one error in the radio on percentage that was leading to >100% values (if n seconds have passed since we started to monitor, there may be n + 1 possible seconds where the radio could have been on).

net/sockstats: expose debug info

---

ipn/ipnlocal/peerapi.go
net/tsdial/tsdial.go
tstest/integration/integration_test.go

Without this, the peer fails to do anything over the PeerAPI if it
has a masquerade address.
```
Apr 19 13:58:15 hydrogen tailscaled[6696]: peerapi: invalid request from <ip>:58334: 100.64.0.1/32 not found in self addresses
```
Updates #8020

ipn/ipnlocal: handle masquerade addresses in PeerAPI

---

.golangci.yml
cmd/k8s-operator/operator_test.go
cmd/tailscale/cli/netcheck.go
hostinfo/hostinfo.go
ipn/ipnlocal/expiry_test.go
ipn/ipnlocal/local.go
ipn/ipnlocal/serve.go
net/dns/resolver/tsdns_test.go
wgengine/magicsock/magicsock.go

This is a follow-up to #7905 that adds two more linters and fixes the corresponding findings. As per the previous PR, this only flags things that are "obviously" wrong, and contains one commit per issue category fixed.
I intend to squash this into a single commit when merging.

ci: add more lints

---

syncs/watchdog_test.go

The test is re-enabled for Windows with a relaxed time assertion.
On Windows the runtime poller currently does not have sufficient
resolution to meet the normal requirements for this test.
See https://github.com/golang/go/issues/44343 for background.
Updates https://github.com/tailscale/tailscale/issues/7876

syncs: relax TestWatchMultipleValues timing on Windows

---

safesocket/basic_test.go
safesocket/pipe_windows.go
safesocket/pipe_windows_test.go

I manually tested that the code path that relaxes pipe permissions is not executed when run with elevated priviliges, and the test also passes in that case.
Updates #7876

safesocket: enable test to run on Windows unpriviliged

---

log/sockstatlog/logger.go

We are seeing indications that some devices are still getting into an upload loop.  Bump logInterval in case these devices are on slow connections that are taking more than 3 seconds to uploads sockstats.
Updates #7719

log/sockstatlog: bump logInterval to 10 seconds

---

tailcfg/derpmap.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

A follow-up PR will start using this field after we set it in our production DERPMap.
Updates #7925
Change-Id: Idb41b79e6055dddb8944f79d91ad4a186ace98c7

tailcfg: add CanPort80 field to DERPNode

---

ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

This adds support to try dialing out to multiple recorders each
with a 5s timeout and an overall 30s timeout. It also starts respecting
the actions `OnRecordingFailure` field if set, if it is not set
it fails open.
Updates https://github.com/tailscale/corp/issues/9967

ssh/tailssh: handle dialing multiple recorders and failing open 

---

net/netcheck/netcheck.go

Looks like on some systems there's an IPv6 address, but then opening a IPv6 UDP socket fails later. Probably some firewall. Tolerate it better and don't crash.
To repro: check the "udp6" to something like "udp7" (something that'll fail) and run "go run ./cmd/tailscale netcheck" on a machine with active IPv6. It used to crash and now it doesn't.
Fixes #7949

net/netcheck: fix crash when IPv6 kinda but not really works

---

.github/workflows/test.yml

Benchmark flags prevent test caching, so benchmarks are now executed
independently of tests.
Fixes https://github.com/tailscale/tailscale/issues/7975

.github/workflows: split tests and benchmarks for caching

---

ipn/ipnlocal/local.go

It was printing like "v0xxxxxxxx" after version.Long became a func in 8b2ae47c31c9574d.
Fixes #7976

ipn/ipnlocal: fix fmt format arg type mismatch in log line

---

cmd/derper/cert.go

The Go DERP client doesn't support HTTP/2. If an HTTP/2 proxy was placed in front of a DERP server requests will fail.
It wasn't clear to me why this was enabled, and it felt inappropriate to add HTTP/2 support to all of DERP.

cmd/derper: disable http2

---

.github/workflows/test.yml

The action cache restore process either matches the restore key pattern
exactly, or uses a matching prefix with the most recent date.
If the restore key is an exact match, then no updates are uploaded, but
if we've just computed tests executions for more recent code then we
will likely want to use those results in future runs.
Appending run_id to the cache key will give us an always new key, and
then we will be restore a recently uploaded cache that is more likely
has a higher overlap with the code being tested.
Updates https://github.com/tailscale/tailscale/issues/7975

.github/workflows: add recency bias to action cache keys

---

build_dist.sh

I'm using tailscale on an openwrt device. Openwrt has its own toolchains so i have to specify `CC` env to openwrt toolchains gcc instead of the one of my host os.
However, `build_dist.sh` runs a `$go run ./cmd/mkversion` and it will fail when `CC` is specified.
I review the logic of mkversion and found it can be run using `CGO_ENABLED=0` to avoid `CC` modification.

build_dist.sh: make cross-compilation friendly for env CC specified

---

syncs/syncs.go

I need this for a corp change where I have a set as a queue, and make a different decisison if the set is empty.
Updates tailscale/corp#10344

syncs: add Map.Len to get the length of the Map

---

.github/workflows/installer.yml
scripts/installer.sh

Every time we change `installer.sh`, run it in a few docker containers based on different Linux distros, just as a simple test.
Also includes a few changes to the installer script itself to make installation work in Docker:
- install `dnf config-manager` command before running it
- run `zypper` in non-interactive mode
- update `pacman` indexes before installing packages
Updates https://github.com/tailscale/corp/issues/8952

.github: test installer script in CI in docker

---

control/controlclient/direct.go
control/controlclient/noise.go
control/controlclient/noise_test.go
control/controlhttp/client.go
control/controlhttp/constants.go

This passes the *dnscache.Resolver down from the Direct client into the Noise client and from there into the controlhttp client. This retains the Resolver so that it can share state across calls instead of creating a new resolver.
Updates https://github.com/tailscale/tailscale/issues/4845
Updates https://github.com/tailscale/tailscale/issues/6110
Change-Id: Ia5d6af1870f3b5b5d7dd5685d775dcf300aec7af

control/controlclient: use dnscache.Resolver for Noise client

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

Avoid selecting an endpoint as "better" than the current endpoint if the total latency improvement is less than 1%. This adds some hysteresis to avoid flapping between endpoints for a minimal improvement in latency.
Change-Id: If8312e1768ea65c4b4d4e13d8de284b3825d7a73

wgengine/magicsock: add hysteresis to endpoint selection

---

wgengine/magicsock/magicsock_test.go

wgengine/magicsock: annotate, skip flaky TestIsWireGuardOnlyPickEndpointByPing

---

scripts/installer.sh

Installer script relies on pkgs.tailscale.com being reachable, both for checking what Linux distros are supported, but also for actually downloading repo configuration files, gpg keys and packages themselves.
This change adds a simple reachability check which will print an error message when pkgs.tailscale.com is not reachable.
Fixes https://github.com/tailscale/corp/issues/8952

scripts/installer.sh: check connectivity with pkgs.tailscale.com

---

cmd/tailscale/cli/diag.go
cmd/tailscaled/taildrop.go
hostinfo/hostinfo_linux.go
ipn/ipnlocal/peerapi.go
version/distro/distro.go

The community Unraid plugin currently has to "simulate" being a QNAP NAS in order for Taildrop to use the NAS-style functionality (i.e., placing taildropped files directly into a folder on the device). This change adds Unraid as a detected distro and enables direct file mode.
Closes #8025

various: add Unraid detection and direct Taildrop support

---

ipn/ipnlocal/local.go
ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go
tailcfg/tailcfg.go

This change sends an SSHEventNotificationRequest over noise when a
SSH session is set to fail closed and the session is unable to start
because a recorder is not available or a session is terminated because
connection to the recorder is ended. Each of these scenarios have their
own event type.

 ssh/tailssh: send ssh event notifications on recording failures 

---

tsweb/promvarz/promvarz_test.go

expvar can only be defined once, so running tests with a repeat counter will fail if the variables are defined inside of the test function.
Observed failure:
```
--- FAIL: TestHandler (0.00s)
panic: Reuse of exported var name: gauge_promvarz_test_expvar
[recovered]
panic: Reuse of exported var name: gauge_promvarz_test_expvar
goroutine 9 [running]:
testing.tRunner.func1.2({0x100f267e0, 0x1400026e770})
/usr/local/go/src/testing/testing.go:1526 +0x1c8
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1529 +0x364
panic({0x100f267e0, 0x1400026e770})
/usr/local/go/src/runtime/panic.go:884 +0x1f4
log.Panicln({0x140000b8e20?, 0x1a?, 0x1400026e750?})
/usr/local/go/src/log/log.go:398 +0x60
expvar.Publish({0x100e2b21d, 0x1a}, {0x100fd7a08?, 0x140000232c0}) …
```

tsweb/promvarz: fix repeated expvar definition in test

---

cmd/tailscaled/tailscaled.go

Signed-off-by: Chenyang Gao <gps949@outlook.com>
in commit 6e96744, the tsd system type has been added. Which will cause the daemon will crash on some  OSs (Windows, darwin and so on). The root cause is that on those OSs, handleSubnetsInNetstack() will return true and set the conf.Router with a wrapper.  Later in NewUserspaceEngine() it will do subsystem set and found that early set router mismatch to current value, then panic.

fix sys.Set(router) issue will crash the daemon in some OSs

---

version/version.go

Current code will set the "dirty" field of VersionInfo always "true" if vcs.modified flag is there. No matter whether the flag is "true" or "false".  It will make sense to set this field due to vcs.modified value, not only the existence of the key.

version: properly handle vcs.modified when it's "false"

---

cmd/viewer/tests/tests.go
cmd/viewer/tests/tests_clone.go
cmd/viewer/tests/tests_view.go
util/codegen/codegen.go

I noticed cmd/{cloner,viewer} didn't support structs with embedded fields while working on a change in another repo. This adds support.

util/codegen: support embedded fields

---

tool/gocross/gocross-wrapper.sh

The subshell in which gocross gets built cd's to the corp checkout dir near the top, so all future references to corp repository files should be simple relative paths, and not reference $repo_root. When $repo_root is an absolute path, it doesn't matter and everything works out, but on some OSes and shells and invocations, $repo_root is a completely relative path that is invalidated by the "cd".
Fixes tailscale/corp#11183
---
Woops, fixed this bug in the wrong repo, so our repo sync logic reverted it. Fixing in the right place this time.

tool/gocross: fix incorrect relpath usage in bootstrap script

---

tsnet/tsnet_test.go

This test was either fixed in the intermediate time or mis-flagged during the #7876 triage, but is now passing.
Updates #7876

tsnet: reenable TestLoopbackSOCKS5 on Windows

---

net/netcheck/netcheck_test.go

This test was either fixed by intermediate changes or was mis-flagged as failing during #7876 triage.
Updates #7876

net/netcheck: reenable TestBasic on Windows

---

util/set/set.go
util/set/set_test.go

We have two other types of Sets here. Add the basic obvious one too.
Needed for a change elsewhere.

util/set: add a basic map-based Set type

---

cmd/k8s-operator/operator.go

getSingleObject can return `nil, nil`, getDeviceInfo was not handling that case which resulted in panics.
Fixes #7303

cmd/k8s-operator: handle NotFound secrets

---

client/tailscale/keys.go
cmd/get-authkey/main.go
cmd/k8s-operator/operator.go
cmd/k8s-operator/operator_test.go

Adds a parameter for create key that allows a number of seconds (less than 90) to be specified for new keys. 
Closes #7965 
Signed-off-by: Matthew Brown <matthew@bargrove.com>

Allow the expiry time to be specified for new keys

---

cmd/tailscale/cli/up.go

cmd/tailscale/cli: [up] fix CreateKey missing argument

---

client/tailscale/keys.go
cmd/get-authkey/main.go
cmd/k8s-operator/operator.go
cmd/k8s-operator/operator_test.go
cmd/tailscale/cli/up.go

The client/tailscale is a stable-ish API we try not to break. Revert the Client.CreateKey method as it was and add a new CreateKeyWithExpiry method to do the new thing. And document the expiry field and enforce that the time.Duration can't be between in range greater than 0 and less than a second.
Updates #7143
Updates #8124 (reverts it, effectively)

client/tailscale: revert CreateKey API change, add Client.CreateKeyWithExpiry

---

cmd/tailscale/cli/web.go
cmd/tailscale/cli/web.html

This change allows the Tailscale web interface to be embedded within the Unraid web UI.
Specifically:
- Adds the CSRF token that Unraid requires for all incoming POSTs to the web UI
- Opens authentication pages in a new window (otherwise, security errors occur in the browser)
Closes #8026

cmd/tailscale: allow Tailscale to work with Unraid web interface

---

ssh/tailssh/tailssh_test.go
ssh/tailssh/user.go

58ab66ec51f1963fbee302c75ad0017d81d37884 added LDAP support for #4945 by shelling out to getdent.
It was supposed to fall back to the old method when getdent wasn't found, but some variable name confusion (uid vs username) meant the old path wasn't calling the right lookup function (user.LookupId instead of user.Lookup).
Which meant that changed probably also broke FreeBSD and macOS SSH support in addition to the reported OpenWRT regression.
The gokrazy support didn't look right either.
Fixes #8180

ssh/tailssh: fix regression after LDAP support

---

api.md

The authorize device API (/api/v2/device/{deviceID}/authorized) now allows device deauthorisation.
Updates tailscale/corp#10160.

api.md: update device authorized API docs to allow for deauth

---

ssh/tailssh/tailssh.go
tailcfg/tailcfg.go

This change introduces a SSHSessionRecordingFailed event type that is used when a session recording fails to start or fails during a session, and the on failure indicates that it should fail open.

ssh/tailssh: add ssh session recording failed event type

---

portlist/netstat.go
portlist/netstat_test.go
portlist/poller.go
portlist/portlist.go
portlist/portlist_linux.go
portlist/portlist_linux_test.go
portlist/portlist_macos.go
portlist/portlist_test.go
portlist/portlist_windows.go

This PR parameterizes receiving loopback updates from the portlist package.
Note that the functional-options pattern was used to avoid breaking changes.
Fixes https://github.com/tailscale/tailscale/issues/8171
Note: tested on mac/linux but have not had the chance to work on the windows part yet. Happy to do so in this PR or as a follow up.

portlist: add Poller.IncludeLocalhost option

---

release/dist/cli/cli.go

Some builders return absolute paths to build products already. When that happens, the manifest writing logic shouldn't tack on another absolute prefix.

release/dist/cli: correctly handle absolute build outputs in manifest

---

wgengine/netstack/netstack.go

Various BSD-derived operating systems including macOS and FreeBSD require that ping6 be used for IPv6 destinations. The "ping" command does not understand an IPv6 destination.
FreeBSD 13.x and later do handle IPv6 in the regular ping command, but also retain a ping6 command. We use ping6 on all versions of FreeBSD.
Fixes https://github.com/tailscale/tailscale/issues/8225

wgengine/netstack: use ping6 on BSD platforms

---

release/dist/synology/targets.go

This platform is technically an armv7, but has no hardware floating point unit. armv5 is the only target Go understands to lack floating point, so use that.
Updates #6860

release/dist/synology: build hi3535 as armv5, not armv7

---

client/tailscale/devices.go

This adds a new `SetAuthorized` method that allows setting device authorization to true or false. I chose the method name to be consistent with `SetTags`.
Updates https://github.com/tailscale/corp/issues/10160

client/tailscale: support deauthorizing a device

---

ipn/ipnlocal/serve.go

This replicates the headers also sent by the golang reverse proxy by default (see the [recent commit](https://github.com/golang/go/commit/1513e57b704056b794f0706362fa3c949f2972a4)). Some applications depend on these headers to generate redirects or links correctly.
I verified this change by building the tool locally on my Mac, running an echo server and serving that via the locally built tailscale CLI. I then used my phone in the same tailnet to access this, verifying that the returned headers included both X-Forwarded-Host and X-Forwarded-Proto.
I need this change to continue with my personal Tailscale use case, so I'd be happy to see this get merged. Happy to adjust as needed, just let me know.
Fixes #7061.

ipn/ipnlocal: [serve/funnel] add forwarded host and proto header

---

ipn/localapi/localapi.go

Allow calls to `WatchIPNBus` to be permformed by clients with Readonly permissions. This brings it in line with the permissions required for `Status`, which also exposes the similar information.
This allows clients to get realtime updates about the tailnet in their own applications, without needing to actively poll the `Status` endpoint.
Fixes https://github.com/tailscale/tailscale/issues/7797

ipn/localapi: require only read permission for WatchIPNBus

---

build_dist.sh

The invocation at the end unconditionally used
./tool/go, but the structuring on lines 14-17
sets up to use a different toolchain if the
platform requires it.
Fixes https://github.com/tailscale/tailscale/issues/8156

build_dist.sh: use $go consistently.

---

ssh/tailssh/user.go

Max username length is increased to 256 on linux to match /usr/include/bits/local_lim.h
Fixes #8277
Signed-off-by: Derek Burdick <derek-burdick@users.noreply.github.com>

ssh/tailssh: Max Username Length 256 for linux

---

ipn/ipnlocal/local.go
portlist/poller.go
portlist/portlist_test.go

This is a follow up on PR #8172 that adds a synchronous Poll method which allows for the Poller to be used as a zero value without needing the constructor. The local backend is also changed to use the new API. A follow up PR will remove the async functionality from the portlist package.
Updates #8171

portlist: add a synchronous Poll method

---

tsnet/tsnet.go

Followup from a conversation on the Gophers slack, also matches the examples in [the tsnet kb](https://tailscale.com/kb/1244/tsnet/#serverdir).
Closes #8287

tsnet: document how to use Dir with multiple servers per process

---

tool/gocross/autoflags.go

First step to start working on #8282. This is needed in order to build our network extension on tvOS.

tool/gocross: handle TVOS_DEPLOYMENT_TARGET

---

portlist/poller.go
portlist/portlist_test.go

This PR removes all async functionality from the portlist package which may be a breaking change for non-tailscale importers. The only importer within this codebase (LocalBackend) is already using the synchronous API so no further action needed.
Fixes #8171

portlist: remove async functionality

---

ipn/ipnstate/ipnstate.go
version/prop.go

Another change supporting #8282. This makes the client report 'tvOS' as the OS name in tailcfg.Hostinfo when we are running within the tvOS network extension. This way, the login flow and admin panel show tvOS instead of iOS.

version: detect tvOS by checking XPC_SERVICE_NAME

---

ssh/tailssh/tailssh.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

This basically allows running services on the SSH client and reaching them from the SSH server during the session.
Updates #6575

ssh/tailssh: add support for remote/reverse port forwarding

---

net/dns/recursive/recursive.go
net/dns/recursive/recursive_test.go

We've talked in the past about reworking how bootstrap DNS works to instead do recursive DNS resolution from the root; this would better support on-prem customers and Headscale users where the DERP servers don't currently resolve their DNS name. This package is an initial implementation of recursive resolution for A and AAAA records.
Updates #5853
Change-Id: Ibe974d78709b4b03674b47c4ef61f9a00addf8b4

net/dns/recursive: add initial implementation of recursive DNS resolver

---

ipn/ipnlocal/network-lock.go
ipn/localapi/localapi.go
tka/deeplink.go

Provides a local API endpoint to verify a `sign-device` deeplink, which can be scanned using the mobile/desktop apps to sign a device for Tailnet lock.
Fixes https://github.com/tailscale/tailscale/issues/8302

tka: provide verify-deeplink local API endpoint

---

tka/deeplink.go
tka/deeplink_test.go

This commit continues the work from #8303, providing a method for a tka.Authority to generate valid deeplinks for signing devices. We'll use this to provide the necessary deeplinks for users to sign from their mobile devices.
Updates #8302
/cc @agottardo

tka: add function for generating signing deeplinks

---

hostinfo/hostinfo.go
ipn/ipnlocal/local.go
ssh/tailssh/incubator.go

Trying to SSH when SELinux is enforced results in errors like:
```
➜  ~ ssh ec2-user@<ip>
Last login: Thu Jun  1 22:51:44 from <ip2>
ec2-user: no shell: Permission denied
Connection to <ip> closed.
```
while the `/var/log/audit/audit.log` has
```
type=AVC msg=audit(1685661291.067:465): avc:  denied  { transition } for  pid=5296 comm="login" path="/usr/bin/bash" dev="nvme0n1p1" ino=2564 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_t:s0 tclass=process permissive=0
```
The right fix here would be to somehow install the appropriate context when tailscale is installed on host, but until we figure out a way to do that stop using the `login` cmd in these situations.
Updates #4908

ssh/tailssh: work around lack of scontext in SELinux

---

prober/derp.go

prober uses NewRegionClient() to connect to a derper using a faked up single-node region, but NewRegionClient() fails to connect if there is no non-STUN only client in the region. Set the STUN only flag to false before we call NewRegionClient() so we can monitor nodes marked as STUN only in the default derpmap.
Updates #11492

prober: allow monitoring of nodes marked as STUN only in default derpmap

---

ipn/ipnlocal/serve.go
ipn/ipnlocal/serve_test.go

Adds a `Tailscale-Headers-Info` header whenever the `Tailscale-User-` headers are filled from the HTTP proxy handler.
Planning on hooking this shorturl up to KB docs about the header values (i.e. what's a login name vs. display name) and security considerations to keep in mind while using these headers - notibly that they can also be filled from external requests that do not hit tailscaled.
Updates https://github.com/tailscale/tailscale/issues/6954

ipn/ipnlocal: add docs header to serve HTTP proxy

---

ssh/tailssh/incubator.go

Leave cmd.Dir empty, which should configure spawned process to use working directory of existing process.
When a user logs in, their directory is set based on shell semantics and is not related to the working directory of 'tailscaled ssh' command, based on my testing.
Fixes #8118
Related to pull #4945

Do not set cmd.Dir when spawning tailscaled ssh command

---

prober/derp.go

Move the clearing of STUNOnly flag to the updateMap() function.
Fixes #8395

prober: fix data race when altering derpmap

---

ssh/tailssh/incubator.go
ssh/tailssh/tailssh.go
ssh/tailssh/tailssh_test.go

There are two race conditions in output handling.
The first race condition is due to a misuse of exec.Cmd.StdoutPipe. The documentation explicitly forbids concurrent use of StdoutPipe with exec.Cmd.Wait (see golang/go#60908) because Wait will close both sides of the pipe once the process ends without any guarantees that all data has been read from the pipe. To fix this, we allocate the os.Pipes ourselves and manage cleanup ourselves when the process has ended.
The second race condition is because sshSession.run waits upon exec.Cmd to finish and then immediately proceeds to call ss.Exit, which will close all output streams going to the SSH client. This may interrupt any asynchronous io.Copy still copying data. To fix this, we close the write-side of the os.Pipes after the process has …

ssh/tailssh: fix double race condition with non-pty command

---

control/controlclient/debug.go
ipn/ipnlocal/c2n.go
util/goroutines/goroutines.go
util/goroutines/goroutines_test.go

ScrubbedGoroutineDump previously only returned the stacks of all goroutines. I also want to be able to use this for only the current goroutine's stack. Add a bool param to support both ways.
Updates tailscale/corp#5149

util/goroutines: let ScrubbedGoroutineDump get only current stack

---

release/dist/synology/files/config
release/dist/synology/pkgs.go

As far as I can tell from the DSM documentation and known undocumented fields, there is no 'version' field in this config file that DSM cares about.
Updates #8232

release/dist/synology: remove 'version' field from ui/config

---

tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go

This change adds Location and ExitNodePriority fields to HostInfo. Location contains the option for a Country and a City. Neither of these fields are populated by default.
The ExitNodePriority field is used to determine the priority an exit node should be given for use, if the field is set. The higher the value set, the higher priority the node should be given for use.

tailcfg: add location field to hostinfo

---

hostinfo/hostinfo.go

Instead of treating any lxcfs mount as an indicator that we're running in a container, check for one of the mounts actually used by LXC containers.
For reference, here's a list of mounts I am seeing in an LXC container:
```
$ grep lxcfs /proc/mounts
lxcfs /proc/cpuinfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/diskstats fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/loadavg fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/meminfo fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/stat fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
lxcfs /proc/swaps fuse.lxcfs …
```

hostinfo: make lxcfs container check more specific

---

.github/workflows/test.yml
cmd/testwrapper/flakytest/flakytest.go
cmd/testwrapper/flakytest/flakytest_test.go
cmd/testwrapper/testwrapper.go

Redo the testwrapper to track and only retry flaky tests instead
of retrying the entire pkg. It also fails early if a non-flaky test fails.
This also makes it so that the go test caches are used.
Fixes https://github.com/tailscale/tailscale/issues/8438

cmd/testwrapper: only retry flaky failed tests

---

ipn/localapi/localapi.go

Correct a minor cut-n-paste error that resulted in an invalid or missing ping type being accepted as a disco ping.
Fixes #8457

ipn/ipnlocal: validate ping type

---

net/netutil/ip_forward.go

This commit updates our IP forwarding parsing logic to allow the less common but still valid value of `2` to be parsed as `true`, which fixes an error some users encountered.
Fixes #8375

net/netutil: parse IP forwarding val as int, not bool

---

cmd/tailscale/cli/network-lock.go

Not sure exactly what help / suggestion text we should have, but coming up with a consise way to say use a device with a trusted tailnet lock key is hard.
Also @agottardo should we add something like this in MacOS/iOS?

cmd/tailscale: improve error message when signing without a tailnet lock key

---

tstest/log.go

The panicLogWriter is too strict, and any panics that occur get wrapped up in quotes. This makes it so that it will allow panics to continue writing to Stderr without going through logger.Logf.

tstest: do not panic when a panic logs

---

tstime/mono/mono.go
tstime/mono/mono_test.go

Calling both mono.Now() and time.Now() is slow and leads to unnecessary precision errors.
Instead, directly compute mono.Time relative to baseMono and baseWall. This is the opposite calculation as mono.Time.WallTime.
Updates tailscale/corp#8427

tstime/mono: fix Time.Unmarshal

---

tsweb/varz/varz.go
tsweb/varz/varz_test.go

To not break Prometheus if the label is unset.
Updates tailscale/corp#12830

tsweb/varz: use default metrics.LabelMap.Label on serialization

---

tsnet/tsnet_test.go
util/linuxfw/iptables.go
util/linuxfw/linuxfw_struct_linux_test.go
util/linuxfw/linuxfw_unsupported.go
util/linuxfw/nftables.go
util/linuxfw/nftables_types.go

Exclide GOARCHs including: mips, mips64, mips64le, mipsle, riscv64. These archs are not supported by gvisor.dev/gvisor/pkg/hostarch.
Updates: #391, #8502
The `gvisor` dependency only supports arm64 and x86 architectures. So we should not include relative files in build when we are on other archs, and include the linuxfw_unsupported file in the build. 
Notice that only `iptables.go` is referencing `gvisor` so technically we only need to exclude `iptables.go` from build. Tho all these files are not really used to we can exclude them just to be safe.

util/linuxfw: add new arch build constraints

---

docs/k8s/Makefile
docs/k8s/README.md

Instead of calling kubectl directly in k8s Makefile, write the yaml to stdout so it can be reviewed/edited/etc before manually applying with kubectl.
Docs can be updated to, ex, `make subnet-router | kubectl apply -f -` so they can continue to work with "one click".
Fixes: https://github.com/tailscale/tailscale/issues/8511
Ping: @maisem

docs/k8s: don't call kubectl directly from Makefile

---

client/tailscale/localclient.go

client/tailscale: add API for verifying network lock signing deeplink

---

net/dns/recursive/recursive_test.go
net/dnscache/messagecache_test.go
tstest/clock.go
tsweb/tsweb_test.go

This change introduces tstime.NewClock and tstime.ClockOpts as a new way to construct tstime.Clock. This is a subset of #8464 as a stepping stone so that we can update our internal code to use the new API before making the second round of changes.
Updates #8463
Change-Id: Ib26edb60e5355802aeca83ed60e4fdf806c90e27

tstest: prepare for Clock API changes

---

version/prop.go

Fixes #8544. Updates #8282.
We renamed the tvOS network extension bundle identifier to io.tailscale.ipn.ios.network-extension-tvos from io.tailscale.ipn.tvos.network-extension to allow for a shared App Store submission between iOS and tvOS.
Need to adjust this in [version/prop.go](https://github.com/tailscale/tailscale/blob/cd4c71c1225aa6703b0766d1cde6b34c67a87dd6/version/prop.go#L91).

version: fix tvOS network extension bundle identifier

---

tstest/clock.go
tstest/clock_test.go
tstime/tstime.go

This change introduces tstime.Clock which is the start of a mockable interface for use with testing other upcoming code changes.
Fixes #8463
cc @bradfitz and @maisem in case you have opinions
This should not be merged until a corresponding update to `corp` is ready to go because it changes how a `tstest.Clock` is created.

tstest, tstime: mockable timers and tickers

---

control/controlclient/noise.go

Without this, the client would just get stuck dialing even if the context was canceled.
Updates tailscale/corp#12590

control/controlclient: use ctx passed down to NoiseClient.getConn

---

wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

This change removes the noV4/noV6 check from addrForSendWireGuardLocked.
On Android, the client panics when reaching	`rand.Intn()`, likely due to the candidates list being containing no candidates. The suspicion is that the `noV4` and the `noV6` are both being triggered causing the loop to continue.
Updates tailscale/corp#12938

wgengine/magicsock: remove noV4/noV6 check in addrForSendWireGuardLocked

---

tsnet/tsnet_test.go

Test flaked in CI.
Updates  #8557

tsnet: mark TestLoopbackLocalAPI as flakey

---

tailcfg/tailcfg.go

We were storing a lot of `"ExitNodeFilteredSet":null` in the database.
Updates tailscale/corp#1818 (found in the process)

tailcfg: add json omitempty to DNSConfig.ExitNodeFilteredSet

---

cmd/tailscaled/tailscaled.go
ipn/ipnserver/proxyconnect.go
log/sockstatlog/logger.go
logpolicy/logpolicy.go
tsnet/tsnet.go
wgengine/netlog/logger.go

This allows sending logs from the "logpolicy" package (and associated callees) to something other than the log package. The behaviour for tailscaled remains the same, passing in log.Printf
Updates #8249
Change-Id: Ie1d43b75fa7281933d9225bffd388462c08a5f31

logpolicy, various: allow overriding log function

---

cmd/derper/derper.go
tsweb/debug.go
tsweb/tsweb.go

This is one of generic HTTP hardening headers (for XSS) that has no impact on real usage. Doesn't do much for derper, but makes security scanners happy.

cmd/derper: add X-Content-Type-Options: nosniff

---

cmd/tailscale/cli/up.go

We've had support for OAuth client keys in `--authkey=...` for several releases, and we're using it in
https://github.com/tailscale/github-action
Remove the TS_EXPERIMENT_* guardrail, it is fully supported now.
Fixes https://github.com/tailscale/tailscale/issues/8403

cmd/tailscale: remove TS_EXPERIMENT_OAUTH_AUTHKEY guardrail

---

control/controlclient/map.go
control/controlclient/map_test.go
net/netcheck/netcheck.go
net/netcheck/netcheck_test.go
tailcfg/derpmap.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

This allows providing additional information to the client about how to
select a home DERP region, such as preferring a given DERP region over
all others.
Updates https://github.com/tailscale/tailscale/issues/8603
Change-Id: Ic6bfe1122ef41fffbe96aae4be3a8f9e7cd9d514

net/netcheck, tailcfg: add DERPHomeParams and use it

---

control/controlclient/auto.go
control/controlclient/direct.go

We were never resetting the backoff in streaming mapResponses. The call to `PollNetMap` always returns with an error. Changing that contract is harder, so manually reset backoff when a netmap is received.
Updates tailscale/corp#12894

control/controlclient: reset backoff in mapRoutine on netmap recv

---

cmd/tailscale/cli/serve.go
ipn/ipnlocal/serve.go

When using a custom http port like 8080, this was resulting in a constructed hostname of `host.tailnet.ts.net:8080.tailnet.ts.net` when looking up the serve handler. Instead, strip off the port before adding the MagicDNS suffix.
Also use the actual hostname in `serve status` rather than the literal string "host".
Fixes #8635

serve: fix hostname for custom http ports

---

net/netcheck/netcheck.go
net/netcheck/netcheck_test.go

If the absolute value of the difference between the current PreferredDERP's latency and the best latency is <= 10ms, don't change it and instead prefer the previous value.
This is in addition to the existing hysteresis that tries to remain on the previous DERP region if the relative improvement is small, but handles nodes that have low latency to >1 DERP region better.
Updates #8603
Change-Id: I1e34c94178f8c9a68a69921c5bc0227337514c70

net/netcheck: ignore PreferredDERP changes that are small

---

wgengine/router/callback.go
wgengine/router/router.go
wgengine/router/router_test.go

The MacOS client can't set the MTU when creating the tun due to lack of permissions, so add it to the router config and have MacOS set it in the callback using a method that it does have permissions for.
Updates #8219

wgengine/router,ipn/ipnlocal: add MTU field to router config

---

client/tailscale/acl.go
cmd/gitops-pusher/gitops-pusher.go
cmd/gitops-pusher/gitops-pusher_test.go

This changes the ACLTestError type to reuse the existing/identical types from the ACL implementation, to avoid issues in the future if the two types fall out of sync.

cmd/gitops-pusher: re-use existing types from acl package

---

tsweb/debug.go
tsweb/tsweb.go

Allow inline CSS for debug handlers to make prototyping easier. These are generally not accessible to the public and the small risk of CSS injection via user content seems acceptable.
Also allow form submissions on the same domain, instead of banning all forms. An example of such form is
http://webhooks.corp.ts.net:6359/debug/private-nodes/
Updates #3576

tsweb: relax CSP for debug handlers

---

tka/key.go
tka/sig.go

In late 2022 a subtle but crucial part of documentation was added to ed25519.Verify: It will panic if len(publicKey) is not [PublicKeySize].
https://cs.opensource.google/go/go/+/02ed0e5e67530e6b041989d55048ce373dc60327
This change catches that error so it won't lead to a panic.
Updates https://github.com/tailscale/corp/issues/8568

tka: guard against key-length panics when verifying signatures

---

cmd/tailscale/cli/update.go
cmd/tailscale/cli/update_test.go

Even on macOS when Tailscale was installed via the App Store, we can check for
and even install new versions if people ask explicitly. Also, warn if App Store
AutoUpdate is not turned on.
Updates #6995
Signed-off-by: Chris Palmer <cpalmer@tailscale.com>

cmd/tailscale/cli: make `tailscale update` query `softwareupdate`

---

cmd/tailscale/cli/update.go
cmd/tailscale/cli/update_test.go

Arch version of tailscale is not maintained by us, but is generally up-to-date with our releases. Therefore "tailscale update" is just a thin wrapper around "pacman -Sy tailscale" with different flags.
Updates #6995

cmd/tailscale/cli: implement update for arch-based distros

---

net/dns/manager_linux.go
net/dns/manager_linux_test.go

Having `127.0.0.53` is not the only way to use `systemd-resolved`. An alternative way is to enable `libnss_resolve` module, which seems to now be used by default on Debian 12 bookworm.
Fixes #8549

net/dns: detect when libnss_resolve is used

---

cmd/tailscale/cli/update.go

Hide the `-app-store` option with `HIDDEN: `.
Updates #6995

cmd/tailscale/cli: limit Darwin-only option to Darwin

---

ssh/tailssh/incubator.go

If the connection provided to sftp.NewServer is closed, Serve returns the io.EOF error verbatim from io.Reader.Read. This is an odd error since this is an expected situation, so we manually ignore io.EOF.
This is somewhat buggy since the sftp package itself incorrectly reports io.EOF in cases where it should actually be reporting io.ErrUnexpectedEOF.
See https://github.com/pkg/sftp/pull/554 which patches Serve to return nil on clean closes and fixes buggy uses of io.ReadFull.
Fixes #8592

ssh: ignore io.EOF from sftp.Server.Serve

---

net/dns/direct.go
net/dns/resolvconfpath_default.go
net/dns/resolvconfpath_gokrazy.go

Appliances built using https://gokrazy.org/ have a read-only root file system, including /etc/resolv.conf, which is a symlink to /tmp/resolv.conf.
The system’s dhcp client overwrites /tmp/resolv.conf instead, so we need to use this path in Tailscale, too.
An alternative would have been to make the code follow symlinks when handling /etc/resolv.conf, but this fix feels a little simpler — less potential to break something and less code complexity.
related to https://github.com/gokrazy/gokrazy/issues/209

net/dns: overwrite /tmp/resolv.conf on gokrazy

---

cmd/tailscale/cli/update.go
cmd/tailscale/cli/update_test.go

This is the Fedora family of distros, including CentOS, RHEL and others. Tested in `fedora:latest` and `centos:7` containers.

cmd/tailscale/cli: implement update for dnf/yum-based distros

---

net/art/art_test.go
net/art/stride_table.go
net/art/stride_table_test.go
net/art/table.go
net/art/table_test.go

Several individual changes. Commits 2 and 3 are the meat of the optimization's implementation, the rest are small fixups and lots of tests.
This implementation currently passes all tests with -count=1000 reliably, so this _appears_ to be correct code. I still need to run benchmarks again, I'll post those in a comment later.

net/art: implement the path compression optimization

---

cmd/tailscale/cli/update.go
cmd/tailscale/cli/update_test.go
version/distro/distro.go

Similar to Arch support, use the latest version info from the official `apk` repo and don't offer explicit track or version switching. Add detection for Alpine Linux in version/distro along the way.
Updates #6995

cmd/tailscale/cli,version/distro: update support for Alpine

---

client/tailscale/apitype/apitype.go
cmd/cloner/cloner.go
ipn/ipnlocal/local.go
ipn/ipnlocal/peerapi.go
ipn/localapi/localapi.go
tailcfg/tailcfg.go
tstest/integration/testcontrol/testcontrol.go
util/deephash/deephash_test.go
wgengine/filter/filter.go
wgengine/filter/filter_clone.go
wgengine/filter/filter_test.go
wgengine/filter/match.go
wgengine/filter/tailcfg.go

Define PeerCapabilty and PeerCapMap as the new way of sending down inter-peer capability information.
Previously, this was unstructured and you could only send down strings which got too limiting for certain usecases. Instead add the ability to send down raw JSON messages that are opaque to Tailscale but provide the applications to define them however they wish.
Also update accessors to use the new values.
Updates #4217

tailcfg,ipn/ipnlocal,wgengine: add values to PeerCapabilities

---

ipn/ipnlocal/cert.go
ipn/ipnlocal/cert_js.go
ipn/ipnlocal/cert_test.go
ipn/ipnlocal/serve.go
ipn/localapi/cert.go

While our `shouldStartDomainRenewal` check is correct, `getCertPEM` would always bail if the existing cert is not expired. Add the same `shouldStartDomainRenewal` check to `getCertPEM` to make it proceed with renewal when existing certs are still valid but should be renewed.
The extra check is expensive (ARI request towards LetsEncrypt), so cache the last check result to not degrade `tailscale serve` performance.
Also, asynchronous renewal is great for `tailscale serve` but confusing for `tailscale cert`. Add an explicit flag to `GetCertPEM` to force a synchronous renewal for `tailscale cert`.
Tested this manually by stubbing out `shouldStartDomainRenewal` and running `tailscale cert` multiple times. Also tested renewal check caching via `tailscale serve` and looking through logs to make …

ipn/{ipnlocal,localapi}: actually renew certs before expiry

---

client/tailscale/apitype/apitype.go
ipn/localapi/localapi.go

Every time I use WhoIsResponse I end up writing mildly irritating nil-checking for both Node and UserProfile, but it turns out our code guarantees that both are non-nil in successful whois responses.

client/tailscale/apitype: document never-nil property of WhoIsResponse

---

cmd/dist/dist.go
release/dist/cli/cli.go
release/dist/unixpkgs/pkgs.go
release/dist/unixpkgs/targets.go

Pass an optional PEM-encoded ECDSA key to `cmd/dist` to sign all built tarballs. The signature is stored next to the tarball with a `.sig` extension.
Tested this with an `openssl`-generated key pair and verified the resulting signature.

cmd/dist,release/dist: sign release tarballs with an ECDSA key

---

client/tailscale/localclient.go
cmd/tailscale/cli/network-lock.go
ipn/ipnlocal/network-lock.go
ipn/ipnlocal/network-lock_test.go
ipn/localapi/localapi.go
tka/tka.go
tka/tka_test.go

The recover-compromised-key command allows nodes with tailnet lock keys
to collaborate to erase the use of a compromised key, and remove trust
in it.
I could use some help with the help text for sure.
```
[nix-shell:~/tailscale]$ go build -o tailscale ./cmd/tailscale && sudo ./tailscale --socket=/tmp/ts/ts1.sock lock recover-compromised-key --help
USAGE
recover-compromised-key <tailnet-lock-key>... or recover-compromised-key [--cosign] [--finish] <recovery-blob>
Retroactively revokes trust in the specified keys, erasing any trust in those keys and preventing them from being used in the future.
Start the process by running: tailscale recover-compromised-key <keys>, where keys is the list of compromised tailnet-lock keys.
The outputted command will then need to be run on other devices with …
```

all: implement lock revoke-keys command

---

cmd/tailscale/cli/update.go
cmd/tailscale/cli/version.go

Add optional `--with-latest` flag to `tailscale version` to fetch the latest release version from `pkgs.tailscale.com`. This is useful to diagnose `tailscale update` behavior or write other tooling.
Example output:
```sh
$ tailscale version --with-latest --json
{
"majorMinorPatch": "1.47.35",
"short": "1.47.35",
"long": "1.47.35-t6afffece8",
"unstableBranch": true,
"gitCommit": "6afffece8a32509aa7a4dc2972415ec58d8316de",
"cap": 66,
"latest": "1.45.61"
}
```
Fixes #8669

cmd/tailscale/cli: add latest version output to "tailscale version"

---

cmd/dist/dist.go
release/dist/cli/cli.go
release/dist/unixpkgs/pkgs.go
release/dist/unixpkgs/targets.go

Plumb a signing callback function to `unixpkgs.rpmTarget` to allow signing RPMs. This callback is optional and RPMs will build unsigned if not set, just as before.
Updates https://github.com/tailscale/tailscale/issues/1882

cmd/dist,release/dist: expose RPM signing hook

---

ipn/ipnlocal/cert.go
ipn/ipnlocal/local.go
ipn/ipnlocal/profiles.go
ipn/store.go
ipn/store_test.go

Rather than make each ipn.StateStore implementation guard against
useless writes (a write of the same value that's already in the
store), do writes via a new wrapper that has a fast path for the
unchanged case.
This then fixes profileManager's flood of useless writes to AWS SSM,
etc.
Updates #8785

ipn: avoid useless no-op WriteState calls

---

util/linuxfw/iptables.go
util/linuxfw/linuxfw.go
util/linuxfw/nftables.go
wgengine/router/router_linux.go
wgengine/router/router_linux_test.go

This change implements `chooseFireWallMode` that decides which one of `iptables`/`nftables` will be used.
Updates: #391 
Fix: #8111 #8733
1. Added `chooseFireWallMode` that automatically decides which one of `iptables` or`nftables` should be used.
2. Replaced the `TS_DEBUG_USE_NETLINK_NFTABLES` envknob with `TS_DEBUG_FIREWALL_MODE` that should be set to either 'iptables' or 'nftables' to select firewall mode manually.
3. Reimplemented `DetectIptables` that detects `iptables` binary and returns number of rules in `iptables` in current network namespace.
1. It is a very edge case when iptables binary is not available, nft is also not available and iptables is in use. So we are not supporting this case for now.
2. It is a very edge case when nftables is only available throught `nft` binary …

wgengine/router: add auto selection heuristic for iptables/nftables

---

client/web/web.go

client/web: fix rendering of node owner profile

---

util/linuxfw/iptables.go
util/linuxfw/linuxfw.go
util/linuxfw/nftables.go

Go style is for error variables to start with "err" (or "Err") and for error types to end in "Error".

util/linuxfw: rename ErrorFWModeNotSupported

---

control/controlclient/auto.go
control/controlclient/direct.go
control/controlclient/direct_test.go
tailcfg/tailcfg.go

Instead of having updates replace the map polls, create a third goroutine which is solely responsible for making sure that control is aware of the latest client state.
This also makes it so that the streaming map polls are only broken when there are auth changes, or the client is paused.
Updates https://github.com/tailscale/corp/issues/5761

control/controlclient: add Auto.informRoutine

---

cmd/tailscale/cli/debug.go
ipn/ipnlocal/breaktcp_darwin.go
ipn/ipnlocal/breaktcp_linux.go
ipn/ipnlocal/local.go
ipn/localapi/localapi.go
wgengine/magicsock/derp.go

For testing reconnects.
Updates tailscale/corp#5761

cmd/tailscale: add debug commands to break connections

---

control/controlclient/auto.go

The read of the synced field for logging takes place outside the lock, and
races with other (locked) writes of this field, including for example the one
at current line 556 in mapRoutine.
Change-Id: I056b36d7a93025aafdf73528dd7645f10b791af6

control/controlclient: avert a data race when logging

---

.github/workflows/installer.yml
scripts/installer.sh

Deepin Linux 20.x reports its version as "apricot"
Set it to bullseye, the Debian version it corresponds to.
Also fix the installer CI: OpenSUSE Leap appears to have removed curl from the base image recently, we have to install it now.
Fixes https://github.com/tailscale/tailscale/issues/8850
Updates https://github.com/tailscale/tailscale/issues/7862
Updates https://github.com/tailscale/corp/issues/8952

scripts/installer.sh: set Deepin to a debian version

---

client/tailscale/localclient.go
ipn/localapi/localapi.go

A #cleanup to add a func to utilize the already-present "/localapi/v0/upload-client-metrics" localapi endpoint.

client/tailscale: add LocalClient.IncrementMetric func

---

client/tailscale/localclient.go
cmd/tailscale/cli/funnel.go
cmd/tailscale/cli/serve.go
cmd/tailscale/cli/serve_test.go

1. Add metrics to funnel flow.
2. Stop blocking users from turning off funnels when no longer in their node capabilities.
3. Rename LocalClient.IncrementMetric to IncrementCounter to better callout its usage is only for counter clientmetrics.
Updates tailscale/corp#10577

cli/serve: funnel interactive enablement flow tweaks

---

.gitignore
client/web/index.html
client/web/package.json
client/web/src/components/app.tsx
client/web/src/components/legacy.tsx
client/web/src/hooks/node-data.ts
client/web/src/index.css
client/web/yarn.lock

This copies the existing go template frontend into very crude react components that will be driven by a simple JSON api for fetching and updating data.  For now, this returns a static set of test data.
This just implements the simple existing UI, so I've put these all in a "legacy" component, with the expectation that we will rebuild this with more properly defined components, some pulled from corp.
Updates https://github.com/tailscale/corp/issues/13775

client/web: copy existing UI to basic react components

---

hostinfo/hostinfo.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_test.go
tailcfg/tailcfg_view.go
wgengine/magicsock/magicsock.go
wgengine/router/router_linux.go

To record wether user is using iptables or nftables after we add support to nftables on linux, we are adding a field FirewallMode to NetInfo in HostInfo to reflect what firewall mode the host is running, and form metrics. The information is gained from a global constant in hostinfo.go. We set it when selection heuristic made the decision, and magicsock reports this to control.
Updates: tailscale/corp#13943

tailcfg: Add FirewallMode to NetInfo to provide metrics.

---

tsweb/log.go
tsweb/tsweb.go
tsweb/tsweb_test.go

If an optional request ID generating func is supplied to StdHandler, then requests that return an error will be logged with a request ID that is also shown as part of the response.
Updates tailscale/corp#2549
Change-Id: Ic7499706df42f95b6878d44d4aab253e2fc6a69b

tsweb: add request ID for errors

---

cmd/tailscale/cli/exitnode.go

All exit nodes are shown under this subcommand.
Updates tailscale/corp#13025

cmd/tailscale/cli: fix comment accuracy

---

net/art/stride_table.go
net/art/table.go
net/art/table_test.go

In preparation for a different refactor, but incidentally also saves 10-25% memory on overall table size in benchmarks.
Updates #7781

net/art: move child table pointers out of strideEntry

---

clientupdate/clientupdate.go

The work is done in Swift; this is now a documentation placeholder.
Updates #6995

clientupdate: return NOTREACHED for macsys

---

client/tailscale/apitype/controltype.go
tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

This PR adds DNSFilterURL to the DNSConfig type to be used by control changes to add DNS filtering logic
Fixes #cleanup

client: update DNSConfig type

---

cmd/k8s-operator/proxy.go
cmd/k8s-operator/proxy_test.go

Previously we would not set any groups; now that we have a way to send down peerCaps, use those to set the Impersonate-Group headers.
Updates #5055

cmd/k8s-operator: add support for control plane assigned groups

---

net/art/stride_table.go
net/art/stride_table_test.go
net/art/table.go
net/art/table_test.go

Values are still turned into pointers internally to maintain the invariants of strideTable, but from the user's perspective it's now possible to tbl.Insert(pfx, true) rather than
tbl.Insert(pfx, ptr.To(true)).
Updates #7781
---
The benchmarks are a little noisy, but generally positive: insertion and deletion got 10-50% faster, and the route tables are half the size they were before. We do pay 1 extra alloc per insertion now (~3 allocs/insert instead of ~2), but given the prior API that's just an alloc from outside the table that's now moved inside, for most uses. Full Table benchmarks below.
```
goos: linux
goarch: amd64
pkg: tailscale.com/net/art
cpu: AMD Ryzen 9 5950X 16-Core Processor
│ before-tbl.txt │            after-tbl.txt             │
│     sec/op     │    sec/op     vs base …
```

net/art: allow non-pointers as values

---

control/controlclient/direct.go
control/controlclient/map.go
control/controlclient/map_test.go
ipn/ipnlocal/local.go
tailcfg/tailcfg.go
tstest/integration/testcontrol/testcontrol.go
types/netmap/netmap_test.go
wgengine/magicsock/derp.go
wgengine/magicsock/magicsock.go
wgengine/userspace.go

Now a nodeAttr: ForceBackgroundSTUN, DERPRoute, TrimWGConfig,
DisableSubnetsIfPAC, DisableUPnP.
Kept support for, but also now a NodeAttr: RandomizeClientPort.
Removed: SetForceBackgroundSTUN, SetRandomizeClientPort (both never
used, sadly... never got around to them. But nodeAttrs are better
anyway), EnableSilentDisco (will be a nodeAttr later when that effort
resumes).
Updates #8923

tailcfg: remove most Debug fields, move bulk to nodeAttrs [capver 70]

---

cmd/tailscale/cli/funnel.go
cmd/tailscale/cli/serve.go
cmd/tailscale/cli/serve_test.go

The tailscale serve|funnel commands frequently call the LocalBackend's Status but they never need the peers to be included. This PR changes the call to be StatusWithoutPeers which should gain a noticeable speed improvement
Updates #8489

cmd/tailscale: change serve and funnel calls to StatusWithoutPeers

---

types/views/views.go
types/views/views_test.go

This is basically https://github.com/bradfitz/iter which was
a joke but now that Go's adding range over int soonish, might
as well. It simplies our code elsewher that uses slice views.
Updates #8948

types/views: add LenIter method to slice view types

---

cmd/tailscale/cli/set.go
cmd/viewer/tests/tests_view.go
cmd/viewer/viewer.go
ipn/ipn_view.go
ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go
ipn/prefs.go
net/tsaddr/tsaddr.go
tailcfg/tailcfg_view.go
types/views/views.go
types/views/views_test.go

Make it just a views.Slice[netip.Prefix] instead of its own named type.
Having the special case led to circular dependencies in another WIP PR
of mine.
Updates #8948

cmd/viewer, types/views, all: un-special case slice of netip.Prefix

---

wgengine/router/router_linux.go

Due to the conflict between our nftables implementation and ufw, which is a common utility used on linux. We now want to take a step back to prevent regression. This will give us more chance to let users to test our nftables support and heuristic.
Updates: #391

wgengine/router: fall back and set iptables as default again

---

tsnet/example/web-client/web-client.go

Serving the web client on the tailscale interface, while useful for remote management, is also inherently risky if ACLs are not configured appropriately. Switch the example to listen only on localhost, which is a much safer default. This is still a valuable example, since it still demonstrates how to have a web client connected to a tsnet instance.
Updates #13775

tsnet/example/web-client: listen on localhost

---

control/controlclient/direct.go
control/controlclient/map.go

It was added 2.5 years ago in c1dabd943674 but was never used.
Clearly that migration didn't matter.
We can attempt this again later if/when this matters.
Meanwhile this simplifies the code and thus makes working on other
current efforts in these parts of the code easier.
Updates #1909

control/controlclient: remove Opts.KeepSharerAndUserSplit

---

types/tkatype/tkatype_test.go

Lock in its wire format before a potential change to its Go type.
Updates #1909

types/tkatype: add test for MarshaledSignature's JSON format

---

ipn/ipnlocal/network-lock.go

I screwed this up in 58a4fd43d as I expected. I even looked out for
cases like this (because this always happens) and I still missed
it. Vet doesn't flag these because they're not the standard printf
funcs it knows about. TODO: make our vet recognize all our
"logger.Logf" types.
Updates #8948

ipn/ipnlocal: fix regression in printf arg type

---

tailcfg/tailcfg.go
tailcfg/tailcfg_clone.go
tailcfg/tailcfg_view.go

It had a custom Clone func with a TODO to replace with cloner, resolve that todo. Had to pull out the embedded Auth struct into a named struct.

tailcfg: generate RegisterResponse.Clone, remove manually written

---

cmd/tailscale/cli/status.go
control/controlclient/map.go
ipn/ipnlocal/local.go
ipn/ipnstate/ipnstate.go
tailcfg/tailcfg.go

In b987b2ab18ff48 (2021-01-12) when we introduced sharing we mapped
the sharer to the userid at a low layer, mostly to fix the display of
"tailscale status" and the client UIs, but also some tests.
The commit earlier today, 7dec09d1693, removed the 2.5yo option
to let clients disable that automatic mapping, as clearly we were never
getting around to it.
This plumbs the Sharer UserID all the way to ipnstatus so the CLI
itself can choose to print out the Sharer's identity over the node's
original owner.
Then we stop mangling Node.User and let clients decide how they want
to render things.
To ease the migration for the Windows GUI (which currently operates on
tailcfg.Node via the NetMap from WatchIPNBus, instead of PeerStatus),
a new method Node.SharerOrUser is added to do the mapping of …

ipn/ipnstate: add PeerStatus.AltSharerUserID, stop mangling Node.User

---

cmd/viewer/tests/tests_view.go
cmd/viewer/viewer.go
ipn/ipnlocal/network-lock.go
tailcfg/tailcfg_view.go
types/views/views.go

Add a new views.ByteSlice[T ~[]byte] to provide a better API to use with views.

types/views,cmd/viewer: add ByteSlice[T] to replace mem.RO

---

control/controlclient/direct.go
control/controlclient/map.go
control/controlclient/map_test.go
ipn/ipnlocal/local.go
types/netmap/netmap.go

And optimize the Persist setting a bit, allocating later and only mutating
fields when there's been a Node change.
Updates #1909

types/netmap: move some mutations earlier, remove, document some fields

---

wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock.go

When sending a ping from the CLI, only accept a pong that is in reply to the specific CLI ping we sent. This matters now that not all pings are equal - some of them are different sizes and we want to know which one got through, specifically. Otherwise we get a heartbeat pong and think that the larger sized ping got through when it did not.
Updates #311

wgengine/magicsock: only accept pong sent by CLI ping

---

tool/node

When running in our github CI environment, curl sometimes hangs while closing the download from the nodejs.org server and fails with INTERNAL_ERROR. This is likely caused by CI running behind some kind of load balancer or proxy that handles HTTP/2 incorrectly in some minor way.
This PR is a draft while I rerun the test enough times to see if this fixes it.

tool: force HTTP/1.1 in curl to prevent hang behind load balancer

---

util/linuxfw/nftables_runner.go

And flesh it out and use idiomatic doc style ("whether" for bools) and end in a period while there anyway.

util/linuxfw: fix typo in unexported doc comment

---

release/dist/dist.go
release/dist/synology/pkgs.go
release/dist/unixpkgs/pkgs.go
tool/yarn

This caused breakages on the build server:
```
synology/dsm7/x86_64: chdir /home/ubuntu/builds/2023-08-21T21-47-38Z-unstable-main-tagged-devices/0/client/web: no such file or directory 
synology/dsm7/i686: chdir /home/ubuntu/builds/2023-08-21T21-47-38Z-unstable-main-tagged-devices/0/client/web: no such file or directory 
synology/dsm7/armv8: chdir /home/ubuntu/builds/2023-08-21T21-47-38Z-unstable-main-tagged-devices/0/client/web: no such file or directory 
...
```
Reverting while I investigate.
This reverts commit 0fb95ec07daa81d2a30a44af7d969249cec5bdc8.

Revert "release/dist: run yarn build before building CLI"

---

.github/workflows/flakehub-publish-tagged.yml

This workflow will publish a flake to flakehub when a tag is pushed to the repository. It will only publish tags that match the pattern `v*.*.*`.
Fixes #9008

.github: add flakehub-publish-tagged.yml

---

control/controlclient/map.go
ipn/ipnlocal/local.go
types/netmap/netmap.go
wgengine/userspace.go

It was in SelfNode.Hostinfo anyway. The redundant copy was just
costing us an allocation per netmap (a Hostinfo.Clone).
Updates #1909

types/netmap: remove redundant Netmap.Hostinfo

---

release/dist/cli/cli.go
release/dist/dist.go
release/dist/synology/pkgs.go
release/dist/unixpkgs/pkgs.go
tool/yarn

This builds the assets for the new web client as part of our release process. The path to the web client source is specified by the -web-client-root flag.  This allows corp builds to first vendor the tailscale.com module, and then build the web client assets in the vendor directory.
The default value for the -web-client-root flag is empty, so no assets are built by default.
This is an update of the previously reverted 0fb95ec

release/dist: run yarn build before building CLI

---

client/web/web.go

instead of embedding each file individually, embed them all into a single embed filesystem.  This is basically a noop for the current frontend, but sets things up a little cleaner for the new frontend.
Also added an embed.FS for the source files needed to build the new frontend. These files are not actually embedded into the binary (since it is a blank identifier), but causes `go mod vendor` to copy them into the vendor directory.

client/web: combine embeds into a single embed.FS

---

client/web/web.go

src/**/* was only grabbing files in subdirectories, but not in the src directory itself.

client/web: fix globbing for file embedding

---

clientupdate/distsign/distsign.go
clientupdate/distsign/distsign_test.go
clientupdate/distsign/roots.go
clientupdate/distsign/roots/to-be-replaced.pub
clientupdate/distsign/roots_test.go

This library is intended for use during release (`cmd/dist`) to sign packages which are then served from pkgs.tailscale.com.
The library is also then used by clients downloading packages for `tailscale update` where OS package managers / app stores aren't used.
In a separate PR I will make a CLI around `distsign.Signer` for common operations like "generate new keys", "sign signing keys", "re-sign stuff with a new signing key". This PR is too big to include that :) 
Updates https://github.com/tailscale/tailscale/issues/8760 
Updates https://github.com/tailscale/tailscale/issues/6995

clientupdate/distsign: add new library for package signing/verification

---

wgengine/magicsock/endpoint.go

There are latency values stored in bestAddr and endpointState that are no longer applicable after a connectivity change and should be cleared out, following the documented behavior of the function.
Updates #8999

wgengine/magicsock: clear endpoint state in noteConnectivityChange

---

wgengine/magicsock/endpoint.go

LastFullPing is now used for disco or wireguard only endpoints. This change updates the comment to make that clear.
Updates #7826

wgengine/magicsock: update lastfullping comment to include wg only

---

wgengine/magicsock/endpoint.go
wgengine/magicsock/endpoint_default.go
wgengine/magicsock/endpoint_js.go

There are cases where we do not detect the non-viability of a route, but we will instead observe a failure to send. In a Disco path this would normally be handled as a side effect of Disco, which is not available to non-Disco WireGuard nodes. In both cases, recognizing the failure as such will result in faster convergence.
Updates #8999

wgengine/magicsock: clear out endpoint statistics when it becomes bad

---

wgengine/magicsock/derp.go
wgengine/magicsock/endpoint.go
wgengine/magicsock/magicsock.go
wgengine/magicsock/magicsock_test.go

If we don't have the ICMP hint available, such as on Android, we can use the signal of rx traffic to bias toward a particular endpoint.
We don't want to stick to a particular endpoint for a very long time without any signals, so the sticky time is reduced to 1 second, which is large enough to avoid excessive packet reordering in the common case, but should be small enough that either rx provides a strong signal, or we rotate in a user-interactive schedule to another endpoint, improving the feel of failover to other endpoints.
Updates #8999

wgengine/magicsock: improve endpoint selection for WireGuard peers with rx time

---

release/release.go

This ensures that `go mod vendor` includes these files, which are needed for client builds run in corp.

release: add empty embed.FS for release files

---

cmd/k8s-operator/operator.go

I forgot to move the defer out of the func, so the tsnet.Server immediately closed after starting.
Updates #502

cmd/k8s-operator: fix regression from earlier refactor

---

tailcfg/tailcfg.go

Actually fixed in 77ff705545 but that was cherry-picked to a branch
and we don't bump capver in branches.
This tells the control plane that UPnP should be re-enabled going
forward.
Updates #8992

tailcfg: bump capver to 72 to restore UPnP

---

client/web/src/hooks/node-data.ts

Open control server auth URLs in new browser tabs on web clients so users don't loose original client URL when redirected for login.

client/web: open auth URLs in new browser tab

---

cmd/ssh-auth-none-demo/ssh-auth-none-demo.go
ipn/localapi/localapi.go
ssh/tailssh/tailssh_test.go
tsnet/tsnet_test.go
tstest/iosdeps/iosdeps.go

This PR removes calls to ioutil library and replaces them with their new locations in the io and os packages.
Fixes #9034

all: replace deprecated ioutil references

---

cmd/tailscale/cli/netcheck.go
net/tlsdial/tlsdial.go

We have a fancy package for doing TLS cert validation even if the machine doesn't have TLS certs (for LetsEncrypt only) but the CLI's netcheck command wasn't using it.
Also, update the tlsdial's outdated package docs while here.

cmd/tailscale/cli: make netcheck run even if machine lacks TLS certs

---

cmd/tailscale/cli/ssh_unix.go
types/logger/rusage_stub.go
types/logger/rusage_syscall.go

Can write "wasm" instead of js || wasi1p, since there's only two:
$ go tool dist list | grep wasm
js/wasm
wasip1/wasm
Plus, if GOOS=wasip2 is added later, we're already set.
Updates #5794

types/logger, cmd/tailscale/cli: flesh out, simplify some non-unix build tags

---

.github/workflows/flakehub-publish-tagged.yml

The previous regex was too advanced for GitHub Actions. They only support a simpler glob syntax.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
Updates #9008

.github: fix flakehub-publish-tagged.yml glob

---

client/web/src/hooks/node-data.ts

Refresh node data when user switches to the web client browser tab. This helps clean up the auth flow where they're sent to another tab to authenticate then return to the original tab, where the data should be refreshed to pick up the login updates.

client/web: refresh on tab focus

---

cmd/testwrapper/testwrapper.go

It was checking if `>= maxAttempts` which meant that the third attempt would never run.
Updates #8493

cmd/testwrapper: fix off-by-one error in maxAttempts check

---

client/web/api.go
client/web/qnap.go
client/web/src/hooks/node-data.ts
client/web/synology.go
client/web/vite.config.ts
client/web/web.go

This should be one of the final sets of changes before we can migrate over to the new javascript web client.  This updates how we run the client in CGI environments (specifically on Synology and QNAP) so that they are able to serve the different paths appropriately.
This PR is three commits that should probably be reviewed separately in order.
Manually tested on Synology DSM7 and QNAP devices.

client/web: refactor and improve synology and qnap request handling

---

cmd/dist/dist.go
release/dist/cli/cli.go
release/dist/dist.go
release/dist/synology/pkgs.go
release/dist/synology/targets.go
release/dist/unixpkgs/pkgs.go
release/dist/unixpkgs/targets.go

Add `dist.Signer` hook which can arbitrarily sign linux/synology artifacts. Plumb it through in `cmd/dist` and remove existing tarball signing key. Distsign signing will happen on a remote machine, not using a local key.
Updates #755
Updates #8760

cmd/dist,release/dist: add distsign signing hooks

---

client/web/web.go
cmd/tailscale/cli/web.go
tsnet/example/web-client/web-client.go

Adds a cached self node to the web client Server struct, which will be used from the web client api to verify that request came from the node's own machine (i.e. came from the web client frontend). We'll be using when we switch the web client api over to acting as a proxy to the localapi, to protect against DNS rebinding attacks.

client/web: add self node cache

---

cmd/sniproxy/.gitignore
cmd/sniproxy/sniproxy.go
cmd/sniproxy/sniproxy_test.go

1. Add TCP port forwarding. For example: ./sniproxy -forwards=tcp/22/github.com will forward SSH to github.
% ssh -i ~/.ssh/id_ecdsa.pem -T git@github.com
Hi GitHubUser! You've successfully authenticated, but GitHub does not provide shell access.
% ssh -i ~/.ssh/id_ecdsa.pem -T git@100.65.x.y
Hi GitHubUser! You've successfully authenticated, but GitHub does not provide shell access.
2. Additionally export clientmetrics as prometheus metrics for local scraping over the tailnet: http://sniproxy-hostname:8080/debug/varz
Updates https://github.com/tailscale/tailscale/issues/1748

cmd/sniproxy: add port forwarding and prometheus metrics

---

cmd/containerboot/main.go
go.mod

This watches the provided path for a JSON encoded ipn.ServeConfig. Everytime the file changes, or the nodes FQDN changes it reapplies the ServeConfig.
At boot time, it nils out any previous ServeConfig just like tsnet does.
As the ServeConfig requires pre-existing knowledge of the nodes FQDN to do SNI matching, it introduces a special `${TS_CERT_DOMAIN}` value in the JSON file which is replaced with the known CertDomain before it is applied.
Updates #502
Updates #7895

cmd/containerboot: add support for setting ServeConfig

---

cmd/k8s-operator/ingress.go
cmd/k8s-operator/manifests/operator.yaml
cmd/k8s-operator/manifests/userspace-proxy.yaml
cmd/k8s-operator/operator.go
cmd/k8s-operator/operator_test.go
cmd/k8s-operator/sts.go
cmd/k8s-operator/svc.go

Previously, the operator would only monitor Services and create
a Tailscale StatefulSet which acted as a L3 proxy which proxied
traffic inbound to the Tailscale IP onto the services ClusterIP.
This extends that functionality to also monitor Ingress resources
where the `ingressClassName=tailscale` and similarly creates a
Tailscale StatefulSet, acting as a L7 proxy instead.
Users can override the desired hostname by setting:
```
- tls
hosts:
- "foo"
```
Hostnames specified under `rules` are ignored as we only create a single
host. This is emitted as an event for users to see.
Depends on #9074
Updates #7895

cmd/k8s-operator: add initial support for k8s ingress

---

util/osdiag/mksyscall.go
util/osdiag/osdiag_windows.go
util/osdiag/zsyscall_windows.go

It's very common for OOM crashes on Windows to be caused by lack of page file space (the NT kernel does not overcommit). Since Windows automatically manages page file space by default, unless the machine is out of disk space, this is typically caused by manual page file configurations that are too small.
This patch obtains the current page file size, the amount of free page file space, and also determines whether the page file is automatically or manually managed.
Fixes #9090

util/osdiag: add query for Windows page file configuration and status

---

release/dist/dist.go

We pass the file as an io.Reader to http.Post under the hood as request body. Post, helpfully, detects that the body is an io.Closer and closes it. So when we try to explicitly close it again, we get "file already closed" error.
The Close there is not load-bearing, we have a defer for it anyway. Remove the explicit close and error check.

release/dist: remove extra Close on a signed file

---

flake.nix

The previous change just switched the Go version used in the dev environment (for use with e.g. direnv), not the version used for the distribution build. Oops.

flake.nix: use Go 1.21 to build tailscale, for real this time

---

cmd/k8s-operator/operator.go
cmd/k8s-operator/operator_test.go
cmd/k8s-operator/svc.go

It'd be great to support this use case where Tailscale is the only controller for LoadBalancer Services.
Updates https://github.com/tailscale/tailscale/issues/502

cmd/k8s-operator: support being the default loadbalancer controller

---

cmd/containerboot/kube.go
cmd/containerboot/main.go
cmd/containerboot/main_test.go
cmd/k8s-operator/ingress.go
cmd/k8s-operator/operator_test.go
cmd/k8s-operator/sts.go
cmd/k8s-operator/svc.go

This way we have more information. Useful for tools like external-dns.
```
status:
loadBalancer:
ingress:
- hostname: service.something.ts.net
- ip: 100.99.98.97
- ip: 2c0a:8083:94d4:2012:3165:34a5:3616:5fdf
```
https://github.com/tailscale/tailscale/issues/502

cmd/k8s-operator: put Tailscale IPs in Service ingress status

---

client/tailscale/localclient.go
cmd/tailscale/cli/debug.go
ipn/localapi/localapi.go
net/portmapper/portmapper.go
net/portmapper/upnp.go

This option allows logging the raw HTTP requests and responses that the portmapper Client makes when using UPnP. This can be extremely helpful when debugging strange UPnP issues with users' devices, and might allow us to avoid having to instruct users to perform a packet capture.
Updates #8992
Change-Id: I2c3cf6930b09717028deaff31738484cc9b008e4

cmd/tailscale, net/portmapper: add --log-http option to "debug portmap"

---

clientupdate/distsign/distsign.go
release/dist/cli/cli.go

Helper command to verify package signatures, mainly for debugging. Also fix a copy-paste mistake in error message in distsign.
Updates #8760

release/dist/cli: add verify-package-signature command

---

net/memnet/conn.go

This makes it more maintainable for other code to statically depend on the exact value of this string. It also makes it easier to identify what code might depend on this string by looking up references to this constant.
Updates tailscale/corp#13777

net/memnet: export the network name

---

clientupdate/clientupdate.go

Top-level Version in pkgs response is not always in sync with SPK versions, especially on unstable track. It's very confusing when the confirmation prompt asks you "update to 1.49.x?" and you end up updating to 1.49.y.
Instead, grab the SPK-specific version field.
Updates #cleanup.

clientupdate: use SPKsVersion instead of Version

---

types/logger/logger_test.go

I didn't see the race builder fail on CI earlier in 590c693b9.
This fixes the test.
Updates #greenci

types/logger: fix test failure I missed earlier

---

control/controlclient/auto.go
control/controlclient/direct.go
ipn/ipnlocal/local.go
ipn/ipnlocal/network-lock_test.go
ipn/ipnlocal/state_test.go

For now the method has only one interface (the same as the func it's
replacing) but it will grow, eventually with the goal to remove the
controlclient.Status type for most purposes.
Updates #1909

control/controlclient: replace a status func with Observer interface

---

ipn/ipnlocal/local.go

Remove an unused argument to shouldUseOneCGNATRoute.

ipn/iplocale: remove unused argument to shouldUseOneCGNATRoute

---

cmd/tailscaled/tailscaled.go

No tun support yet.
Updates #5794

cmd/tailscaled: default to userspace-networking on plan9

---

net/dns/nm.go
net/interfaces/interfaces.go
net/interfaces/interfaces_test.go
net/netmon/netmon.go
net/netmon/netmon_test.go
net/netns/netns_darwin.go
net/netns/netns_darwin_test.go

This removes a lot of API from net/interfaces (including all the filter types, EqualFiltered, active Tailscale interface func, etc) and moves the "major" change detection to net/netmon which knows more about the world and the previous/new states.
Updates #9040

net/{interfaces,netmon}: remove "interesting", EqualFiltered API

---

types/opt/bool.go
types/opt/bool_test.go

The compiler does indeed perform this optimization.

types/opt: use switch in Bool.UnmarshalJSON

---

cmd/k8s-operator/sts.go
ipn/store/kubestore/store_kube.go
kube/client.go

We would call Update on the secret, but that was racey and would occasionaly fail. Instead use patch whenever we can.
Fixes errors like
```
boot: 2023/08/29 01:03:53 failed to set serve config: sending serve config: updating config: writing ServeConfig to StateStore: Operation cannot be fulfilled on secrets "ts-webdav-kfrzv-0": the object has been modified; please apply your changes to the latest version and try again
{"level":"error","ts":"2023-08-29T01:03:48Z","msg":"Reconciler error","controller":"ingress","controllerGroup":"networking.k8s.io","controllerKind":"Ingress","Ingress":{"name":"webdav","namespace":"default"},"namespace":"default","name":"webdav","reconcileID":"96f5cfed-7782-4834-9b75-b0950fd563ed","error":"failed to provision: failed to create or get API key secret: …
```

cmd/k8s-operator,ipn/store/kubestore: patch secrets instead of updating

---

client/web/src/components/app.tsx
client/web/src/components/legacy.tsx
client/web/src/hooks/node-data.ts
client/web/web.go
client/web/web_test.go

Adds proxy to the localapi from /api/local/ web client endpoint. The localapi proxy is restricted to an allowlist of those actually used by the web client frontend.

client/web: add localapi proxy

---

client/web/web.go

This is unused. Can be added back if needed in the future.

client/web: remove self node on server

---

client/web/src/api.ts
client/web/src/components/legacy.tsx
client/web/src/hooks/node-data.ts

Ensures that we're sending back the csrf token for all requests made back to unraid clients.

client/web: pipe unraid csrf token through apiFetch

---

cmd/derper/websocket.go
control/controlhttp/client_js.go
control/controlhttp/server.go
derp/derphttp/websocket.go
net/wsconn/wsconn.go

This makes wsconn.Conns somewhat present reasonably when they are the client of an http.Request, rather than just put a placeholder in that field.
Updates tailscale/corp#13777
---
Sadly I can't make this a properly typed net.Addr, since the call sites where wsconns get established only have strings of undefined content as remote addresses. But we can at least pass through that unspecified string to whoever cares.

net/wsconn: accept a remote addr string and plumb it through

---

cmd/containerboot/main.go
cmd/containerboot/main_test.go

The tests were broken in a61a9ab087e16270bc039252e7620aae4de3d56e, maybe even earlier.

cmd/containerboot: fix broken tests

---

cmd/testwrapper/testwrapper.go

While investigating the fix in 7538f386710b80c6b4c1997797be28a661210d4a, I was curious why the testwrapper didn't fail. Turns out if the test times out and there was no explicit failure, the only message we get is that the overall pkg failed and no failure information about the individual test. This resulted in a 0 exit code.
This fixes that by failing the explicit case of the pkg failing when there is nothing to retry for that pkg.
Updates #8493

cmd/testwrapper: handle timeouts as test failures

---

cmd/containerboot/main.go
cmd/k8s-operator/ingress.go
cmd/k8s-operator/operator_test.go
cmd/k8s-operator/sts.go
cmd/k8s-operator/svc.go

First part of work for the functionality that allows users to create an egress proxy to access Tailnet services from within Kubernetes cluster workloads. This PR allows creating an egress proxy that can access Tailscale services over HTTP only.
This PR allows users to specify a Tailscale service that should be made accessible to workloads in Kubernetes cluster by adding a `tailscale.com/target-ip` annotation to a Kubernetes `Service` with the value being the Tailscale IP of the service they wish to access.
Tailscale operator then does work in the background to create an egress proxy.
Tailscale operator updates `spec.externalName` of the annotated Service with a DNS name that workloads in cluster can use to access the Tailscale service. This currently gets set to the Kuberentes DNS name of …

cmd/k8s-operator,cmd/containerboot: add kube egress proxy

---

cmd/containerboot/main_test.go
cmd/k8s-operator/svc.go

This small PR:
- ensures that Statefulset reconciler config has only one of Cluster target IP or tailnet target IP
- adds a test case for containerboot egress proxy mode.
Updates tailscale/tailscale#8184

cm/k8s-operator,cmd/containerboot: fix STS config, adds another test case

---

control/controlclient/auto.go
health/health.go

I'm trying to remove some stuff from the netmap update path.
Updates #1909

control/controlclient: merge, simplify two health check calls

---

logtail/filch/filch_unix.go
net/interfaces/interfaces.go
net/tstun/tun.go
paths/paths_unix.go
types/logger/rusage_stub.go
types/logger/rusage_syscall.go

This PR adjust build tags to allow compilation under the [TamaGo framework](https://github.com/usbarmory/tamago).

adjust build tags for tamago

---

cmd/sniproxy/sniproxy.go

Port 8080 is routinely used for HTTP services, make it easier to use --forwards=tcp/8080/... by moving the metrics port out of the way.
Updates #1748

cmd/sniproxy: move default debug-port away from 8080.

---

cmd/k8s-operator/ingress.go
cmd/k8s-operator/operator.go
cmd/k8s-operator/sts.go

Instead of confusing users, emit an event that explicitly tells the user that HTTPS is disabled on the tailnet and that ingress may not work until they enable it.
Updates #9141

cmd/k8s-operator: emit event if HTTPS is disabled on Tailnet

---

client/web/web.go

Instead of trying to use the user config dir, and then fail back to the OS temp dir, just always use the temp dir. Also use a filename that is less likely to cause collisions.
This addresses an issue on a test synology instance that was mysteriously failing because there was a file at /tmp/tailscale. We could still technically run into this issue if a
/tmp/tailscale-web-csrf.key file exists, but that seems far less likely.

client/web: simply csrf key caching in cgi mode

---

control/controlclient/auto.go

Don't depend on the server to do it.

control/controlclient: cancel map poll when logging out

---

ipn/ipnlocal/local.go

Found while debugging something else.

ipn/ipnlocal: add missing mutex unlock in error path
