control/controlclient/auto.go, ipn/ipnlocal/local.go
We have cases where the SetControlClientStatus would result in a Shutdown call back into the auto client that would block forever. The right thing to do here is to fix the LocalBackend state machine but thats a different dumpster fire that we are slowly making progress towards.
This makes it so that the SetControlClientStatus happens in a different goroutine so that calls back into the auto client do not block.
Also add a few missing mu.Unlocks in LocalBackend.Start.
Updates #9181
=> control/controlclient: run SetControlClientStatus in goroutine

cmd/tsconnect/wasm/wasm_js.go, control/controlclient/status.go, ipn/ipnlocal/local.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/state_test.go, ipn/localapi/localapi.go, tstest/integration/integration_test.go
We already removed the async API, make it more sync and remove
the FinishLogout state too.
This also makes the callback be synchronous again as the previous
attempt was trying to work around the logout callback resulting
in a client shutdown getting blocked forever.
Updates #3833
=> ipn/ipnlocal,control/controlclient: make Logout more sync

net/interfaces/interfaces.go, net/tsdial/tsdial.go
It was too aggressive before, as it only had the ill-defined "Major"
bool to work with. Now it can check more precisely.
Updates #9040
=> net/tsdial: be smarter about when to close SystemDial conns

ipn/ipnlocal/local.go
During Shutdown of an ephemeral node, we called Logout (to best effort
delete the node earlier), which then called back into
resetForProfileChangeLockedOnEntry, which then tried to Start
again. That's all a waste of work during shutdown and complicates
other cleanups coming later.
=> ipn/ipnlocal: avoid calling Start from resetForProfileChangeLockedOnEntry

control/controlclient/auto.go, control/controlclient/controlclient_test.go
We want the overall state (used only for tests) to be computed from
the individual states of each component, rather than moving the state
around by hand in dozens of places.
In working towards that, we found a lot of things to clean up.
=> control/controlclient: clean up various things in prep for state overhaul

cmd/tailscaled/tailscaled.go, tstest/integration/integration_test.go
I noticed that failed tests were leaving aroudn stray tailscaled processes
on macOS at least.
To repro, add this to tstest/integration:
func TestFailInFewSeconds(t *testing.T) {
t.Parallel()
time.Sleep(3 * time.Second)
os.Exit(1)
t.Fatal("boom")
}
Those three seconds let the other parallel tests (with all their
tailscaled child processes) start up and start running their tests,
but then we violently os.Exit(1) the test driver and all the children
were kept alive (and were spinning away, using all available CPU in
gvisor scheduler code, which is a separate scary issue)
=> cmd/tailscaled, tstest/integration: make tailscaled die when parent dies

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/set.go, cmd/tailscale/cli/up.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/c2n.go, ipn/prefs.go, ipn/prefs_test.go
The flags are hidden for now. Adding propagation to tailscaled and persistence only.
Updates #6907
=> cmd/tailscale,ipn: add auto-update flags and prefs

client/web/qnap.go, client/web/src/api.ts, client/web/synology.go, client/web/web.go, cmd/tailscale/cli/web.go, release/dist/synology/files/index.cgi
We already had a path on the web client server struct, but hadn't plumbed it through to the CLI. Add that now and use it for Synology and QNAP instead of hard-coding the path. (Adding flag for QNAP is https://github.com/tailscale/tailscale-qpkg/pull/112) This will allow supporting other environments (like unraid) without additional changes to the client/web package.
Also fix a small bug in unraid handling to only include the csrf token on POST requests.
=> client/web,cmd/tailscale: add prefix flag for web command

control/controlclient/status.go, tailcfg/tailcfg.go, tailcfg/tailcfg_export_test.go, tailcfg/tailcfg_test.go, tka/aum.go, types/key/chal.go, types/key/disco.go, types/key/machine.go, types/key/nl.go, types/key/node.go, types/key/util.go, types/logid/id.go
This eventually allows encoding packages that may respect the proposed encoding.TextAppender interface.
The performance gains from this is between 10-30%.
Updates tailscale/corp#14379
=> all: implement AppendText alongside MarshalText

control/controlclient/auto.go, control/controlclient/client.go, control/controlclient/direct.go, ipn/ipnlocal/local.go, ipn/ipnlocal/network-lock_test.go, ipn/ipnlocal/state_test.go
resetControlClientLocked is called while b.mu was held and would call cc.Shutdown which would wait for the observer queue to drain.
However, there may be active callbacks from cc already waiting for b.mu resulting in a deadlock.
This makes it so that resetControlClientLocked does not call Shutdown, and instead just returns the value.
It also makes it so that any status received from previous cc are ignored.
Updates tailscale/corp#12827
=> ipn/ipnlocal: fix deadlock in resetControlClientLocked

client/web/web.go, clientupdate/clientupdate.go, util/linuxfw/nftables_runner.go, wgengine/magicsock/magicsock.go
Replace %w verb with %v verb when logging errors.
Use %w only for wrapping errors with fmt.Errorf()
Fixes: #9213
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
=> client/web, clientupdate, util/linuxfw, wgengine/magicsock: Use %v verb for errors

ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/local.go, ipn/ipnlocal/serve.go, ipn/serve.go
This PR adds a new field to the ServeConfig which maps WatchIPNBus session ids to foreground serve configs.
The PR also adds a DeleteForegroundSession method to ensure the config gets cleaned up on sessions ending.
Note this field is not currently used but will be in follow up work.
Updates #8489
=> ipn, ipn/ipnlocal: add Foreground field to ServeConfig

control/controlclient/auto.go
We would only check if the client was paused, but not if the client was closed. This meant that a call to Shutdown may block forever/leak goroutines
=> control/controlclient: check c.closed in waitUnpause

safesocket/safesocket_darwin.go
My earlier PR #9217 attempted to fix the same issue, but suffered from not letting the user connect to non-oss tailscaled if oss tailscaled was listening on the socket. The --socket flag doesn't let you select the mac apps.
Rather than leave the user unable to choose which tailscaled to connect to, this PR keeps the mac/socket preference order the same and checks a bit harder whether the macsys version really is running. Now, we still prefer the App Store Tailscale (even if it's listening with BackendState=Stopped) and you can use --socket to switch. But now if you quit the App Store Tailscale, we'll try the socket without needing the flag.
Fixes #5761
=> cmd/tailscale: Check App Store tailscaled dialable before selecting.

tstest/resource.go
It was only waiting for 0.5s (5ms * 100), but our CI is too slow so make it wait up to 3s (10ms * 300).
Updates tailscale/corp#14515
=> tstest: relax ResourceCheck to 3s

cmd/testwrapper/testwrapper.go, cmd/testwrapper/testwrapper_test.go
Note that merging this PR will then block upgrading tailscale.com in corp until a darwin build error from the PR below is fixed.
Fixes #9275
Fixes #8586
Fixes tailscale/corp#13115
=> cmd/testwrapper: exit code 1 when go build fails

client/tailscale/localclient.go, cmd/tailscale/cli/serve.go, cmd/tailscale/cli/serve_dev.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/serve.go, ipn/localapi/localapi.go, ipn/serve.go
ipn, ipn/ipnlocal: add Foreground field for ServeConfig
This PR adds a new field to the serve config that can be used to identify which serves are in "foreground mode" and then can also be used to ensure they do not get persisted to disk so that if Tailscaled gets ungracefully shutdown, the reloaded ServeConfig will not have those ports opened.
Updates #8489
=> ipn, ipn/ipnlocal: use Foreground field in ServeConfig

release/dist/unixpkgs/pkgs.go
=> release/dist/unixpkgs: demote deb iptables+iproute2 packages to recommended

cmd/tailscale/cli/funnel.go, cmd/tailscale/cli/serve.go, cmd/tailscale/cli/serve_dev.go, cmd/tailscale/cli/serve_dev_test.go
> **Note**
> Behind the `TAILSCALE_USE_WIP_CODE` flag
In preparing for incoming CLI changes, this PR adds a background mode to both serve and funnel.
See the [parent issue](https://github.com/tailscale/tailscale/issues/8489) for more context.
```
./tool/go run -exec "sudo env TAILSCALE_USE_WIP_CODE=1" ./cmd/tailscaled --socket=/tmp/ts/ts1.sock --state=/tmp/ts/ts1.state --statedir=/Library/Tailscale
TAILSCALE_USE_WIP_CODE=1 ./tool/go run ./cmd/tailscale --socket=/tmp/ts/ts1.sock funnel --bg localhost:3000
TAILSCALE_USE_WIP_CODE=1 ./tool/go run ./cmd/tailscale --socket=/tmp/ts/ts1.sock funnel --set-path=/bar localhost:4000
```
Replaces #9134
Updates #8489
=> cmd/tailscale: add background mode to serve/funnel wip

util/lru/lru.go, util/lru/lru_test.go
pre-generics container/list is quite unpleasant to use, and the pointer manipulation operations for an LRU are simple enough to implement directly now that we have generic types.
With this change, the LRU uses a ring (aka circularly linked list) rather than a simple doubly-linked list as its internals, because the ring makes list manipulation edge cases more regular: the only remaining edge case is the transition between 0 and 1 elements, rather than also having to deal specially with manipulating the first and last members of the list.
=> util/lru: replace container/list with a custom ring implementation

util/linuxfw/linuxfw_unsupported.go
Only arm64 and amd64 are supported
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
For example, if you build with:
```
GOOS=linux GOARCH=386 ./tool/go install tailscale.com/cmd/tailscale tailscale.com/cmd/tailscaled
```
That is not supported, even though it is an x86 arch.
The lsupported arches are listed
in  the Build Constraints here: https://github.com/tailscale/tailscale/pull/9279/files#diff-87f1974e43e52bc996fdeb5ddd5246c8e267c0de9e1114446e55922b116360b6R8
=> util/linuxfw: Fix comment which lists supported linux arches

client/web/assets.go, client/web/build/index.html, client/web/web.go
A #cleanup that moves all frontend asset handling into assets.go (formerly dev.go), and stores a single assetsHandler field back to web.Server that manages when to serve the dev vite proxy versus static files itself.
=> client/web: clean up assets handling

clientupdate/clientupdate.go, ipn/ipnlocal/c2n.go, ipn/ipnlocal/local.go, tailcfg/c2ntypes.go
Log some progress info to make updates more debuggable. Also, track whether an active update is already started and return an error if a concurrent update is attempted.
Some planned future PRs:
* add JSON output to `tailscale update`
* use JSON output from `tailscale update` to provide a more detailed status of in-progress update (stage, download progress, etc)
Updates #6907
=> ipn/ipnlocal: add logging and locking to c2n /update

cmd/tailscale/cli/status.go, ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go, tailcfg/tailcfg.go
Cache the last `ClientVersion` value that was received from coordination server and pass it in the localapi `/status` response. When running `tailscale status`, print a message if `RunningAsLatest` is `false`.
Updates #6907
=> cmd/tailscale/cli,ipn: mention available update in "tailscale status"

util/limiter/limiter.go, util/limiter/limiter_test.go, util/lru/lru.go, util/lru/lru_test.go
For use in tsweb debug handlers, so that we can easily inspect cache and limiter state when troubleshooting.
Updates tailscale/corp#3601
---
As discussed with bradfitz, I deliberately avoided taking a dependency on either net/http or html/template, so downstream packages don't pick up things like reflection de-optimizations or all of HTTP just for a debug printer they may never use.
=> util/lru, util/limiter: add debug helper to dump state as HTML

health/health.go, health/health_test.go, net/dns/nrpt_windows.go, net/tstun/wrap.go, tka/aum.go, tka/tka.go, util/set/set.go, util/winutil/svcdiag_windows.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/router/router_openbsd.go, wgengine/userspace.go
I didn't clean up the more idiomatic map[T]bool with true values, at
least yet.  I just converted the relatively awkward struct{}-valued
maps.
=> all: use set.Set consistently instead of map[T]struct{}

tailcfg/tailcfg.go
It's been implicitly enabled (based on capver) for years.
=> tailcfg: remove unused MapRequest.IncludeIPv6 field

cmd/testwrapper/flakytest/flakytest.go
If the user's running "go test" by hand, no need to spam stderr with the sentinel marker. It already calls t.Logf (which only gets output on actual failure, or verbose mode) which is enough to tell users it's known flaky. Stderr OTOH always prints out and is distracting to manual "go test" users.
=> cmd/testwrapper/flakytest: don't spam stderr in Mark when not under wrapper

envknob/envknob.go, wgengine/magicsock/debugknobs.go, wgengine/magicsock/debugknobs_stubs.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/magicsock/peermap.go, wgengine/userspace_test.go
In prep for incremental netmap update plumbing (#1909), make peerMap
also keyed by NodeID, as all the netmap node mutations passed around
later will be keyed by NodeID.
In the process, also:
* add envknob.InDevMode, as a signal that we can panic more aggressively
in unexpected cases.
* pull two moderately large blocks of code in Conn.SetNetworkMap out
into their own methods
* convert a few more sets from maps to set.Set
Updates #1909
=> wgengine/magicsock: make peerMap also keyed by NodeID

cmd/tailscale/cli/netcheck.go, cmd/tailscaled/tailscaled.go, cmd/tsconnect/wasm/wasm_js.go, control/controlclient/direct.go, control/controlclient/map.go, control/controlclient/map_test.go, control/controlknobs/controlknobs.go, ipn/ipnlocal/local.go, ipn/localapi/localapi.go, net/portmapper/igd_test.go, net/portmapper/portmapper.go, net/portmapper/portmapper_test.go, net/portmapper/upnp.go, tsd/tsd.go, tsnet/tsnet.go, wgengine/magicsock/derp.go, wgengine/magicsock/magicsock.go, wgengine/userspace.go, wgengine/userspace_test.go
Previously two tsnet nodes in the same process couldn't have disjoint
sets of controlknob settings from control as both would overwrite each
other's global variables.
This plumbs a new controlknobs.Knobs type around everywhere and hangs
the knobs sent by control on that instead.
Updates #9351
=> control/controlknobs, all: add plumbed Knobs type, not global variables

wgengine/magicsock/derp.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/endpoint_default.go, wgengine/magicsock/endpoint_js.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
WireGuard-only node fixes, use successful rx to maintain connection stability, and ensure that statistics are cleared on connectivity change:
* [wgengine/magicsock: clear endpoint state in noteConnectivityChange](https://github.com/tailscale/tailscale/commit/92718070f206fa8a31fe4e11403c7fdb38db26ab)
* [wgengine/magicsock: update lastfullping comment to include wg only](https://github.com/tailscale/tailscale/commit/274db2fdd3ecbec93947b2460a9d574fba1f7537)
* [wgengine/magicsock: clear out endpoint statistics when it becomes bad](https://github.com/tailscale/tailscale/commit/9f515676ce90c6bb438afbf7ca2b4be9f2a98c24)
* [wgengine/magicsock: improve endpoint selection for WireGuard peers wi…](https://github.com/tailscale/tailscale/commit/1a8b7af39036443cc328513746324715108a1292)
=> release: cherry picks for 1.48.2

control/controlclient/direct.go, control/controlknobs/controlknobs.go, wgengine/magicsock/magicsock.go
This is both more efficient (because the knobs' bool is only updated
whenever Node is changed, rarely) and also gets us one step closer to
removing a case of storing a netmap.NetworkMap in
magicsock. (eventually we want to phase out much of the use of that
type internally)
Updates #1909
=> control/controlknobs: move ForceBackgroundSTUN to controlknobs.Knobs

wgengine/userspace.go, wgengine/wgengine.go
I guess we missed this one earlier when we unified the various copies into set.HandleSet.
=> wgengine: use set.HandleSet in another place

wgengine/magicsock/debughttp.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
We're trying to start using that monster type less and eventually get rid of it.
Updates #1909
=> wgengine/magicsock: stop retaining *netmap.NetworkMap

client/tailscale/localclient.go, cmd/tailscale/cli/debug.go, control/controlknobs/controlknobs.go, ipn/ipnlocal/local.go, ipn/localapi/localapi.go, tstest/integration/integration_test.go
I missed connecting some controlknobs.Knobs pieces in 4e91cf20a854 resulting in that breaking control knobs entirely.
Whoops.
The fix in ipn/ipnlocal (where it makes a new controlclient) but to atone, I also added integration tests. Those integration tests use a new "tailscale debug control-knobs" which by itself might be useful for future debugging.
Updates #9351
=> ipn/ipnlocal: fix missing controlknobs.Knobs plumbing

cmd/tailscale/cli/netcheck.go
=> cmd/tailscale/cli: fix panic in netcheck print when no DERP home

tstest/integration/integration_test.go, tstest/integration/testcontrol/testcontrol.go
This adds a new integration test with two nodes where the first gets a
incremental MapResponse (with only PeersRemoved set) saying that the
second node disappeared.
This extends the testcontrol package to support sending raw
MapResponses to nodes.
Updates #1909
=> tstest/integration: add start of integration tests for incremental map updates

cmd/tailscaled/tailscaled.go, ipn/ipnlocal/local.go, tsd/tsd.go, tsnet/tsnet.go, tstest/integration/integration_test.go, wgengine/netstack/netstack.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
It had exactly one user: netstack. Just have LocalBackend notify netstack when here's a new netmap instead, simplifying the bloated Engine interface that has grown a bunch of non-Engine-y things. (plenty of rando stuff remains after this, but it's a start)
=> wgengine{,/netstack}: remove AddNetworkMapCallback from Engine interface

cmd/tsconnect/wasm/wasm_js.go
I missed this in 343c0f1031a and I guess we don't have integration
tests for wasm. But it compiled! :)
Updates #fixup to a #cleanup
=> cmd/tsconnect/wasm: register netstack.Impl with tsd.System

ipn/ipnlocal/local.go, wgengine/magicsock/magicsock.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
LocalBackend can talk to magicsock on its own to do this without the "Engine" being involved.
(Continuing a little side quest of cleaning up the Engine interface...)
=> wgengine: remove SetNetInfoCallback method from Engine

wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
It was only used by Android, until
https://github.com/tailscale/tailscale-android/pull/131 which does the call to the netMon directly instead.
=> wgengine: remove LinkChange method from Engine interface

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi.go, wgengine/bench/wg.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
(continuing the mission of removing rando methods from the Engine
interface that we don't need anymore)
=> wgengine: remove SetDERPMap method from Engine interface

cmd/tailscale/cli/serve.go, cmd/tailscale/cli/serve_dev.go, cmd/tailscale/cli/serve_dev_test.go, cmd/tailscale/cli/serve_test.go, ipn/serve.go
General cleanup and additional test coverage of WIP code.
* use enum for serveType
* cleanMountPoint rewritten into cleanURLPath as it only handles URL paths
* refactor and test expandProxyTargetDev
> **Note**
> Behind the `TAILSCALE_USE_WIP_CODE` flag
See the [parent issue](https://github.com/tailscale/tailscale/issues/8489) for more context.
=> cmd/tailscale: funnel wip cleanup and additional test coverage

README.md
Move into the main "building" section and add the missing `yarn install` step.
Updates #9312
=> README: update docs for building web client

cmd/tsconnect/wasm/wasm_js.go
It became required as of 6e967446e412a5f5
Updates #8052
=> cmd/tsconnect/wasm: pass a netmon to ipnserver.New

client/tailscale/localclient.go, cmd/tailscale/cli/serve_dev.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/serve.go
This PR uses the etag/if-match pattern to ensure multiple calls to SetServeConfig are synchronized. It currently errors out and asks the user to retry but we can add occ retries as a follow up.
Updates #8489
=> cmd/tailscale/cli: use optimistic concurrency control on SetServeConfig

.github/workflows/govulncheck.yml
Currently slack messages for errors fail:
https://github.com/tailscale/tailscale/actions/runs/6159104272/job/16713248204
```
Error: Unexpected token
in JSON at position 151
```
This is likely due to the line break in the text. Restructure the message to use separate title/text and fix the slack webhook body.
=> .github/workflows: fix slack-action format in govulncheck.yml

cmd/tailscale/cli/serve_dev.go, cmd/tailscale/cli/serve_dev_test.go
This PR adds validations for the new new funnel/serve commands under the following rules:
1. There is always a single config for one port (bg or fg).
2. Foreground configs under the same port cannot co-exists (for now).
3. Background configs can change as long as the serve type is the same.
Updates #8489
=> cmd/tailscale/cli: add set serve validations

cmd/cloner/cloner.go, cmd/viewer/tests/tests_clone.go, tailcfg/tailcfg_clone.go, wgengine/filter/filter_clone.go, wgengine/wgcfg/wgcfg_clone.go
tailcfg.Node zero-value clone equality checks failed when I added a []*foo to the structure, as the zero value and it's clone contained a different slice header.
Updates #9377
Updates #9408
=> cmd/cloner: do not allocate slices when the source is nil

net/dns/publicdns/publicdns.go
The following IPs are not used anymore: 193.19.108.2 and 193.19.108.3.
All of the servers are now named consistently under dns.mullvad.net.
Several new servers were added.
https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/
Updates #5416
Updates #9345
=> net/dns/publicdns: update Mullvad DoH server list

control/controlclient/map.go, control/controlclient/map_test.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go, types/dnstype/dnstype.go, types/dnstype/dnstype_test.go, types/dnstype/dnstype_view.go
Tailscale exit nodes provide DNS service over the peer API, however IsWireGuardOnly nodes do not have a peer API, and instead need client DNS parameters passed in their node description.
For Mullvad nodes this will contain the in network 10.64.0.1 address.
Updates #9377
=> tailcfg: add DNS address list for IsWireGuardOnly nodes

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
This enables installing default resolvers specified by tailcfg.Node.ExitNodeDNSResolvers when the exit node is selected.
Updates #9377
=> ipn/ipnlocal: plumb ExitNodeDNSResolvers for IsWireGuardOnly exit nodes

net/ping/ping.go
The code was trying to pass the ICMP protocol number here (1), which is not a valid code. Many servers will not respond to echo messages with codes other than 0.
=> net/ping: fix ICMP echo code field to 0

ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go
* Remove unnecessary mutexes (there's no concurrency)
* Simplify LocalBackend.UpdateStatus using the StatusBuilder.WantPeers
field that was added in 0f604923d345ff, removing passing around some
method values into func args. And then merge two methods.
More remains, but this is a start.
Updates #9433
=> ipn/{ipnlocal,ipnstate}: start simplifying UpdateStatus/StatusBuilder

cmd/tsconnect/wasm/wasm_js.go, ipn/ipnlocal/local.go, types/netmap/netmap.go
Step 1 of deleting it, per TODO.
=> types/netmap: deprecate NetworkMap.MachineStatus, add accessor method

ipn/ipnlocal/local.go, ipn/ipnlocal/serve.go, net/tsdial/dnsmap.go, tsnet/tsnet.go, types/netmap/netmap.go, wgengine/magicsock/magicsock.go
NetworkMap.Addresses is redundant with the SelfNode.Addresses. This
works towards a TODO to delete NetworkMap.Addresses and replace it
with a method.
This is similar to #9389.
=> types/netmap: start phasing out Addresses, add GetAddresses method

cmd/tailscale/cli/serve_dev.go, cmd/tailscale/cli/serve_dev_test.go
This PR fixes a bug to make sure that we don't allow two configs exist with duplicate ports
Updates #8489
=> cmd/tailscale/cli: error when serving foreground if bg already exists

cmd/tsconnect/wasm/wasm_js.go, control/controlclient/map.go, ipn/ipnlocal/dnsconfig_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/state_test.go, net/tsaddr/tsaddr.go, net/tsaddr/tsaddr_test.go, net/tsdial/dnsmap_test.go, types/netmap/netmap.go, wgengine/magicsock/magicsock_test.go, wgengine/netstack/netstack.go, wgengine/userspace.go, wgengine/wgcfg/nmcfg/nmcfg.go
And convert all callers over to the methods that check SelfNode.
Now we don't have multiple ways to express things in tests (setting
fields on SelfNode vs NetworkMap, sometimes inconsistently) and don't
have multiple ways to check those two fields (often only checking one
or the other).
=> types/netmap: remove NetworkMap.{Addresses,MachineStatus}

ipn/ipnlocal/local.go, ipn/ipnlocal/network-lock.go, ipn/ipnlocal/network-lock_test.go, ipn/ipnlocal/peerapi_test.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_test.go, ipn/ipnlocal/state_test.go, ipn/prefs.go, types/netmap/netmap.go
ipn/ipnlocal: add tailnet MagicDNS name to ipn.LoginProfile
Start backfilling MagicDNS suffixes on LoginProfiles.
Updates #9286
=> ipn/ipnlocal: add tailnet MagicDNS name to LoginProfiles

control/controlclient/map.go, control/controlclient/map_test.go, ipn/ipnlocal/peerapi.go, net/tstun/wrap.go, net/tstun/wrap_test.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go, tstest/integration/testcontrol/testcontrol.go, wgengine/wgcfg/config.go, wgengine/wgcfg/nmcfg/nmcfg.go, wgengine/wgcfg/wgcfg_clone.go
This PR plumbs through awareness of an IPv6 SNAT/masquerade address from the wire protocol through to the low-level (tstun / wgengine). This PR is the first in two PRs for implementing IPv6 NAT support to/from peers.
A subsequent PR will implement the data-plane changes to implement IPv6 NAT - this is just plumbing.
Updates ENG-991
=> all: declare & plumb IPv6 masquerade address for peer

Makefile
At the moment the dev images for k8s-operator and proxy are always tagged only with `latest` tag which makes it slightly inconvenient to use them when redeploying with additional changes during development.
This makes it possibe to pass a custom tag:
`TAGS=v0.0.3 REPO=<some-repo> make publishdevoperator`
=> Makefile: make it possibe to pass a custom tag when building dev images

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
The initial implementation directly mirrored the behavior of Tailscale exit nodes, where the WireGuard exit node DNS took precedence over other configuration.
This adjusted implementation treats the WireGuard DNS resolvers as a lower precedence default resolver than the tailnet default resolver, and allows split DNS configuration as well.
This also adds test coverage to the existing DNS selection behavior with respect to default resolvers and split DNS routes for Tailscale exit nodes above cap 25. There may be some refinement to do in the logic in those cases, as split DNS may not be working as we intend, though that would be a pre-existing and separate issue.
Updates #9377
=> ipn/ipnlocal: allow Split-DNS and default resolvers with WireGuard nodes

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
This reverts commit c7ce4e07e5c43f172d2655c4fe5c6d85731bb70b.
=> Revert "ipn/ipnlocal: allow Split-DNS and default resolvers with WireGuard nodes

cmd/k8s-operator/sts.go, cmd/k8s-operator/svc.go
It was tailscale.com/ts-tailnet-target-ip, which was pretty redundant. Change it to tailscale.com/tailnet-ip.
Updates #502
=> cmd/k8s-operator: rename egress annotation

cmd/k8s-operator/operator_test.go, cmd/k8s-operator/svc.go
Fix the external name for egress Service.
Updates https://github.com/tailscale/tailscale/issues/502
=> cmd/k8s-operator: fix egress service name

ipn/ipnlocal/local.go
9538e9f97035ce7a382d2b395db3368bd0326113 broke LocalBackend.WhoIs where you can no longer lookup yourself in WhoIs.
This occurs because the LocalBackend.peers map only contains peers. If we fail to lookup a peer, double-check whether it is ourself.
Fixes #9470
=> ipn/ipnlocal: fix LocalBackend.WhoIs for self

cmd/containerboot/main.go, cmd/containerboot/main_test.go
In typical k8s setups, the MTU configured on the eth0 interfaces is typically 1500 which results in packets being dropped when they make it to proxy pods as the tailscale0 interface has a 1280 MTU.
As the primary use of this functionality is TCP, add iptables based MSS clamping to allow connectivity.
Updates #502
=> cmd/containerboot: add iptables based MSS clamping for ingress/egress proxies

net/dns/publicdns/publicdns.go
One Quad9 IPv6 address was incorrect, and an additional group needed adding. Additionally I checked Cloudflare and included source reference URLs for both.
=> net/dns/publicdns: update Quad9 addresses and references

ipn/ipnlocal/peerapi.go
Use filepath.IsLocal to further validate the baseName.
=> ipn/ipnlocal: perform additional sanity check in diskPath

cmd/containerboot/main_test.go, cmd/containerboot/test_tailscaled.sh
The test was sending SIGKILL to containerboot, which results in no signal propagation down to the bash script that is running as a child process, thus it leaks.
Minor changes to the test daemon script, so that it cleans up the socket that it creates on exit, and spawns fewer processes.
Fixes tailscale/corp#14833
=> cmd/containerboot: avoid leaking bash scripts after test runs

net/tstun/mtu.go
=> net/tstun: use untyped consts, simplify DefaultMTU func

control/controlknobs/controlknobs.go, net/dns/manager.go, net/dns/manager_tcp_test.go, net/dns/manager_test.go, net/dns/resolver/forwarder.go, net/dns/resolver/forwarder_test.go, net/dns/resolver/tsdns.go, net/dns/resolver/tsdns_test.go, net/sockstats/label_string.go, net/sockstats/sockstats.go, tailcfg/tailcfg.go, wgengine/netstack/netstack.go, wgengine/userspace.go
We weren't correctly retrying truncated requests to an upstream DNS server with TCP. Instead, we'd return a truncated request to the user, even if the user was querying us over TCP and thus able to handle a large response.
Updates #9264
Change-Id: Ifb04b563839a9614c0ba03e9c564e8924c1a2bfd
=> net/dns: retry forwarder requests over TCP

cmd/tailscale/cli/serve_dev.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/serve.go, ipn/ipnlocal/serve_test.go
This PR ensures zombie foregrounds are shutdown if a new ServeConfig is created that wipes the ongoing foreground ones. For example, "tailscale serve|funnel reset|off" should close all open sessions.
Updates #8489
=> ipn/ipnlocal: close foreground sessions on SetServeConfig

cmd/tailscaled/tailscaled_windows.go, control/controlclient/sign_supported.go, hostinfo/hostinfo_windows.go, ipn/ipnlocal/profiles.go, logpolicy/logpolicy.go, util/winutil/policy/policy_windows.go, util/winutil/winutil.go, util/winutil/winutil_notwindows.go, util/winutil/winutil_windows.go
allow callers to handle errors instead of forcing a default value 
Updates tailscale/corp#14879
~~First appending v2 before we merge into oss, then will clean up after and remove v2 suffix and old methods~~
=> winutil: refactor methods to get values from registry to also return errors

util/linuxfw/nftables_runner.go
Appears to be a missing nil handling case. I looked back over other usage of findRule and the others all have nil guards. findRule returns nil when no rules are found matching the arguments.
Fixes #9553
=> util/linuxfw: fix crash in DelSNATRule when no rules are found

wgengine/magicsock/magicsock.go
If the condition arises, it should be easy to track down.
Updates #9547
=> wgengine/magicsock: add nodeid to panic condition on public key reuse

client/web/qnap.go, client/web/synology.go, client/web/web.go
Adds new LoginOnly server option and swaps out API handler depending
on whether running in login mode or full web client mode.
Also includes some minor refactoring to the synology/qnap authorization
logic to allow for easier sharing between serveLoginAPI and serveAPI.
Updates https://github.com/tailscale/corp/issues/14335
=> client/web: add login client mode to web.Server

tool/gocross/autoflags.go
So we can experiment with disabling static linking for tests in CI to make GitHub Actions output less spammy.
Updates tailscale/corp#13113
=> tool/gocross: disable Linux static linking if GOCROSS_STATIC=0

cmd/containerboot/main.go, cmd/containerboot/main_test.go
1.50.0 switched containerboot from using `tailscale up` to `tailscale login`. A side-effect is that a re-usable authkey is now re-applied on every boot by `tailscale login`, where `tailscale up` would ignore an authkey if already authenticated.
Though this looks like it is changing the default, in reality it is setting the default to match what 1.48 and all prior releases actually implemented.
Fixes https://github.com/tailscale/tailscale/issues/9539
Fixes https://github.com/tailscale/corp/issues/14953
=> cmd/containerboot: set TS_AUTH_ONCE default to true.

util/syspolicy/handler.go, util/syspolicy/handler_test.go, util/syspolicy/handler_windows.go, util/syspolicy/policy_keys.go, util/syspolicy/syspolicy.go, util/syspolicy/syspolicy_test.go
Add a more generalized package for getting mdm policies. Updates tailcale/corp#10967
note - in process of moving winutil/policy to syspolicy and will remove winutil/policy and refactor usages of this after this pr
=> util: add syspolicy package

gomod_test.go
Prevent future problems like we earlier with go.mod replace directives (e.g. removing our certstore replace in 6d6cf88d826c or wireguard-go in ea5ee6f87c15fa, both of which were reactions to problems caused by go.mod replace in non-root modules, often because people are using tsnet as a library from another module)
=> go.mod: add test that replace directives aren't added in oss

cmd/cloner/cloner.go, cmd/viewer/tests/tests_clone.go, tailcfg/tailcfg_clone.go, wgengine/filter/filter_clone.go, wgengine/wgcfg/wgcfg_clone.go
This reverts commit ee90cd02fdd4e4125ec9d12eef1195ed36ef4b2e.
The outcome is not identical for empty slices. Cloner really needs tests!
=> cmd/cloner,*: revert: optimize nillable slice cloner

net/dnsfallback/dnsfallback.go
We should be able to freely run `./tool/go generate ./...`, but we're continually dodging this particular generator. Instead of constantly dodging it, let's just remove it.
=> net/dnsfallback: remove net/dnsfallback go:generate line

cmd/cloner/cloner_test.go, cmd/cloner/clonerex/clonerex.go, cmd/cloner/clonerex/clonerex_clone.go
s/SliceContianer/SliceContainer/g
Updates #9604
=> cmd/cloner: fix typo in test type's name

tailcfg/tailcfg.go, util/slicesx/slicesx.go, util/slicesx/slicesx_test.go, wgengine/router/router_windows.go
Then use it in tailcfg which had it duplicated a couple times.
I think we have it a few other places too.
And use slices.Equal in wgengine/router too. (found while looking for callers)
=> util/slicesx: add EqualSameNil, like slices.Equal but same nilness

control/controlclient/direct.go, control/controlclient/map_test.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go, tstest/integration/testcontrol/testcontrol.go, types/netmap/netmap.go, types/netmap/netmap_test.go, types/netmap/nodemut.go, types/netmap/nodemut_test.go, wgengine/bench/wg.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock_test.go
=> tailcfg, all: use []netip.AddrPort instead of []string for Endpoints

wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock_test.go
When sending a CLI ping with a specific size, continue to probe all possible UDP paths to the peer until we find one with a large enough MTU to accommodate the ping. Record any peer path MTU information we discover (but don't use it for anything other than CLI pings).
Updates #311
=> Use CLI ping to probe path MTUs to peer

cmd/tailscale/cli/debug.go, ipn/backend.go, ipn/ipnlocal/local.go
Make the 'tailscale debug component-logs' command print the component names for which extra logging can be turned on, for easier discoverability of debug functions.
=> cmd/tailscale,ipn/ipnlocal: print debug component names

wgengine/magicsock/magicsock_linux.go
=> wgengine/magicsock: use binary.NativeEndian for UDP GSO control data

tool/gocross/autoflags.go
This reverts commit 2c0f0ee759cc571db06b4615c900fc2e905498b1.
Fixed by efac2cb8d672670b7
Updates tailscale/corp#15058
Updates tailscale/corp#13113
=> Revert "tool/gocross: disable Linux static linking if GOCROSS_STATIC=0"

portlist/portlist.go, portlist/portlist_linux.go
The Port.Pid was always more of an implementation detail on some platforms and isn't necessary on Linux so it was never populated. (Nothing outside the portlist package ever used it)
But might as well populate it for consistency since we have it in memory and its absence confused people.
=> portlist: populate Pid field on Linux

net/tstun/wrap.go, net/tstun/wrap_test.go, tailcfg/tailcfg.go, tstest/integration/integration_test.go, tstest/integration/testcontrol/testcontrol.go, types/ipproto/ipproto.go
This change generalizes the natConfig type in the data plane to handle both ipv6 and ipv4 addresses. The existing implementation is unchanged, the main changes are just struct structuring and construction of the NAT tables for different address families.
The existing NAT test is updated to also run with v6 addresses and passes fine.
I will need someone with a v6 internet connection to test this manually. This probably looks like:
1. Pulling my changes
2. Enabling mullvad and configuring it for your local node
3. Yeeting some change to set `SelfNodeV6MasqAddrForThisPeer` appropriately for the mullvad peers (/cc @james what would this be?)
4. Building/running locally and see if you can send v6 traffic over Mullvad
=> net/tstun: finish wiring IPv6 NAT support

hostinfo/hostinfo.go, hostinfo/wol.go, ipn/ipnlocal/c2n.go, ipn/ipnlocal/peerapi.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go
This optionally uploads MAC address(es) to control, then adds a
c2n handler so control can ask a node to send a WoL packet.
Updates #306
=> hostinfo, ipnlocal: flesh out Wake-on-LAN support, send MACs, add c2n sender

ipn/ipnlocal/local.go, net/dns/resolver/tsdns.go
Advertise it on Android (it looks like it already works once advertised).
And both advertise & likely fix it on iOS. Yet untested.
Updates #9672
=> net/dns/resolver, ipnlocal: fix ExitDNS on Android and iOS

client/web/web.go, client/web/web_test.go, ipn/ipnstate/ipnstate.go
Adds `getTailscaleBrowserSession` to pull the user's session out of api requests, and `serveTailscaleAuth` to provide the "/api/auth" endpoint for browser to request auth status and new sessions.
=> client/web: restrict full management client behind browser sessions

cmd/tailscale/cli/status.go, cmd/tailscale/cli/up.go
Add available update message in "tailscale up" output. Also update the message in "tailscale status" to match and mention auto-update.
Note: we might need to remove the `tailscale set --auto-update` part if we don't finish everything before 1.52 release.
Updates https://github.com/tailscale/tailscale/issues/755
=> cmd/tailscale/cli: add update notification to "up"

api.md
We don't actually send this. It's always been empty.
Updates tailscale/corp#13400
=> api.md: remove clientConnectivity.derp field

clientupdate/clientupdate.go, cmd/tailscale/cli/update.go
In case cli.Stdout/Stderr get overriden, all CLI output should use them instead of os.Stdout/Stderr. Update the `update` command to follow this pattern.
=> clientupdate,cmd/tailscale/cli: use cli.Stdout/Stderr

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi_test.go, taildrop/retrieve.go, taildrop/send.go, taildrop/taildrop.go, taildrop/taildrop_test.go
Changes made:
* Unexport declarations specific to internal taildrop functionality.
* Document all exported functionality.
* Move TestRedactErr to the taildrop package.
* Rename and invert Handler.DirectFileDoFinalRename as AvoidFinalRename.
=> taildrop: document and cleanup the package

syncs/syncs.go, syncs/syncs_test.go
I was reviewing some code that was performing this by hand, and wanted to suggest using syncs.Map, however as the code in question was allocating a non-trivial structure this would be necessary to meet the target.
=> syncs: add Map.LoadOrInit for lazily initialized values

tstest/resource.go, wgengine/magicsock/magicsock_test.go
To find potential flakes earlier.
Updates #deflake-effort
=> tstest: make ResourceCheck panic on parallel tests

docs/sysv/tailscale.init
The script depends on a sufficiently recent start-stop-daemon as to provide the `-m` and `--remove-pidfile` flags.
Updates #9502
=> docs/sysv: add a sysv style init script

cmd/tailscale/cli/debug.go, ipn/ipnlocal/local.go, ipn/localapi/localapi.go, wgengine/magicsock/magicsock.go
For testing netmap patchification server-side.
Updates #1909
=> cmd/tailscale, magicsock: add debug command to flip DERP homes

cmd/sniproxy/sniproxy.go
This PR enables setting a hostname for an sniproxy by specifying --hostname <hostname> on the command line.
=> cmd/sniproxy: allow configuration of hostname via command line argument

disco/disco.go, net/tstun/mtu.go, net/tstun/mtu_test.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/magicsock/peermtu.go
disco,net/tstun,wgengine/magicsock: probe and record peer MTU
Automatically probe and record the path MTU to a peer when peer MTU is enabled, 
but do not use the MTU information for anything other than metrics yet.
Updates #311
=> disco,net/tstun,wgengine/magicsock: probe and record peer MTU

ipn/localapi/localapi.go, ipn/localapi/localapi_test.go
The whois handler was documented as taking IP (e.g. 100.101.102.103)
or IP:port (e.g. usermode 127.0.0.1:1234) but that got broken at some point
and we started requiring a port always. Fix that.
Also, found in the process of adding tests: fix the CapMap lookup in
userspace mode (it was always returning the caps of 127.0.0.1 in
userspace mode). Fix and test that too.
Updates #9714
=> ipn/localapi: make whois take IP or IP:port as documented, fix capmap netstack lookup

tailcfg/tailcfg.go
This will be returned from the upcoming control endpoints for doing web client session authentication.
Updates #tailscale/corp#14335
=> tailcfg: add type for web client auth response

util/linuxfw/detector.go, util/linuxfw/iptables.go, util/linuxfw/iptables_runner.go, util/linuxfw/linuxfw_unsupported.go, util/linuxfw/nftables.go, util/linuxfw/nftables_runner.go, util/linuxfw/nftables_runner_test.go, wgengine/router/router_linux.go, wgengine/router/router_linux_test.go
Just a refactor to consolidate the firewall detection logic in a single package so that it can be reused in a later commit by containerboot.
Updates #9310
=> util/linuxfw: move detection logic

util/cmpver/version.go, util/cmpver/version_test.go
=> util/cmpver: only consider ascii numerals

util/linuxfw/fake.go, util/linuxfw/iptables_runner_test.go
This allows using the fake runner in different packages that need to manage filter rules.
=> util/linuxfw: move fake runner into pkg

cmd/containerboot/main.go, cmd/containerboot/main_test.go, util/linuxfw/iptables_runner.go, util/linuxfw/nftables_runner.go, wgengine/router/router_linux_test.go
This migrates containerboot to reuse the NetfilterRunner used by tailscaled instead of manipulating iptables rule itself. This has the added advantage of now working with nftables and we can potentially drop the `iptables` command from the container image in the future.
Updates #9310
=> cmd/containerboot: use linuxfw.NetfilterRunner

cmd/k8s-operator/manifests/operator.yaml
Replace the deprecated var with the one in docs to avoid confusion. Introduced in 335a5aaf9a25cb6969f7c043567425e7070ab21e.
Updates #8317
Fixes #9764
=> cmd/k8s-operator: update env var in manifest to APISERVER_PROXY

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi.go, ipn/ipnlocal/peerapi_test.go, taildrop/retrieve.go, taildrop/send.go, taildrop/taildrop.go, taildrop/taildrop_test.go
Changes made:
* Move all HTTP related functionality from taildrop to ipnlocal.
* Add two arguments to taildrop.Manager.PutFile to specify an opaque client ID and a resume offset (both unused for now).
* Cleanup the logic of taildrop.Manager.PutFile to be easier to follow.
* Implement file conflict handling where duplicate files are renamed (e.g., "IMG_1234.jpg" -> "IMG_1234 (2).jpg").
* Implement file de-duplication where "renaming" a partial file simply deletes it if it already exists with the same contents.
* Implement conflicting active puts where a second concurrent put results in an error.
=> taildrop: improve the functionality and reliability of put

client/web/web.go
Updates https://github.com/tailscale/corp/issues/15215.
=> client/web: add metric for exit node advertising

tstime/tstime.go
In almost every single use of Clock, there is a default behavior we want to use when the interface is nil, which is to use the the standard time package.
The Clock interface exists only for testing, and so tests that care about mocking time can adequately plumb the the Clock down the stack and through various data structures.
However, the problem with Clock is that there are many situations where we really don't care about mocking time (e.g., measuring execution time for a log message), where making sure that Clock is non-nil is not worth the burden. In fact, in a recent refactoring, the biggest pain point was dealing with nil-interface panics when calling tstime.Clock methods where mocking time wasn't even needed for the relevant tests. This required wasted time carefully reviewing the …
=> tstime: add DefaultClock

ipn/ipnlocal/cert.go, ipn/ipnlocal/cert_js.go, ipn/ipnlocal/serve.go, ipn/localapi/cert.go
We were eagerly doing a synchronous renewal of the cert while trying to serve traffic. Instead of that, just do the cert renewal in the background and continue serving traffic as long as the cert is still valid.
Fixes #9783
=> ipn/ipnlocal: do unexpired cert renewals in the background

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi_test.go, taildrop/resume.go, taildrop/resume_test.go, taildrop/retrieve.go, taildrop/send.go, taildrop/taildrop.go
We add the following API:
* type FileChecksums
* type Checksum
* func Manager.PartialFiles
* func Manager.HashPartialFile
* func ResumeReader
The Manager methods provide the ability to query for partial files and retrieve a list of checksums for a given partial file. The ResumeReader function is a helper that wraps an io.Reader to discard content that is identical locally and remotely. The FileChecksums type represents the checksums of a file and is safe to JSON marshal and send over the wire.
=> taildrop: add logic for resuming partial files

util/httphdr/httphdr.go, util/httphdr/httphdr_test.go
This adds support for parsing Range and Content-Range headers according to RFC 7230. The package could be extended in the future to handle other headers.
=> util/httphdr: add new package for parsing HTTP headers

tstest/integration/integration.go, tstest/integration/integration_test.go
Misc cleanups and things noticed while working on #7894 and pulled out
of a separate change. Submitting them on their own to not distract
from later changes.
Updates #7894
=> tstest/integration: set race flag when cross compiling, fail on race

.github/workflows/test.yml
They're slow. Make them their own job that can run in parallel.
Also, only run them in race mode. No need to run them on 386 or non-race amd64.
Updates #7894
=> github/workflows: move race tests to their own job

.github/workflows/test.yml
Move the compilation of everything to its own job too, separate from test execution.
Updates #7894
=> .github/workflows: break up race builder a bit more

ipn/ipnlocal/c2n.go, util/syspolicy/policy_keys.go
This commit changes the PostureChecking syspolicy key to be a PreferenceOption(user-defined, always, never) instead of Bool.
This aligns better with the defaults implementation on macOS allowing CLI arguments to be read when user-defined or no defaults is set.
=> ipn/ipnlocal: change serial number policy to be PreferenceOption

ipn/localapi/localapi.go
Debug endpoint for the web client's auth flow to talk back to the control server. Restricted behind a feature flag on control.
We will either be removing this debug endpoint, or renaming it before launching the web client updates.
=> ipn/localapi: add debug-web-client endpoint

clientupdate/clientupdate.go, ipn/ipnlocal/c2n.go
The Sparkle-based update is not quite working yet. Make `NewUpdater` return `ErrUnsupported` for it to avoid the proliferation of exceptions up the stack.
Updates #755
=> clientupdate: return ErrUnsupported for macSys clients

ipn/ipnlocal/local.go
The old code would always retain value `true` if it was set once, even if you then change `prefs.AutoUpdate.Apply` to `false`. Instead of using the previous value, use the default (envknob) value to OR with.
Updates #755
=> ipn/ipnlocal: fix AllowsUpdate disable after enable

cmd/containerboot/main.go, cmd/containerboot/main_test.go
This partially reverts commits a61a9ab087e16270bc039252e7620aae4de3d56e and 7538f386710b80c6b4c1997797be28a661210d4a and fully reverts 4823a7e591ef859250114ad20b337d4358af9ead.
The goal of that commit was to reapply known config whenever the container restarts. However, that already happens when TS_AUTH_ONCE was false (the default back then). So we only had to selectively reapply the config if TS_AUTH_ONCE is true, this does exactly that.
This is a little sad that we have to revert to `tailscale up`, but it fixes the backwards incompatibility problem.
Updates tailscale/tailscale#9539
=> cmd/containerboot: revert to using tailscale up

.github/workflows/test.yml, cmd/testwrapper/args.go, cmd/testwrapper/args_test.go, cmd/testwrapper/testwrapper.go
Previously we were just smushing together args and not trying to parse the values at all. This resulted in the args to testwrapper being limited and confusing.
This makes it so that testwrapper parses flags exactly like the `go test` command and passes them down in the provided order.
Updates tailscale/corp#14975
=> cmd/testwrapper: parse args better

cmd/k8s-operator/manifests/proxy.yaml, cmd/k8s-operator/operator_test.go, cmd/k8s-operator/sts.go, docs/k8s/proxy.yaml
We already have sysctl in the `tailscale/tailscale` image, just use that.
=> cmd/k8s-operator: use our own container image instead of busybox

cmd/k8s-operator/manifests/operator.yaml, cmd/k8s-operator/operator.go, cmd/k8s-operator/operator_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/svc.go
Users can now set `PROXY_FIREWALL_MODE` on the operator manifest to {nftables, iptables, auto} to configure what firewall mode ingress/egress proxies will use (if `PROXY_FIREWALL_MODE` is set, operator will set `TS_DEBUG_FIREWALL_MODE` env var for ingress/egress proxies)
Setting this value will update firewall mode for all currently deployed ingress/egress proxies.
Updates #9310
=> cmd/k8s-operator: users can configure firewall mode for kube operator proxies

cmd/tailscale/cli/status.go, cmd/tailscale/cli/up.go, tailcfg/tailcfg.go
This flag is used in clients to surface urgent updates more prominently.
Updates #755
=> tailcfg,cmd/tailscale: add UrgentSecurityUpdate flag to ClientVersion

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi_test.go, taildrop/delete.go, taildrop/delete_test.go, taildrop/resume.go, taildrop/resume_test.go, taildrop/retrieve.go, taildrop/send.go, taildrop/taildrop.go, taildrop/taildrop_test.go
File resumption requires keeping partial files around for some time, but we must still eventually delete them if never resumed. Thus, we implement asynchronous file deletion, which could spawn a background goroutine to delete the files.
We also use the same mechanism for deleting files on Windows, where a file can't be deleted if there is still an open file handle. We can enqueue those with the asynchronous file deleter as well.
=> taildrop: implement asynchronous file deletion

clientupdate/clientupdate.go, ipn/ipnlocal/c2n.go
Two bug fixes:
1. when tailscale update is executed as root, `os.UserCacheDir` may return an error because `$XDG_CACHE_HOME` and `$HOME` are not set; fallback to `os.TempDir` in those cases
2. on some weird distros (like my EndeavourOS), `/usr/sbin` is just a symlink to `/usr/bin`; when we resolve `tailscale` binary path from `tailscaled`, allow `tailscaled` to be in either directory
Updates #755
=> clientupdate: fix background install for linux tarballs

ipn/ipnlocal/peerapi.go, ipn/localapi/localapi.go
Minor fixes:
* The branch for listing or hashing partial files was inverted.
* The host for peerapi call needs to be real (rather than bogus).
* Handle remote peers that don't support resuming.
* Make resume failures non-fatal (since we can still continue).
This was tested locally, end-to-end system test is future work.
=> ipn: fix localapi and peerapi protocol for taildrop resume

util/linuxfw/nftables.go, util/linuxfw/nftables_runner.go, util/linuxfw/nftables_runner_test.go
We were previously using the netlink API to see if there are chains/rules that already exist. This works fine in environments where there is either full nftable support or no support at all. However, we have identified certain environments which have partial nftable support and the only feasible way of detecting such an environment is to try to create some of the chains that we need.
This adds a check to create a dummy postrouting chain which is immediately deleted. The goal of the check is to ensure we are able to use nftables and that it won't error out later. This check is only done in the path where we detected that the system has no nftable rules.
Updates #5621
Updates #8555
Updates #8762
=> util/linuxfw: add additional nftable detection logic

syncs/syncs.go, syncs/syncs_test.go
The LoadFunc loads a value and calls a user-provided function. The utility of this method is to ensure that the map lock is held while executing user-provided logic.
This allows us to solve TOCTOU bugs that would be nearly imposible to the solve without this API.
=> syncs: add Map.LoadFunc

taildrop/resume_test.go
This test is currently failing on Windows.
=> taildrop: disable TestResume

cmd/tsconnect/wasm/wasm_js.go
It's required as of the recent 5297bd2cff8e.
Updates #7894
Updates #9394 (sure would be nice)
=> cmd/tsconnect/wasm: add missing tstun.Wrapper.Start call

taildrop/resume_test.go
Previously, the test simply relied on:
defer close()
to cleanup file handles.
This works fine on Unix-based systems,
but not on Windows, which dislikes deleting files
where an open file handle continues to exist.
Fix the test by explicitly closing the file handle after we are done with the resource.
=> taildrop: fix TestResume

wgengine/magicsock/magicsock_linux.go
Don't assume Linux lacks UDP_GRO support if it lacks UDP_SEGMENT support. This mirrors a similar change in wireguard/wireguard-go@177caa7 for consistency sake. We haven't found any issues here, just being overly paranoid.
=> wgengine/magicsock: simplify tryEnableUDPOffload()

ipn/ipnlocal/serve.go, ipn/ipnlocal/serve_test.go
Makes it possible for the proxy to work with a gRPC over h2c backend by detecting tha the request is for a grpc service + using prior knowledge of the proxy configuration to determine that it's not HTTPS.
This seems to be the best that we can do- @maisem and I were originally discussing detecting that it is an h2c backend, however it seems that the only way to reliably do this is with prior knowledge see https://datatracker.ietf.org/doc/html/rfc9113#name-http-2-version-identificati:~:text=The%20means%20by,%C2%B6
It seems like using the proxy host protocol prefix + request's proto + request's content type header should be sufficient for plaintext gRPC backends because:
- if the backend has an 'http' prefix, we at that point know that it's http (it would anyway likely not work if there was …
=> ipn/ipnlocal: proxy gRPC requests over h2c if needed

client/web/src/components/app.tsx, client/web/src/hooks/auth.ts, client/web/web.go, client/web/web_test.go, ipn/localapi/localapi.go
Connects serveTailscaleAuth to the localapi webclient endpoint and pipes auth URLs and session cookies back to the browser to redirect users from the frontend.
All behind debug flags for now.
=> client/web: hook up auth flow

cmd/tailscale/cli/serve_v2.go, cmd/tailscale/cli/serve_v2_test.go
The `off` subcommand removes a serve/funnel for the corresponding type and port. Previously, we were not providing this which would result in an error if someone was using something than the default https=443.
closes #9858
=> cmd/tailscale/cli: [serve/funnel] provide correct command for disabling

cmd/tailscale/cli/serve_v2.go, cmd/tailscale/cli/serve_v2_test.go
The `serve` command for TCP  has always required the scheme of the target to be specified. However, when it's omitted the error message reported is misleading
```
error: failed to apply TCP serve: invalid TCP target "localhost:5900": missing port in address
```
Since we know the target is TCP, we shouldn't require it to be specified. This aligns with the changes for HTTP proxies in https://github.com/tailscale/tailscale/issues/8489
closes https://github.com/tailscale/tailscale/issues/9855
=> cmd/tailscale/cli: [serve/funnel] support omitting scheme for TCP

ipn/ipnlocal/local.go
Apple frontends will now understand this Notify field and handle it.
Updates #755
=> ipn/ipnlocal: send ClientVersion to Apple frontends

taildrop/delete.go, taildrop/delete_test.go, taildrop/resume.go, taildrop/retrieve.go, taildrop/taildrop.go
It is possible that upon a cold-start, we enqueue a partial file for deletion that is resumed shortly after startup.
If the file transfer happens to last longer than deleteDelay, we will delete the partial file, which is unfortunate.
The client spent a long time uploading a file, only for it to be accidentally deleted.
It's a very rare race, but also a frustrating one if it happens to manifest.
Fix the code to only delete partial files that do not have an active puts against it.
We also fix a minor bug in ResumeReader where we read `b[:blockSize]` instead of `b[:cs.Size]`.
The former is the fixed size of 64KiB, while the latter is usually 64KiB, but may be less for the last block.
=> taildrop: fix theoretical race condition in fileDeleter.Init

ipn/ipnlocal/local.go, ipn/ipnlocal/serve.go, ipn/ipnlocal/serve_test.go
Fixes a bug in type conversion when reloading userspace proxy config.
Ensures that for if http or http2 transport connections have been open for a proxy, they will be closed when the proxy is removed.
I've tested this by hand using a kube ingress for tailscale operator with multiple backends and observed that connections are successfully closed after one backend gets removed.
Updates tailscale/tailscale#9725
=> ipn/ipnlocal: close connections for removed proxy transports

client/web/web.go, ipn/localapi/localapi.go
This commit makes two changes to the web client auth flow error handling:
1. Properly passes back the error code from the noise request from the localapi. Previously we were using io.Copy, which was always setting a 200 response status code.
2. Clean up web client browser sessions on any /wait endpoint error. This avoids the user getting in a stuck state if something goes wrong with their auth path.
=> ipn/localapi,client/web: clean up auth error handling

ipn/ipnlocal/local.go, ipn/ipnlocal/serve.go
This adds a check to prevent changes to ServeConfig if tailscaled is run with a Locked config.
Missed in 1fc3573446a9bb2411bb6b68864368fd1e465b7e.
Updates #1412
=> ipn/ipnlocal: prevent changing serve config if conf.Locked

ipn/localapi/localapi.go
Go has no way to explicitly identify Go struct as effectively a tuple, so staticcheck assumes any external use of unkeyed literals is wrong.
=> ipn/localapi: avoid unkeyed literal

hostinfo/hostinfo.go, ipn/ipnlocal/local.go, ipn/localapi/localapi.go, ipn/localapi/localapi_test.go
It would end up resetting whatever hostinfo we had constructed
and leave the backend statemachine in a broken state.
This fixes that by storing the PushDeviceToken on the LocalBackend
and populating it on Hostinfo before passing it to controlclient.
Updates #tailscale/corp#8940
=> ipn/ipnlocal: set the push device token correctly 

cmd/tailscale/cli/serve_v2.go, cmd/tailscale/cli/serve_v2_test.go
This PR fixes the isLegacyInvocation to better catch serve and funnel legacy commands. In addition, it now also returns a string that translates the old command into the new one so that users can have an easier transition story.
Updates #8489
=> cmd/tailscale: translate old serve commands to new ones

cmd/tailscale/cli/serve_v2.go
This PR adds the same set-raw from the old flow into the new one so that users can continue to use it when transitioning into the new flow.
Updates #8489
=> cmd/tailscale: add set-raw to the new serve funnel commands

cmd/tailscale/cli/serve_v2.go, cmd/tailscale/cli/serve_v2_test.go
* Fixes issue with template string not being provided in help text
* Updates background information to provide full URL, including path, to make it clear the source and destination
* Restores some tests
* Removes AllowFunnel in ServeConfig if no proxy exists for that port.
updates #8489
=> cmd/tailscale/cli: updates help and background messaging

wgengine/netstack/netstack.go
Prior to an earlier netstack bump this code used a string conversion path to cover multiple cases of behavior seemingly checking for unspecified addresses, adding unspecified addresses to v6. The behavior is now crashy in netstack, as it is enforcing address length in various areas of the API, one in particular being address removal.
As netstack is now protocol specific, we must not create invalid protocol addresses - an address is v4 or v6, and the address value contained inside must match. If a control path attempts to do something otherwise it is now logged and skipped rather than incorrect addressing being added.
Fixes tailscale/corp#15377
=> wgengine/netstack: only add addresses to correct protocols

clientupdate/clientupdate.go, cmd/tailscale/cli/set.go, ipn/ipnlocal/c2n.go
clientupdate.Updater will have a non-nil Update func in a few cases where it doesn't actually perform an update:
* on Arch-like distros, where it prints instructions on how to update
* on macOS app store version, where it opens the app store page
Add a new clientupdate.Arguments field to cause NewUpdater to fail when we hit one of these cases. This results in c2n updates being "not supported" and `tailscale set --auto-update` returning an error.
Updates #755
=> clientupdate: distinguish when auto-updates are possible

wgengine/magicsock/magicsock.go
TestNewConn now passes as root on Linux. It wasn't closing the BPF listeners and their goroutines.
The code is still a mess of two Close overlapping code paths, but that can be refactored later. For now, make the two close paths more similar.
Updates #9945
=> wgengine/magicsock: close disco listeners on Conn.Close, fix Linux root TestNewConn

derp/derphttp/derphttp_client.go
When trying to set up multiple derper instances meshing with each other, it turned out that while one can specify an alternative listening port using the `-a` flag, the TLS hostname gets incorrectly determined and includes the set alternative listening port as part of the hostname. Thus, the TLS hostname validation always fails when the `-mesh-with` values have ports.
This PR addresses this by using the [`Hostname`](https://pkg.go.dev/net/url#URL.Hostname) function instead of the [`Host`](https://pkg.go.dev/net/url#URL.Host) field.
=> Fix tlsServerName not stripping port numbers if present

cmd/tailscale/cli/serve_v2.go, cmd/tailscale/cli/serve_v2_test.go
A few people have run into issues with understanding why `--set-path` started in background mode, and/or why they couldn't use a path in foreground mode. This change allows `--set-path` to be used in either case (foreground or background).
=> cmd/tailscale/cli: serve --set-path should not force background mode

clientupdate/clientupdate.go, cmd/tailscale/cli/set.go, version/prop.go
On `tailscale set --auto-update`, set the Sparkle plist option for it. Also make macsys report not supporting auto-updates over c2n, since they will be triggered by Sparkle locally.
Updates #755
=> cmd/tailscale/cli: set Sparkle auto-update on macsys

cmd/tailscale/cli/serve_v2.go, cmd/tailscale/cli/serve_v2_test.go
We currently print out "run tailscale serve --help" when the subcmd might be funnel. This PR ensures the right subcmd is passed.
Updates #8489
=> cmd/tailscale: fix help message for serve funnel

ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_windows.go, util/syspolicy/policy_keys.go
In addition to the new policy keys for the new options, some already-in-use but missing policy keys are also being added to util/syspolicy.
Updates ENG-2133
Change-Id: Iad08ca47f839ea6a65f81b76b4f9ef21183ebdc6
cc @nickoneill
=> ipn/ipnlocal: add new DNS and subnet router policies

client/web/web.go, client/web/web_test.go
Previously returned errTaggedSource in the case that of any tagged source. Now distinguishing whether the source was local or remote. We'll be presenting the two cases with varying copy on the frontend.
=> client/web: split errTaggedSelf resp from getTailscaleBrowserSession

ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_windows.go, util/syspolicy/policy_keys.go
Reverts tailscale/tailscale#9936. 
The change was causing unstable builds of the the macOS and macsys clients to crash on launch of the IPNExtension.
=> Revert "ipn/ipnlocal: add new DNS and subnet router policies"

cmd/tailscale/cli/serve_legacy.go, cmd/tailscale/cli/serve_v2.go, cmd/tailscale/cli/serve_v2_test.go
This PR changes the -https, -http, -tcp, and -tls-terminated-tcp flags from string to int and also updates the validation to ensure they fit the uint16 size as the flag library does not have a Uint16Var method.
Updates #8489
=> cmd/tailscale/cli: chage port flags to uint for serve and funnel

cmd/tailscale/cli/serve_v2.go, cmd/tailscale/cli/serve_v2_test.go
The `--http` flag can not be used with Funnel, so we should remove it to remove confusion.
Updates #8489
ENG-2316
=> cmd/tailscale/cli: remove http flag for funnel command

.github/workflows/checklocks.yml
Currently the checklocks step is not configured to fail, as we do not yet have the appropriate annotations.
Updates tailscale/corp#14381
=> .github/workflows: add checklocks

.github/workflows/test.yml
The branch name selector "*" doesn't match branches with a "/" in their name. The vast majority of our PRs are against the main (or previously, master) branch anyway, so this will have minimal impact. But in the rare cases that we want to open a PR against a branch with a "/" in the name, tests should still run.
```
gh pr list --limit 9999 --state all --json baseRefName | \
jq -cs '.[] | group_by(.baseRefName) |
map({ base: .[0].baseRefName, count: map(.baseRefName) | length}) |
sort_by(-.count) | .[]'
{"base":"main","count":4593}
{"base":"master","count":226}
{"base":"release-branch/1.48","count":4}
{"base":"josh-and-adrian-io_uring","count":3}
{"base":"release-branch/1.30","count":3}
{"base":"release-branch/1.32","count":3}
{"base":"release-branch/1.20","count":2} …
```
=> .github: run tests on all PRs, regardless of branch name

client/web/src/components/app.tsx, client/web/src/components/views/legacy-client-view.tsx, client/web/src/components/views/login-client-view.tsx, client/web/src/components/views/management-client-view.tsx, client/web/src/components/views/readonly-client-view.tsx, client/web/src/ui/profile-pic.tsx
This commit makes the following structural changes to the web client interface. No user-visible changes.
1. Splits login, legacy, readonly, and full management clients into their own components, and pulls them out into their own view files.
2. Renders the same Login component for all scenarios when the client is not logged in, regardless of legacy or debug mode. Styling comes from the existing legacy login, which is removed from legacy.tsx now that it is shared.
3. Adds a ui folder to hold non-Tailscale-specific components, starting with ProfilePic, previously housed in app.tsx.
=> client/web: split out UI components

ipn/localapi/localapi.go, ipn/localapi/localapi_test.go, ipn/serve.go, ipn/serve_test.go
For a serve config with a path handler, ensure the caller is a local administrator on Windows.
=> ipn/localapi: require local Windows admin to set serve path

cmd/tailscale/cli/funnel.go, cmd/tailscale/cli/serve_legacy.go, cmd/tailscale/cli/serve_legacy_test.go, cmd/tailscale/cli/serve_v2.go
We were inconsistent whether we checked if the feature was already enabled which we could do cheaply using the locally available status. We would do the checks fine if we were turning on funnel, but not serve.
This moves the cap checks down into enableFeatureInteractive so that are always run.
Updates #9984
=> cmd/tailscale/cli: use status before doing interactive feature query

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
tvOS cannot accept files so we do not want to show them in the target list for taildrop.
Fixes #9903
=> ipn/ipnlocal: exclude tvOS devices from taildrop file targets

util/linuxfw/nftables_runner_test.go
This would surface as panics when run on Fly. Still fail, but at least don't panic.
Updates #10003
=> util/linuxfw: add missing error checks in tests

net/dns/recursive/recursive.go
As of 2023-11-27, the official IP addresses for b.root-servers.net will change to a new set, with the older IP addresses supported for at least a year after that date. These IPs are already active and returning results, so update these in our recursive DNS resolver package so as to be ready for the switchover.
See: https://b.root-servers.org/news/2023/05/16/new-addresses.html
Fixes #9994
Change-Id: I29e2fe9f019163c9ec0e62bdb286e124aa90a487
=> net/dns/recursive: update IP for b.root-servers.net

ipn/localapi/localapi.go
This PR adds a new `handle-push-message` local API endpoint. When an APNS payload is delivered to the main app, this endpoint can be used to forward the JSON body of the message to the backend, making a POST request.
Fixes #9971. 
Updates #9845.
cc @bradfitz
=> ipn/localapi: add endpoint to handle APNS payloads

cmd/tailscale/cli/cli_test.go, ipn/conf.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/local.go, ipn/ipnlocal/web.go, ipn/ipnlocal/web_stub.go, ipn/localapi/localapi.go, ipn/prefs.go, ipn/prefs_test.go
instead of starting a separate server listening on a particular port to serve the web client, use the TCPHandlerForDst method to intercept requests for the special web client port (currently 5252, probably configurable later).  Add a new user pref that tracks whether the web client should be enabled or not.
Updates https://github.com/tailscale/corp/issues/14335
=> ipn: serve web client requests from LocalBackend.TCPHandlerForDst

appc/appc.go, cmd/sniproxy/sniproxy.go, cmd/sniproxy/sniproxy_test.go, tstest/integration/testcontrol/testcontrol.go
* Implement missing tests for sniproxy
* Wire sniproxy to new appc package
* Add support to tsnet for routing subnet router traffic into netstack, so it can be handled
Updates: https://github.com/tailscale/corp/issues/15038
=> cmd/sniproxy: implement support for control configuration, multiple addresses

types/appctype/appconnector.go
Updates: https://github.com/tailscale/corp/issues/15440
Code-authored-by: Podtato <podtato@tailscale.com>
=> types/appctype: define the nodeAttrs type for dns-driven app connectors

ipn/ipnlocal/local.go, ipn/ipnlocal/web_client.go, ipn/ipnlocal/web_client_stub.go, ipn/localapi/localapi.go
For consistency and clarity around what the LocalBackend.web field is used for.
=> ipn/ipnlocal: rename web fields/structs to webClient

clientupdate/clientupdate.go
Not all users know about our tracks and versioning scheme. They can be confused when e.g. 1.52.0 is out but 1.53.0 is available. Or when 1.52.0 is our but 1.53 has not been built yet and user is on 1.51.x.
Mentioning the track in output should hint at why update is not happening.
=> clientupdate: mention release track when running latest

cmd/tailscaled/tailscaled.go, ipn/ipnlocal/local.go, ipn/ipnlocal/web_client.go, tailcfg/tailcfg.go
The web client in tailscaled is now enabled by setting the "preview-webclient" node capability in the tailnet policy file:
```json
"nodeAttrs": [
{"target": ["*"], "attr": ["preview-webclient"]},
],
```
This makes it much easier to test on real NAS devices where setting additional environment variables is kind of a pain.  We still need to update the client itself to no longer require the `--dev` flag or `TS_DEBUG_WEB_CLIENT_MODE` var.
=> ipn: replace web client debug flag with node capability

derp/derphttp/derphttp_test.go
=> derp/derphttp: close DERP client to avoid data race in test

.github/workflows/kubemanifests.yaml, cmd/k8s-operator/deploy/chart/Chart.yaml
Helm chart was failing helm linter because I had added `type` field which only appears in Helm API v2.
I have upgraded the chart to use API v2 - as I understand [the main difference is that v2 does not support helm v2 deployment mechanism](https://helm.sh/docs/topics/charts/#the-apiversion-field)- but this is [long deprecated](https://helm.sh/blog/helm-v2-deprecation-timeline/) and I have not heard that anyone would still use that.
both v1 and v2 API versions are use by other projects:
- https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/Chart.yaml#L5
- https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/Chart.template.yaml#L1
Also added a CI test that packages chart and runs helm linter.
Updates tailscale/tailscale#9222
=> cmd/k8s-operator/deploy/chart,.github/workflows: use helm chart API v2

clientupdate/clientupdate.go
The built-in update will not work properly on Unraid since the system runs from memory and "reinstalls" itself on every boot. Updates must be applied via the Unraid plugin system since this will allow the update to persist across reboots.
If users attempt to use the built-in updater, they could encounter unusual behavior (Tailscale rolling back on restart, Unraid errors, etc.).
Updates dkaser/unraid-tailscale#94
=> clientupdate: disable on Unraid

client/web/auth.go, client/web/web.go
=> client/web: move session logic to auth.go

net/dnscache/dnscache.go
The other IP types don't appear to be imported anymore, and after a scan through I couldn't see any substantial usage of other representations, so I think this TODO is complete.
=> net/dnscache: remove completed TODO

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/set.go, cmd/tailscale/cli/up.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/prefs.go, ipn/prefs_test.go
Introduce a preference structure to store the setting for app connector
advertisement.
Introduce the associated flags:
tailscale up --advertise-connector{=true,=false}
tailscale set --advertise-connector{=true,=false}
```
% tailscale set --advertise-connector=false
% tailscale debug prefs | jq .AppConnector.Advertise
false
% tailscale set --advertise-connector=true
% tailscale debug prefs | jq .AppConnector.Advertise
true
% tailscale up --advertise-connector=false
% tailscale debug prefs | jq .AppConnector.Advertise
false
% tailscale up --advertise-connector=true
% tailscale debug prefs | jq .AppConnector.Advertise
true
```
Updates https://github.com/tailscale/corp/issues/15437
=> ipn: introduce app connector advertisement preference and flags

client/web/src/components/app.tsx, client/web/web.go
For now this is effectively a noop, since only the ManagementClientView uses the auth data. That will change soon.
=> client/web: call /api/auth before rendering any client views

cmd/k8s-operator/proxy.go
=> cmd/k8s-operator: strip credentials from client config in noauth mode

clientupdate/clientupdate.go
Make the error message a bit more helpful for users.
Updates #9456
=> clientupdate: clarify how to run update as Administrator on Windows

client/web/src/api.ts, client/web/src/hooks/auth.ts, client/web/web.go
When the /api/auth response indicates that synology auth is needed, fetch the SynoToken and store it for future API calls.  This doesn't yet update the server-side code to set the new SynoAuth field.
=> web/client: update synology token from /api/auth call

client/web/auth.go, client/web/web.go, client/web/web_test.go
=> client/web: move more session logic to auth.go

ipn/ipnlocal/local.go
WebClientShutdown tries to acquire the b.mu lock, so run it in a go routine so that it can finish shutdown after setPrefsLockedOnEntry is finished. This is the same reason b.sshServer.Shutdown is run in a go routine.
=> ipn/ipnlocal: prevent deadlock on WebClientShutdown

tstest/deptest/deptest.go
Fixes https://github.com/tailscale/tailscale/security/code-scanning/112
=> tstest/deptest: fix minor escaping error in regex

util/groupmember/groupmember.go
Noticed both while re-reading this code.
=> util/groupmember: fail earlier if group doesn't exist, use slices.Contains

cmd/k8s-operator/operator.go, cmd/k8s-operator/proxy.go
This PR fixes a bug where, although we intend to set different app type for operator with proxy enabled vs disabled, it was in practice always set to 'k8s-operator' because that code path got hit first and early.
I have tested this fix by deploying operator from this PR with the proxy enabled and checked that 'App' gets set to 'k8s-operator-proxy'. This can be observed in the operator logs if the logging level is set to 'debug':
```
k logs deploy/operator -n tailscale
...
{"level":"debug","ts":"2023-11-02T13:13:44Z","logger":"tailscaled","msg":"control: [v1] HostInfo: {\"IPNVersion\":\"1.53.51-t50aeac003\",\"BackendLogID\":\"7aa1bca5af2cdc83c59b51a77c57f8b871dc188455862c4d36797a11a4d0edf3\",\"OS\":\"linux\",\"OSVersion\":\"5.15.120+\",\"Container\":false,\"Env\":\"k8s\",\"Distro\":\"alpine …
```
=> cmd/k8s-operator: set different app type for operator with proxy enabled/disabled

ipn/ipnlocal/local.go, ipn/ipnlocal/web_client.go
Now uses webClientAtomicBool as the source of truth for whether the web client should be running in tailscaled, with it updated when either the RunWebClient pref or CapabilityPreviewWebClient node capability changes.
This avoids requiring holding the LocalBackend lock on each call to ShouldRunWebClient to check for the CapabilityPreviewWebClient value.
=> ipn/ipnlocal: pull CapabilityPreviewWebClient into webClientAtomicBool

ipn/localapi/localapi.go
Managing starting/stopping tailscaled web client purely via setting the RunWebClient pref.
=> ipn/localapi: remove webclient endpoint

clientupdate/clientupdate.go
After we're done installing, clean up the temp files. This prevents temp volumes from filling up on hosts that don't reboot often.
Fixes https://github.com/tailscale/tailscale/issues/10082
=> clientupdate: cleanup SPK and MSI downloads

client/web/qnap.go, client/web/src/components/app.tsx, client/web/src/hooks/auth.ts, client/web/synology.go, client/web/web.go, client/web/web_test.go
This completes the migration to setting up authentication state in the client first before fetching any node data or rendering the client view.
Notable changes:
- `authorizeRequest` is now only enforced on `/api/*` calls (with the exception of /api/auth, which is handled early because it's needed to initially setup auth, particularly for synology)
- re-separate the App and WebClient components to ensure that auth is completed before moving on
- refactor platform auth (synology and QNAP) to fit into this new structure. Synology no longer returns redirect for auth, but returns authResponse instructing the client to fetch a SynoToken
=> client/web: limit authorization checks to API calls

client/web/web.go, client/web/web_test.go, cmd/tailscale/cli/web.go, ipn/ipnlocal/web_client.go, tsnet/example/web-client/web-client.go
Adds a new Mode to the web server, indicating the specific scenario the constructed server is intended to be run in. Also
starts filling this from the cli/web and ipn/ipnlocal callers.
From cli/web this gets filled conditionally based on whether the preview web client node cap is set. If not set, the existing
"legacy" client is served. If set, both a login/lobby and full management client are started (in "login" and "manage" modes respectively).
=> client/web: add ServerMode to web.Server

ipn/localapi/localapi.go
The existing read permission check looks like an oversight. Write seems more appropriate for sining new nodes.
Updates https://github.com/tailscale/corp/issues/15506
=> ipn/localapi: make serveTKASign require write permission

client/web/web.go, cmd/tailscale/cli/web.go, ipn/ipnlocal/web_client.go, tsnet/example/web-client/web-client.go
Avoids the need to pipe a web client dev flag through the tailscaled command.
=> client/web: fill devMode from an env var

types/dnstype/dnstype.go
There was pre-existing additional usage for Exit Node DNS resolution via PeerAPI, as well as new usage just introduced for App Connectors.
Fixes ENG-2324
=> types/dnstype: update the usage documentation on dnstype.Resolver

ipn/ipnlocal/local.go
if the user pref and nodecap for the new web client are enabled, serve the client over requests to 100.100.100.100.  Today, that is just a static page that lists the local Tailcale IP addresses.
For now, this will render the readonly full management client, with an "access" button that sends the user through check mode.  After completing check mode, they will still be in the read-only view, since they are not accessing the client over Tailscale.
Instead, quad100 should serve the lobby client that has a "manage" button that will open the management client on the Tailscale IP (and trigger check mode). That is something we'll fix in a subsequent PR in the web client code itself.
=> ipn/ipnlocal: serve web client on quad100 if enabled

client/web/src/components/app.tsx, client/web/src/components/views/readonly-client-view.tsx, client/web/src/hooks/auth.ts, client/web/web.go, client/web/web_test.go
Splits auth session creation into two new endpoints:
/api/auth/session/new - to request a new auth session
/api/auth/session/wait - to block until user has completed auth url
=> client/web: move auth session creation out of /api/auth

ipn/ipnauth/ipnauth_windows.go, ipn/ipnserver/server.go, util/winutil/winutil_windows.go
(*Token).IsAdministrator is supposed to return true even when the user is running with a UAC limited token. The idea is that, for the purposes of this check, we don't care whether the user is *currently* running with full Admin rights, we just want to know whether the user can *potentially* do so.
We accomplish this by querying for the token's "linked token," which should be the fully-elevated variant, and checking its group memberships.
Fixes #10036
=> ipn/ipnauth: improve the Windows token administrator check

client/web/web.go, client/web/web_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/web_client.go, ipn/ipnlocal/web_client_stub.go
Require that requests to servers in manage mode are made to the Tailscale IP (either ipv4 or ipv6) or quad-100 in order to mitigate dns rebinding attacks. I don't love that this is fetching status from localapi on every single request to get local IPs, particularly since these values don't change often, so we'll probably want to cache these.
Also set various security headers on those responses.  These might be too restrictive, but we can relax them as needed.
Allow requests to /ok (even in manage mode) with no checks. This will be used for the connectivity check from a login client to see if the management client is reachable.
=> client/web: add some security checks for full client

client/web/web.go
r.URL.Host is not typically populated on server requests.
=> client/web: check r.Host rather than r.URL.Host

client/web/web.go
Don't return CSP headers in dev mode, since that includes a bunch of extra things like the vite server.
Allow images from any source, which is needed to load user profile images.
Allow 'unsafe-inline' for various inline scripts and style react uses. We can eliminate this by using CSP nonce or hash values, but we'll need to look into the best way to handle that. There appear to be several react plugins for this, but I haven't evaluated any of them.
=> client/web: relax CSP restrictions for manage client

client/tailscale/localclient.go
The error check on line 1254 means that this one is entirely redundant.
=> client/tailscale: remove redundant error check

control/controlclient/auto.go, control/controlclient/direct.go, control/controlclient/map.go
It was a really a mutable field owned by mapSession that we didn't move
in earlier commits.
Once moved, it's then possible to de-func-ify the code and turn it into
a regular method rather than an installed optional hook.
Noticed while working to move map session lifetimes out of
Direct.sendMapRequest's single-HTTP-connection scope.
Updates #7175
=> control/controlclient: move lastPrintMap field from Direct to mapSession

control/controlclient/direct.go, control/controlclient/map.go
In prep for making mapSession's lifetime not be 1:1 with a single HTTP
response's lifetime, this moves the inactivity timer watchdog out of
mapSession and into the caller that owns the streaming HTTP response.
(This is admittedly closer to how it was prior to the mapSession type
existing, but that was before we connected some dots which were
impossible to even see before the mapSession type broke the code up.)
Updates #7175
=> control/controlclient: move watchdog out of mapSession

client/web/vite.config.ts
Previously had HMR websocket set to run from a different port than the http proxy server. This was an old setting carried over from the corp repo admin panel config. It's messing with hot reloads when run from the tailscaled web client, as it keeps causing the full page to refresh each time a connection is made. Switching back to the default config here fixes things.
=> client/web: fix hotreload proxy

wgengine/magicsock/endpoint.go
This change updates log messaging when cleaning up wireguard only peers. This change also stops us unnecessarily attempting to clean up disco pings for wireguard only endpoints.
Updates #7826
=> wgengine/magicsock: handle wireguard only clean up and log messages

prober/derp.go
When using derpprobe to probe custom derp servers running on an alternative port, the prober always defaulted to port 443. 
It returned an error, even when the `DERPNode.DERPPort` was set to the alternative port.
This PR changes the hardcoded 443 port to the one specified in `DERPNode.DERPPort` if one is provided.
Fixes #10146
=> prober: Add support for custom DERP port in TLS prober

client/web/src/components/views/readonly-client-view.tsx, client/web/src/hooks/auth.ts
We render the readonly view in two situations:
- the client is in login mode, and the device is connected
- the client is in manage mode, but the user does not yet have a session
If the user is not authenticated, and they are not currently on the Tailscale IP address, render a "Manage" button that will take them to the Tailcale IP of the device and immediately start check mode.  This ends up being used for login clients and accessing the full client over quad100.
Still to do is detecting if they have connectivity to the Tailscale IP, and disabling the button if not.
=> client/web: show manage button in readonly view

client/web/src/components/app.tsx, client/web/src/hooks/node-data.ts, client/web/web.go
This allows wouter to route URLs properly when running in CGI mode.
=> client/web: pass URL prefix to frontend

appc/appconnector.go, ipn/ipnlocal/c2n.go, tailcfg/c2ntypes.go
This change introduces a c2n endpoint that returns a map of domains to a slice of resolved IP addresses for the domain.
Fixes tailscale/corp#15657
=> tailcfg,ipn,appc: add c2n endpoint for appc domain routes

ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi.go
App connectors handle DNS requests for app domains over PeerAPI, but a safety check verifies the requesting peer has at least permission to send traffic to 0.0.0.0:53 (or 2000:: for IPv6) before handling the DNS request. The correct filter rules are synthesized by the coordination server and sent down, but the address needs to be part of the 'local net' for the filter package to even bother checking the filter rules, so we set them here.
Updates https://github.com/tailscale/corp/issues/1196
Updates: ENG-2405
=> ipn/ipnlocal: add empty address to the app-connector localNets set

logtail/logtail.go, logtail/logtail_test.go
io.Writer says you need to write completely on err=nil. (the result int should be the same as the input buffer length)
We weren't doing that. We used to, but at some point the verbose filtering was modifying buf before the final return of len(buf).
We've been getting lucky probably, that callers haven't looked at our results and turned us into a short write error.
Updates tailscale/corp#15664
=> logtail: fix Logger.Write return result

tsnet/tsnet.go
This was mostly already fixed already indirectly in earlier commits but add a last second length check to this slice so it can't ever OOB.
Fixes #7860
=> tsnet: check a bit harder for https in Server.ListenFunnel

ipn/ipnlocal/local.go, ipn/ipnlocal/serve.go, ipn/ipnlocal/web_client.go, ipn/ipnlocal/web_client_stub.go
The local web client has the same characteristic as tailscale serve, in that it needs a local listener to allow for connections from the local machine itself when running in kernel networking mode.
This change renames and adapts the existing `serveListener` to allow it to be used by the web client as well.
cc @bradfitz who originally reviewed #6282 where this was added for tailscale serve.
=> ipn/ipnlocal: allow connecting to local web client in kernel networking mode

ssh/tailssh/tailssh.go
We were incrementing the sftp metric on regular sessions
too, not just sftp.
=> ssh/tailssh: fix sftp metric increment location

clientupdate/clientupdate.go, ipn/ipnlocal/c2n.go
Use the `qpkg_cli` to check for updates and install them. There are a couple special things about this compare to other updaters:
* qpkg_cli can tell you when upgrade is available, but not what the version is
* qpkg_cli --add Tailscale works for new installs, upgrades and reinstalling existing version; even reinstall of existing version takes a while
Updates #10178
=> clientupdate: add support for QNAP

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/policy/policy.go, tailcfg/tailcfg.go
This was never released, and is replaced by HostInfo.AppConnector.
Updates tailscale/corp#15437
=> ipn,tailconfig: clean up unreleased and removed app connector service

control/controlknobs/controlknobs.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock.go
This change exposes SilentDisco as a control knob, and plumbs it down to magicsock.endpoint. No changes are being made to magicsock.endpoint disco behavior, yet.
=> control/controlknobs,wgengine/magicsock: implement SilentDisco toggle

ipn/ipnlocal/local.go, ipn/store.go, taildrop/delete.go, taildrop/delete_test.go, taildrop/send.go, taildrop/taildrop.go
Simply reading the taildrop directory can pop up security dialogs on platforms like macOS. Avoid this by only performing garbage collection of partial and deleted files after the first received taildrop file, which would have prompted the security dialog window.
=> taildrop: lazily perform full deletion scan after first taildrop use

cmd/tailscale/cli/up.go
=> cmd/tailscale: warn if app-connector is enabled without ip forwarding

wgengine/magicsock/endpoint.go
=> wgengine/magicsock: fix typo in endpoint.sendDiscoPing() docs

clientupdate/clientupdate.go, ipn/ipnlocal/c2n.go
When we run tailscled under systemd, restarting the unit kills all child processes, including "tailscale update". And during update, the package manager will restart the tailscaled unit. Specifically on Debian-based distros, interrupting `apt-get install` can get the system into a wedged state which requires the user to manually run `dpkg --configure` to recover.
To avoid all this, use `systemd-run` where available to run the `tailscale update` process. This launches it in a separate temporary unit and doesn't kill it when parent unit is restarted.
Also, detect when `apt-get install` complains about aborted update and try to restore the system by running `dpkg --configure tailscale`. This could help if the system unexpectedly shuts down during our auto-update.
Fixes …
=> ipn/ipnlocal: run "tailscale update" via systemd-run on Linux

client/web/web.go
Fix panic due to `CurrentTailnet` being nil.
Fixes #15791
=> client/web: fix panic on logout

ipn/ipnlocal/web_client.go
This prevents a panic in some cases where WebClientShutdown is called multiple times.
=> ipn/ipnlocal: remove web client listeners after close

ipn/ipnlocal/serve.go
Tailscale serve maintains a set of listeners so that serve traffic from the local device can be properly served when running in kernel networking mode. #10177 refactored that logic so that it could be reused by the internal web client as well. However, in my refactoring I missed actually calling the serve handler to handle the traffic.
Updates #10177
=> ipn/ipnlocal: call serve handler for local traffic

ipn/ipnlocal/serve.go
return early if handler is nil. Go ahead and return the error from handler, though in this case the caller isn't doing anything with it (which has always been the case).
Updates #10177
Updates #10251
=> ipn/ipnlocal: only call serve handler if non-nil

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go
Causing issues building a stable release. Getting rid of the flag for now because it was only available in unstable, can still be turned on through localapi.
A #cleanup
=> cmd/cli: remove --webclient flag from up

types/appctype/appconnector.go
=> types/appctype: correct app-connector cap name in documentation

cmd/tailscale/cli/set.go
This removes the dev/unstable build check for the --webclient flag on `tailscale set`, so that it will be included in the next major stable release (1.56)
=> cmd/tailscale: expose --webclient for all builds

cmd/tailscale/cli/web.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go
Now that 1.54 has released, and the new web client will be included in 1.56, we can remove the need for the node capability. This means that all 1.55 unstable builds, and then eventually the 1.56 build, will work without setting the node capability.
The web client still requires the "webclient" user pref, so this does NOT mean that the web client will be on by default for all devices.
=> ipn: remove the preview-webclient node capability

client/web/src/components/exit-node-selector.tsx
We currently disable the exit-node drop down selector when the user is in read-only mode, but we missed disabling the "Disable" button also. Previously, it would display an error when clicked.
=> client/web: disable the "disable" button when disabled

util/osdiag/osdiag_windows.go, util/winutil/winutil.go, util/winutil/winutil_notwindows.go
The Windows base registry key is already exported but the policy key was not. util/osdiag currently replicates the string rather than the preferred approach of reusing the constant.
Change-Id: I6c1c45337896c744059b85643da2364fb3f232f2
=> util/osdiag, util/winutil: expose Windows policy key

util/syspolicy/policy_keys.go
These policy keys are supported on Apple platforms in Swift code; in order to support them on platforms using Go (e.g. Windows), they also need to be recorded here.
This does not affect any code, it simply adds the constants for now.
Updates ENG-2240
Updates ENG-2127
Updates ENG-2133
Change-Id: I0aa9863a3641e5844479da3b162761452db1ef42
=> util/syspolicy: add some additional policy keys

appc/appconnector.go, appc/appconnector_test.go
The non-referential copy destination doesn't extend the map contents, but also the read of a non-key is returning a zero value not bound to the map contents in any way.
Updates tailscale/corp#15657
=> appc: fix DomainRoutes copy

cmd/tailscaled/tailscaled.go, ipn/ipnlocal/web_client.go, ipn/ipnlocal/web_client_stub.go
For consistency with the "WebClient" naming of the other functions here. Also fixed a doc typo.
A #cleanup
=> ipn/ipnlocal: rename SetWebLocalClient to ConfigureWebClient

client/web/src/hooks/node-data.ts, client/web/web.go, cmd/tailscale/cli/web.go, tsnet/example/web-client/web-client.go
No longer using this! Readonly state fully managed via auth endpoint.
A #cleanup
=> client/web: remove DebugMode from GET /api/data

ipn/ipnlocal/local.go, ipn/ipnlocal/web_client.go, ipn/ipnlocal/web_client_stub.go
Adds a new sync.Mutex field to the webClient struct, rather than using the general LocalBackend mutex. Since webClientGetOrInit (previously WebClientInit) gets called on every connection, we want to avoid holding the lock on LocalBackend just to check if the server is initialized.
Moves all web_client.go funcs over to using the webClient.mu field.
=> ipn/ipnlocal: add mutex to webClient struct

cmd/tailscaled/tailscaled.go
Now that we have nftable support this works fine and force it on gokrazy since 25a8daf405a9db68187989428548405fa0a94d65.
Updates gokrazy/gokrazy#209
=> cmd/tailscaled: make tun mode default on gokrazy

cmd/tailscale/cli/debug.go, ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi.go, ipn/localapi/localapi.go, wgengine/magicsock/derp.go, wgengine/magicsock/magicsock.go
In DERP homeless mode, a DERP home connection is not sought or maintained and the local node is not reachable.
Updates #3363
Updates tailscale/corp#396
=> wgengine/magicsock: add DERP homeless debug mode for testing

client/web/web.go
I don't believe this has ever worked, since we didn't allow POST requests in the login client. But previously, we were primarily using the legacy client to login, so it didn't really matter. Now that we've removed the legacy client, we have no way to login.
This fixes the login client, allowing it to login, but it still needs to be refactored to expose a dedicated login method, without exposing all the node update functionality.
=> client/web: allow login client to still run tailscale up

.github/workflows/update-webclient-prebuilt.yml
This `go get` action has been running very slowly, and I'm pretty sure it's because we're building gocross on the first `./tool/go` run, and because we've set `GOPROXY=direct`, it's going directly to GitHub to fetch all of the gocross dependencies.
=> .github: build gocross using regular GOPROXY settings

cmd/containerboot/main.go
This PR fixes a bug where containerboot does not shut down cleanly when SIGTERM is received.
It ensures that:
- containerboot's long running tailscaled watch shuts down when SIGTERM is received
- the watch shuts down before tailscaled
I have verified that the fix works following the same steps used to reproduce the issue, see https://github.com/tailscale/tailscale/issues/10090
Updates https://github.com/tailscale/tailscale/issues/10090
=> cmd/containerboot: fix unclean shutdown

ipn/ipnlocal/c2n.go, ipn/ipnlocal/c2n_test.go, ipn/ipnlocal/cert.go, ipn/ipnlocal/cert_js.go, tailcfg/c2ntypes.go, tailcfg/tailcfg.go
So the control plane can delete TXT records more aggressively after client's done with ACME fetch.
Updates tailscale/corp#15848
=> ipn/ipnlocal: add c2n method to check on TLS cert fetch status

ipn/ipnlocal/expiry.go, ssh/tailssh/tailssh.go
This takes advantage of existing functionality in ipn/ipnlocal to adjust
the local clock based on periodic time signals from the control server.
This way, when checking things like SSHRule expirations, calculations are
protected from incorrectly set local clocks.
Fixes tailscale/corp#15796
=> ssh/tailssh: use control server time instead of local time

client/web/src/components/views/home-view.tsx
Hiding links to unimplemented settings pages.
Updates #10261
=> client/web: hide unimplemented links

client/web/src/components/app.tsx, client/web/src/components/views/login-view.tsx, client/web/src/hooks/node-data.ts, client/web/web.go
This creates a new /api/up endpoint which is exposed in the login client, and is solely focused on logging in. Login has been removed from the nodeUpdate endpoint.
This also adds support in the LoginClientView for a stopped node that just needs to reconnect, but not necessarily reauthenticate.  This follows the same pattern in `tailscale up` of just setting the WantRunning user pref.
=> client/web: split login from nodeUpdate

client/web/src/components/app.tsx, client/web/src/components/exit-node-selector.tsx, client/web/src/components/views/home-view.tsx, client/web/src/hooks/exit-nodes.ts, client/web/src/hooks/node-data.ts, client/web/src/ui/search-input.tsx, client/web/web.go
Add exit node selector (in full management client only) that allows for advertising as an exit node, or selecting another exit node on the Tailnet for use.
Updates #10261
=> client/web: add exit node selector

cmd/tailscale/cli/switch.go, ipn/ipnlocal/local.go, ipn/ipnlocal/network-lock.go, ipn/ipnlocal/network-lock_test.go, ipn/ipnlocal/peerapi_test.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_test.go, ipn/ipnlocal/state_test.go, ipn/prefs.go, types/netmap/netmap.go
This PR starts to persist the NetMap tailnet name in SetPrefs so that tailscaled clients can use this value to disambiguate fast user switching from one tailnet to another that are under the same exact login. We will also try to backfill this information during backend starts and profile switches so that users don't have to re-authenticate their profile. The first client to use this new information is the CLI in 'tailscale switch -list' which now uses text/tabwriter to display the ID, Tailnet, and Account. Since account names are ambiguous, we allow the user to pass 'tailscale switch ID' to specify the exact tailnet they want to switch to.
Updates #9286
=> ipn/ipnlocal,cmd/tailscale: persist tailnet name in user profile

client/web/package.json, client/web/src/components/views/login-view.tsx, client/web/src/index.css, client/web/src/ui/collapsible.tsx, client/web/src/ui/input.tsx, client/web/tailwind.config.js, client/web/web.go, client/web/yarn.lock
This adds an expandable section of the login view to allow users to specify an auth key and an alternate control URL.
Input and Collapsible components and accompanying styles were brought over from the adminpanel.
I've tested, and this works successfully for connecting to Headscale.  Check mode for using the web client is another story, but this allows for registering the device.
Updates #10261
=> client/web: add advanced login options

syncs/watchdog.go
Depending on how the preemption will occur, in some scenarios sendc would have blocked indefinitely even after cancelling the context.
=> Fix potential goroutine leak in syncs/watchdog.go

net/dns/manager.go
Config.singleResolverSet returns true if all routes have the same resolvers, even if the routes have no resolvers. If none of the routes have a specific resolver, the default should be used instead. Therefore, check for more than 0 instead of nil.
Fixes #8468
=> Fix Empty Resolver Set

cmd/tailscale/cli/debug.go
jq doens't like non-json output in the json stream, and works more happily when the input stream EOFs at some point. Move non-json words to stderr, and add a parameter to stop watching and exit after some number of objects.
---
Fixing annoyances discovered in watch-ipn while trying to steer a user to provide debug info.
=> cmd/tailscale/cli: make 'debug watch-ipn' play nice with jq

cmd/k8s-operator/proxy.go, cmd/k8s-operator/proxy_test.go
Configuring [api-server proxy](https://tailscale.com/kb/1236/kubernetes-operator/#configuring-the-api-server-proxy) involves a number of steps and there have been a few cases where it is not clear why it's not working as the user expected, see i.e #10127 .
This PR logs what user/group is being impersonated and why- that should help with debugging proxy issues.
(Alternative would be by looking at [kube apiserver logs or audit logs](https://github.com/kubernetes/apiserver/blob/v0.28.4/pkg/endpoints/filters/impersonation.go#L166-L170), however those will not be accessible to everyone).
Logging the headers will be quite verbose, but it should be okay to do it at debug level which is not the default and not what folks should use in production etc.
Updates tailscale/tailscale#10127
=> cmd/k8s-operator: log user/group impersonated by apiserver proxy at debug level

util/set/set.go, util/set/set_test.go
Marshal as a JSON list instead of a map. Because set elements are `comparable` and not `cmp.Ordered`, we cannot easily sort the items before marshaling.
=> util/set: implement json.Marshaler/Unmarshaler

flake.nix
It looks like `gitCommitStamp` is the new "entrypoint" for setting this information.
Fixes #9996.
---
In https://github.com/tailscale/tailscale/pull/9991#discussion_r1374895191, it was suggested to also set the `gitDirtyStamp`, but unfortunately, Go doesn't seem to like converting the stringly command line flags to the boolean that the code expects:
```
tailscale.com/version.gitDirtyStamp: cannot set with -X: not a var of type string (type:bool)
```
=> flake: fixup version embedding

cmd/k8s-operator/deploy/chart/values.yaml
Closes https://github.com/tailscale/tailscale/issues/10182.
Add missing keys to helm chart default values.
=> cmd/k8s-operator: helm chart add missing keys

wgengine/magicsock/magicsock.go
=> wgengine/magicsock: fix typo in Conn.handlePingLocked()

flake.nix
vendorSha256 is getting retired, and throws warning in builds.
=> flake.nix: use vendorHash instead of vendorSha256

cmd/containerboot/main.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/operator_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/svc.go
This PR adds a new supported `Service` annotation `tailscale.com/tailnet-fqdn` that users can use to specify a Tailnet FQDN for which an egress proxy should be deployed in cluster. This works in a very similar way to the existing `tailscale.com/tailnet-ip` annotation and the implementation follows the same pattern.
The annotation value has to be a full FQDN, except for the final dot can be missing.
See #10280 for context.
Currently only iptables/nftables rules for the IPv4 ts address of the egress target are set up - I ran into some issues when trying to create IPv6 rules - I think we have never actually tested the proxies with IPv6. I think this should be debugged separately.
I have tested this by hand on kind and on GKE + there are unit tests for the operator. Once we have e2e test …
=> cmd/{containerboot,k8s-operator}: allow users to define tailnet egress target by FQDN

cmd/tailscale/cli/set.go, cmd/tailscale/cli/up.go
We warn users about IP forwarding being disabled when using `--avertise-routes` in `tailscale up`, this adds the same warnings to `tailscale set`.
Updates tailscale/corp#9968
=> cmd/tailscale: also warn about IP forwarding if using CLI set

client/web/src/components/exit-node-selector.tsx
When search input changes, reset the scroll to the top of the dropdown list.
Updates #10261
=> client/web: scroll exit node dropdown to top on search

client/web/src/api.ts, client/web/src/components/acl-tag.tsx, client/web/src/components/app.tsx, client/web/src/components/exit-node-selector.tsx, client/web/src/components/login-toggle.tsx, client/web/src/components/update-available.tsx, client/web/src/components/views/device-details-view.tsx, client/web/src/components/views/home-view.tsx, client/web/src/components/views/login-view.tsx, client/web/src/components/views/ssh-view.tsx, client/web/src/components/views/updating-view.tsx, client/web/src/hooks/auth.ts, client/web/src/hooks/exit-nodes.ts, client/web/src/hooks/node-data.ts, client/web/src/hooks/self-update.ts, client/web/src/index.tsx, client/web/src/ui/badge.tsx, client/web/src/ui/collapsible.tsx, client/web/src/ui/input.tsx, client/web/src/ui/popover.tsx, client/web/src/ui/profile-pic.tsx, client/web/src/ui/search-input.tsx, client/web/src/ui/spinner.tsx, client/web/src/ui/toggle.tsx, cmd/tsconnect/src/lib/ssh.ts, scripts/check_license_headers.sh
Enforcing inclusion of our OSS license at the top of .ts and .tsx files. Also updates any relevant files in the repo that were previously missing the license comment. An additional `@license` comment is added to client/web/src/index.tsx to preserve the license in generated Javascript.
Updates #10261
=> scripts/check_license_headers: enforce license on ts/tsx files

client/web/package.json, client/web/src/components/app.tsx, client/web/src/components/exit-node-selector.tsx, client/web/src/components/login-toggle.tsx, client/web/src/components/views/device-details-view.tsx, client/web/src/components/views/login-view.tsx, client/web/src/components/views/ssh-view.tsx, client/web/src/hooks/auth.ts, client/web/src/hooks/exit-nodes.ts, client/web/src/hooks/node-data.ts, client/web/src/hooks/self-update.ts, client/web/yarn.lock
Add eslint to require stricter typescript rules, particularly around required hook dependencies. This commit also updates any files that were now throwing errors with eslint.
Updates #10261
=> client/web: add eslint

client/web/yarn.lock
6e30c9d1f added eslint to the web client. As a part of that change, the existing yarn.lock file was removed and yarn install run to build with a clean yarn dependencies set with latest versions. This caused a change in the "vite-plugin-rewrite-all" package that fails at build time with our existing vite config. This is a known bug with some suggested fixes: https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only
Rather than editing our package.json type, this commit reverts back the yarn.lock file to it's contents at the commit just before 6e30c9d1f and then only runs yarn install to add the new eslint packages, rather than installing the latest versions of all packages.
Updates [#10261](https://github.com/tailscale/tailscale/issues/10261)
=> client/web: fix Vite dev server build error

client/web/auth.go, client/web/src/hooks/auth.ts, client/web/web_test.go
Only enforce check mode if the control server URL ends in ".tailscale.com".  This allows the web client to be used with headscale (or other) control servers while we work with the project to add check mode support (tracked in juanfont/headscale#1623).
Updates #10261
I don't *love* all of the string pointers in the tests, but it does seem to work fine and is consistent with how we do this in some other tests.  It does mean that we have to be careful not to run these test cases in parallel, but that's probably fine.
=> client/web: skip check mode for non-tailscale.com control servers

cmd/tailscale/cli/status.go, cmd/tailscale/cli/up.go, ipn/ipnlocal/local.go
To be consistent with the formatting of other warnings, pass available update health message instead of handling ClientVersion in the CLI.
Fixes #10312
=> cmd/tailscale,ipn/ipnlocal: pass available update as health message

ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go
Adds AllowedIPs to PeerStatus, allowing for easier lookup of the routes allowed to be routed to a node. Will be using the AllowedIPs of the self node from the web client interface to display approval status of advertised routes.
Updates #10261
=> ipn/ipnstate: add AllowedIPs to PeerStatus

client/web/src/components/app.tsx, client/web/src/components/control-components.tsx, client/web/src/components/views/device-details-view.tsx, client/web/src/components/views/ssh-view.tsx, client/web/src/components/views/subnet-router-view.tsx, client/web/src/hooks/node-data.ts, client/web/web.go, ipn/prefs.go
=> client/web: hide admin panel links for non-tailscale control servers

net/dns/manager_darwin.go
putting each nameserver on one line in /etc/resolver/<domain>
fixes: #10134
=> net/dns: fix darwin dns resolver files

clientupdate/clientupdate.go
When updating on Windows, we make a copy of the tailscale.exe file in a temp directory to perform the update, because the original tailscale.exe gets deleted during the update.
This can eat up disk space if a machine is stuck doing repeated failed update attempts. Clean up old copies explicitly before making a new one, same as we do with MSIs.
Updates #10082
=> clientupdate: cleanup tailscale binary copies on Windows

client/web/src/components/app.tsx, client/web/src/components/login-toggle.tsx
Centers login pill with Tailscale icon, and fixes height of login pill.
Updates #10261
=> client/web: center and fix height of header

client/tailscale/localclient.go, client/web/src/components/login-toggle.tsx, client/web/src/hooks/node-data.ts, client/web/web.go
Use the packet filter rules to determine if any device is allowed to connect on port 5252.  This does not check whether a specific device can connect (since we typically don't know the source device when this is used).  Nor does it specifically check for wide-open ACLs, which is something we may provide a warning about in the future.
Update the login popover content to display information when the src device is unable to connect to the dst device over its Tailscale IP. If we know it's an ACL issue, mention that, otherwise list a couple of things to check. In both cases, link to a placeholder URL to get more information about web client connection issues.
Updates #10261
This doesn't have any tests yet, but I wanted to go ahead and get it out for review.  I can easily test the packet filter …
=> client/web: indicate if ACLs prevent access

wgengine/filter/filter.go
For use in ACL tests, we need a way to check whether a packet is allowed not just with TCP, but any protocol.
Updates #3561
=> wgengine/filter: add protocol-agnostic packet checker

.github/workflows/kubemanifests.yaml, .github/workflows/test.yml, cmd/k8s-operator/deploy/README.md, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/deploy/manifests/templates/01-header.yaml, cmd/k8s-operator/deploy/manifests/templates/02-namespace.yaml, cmd/k8s-operator/deploy/manifests/templates/03-secret.yaml, cmd/k8s-operator/generate/main.go, cmd/k8s-operator/operator.go, go.mod, go.sum
Generate static kube manifests for the Tailscale operator from the Helm chart to ensure a single source of truth.
The workflow for adding new functionality for the manifests will now be:
- add the changes to `./cmd/k8s-operator/deploy/charts`
- run `go generate tailscale.com/cmd/k8s-operator` to ensure the change is propagated to the static manifests
- commit all changes
This PR also adds a CI test to ensure that the static manifests are up to date with regards to the chart.
I have tested the generated manifest by setting the client id and client secret fields of the Secret data and applying it to a cluster.
=> cmd/k8s-operator: generate static kube manifests from the Helm chart.

client/web/src/components/app.tsx, client/web/src/components/exit-node-selector.tsx, client/web/src/components/login-toggle.tsx, client/web/src/components/update-available.tsx, client/web/src/components/views/device-details-view.tsx, client/web/src/components/views/home-view.tsx, client/web/src/components/views/login-view.tsx, client/web/src/components/views/subnet-router-view.tsx, client/web/src/components/views/updating-view.tsx, client/web/src/index.css, client/web/src/ui/button.tsx, client/web/src/ui/collapsible.tsx, client/web/src/ui/loading-dots.tsx, client/web/src/util.ts
Makes the following changes:
* Use “link” class in various spots
* Remove button appearance on Exit Node dropdown in readonly mode
* Update `-stone-` colors to `-gray-` (couple spots missed by original color config commit)
* Pull full ui/button component from admin panel, and update buttons throughout UI to use this component
* Remove various buttons in readonly view to match mocks
* Add route (and “pending approval”) highlights to Subnet router settings card
* Delete legacy client button styles from index.css
* Fixes overflow of IPv6 address on device details view
Updates #10261
=> client/web: button, link, and other small UI updates

client/web/src/components/app.tsx
Switch the "feature disabled" page to use the same treatment.
Updates #10261
=> client/web: render 404 message in empty card

client/web/src/components/login-toggle.tsx
If the login client is inside an iframe, open the management client in a new window, since it can't be loaded in the frame.
Updates #10261
=> client/web: handle login client inside an iframe

client/web/src/api.ts, client/web/src/hooks/node-data.ts, client/web/web.go
Add metric logging logic for the web client frontend. This is an initial pass of adding the base logic, plus a single point where it is used for validation that the logging is working correctly. More metric logging calls will follow in subsquent PRs.
=> client/web: add metric logging logic to the web client

net/interfaces/interfaces.go, net/interfaces/interfaces_test.go
Before this fix, LikelyHomeRouterIP could return a 'self' IP that doesn't correspond to the gateway address, since it picks the first private address when iterating over the set interfaces as the 'self' IP, without checking that the address corresponds with the previously-detected gateway.
This behaviour was introduced by accident in aaf2df7, where we deleted the following code:
for _, prefix := range privatev4s {
if prefix.Contains(gateway) && prefix.Contains(ip) {
myIP = ip
ok = true
return
}
}
Other than checking that 'gateway' and 'ip' were private IP addresses (which were correctly replaced with a call to the netip.Addr.IsPrivate method), it also implicitly checked that both 'gateway' and 'ip' were a part of the *same* prefix, and thus likely to be the same interface.
Restore that …
=> net/interfaces: ensure we return valid 'self' IP in LikelyHomeRouterIP

cmd/containerboot/main_test.go, control/controlclient/direct.go, ipn/ipnlocal/cert.go, ipn/ipnserver/proxyconnect.go, ipn/prefs.go, portlist/portlist_linux.go, posture/serialnumber_notmacos.go
On main, there are numerous issues indicated by: https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/nilness.
```
/home/matt/src/github.com/tailscale/tailscale/ipn/prefs.go:447:11: tautological condition: non-nil != nil
/home/matt/src/github.com/tailscale/tailscale/ipn/prefs.go:447:24: tautological condition: non-nil != nil
/home/matt/src/github.com/tailscale/tailscale/control/controlclient/direct.go:713:9: impossible condition: nil != nil
/home/matt/src/github.com/tailscale/tailscale/portlist/portlist_linux.go:181:10: tautological condition: nil == nil
/home/matt/src/github.com/tailscale/tailscale/posture/serialnumber_notmacos.go:104:30: impossible condition: nil != nil
/home/matt/src/github.com/tailscale/tailscale/ipn/ipnlocal/cert.go:597:16: tautological condition: non-nil != nil …
```
=> all: fix nilness issues

util/syspolicy/policy_keys.go
These keys were intended to match the Apple platforms, but accidentally used the wrong name.
Updates ENG-2133
Change-Id: I9ed7a17919e34e2d8896a5c64efc4d0c0003166e
=> util/syspolicy: rename incorrectly named policy keys

cmd/containerboot/main.go, cmd/tailscale/cli/cli_test.go, control/controlknobs/controlknobs.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/c2n.go, ipn/ipnlocal/local.go, ipn/prefs.go, ipn/prefs_test.go, tailcfg/tailcfg.go, util/linuxfw/detector.go, util/linuxfw/nftables_runner.go, wgengine/router/router.go, wgengine/router/router_linux.go, wgengine/router/router_linux_test.go, wgengine/router/router_test.go
This allows for a break-glass control to remotely revert to one netfilter in case the other starts causing issues, without issuing a patch update.
Updates corp#14029.
=> linuxfw,wgengine/route,ipn: add c2n and nodeattrs to control linux netfilter

client/web/package.json, client/web/src/assets/icons/copy.svg, client/web/src/assets/icons/x.svg, client/web/src/components/address-copy-card.tsx, client/web/src/components/login-toggle.tsx, client/web/src/components/nice-ip.tsx, client/web/src/components/views/device-details-view.tsx, client/web/src/components/views/home-view.tsx, client/web/src/components/views/subnet-router-view.tsx, client/web/src/hooks/node-data.ts, client/web/src/hooks/toaster.ts, client/web/src/index.css, client/web/src/index.tsx, client/web/src/ui/quick-copy.tsx, client/web/src/ui/toaster.tsx, client/web/src/utils/clipboard.ts, client/web/src/utils/util.ts, client/web/web.go, client/web/yarn.lock
Updates the IP address on home view to open a copyable list of node addresses on click. And makes various values on the details view copyable text items, mirroring the machine admin panel table.
As part of these changes, pulls the AddressCard, NiceIP and QuickCopy components from the admin panel, with the AddressCard slightly modified to avoid needing to also pull in the CommandLine component.
A new toaster interface is also added, allowing us to display success and failure toasts throughout the UI. The toaster code is slightly modified from it's admin form to avoid the need for some excess libraries.
Updates #10261
=> client/web: add copyable components throughout UI

net/portmapper/upnp_test.go
Unfortunately in the test we can't reproduce the failure seen in the real system ("SOAP fault: UPnPError")
Updates https://github.com/tailscale/tailscale/issues/8364
=> net/portmap: add test of Mikrotik Root Desc XML.

client/web/src/components/views/login-view.tsx
The IP property in node data was renamed to IPv4 but refactoring the usage of the property was missed in this file.
=> client/web: use IPv4 instead of IP in login view

client/web/src/components/views/device-details-view.tsx
Adds a footer to the device details page that mirrors license and policy content on other Tailscale clients.
Updates #10261
=> client/web: add licenses and policies links

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_windows.go, util/syspolicy/policy_keys.go, util/syspolicy/syspolicy.go
Previously, policies affected the default prefs for a new profile, but
that does not affect existing profiles. This change ensures that
policies are applied whenever preferences are loaded or changed, so a
CLI or GUI client that does not respect the policies will still be
overridden.
Exit node IP is dropped from this PR as it was implemented elsewhere
in #10172.
Fixes tailscale/corp#15585
Change-Id: Ide4c3a4b00a64e43f506fa1fab70ef591407663f
=> ipn/ipnlocal: better enforce system policies

client/web/src/components/exit-node-selector.tsx
Remove padding on top of search bar, remove rounded corners of bottom border of earch bar, and add auto focus.
Updates #10261
Before
After
=> client/web: fix exit node selector styling

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, util/syspolicy/policy_keys.go
Due to the Sparkle preference naming convention, macsys already has a policy key named "ApplyUpdates" that merely shows or hides the menu item that controls if auto updates are installed, rather than directly controlling the setting.
For other platforms, we are going to use "InstallUpdates" instead because it seemed better than the other options that were considered.
Change-Id: Ia6a125beb6b4563d380c6162637ce4088f1117a0
=> ipn/ipnlocal, util/syspolicy: add auto update policy

util/cache/cache_test.go, util/cache/interface.go, util/cache/locking.go, util/cache/none.go, util/cache/single.go
This package allows caching arbitrary key/value pairs in-memory, along with an interface implemented by the cache types.
Extracted from #7493
Change-Id: Ic8ca820927c456721cf324a0c8f3882a57752cc9
=> util/cache: add package for general-purpose caching

client/web/assets.go, client/web/build/index.html, cmd/build-webclient/build-webclient.go
Precompress webclient assets with precompress util. This cuts our css and js build sizes to about 1/3 of non-compressed size. Similar compression done on tsconnect and adminhttp assets.
Updates #10261
=> client/web: precompress assets

util/syspolicy/handler_windows.go
Updates ENG-2513. Renames client metrics keys used on Windows for consistency with Apple platforms.
See corp PR: https://github.com/tailscale/corp/pull/16282
=> util/syspolicy: rename client metric keys

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/set.go, cmd/tailscale/cli/up.go, ipn/conf.go, ipn/prefs.go, ipn/prefs_test.go
Some fields if `ipn.Prefs` are structs. `ipn.MaskedPrefs` has a single level of boolean `*Set` flags, which doesn't map well to nested structs within `ipn.Prefs`.
Change `MaskedPrefs` and `ApplyEdits` to support `FooSet` struct fields that map to a nested struct of `ipn.Prefs` like `AutoUpdates`. Each struct field in `MaskedPrefs` is just a bundle of more `Set` bool fields or other structs. This allows you to have a `Set` flag for any arbitrarily-nested field of `ipn.Prefs`.
Also, make `ApplyEdits` match fields between `Prefs` and `MaskedPrefs` by name instead of order, to make it a bit less finicky. It's probably slower but `ipn.ApplyEdits` should not be in any hot path.
As a result, `AutoUpdate.Check` and `AutoUpdate.Apply` fields don't clobber each other when set individually.
Updates …
=> ipn,cmd/tailscale/cli: support hierarchical MaskedPrefs

client/web/web.go
Even if connected to the login client over tailscale, still check platform auth so the browser can obtain the tokens it needs to make platform requests complete successfully.
Updates #10261
=> client/web: always run platform auth for login mode

client/web/auth.go, client/web/web.go, client/web/web_test.go
Add logging of device management type for the web client auth flow. Namely, this differentiates between viewing a node you do not own, viewing a local tagged node, viewing a remote tagged node, managing a local node, and managing a remote node.
=> client/web: add logging of device management type for web client

client/web/web.go
Calling DebugPacketFilterRules fails when the node is not logged in, which was causing 500 errors on the node data endpoint after logging the node out. This change updates to only check the filter rules when the backend state is "Running".
Updates #10261
=> client/web: fix 500 error after logout

client/web/web.go
The client has changed a bit since we introduced the path prefix.  It is now used for two things:
- its original purpose, of ensuring that when the client is run in CGI mode at arbitrary paths, then relative paths for assets continue to work
- we also now pass the path to the frontend and use wouter to manage routes for the various subpages of the client.
When the client is run behind a reverse proxy (as it is in Home Assistant), it is common for the proxy to rewrite the request so that the backend application doesn't see the path it's being served at. In this case, we don't need to call enforcePrefix, since it's already stripped before it reaches us.  However, wouter (our react router library) still sees the original path in the browser, and needs to know what part of it is the prefix …
=> client/web: only enforce path prefix in CGI mode

client/web/web.go
The updates view still needs a final design pass, limit to unstable track for now.
Updates #10261
=> client/web: limit updates ui to unstable builds

client/web/web.go
Limit cookies to HTTP requests (not accessible from javascript). Set SameSite to "Lax", which is similar to "Strict" but allows for cookies to be included in requests that come from offsite links.  This will be necessary when we link to the web client from the admin console.
Updates #10261
Fixes tailscale/corp#16265
=> client/web: add security attributes on session cookie

client/web/web.go
When running on Home Assistant, use the X-Ingress-Path header to set the URLPrefix that is passed to the frontend.
Also fix handling of errNotUsingTailscale in the auth handler (previously it falling through to a later case and returning a 500). Instead, it's just a terminal state with no auth needed.
Updates #10261
=> client/web: use Home Assistant's X-Ingress-Path header

cmd/tailscaled/tailscaled.go
Previously were always setting `UseSocketOnly` because we were comparing `args.socketpath != ""`, but `args.socketpath` flag always gets filled with `paths.DefaultTailscaledSocket()` when not provided. Rather than comparing to the empty string, compare to the default value to determine if `UseSocketOnly` should be set.
Should fix issue with web client being unreachable for Mac App Store variant of the mac build.
```
error getting status: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscaled.socket: connect: no such file or directory
```
Updates #16054
=> cmd/tailscaled: update ConfigureWebClient's UseSocketOnly value

client/web/src/components/login-toggle.tsx
Previously, we were only breaking out of iframes when accessing the login client over a local IP address (where viewerIdentity is not set). We need to also handle the case where the user is accessing the login client over the Tailscale IP, and similarly break out of the iframe when logging into the management client.
Updates #10261
=> client/web: open new window if iframed

client/web/src/api.ts, client/web/src/components/exit-node-selector.tsx, client/web/src/types.ts, client/web/web.go
Add visual indication when running as an exit node prior to receiving admin approval.
https://github.com/tailscale/tailscale/assets/8587567/8b10e1d4-0b43-4aac-bec1-d32d6b392147
=> client/web: add visual indication for exit node pending approval

client/web/src/components/login-toggle.tsx
When displaying the login client, we check for connectivity to the management client by calling it's /ok handler. If that response is non-200, then there is something wrong with the management client, so don't render the login button.
Updates #10261
=> client/web: don't show login button if /ok errors

client/web/web.go
Completed testing of the new UI on the existing platforms that use it. From testing, QNAP, Unraid, and Home Assistant (in addition to Synology) all do not play well with using an exit node. For now, we're disabling this setting from the UI. CLI should be updated to also disallow selection of an exit node from these platforms. All platforms still allow for advertising as an exit node.
Updates #10261
=> client/web: restrict using an exit node on a couple more platforms

client/web/index.html, client/web/web.go
Calculate and set the hash of the one inline script we have in index.html. That script is unlikely to change, so hardcoding the hash seems fine for now.
Updates #10261
Updates tailscale/corp#16266
=> client/web: use CSP hash for inline javascript

client/web/auth.go
To be safe, use `prefs.ControlURLOrDefault()` rather than the current `prefs.ControlURL` directly.
Updates #10261
=> client/web: use prefs.ControlURLOrDefault from controlSupportsCheckMode

client/web/src/components/views/device-details-view.tsx
Add a new "Debug" card at the bottom of the details page. It's maybe premature to add a separate card for this, since all it currently lists is whether the device is using TUN mode and (for Synology) the DSM version. But I think it may be helpful to add client connectivity data (like shown on admin console machine page) as well as a bug report button.  Those can come soon after the 1.56 launch.
Updates #10261
=> client/web: add debug card to details page

client/web/src/hooks/auth.ts
Makes sure we refresh auth state after synology auth has run.
Updates #10261
=> client/web: refresh auth after syno login

client/web/src/components/views/device-details-view.tsx
Displays "No expiry" when disabled.
Updates #10261
=> client/web: fix key expiry text when expiry disabled

net/netcheck/netcheck.go
This PR ensures that only HTTP netcheck is used on tamago clients which lack API for raw ICMP requests.
=> net/netcheck: only run HTTP netcheck for tamago clients

client/web/src/components/login-toggle.tsx, client/web/src/hooks/auth.ts, client/web/web.go, client/web/web_test.go
Was previously failing to redirect to the manage client when accessing the login client with the Tailscale IP.
Updates #10261
Fixes tailscale/corp#16348
=> client/web: fix redirect logic when accessing login client over TS IP

net/portmapper/portmapper.go, net/portmapper/select_test.go, net/portmapper/upnp.go, net/portmapper/upnp_test.go
Previously, we would select the first `WANIPConnection2` (and related) client from the root device, without any additional checks. However, some routers expose multiple UPnP devices in various states, and simply picking the first available one can result in attempting to perform a portmap with a device that isn't functional.
Instead, mimic what the miniupnpc code does, and prefer devices that are (a) reporting as Connected, and (b) have a valid external IP address. For our use-case, we additionally prefer devices that have an external IP address that's a public address, to increase the likelihood that we can obtain a direct connection from peers.
Finally, we split out fetching the root device (`getUPnPRootDevice`) from selecting the best service within that root device …
=> net/portmapper: be smarter about selecting a UPnP device

cmd/tailscale/cli/netcheck.go, health/health.go, net/netcheck/netcheck.go, net/netcheck/netcheck_test.go, wgengine/magicsock/magicsock.go
This uses the fact that we've received a frame from a given DERP region within a certain time as a signal that the region is stil present (and thus can still be a node's PreferredDERP / home region) even if we don't get a STUN response from that region during a netcheck.
This should help avoid DERP flaps that occur due to losing STUN probes while still having a valid and active TCP connection to the DERP server.
Updates #8603
Change-Id: If7da6312581e1d434d5c0811697319c621e187a0
=> net/netcheck: use DERP frames as a signal for home region liveness

client/web/web.go, client/web/web_test.go
Ensure we don't create Location: header URLs that have leading //, which is a schema-less reference to arbitrary 3rd-party sites. That is, //example.com/foo redirects off-site, while /example.com/foo is an on-site path URL.
Fixes tailscale/corp#16268
=> client/web: keep redirects on-site

client/web/web.go
Throughout the web UI, we present the tailscale addresses for the self node. In the case of the node being shared out with a user from another tailnet, the peer viewer may actually know the node by a different IP than the node knows itself as (Tailscale IPs can be configured as desired on a tailnet level). This change includes two fixes:
1. Present the self node's addresses in the frontend as the addresses the viewing node knows it as (i.e. the addresses the viewing node uses to access the web client).
2. We currently redirect the viewer to the Tailscale IPv4 address if viewing it by MagicDNS name, or any other name that maps to the Tailscale node. When doing this redirect, which is primarily added for DNS rebinding protection, we now check the address the peer knows this node as, and …
=> client/web: use Tailscale IP known by peer node

cmd/connector-gen/README.md, cmd/connector-gen/advertise-routes.go, cmd/connector-gen/aws.go, cmd/connector-gen/connector-gen.go, cmd/connector-gen/github.go
connector-gen can initially generate connector ACL snippets and advertise-routes flags for Github and AWS based on their public IP / domain data.
Updates ENG-2425
=> cmd/connector-gen: add helper tool for wide app connector configurations

logtail/logtail.go, logtail/logtail_test.go
In order to provide more visibility into the operation of tailnets for a specific customer, redact public IP addresses such as employee homes from the log content before the upload. 
Updates [#15664](https://github.com/tailscale/corp/issues/15664)
=> tailscale/logtail: log-filtering

cmd/k8s-operator/deploy/chart/values.yaml
Document how to pass multiple tag values for default proxy tags via Helm. Also document available log levels for the operator.
The comments in the Helm values file are user facing documentation- they are visible if a user runs views available values for the chart by running  `helm show values tailscale/tailscale-operator`
=> cmd/k8s-operator/deploy/chart: document some chart values

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/set.go, control/controlclient/direct.go, ipn/ipnlocal/c2n.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/prefs.go, ipn/prefs_test.go, tailcfg/tailcfg.go, types/netmap/nodemut.go, types/netmap/nodemut_test.go, types/opt/bool.go
When auto-update setting in local Prefs is unset, apply the tailnet
default value from control. This only happens once, when we apply the
default (or when the user manually overrides it), tailnet default no
longer affects the node.
Updates #16244
=> ipn: apply tailnet-wide default for auto-updates

appc/appconnector.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
Individual route advertisements that are covered by existing routes are
no longer advertised. If an upstream returns 0.0.0.0, 127.x, and other
common unwanted addresses those are also rejected.
Updates #16425
=> appc,ipn: prevent undesirable route advertisements

tool/gocross/autoflags.go
In this commit, we have updated the build process for our Windows DLLs to link statically with libgcc, ensuring our Windows DLLs are self-contained.
Updates #10617
=> tool/gocross: make all Windows DLLs build with static libgcc

api.md, client/tailscale/devices.go
These new API fields come from tailscale/corp#15445.
Closes tailscale/corp#15617
Edit: We'll look at shipping this once the feature hits beta. Work-in-progress tests for these clients changes are in https://github.com/tailscale/corp/commit/92e5311c4c58f878d2f412cd765aac4a16ca11d1
=> client/tailscale: add Device.PostureIdentity field

net/netutil/ip_forward.go, net/netutil/netutil_test.go
Updates #4432
Change-Id: Ifc332a5747fc1feffdbb87437308cf8ecb21b0b0
=> net/netutil: add function to check rp_filter value

net/interfaces/interfaces.go, net/interfaces/interfaces_bsd.go, net/interfaces/interfaces_darwin_test.go, net/interfaces/interfaces_linux.go, net/interfaces/interfaces_test.go, net/interfaces/interfaces_windows.go
Currently, we get the "likely home router" gateway IP and then iterate through all IPs for all interfaces trying to match IPs to determine the source IP. However, on many platforms we know what interface the gateway is through, and thus we don't need to iterate through all interfaces checking IPs. Instead, use the IP address of the associated interface.
This better handles the case where we have multiple interfaces on a system all connected to the same gateway, and where the first interface that we visit (as iterated by ForeachInterfaceAddress) isn't also the default internet route.
Updates #8992
Change-Id: I8632f577f1136930f4ec60c76376527a19a47d1f
=> net/interfaces: better handle multiple interfaces in LikelyHomeRouterIP

net/portmapper/pcp.go, net/portmapper/portmapper.go, net/portmapper/portmapper_test.go, net/portmapper/upnp.go
This logs additional information about what mapping(s) are obtained during the creation process, including whether we return an existing cached mapping.
Updates #10597
Change-Id: I9ff25071f064c91691db9ab0b9365ccc5f948d6e
=> net/portmapper: add logs about obtained mapping(s)

net/packet/packet_test.go, net/portmapper/igd_test.go, net/proxymux/mux_test.go, net/routetable/routetable.go, net/tsaddr/tsaddr.go, net/tsdial/peerapi_macios_ext.go, net/tsdial/tsdial.go, net/tstun/wrap_test.go, release/dist/cli/cli.go, ssh/tailssh/tailssh.go, tailcfg/tailcfg_test.go, tka/scenario_test.go, tool/gocross/goroot.go, tstest/archtest/archtest_test.go, tstest/integration/vms/derive_bindhost_test.go, tstest/integration/vms/vms_steps_test.go, tstest/natlab/natlab.go, tstime/rate/rate_test.go, util/deephash/deephash_test.go, util/deephash/types_test.go, util/syspolicy/policy_keys.go, util/syspolicy/policy_keys_windows.go, version/modinfo_test.go, version/prop.go, wgengine/router/router_linux.go, wgengine/userspace.go
Run `staticcheck` with `U1000` to find unused code. This cleans up about a half of it. I'll do the other half separately to keep PRs manageable.
=> all: cleanup unused code, part 1

client/tailscale/localclient.go, logpolicy/logpolicy.go, safesocket/basic_test.go, safesocket/pipe_windows.go, safesocket/pipe_windows_test.go, safesocket/safesocket.go, safesocket/safesocket_js.go, safesocket/safesocket_plan9.go, safesocket/unixsocket.go, tstest/integration/integration_test.go
This type seems to be a migration shim for TCP tailscaled sockets (instead of unix/windows pipes). The `port` field was never set, so it was effectively used as a string (`path` field).
Remove the whole type and simplify call sites to pass the socket path directly to `safesocket.Connect`.
=> safesocket: remove ConnectionStrategy

net/netmon/netmon.go, net/netmon/netmon_windows.go
When the portable Monitor creates a winMon via newOSMon, we register address and route change callbacks with Windows. Once a callback is hit, it starts a goroutine that attempts to send the event into messagec and returns. The newly started goroutine then blocks until it can send to the channel. However, if the monitor is never started and winMon.Receive is never called, the goroutines remain indefinitely blocked, leading to goroutine leaks and significant memory consumption in the tailscaled service process on Windows. Unlike the tailscaled subprocess, the service process creates but never starts a Monitor.
This PR adds a check within the callbacks to confirm the monitor's active status, and exits immediately if the monitor hasn't started.
Updates #9864
=> net/netmon: fix goroutine leak in winMon if the monitor is never started

cmd/tailscale/cli/whois.go
The IP argument is required; only the port is optional.
Updates #10605
=> cmd/tailscale/cli: document usage more clearly

release/deb/debian.postinst.sh
Seems like an omission, since we have it in postrm and prerm.
Fixes #10705
=> release: add shebang to the debian postinst script

logpolicy/logpolicy.go
Previously, for Windows clients only, a registry value named LogTarget could override the log server, but only if the environment variable was unset.
To allow administrators to enforce using a particular log server, switch this to make the registry value take precedence over the environment variable, and switch to the newer syspolicy.GetString so that the log target can be specified by a GPO more easily.
Updates ENG-2515
Change-Id: Ia618986b0e07715d7db4c6df170a24d511c904c9
Testing: manually tested
1. Old registry value on its own
2. New registry value on its own
3. Environment variable on its own
4. New registry value + environment variable, new registry value wins
5. Nothing set
=> logpolicy: use syspolicy to override LogTarget

tsweb/debug.go, tsweb/tsweb.go
plugin-types is deprecated, and setting object-src: 'none' is best practice. This should result in no functional change.
Fixes #10718
=> tsweb: use object-src instead of plugin-types

net/portmapper/pcp.go, net/portmapper/portmapper.go
If the epoch that we see during a Probe is less than the existing epoch, it means that the gateway has either restarted or reset its configuration, and an existing mapping is no longer valid. Reset any saved mapping(s) if we detect this case so that a future createOrGetMapping will not attempt to re-use it.
Updates #10597
Change-Id: Ie3cddaf625cb94a29885f7a1eeea25dbf6b97b47
=> net/portmapper: check returned epoch from PMP and PCP protocols

cmd/containerboot/main.go, cmd/containerboot/main_test.go
A Tailnet node can be told to stop advertise subnets by passing an empty string to `--advertise-routes` flag to `tailscale up`/`tailscale set`.
containerboot currently ignores `TS_ROUTES` if it's set to empty string, which means that the only way to stop a containerised tailscale with `TS_AUTH_ONCE` set to true would be to recreate it (if it's not created with `TS_AUTH_ONCE` this can probably be achieved by passing `--advertise-routes` to `TS_EXTRA_ARGS` instead (?)).
This would cause issues for #10724 where we should allow subnet routes to be added as well as removed from an existing `Connector` custom resource.
This PR ensures that if `TS_ROUTES` is empty (either because it's unset or explicitly set to empty string) `--advertise-routes` too is set to empty string.
This means that we do …
=> cmd/containerboot: ensure that --advertise-routes can be unset

cmd/containerboot/main.go
Fixes a bug introduced [here](https://github.com/tailscale/tailscale/pull/10734/commits/fdbbf9ee95b717261e8d81077a73d5a9fbaacfb7#diff-700830ac79a41da42cd3a82065f0fee3003a4390eead4db1de4bf30557a06bd6L748-R759)  - I assumed that [`strings.Split`](https://github.com/tailscale/tailscale/blob/v1.56.1/cmd/containerboot/main.go#L749) returns an empty slice for an empty target, however it [returns a slice with one item](https://pkg.go.dev/strings#Split) - which causes us to loop over routes once and fail when parsing the empty string as an IP address:
```
$ k logs ts-prod-dg76j-0 -n tailscale
Defaulted container "tailscale" out of: tailscale, sysctler (init)
boot: 2024/01/04 11:46:39 Failed to enable IP forwarding: invalid subnet route: netip.ParsePrefix(""): no '/'
```
=> cmd/containerboot: don't parse empty subnet routes

control/controlknobs/controlknobs.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go
This is based off [earlier work pairing with Maisem](https://github.com/tailscale/tailscale/compare/maisem/login-renew?expand=1), but modifies it to be feature flagged rather than changing this for everyone.
The logic to the feature flagging is to ensure we can always _exit_ a blocked state, but never enter it if the feature flag is enabled. This is to ensure that if the flag changes, we don't end up stuck in a blocked state.
The motivation for the feature flagging is already covered in tailscale/corp#16302
Updates tailscale/corp#16016
=> ipn/ipnlocal: refresh node key without blocking if cap enabled

control/controlclient/direct.go, control/controlclient/map.go, tailcfg/tailcfg.go, types/netmap/netmap.go, types/netmap/nodemut.go, types/netmap/nodemut_test.go
Updates tailscale/corp#16016
Design doc for more context: https://docs.google.com/document/d/1zaoCId-biwgMNThDLzK0R8_PGB11dddTSoOMnGlkTFU/
Probably makes sense to review this in tandem with tailscale/corp#16049 , which is the server-side change.
=> controlclient,tailcfg,types: expose MaxKeyDuration via localapi

ssh/tailssh/tailssh.go
ErrDenied was added in [our fork of
x/crypto/ssh](https://github.com/golang/crypto/commit/acc6f8fe8d618cba34d44e89fdde304f98c576df) to short-circuit auth attempts once one fails.
In the case of our callbacks, this error is returned when SSH policy check determines that a connection should not be allowed. Both `NoClientAuthCallback` and `PublicKeyHandler` check the policy and will fail anyway. The `fakePasswordHandler` returns true only if `NoClientAuthCallback` succeeds the policy check, so it checks it indirectly too.
The difference here is that a client might attempt all 2-3 auth methods instead of just `none` but will fail to authenticate regardless.
Updates #8593
=> ssh/tailssh: use a local error instead of gossh.ErrDenied

cmd/tailscaled/tailscaled.go, tsnet/tsnet.go
This tripped me up when I was testing something and wrote:
if conn != nil {
conn.Close()
}
In netstack mode, when an error occurred we were getting a non-nil error and a non-nil interface that contained a nil pointer. Instead, just return a nil interface value.
Change-Id: Id9ef3dd24529e0e8c53adc60ed914c31fbb10cc4
=> cmd/tailscaled, tsnet: don't return an interface containing a nil pointer

cmd/tailscale/cli/debug.go, ipn/localapi/localapi.go
This command allows observing whether a given dialer ("SystemDial", "UserDial", etc.) will successfully obtain a connection to a provided host, from inside tailscaled itself. This is intended to help debug a variety of issues from subnet routers to split DNS setups.
Updates #9619
Change-Id: Ie01ebb5469d3e287eac633ff656783960f697b84
=> cmd/tailscale, ipn/ipnlocal: add 'debug dial-types' command

taildrop/taildrop.go, taildrop/taildrop_test.go
This will expand the unicode character categories that we allow for valid filenames to go from "L, M, N, P, S, and the ASCII space character" to "L, M, N, P, S, Zs"
Fixes #10105
=> taildrop: Allow category Z unicode characters

docs/windows/policy/en-US/tailscale.adml, docs/windows/policy/tailscale.admx
To make setting Windows policies easier, this adds ADMX policy descriptions.
Fixes #6495
Updates ENG-2515
Change-Id: If4613c9d8ec734afec8bd781575e24b4aef9bb73
=> docs: add Windows administrative template

cmd/containerboot/main.go, cmd/containerboot/main_test.go
Currently when a containerboot container starts:
- if `TS_AUTH_ONCE` env var is set to true it runs `tailscaled` followed by `tailscale up` + auth key + config opts on first container start and `tailscaled` + `tailscale set` + config opts on subsequent starts
- if `TS_AUTH_ONCE` env var is set to false (default) runs `tailscaled` followed by `tailscale up` + config opts on any container start
The config opts are passed as [env vars](https://github.com/tailscale/tailscale/blob/v1.56.1/cmd/containerboot/main.go#L14-L47). This has a number of issues- env vars are not a great configuration option as we need to add extra logic in tailscale to validate them and having the config scattered accross multiple commands makes it harder to implement declarative configuration.
Right now we need to add …
=> cmd/containerboot: add EXPERIMENTAL_TS_CONFIGFILE_PATH env var to allow passing tailscaled config in a file

client/web/src/components/app.tsx, client/web/src/components/views/device-details-view.tsx, client/web/src/components/views/disconnected-view.tsx
For consistency w/ the CLI command. And to be more accurate to what is actually happening on this action - node key is expired.
Updates #10261
=> client/web: rename Disconnect to Logout

client/web/web.go, client/web/web_test.go
This is simply an extra check to prevent hypothetical issues if a prefix such as `--prefix="javascript:alert(1)"` was provided.  This isn't really necessary since the prefix is a configuration flag provided by the device owner, not user input.  But it does enforce that we are always interpreting the provided value as a path relative to the root.
Fixes: tailscale/corp#16268
=> client/web: ensure path prefix has a leading slash

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/debug.go, net/netutil/routes.go
The prefix has space for 32-bit site IDs, but the validateViaPrefix function would previously have disallowed site IDs greater than 255.
Fixes tailscale/corp#16470
Change-Id: I4cdb0711dafb577fae72d86c4014cf623fa538ef
=> net/netutil: allow 16-bit 4via6 site IDs

.github/workflows/govulncheck.yml
Send failures to a new channel using a github app token instead of webhook URL.
=> .github/workflows/govulncheck: migrate to a Github App

cmd/tailscaled/taildrop.go, ipn/backend.go, ipn/ipnlocal/local.go, taildrop/resume.go, taildrop/send.go, taildrop/taildrop.go
Removes the avoidFinalRename logic and all associated code as it is no longer required by the Apple clients. Enables resume logic to be usable for Apple clients.
Fixes tailscale/corp#14772
This and tailscale/corp#16589 need to be merged at the same time because there are dependencies for the apple client behavior in these two PRs
=> taildrop: remove breaking abstraction layers for apple

cmd/tailscale/cli/set.go
Prints a helpful message with the web UI's address when running tailscale set --webclient.
Updates tailscale/corp#16345
```
$ tailscale set --webclient
Web interface now running at 100.101.101.101:5252
```
=> cli/set: add printout when web client started

safesocket/safesocket_darwin.go
macOS environment variables needed by safesocket are currently only being properly populated when called from the CLI. When using safesocket from within tailscaled (not typical, but done for the device web UI), HOME is not set, for example.  Instead, use XPC_SERVICE_NAME to detect that we are running on macsys.
This fixes the device web UI on macsys.
Updates tailscale/corp#16393
=> safesocket: detect macsys from within tailscaled

version/mkversion/mkversion.go
This is useful to build local binaries with custom versions to test version-specific logic (like updates).
Updates https://github.com/tailscale/corp/issues/16703
=> version/mkversion: allow version override with $TS_VERSION_OVERRIDE

Makefile, build_docker.sh
Build dev tailscale and k8s-operator images for linux/amd64 only by default, make it possible to configure target build platform via PLATFORM var.
To make it easier for folks who are working on containerboot and operator and build the images frequently.
=> Makefile,build_docker.sh: build dev images for linux/amd64 only, allow to configure target platform

wgengine/router/router_windows.go, wgengine/router/router_windows_test.go
This is in response to logs from a customer that show that we're unable to run netsh due to the following error:
router: firewall: adding Tailscale-Process rule to allow UDP for "C:\\Program Files\\Tailscale\\tailscaled.exe" ...
router: firewall: error adding Tailscale-Process rule: exec: "netsh": cannot run executable found relative to current directory:
There's approximately no reason to ever dynamically look up the path of a system utility like netsh.exe, so instead let's first look for it in the System32 directory and only if that fails fall back to the previous behaviour.
Updates #10804
Change-Id: I68cfeb4cab091c79ccff3187d35f50359a690573
=> wgengine/router: look up absolute path to netsh.exe on Windows

client/web/auth.go, client/web/web.go, client/web/web_test.go, tailcfg/tailcfg.go
Sets up peer capability types for future use within the web client views and APIs.
=> client/web: add initial types for using peer capabilities

cmd/k8s-operator/sts.go, cmd/k8s-operator/sts_test.go
StatefulSet names for ingress/egress proxies [are calculated using Kubernetes name generator and the parent resource name as a base](https://github.com/tailscale/tailscale/blob/v1.56.1/cmd/k8s-operator/sts.go#L215-L218).
We currently try pre-calculate how long the generated name will be and cut the base it is to be longer than 52 chars, see https://github.com/tailscale/tailscale/pull/10343.
The name generator also cuts the base, but has [a higher max cap](https://github.com/kubernetes/kubernetes/blob/v1.28.4/staging/src/k8s.io/apiserver/pkg/storage/names/generate.go#L46). This commit fixes a bug where, if we get a shortened base back from _the generator_, we cut off too little as the base that we have cut will be passed into the generator again, which will then itself cut less because the …
=> cmd/k8s-operator: fix base truncating for extra long Service names

cmd/k8s-operator/deploy/chart/templates/deployment.yaml, cmd/k8s-operator/deploy/chart/values.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/operator.go
The configuration knob (that defaulted to Connector being disabled) was added largely because the Connector CRD had to be installed in a separate step. Now when the CRD has been added to both chart and static manifest, we can have it on by default.
This PR removes the `ENABLE_CONNECTOR` configuration knob (this was never released) and make the connector reconciler always run. This means that the `connectors.tailscale.com` CRD has to be always installed (else the reconciler would error when trying to retrieve an object of schema that the api-server does not understand). This is fine as we now always install the CRD by default.
The latest published 'unstable' Helm chart `v1.57.70` and the static manifest at ./cmd/k8s-operator/deploy/manifests/operator.yaml` both install the CRD by default.
=> cmd/k8s-operator: remove configuration knob for Connector functionality

derp/derp_server.go
Observed on one busy derp node, there were 600 goroutines blocked writing to this channel, which represents not only more blocked routines than we need, but also excess wake-ups downstream as the latent goroutines writes represent no new work.
Updates #self
=> derp: reduce excess goroutines blocking on broadcasts

cmd/tailscale/cli/exitnode.go
This change adds a description to the exit-node CLI command. This description will be displayed when using `tailscale -h` and `tailscale exit-node -h`.
Fixes #10787
=> cmd/tailscale/cli: add description to exit-node CLI command

derp/derp_server.go
See the field alignment lints for more information. Reductions are 64->24 and 64->32 respectively.
Updates #self
=> derp: optimize field order to reduce GC cost

ipn/ipnauth/ipnauth.go, ipn/ipnauth/ipnauth_windows.go, ipn/ipnlocal/local.go, ipn/ipnserver/server.go
When establishing connections to the ipnserver, we validate that the local user is allowed to connect.  If Tailscale is currently being managed by a different user (primarily for multi-user Windows installs), we don't allow the connection.
With the new device web UI, the inbound connection is coming from tailscaled itself, which is often running as "NT AUTHORITY\SYSTEM". In this case, we still want to allow the connection, even though it doesn't match the user running the Tailscale GUI. The SYSTEM user has full access to everything on the system anyway, so this doesn't escalate privileges.
Eventually, we want the device web UI to run outside of the tailscaled process, at which point this exception would probably not be needed.
Updates tailscale/corp#16393
=> ipn/ipnserver: always allow Windows SYSTEM user to connect

util/ctxkey/key.go, util/ctxkey/key_test.go
The lack of type-safety in context.WithValue leads to the common pattern of defining of package-scoped type to ensure global uniqueness:
type fooKey struct{}
func withFoo(ctx context, v Foo) context.Context {
return context.WithValue(ctx, fooKey{}, v)
}
func fooValue(ctx context) Foo {
v, _ := ctx.Value(fooKey{}).(Foo)
return v
}
where usage becomes:
ctx = withFoo(ctx, foo)
foo := fooValue(ctx)
With many different context keys, this can be quite tedious.
Using generics, we can simplify this as:
var fooKey = ctxkey.New("mypkg.fooKey", Foo{})
where usage becomes:
ctx = fooKey.WithValue(ctx, foo)
foo := fooKey.Value(ctx)
See https://go.dev/issue/49189
=> util/ctxkey: add package for type-safe context keys

cmd/k8s-operator/sts.go, cmd/k8s-operator/testutils_test.go
Sync StatefulSet child labels to their Pods that users have predictable label values to use when configuring network policies (see #10854 )
Updates tailscale/tailscale#10854
=> cmd/k8s-operator: sync StatefulSet labels to their Pods

cmd/k8s-operator/ingress.go
[Kubernetes Ingress spec defines three path types](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types), where path type `Exact` is meant to have strict request path matching where, for example, if the defined path is `/foo` a request for `/foo/bar` would be rejected (in the ingress controller as I understand).
We do not currently check path types and route as per the definition of `Prefix` path type. I am not sure if we need to implement `Exact`, but if a use case arises in the future, it would be good if users didn't depend on the current behaviour for `Exact`- ideally they should use `Prefix` now and let us know if they have a use case for the strict matching of `Exact`.
This PR adds a warning if a path with `Exact` path type is found.
Updates …
=> cmd/k8s-operator: warn if unsupported Ingress Exact path type is used.

appc/appconnector.go, appc/appconnector_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, types/appctype/appconnector.go
Control can now send down a set of routes along with the domains, and the routes will be advertised, with any newly overlapped routes being removed to reduce the size of the routing table.
Fixes tailscale/corp#16833
=> appc,ipn/ipnlocal,types/appctype: implement control provided routes

.github/workflows/kubemanifests.yaml
Fix the pattern for paths whose changes should trigger the kube tests to run- they weren't actually running.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
=> ./github/workflows/kubemanifests.yaml: fix the included paths pattern

cmd/tailscaled/tailscaled.go, wgengine/netstack/netstack.go
When tailscaled is run with "-debug 127.0.0.1:12345", these metrics are available at:
http://localhost:12345/debug/metrics
Updates #8210
Change-Id: I19db6c445ac1f8344df2bc1066a3d9c9030606f8
=> wgengine/netstack: expose gVisor metrics through expvar

tsweb/tsweb.go, tsweb/tsweb_test.go
We issue redirects in a few different places, it's time to have a common helper to do target validation.
Updates tailscale/corp#16875
=> tsweb: add a helper to validate redirect URLs

tool/gocross/autoflags.go, tool/gocross/autoflags_test.go
The new 'toolchain' directive in go.mod can sometimes force the use of an upstream toolchain against our wishes. Concurrently, some of our dependencies have added the 'toolchain' directive, which transitively adds it to our own go.mod. Force all uses of gocross to ignore that directive and stick to our customized toolchain.
=> tool/gocross: force use of our custom toolchain

net/portmapper/upnp.go, net/portmapper/upnp_test.go
This no longer results in a nil pointer exception when we get a valid UPnP response with no supported clients.
Updates #10911
Change-Id: I6e3715a49a193ff5261013871ad7fff197a4d77e
=> net/portmapper: handle cases where we have no supported clients

cmd/k8s-operator/ingress.go
Do not provision resources for a tailscale Ingress that has no valid backends.
Updates tailscale/tailscale#10910
=> cmd/k8s-operator: do not provision resources for a tailscale Ingress that has no valid backends.

appc/appconnector.go, appc/appconnector_test.go, appc/appctest/appctest.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi_test.go
This change allows us to perform batch modification for new route advertisements and route removals. Additionally, we now handle the case where newly added routes are covered by existing ranges.
This change also introduces a new appctest package that contains some shared functions used for testing.
Updates tailscale/corp#16833
=> appc,ipn/ipnlocal: optimize preference adjustments when routes update

appc/appconnector.go, appc/appconnector_test.go, appc/appctest/appctest.go
If control advised the connector to advertise a route that had already been discovered by DNS it would be incorrectly removed. Now those routes are preserved.
Updates tailscale/corp#16833
=> appc: fix removal of domain advertised routes matching control routes

control/controlknobs/controlknobs.go, ipn/ipnlocal/local.go, tailcfg/tailcfg.go, types/key/disco.go, wgengine/magicsock/debughttp.go, wgengine/magicsock/derp.go, wgengine/magicsock/discopingpurpose_string.go, wgengine/magicsock/endpoint.go, wgengine/magicsock/endpoint_test.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
This commit implements probing of UDP path lifetime on the tail end of an active direct connection. Probing configuration has two parts - Cliffs, which are various timeout cliffs of interest, and CycleCanStartEvery, which limits how often a probing cycle can start, per-endpoint. Initially a statically defined default configuration will be used. The default configuration has cliffs of 10s, 30s, and 60s, with a CycleCanStartEvery of 24h. Probing results are communicated via clientmetric counters. Probing is off by default, and can be enabled via control knob. Probing is purely informational and does not yet drive any magicsock behaviors.
Updates #540
=> wgengine/magicsock: implement probing of UDP path lifetime

ipn/ipnlocal/serve.go, ipn/ipnlocal/serve_test.go
When the serve reverse proxy receives a request that matches one of the web handlers, we [strip the handler's mount point section from the request URL](https://github.com/tailscale/tailscale/blob/v1.56.1/ipn/ipnlocal/serve.go#L742-L745) and later [call `httputil.ProxyRequest.SetURL`](https://github.com/tailscale/tailscale/blob/v1.56.1/ipn/ipnlocal/serve.go#L613) with the proxy path on the outgoing request URL.
In an edge case where the request path matches mount path exactly, we end up requesting path with an appended slash from the backend, i.e `/foo` -> `/foo/`. This is because the request path that matched the mount path was set to an empty string in `serveWebHandler`, then `httputil.ProxyRequest.SetURL` [calls `httputil.joinURLPath(<proxyPath>, …
=> ipn/ipnlocal: don't append slash to proxy backend path that matches mount path exactly

net/portmapper/legacy_upnp.go, net/portmapper/portmapper.go, net/portmapper/upnp.go, net/portmapper/upnp_test.go
These are functionally the same as the "urn:schemas-upnp-org" services with a few minor changes, and are still used by older devices. Support them to improve our ability to obtain an external IP on such networks.
Updates #10911
Change-Id: I05501fad9d6f0a3b8cf19fc95eee80e7d16cc2cf
=> net/portmapper: support legacy "urn:dslforum-org" portmapping services

util/expvarx/expvarx.go, util/expvarx/expvarx_test.go
`expvarx.SafeFunc` wraps an `expvar.Func` with a time limit. On reaching the time limit, calls to Value return nil, and no new concurrent calls to the underlying `expvar.Func` will be started until the call completes.
=> util/expvarx: add a time and concurrency limiting expvar.Func wrapper

cmd/tailscale/cli/serve_v2.go
When running as non-root non-operator user, you get this error:
```
$ tailscale serve 8080
Access denied: watch IPN bus access denied, must set ipn.NotifyNoPrivateKeys when not running as admin/root or operator
Use 'sudo tailscale serve 8080' or 'tailscale up --operator=$USER' to not require root.
```
It should fail, but the error message is confusing.
With this fix:
```
$ tailscale serve 8080
sending serve config: Access denied: serve config denied
Use 'sudo tailscale serve 8080' or 'tailscale up --operator=$USER' to not require root.
```
=> cmd/tailscale/cli: run Watch with NotifyNoPrivateKeys

cmd/gitops-pusher/gitops-pusher.go
gitops-pusher supports authenticating with an API key or OAuth credentials (added in #7393). You shouldn't ever use both of those together, so we error if both are set.
In tailscale/gitops-acl-action#24, OAuth support is being added to the GitHub action. In that environment, both the TS_API_KEY and OAuth variables will be set, even if they are empty values.  This causes an error in gitops-pusher which expects only one to be set.
Update gitops-pusher to check that only one set of environment variables are non-empty, rather than just checking if they are set.
Updates #7393
=> cmd/gitops-pusher: fix logic for checking credentials

ipn/ipnlocal/local.go, ipn/ipnlocal/ssh.go, ipn/ipnlocal/ssh_stub.go
When reporting ssh host keys to control, log a warning if we're unable to get the SSH host keys.
Relates to tailscale/support-escalations#21.
=> ipnlocal: log failure to get ssh host keys

ipn/ipnlocal/peerapi.go, ipn/ipnlocal/peerapi_test.go
The API on the DNS record parser is slightly subtle and requires explicit handling of unhandled records. Failure to advance previously resulted in an infinite loop in the pretty responder for any reply that contains a record other than A/AAAA/TXT.
Updates tailscale/corp#16928
=> ipn/ipnlocal: fix pretty printing of multi-record peer DNS results

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
If an app connector is also configured as an exit node, it should still advertise discovered routes that are not covered by advertised routes, excluding the exit node routes.
Updates tailscale/corp#16928
=> ipn/ipnlocal: fix app connector route advertisements on exit nodes

util/deephash/deephash.go, util/deephash/deephash_test.go, util/deephash/types.go, util/deephash/types_test.go
Providing a hashx.Block512 is an implementation detail of how deephash works today, but providing an opaque type with mostly equivalent API (i.e., HashUint8, HashBytes, etc. methods) is still sensible. Thus, define a public Hasher type that exposes exactly the API that an implementation of SelfHasher would want to call. This gives us freedom to change the hashing algorithm of deephash at some point in the future.
Also, this type is likely going to be called by types that are going to memoize their own hash results, we additionally add a HashSum method to simplify this use case.
Add documentation to SelfHasher on how a type might implement it.
Updates: corp#16409
=> util/deephash: tighten up SelfHasher API

types/views/views.go, types/views/views_test.go
views.Slice are meant to be immutable, and if used as such it is at times desirable to use them as a key in a map. For non-viewed slices it was kinda doable by creating a custom key struct but views.Slice didn't allow for the same so add a method to create that struct here.
Updates tailscale/corp#17122
=> types/views: add SliceMapKey[T]

.github/workflows/test.yml, util/linuxfw/nftables_runner.go
We had missed regressions from privileged tests not running, now they can run.
=> .github/workflows: add privileged tests workflow

cmd/containerboot/main.go, cmd/k8s-operator/deploy/manifests/proxy.yaml, cmd/k8s-operator/ingress.go, cmd/k8s-operator/ingress_test.go, cmd/k8s-operator/operator_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/testutils_test.go
This PR allows to optionally configure tailscale Ingress to receive traffic from cluster (on proxy Pod's IP address).
This is meant to be used in conjunction with MagicDNS name resolution in cluster (#11019, #11017) and is useful in cases where a cluster workload and a non-cluster tailnet client both need to access a service running in the cluster using the same hostname (in this case, the MagicDNS name of the ingress proxy). See i.e https://github.com/tailscale/tailscale/issues/10027#issuecomment-1827763853
Users can configure that a proxy created for an Ingress should forward cluster traffic to the backends by setting `tailscale.com/experimental-forward-cluster-traffic-via-ingress` annotation on the `Ingress`.
Note that proxies created for an `Ingress` with this annotation will run …
=> cmd/{containerboot,k8s-operator/deploy/manifests}: optionally allow proxying cluster traffic to a cluster target via ingress proxy

client/web/src/components/login-toggle.tsx, client/web/src/hooks/auth.ts, client/web/web.go, cmd/tailscale/cli/web.go
The new read-only mode is only accessible when running `tailscale web` by passing a new `-readonly` flag. This new mode is identical to the existing login mode with two exceptions:
- the management client in tailscaled is not started (though if it is already running, it is left alone)
- the client does not prompt the user to login or switch to the management client. Instead, a message is shown instructing the user to use other means to manage the device.
I implemented this as a new mode rather than a separate boolean flag on the server, since otherwise it was not obvious to me what it would mean to have a client in manage mode with a read-only flag.  Those things are mutually exclusive, so adding a new mode seemed appropriate.
Updates #10979
=> client/web: add new readonly mode

client/web/package.json, client/web/src/components/exit-node-selector.tsx, client/web/src/components/login-toggle.tsx, client/web/src/components/update-available.tsx, client/web/src/components/views/login-view.tsx, client/web/src/components/views/updating-view.tsx, client/web/yarn.lock
add the curly-quotes eslint plugin (same that we use for the admin panel), and fix existing straight quotes in the current web UI.
=> client/web: use smart quotes in web UI frontend

cmd/dist/dist.go, release/dist/synology/pkgs.go
Running the following to build new Synology package center releases previously ignored the `--synology-package-center` flag, which is vital for making app store releases.
```
./tool/go run ./cmd/dist build synology --synology-package-center
```
This change updates `getTargets` to accept the args passed into the build command. And then checks for existance of the synology flag directly. This also allows us to move the synology flag out of the dist main func and into the CLI func where all other build flags are defined.
Can skip-issubot
=> cmd/dist: fix --synology-package-center flag

ipn/ipnlocal/local.go
Fixes tailscale/support-escalations#23.
authURLs returned by control expire after 1 hour from creation. Customer reported that the Tailscale client on macOS would sending users to a stale authentication page when clicking on the `Login...` menu item. This can happen when clicking on Login after leaving the device unattended for several days. The device key expires, leading to the creation of a new authURL, however the client doesn't keep track of when the authURL was created. Meaning that `login-interactive` would send the user to an authURL that had expired server-side a long time before.
This PR ensures that whenever `login-interactive` is called via LocalAPI, an authURL that is too old won't be used. We force control to give us a new authURL whenever it's been more than 30 minutes …
=> ipnlocal: force-regen new authURL when it is too old

cmd/tailscale/cli/status.go
This change fixes the format of tailscale status output when location based exit nodes are present.
Fixes #11065
=> cmd/tailscale/cli: fix exit node status output

cmd/gitops-pusher/gitops-pusher.go
`os.LookupEnv` may return true if the variable is present in the environment but an empty string. We should only attempt to set OAuth Config if thsoe values are non-empty.
Updates gitops-acl-action#33
=> cmd/gitops-pusher: only use OAuth creds if non-empty string

tsweb/debug.go
Go 1.22.0 introduced the ability to use more expressive routing patterns that include HTTP method when constructing ServeMux entries. Applications that attempted to use these patterns in combination with the old `tsweb.Debugger` would experience a panic as Go would not permit the use of matching rules with mixed level of specificity.
=> tsweb: update Debugger ServeMux routes to 1.22.0 syntax

tsweb/debug.go
Reverts tailscale/tailscale#11087
Updates #cleanup 
This PR needs additional changes to the registration of child handlers under `/debug`
=> Revert "tsweb: update Debugger ServeMux routes to 1.22.0 syntax"

go.mod
This PR should relate to https://github.com/tailscale/tailscale/issues/11058
I saw this issue.
```
$ go mod tidy
go: downloading go1.22 (linux/amd64)                   
go: download go1.22 for linux/amd64: toolchain not available
```
Then, followed https://github.com/golang/go/issues/62278#issuecomment-1933790368, then it's fixed.
=> Specify patch version in go.mod to fix toolchain not available error

client/web/auth.go, client/web/web.go, client/web/web_test.go
For user-owned nodes, only the owner is ever allowed to manage the node.
=> client/web: only check policy caps for tagged nodes

ipn/ipnlocal/local.go, ipn/ipnlocal/tailfs.go, wgengine/netstack/netstack.go
FileSystemForLocal was listening on the node's Tailscale address, which potentially exposes the user's view of TailFS shares to other Tailnet users. Remote nodes should connect to exported shares via the peerapi.
This removes that code so that FileSystemForLocal is only avaialable on 100.100.100.100:8080.
=> tailfs: listen for local clients only on 100.100.100.100

types/views/views_test.go
For a second we thought this was allocating but we were looking at a CPU profile (which showed calls to mallocgc view makeslice) instead of the alloc profile.
Updates golang/go#65685 (which if fixed wouldn't have confused us)
=> types/views: add test that LenIter doesn't allocate

util/topk/topk.go, util/topk/topk_test.go
This package uses a count-min sketch and a heap to track the top K items in a stream of data. Tracking a new item and adding a count to an existing item both require no memory allocations and is at worst O(log(k)) complexity.
Change-Id: I0553381be3fef2470897e2bd806d43396f2dbb36
=> util/topk: add package containing a probabilistic top-K tracker

clientupdate/clientupdate.go
NixOS packages are immutable and attempts to update via our tarball mechanism will always fail as a result. Instead we now direct users to update their nix channel or nixpkgs flake input to receive the latest Tailscale release.
=> clientupdate: disable auto update on NixOS

cmd/tailscale/cli/web.go
Instead of constructing the `ip:port` string ourselves, use netip.AddrPortFrom which handles IPv6 correctly.
Updates #11164
=> cmd/tailscale: support clickable IPv6 web client addresses

tool/gocross/autoflags.go
Adds logic in gocross to detect environment variables and pass the right flags so that the backend can be built with more platforms.
=> tool/gocross: handle additional Xcode build flags

net/dns/direct.go
This fixes an infinite loop caused by the configuration of systemd-resolved on Amazon Linux 2023 and how that interacts with Tailscale's "direct" mode. We now drop the Tailscale service IP from the OS's "base configuration" when we detect this configuration.
Updates #7816
Change-Id: I73a4ea8e65571eb368c7e179f36af2c049a588ee
=> net/dns: fix infinite loop when run on Amazon Linux 2023

logpolicy/logpolicy.go
From a packet trace we have seen log connections being closed prematurely by the client, resulting in unnecessary extra TLS setup traffic.
Updates #3363
Updates tailscale/corp#8564
=> logpolicy: allow longer idle log upload connections

prober/tls.go, prober/tls_test.go
So we can probe load balancers by their unique DNS name but without asking for that cert name.
Updates tailscale/corp#13050
=> prober: add TLS probe constructor to split dial addr from cert name

net/ktimeout/ktimeout.go, net/ktimeout/ktimeout_default.go, net/ktimeout/ktimeout_linux.go, net/ktimeout/ktimeout_linux_test.go, net/ktimeout/ktimeout_test.go
Setting a user timeout will be a more practical tuning knob for a number of endpoints, this provides a way to set it.
Updates tailscale/corp#17587
=> net/ktimeout: add a package to set TCP user timeout

util/syspolicy/policy_keys.go, util/syspolicy/policy_keys_windows.go
Updates tailscale/corp#17652. Adds the ManagedBy* keys presently only used on Darwin platforms to OSS, for the Windows client.
=> util/syspolicy: add ManagedBy keys for Windows

client/web/auth.go, client/web/web.go, client/web/web_test.go
This change adds a new apiHandler struct for use from serveAPI to aid with restricting endpoints to specific peer capabilities.
=> client/web: restrict serveAPI endpoints to peer capabilities

cmd/tailscale/cli/ssh.go
Given that we're already passing the fully-qualified domain to ssh and have written the ssh_known_hosts ourselves, I think we can disable this option which breaks `tailscale ssh`.
Fixes #10348
---
I originally started with attempting to canonicalise the hostname ourselves but I'm not certain I know all transformations involved beyond trimming the final "." from the DNS name (played with in #10342).
=> cmd/tailscale/cli: pass "-o 'CanonicalizeHostname no'" to ssh

cmd/derper/derper.go, derp/derp_server.go, tailcfg/derpmap.go
So derpers can check an external URL for whether to permit access
to a certain public key.
Updates tailscale/corp#17693
=> cmd/derper, derp, tailcfg: add admission controller URL option

util/syspolicy/policy_keys.go, util/syspolicy/policy_keys_windows.go
Updates ENG-2133. Adds the ResetToDefaults visibility policy currently only available on macOS, so that the Windows client can read its value.
=> util/syspolicy: add 'ResetToDefaults'

wgengine/wglog/wglog.go, wgengine/wglog/wglog_test.go
An increasing number of users have very large subnet route configurations, which can produce very large amounts of log data when WireGuard is reconfigured. The logs don't contain the actual routes, so they're largely useless for diagnostics, so we'll just suppress them.
Fixes tailscale/corp#17532
=> wgengine/wglog: quieten WireGuard logs for allowedips

cmd/tailscale/cli/share.go
This adds details on how to configure node attributes to allow sharing and accessing shares.
=> cmd/tailscale: add node attribute instructions to share command help

client/web/auth.go, client/web/src/components/app.tsx, client/web/src/components/login-toggle.tsx, client/web/src/components/views/device-details-view.tsx, client/web/src/components/views/home-view.tsx, client/web/src/hooks/auth.ts, client/web/src/hooks/ts-web-connected.ts, client/web/src/utils/util.ts, client/web/web.go, client/web/web_test.go
Starts using peer capabilities to restrict the management client on a per-view basis. This change also includes a bulky cleanup of the login-toggle.tsx file, which was getting pretty unwieldy in its previous form.
------
Example use of grants where user initially has "ssh" edit capabilities of a tagged device, and then gets updated to having no edit capabilities:
https://github.com/tailscale/tailscale/assets/9019214/f4c9004f-47ff-43fc-b77e-263ee82512d5
=> client/web: use grants on web UI frontend

client/web/package.json, client/web/tsconfig.json, client/web/vite.config.ts, client/web/yarn.lock
Update vite to 5.1.4, and vitest to 1.3.1 (their latest versions). Also remove vite-plugin-rewrite-all as this is no longer necessary with vite 5.x and has a dependency on vite 4.x.
Updates https://github.com/tailscale/corp/issues/17715
=> client/web: update vite and vitest to latest versions

cmd/tailscale/cli/debug.go
Renames a debug flag in the CLI.
=> cli/debug: rename DERP debug mode

.github/workflows/test.yml
This appears to be one of the contributors to this CI target regularly entering a bad state with a partially written toolchain.
Updates #self
=> .github/workflows: fix typo in XDG_CACHE_HOME

cmd/derper/derper.go
I missed a case in the earlier patch, and so we're still sending 15s TCP keepalive for TLS connections, now adjusted there too.
Updates tailscale/corp#17587
Updates #3363
=> cmd/derper: apply TCP keepalive and timeout to TLS as well

net/dns/resolver/forwarder.go
If a client socket is remotely lost but the client is not sent an RST in response to the next request, the socket might sit in RTO for extended lengths of time, resulting in "no internet" for users. Instead, timeout after 10s, which will close the underlying socket, recovering from the situation more promptly.
Updates #10967
=> net/dns: timeout DOH requests after 10s without response headers

wgengine/wgcfg/config.go, wgengine/wgcfg/writer.go
That's already the default. Avoid the overhead of writing it on one side and reading it on the other to do nothing.
Updates #cleanup (noticed while researching something else)
=> wgengine/wgcfg: don't send UAPI to disable keep-alives on new peers

wgengine/wglog/wglog.go
Updates #7617 (part of debugging it)
=> wgengine/wglog: add TS_DEBUG_RAW_WGLOG envknob for raw wg logs

client/web/auth.go, client/web/src/components/app.tsx, client/web/src/components/login-toggle.tsx, client/web/src/components/views/device-details-view.tsx, client/web/src/components/views/home-view.tsx, client/web/src/hooks/auth.ts, client/web/src/hooks/ts-web-connected.ts, client/web/src/utils/util.ts, client/web/web.go, client/web/web_test.go
Merging `soniaappasamy/web-client-use-grants` base working branch for web client grants into main, now that FE and BE work both completed.
The two commits in this PR were already reviewed upon merge into `soniaappasamy/web-client-use-grants` base branch:
* https://github.com/tailscale/tailscale/pull/10894
* https://github.com/tailscale/tailscale/pull/11198
=> Use grants in web client

cmd/tailscaled/tailscaled.go, ipn/ipnlocal/local.go, net/dns/manager_windows.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgengine.go
Tailscaled becomes inoperative if the Tailscale Tunnel wintun adapter is abruptly removed.
wireguard-go closes the device in case of a read error, but tailscaled keeps running.
This adds detection of a closed WireGuard device, triggering a graceful shutdown of tailscaled.
It is then restarted by the tailscaled watchdog service process.
Additionally, the WinTun adapter may have been removed by the time we're closing
the dns.windowsManager, and its associated interface registry key might also have been deleted.
We shouldn't use winutil.OpenKeyWait and wait for the interface key to appear when performing
a cleanup as a part of the windowsManager shutdown.
Fixes #11222
=> Shutdown tailscaled on Windows if wgdevice is closed

cmd/tailscale/cli/up.go, health/health.go, health/healthmsg/healthmsg.go, ipn/ipnlocal/local.go, net/netutil/ip_forward.go, net/netutil/netutil_test.go
When reverse path filtering is in strict mode on Linux, using an exit node blocks all network connectivity. This change adds a warning about this to `tailscale status` and the logs.
Example in `tailscale status`:
```
- not connected to home DERP region 22
- The following issues on your machine will likely make usage of exit nodes impossible: [interface "eth0" has strict reverse-path filtering enabled], please set rp_filter=2 instead of rp_filter=1; see https://github.com/tailscale/tailscale/issues/3310
```
Example in the logs:
```
2024/02/21 21:17:07 health("overall"): error: multiple errors:
not in map poll
The following issues on your machine will likely make usage of exit nodes impossible: [interface "eth0" has strict reverse-path filtering enabled], please set rp_filter=2 instead of …
```
=> health: warn about reverse path filtering and exit nodes

cmd/k8s-operator/operator.go, cmd/k8s-operator/operator_test.go
Ensure that tailscale Ingresses get reconciled if their backend Services change.
This is so that if a backend Service gets created after the Ingress, it gets picked up by the operator else we may end up in a situation where, if a backend Service does not _yet_ exist when an Ingress is applied, the operator does not pick it up after it's created- see #11251
=> cmd/k8s-operator: reconcile tailscale Ingresses when their backend Services change

wgengine/netstack/netstack.go, wgengine/netstack/netstack_test.go
This is a fun one. Right now, when a client is connecting through a subnet router, here's roughly what happens:
1. The client initiates a connection to an IP address behind a subnet router, and sends a TCP SYN
2. The subnet router gets the SYN packet from netstack, and after running through acceptTCP, starts DialContext-ing the destination IP, without accepting the connection¹
3. The client retransmits the SYN packet a few times while the dial is in progress, until either...
4. The subnet router successfully establishes a connection to the destination IP and sends the SYN-ACK back to the client, or...
5. The subnet router times out and sends a RST to the client.
6. If the connection was successful, the client ACKs the SYN-ACK it received, and traffic starts flowing
As a result, the …
=> wgengine/netstack: add a per-client limit for in-flight TCP forwards

tsweb/request_id.go
For use in corp.
Updates tailscale/corp#2549
Change-Id: I71debae1ce9ae48cf69cc44c2ab5c443fc3b2005
=> tsweb: expose function to generate request IDs

net/tstun/wrap.go, wgengine/netstack/netstack.go, wgengine/userspace.go
Change-Id: Ida7e30f4689bc18f5f7502f53a0adb5ac3c7981a
=> net/tstun: fix spelling of "WireGuard"

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/serve_test.go, wgengine/netstack/netstack.go
Previously, we intercepted all userspace traffic to port 8080, which prevented users from exposing their own services to their tailnet at port 8080.
Now, we only intercept traffic to port 8080 if it's bound for 100.100.100.100 or fd7a:115c:a1e0::53.
Fixes #11283
=> ipn,wgengine: only intercept TailFS traffic to quad 100

client/web/package.json, client/web/tailwind.config.js
Starting in Vite 5, Vite now issues a deprecation warning when using a CJS-based Vite config file. This commit fixes it by adding the `"type": "module"` to our package.json to opt our files into ESM module behaviours.
Unlike the corp PR, this one can use `"type": "module"` because we're using Tailwind v3.3+, which supports ESM.
=> client/web: fix Vite CJS deprecation warning

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/serve_test.go, wgengine/netstack/netstack.go
This fixes a regression introduced with 993acf4 and released in v1.60.0.
The regression caused us to intercept all userspace traffic to port 8080 which prevented users from exposing their own services to their tailnet at port 8080.
Now, we only intercept traffic to port 8080 if it's bound for 100.100.100.100 or fd7a:115c:a1e0::53.
Fixes #11283
Signed-off-by: Percy Wegmann <percy@tailscale.com>
(cherry picked from commit 17cd0626f35dbc7948a78665d06a5862fc3dfdab)
=> ipn,wgengine: only intercept TailFS traffic on quad 100

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
We used a HandleSet before when we didn't have a unique handle. But a sessionID is a unique handle, so use that instead. Then that replaces the other map we had.
And now we'll have a way to look up an IPN session by sessionID for later.
Updates tailscale/corp#17859
=> ipn/ipnlocal: make active IPN sessions keyed by sessionID

wgengine/userspace.go
This was just added in 69f4b459 which doesn't yet use it. This still
doesn't yet use it. It just pushes it down deeper into magicsock where
it'll used later.
Updates #7617
=> wgengine: plumb the PeerByKey from wgengine to magicsock

cmd/tailscale/cli/serve_legacy.go, cmd/tailscale/cli/serve_v2.go, cmd/tailscale/cli/serve_v2_test.go, ipn/serve.go, ipn/serve_test.go
In preparation for changes to allow configuration of serve/funnel from the web client, this commit moves some functionality that will be shared between the CLI and web client to the ipn package's serve.go file, where some other util funcs are already defined.
Updates #10261
=> {ipn/serve,cmd/tailscale/cli}: move some shared funcs to ipn

wgengine/magicsock/endpoint.go, wgengine/magicsock/magicsock_test.go
Since link-local addresses are definitionally more likely to be a direct (lower-latency, more reliable) connection than a non-link-local private address, give those a bit of a boost when selecting endpoints.
Updates #8097
Change-Id: I93fdeb07de55ba39ba5fcee0834b579ca05c2a4e
=> wgengine/magicsock: prefer link-local addresses to private ones

client/tailscale/acl.go
Updates tailscale/corp#17770
Allows postures to be annotated in the API, feedback and ACL previews.
=> client/tailscale: add postures to UserRuleMatch

cmd/tailscale/cli/funnel.go, cmd/tailscale/cli/serve_legacy.go, cmd/tailscale/cli/serve_v2.go, ipn/serve.go
Moving logic that manipulates a ServeConfig into recievers on the ServeConfig in the ipn package. This is setup work to allow the web client and cli to both utilize these shared functions to edit the serve config.
Any logic specific to flag parsing or validation is left untouched in the cli command. The web client will similarly manage its validation of user's requested changes. If validation logic becomes similar-enough, we can make a serve util for shared functionality, which likely does not make sense in ipn.
Updates #10261
=> {ipn,cmd/tailscale/cli}: move ServeConfig mutation logic to ipn/serve

util/linuxfw/iptables_runner.go, util/linuxfw/linuxfw.go, util/linuxfw/nftables_runner.go
This PR fixes an issue where the check for whether IPv6 NAT is available was falsely failing in container environments resulting in our default IPv6 masquerading rule not being set up. See #11344 for more context- for example, exit nodes deployed on dual stack Kubernetes clusters were not able to route IPv6 traffic because of the missing masquerading rule.
This PR fixes the IPv6 NAT check for containers:
- removes the check altogether if we are running on nftables. This is because nftables support in kernel was added after the support for IPv6 NAT so a kernel version that supports nftables, but not IPv6 NAT is not possible
- adds an additional check for iptables (the earlier check will always fail because modprobe doesn't normally work in container envs and `/proc/net/ip6_tables_names` is …
=> util/linuxfw: add container-friendly IPv6 NAT check

net/interfaces/interfaces_darwin_test.go
This test could hang because the subprocess was blocked on writing to the stdout pipe if we find the address we're looking for early in the output.
Change-Id: I68d82c22a5d782098187ae6d8577e43063b72573
=> net/interfaces: fix test hang on Darwin

docs/k8s/subnet.yaml
This PR updates our example standalone subnet router deployment yaml to not run in userspace mode.
Folks shouldn't need to run in userspace unless they specifically need it (i.e need to run on host network) and running in userspace would mean a performance hit for the subnet router.
=> docs/k8s: don't run subnet router in userspace mode

cmd/derper/derper.go, types/logger/logger.go, types/logger/logger_test.go
So we can use it in trunkd to quiet down the logs there.
Updates #5563
Change-Id: Ie3177dc33f5ad103db832aab5a3e0e4f128f973f
=> cmd/derper, types/logger: move log filter to shared package

client/web/yarn.lock
Run yarn-deduplicate on yarn.lock to dedupe packages. This is being done to reduce the number of redundant packages fetched by yarn when existing versions in the lockfile satisfy the version dependency we need.
See https://github.com/scinos/yarn-deduplicate for details on the tool used to perform this deduplication.
=> client/web: dedupe packages in yarn.lock

release/dist/synology/pkgs.go, version/mkversion/mkversion.go
Synology requires version numbers are within int32 range. This change updates the version logic to keep things closer within the range, and errors on building when the range is exceeded.
=> version/mkversion: enforce synology versions within int32 range

wgengine/magicsock/derp.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
This pretty much always results in an outage because peers won't discover our new home region and thus won't be able to establish connectivity.
Updates https://github.com/tailscale/corp/issues/18095
Change-Id: Ic0d09133f198b528dd40c6383b16d7663d9d37a7
=> wgengine/magicsock: don't change DERP home when not connected to control

ipn/ipnlocal/local.go, ipn/localapi/localapi.go
To force the problem in its worst case scenario before fixing it.
Updates tailscale/corp#17859
=> ipn/{ipnlocal,localapi}: add debug verb to force spam IPN bus NetMap

clientupdate/clientupdate.go
According to
https://learn.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options#promptrestart, `/promptrestart` is ignored with `/quiet` is set, so msiexec.exe can sometimes silently trigger a reboot. The best we can do to reduce unexpected disruption is to just prevent restarts, until the user chooses to do it. Restarts aren't normally needed for Tailscale updates, but there seem to be some situations where it's triggered.
Updates #18254
=> clientupdate: do not allow msiexec to reboot the OS

net/routetable/routetable_linux_test.go
I was running all tests while preparing a recent stable release, and this was failing because my computer is connected to a fairly large tailnet.
```
--- FAIL: TestGetRouteTable (0.01s)
routetable_linux_test.go:32: expected at least one default route;
...
```
```
$ ip route show table 52  | wc -l
1051
```
=> net/routetable: increase route limit used by the test

cmd/tailscale/cli/configure-kube.go, cmd/tailscale/cli/configure-kube_test.go
When a user deletes the last cluster/user/context from their kubeconfig via `kubectl delete-[cluster|user|context]` command, kubectx sets the relevant field in kubeconfig to 'null' i.e
```
apiVersion: v1
clusters: null
contexts: null
...
```
This was breaking our conversion logic that was assuming that the field is either non-existant or is an array.
Updates tailscale/corp#18320
(cc @timtailscale )
=> cmd/tailscale/cli: fix panic when configuring partially empty kubeconfig

cmd/tailscale/cli/ssh.go, safesocket/safesocket_darwin.go, version/prop.go
Updates ENG-2848
Updates #4518
We can safely disable the App Sandbox for our macsys GUI, allowing us to use `tailscale ssh` and do a few other things that we've wanted to do for a while. This PR:
- allows Tailscale SSH to be used from the macsys GUI binary when called from a CLI
- tweaks the detection of client variants in prop.go, with new functions `IsMacSys()`, `IsMacSysApp()` and `IsMacAppSandboxEnabled()`
=> version,cli,safesocket: detect non-sandboxed macOS GUI

clientupdate/clientupdate.go
Cherry-pick https://github.com/tailscale/tailscale/pull/11409 into 1.62, in case we make a patch release later.
Updates #18254
=> clientupdate: do not allow msiexec to reboot the OS (cherry-pick for 1.62 branch)

envknob/envknob.go
This PR fixes a panic that I saw in the mac app where parsing the env file fails but we don't get to see the error due to the panic of using f.Name()
Fixes #11425
=> envknob: ensure f is not nil before using it

ipn/ipnlocal/local.go, tailcfg/tailcfg.go
Add a disable-web-client node attribute and add handling for disabling the web client when this node attribute is set.
=> ipn/ipnlocal, tailcfg: add disable-web-client node attribute

api.md
This was originally built for testing node expiration flows, but is also useful for customers to force device re-auth without actually deleting the device from the tailnet.
Updates tailscale/corp#18408
=> api.md: document device expiration endpoint

cmd/tailscale/cli/set.go, ipn/ipnlocal/local.go, ipn/prefs.go
Enable the web client over 100.100.100.100 by default. Accepting traffic from [tailnet IP]:5252 still requires setting the `webclient` user pref.
=> ipn/ipnlocal: enable web client over 100.100.100.100 by default

types/views/views.go
In control there are conditions where the leaf functions are not being optimized away (i.e. At is not inlined), resulting in undesirable time spent copying during SliceContains. This optimization is likely irrelevant to simpler code or smaller structures.
Updates #optimization
=> types/views: optimize slices contains under some conditions

cmd/k8s-operator/connector_test.go, cmd/k8s-operator/ingress_test.go, cmd/k8s-operator/operator_test.go, cmd/k8s-operator/proxyclass_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/testutils_test.go, ipn/conf.go
Fix a bug where all proxies got configured with --accept-routes set to true. The bug was introduced in https://github.com/tailscale/tailscale/pull/11238.
Before 1.62 operator proxies were configured via `tailscale set` command that sets `--accept-routes` to the value passed to it explicitly (defaults to false). In #11238 I moved the proxies to use the [`ipn.ConfigVAlpha`](https://pkg.go.dev/tailscale.com@v1.56.1/ipn#ConfigVAlpha) where accept-routes defaults to true if unset, which is the [behaviour of non-linux clients](https://tailscale.com/kb/1019/subnets?q=subnet%20routers#step-6-use-your-subnet-routes-from-other-machines).
This is a breaking change and in some cases can deem proxies unusable (for example, proxy Pod's cluster traffic might be unexpectedly forced via a subnet router …
=> cmd/k8s-operator,ipn/conf.go: fix --accept-routes for proxies

api.md
Mostly inconsequential minor fixes for consistency.  A couple of changes to actual JSON examples, but all still very readable, so I think it's fine.
=> api.md: format API docs with prettier

api.md
Add missing backtick to GET searchpaths api documentation.
=> api.md: add missing backtick to GET searchpaths doc

version/prop.go
Fixes tailscale/corp#18441
For a few days, IsMacAppStore() has been returning `false` on App Store builds (IPN-macOS target in Xcode).
I regressed this in #11369 by introducing logic to detect the sandbox by checking for the `APP_SANDBOX_CONTAINER_ID` environment variable. I thought that was a more robust approach instead of checking the name of the executable. However, it appears that in the CLI this environment variable is not set, so we should go back to the previous logic that checks for the executable path, or `HOME` containing references to macsys. 
This PR also adds additional checks to the logic by also checking `XPC_SERVICE_NAME` in addition to HOME where possible. That environment variable is set inside the network extension, either macos or macsys and is good to look at if for …
=> version/prop: revert IsMacAppSandboxEnabled

wgengine/userspace_ext_test.go
Observed in:
https://github.com/tailscale/tailscale/actions/runs/8350904950/job/22858266932?pr=11463
Updates #11226
Change-Id: I9b57db4b34b6ad91d240cd9fa7e344fc0376d52d
=> wgengine: fix logger data race in tests

control/controlclient/map.go, control/controlclient/map_test.go
Instead of just checking if a peer capmap is nil, also check if the previous state's capmap was nil.
Updates tailscale/corp#17516
=> control/controlclient: fix sending peer capmap changes

tailfs/tailfsimpl/tailfs_test.go
Since TailFS allows spaces in folder and file names, test with spaces.
=> tailfs: include whitespace in test share and filenames

control/controlclient/map.go, control/controlclient/map_test.go
Change-Id: I10fd5e04310cdd7894a3caa3045b86eb0a06b6a0
Okay, this was more trivial than I initially feared it might be
cc @clairew
=> control/controlclient: do not alias peer CapMap

util/reload/reload.go, util/reload/reload_test.go
This can be used to reload a value periodically, whether from disk or another source, while handling jitter and graceful shutdown.
Change-Id: Iee2b4385c9abae59805f642a7308837877cb5b3f
=> util/reload: add new package to handle periodic value loading

util/ringbuffer/ringbuffer.go, wgengine/magicsock/magicsock.go
=> wgengine/magicsock: don't use endpoint debug ringbuffer on mobile.

ipn/ipnlocal/c2n_pprof.go
=> ipn/ipnlocal: add c2n pprof option to force a GC

util/zstdframe/options.go, util/zstdframe/zstd.go, util/zstdframe/zstd_test.go
The Go zstd package is not friendly for stateless zstd compression. Passing around multiple zstd.Encoder just for stateless compression is a waste of memory since the memory is never freed and seldom used if no compression operations are happening.
For performance, we pool the relevant Encoder/Decoder with the specific options set.
Functionally, this package is a wrapper over the Go zstd package with a more ergonomic API for stateless operations.
This package can be used to cleanup various pre-existing zstd.Encoder pools or one-off handlers spread throughout our codebases.
Performance:
BenchmarkEncode/Best               1690        610926 ns/op      25.78 MB/s           1 B/op          0 allocs/op
zstd_test.go:137: memory: 50.336 MiB
zstd_test.go:138: ratio:  3.269x
BenchmarkEncode/Better …
=> util/zstdframe: add package for stateless zstd compression

control/controlclient/direct.go, types/persist/persist.go
In the recent 20e9f3369 we made HealthChangeRequest machine requests
include a NodeKey, as it was the oddball machine request that didn't
include one. Unfortunately, that code was sometimes being called (at
least in some of our integration tests) without a node key due to its
registration with health.RegisterWatcher(direct.ReportHealthChange).
Fortunately tests in corp caught this before we cut a release. It's
possible this only affects this particular integration test's
environment, but still worth fixing.
=> control/controlclient: fix panic regression from earlier load balancer hint header

util/linuxfw/iptables_runner.go, util/linuxfw/linuxfw.go, util/linuxfw/nftables_runner.go, wgengine/router/router_linux.go
=> util/linuxfw,wgengine/router: enable IPv6 configuration when netfilter is disabled

control/controlclient/map.go, ipn/ipnlocal/local.go, types/netmap/netmap.go
When node attributes were super rare, the O(n) slice scans looking for
node attributes was more acceptable. But now more code and more users
are using increasingly more node attributes. Time to make it a map.
Noticed while working on tailscale/corp#17879
=> ipn/ipnlocal, types/netmap: replace hasCapability with set lookup on NetworkMap

tsweb/varz/varz.go, tsweb/varz/varz_test.go
From a problem we hit with how badger registers expvars; it broke
trunkd's exported metrics.
=> tsweb/varz: flesh out munging of expvar keys into valid Prometheus metrics

cmd/tailscale/cli/serve_legacy_test.go, control/controlclient/map.go, control/controlclient/map_test.go, control/controlknobs/controlknobs.go, ipn/ipnlocal/local.go, ipn/ipnlocal/peerapi_test.go, ipn/ipnlocal/serve_test.go, ipn/ipnstate/ipnstate.go, ipn/serve.go, tailcfg/tailcfg.go
First we had Capabilities []string. Then
https://tailscale.com/blog/acl-grants (#4217) brought CapMap, a
superset of Capabilities. Except we never really finished the
transition inside the codebase to go all-in on CapMap. This does so.
Notably, this coverts Capabilities on the wire early to CapMap
internally so the code can only deal in CapMap, even against an old
control server.
In the process, this removes PeerChange.Capabilities support, which no
known control plane sent anyway. They can and should use
PeerChange.CapMap instead.
Updates #11508
Updates #4217
=> all: deprecate Node.Capabilities (more), remove PeerChange.Capabilities [capver 89]

go.mod, go.sum
There's a vulnerability https://pkg.go.dev/vuln/GO-2024-2659 that govulncheck flags, even though it's only reachable from tests and cmd/sync-containers and cannot be exploited there.
=> go.mod: bump github.com/docker/docker

util/linuxfw/iptables_runner.go, util/linuxfw/linuxfw.go, util/linuxfw/nftables_runner.go, wgengine/router/router_linux.go
This cherry-picks @raggi 's fix for Synology subnet router bug in 1.62 to release/1.62 branch.
A user has confirmed that the fix works https://github.com/tailscale/tailscale/issues/11434#issuecomment-2015952670 so we can cherry-pick and release the 1.62.1 patch
Updates #11434
(cherry picked from commit 3f7313dbdbb86b166b115c59bff444b1dc301e64)
=> util/linuxfw,wgengine/router: (cherry-pick) enable IPv6 configuration when netfilter is disabled

cmd/k8s-operator/deploy/chart/values.yaml
Having double quotes (`"`) around the value made it appear like the helm chart should expect a string value for `installCRDs`. When updating the value to `false`, to keep the type the same I initially set it to the string `"false"`, but the chart still tried to create the CRDs. Removing the quotes fixed the issue, but I might have avoided a small inconvenience if the type was more obvious on the default.
=> Update type of installCRDs in kuberenetes-operator helm chart values

.github/workflows/kubemanifests.yaml
CI job path filter does not expect relative paths https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
=> .github/workflows: fix path filter for 'Kubernetes manifests' test job

logtail/logtail.go
Rather than pass around a scratch buffer, put it on the Logger.
This is a baby step towards removing the background uploading
goroutine and starting it as needed.
Updates tailscale/corp#18514 (insofar as it led me to look at this code)
=> logtail: move a scratch buffer to Logger

cmd/k8s-operator/sts.go
Ensure that when auth key is provided to operator's proxy as part of tailscaled config, we don't print it, when the config is being printed for debugging purposes.
What the output looks like now:
```
{"level":"debug","ts":"2024-03-26T14:47:36Z","logger":"service-reconciler","msg":"creating a new Secret for the proxy with tailscaled config {\"Version\":\"alpha0\",\"Locked\":false,\"AuthKey\":\"**redacted**\",\"Hostname\":\"kuard1\",\"acceptDNS\":false,\"acceptRoutes\":false}","service-ns":"default","service-name":"kuard1"}
```
```
{"level":"debug","ts":"2024-03-26T14:46:04Z","logger":"service-reconciler","msg":"patching the existing proxy Secret with tailscaled config {\"Version\":\"alpha0\",\"Locked\":false,\"AuthKey\":\"**redacted**\",\"Hostname\":\"kuard1\",\"acceptDNS\":false,\"acceptRo …
```
=> cmd/k8s-operator: redact auth key from debug logs

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi.go
This change introduces some basic logging into the access and share pathways for tailfs.
Updates tailscale/corp#17818
=> ipn/localipn: introduce logs for tailfs

cmd/tailscale/cli/serve_v2.go
Updates tailscale/corp#18662
Updates the detection logic and shows a (better) error message if attempting to use `tailscale serve` on macsys, where the CLI isn't sandboxed, but the network extension is.
=> cmd/serve: update warning for sandboxed macOS builds

safeweb/http.go, safeweb/http_test.go
Implement a first pass of "safeweb" per the "Secure Internal Web Applications by Default" eng doc.
Safeweb is a wrapper around http.Server & tsnet that encodes some
application security defaults.
Safeweb asks developers to split their HTTP routes into two
http.ServeMuxs for serving browser and API-facing endpoints
repsectively. It then wraps these HTTP routes with the
context-appropriate security controls.
safeweb.Server#Serve will serve the HTTP muxes over the provided
listener. Caller are responsible for creating and tearing down their
application's listeners. Applications being served over HTTPS that wish
to implement HTTP redirects can use the Server#HTTPRedirect handler to
do so.
=> safeweb: init

safeweb/http.go
Change the return type of the safeweb.RedirectHTTP method to a handler
that can be passed directly to http.Serve without any http.HandlerFunc
wrapping necessary.
=> safeweb: return http.Handler from safeweb.RedirectHTTP

cmd/k8s-operator/nameserver_test.go
These got broken because I merged a PR that adds a new test that uses a function whose signature I changed in PR that got merged in between.
=> cmd/k8s-operator: fix failing tests

tsweb/varz/varz.go
Some of our labels contain UTF-8 and get mojibaked in the browser
right now.
Updates tailscale/corp#18687
=> tsweb/varz: add charset=utf-8 to varz handler

util/linuxfw/fake.go, util/linuxfw/iptables_runner.go, util/linuxfw/nftables_runner.go, wgengine/router/router_linux.go, wgengine/router/router_linux_test.go
- In https://github.com/tailscale/tailscale/pull/11381 we added a stricter check for whether ip6tables filter table is supported to fix an issue where, in container environments that ran on hosts with partial support ip6tables (no filter table), we anyway attempted to configure IPv6 firewall, errored out and skipped the rest of the router configuration, resulting in hard-to-debug issues
- https://github.com/tailscale/tailscale/pull/11381 broke Synology IPv6 subnet routers where iptables are not supported, but IPv6 routes should still be set up, see https://github.com/tailscale/tailscale/issues/11430
- We fixed the broken Synology subnet routers in https://github.com/tailscale/tailscale/pull/11494 by changing the configuration logic slightly so that if iptables don't seem to support IPv6, …
=> wgengine/router,util/linuxfw: don't attempt to configure IPv6 firewall rules with ip6tables that don't support filter table

ipn/ipnlocal/local.go
We're tracking down a new instance of memory usage, and excessive memory usage from sockstats is definitely not going to help with debugging, so disable it by default on mobile.
=> ipn/ipnlocal: disable sockstats on (unstable) mobile by default

logtail/logtail.go
This is based on empirical testing using actual logs data.
FastestCompression only incurs a marginal <1% compression ratio hit for a 2.25x reduction in memory use for small payloads (which are common if log uploads happen at a decently high frequency). The memory savings for large payloads is not as notable (1.1x reduction).
LowMemory only incurs a marginal <5% hit on performance for a 1.6-2.0x reduction in memory use for small or large payloads.
The memory gains for both settings justifies the loss of benefits, which are arguably minimal.
tailscale/corp#18514
=> logtail: always zstd compress with FastestCompression and LowMemory

hostinfo/hostinfo.go, hostinfo/hostinfo_linux.go
This was causing a relatively constant ~10ms of delay on Linux.
=> Lazily initialize device model to speed up `init()`

net/packet/icmp4.go, net/packet/icmp6.go, net/packet/packet.go
We now allow some more ICMP errors to flow, specifically:
- ICMP parameter problem in both IPv4 and IPv6 (corrupt headers)
- ICMP Packet Too Big (for IPv6 PMTU)
Updates #311
Updates #8102
Updates #11002
=> net/packet: allow more ICMP errors

safeweb/http.go
Refactor the interaction between caller/library when establishing the HTTP to HTTPS redirects by moving the call to http.Serve into safeweb. This makes linting for other uses of http.Serve easier without having to account for false positives created by the old interface.
=> safeweb: move http.Serve for HTTP redirects into lib

tsweb/tsweb.go
I originally came to update this to match the documented behavior, but the code is deliberately avoiding this behavior currently, making it hard to decide how to update this. For now just align the documentation to the behavior.
=> tsweb: update doc on BucketedStatsOptions.Finish to match behavior

ipn/ipnlocal/serve.go, ipn/ipnlocal/serve_test.go
=> ipn/ipnlocal: q-encode (RFC 2047) Tailscale serve header values

client/tailscale/localclient.go, cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/share.go, cmd/tailscaled/tailscaled.go, drive/driveimpl/drive_test.go, drive/driveimpl/fileserver.go, drive/driveimpl/local_impl.go, drive/driveimpl/remote_impl.go, drive/driveimpl/shared/readonlydir.go, drive/local.go, drive/remote.go, ipn/backend.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/drive.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi.go, ipn/ipnlocal/serve.go, ipn/localapi/localapi.go, ipn/prefs.go, ipn/prefs_test.go, tailcfg/tailcfg.go, tsd/tsd.go, tsnet/tsnet.go, wgengine/netstack/netstack.go, wgengine/userspace.go
This change updates all tailfs functions and the majority of the tailfs variables to use the new drive naming.
Update tailscale/corp#16827
=> tailscale: update tailfs functions and vars to use drive naming

prober/dns.go, prober/dns_example_test.go, prober/dns_test.go
This allows us to check all IP addresses (and address families) for a given DNS hostname while dynamically discovering new IPs and removing old ones as they're no longer valid.
Also add a testable example that demonstrates how to use it.
Alternative to #11610
Updates tailscale/corp#16367
Change-Id: I6d6f39bafc30e6dfcf6708185d09faee2a374599
=> prober: add helper function to check all IPs for a DNS hostname

prober/dns.go, prober/dns_example_test.go, prober/dns_test.go
So that we can e.g. check TLS on multiple ports for a given IP.
Updates tailscale/corp#16367
Change-Id: I81d840a4c88138de1cbb2032b917741c009470e6
=> prober: support creating multiple probes in ForEachAddr

util/zstdframe/options.go, util/zstdframe/zstd_test.go
Specifying a smaller window size during compression provides a knob to tweak the tradeoff between memory usage and the compression ratio.
=> util/zstdframe: support specifying a MaxWindowSize

client/tailscale/localclient.go, cmd/tailscale/cli/share.go, cmd/tailscaled/tailscaled.go, drive/driveimpl/remote_impl.go, ipn/ipnlocal/drive.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi.go, ipn/localapi/localapi.go, tailcfg/tailcfg.go
This change switches the api to /drive, rather than the previous /tailfs as well as updates the log lines to reflect the new value. It also cleans up some existing tailfs references.
=> tailscale: switch tailfs to drive syntax for api and logs

util/truncate/truncate.go
There are no mutations to the input,
so we can support both ~string and ~[]byte just fine.
=> util/truncate: support []byte as well

wgengine/router/router_linux.go
Only on Gokrazy, set sysctls to enable IP forwarding so subnet routing and advertised exit node works.
Implements #11405
=> wgengine/router: enable ip forwarding on gokrazy

metrics/multilabelmap.go
And make NewMultiLabelMap panic earlier (at construction time)
if the comparable struct type T violates the documented rules,
rather than panicking at Add time.
=> metrics: fix outdated docs on MultiLabelMap

drive/remote.go, drive/remote_test.go, ipn/ipnlocal/drive.go, ipn/ipnlocal/local_test.go, ipn/localapi/localapi.go
This change makes the normalizeShareName function public, so it can be
used for validation in control.
=>  drive: move normalizeShareName into pkg drive and make func public

util/linuxfw/nftables_runner.go
Don't compare pointer fields by pointer value, but by the actual value.
`getOrCreateChain` creates a nftables chain template and, for chains prefixed with `ts-`, if a chain already exists checks if the hook and priority are the same.
The check was comparing pointer fields by pointer value. Looks like it was never run a second time with a pre-existing `ts-` chain (?), but started failing in containers after I added #11588 which adds a new `ts-` chain that we attempt to 'get or create' potentially mutliple times during container run if some underlying values (proxy's backend IP) changes.
=> util/linuxfw: fix chain comparison

net/netcheck/netcheck.go, net/netcheck/netcheck_test.go, wgengine/magicsock/derp.go, wgengine/magicsock/derp_test.go
The netcheck package and the magicksock package coordinate via the health package, but both sides have time based heuristics through indirect dependencies. These were misaligned, so the implemented heuristic aimed at reducing DERP moves while there is active traffic were non-operational about 3/5ths of the time.
It is problematic to setup a good test for this integration presently, so instead I added comment breadcrumbs along with the initial fix.
Updates #8603
=> net/netcheck,wgengine/magicsock: align DERP frame receive time heuristics

client/tailscale/localclient.go, cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/exitnode.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/localapi/localapi.go, ipn/prefs.go, ipn/prefs_test.go
This is primarily for GUIs, so they don't need to remember the most
recently used exit node themselves.
This adds some CLI commands, but they're disabled and behind the WIP
envknob, as we need to consider naming (on/off is ambiguous with
running an exit node, etc) as well as automatic exit node selection in
the future. For now the CLI commands are effectively developer debug
things to test the LocalAPI.
Updates tailscale/corp#18724
=> ipn/{ipnlocal,localapi}: add API to toggle use of exit node

cmd/tailscale/cli/ssh.go, net/tsdial/tsdial.go, version/prop.go
net/tsdial: partially fix "tailscale nc" (UserDial) on macOS
At least in the case of dialing a Tailscale IP.
Updates #4529
=> net/tsdial: partially fix "tailscale nc" (UserDial) on macOS

logtail/buffer.go
Buffer.Write has the exact same signature of io.Writer.Write. The latter requires that implementations to never retain the provided input buffer, which is an expectation that most users will have when they see a Write signature.
The current behavior of Buffer.Write where it does retain the input buffer is a risky precedent to set.
Switch the behavior to match io.Writer.Write.
There are only two implementations of Buffer in existence:
* logtail.memBuffer
* filch.Filch
The former can be fixed by cloning to input to Write. This will cause an extra allocation in every Write, but we can fix that will pooling on the caller side in a follow-up PR.
The latter only passes the input to os.File.Write, which does respect the io.Writer.Write requirements.
=> logtail: require Buffer.Write to not retain the provided slice

cmd/tailscaled/tailscaled.go, cmd/tailscaled/tailscaled.service, net/dns/manager.go, util/linuxfw/iptables_runner.go, wgengine/router/router.go, wgengine/router/router_darwin.go, wgengine/router/router_default.go, wgengine/router/router_freebsd.go, wgengine/router/router_linux.go, wgengine/router/router_openbsd.go, wgengine/router/router_windows.go
This removes a potentially increased boot delay for certain boot topologies where they block on ExecStartPre that may have socket activation dependencies on other system services (such as systemd-resolved and NetworkManager).
Fixes #11599
=> cmd/tailscaled: move cleanup to an implicit action during startup

scripts/installer.sh
Extend the `zypper` install to import importing the GPG key used to sign the repository packages.
Fixes #11635
=> scripts/installer.sh: add rpm GPG key import

wgengine/magicsock/magicsock.go, wgengine/magicsock/peermap.go
Just because we don't have known endpoints for a peer does not mean that the peer should become unreachable. If we know the peers key, it should be able to call us, then we can talk back via whatever path it called us on. First step - don't drop the packet in this context.
Updates #self
=> wgengine/magicsock: allow disco communication without known endpoints

.github/licenses.tmpl
This package is included in the tempfork directory, rather than as a go module dependency, so is not included in the normal package list.
=> licenses: add gliderlabs/ssh license

ipn/ipnlocal/local_test.go
=> ipn/ipnlocal: delete useless SetControlClientGetterForTesting use

Makefile
It was broken with the move to dist in 32e0ba5e68 which doesn't accept
amd64 anymore.
=> Makefile: fix default SYNO_ARCH in Makefile

.github/licenses.tmpl
The gliderlabs/ssh license is actually already included in the standard package listing.  I'm not sure why I thought it wasn't.
This reverts commit 11dca08e93b001b93bce6dc4435e7ad2f44d326a.
=> Revert "licenses: add gliderlabs/ssh license"

wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
We have seen in macOS client logs that the "operation not permitted", a
syscall.EPERM error, is being returned when traffic is attempted to be
sent. This may be caused by security software on the client.
This change will perform a rebind and restun if we receive a
syscall.EPERM error on clients running darwin. Rebinds will only be
called if we haven't performed one specifically for an EPERM error in
the past 5 seconds.
Updates https://github.com/tailscale/tailscale/issues/11710
=> wgengine/magicsock: rebind/restun if a syscall.EPERM error is returned

cmd/tsconnect/wasm/wasm_js.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/state_test.go, ipn/localapi/localapi.go, tsnet/tsnet.go
In prep for future fix to undermentioned issue.
Updates tailscale/tailscale#7036
=> ipn/ipnlocal: make StartLoginInteractive take (yet unused) context

ipn/backend.go, ipn/ipnlocal/local.go, wgengine/netstack/netstack_test.go
I'm on a mission to simplify LocalBackend.Start and its locking
and deflake some tests.
I noticed this hasn't been used since March 2023 when it was removed
from the Windows client in corp 66be796d33c.
So, delete.
Updates #11649
=> ipn: remove unused Options.LegacyMigrationPrefs

ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go
We haven't needed this hack for quite some time Andrea says.
Updates #11649
=> ipn/ipnlocal: remove outdated iOS hacky workaround in Start

tailcfg/tailcfg.go
Updates tailscale/corp#17516
Updates #11508
Change-Id: Iad2dafb38ffb9948bc2f3dfaf9c268f7d772cf56
This supercedes #11379 and resolves the [documentation request discussion](https://github.com/tailscale/corp/pull/18027#discussion_r1515168103) in tailscale/corp#11379
=> tailcfg: document use of CapMap for peers

cmd/k8s-operator/deploy/crds/tailscale.com_connectors.yaml, cmd/k8s-operator/deploy/crds/tailscale.com_proxyclasses.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_connector.go, k8s-operator/apis/v1alpha1/types_proxyclass.go
This PR updates the documentation for tailscale.com CRDs. See i.e https://github.com/tailscale/tailscale/issues/10880#issuecomment-2042025682 .
Users will typically view these docs either by running `kubectl explain <crd-name>` or by viewing https://github.com/tailscale/tailscale/blob/main/k8s-operator/api.md that we link from our docs.
Below are the outputs of `kubectl explain <crd-name>` from this PR (top level fields only)
<details>
</details>
Updates tailscale/tailscale#10880
=> cmd/k8s-operator,k8s-operator: document tailscale.com Custom Resource Definitions better.

cmd/tailscale/cli/up.go, tstest/integration/integration_test.go, wgengine/magicsock/magicsock_test.go
Seems to deflake tstest/integration tests. I can't reproduce it
anymore on one of my VMs that was consistently flaking after a dozen
runs before. Now I can run hundreds of times.
Updates #11649
Fixes #7036
=> cmd/tailscale/cli: prevent concurrent Start calls in 'up'

ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/prefs.go
Updates tailscale/corp#18724
When localAPI clients directly set ExitNodeID to "", the expected behaviour is that the prior exit node also gets zero'd - effectively setting the UI state back to 'no exit node was ever selected'
If a client wants to zero the exit node, but remember it, they use SetUseExitNodeEnabled.
The IntenalExitNodePrior has been changed to be a non-opaque type, as it is read by the UI to render the users last selected exit node, and must be concrete type.   Future-us can either break this, or deprecate it and replace it with something more interesting.
=> ipn/{localapi, ipnlocal}: forget the prior exit node when localAPI is used to zero the ExitNodeID

net/interfaces/interfaces.go, net/interfaces/interfaces_test.go
It should've been deleted in 11ece02f5246dee.
Updates #9040
=> net/interfaces: delete unused unexported function

net/interfaces/interfaces.go, net/interfaces/interfaces_test.go
This wasn't previously handling the case where an interface in s2 was removed and not present in s1, and would cause the Equal method to incorrectly return that the states were equal.
Updates tailscale/corp#19124
Change-Id: I3af22bc631015d1ddd0a1d01bfdf312161b9532d
=> net/interfaces: handle removed interfaces in State.Equal

build_docker.sh, ipn/store/store_aws.go, ipn/store/store_kube.go, ipn/store/stores.go
This removes AWS and Kubernetes support from Linux binaries by default
on GOARCH values where people don't typically run on AWS or use
Kubernetes, such as 32-bit mips CPUs.
It primarily focuses on optimizing for the static binaries we
distribute. But for people building it themselves, they can set
ts_kube or ts_aws (the opposite of ts_omit_kube or ts_omit_aws) to
force it back on.
Makes tailscaled binary ~2.3MB (~7%) smaller.
Updates #7272, #10627 etc
=> ipn/store: omit AWS & Kubernetes support on 'small' Linux GOARCHes

safeweb/http.go
=> safeweb: set SameSite=Strict, with an option for Lax

ipn/ipnlocal/local.go
Turns out, `profileManager` is not safe for concurrent use and I missed all the locking infrastructure in `LocalBackend`, oops.
I was not able to reproduce the race even with `go test -race -count 100`, but this seems like an obvious fix.
Fixes #11773
=> ipn/ipnlocal: hold the mutex when in onTailnetDefaultAutoUpdate

tstest/log.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
Most of the magicsock tests fake the network, simulating packets going
out and coming in. There's no reason to actually hit your router to do
UPnP/NAT-PMP/PCP during in tests. But while debugging thousands of
iterations of tests to deflake some things, I saw it slamming my
router. This stops that.
Updates #11762
=> wgengine/magicsock: disable portmapper in tunchan-faked tests

safeweb/http.go
This change is safe (self is still safe, by
definition), and makes the code match the comment.
=> safeweb: allow object-src: self in CSP

drive/driveimpl/compositedav/compositedav.go, drive/driveimpl/compositedav/propfind.go, drive/driveimpl/drive_test.go, drive/driveimpl/shared/pathutil.go
This ensures that MOVE, LOCK and any other verbs that use the Location header work correctly.
Fixes #11758
=> drive: rewrite Location headers

ipn/ipnlocal/local.go
peerapi does not want these, but rclone includes them. Stripping them out allows rclone to work with Taildrive configured as a WebDAV remote.
=> ipn/ipnlocal: strip origin and referer headers from Taildrive requests

clientupdate/clientupdate.go
We don't always have the same latest version for all platforms (like with 1.64.2 is only Synology+Windows), so we should use the OS-specific result from pkgs JSON response instead of the main Version field.
cc @bradfitz 
Updates #11795
=> clientupdate: return OS-specific version from LatestTailscaleVersion

clientupdate/clientupdate.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
Containers are typically immutable and should be updated as a whole (and not individual packages within). Deny enablement of auto-updates in containers.
Also, add the missing check in EditPrefs in LocalAPI, to catch cases like tailnet default auto-updates getting enabled for nodes that don't support it.
Updates #11544
=> ipn/ipnlocal,clientupdate: disallow auto-updates in containers

wgengine/router/ifconfig_windows.go, wgengine/router/router_windows.go
The Network Location Awareness service identifies networks authenticated against an Active Directory domain and categorizes them as "Domain Authenticated". This includes the Tailscale network if a Domain Controller is reachable through it.
If a network is categories as NLM_NETWORK_CATEGORY_DOMAIN_AUTHENTICATED, it is not possible to override its category, and we shouldn't attempt to do so. Additionally, our Windows Firewall rules should be compatible with both private and domain networks.
This fixes both issues.
Fixes #11813
=> wgengine\router: fix the Tailscale-In firewall rule to work on domain networks

control/controlclient/direct.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_view.go, tstest/integration/testcontrol/testcontrol.go
We were storing server-side lots of:
"Auth":{"Provider":"","LoginName":"","Oauth2Token":null,"AuthKey":""},
That was about 7% of our total storage of pending RegisterRequest
bodies.
Updates tailscale/corp#19327
=> tailcfg: pointerify RegisterRequest.Auth, omitemptify RegisterResponseAuth

control/controlclient/direct.go, types/persist/persist.go, types/persist/persist_clone.go, types/persist/persist_test.go, types/persist/persist_view.go
It was only obviously unused after the previous change, c39cde79d.
Updates #19334
=> types/persist: remove unused field Persist.Provider

ipn/ipnlocal/c2n.go, ipn/ipnlocal/local.go, ssh/tailssh/tailssh.go
Since we already track active SSH connections, it's not hard to proactively reject updates until those finish. We attempt to do the same on the control side, but the detection latency for new connections is in the minutes, which is not fast enough for common short sessions.
Handle a `force=true` query parameter to override this behavior, so that control can still trigger an update on a server where some long-running abandoned SSH session is open.
Updates https://github.com/tailscale/corp/issues/18556
=> ipn/ipnlocal,ssh/tailssh: reject c2n /update if SSH conns are active

cmd/tailscaled/tailscaled_windows.go, ipn/localapi/localapi.go, util/osdiag/osdiag.go, util/osdiag/osdiag_notwindows.go, util/osdiag/osdiag_windows.go
There is an undocumented 16KiB limit for text log messages. However, the limit for JSON messages is 256KiB.
Even worse, logging JSON as text results in significant overhead since each double quote needs to be escaped.
Instead, use logger.Logf.JSON to explicitly log the info as JSON.
We also modify osdiag to return the information as structured data rather than implicitly have the package log on our behalf. This gives more control to the caller on how to log.
Updates #7802
=> ipn/local: log OS-specific diagnostic information as JSON

ssh/tailssh/user.go, util/osuser/group_ids.go, util/osuser/group_ids_test.go
I verified that this fixes #11682 by doing the following:
1. Install LDAP on my Ubuntu workstation following [these instructions](https://ubuntu.com/server/docs/install-and-configure-ldap)
2. Enabling ldaps using [these instructions](https://ubuntu.com/server/docs/ldap-and-transport-layer-security-tls)
3. Enabling sssd using [these instructions](https://ubuntu.com/server/docs/how-to-set-up-sssd-with-ldap)
4. Creating a user named `john` who is a member of two posix groups in ldap, `miners` (primary) and `friends` (supplementary)
5. Connecting to this workstation via Tailscale from [VSCode Remote SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) and seeing that the `id` command only returns the primary group `miners`
6. Deploying the fix
7. Killing any …
=> ssh/tailssh: fetch group IDs using the id command

cmd/containerboot/main.go, cmd/k8s-operator/operator_test.go, cmd/k8s-operator/sts.go, cmd/k8s-operator/svc.go, cmd/k8s-operator/testutils_test.go, util/linuxfw/iptables_runner.go, util/linuxfw/nftables_runner.go, wgengine/router/router_linux_test.go
See https://github.com/tailscale/tailscale/issues/10606 for context, especially  https://github.com/tailscale/tailscale/issues/10606#issuecomment-1858858609
This PR adds initial support to exposing targets accessible from within the Kubernetes cluster to tailnet via DNS names using an [`ExternalName` `Service`](https://kubernetes.io/docs/concepts/services-networking/service/#externalname).
To expose a target accessible from within a cluster:
1. A user would create an `ExternalName` `Service`:
```yaml
apiVersion: v1
kind: Service
metadata:
name: foo 
annotations:
tailscale.com/expose: "true"
spec:
type: ExternalName
externalName: <dns-name>
```
2. The Kubernetes operator will reconcile the `Service` and create a proxy based on containerboot  deployment with [`TS_DEST_DNS_NAME` env …
=> cmd{containerboot,k8s-operator},util/linuxfw: support ExternalName Services

go.mod, go.sum, util/linuxfw/iptables_runner.go, util/linuxfw/iptables_runner_test.go, util/linuxfw/linuxfw.go
See https://github.com/tailscale/corp/issues/19336#issuecomment-2072516735 for context - since 1.64 we attempt to clean up firewall rules on every tailscaled start, but our current cleanup was logging error messages if the rules/chains to be cleaned up were not found, which was every time after a 'normal' shutdown that would delete those rules and chains.
This resulted in a lot of confusing logs on start, see below for a container start:
<details>
<code>
...
2024/04/23 17:10:33 dns: using "direct" mode
2024/04/23 17:10:33 dns: using *dns.directManager
2024/04/23 17:10:33 deleting [-j ts-input] in filter/INPUT: running [/sbin/iptables -t filter -D INPUT -j ts-input --wait]: exit status 2: iptables v1.8.9 (legacy): Couldn't load target `ts-input':No such file or directory
Try `iptables -h' …
=> util/linuxfw,go.{mod,sum}: don't log errors when cleaning up non-existant rules/chains

wgengine/router/consolidating_router.go, wgengine/router/consolidating_router_test.go, wgengine/userspace.go
This helps reduce memory pressure on tailnets with large numbers of routes.
Updates tailscale/corp#19332
On a large tailnet like my corp tailnet, this results in about a 23% reduction in the number of routes.
```
26.9M/216.7M router: consolidated 5311 routes down to 4075
```
=> wgengine/router: consolidate routes before reconfiguring router for mobile clients

ipn/ipnlocal/local_test.go, util/syspolicy/caching_handler.go, util/syspolicy/handler.go, util/syspolicy/handler_windows.go, util/syspolicy/syspolicy.go, util/syspolicy/syspolicy_test.go, util/winutil/winutil.go, util/winutil/winutil_notwindows.go, util/winutil/winutil_windows.go
Fixes tailscale/corp#19459
This PR adds the ability for users of the syspolicy handler to read string arrays from the MDM solution configured on the system.
=> util/syspolicy: add ReadStringArray interface

ipn/ipnlocal/local.go
If seamless key renewal is enabled, we typically do not stop the engine (deconfigure networking). However, if the node key has expired there is no point in keeping the connection up, and it might actually prevent key renewal if auth relies on endpoints routed via app connectors.
Fixes tailscale/corp#5800
=> ipn/ipnlocal: always stop the engine on auth when key has expired

release/dist/qnap/pkgs.go
Allows all users to read all files, and .sh/.cgi files to be executable.
Updates tailscale/tailscale-qpkg#135
=> release/dist/qnap: update perms for tmpDir files

control/controlclient/auto.go, control/controlclient/direct.go, health/health.go, health/health_test.go, ipn/ipnlocal/local.go, ipn/ipnlocal/network-lock.go, ipn/localapi/localapi.go, net/dns/direct_linux.go, net/dns/manager.go, net/dns/manager_linux.go, net/dns/resolved.go, net/tlsdial/tlsdial.go, wgengine/magicsock/derp.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go, wgengine/router/ifconfig_windows.go, wgengine/userspace.go
This moves most of the health package global variables to a new
`health.Tracker` type.
But then rather than plumbing the Tracker in tsd.System everywhere,
this only goes halfway and makes one new global Tracker
(`health.Global`) that all the existing callers now use.
A future change will eliminate that global.
Updates #11874
Updates #4136
=> health: add Tracker type, in prep for removing global variables

health/health.go, health/health_test.go, ipn/ipnlocal/local.go, net/dns/direct_linux.go, wgengine/router/ifconfig_windows.go
Previously it was both metadata about the class of warnable item as
well as the value.
Now it's only metadata and the value is per-Tracker.
Updates #11874
Updates #4136
=> health: break Warnable into a global and per-Tracker value halves

health/health.go, health/health_test.go
In prep for tsd.System Tracker plumbing throughout tailscaled,
defensively permit all methods on Tracker to accept a nil receiver
without crashing, lest I screw something up later. (A health tracking
system that itself causes crashes would be no good.) Methods on nil
receivers should not be called, so a future change will also collect
their stacks (and panic during dev/test), but we should at least not
crash in prod.
This also locks that in with a test using reflect to automatically
call all methods on a nil receiver and check they don't crash.
Updates #11874
Updates #4136
=> health: permit Tracker method calls on nil receiver

ipn/ipnlocal/local.go
Fixes tailscale/corp#19558
A request for the suggested exit nodes that occurs too early in the VPN lifecycle would result in a null deref of the netmap and/or the netcheck report.  This checks both and errors out.
=> ipn/ipnlocal: fix null dereference for early suggested exit node queries

net/netutil/ip_forward.go, net/netutil/netutil_test.go
I'm working on moving all network state queries to be on
netmon.Monitor, removing old APIs.
Updates tailscale/corp#10910
Updates tailscale/corp#18960
Updates #7967
Updates #3299
=> net/netutil: remove a use of deprecated interfaces.GetState

cmd/tailscale/cli/netcheck.go, net/netcheck/netcheck.go, net/netcheck/netcheck_test.go, wgengine/magicsock/magicsock.go, wgengine/magicsock/magicsock_test.go
This has been a TODO for ages. Time to do it.
The goal is to move more network state accessors to netmon.Monitor
where they can be cheaper/cached.
Updates tailscale/corp#10910
Updates tailscale/corp#18960
Updates #7967
Updates #3299
=> net/netcheck, wgengine/magicsock: make netmon.Monitor required

ipn/ipnlocal/local_test.go
While it's broken.
Updates #11894
=> ipn/ipnlocal: skip TestOnTailnetDefaultAutoUpdate on macOS for now

cmd/containerboot/kube.go, cmd/containerboot/kube_test.go, cmd/containerboot/main.go, ipn/store/kubestore/store_kube.go, kube/client.go, kube/fake_client.go
See https://github.com/tailscale/tailscale/issues/11170 for context.
This PR fixes a couple small inconsistencies in containerboot flow when on kube:
- if tailscale state needs to be stored in a `Secret`, but the `Secret` does not exist, check that we have permissions to create the `Secret`, if not exit early
- allow interactive login in all cases
At the moment this is a bit inconsistent- if the state `Secret` exists, but the auth key is not provided (neither via env var nor via the `Secret`) we allow the startup flow to continue and users can log in using the URL in logs. But if the state `Secret` does not exist we error out [here](https://github.com/tailscale/tailscale/blob/v1.60.1/cmd/containerboot/main.go#L184). This PR allows the startup flow to continue if the auth key is not …
=> cmd/containerboot,kube,ipn/store/kubestore: allow interactive login on kube, check Secret create perms, allow empty state Secret

api.md
Explicitly set `-H "Content-Type: application/json"` in CURL examples for POST endpoints as the default content type used by CURL is otherwise `application/x-www-form-urlencoded` and these endpoints expect JSON data.
Updates https://github.com/tailscale/tailscale/issues/11914
=> api.md: explicitly set content-type headers in POST CURL examples

wgengine/wgcfg/nmcfg/nmcfg.go
Updates tailscale/corp#19315
Change-Id: I1ad0c8796efe3dd456280e51efaf81f6d2049772
=> wgengine/wgcfg/nmcfg: skip expired peers

appc/appconnector.go, appc/appconnector_test.go, control/controlknobs/controlknobs.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi_test.go, ipn/localapi/localapi.go, tailcfg/tailcfg.go
Users complain that
* there [are bugs when specifying routes from the cli](https://github.com/tailscale/tailscale/issues/11006)
* they [wish when they removed domains from the tailscale config that we removed routes that were advertised](https://github.com/tailscale/tailscale/issues/11008)
Kevin and I have taken a swing at:
* a [prototype for this functionality](https://github.com/tailscale/tailscale/pull/11490/files)
* a [design doc](https://docs.google.com/document/d/1AVUu41LgWklhDnMt6auWEIlbUmgGX5r57McpbSq-m34)
* a [doc describing a follow up issue](https://docs.google.com/document/d/1Xfd8wALjsw0xbmbWQ5rjCkvpb9Fzq7JOixteWWqjm6M) where what we had made prefs act strangely
This PR attempts to be:
* a step towards our full plan
* a 90% solution for the users pain
This PR
* adds a nodeattr …
=> App connectors: unadvertise routes when reconfiguring

scripts/installer.sh
The tailscale package is in the community Alpine repo. Check if it's commented out in `/etc/apk/repositories` and run `setup-apkrepos -c -1` if it's not.
Fixes #11263
=> scripts/installer.sh: enable Alpine community repo if needed

cmd/k8s-operator/deploy/manifests/proxy.yaml, cmd/k8s-operator/testutils_test.go
See #11860 for context- before attempting to enable IPv6 forwarding in the proxy init container check if the relevant module is found, else the container crashes on hosts that don't have it.
Updates#11860
=> cmd/k8s-operator/deploy/manifests:  check if IPv6 module exists before attempting to enable IPv6 forwarding 

ipn/ipnlocal/local_test.go
We don't run CI tests on darwin in this repo, so this failure wasn't caught.
Fixes #11894
=> ipn/ipnlocal: fix TestOnTailnetDefaultAutoUpdate on unsupported platforms

api.md
Add documentation for GET/PATCH/PUT `api/v2/tailnet/<ID>/dns/split-dns`. These endpoints allow for reading, partially updating, and replacing the split DNS settings for a given tailnet.
Updates https://github.com/tailscale/corp/issues/19483
=> api.md: add documentation for new split DNS endpoints

go.mod, go.sum, net/tstun/tun.go, net/tstun/tun_features_linux.go, net/tstun/tun_features_notlinux.go
Certain device drivers (e.g. vxlan, geneve) do not properly handle coalesced UDP packets later in the stack, resulting in packet loss.
Updates #11026
=> net/tstun: implement env var for disabling UDP GRO on Linux

syncs/syncs.go, syncs/syncs_test.go
If AtomicValue[T] is used with a T that is an interface kind, then Store may panic if different concrete types are ever stored.
Fix this by always wrapping in a concrete type.
Technically, this is only needed if T is an interface kind, but there is no harm in doing it also for non-interface kinds.
=> syncs: fix AtomicValue for interface kinds

cmd/k8s-operator/deploy/chart/templates/deployment.yaml, cmd/k8s-operator/deploy/chart/values.yaml
This adds `operatorConfig.podLabels` to the Helm Chart, mirroring the existing `operatorConfig.podAnnotations`.
Fixes #11947
=> cmd/k8s-operator/deploy/chart: podLabels

net/netmon/defaultroute_bsd.go, net/netmon/defaultroute_darwin.go
Updates tailscale/corp#18960
iOS uses Apple's NetworkMonitor to track the default interface and there's no reason we shouldn't also use this on macOS, for the same reasons noted in the comments for why this change was made on iOS.
This eliminates the need to load and parse the routing table when querying the defaultRouter() in almost all cases.
A slight modification here (on both platforms) to fallback to the default BSD logic in the unhappy-path rather than making assumptions that may not hold.  If netmon is eventually parsing AF_ROUTE and able to give a consistently correct answer for the  default interface index, we can fall back to that and eliminate the Swift dependency.
=> net/netmon: swap to swift-derived defaultRoute on macos

net/netmon/defaultroute_darwin.go
Updates tailscale/corp#18960
Tests in corp called us using the wrong logging calls.  Removed. This is logged downstream anyway.
=> net/netmon: remove spammy log statements

net/tstun/wrap.go, net/tstun/wrap_test.go
So that we can use this for additional, non-NAT configuration without it being confusing.
Change-Id: I1658d59c9824217917a94ee76d2d08f0a682986f
=> net/tstun: rename natConfig to peerConfig

cmd/k8s-nameserver/main.go, cmd/k8s-operator/deploy/chart/templates/operator-rbac.yaml, cmd/k8s-operator/deploy/crds/tailscale.com_dnsconfigs.yaml, cmd/k8s-operator/deploy/examples/dnsconfig.yaml, cmd/k8s-operator/deploy/manifests/nameserver/cm.yaml, cmd/k8s-operator/deploy/manifests/nameserver/deploy.yaml, cmd/k8s-operator/deploy/manifests/nameserver/sa.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, cmd/k8s-operator/dnsrecords.go, cmd/k8s-operator/dnsrecords_test.go, cmd/k8s-operator/nameserver.go, cmd/k8s-operator/nameserver_test.go, cmd/k8s-operator/operator.go, cmd/k8s-operator/svc.go, go.mod, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_tsdnsconfig.go, k8s-operator/apis/v1alpha1/zz_generated.deepcopy.go, k8s-operator/tsdns.go
This PR adds functionality to the operator to optionally populate DNS records config for the in-cluster ts.net nameserver (added in #11017) with records for cluster proxies' MagicDNS names:
- For [Tailscale Ingress](https://tailscale.com/kb/1236/kubernetes-operator#exposing-a-service-using-ingress) the record is a mapping between `Ingress`s MagicDNS name and the proxy's Pod IP 
- For cluster egress proxies configured via `tailscale.com/tailnet-fqdn` annotation the record is a mapping between the annotation's value and the proxy's Pod IP
No records are currently created for any other proxy types.
The records are created only if there is a ready `tailscale.com/v1alpha1.DNSConfig` instance in the cluster (see #11017 ) i.e if users have explicitly configured the operator to deploy the …
=> cmd/{k8s-operator,k8s-nameserver},k8s-operator: update nameserver config with records for ingress/egress proxies

cmd/k8s-operator/deploy/crds/tailscale.com_proxyclasses.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_proxyclass.go
In https://github.com/tailscale/tailscale/pull/11699 we added a new `proxyClass.spec.metrics` field to allow users to expose tailscled metrics on proxy Pod IP. However the tailscaled metrics are currently considered unstable, so we should warn users that breaking changes will be made in the future.
=> cmd/k8s-operator/deploy,k8s-operator: document that metrics are unstable

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/network-lock_test.go, ipn/ipnlocal/peerapi_test.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_test.go, ipn/ipnlocal/serve_test.go, ipn/ipnlocal/ssh_test.go
Setting the field after-the-fact wasn't working because we could migrate prefs on creation, which would set health status for auto updates.
Updates #11986
Change-Id: I41d79ebd61d64829a3a9e70586ce56f62d24ccfd
=> ipn/ipnlocal: plumb health.Tracker into profileManager constructor

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, wgengine/magicsock/magicsock.go
tailscale/corp#19681
Start storing last suggested exit node id, and fallback on the suggestion if the last exit node suggestion exists.
=> ipnlocal: store last suggested exit node in local backend

cmd/k8s-operator/generate/main.go, cmd/k8s-operator/operator.go
Cleans up `runReconciler` signature, updates a couple log messages.
=> cmd/k8s-operator: clean up runReconciler signature

util/set/set.go, util/set/set_test.go
set.Of(1, 2, 3) is prettier than set.SetOf([]int{1, 2, 3}).
I was going to change the signature of SetOf but then I noticed its
name has stutter anyway, so I kept it for compatibility. People can
prefer to use set.Of for new code or slowly migrate.
Also add a lazy Make method, which I often find myself wanting,
without having to resort to uglier mak.Set(&set, k, struct{}{}).
=> util/set: add Of variant of SetOf that takes variadic parameter

cmd/tailscale/cli/up.go, control/controlclient/direct.go, ipn/ipnlocal/local.go, tstest/integration/integration_test.go
The CLI "up" command is a historical mess, both on the CLI side and
the LocalBackend side. We're getting closer to cleaning it up, but in
the meantime it was again implicated in flaky tests.
In this case, the background goroutine running WatchIPNBus was very
occasionally running enough to get to its StartLoginInteractive call
before the original goroutine did its Start call. That meant
integration tests were very rarely but sometimes logging in with the
default control plane URL out on the internet
(controlplane.tailscale.com) instead of the localhost control server
for tests.
This also might've affected new Headscale etc users on initial "up".
Fixes #11962
=> cmd/tailscale/cli: don't start WatchIPNBus until after up's initial Start

net/tstun/wrap.go, net/tstun/wrap_test.go
This refactors the peerConfig struct to allow storing more details about a peer and not just the masq addresses. To be used in a follow up change.
As a side effect, this also makes the DNAT logic on the inbound packet stricter. Previously it would only match against the packets dst IP, not it also takes the src IP into consideration. The beahvior is at parity with the SNAT case.
Updates tailscale/corp#19623
Change-Id: I5f40802bebbf0f055436eb8824e4511d0052772d
=> net/tstun: refactor peerConfig to allow storing more details

cmd/tailscale/cli/cli_test.go, cmd/tailscale/cli/up.go, ipn/ipn_clone.go, ipn/ipn_view.go, ipn/ipnlocal/local.go, ipn/ipnlocal/profiles.go, ipn/ipnlocal/profiles_test.go, ipn/prefs.go, ipn/prefs_test.go, tailcfg/tailcfg.go, util/linuxfw/fake.go, util/linuxfw/iptables_runner.go, util/linuxfw/nftables_runner.go, wgengine/router/router.go, wgengine/router/router_linux.go, wgengine/router/router_linux_test.go, wgengine/router/router_test.go
Adds new `--stateful-filtering` flag to `tailscale up/set` which enables a stateful firewall using iptables/nftables on Linux subnet routers. Backfill the flag to match `--snat-subnet-routes`, as it could break some connections when mismatched.
Updates https://github.com/tailscale/corp/issues/19623
Change-Id: I7980e1fb736e234e66fa000d488066466c96ec85
=> various: allow configuring stateful firewalling on Linux

control/controlknobs/controlknobs.go, net/dns/resolver/forwarder.go, tailcfg/tailcfg.go
Now that tsdial.Dialer.UserDial has been updated to honor the configured routes and dial external network addresses without going through Tailscale, while also being able to dial a node/subnet router on the tailnet, we can start using UserDial to forward DNS requests. This is primarily needed for DNS over TCP when forwarding requests to internal DNS servers, but we also update getKnownDoHClientForProvider to use it.
Updates tailscale/corp#18725
=> net/dns/resolver: use UserDial instead of SystemDial to dial DNS servers

control/controlclient/map.go, ipn/ipnlocal/local.go, net/tstun/wrap.go, tailcfg/tailcfg.go, tailcfg/tailcfg_clone.go, tailcfg/tailcfg_test.go, tailcfg/tailcfg_view.go, tstest/integration/integration_test.go, tstest/integration/testcontrol/testcontrol.go, wgengine/userspace.go, wgengine/watchdog.go, wgengine/wgcfg/config.go, wgengine/wgcfg/nmcfg/nmcfg.go, wgengine/wgcfg/wgcfg_clone.go, wgengine/wgengine.go
Broken up into two commits.
The first commit is a no-op and does the refactor necessary to use two different packet filters,
the second commit does the plumbing and hooks up the new jailed packet filter for peers and
adds a test to ensure that jailing works as expected.
```
ipn/ipnlocal,net/tstun,wgengine: create and plumb jailed packet filter
This plumbs a packet filter for jailed nodes through to the
tstun.Wrapper; the filter for a jailed node is equivalent to a "shields
up" filter. Currently a no-op as there is no way for control to
tell the client whether a peer is jailed.
```
```
tailcfg,all: add/plumb Node.IsJailed
This adds a new bool that can be sent down from control
to do jailing on the client side. Previously this would
only be done from control by modifying the packet filter …
```
=> all: add client side jailing of peers

tailcfg/tailcfg.go
Missed in f62e678df8e1d4a3fd3a41f8c847c6b0a3605ac8.
Updates tailscale/corp#18725
Updates #4529
=> tailcfg: bump capver for using NodeAttrUserDialUseRoutes for DNS

cmd/tailscale/cli/ffcomplete/complete.go
=> cmd/tailscale/cli/ffcomplete: remove fullstop from ShortHelp

client/web/web.go
Web version of https://github.com/tailscale/tailscale-android/pull/370 This allows us to update the prefs rather than creating new prefs
Updates tailscale/tailscale#11731
=> web: use EditPrefs instead of passing UpdatePrefs to starting

net/netcheck/netcheck.go
It was documented as such but seems to have been dropped in a refactor, restore the behavior. This brings down the time it takes to run a single integration test by 2s which adds up quite a bit.
Updates tailscale/corp#19786
=> net/netcheck: do not add derps if IPv4/IPv6 is set to "none"

ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go
This removes one of the Lock,Unlock,Lock,Unlock at least in the Start function. Still has 3 more of these.
Updates #11649
=> ipn/ipnlocal: use lockAndGetUnlock in Start

control/controlclient/client.go, ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go
We used to Lock, Unlock, Lock, Unlock quite a few
times in Start resulting in all sorts of weird race conditions. Simplify it all and only Lock/Unlock once.
Updates #11649
=> ipn/ipnlocal: acquire b.mu once in Start

ipn/ipnlocal/local_test.go, ipn/ipnlocal/loglines_test.go, ipn/ipnlocal/peerapi_test.go, ipn/ipnlocal/serve_test.go, ipn/ipnlocal/state_test.go, ipn/localapi/localapi_test.go, wgengine/bench/wg.go, wgengine/netstack/netstack_test.go, wgengine/userspace.go, wgengine/userspace_ext_test.go, wgengine/userspace_test.go, wgengine/watchdog_test.go
I saw some panics in CI, like:
2024-05-08T04:30:25.9553518Z ## WARNING: (non-fatal) nil health.Tracker (being strict in CI):
2024-05-08T04:30:25.9554043Z goroutine 801 [running]:
2024-05-08T04:30:25.9554489Z tailscale.com/health.(*Tracker).nil(0x0)
2024-05-08T04:30:25.9555086Z 	tailscale.com/health/health.go:185 +0x70
2024-05-08T04:30:25.9555688Z tailscale.com/health.(*Tracker).SetUDP4Unbound(0x0, 0x0)
2024-05-08T04:30:25.9556373Z 	tailscale.com/health/health.go:532 +0x2f
2024-05-08T04:30:25.9557296Z tailscale.com/wgengine/magicsock.(*Conn).bindSocket(0xc0003b4808, 0xc0003b4878, {0x1fbca53, 0x4}, 0x0)
2024-05-08T04:30:25.9558301Z 	tailscale.com/wgengine/magicsock/magicsock.go:2481 +0x12c5
2024-05-08T04:30:25.9559026Z tailscale.com/wgengine/magicsock.(*Conn).rebind(0xc0003b4808, 0x0) …
=> ipn/ipnlocal, all: plumb health trackers in tests

cmd/tailscale/cli/up.go, control/controlclient/auto.go, control/controlclient/direct.go, ipn/ipnlocal/local.go, ipn/ipnstate/ipnstate.go, tstest/integration/integration_test.go
The CLI's "up" is kinda chaotic and LocalBackend.Start is kinda
chaotic and they both need to be redone/deleted (respectively), but
this fixes some buggy behavior meanwhile. We were previously calling
StartLoginInteractive (to start the controlclient's RegisterRequest)
redundantly in some cases, causing test flakes depending on timing and
up's weird state machine.
We only need to call StartLoginInteractive in the client if Start itself
doesn't. But Start doesn't tell us that. So cheat a bit and a put the
information about whether there's a current NodeKey in the ipn.Status.
It used to be accessible over LocalAPI via GetPrefs as a private key but
we removed that for security. But a bool is fine.
So then only call StartLoginInteractive if that bool is false and don't
do it in the …
=> cmd/tailscale,controlclient,ipnlocal: fix 'up', deflake tests more

api.md
My vscode formatter did this for me automatically, so happy to turn that off if we want to keep things as-is, but this update is more correct from a json syntax perspective.
=> api.md: remove extraneous commas in json examples

wgengine/netstack/netstack.go, wgengine/netstack/netstack_test.go
Previously, a node that was advertising a 4via6 route wouldn't be able to make use of that same route; the packet would be delivered to Tailscale, but since we weren't accepting it in handleLocalPackets, the packet wouldn't be delivered to netstack and would never hit the 4via6 logic. Let's add that support so that usage of 4via6 is consistent regardless of where the connection is initiated from.
Updates #11304
Change-Id: Ic28dc2e58080d76100d73b93360f4698605af7cb
=> wgengine/netstack: handle 4via6 routes that are advertised by the same node

cmd/k8s-operator/nameserver.go, cmd/k8s-operator/nameserver_test.go
This PR starts defaulting the image for the nameserver, that the Kubernetes operator can optionally deploy, to `tailscale/k8s-nameserver:unstable`.
We are now publishing nameserver images to `tailscale/k8s-nameserver`, so we can start defaulting the images if users haven't set them explicitly, same as we already do with proxy images.
The nameserver images are currently only published for unstable track, so we have to use the static 'unstable' tag. Once we start publishing to stable, we can make the operator default to its own tag (because then we'll know that for each operator tag X there is also a nameserver tag X as we always cut all images for a given tag.
Updates tailscale/tailscale#10499
=> cmd/k8s-operator: default nameserver image to tailscale/k8s-nameserver:unstable

util/linuxfw/nftables_runner.go
To match iptables:
https://github.com/tailscale/tailscale/blob/b5dbf155b1b0fbd5947160d8bca4085c6ff039a5/util/linuxfw/iptables_runner.go#L536
Updates #12066
=> util/linuxfw: fix stateful packet filtering in nftables mode

cmd/tailscale/cli/set.go, cmd/tailscale/cli/up.go
We were missing `snat-subnet-routes`, `stateful-filtering` and `netfilter-mode`. Add those to set too.
Fixes #12061
=> cmd/tailscale: add missing set flags for linux

util/linuxfw/nftables_runner.go
Updates #12061
Follow-up to #12072
Change-Id: I2ba8c4bff14d93816760ff5eaa1a16f17bad13c1
=> util/linuxfw: fix table name in DelStatefulRule

wgengine/router/router_linux.go, wgengine/router/router_linux_test.go
When Docker is detected on the host and stateful filtering is enabled, Docker containers may be unable to reach Tailscale nodes (depending on the network settings of a container). Detect Docker when stateful filtering is enabled and print a health warning to aid users in noticing this issue.
Updates #12070
Change-Id: Idef538695f4d101b0ef6f3fb398c0eaafc3ae281
=> wgengine/router: print Docker warning when stateful filtering is enabled

drive/driveimpl/compositedav/compositedav.go, drive/driveimpl/compositedav/stat_cache.go, drive/driveimpl/compositedav/stat_cache_test.go, drive/driveimpl/shared/pathutil.go
Clients often perform a PROPFIND for the parent directory before performing PROPFIND for specific children within that directory. The PROPFIND for the parent directory is usually done at depth 1, meaning that we already have information for all of the children. By immediately adding that to the cache, we save a roundtrip to the remote peer on the PROPFIND for the specific child.
Updates tailscale/corp#19779
=> drive: parse depth 1 PROPFIND results to include children in cache

types/views/views.go
This was a typo in 2e19790f611cd15d603eac35bae46cb3c707ef85. It should have been on `Map` and not on `*Map` as otherwise it doesn't allow for chaining like `someView.SomeMap().AsMap()` and requires first assigning it to a variable.
Updates #typo
=> types/views: move AsMap to Map from *Map

ipn/ipnlocal/local.go, ipn/ipnlocal/state_test.go
The previous LocalBackend & CLI 'up' changes improved some stuff, but
might've been too aggressive in some edge cases.
This simplifies the authURL vs authURLSticky distinction and removes
the interact field, which seemed to just just be about duplicate URL
suppression in IPN bus, back from when the IPN bus was a single client
at a time. This moves that suppression to a different spot.
Fixes #12119
Updates #12028
Updates #12042
=> ipn/ipnlocal: simplify authURL vs authURLSticky, remove interact field

util/linuxfw/iptables_runner.go, util/linuxfw/linuxfw.go, util/linuxfw/nftables_runner.go, util/linuxfw/nftables_runner_test.go
See #11353 for context- this change fixes a firewall NAT availability check that was using the no-longer set ipv6NATAvailable field by removing the field and using a method that, for nftables, just checks that IPv6 is available.
When running firewall in nftables mode,
there is no need for a separate NAT availability check (unlike with iptables, there are no hosts that support nftables, but not IPv6 NAT - see tailscale/tailscale#11353).
I have tested that with this change the IPv6 NAT table gets created as expected:
<details>
<code>
/ # nft list ruleset
table ip filter {
chain FORWARD {
type filter hook forward priority filter; policy accept;
counter packets 0 bytes 0 jump ts-forward
}
chain INPUT {
type filter hook input priority filter; policy accept;
counter packets 114 bytes 26380 jump …
=> util/linuxfw: fix IPv6 availability check for nftables

util/linuxfw/iptables_runner.go, util/linuxfw/linuxfw.go, util/linuxfw/nftables_runner.go, util/linuxfw/nftables_runner_test.go
Cherry-pick of https://github.com/tailscale/tailscale/pull/12009
=> util/linuxfw: fix IPv6 nat for nftables (cherry-pick)

derp/derp_server.go, derp/derp_server_default.go, derp/derp_server_linux.go
Without changing behaviour, don't create a goroutine per connection that sits and sleeps, but rather use a timer that wakes up and gathers statistics on a regular basis.
Fixes #12127
Change-Id: Ibc486447e403070bdc3c2cd8ae340e7d02854f21
=> derp: remove stats goroutine, use a timer

net/tstun/wrap.go
In a configuration where the local node (ip1) has a different IP (ip2) that it uses to communicate with a peer (ip3) we would do UDP flow tracking on the `ip2->ip3` tuple. When we receive the response from the peer `ip3->ip2` we would dnat it back to `ip3->ip1` which would then not match the flow track state and the packet would get dropped.
To fix this, we should do flow tracking on the `ip1->ip3` tuple instead of `ip2->ip3` which requires doing SNAT after the running filterPacketOutboundToWireGuard.
Updates tailscale/corp#19971, tailscale/corp#8020
=> net/tstun: do SNAT after filterPacketOutboundToWireGuard

prober/derp.go
=> prober: plumb a now-required netmon to derphttp

net/dns/publicdns/publicdns.go, net/dns/publicdns/publicdns_test.go
In this commit I updated the Ipv6 range we use to generate Control D DOH ip, we were using the NextDNSRanges to generate Control D DOH ip, updated to use the correct range.
Solves: #12144
Updates: #7946
=> Net/DNS/Publicdns: update the IPv6 range that we use to recreate route endpoint for control D

version/prop.go, version/version.go
Reverts the previous change that didn't add CommitTime and only added CommitDate in a new exported function. Instead of exporting that, add a new field to Meta instead.
=> version: add GitCommitTime to Meta

tool/gocross/autoflags.go, tool/gocross/autoflags_test.go
Tracking down the side effect can otherwise be a pain, for example on Darwin an empty GOOS resulted in CGO being implicitly disabled. The user intended for `export GOOS=` to act like unset, and while this is a misunderstanding, the main toolchain would treat it this way.
Fixes tailscale/corp#20059
=> tool/gocross: treat empty GOOS/GOARCH as native GOOS/GOARCH

publicapi/device.md, publicapi/overview.md, publicapi/tailnet.md
This change creates a new folder called publicapi that will become the future home to the Tailscale public API docs.
This change also splits the existing API docs (still located in api.md) into separate files, for easier reading and contribution.
Updates tailscale/corp#19526
=> publicapi: create new home for API docs and split into catagory files

cmd/tailscale/cli/netcheck.go, net/netcheck/netcheck.go, net/netcheck/netcheck_test.go, wgengine/magicsock/magicsock.go
Palo Alto firewalls have a typically hard NAT, but also have a mode
called Persistent DIPP that is supposed to provide consistent port
mapping suitable for STUN resolution of public ports. Persistent DIPP
works initially on most Palo Alto firewalls, but some models/software
versions have a bug which this works around.
The bug symptom presents as follows:
- STUN sessions resolve a consistent public IP:port to start with
- Much later netchecks report the same IP:Port for a subset of
sessions, most often the users active DERP, and/or the port related
to sustained traffic.
- The broader set of DERPs in a full netcheck will now consistently
observe a new IP:Port.
- After this point of observation, new inbound connections will only
succeed to the new IP:Port observed, and existing/old sessions …
=> net/netcheck,wgengine/magicsock: add potential workaround for Palo Alto DIPP misbehavior

publicapi/device.md, publicapi/deviceinvites.md, publicapi/overview.md, publicapi/tailnet.md, publicapi/userinvites.md
This PR does two things:
1. Updates the new publicapi docs to include the user and device invites
2. Edits the existing api.md file to point the TOC at the new documentation home, and removes the API docs content since it will live in the new folder!.
=> publicapi: include user and device invites, and point existing docs to the new format.

util/lru/lru.go, util/lru/lru_test.go
Updates tailscale/corp#20109
Change-Id: I751a669251a70f0134dd1540c19b274a97608a93
=> util/lru: add Clear method

cmd/tailscale/cli/netcheck.go, net/netcheck/netcheck.go, net/netcheck/netcheck_test.go, wgengine/magicsock/magicsock.go
Palo Alto reported interpreting hairpin probes as LAND attacks, and the firewalls may be responding to this by shutting down otherwise in use NAT sessions prematurely. We don't currently make use of the outcome of the hairpin probes, and they contribute to other user confusion with e.g. the AirPort Extreme hairpin session workaround. We decided in response to remove the whole probe feature as a result.
Updates #188
Updates tailscale/corp#19106
Updates tailscale/corp#19116
=> net/netcheck: remove hairpin probes

tool/gocross/autoflags.go, tool/gocross/autoflags_test.go
We don't build a lot of tools with CGO, but we do build some, and it's extremely valuable for production services in particular to have symbols included - for perf and so on.
I tested various other builds that could be affected negatively, in particular macOS/iOS, but those use split-dwarf already as part of their build path, and Android which does not currently use gocross.
One binary which is normally 120mb only grew to 123mb, so the trade-off is definitely worthwhile in context.
Updates tailscale/corp#20296
=> tool/gocross: add debug data to CGO builds

cmd/k8s-operator/deploy/chart/values.yaml
Add a note to the proxy config opts in helm chart values file pointing at ProxyClass CRD docs, which has more config opts and is where new configuration knobs will be added in the future.
Updates tailscale/tailscale#12242
=> cmd/k8s-operator: update proxy config opts in Helm chart values with a note pointing to ProxyClass CRD

cmd/k8s-operator/operator.go
Fixes #11980
First PR.. looking to pick up some of the lower hanging fruit https://github.com/tailscale/tailscale/labels/kubernetes issues to learn more about k8s operators / go / tailscale.
=> cmd/k8s-operator: fix CRD manifest generation for kube-generate-all make target

Makefile, go.mod, go.sum, ssh/tailssh/incubator.go, ssh/tailssh/incubator_linux.go, ssh/tailssh/privs_test.go, ssh/tailssh/tailssh_integration_test.go, ssh/tailssh/testcontainers/Dockerfile, tailcfg/tailcfg.go
This allows pam authentication to run, triggering automation
like pam_mkhomedir.
Updates #11854
=> ssh/tailssh: fall back to using su when no TTY available on Linux

util/linuxfw/iptables_runner.go, wgengine/router/router_linux.go
This busybox fwmaskWorks check was added before we moved away from
using the "ip" command to using netlink directly.
So it's now just wasted work (and log spam on Gokrazy) to check the
"ip" command capabilities if we're never going to use it.
Do it lazily instead.
Updates #12277
=> wgengine/router: probe generally-unused "ip" command style lazily

cmd/tailscale/cli/network-lock.go, ipn/ipnlocal/network-lock.go, ipn/ipnstate/ipnstate.go, tka/sig.go
- Add current node signature to `ipnstate.NetworkLockStatus`;
- Print current node signature in a human-friendly format as part of `tailscale lock status`.
Examples:
```
$ tailscale lock status
Tailnet lock is ENABLED.
This node is accessible under tailnet lock. Node signature:
SigKind: direct
Pubkey: [OTB3a]
KeyID: tlpub:44a0e23cd53a4b8acc02f6732813d8f5ba8b35d02d48bf94c9f1724ebe31c943
WrappingPubkey: tlpub:44a0e23cd53a4b8acc02f6732813d8f5ba8b35d02d48bf94c9f1724ebe31c943
This node's tailnet-lock key: tlpub:44a0e23cd53a4b8acc02f6732813d8f5ba8b35d02d48bf94c9f1724ebe31c943
Trusted signing keys:
tlpub:44a0e23cd53a4b8acc02f6732813d8f5ba8b35d02d48bf94c9f1724ebe31c943	1	(self)
tlpub:6fa21d242a202b290de85926ba3893a6861888679a73bc3a43f49539d67c9764	1	(pre-auth key kq3NzejWoS11KTM59)
```
For a node …
=> cmd/tailscale/cli: print node signature in `tailscale lock status`

derp/derp_server.go
the `counter_packets_dropped_reason` metric is using incorrect labels
#2745 added `dropReasonDupClient` without the corresponding metric label
#7552 added the label "gone_not_here" without the corresponding `dropReason`
The actual reasons are
```
const (
dropReasonUnknownDest      dropReason = iota // unknown destination pubkey
dropReasonUnknownDestOnFwd                   // unknown destination pubkey on a derp-forwarded packet
dropReasonGoneDisconnected                   // destination tailscaled disconnected before we could send
dropReasonQueueHead                          // destination queue is full, dropped packet at queue head
dropReasonQueueTail                          // destination queue is full, dropped packet at queue tail
dropReasonWriteError                         // OS …
```
=> fix: fix dropReason metrics labels

tsweb/log.go, tsweb/tsweb.go, tsweb/tsweb_test.go
This change makes our access log record more consistent with the new log/tslog package formatting of "time". Note that we can change slog itself to call "time" "when" but we're chosing to make this breaking change to be consistent with the std lib's defaults.
Updates tailscale/corp#17071
=> tsweb: rename AccessLogRecord's When to Time

derp/derp_server.go, derp/dropreason_string.go
The derp metrics got out of sync in 74eb99aed17539 (2023-03).
They were fixed in 0380cbc90d6 (2024-05).
This adds some further guardrails (atop the previous fix) to make sure
they don't get out of sync again.
Updates #12288
=> derp: add some guardrails for derpReason metrics getting out of sync

docs/k8s/subnet.yaml
In https://github.com/tailscale/tailscale/pull/11363 I changed the subnet router manifest to run in tun mode (for performance reasons), but did not
change the security context to give it NET_ADMIN cap, which is required to for the tailscale socket.
I have tested that the updated manifests deploy a functioning subnet router.
Updates tailscale/tailscale#12083
=> docs/k8s: fix subnet router manifest

cmd/containerboot/kube.go, ipn/store/kubestore/store_kube.go
In our environment, the endpoint for `kubernetes.default.svc` is in the RFC6598 address range. This conflicts with the range Tailscale uses for node address assignment; additionally, the proxy pod drops traffic to addresses in this range that are not from the `tailscale` interface:
`iifname != "tailscale0*" ip saddr 100.64.0.0/10 counter packets 0 bytes 0 drop`
Previously we worked around this by setting `--netfilter-mode=off` but as of #11238 this has become more challenging. 
I would like to instead override the address `containerboot` uses to talk to the kubernetes api server and point it to something not in the RFC6598 range. Having tested this locally it does appear to resolve my issue (where `containerboot` cannot `POST` to `kubernetes.default.svc`) 
Closes #11397
=> kube: allow overriding client api server URL via ENV

cmd/tailscale/cli/up.go
Cherry-pick of https://github.com/tailscale/tailscale/pull/12312 into `1.66` release branch
Updates tailscale/tailscale#12307
=> cmd/tailscale/cli: allow 'tailscale up' to succeed if a previously set `--stateful-filtering` flag is unset

control/controlclient/direct.go, ipn/ipnlocal/network-lock.go, ipn/ipnlocal/network-lock_test.go, tka/sig.go, tka/sig_test.go, tka/tka.go
A non-signing node can be allowed to re-sign its new node keys following key renewal/rotation (e.g. via `tailscale up --force-reauth`). To be able to do this, node's TLK is written into WrappingPubkey field of the initial SigDirect signature, signed by a signing node.
The intended use of this field implies that, for each WrappingPubkey, we typically expect to have at most one active node with a signature tracing back to that key. Multiple valid signatures referring to the same WrappingPubkey can occur if a client's state has been cloned, but it's something we explicitly discourage and don't support: https://tailscale.com/s/clone
This change propagates rotation details (wrapping public key, a list of previous node keys that have been rotated out) to netmap processing, and adds tracking of …
=> ipn/ipnlocal: discard node keys that have been rotated out

net/dns/osconfig.go
Change-Id: I48834a0a5944ed35509c63bdd2830aa34e1bddeb
=> net/dns: fix typo in OSConfig logging

ipn/ipnlocal/local_test.go
This mostly removes a lot of repetition by predefining some nodes and other data structures, plus adds some helpers for creating Peer entries in the netmap. Several existing test cases were reworked to ensure better coverage of edge cases, and several new test cases were added to handle some additional responsibility that is in (or will be shortly moving in) suggestExitNode().
Change-Id: Ie14c2988d7fd482f7d6a877f78525f7788669b85
=> ipn/ipnlocal: simplify suggest exit node tests

tsnet/tsnet.go
A `*listener` implements net.Listener which breaks a test in another repo.
Regressed in 42cfbf427c671265d3c1fc47408b7961aa7eaec4.
Updates #12182
=> tsnet: return net.Listener from s.listen

cmd/natc/natc.go
This adds a new prototype `cmd/natc` which can be used to expose a services/domains to the tailnet.
It requires the user to specify a set of IPv4 prefixes from the CGNAT range. It advertises these as normal subnet routes. It listens for DNS on the first IP of the first range provided to it.
When it gets a DNS query it allocates an IP for that domain from the v4 range. Subsequent connections to the assigned IP are then tcp proxied to the domain.
It is marked as a WIP prototype and requires the use of the `TAILSCALE_USE_WIP_CODE` env var.
Updates tailscale/corp#20503
=> cmd/natc: initial implementation of a NAT based connector

ipn/ipnlocal/autoupdate.go, ipn/ipnlocal/autoupdate_disabled.go, ipn/ipnlocal/c2n.go, ipn/ipnlocal/local.go
When the client is disconnected from control for any reason (typically just turned off), we should still attempt to update if auto-updates are enabled. This may help users who turn tailscale on infrequently for accessing resources.
Updates #12117
=> ipn/ipnlocal: periodically run auto-updates when "offline"

cmd/stunstamp/stunstamp.go, cmd/stunstamp/stunstamp_default.go, cmd/stunstamp/stunstamp_linux.go
Extremely late arriving responses may leak across probing intervals.
Updates tailscale/corp#20344
=> cmd/stunstamp: validate STUN tx ID in responses

ipn/ipnlocal/local.go
Clean up the updater goroutine on shutdown, in addition to doing that on backend state change. This fixes a goroutine leak on shutdown in tests.
=> ipn/ipnlocal: stop offline auto-updates on shutdown

cmd/k8s-operator/deploy/chart/templates/deployment.yaml, cmd/k8s-operator/deploy/chart/values.yaml
Using helm coalesce function: https://helm.sh/docs/chart_template_guide/function_list/#coalesce
Fixes #12100
=> cmd/k8s-operator: Support image 'repo' or 'repository' keys in helm values file

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
Rather than building a new suggested exit node set every time, compute it once on first use. Currently, syspolicy ensures that values do not change without a restart anyway.
Since the set is being constructed in a separate func now, the test code that manipulates syspolicy can live there, and the TestSuggestExitNode can now run in parallel with other tests because it does not have global dependencies.
Change-Id: Ic4bb40ccc91b671f9e542bd5ba9c96f942081515
=> ipn/ipnlocal: only build allowed suggested node list once

net/dns/manager.go, net/dns/manager_tcp_test.go, net/dns/manager_test.go, wgengine/userspace.go
This PR addresses a DNS issue on macOS as discussed this morning.
=> net/dns: don't set MatchDomains on Apple platforms when no upstream nameservers available

cmd/k8s-operator/proxy.go, cmd/k8s-operator/proxy_test.go, tailcfg/tailcfg.go
Move `tailscale.com/cap/kubernetes` peer cap to location shared with control.
This is done in preparation for adding kubectl session recording rules to this capability grant that will need to be unmarshalled by control, so will also need to be in a shared location.
Next steps will be to move the actual cap type definiton to a shared location too and add the rules for exec https://github.com/tailscale/tailscale/pull/12236
cc @tomhjp 
Updates tailscale/corp#19821
=> tailcfg,cmd/k8s-operator: move tailscale.com/cap/kubernetes peer cap to location shared with control

go.mod, go.sum, ipn/ipnlocal/cert.go
Update our fork of golang.org/x/crypto to pick up a fix for ACME ARI: https://github.com/tailscale/golang-x-crypto/commit/3fde5e568aa421f641805f385e599b6e5a40e837
Fixes #12278
=> go.mod,ipn/ipnlocal: update the ACME fork

tsnet/tsnet.go
Add a new error when users attempt to use tsnet https serving on a tailnet with HTTPS enabled but MagicDNS disabled
[Issue](https://github.com/tailscale/tailscale/issues/12303)
=> tsnet: add a new error when HTTPS enabled but MagicDNC Disabled

net/netcheck/netcheck.go
This bug was introduced in e6b84f215 (May 2020) but was only used in
tests when stringifying probeProto values on failure so it wasn't
noticed for a long time.
But then it was moved into non-test code in 8450a18aa (Jun 2024) and I
didn't notice during the code movement that it was wrong. It's still
only used in failure paths in logs, but having wrong/ambiguous
debugging information isn't the best.
Whoops.
Updates tailscale/corp#20654
=> net/netcheck: fix probeProto.String result for IPv6 probes

cmd/derpprobe/derpprobe.go, prober/derp.go
To make it easier for people to monitor their custom DERP fleet.
Updates tailscale/corp#20654
=> cmd/derpprobe: support 'local' derpmap to get derp map via LocalAPI

cmd/k8s-operator/sts.go, ipn/ipnlocal/local.go, wgengine/netstack/netstack_userping_apple.go
Some lint warnings caught by running 'make lint' locally.
Change-Id: I1534ed6f2f5e1eb029658906f9d62607dad98ca3
=> various: fix lint warnings

control/controlknobs/controlknobs.go, net/dns/manager.go, tailcfg/tailcfg.go
Updates tailscale/corp#15802.
Adds the ability for control to disable the recently added change that uses split DNS in more cases on iOS. This will allow us to disable the feature if it leads to regression in production. We plan to remove this knob once we've verified that the feature works properly.
=> tailcfg,net/dns: add controlknob to disable battery split DNS on iOS

ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go
The last suggested exit node needs to be incorporated in the decision making process when a new suggestion is requested, but currently it is not quite right: it'll be used if the suggestion code has an error or a netmap is unavailable, but it won't be used otherwise.
Instead, this makes the last suggestion into a tiebreaker when making a random selection between equally-good options. If the last suggestion does not make it to the final selection pool, then a different suggestion will be made.
Since LocalBackend.SuggestExitNode is back to being a thin shim that sets up the parameters to suggestExitNode, it no longer needs a test. Its test was unable to be comprehensive anyway as the code being tested contains an uncontrolled random number generator.
Change-Id: …
=> ipn/ipnlocal: improve sticky last suggestion

net/dns/manager.go, net/dns/manager_test.go
Looks like #12346 as submitted with failing tests.
Updates #12346
=> net/dns: fix crash in tests

cmd/k8s-operator/deploy/crds/tailscale.com_dnsconfigs.yaml, cmd/k8s-operator/deploy/examples/dnsconfig.yaml, cmd/k8s-operator/deploy/manifests/operator.yaml, k8s-operator/api.md, k8s-operator/apis/v1alpha1/types_tsdnsconfig.go
Update the DNSConfig CRD fields to better document how to use the CRD.
```
irbe@tailscale$ k explain dnsconfig
GROUP:      tailscale.com
KIND:       DNSConfig
VERSION:    v1alpha1
DESCRIPTION:
DNSConfig can be deployed to cluster to make a subset of Tailscale MagicDNS
names resolvable by cluster workloads. Use this if: A) you need to refer to
tailnet services, exposed to cluster via Tailscale Kubernetes operator
egress proxies by the MagicDNS names of those tailnet services (usually
because the services run over HTTPS) B) you have exposed a cluster workload
to the tailnet using Tailscale Ingress and you also want to refer to the
workload from within the cluster over the Ingress's MagicDNS name (usually
because you have some callback component that needs to use the same URL as
that used by …
```
=> k8s-operator/apis/v1alpha1: update DNSConfig CRD description

cmd/k8s-operator/proxy.go, cmd/k8s-operator/proxy_test.go, kube/grants.go, tailcfg/tailcfg.go, tailcfg/tailcfg_test.go
This PR is in preparation of adding logic to control to parse `tailscale.com/cap/kubernetes` caps (to resolve recorder tags to IPs):
- moves the type definitions of `tailscale.com/cap/kubernetes` cap rules to a location that can be shared with control (`./kube`)
- adds `recorder`, `enforceRecorder` rules to this cap that will be used to control session recording for `kubectl exec` sessions via the kube API server proxy
- adds a convenience function to marshal arbitrary cap rules to raw messages + a test
An example grants definition with a recording capability:
```
"grants": [{
"src": ["tag:eng"],
"dst": ["tag:k8s-operator"],
"app": {
"tailscale.com/cap/kubernetes": [{
"recorder": ["tag:my-recorder"],
"enforceRecorder": true
}],
},
}
]
```
The grants in this example:
- enforce that when …
=> tailcfg,cmd/k8s-operator,kube: move Kubernetes cap type defintion to shared location, add exec rules definition

cmd/k8s-nameserver/main.go, cmd/k8s-nameserver/main_test.go
See https://github.com/tailscale/tailscale/issues/12321 for context- although the nameserver for [cluster MagicDNS name resolution](https://tailscale.com/kb/1236/kubernetes-operator#expose-a-tailnet-https-service-to-your-cluster-workloads) does not currently support IPv6, we have to assume that AAAA records will be queries as part of normal DNS client query workflow
Return empty response and NOERROR for AAAA record queries for DNS names for which the nameserver has an A record.
This is to allow for callers that might be first sending an AAAA query and then, if that does not return a response, follow with an A record query. Previously we were returning NOTIMPL that caused some callers to potentially not follow with an A record query or misbehave in different ways.
Also return NXDOMAIN for …
=> cmd/k8s-nameserver: fix AAAA record query response

util/singleflight/singleflight.go, util/singleflight/singleflight_test.go
This is a variant of DoChan that supports context propagation, such that the context provided to the inner function will only be canceled when there are no more waiters for a given key. This can be used to deduplicate expensive and cancelable calls among multiple callers safely.
Updates #11935
Change-Id: Ibe1fb67442a854babbc6924fd8437b02cc9e7bcf
=> util/singleflight: add DoChanContext

tailcfg/tailcfg.go
Missed in b65221999ca2644e917efce394dc0c9603cfacb7.
Updates tailscale/corp#15802
=> tailcfg: bump capver for NodeAttrDisableSplitDNSWhenNoCustomResolvers

kube/grants.go, tailcfg/tailcfg_test.go
Add an additional `RecorderAddrs` field to `tailscale.com/cap/kubernetes` capability rule to separate the field set by users only, from the field populated by control with the addresses resolved from the tags provided the `Recorders` field.
Updates tailscale/corp#19821
=> kube,tailcfg: store parsed recorder tags in a separate field

kube/grants.go
=> kube: fix typo

ssh/tailssh/incubator.go, ssh/tailssh/testcontainers/Dockerfile
Checking in the incubator as this used to do fails because the getenforce command is not on the PATH.
Updates #12442
=> ssh/tailssh: check for SELinuxEnforcing in tailscaled process

ssh/tailssh/incubator.go, ssh/tailssh/testcontainers/Dockerfile
Checking in the incubator as this used to do fails because the getenforce command is not on the PATH.
Updates #12442
Signed-off-by: Percy Wegmann <percy@tailscale.com>
(cherry picked from commit d7fdc01f7f1266fa6cddefcb0dd07d81b445cdca)
=> ssh/tailssh: check IsSELinuxEnforcing in tailscaled process

tailcfg/tailcfg.go
We do not intend to use this value for feature support communication in the future, and have applied changes elsewhere that now fix the expected value.
Updates tailscale/corp#19391
Updates tailscale/corp#20398
=> tailcfg: update PeerAPIDNS Port value documentation

posture/serialnumber_ios.go, posture/serialnumber_stub.go, tailcfg/tailcfg.go, util/syspolicy/policy_keys.go
Fixes tailscale/corp#18366.
This PR provides serial number collection on iOS, by allowing system administrators to pass a `DeviceSerialNumber` MDM key which can be read by the `posture` package in Go.
=> xcode/iOS: support serial number collection via MDM on iOS

control/controlclient/direct.go, health/args.go, health/health.go, health/health_test.go, health/state.go, health/warnings.go, ipn/backend.go, ipn/ipnlocal/local.go, net/dns/direct_linux.go, wgengine/router/ifconfig_windows.go, wgengine/router/router_linux.go
This PR is the first round of work to move from encoding health warnings as strings and use structured data instead. The current health package revolves around the idea of Subsystems. Each subsystem can have (or not have) a Go error associated with it. The overall health of the backend is given by the concatenation of all these errors.
This PR polishes the concept of Warnable introduced by @bradfitz a few weeks ago. Each Warnable is a component of the backend (for instance, things like 'dns' or 'magicsock' are Warnables). Each Warnable has a unique identifying code. A Warnable is an entity we can warn the user about, by setting (or unsetting) a WarningState for it. Warnables have:
- an identifying Code, so that the GUI can track them as their WarningStates …
=> health: begin work to use structured health warnings instead of strings, pipe changes into ipn.Notify

cmd/tailscaled/tailscaled.go, control/controlknobs/controlknobs.go, net/dns/manager.go, net/dns/manager_darwin.go, net/dns/manager_default.go, net/dns/manager_freebsd.go, net/dns/manager_linux.go, net/dns/manager_openbsd.go, net/dns/manager_windows.go, net/dns/manager_windows_test.go, tailcfg/tailcfg.go
Without this rule, Windows 8.1 and newer devices issue parallel DNS requests to DNS servers associated with all network adapters, even when "Override local DNS" is enabled and/or a Mullvad exit node is being used, resulting in DNS leaks.
This also adds "disable-local-dns-override-via-nrpt" nodeAttr that can be used to disable the new behavior if needed.
Fixes tailscale/corp#20718
=> various: create a catch-all NRPT rule when "Override local DNS" is enabled on Windows

wgengine/filter/filter.go, wgengine/filter/filter_clone.go, wgengine/filter/filter_test.go, wgengine/filter/match.go, wgengine/filter/tailcfg.go
NewContainsIPFunc returns a contains matcher optimized for its
input. Use that instead of what this did before, always doing a test
over each of a list of netip.Prefixes.
goos: darwin
goarch: arm64
pkg: tailscale.com/wgengine/filter
│   before    │                after                │
│   sec/op    │   sec/op     vs base                │
FilterMatch/file1-8   32.60n ± 1%   18.87n ± 1%  -42.12% (p=0.000 n=10)
Updates #12486
=> wgengine/filter: use NewContainsIPFunc for Srcs matches

cmd/viewer/tests/tests_view.go, cmd/viewer/viewer.go, ipn/ipnlocal/local.go, ipn/ipnlocal/serve.go, tailcfg/tailcfg_view.go, types/views/views.go
This abstraction provides a nicer way to work with
maps of slices without having to write out three long type
params.
Updates tailscale/corp#20910
=> cmd/viewer,type/views: add MapSlice for maps of slices

wgengine/filter/filter_test.go
I noticed the not-local-v6 numbers were nowhere near the v4 numbers
(they should be identical) and then saw this. It meant the
Addr().Next() wasn't picking an IP that was no longer local, as
assumed.
Updates #12486
=> wgengine/filter: fix copy/pasteo in new benchmark's v6 CIDR

wgengine/filter/filter.go, wgengine/filter/filter_test.go
If we already know it's an incoming IPv4 packet, no need to match
against the set of IPv6s and vice versa.
goos: darwin
goarch: arm64
pkg: tailscale.com/wgengine/filter
│   before    │                after                │
│   sec/op    │   sec/op     vs base                │
FilterMatch/not-local-v4-8             21.40n ± 3%   16.04n ± 1%  -25.09% (p=0.000 n=10)
FilterMatch/not-local-v6-8             20.75n ± 9%   15.71n ± 0%  -24.31% (p=0.000 n=10)
FilterMatch/no-match-v4-8              81.37n ± 1%   78.57n ± 3%   -3.43% (p=0.005 n=10)
FilterMatch/no-match-v6-8              77.73n ± 2%   73.71n ± 3%   -5.18% (p=0.002 n=10)
FilterMatch/tcp-not-syn-v4-8           21.41n ± 3%   16.86n ± 0%  -21.25% (p=0.000 n=10)
FilterMatch/tcp-not-syn-v4-no-logs-8   10.04n ± 0%   10.05n ± 0%        ~ …
=> wgengine/filter: split local+logs lookups by IPv4-vs-IPv6

net/ipset/ipset.go, net/ipset/ipset_test.go
For pprof cosmetic/confusion reasons more than performance, but it
might have tiny speed benefit.
Updates #12486
=> net/ipset: skip the loop over Prefixes when there's only one

clientupdate/clientupdate.go, clientupdate/clientupdate_test.go
Previously, we would only compare the current version to resolved latest version for track. When running `tailscale update --track=stable` from an unstable build, it would almost always fail because the stable version is "older". But we should support explicitly switching tracks like that.
Fixes #12347
=> clientupdate: allow switching from unstable to stable tracks

cmd/tailscale/cli/update.go
We do not support specific version updates or track switching on macOS. Do not populate the flag to avoid confusion.
Fixes https://github.com/tailscale/corp/issues/20939
=> cmd/tailscale/cli: do not allow update --version on macOS

cmd/containerboot/kube.go, cmd/containerboot/main.go, cmd/k8s-operator/sts.go
For Kubernetes operator proxies, the proxy device ID, tailnet IPs and MagicDNS name are stored in a Kubernetes `Secret`.
Device ID is used [when cleaning up a device](https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/sts.go#L228-L234) and tailnet IPs and MagicDNS name are stored on resources that users interact with for visibility (i.e [`Ingress`'s status](https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/ingress.go#L278-L295)).
At the moment, all three are stored at the same time, once the proxy route setup has succeeded.
This means that if proxy route setup fails, the operator won't be able to clean up the device, see #12146 .
This PR splits the device info storing - we now store device ID early to ensure that it's availabe even if route setup has failed. …
=> cmd/{containerboot,k8s-operator}: store proxy device ID early to help with cleanup for broken proxies

client/tailscale/localclient.go, cmd/tailscale/cli/whois.go, ipn/ipnlocal/local.go, ipn/ipnlocal/local_test.go, ipn/ipnlocal/peerapi.go, ipn/ipnlocal/serve.go, ipn/localapi/localapi.go, ipn/localapi/localapi_test.go, proxymap/proxymap.go, ssh/tailssh/tailssh.go, ssh/tailssh/tailssh_test.go, wgengine/netstack/netstack.go
Previously, we were registering TCP and UDP connections in the same map, which could result in erroneously removing a mapping if one of the two connections completes while the other one is still active.
Add a "proto string" argument to these functions to avoid this.
Updates https://github.com/tailscale/corp/issues/20600
Change-Id: I35d5efaefdfbf4721e315b8ca123f0c8af9125fb
=> proxymap: distinguish between different protocols

net/tstun/wrap_test.go, util/deephash/deephash_test.go, wgengine/filter/filter.go, wgengine/filter/filter_test.go, wgengine/filter/filtertype/filtertype.go, wgengine/filter/filtertype/filtertype_clone.go, wgengine/filter/match.go, wgengine/filter/tailcfg.go
I noticed we were allocating these every time when they could just
share the same memory. Rather than document ownership, just lock it
down with a view.
I was considering doing all of the fields but decided to just do this
one first as test to see how infectious it became.  Conclusion: not
very.
Updates #cleanup (while working towards tailscale/corp#20514)
=> wgengine/filter/filtertype: make Match.IPProto a view

health/health_test.go, health/state.go
Updates #4136
Small PR to expose the health Warnables dependencies to the GUI via LocalAPI, so that we can only show warnings for root cause issues, and filter out unnecessary messages before user presentation.
=> health: expose DependsOn to local API via UnhealthyState

health/args.go, health/health.go, health/warnings.go, ipn/ipnlocal/local.go
Fixes tailscale/corp#20971
We added some Warnables for DERP failure situations, but their Text currently spits out the DERP region ID ("10") in the UI, which is super ugly. It would be better to provide the RegionName of the DERP region that is failing. We can do so by storing a reference to the last-known DERP map in the health package whenever we fetch one, and using it when generating the notification text.
This way, the following message...
> Tailscale could not connect to the relay server '10'. The server might be temporarily unavailable, or your Internet connection might be down.
becomes:
> Tailscale could not connect to the 'Seattle' relay server. The server might be temporarily unavailable, or your Internet connection might be down.
which is a lot more user-friendly.
=> health: include DERP region name in bad derp notifications

net/flowtrack/flowtrack.go, net/flowtrack/flowtrack_test.go, net/packet/tsmp.go, wgengine/filter/filter.go, wgengine/filter/filter_test.go, wgengine/pendopen.go
This gets UDP filter overhead closer to TCP. Still ~2x, but no longer ~3x.
goos: darwin
goarch: arm64
pkg: tailscale.com/wgengine/filter
│   before    │                after                │
│   sec/op    │   sec/op     vs base                │
FilterMatch/tcp-not-syn-v4-8         15.43n ± 3%   15.38n ± 5%        ~ (p=0.339 n=10)
FilterMatch/udp-existing-flow-v4-8   42.45n ± 0%   34.77n ± 1%  -18.08% (p=0.000 n=10)
geomean                              25.59n        23.12n        -9.65%
Updates #12486
=> net/flowtrack: optimize Tuple type for use as map key

derp/derp_server.go
It was hex-ifying the String() form of key.NodePublic, which was already hex.
I noticed in some logs:
"client 6e6f64656b65793a353537353..."
And thought that 6x6x6x6x looked strange. It's "nodekey:" in hex.
=> derp: fix fmt verb for nodekeys

health/health.go
Fixes tailscale/tailscale#12534
Looks like a DERPmap might not be available when we try to get the name associated with a region ID, and that was causing an intermittent panic in CI.
=> health: fix nil map dereference panic

control/controlhttp/client.go
=> control/controlhttp: add health warning for macOS filtering blocking Tailscale

.github/workflows/ssh-integrationtest.yml, Makefile, ssh/tailssh/incubator.go, ssh/tailssh/tailssh_integration_test.go, ssh/tailssh/testcontainers/Dockerfile
This allows the SSH_AUTH_SOCK environment variable to work inside of
su and agent forwarding to succeed.
Fixes https://github.com/tailscale/tailscale/issues/12467
=> ssh/tailssh: replace incubator process with su instead of running su as child

wgengine/filter/filter.go
Changes "Accept" TCP logs to display in verbose logs only, and removes lines from default logging behavior.
Updates #12158
=> wgengine/filter: mark "Accept" TCP log lines as verbose

cmd/proxy-to-grafana/proxy-to-grafana.go
This PR adds a flag to proxy-to-grafana so it can connect to an alternative control server.
=> cmd/proxy-to-grafana: add flag for alternative control server

appc/appconnector.go
When the store-appc-routes flag is on for a tailnet we are writing the routes more often than seems necessary. Investigation reveals that we are doing so ~every time we observe a dns response, even if this causes us not to advertise any new routes. So when we have no new routes, instead do not advertise routes.
Fixes #12593
=> appc: don't schedule advertisement of 0 routes

cmd/derper/mesh.go, derp/derp.go, derp/derphttp/derphttp_test.go, derp/derphttp/mesh_client.go
PeerPresentFlags was added in 5ffb2668ef but wasn't plumbed through to
the RunConnectionLoop. Rather than add yet another parameter (as
IP:port was added earlier), pass in the raw PeerPresentMessage and
PeerGoneMessage struct values, which are the same things, plus two
fields: PeerGoneReasonType for gone and the PeerPresentFlags from
5ffb2668ef.
Updates tailscale/corp#17816
=> derp: make RunConnectionLoop funcs take Messages, support PeerPresentFlags

ipn/ipnlocal/local.go
So non-local users (e.g. Kerberos on FreeIPA) on Linux can be looked
up. Our default binaries are built with pure Go os/user which only
supports the classic /etc/passwd and not any libc-hooked lookups.
Updates #12601
=> ipn/ipnlocal: check operator user via osuser package

net/dns/manager.go, net/dns/resolver/forwarder.go, net/dns/resolver/tsdns.go
Fixes tailscale/corp#20677
Replaces the original attempt to rectify this (by injecting a netMon event) which was both heavy handed, and missed cases where the netMon event was "minor".
On apple platforms, fetching the interface's nameservers can and does return an empty list in certain situations.   Apple's API in particular is very limiting here.  The header hints at notifications for dns changes which would let us react ahead of time, but it's all private APIs.
To avoid remaining in the state where we end up with no nameservers but we absolutely need them, we'll react to a lack of upstream nameservers by attempting to re-query the OS.
We'll rate limit this to space out the attempts.   It seems relatively harmless to attempt a reconfig every 5 seconds (triggered by an incoming query) if …
=> net/dns: attempt to reload interface nameservers on SERVFAIL errors

wgengine/magicsock/derp.go, wgengine/magicsock/magicsock_test.go
The logic we added in #11378 would prevent selecting a home DERP if we have no control connection.
Updates tailscale/corp#18095
Change-Id: I44bb6ac4393989444e4961b8cfa27dc149a33c6e
=> wgengine/magicsock: always set home DERP if no control conn

net/dns/direct.go, net/dns/direct_unix_test.go, net/dns/manager_linux_test.go, net/dns/wsl_windows.go
Previously, if we had a umask set (e.g. 0027) that prevented creating a world-readable file, /etc/resolv.conf would be created without the o+r bit and thus other users may be unable to resolve DNS.
Since a umask only applies to file creation, chmod the file after creation and before renaming it to ensure that it has the appropriate permissions.
Updates #12609
Change-Id: I2a05d64f4f3a8ee8683a70be17a7da0e70933137
=> net/dns: ensure /etc/resolv.conf is world-readable even with a umask

ipn/ipnlocal/serve_test.go
We can observe a data race in tests when logging after a test is finished. `b.onHealthChange` is called in a goroutine after being registered with `health.Tracker.RegisterWatcher`, which calls callbacks in `setUnhealthyLocked` in a new goroutine.
See: https://github.com/tailscale/tailscale/actions/runs/9672919302/job/26686038740
Updates #12054
Change-Id: Ibf22cc994965d88a9e7236544878d5373f91229e
=> ipn/ipnlocal: fix data race in tests

health/health.go, health/health_test.go, health/state.go, health/warnings.go
Creates and exposes a 'fake' warnable that persists for the first 5 seconds of lifetime of the backend. This is used to silence spurious warnings while the backend is starting up.
=> health: add warming-up warnable
